### PR TITLE
Apply escaping args to other command shells

### LINKED ISSUE #19636: NoMethodError undefined method `escape_arg'
## Steps to reproduce

1. Got a session with an `ssh_login` module shell on Ubuntu 22.04
2. Used https://github.com/rapid7/metasploit-framework/pull/19625
3. crash

## Current behavior

```
[*] Finished creating exploit source zip, uploading...
[*] Max line length is 65537
[*] Writing 2186825 bytes in 134 chunks of 60512 bytes (octal-encoded), using printf
[-] Exploit failed: NoMethodError undefined method `escape_arg' for #<Session:shell 1.1.1.1:22 (192.168.10.110) "SSH h00die@ ">
[*] Exploit completed, but no session was created.
```

### Metasploit version

Framework: 6.4.36-dev-88132657d2
Console  : 6.4.36-dev-88132657d2

### PR DESCRIPTION
**Pull request by smashery**
This adds `escape_args` method to all CommandShells, and more specifically, finds the appropriate OS escaping routines for an SSH server (usually Unix presumably, but possibly Windows).

Resolves #19636

## Verification

- [ ] Start `msfconsole`
- [ ] `auxiliary/scanner/ssh/ssh_login`
- [ ] Create a session on a target host
- [ ] Launch a post exploitation module (just to set up `irb` correctly)
- [ ] For example: `use netfilter_priv_esc_ipv4`
- [ ] `set session 1` (again to set up `irb`)
- [ ] `irb`
- [ ] `write_file('/tmp/test','data')
- [ ] `write_file('/tmp/test "quotes"', 'hi')`
- [ ] **Verify** that it successfully writes the files, correctly escaping the quotes (previously it would fail with the `escape_arg` error)

### CODE REVIEW

**Comment by adfoster-r7** [comment]
Not a blocker to this PR; Looks like it'd be worth us expanding our [acceptance tests](https://github.com/rapid7/metasploit-framework/tree/4a13b09767c3f7f91b0b0169e53dad99ff9fa504/spec/acceptance#acceptance-tests) to include ssh modules in the future :+1:

File: lib/msf/base/sessions/ssh_command_shell_bind.rb [hunk 1]
```diff
@@ -238,6 +238,11 @@ def initialize(ssh_connection, opts = {})
     def bootstrap(datastore = {}, handler = nil)
       # this won't work after the rstream is initialized, so do it first
       @platform = Metasploit::Framework::Ssh::Platform.get_platform(ssh_connection)
+      if @platform == 'windows'
+        extend(Msf::Sessions::WindowsEscaping)
+      else
+        extend(Msf::Sessions::UnixEscaping)
+      end
```
Comment (jvoisin) [inline lib/msf/base/sessions/ssh_command_shell_bind.rb:245]: Are you sure there are no other possibilities besides Windows and Unix wrt. shell escaping?

File: lib/msf/base/sessions/unix_escaping.rb [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+    def shell_command_token(cmd,timeout = 10)
+      shell_command_token_unix(cmd,timeout)
+    end
+
+    # Convert the executable and argument array to a command that can be run in this command shell
+    # @param cmd_and_args [Array<String>] The process path and the arguments to the process
+    def to_cmd(cmd_and_args)
+      escaped = cmd_and_args.map do |arg|
+        escape_arg(arg)
+      end
```
Comment (jvoisin) [inline lib/msf/base/sessions/unix_escaping.rb:12]:
```suggestion
      escaped = cmd_and_args.map { |arg| escape_arg(arg) }
```

I think this syntax is a bit more idiomatic

File: lib/msf/base/sessions/ssh_command_shell_bind.rb (hunk 1 above)
Comment (smashery) [reply lib/msf/base/sessions/ssh_command_shell_bind.rb:245]: From https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/ssh/platform.rb#L97-L132, I'm really not all that familiar with what exactly to expect shell-escaping-wise when you get (for example) an "arista" shell. If it's some custom shell completely unrelated to anything POSIX, then any of the behaviour that uses `escape_arg` (such as uploading files or launching processes) would be useless anyway and would need its entirely new implementation.

In those cases, I'm not sure what the best default would be. The alternative I guess would be better in those unknown cases to just not extend the object, and do no escaping.

Comment (msutovsky-r7) [reply lib/msf/base/sessions/ssh_command_shell_bind.rb:245]: From my very brief analysis, the current state should easily cover all platforms except **Cisco ios**, **Juniper**, **Mikrotik**, **Arista** and **vcenter** - I'm not 100% sure how those shells work when it comes to character escaping. So the options are: add `else` for all above mentioned and just implement escaping for them later on with more thorough analysis or ignore it, hope for best and add at least `else` block for **Unknown** platform. We will probably have to create/extend tests for SSH sessions (though I'm not very familiar how they are implemented now, but I don't expect such cases are covered there).

**Review by msutovsky-r7 — COMMENTED** [review]
Hi @smashery, I added some comments.

**Comment by smashery** [comment]
Modified to avoid escaping on those platforms @msutovsky-r7.

File: lib/msf/base/sessions/ssh_command_shell_bind.rb [hunk 3]
```diff
@@ -240,7 +240,7 @@ def bootstrap(datastore = {}, handler = nil)
       @platform = Metasploit::Framework::Ssh::Platform.get_platform(ssh_connection)
       if @platform == 'windows'
         extend(Msf::Sessions::WindowsEscaping)
-      else
+      elsif Metasploit::Framework::Ssh::Platform.is_posix(@platform)
         extend(Msf::Sessions::UnixEscaping)
```
Comment (msutovsky-r7) [inline lib/msf/base/sessions/ssh_command_shell_bind.rb:244]: This looks much better! Maybe one small additional detail would be adding `else` branch with some message/exception to cover those cases where the platform is not posix - but otherwise, it's all great.

**Review by msutovsky-r7 — COMMENTED** [review]
Thanks @smashery, it looks great! I just left one comment that would probably needed to be addressed, otherwise I don't have any additional comments.

**Comment by msutovsky-r7** [comment]
Hey @smashery just wanted to ping you, there's one detail left on this PR before it can be landed. Otherwise, it's all good

**Review by msutovsky-r7 — APPROVED** [review]

**Comment by bwatters-r7** [comment]
# Release Notes
This adds an escape_args method to all CommandShells that finds the appropriate OS escaping routines for an SSH server.
