### PR TITLE
Makes improvements to enum_computers module

### LINKED ISSUE #17920: post/windows/gather/enum_computers: many bugs
Cleaning up my dev box. I started refactoring this but lost interest. Leaving the diff and a non-exhaustive list of bugs here.

---

The module description is a lie.

https://github.com/rapid7/metasploit-framework/blob/0436e8bad998d035e6558ebcbb2e878eaf898ce6/modules/post/windows/gather/enum_computers.rb#L17

The module uses `net view` which lists the computers on the current domain *or network*. It also works only when the network profile permits network sharing - otherwise `net view` will return error 6118.

Although the module retrieves the domain name, this is used only to verify that the host is part of a domain (see below). Also, why would we not want a list of all identifiable computers regardless of whether they are domain joined?

Also, we already have the `enum_ad_computers` module to enumerate computers on the Active Directory domain:

* https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/enum_ad_computers.rb

---

The module only supports Meterpreter sessions.

https://github.com/rapid7/metasploit-framework/blob/0436e8bad998d035e6558ebcbb2e878eaf898ce6/modules/post/windows/gather/enum_computers.rb#L22

Meterpreter functionality is only used for hostname IP address resolution. There's no reason that this module can't resolve IP addresses on other session types, and even if it couldn't we could simply enumerate only the computer names without IP resolution:

```ruby
  def resolve_host(host)
    return host if Rex::Socket.dotted_ip?(host)

    return unless client.respond_to?(:net)

    vprint_status("Resolving host #{host}")

    result = client.net.resolve.resolve_host(host)

    return if result[:ip].blank?

    result[:ip]
  end
```

---

There are many problems with the `get_domain_computers` method.

https://github.com/rapid7/metasploit-framework/blob/0436e8bad998d035e6558ebcbb2e878eaf898ce6/modules/post/windows/gather/enum_computers.rb#L54-L68

The `# List Members of a domain group` code comment is a lie. This module has nothing to do with domain groups.

The module uses `net view`. It does not use the `/domain` flag, which is fine because we might want to list all hosts regardless of whether they are domain joined (see above).

The parsing is extremely brittle and locale dependent. It is unlikely to work on non-English systems.

```
net help view
The syntax of this command is:

NET VIEW
[\\computername [/CACHE] | [/ALL] | /DOMAIN[:domainname]]
NET VIEW /NETWORK:NW [\\computername]

NET VIEW displays a list of resources being shared on a computer. When used
without options, it displays a list of computers in the current domain or
network.

\\computername             Is a computer whose shared resources you want 
                           to view.
/DOMAIN:domainname         Specifies the domain for which you want to 
                           view the available computers. If domainname is
                           omitted, displays all domains in the local area
                           network.
/NETWORK:NW                Displays all available servers on a NetWare 
                           network. If a computername is  specified, the
                           resources available on that computer in 
                           the NetWare network will be displayed.
/CACHE                     Displays the offline client caching settings for
                           the resources on the specified computer
/ALL			         Displays all the shares including the $ shares
```

---

The `get_domain` method can easily be replaced with `get_domain_name` from Post libs (see diff below).

https://github.com/rapid7/metasploit-framework/blob/0436e8bad998d035e6558ebcbb2e878eaf898ce6/modules/post/windows/gather/enum_computers.rb#L70-L83

---

The `list_computers` method takes a domain name as an argument but does nothing with it except print it. Thus any identified host which is not domain joined will be printed as part of the domain, and the table name "List of Domain Hosts for the primary Domain" is a lie.

https://github.com/rapid7/metasploit-framework/blob/0436e8bad998d035e6558ebcbb2e878eaf898ce6/modules/post/windows/gather/enum_computers.rb#L85-L108

---

Diff:

```diff
diff --git a/modules/post/windows/gather/enum_computers.rb b/modules/post/windows/gather/enum_computers.rb
index 5e176bec1d..a3a60891db 100644
--- a/modules/post/windows/gather/enum_computers.rb
+++ b/modules/post/windows/gather/enum_computers.rb
@@ -5,7 +5,7 @@
 
 class MetasploitModule < Msf::Post
   include Msf::Post::File
-
+  include Msf::Post::Windows::Accounts
   include Msf::Post::Windows::Registry
 
   def initialize(info = {})
@@ -14,12 +14,17 @@ class MetasploitModule < Msf::Post
         info,
         'Name' => 'Windows Gather Enumerate Computers',
         'Description' => %q{
-          This module will enumerate computers included in the primary Domain.
+          This module will enumerate computers included in the primary Active Directory domain.
         },
         'License' => MSF_LICENSE,
         'Author' => [ 'Joshua Abraham <jabra[at]rapid7.com>'],
         'Platform' => [ 'win'],
-        'SessionTypes' => [ 'meterpreter' ],
+        'SessionTypes' => %w[meterpreter powershell shell],
+        'Notes' => {
+          'Stability' => [CRASH_SAFE],
+          'Reliability' => [],
+          'SideEffects' => []
+        },
         'Compat' => {
           'Meterpreter' => {
             'Commands' => %w[
@@ -31,55 +36,49 @@ class MetasploitModule < Msf::Post
     )
   end
 
-  # Run Method for when run command is issued
   def run
-    print_status("Running module against #{sysinfo['Computer']}") if !sysinfo.nil?
-    domain = get_domain
-    if !domain.empty?
-      hostname_list = get_domain_computers
-      list_computers(domain, hostname_list)
+    hostname = sysinfo.nil? ? cmd_exec('hostname') : sysinfo['Computer']
+    print_status("Running module against #{hostname} (#{session.session_host})")
+
+    domain = get_domain_name
+
+    fail_with(Failure::Unknown, 'Could not retrieve domain name. Is the host part of a domain?') unless domain
+
+    netbios_domain_name = domain.split('.').first.upcase
+
+    hostname_list = get_domain_computers
+
+    if hostname_list.empty?
+      print_error('No computers found')
+      return
     end
+
+    list_computers(netbios_domain_name, hostname_list)
   end
 
   def gethost(hostname)
-    ## get IP for host
     vprint_status("Looking up IP for #{hostname}")
     result = client.net.resolve.resolve_host(hostname)
 
-    return nil if result[:ip].nil? || result[:ip].blank?
+    return if result[:ip].blank?
 
-    return result[:ip]
+    result[:ip]
   end
 
-  # List Members of a domain group
   def get_domain_computers
     computer_list = []
     devisor = "-------------------------------------------------------------------------------\r\n"
     raw_list = cmd_exec('net view').split(devisor)[1]
-    if raw_list =~ /The command completed successfully/
-      raw_list.sub!(/The command completed successfully\./, '')
-      raw_list.gsub!(/\\\\/, '')
-      raw_list.split(' ').each do |m|
-        computer_list << m
-      end
-    end
 
-    return computer_list
-  end
+    return [] unless raw_list.include?('The command completed successfully')
 
-  # Gets the Domain Name
-  def get_domain
-    domain = ''
-    begin
-      subkey = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Group Policy\\History'
-      v_name = 'DCName'
-      domain_dc = registry_getvaldata(subkey, v_name)
-      dom_info = domain_dc.split('.')
-      domain = dom_info[1].upcase
-    rescue StandardError
-      print_error('This host is not part of a domain.')
+    raw_list.sub!(/The command completed successfully\./, '')
+    raw_list.gsub!(/\\\\/, '')
+    raw_list.split(' ').each do |m|
+      computer_list << m
     end
-    return domain
+
+    computer_list
   end
 
   def list_computers(domain, hosts)
@@ -97,13 +96,13 @@ class MetasploitModule < Msf::Post
       hostip = gethost(hostname)
       tbl << [domain, hostname, hostip]
     end
-    results = tbl.to_s
-    print_line("\n" + results + "\n")
+
+    print_line("\n#{tbl}\n")
 
     report_note(
-      host: session,
-      type: 'domain.hosts',
-      data: tbl.to_csv
+      :host => session,
+      :type => 'domain.hosts',
+      :data => tbl.to_csv
     )
   end
 end
```

Updated module:

```ruby
##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##

class MetasploitModule < Msf::Post
  include Msf::Post::File
  include Msf::Post::Windows::Accounts
  include Msf::Post::Windows::Registry

  def initialize(info = {})
    super(
      update_info(
        info,
        'Name' => 'Windows Gather Enumerate Computers',
        'Description' => %q{
          This module will enumerate computers included in the primary Active Directory domain.
        },
        'License' => MSF_LICENSE,
        'Author' => [ 'Joshua Abraham <jabra[at]rapid7.com>'],
        'Platform' => [ 'win'],
        'SessionTypes' => %w[meterpreter powershell shell],
        'Notes' => {
          'Stability' => [CRASH_SAFE],
          'Reliability' => [],
          'SideEffects' => []
        },
        'Compat' => {
          'Meterpreter' => {
            'Commands' => %w[
              stdapi_net_resolve_host
            ]
          }
        }
      )
    )
  end

  def run
    hostname = sysinfo.nil? ? cmd_exec('hostname') : sysinfo['Computer']
    print_status("Running module against #{hostname} (#{session.session_host})")

    domain = get_domain_name

    fail_with(Failure::Unknown, 'Could not retrieve domain name. Is the host part of a domain?') unless domain

    netbios_domain_name = domain.split('.').first.upcase

    hostname_list = get_domain_computers

    if hostname_list.empty?
      print_error('No computers found')
      return
    end

    list_computers(netbios_domain_name, hostname_list)
  end

  def gethost(hostname)
    vprint_status("Looking up IP for #{hostname}")
    result = client.net.resolve.resolve_host(hostname)

    return if result[:ip].blank?

    result[:ip]
  end

  def get_domain_computers
    computer_list = []
    devisor = "-------------------------------------------------------------------------------\r\n"
    raw_list = cmd_exec('net view').split(devisor)[1]

    return [] unless raw_list.include?('The command completed successfully')

    raw_list.sub!(/The command completed successfully\./, '')
    raw_list.gsub!(/\\\\/, '')
    raw_list.split(' ').each do |m|
      computer_list << m
    end

    computer_list
  end

  def list_computers(domain, hosts)
    tbl = Rex::Text::Table.new(
      'Header' => 'List of Domain Hosts for the primary Domain.',
      'Indent' => 1,
      'Columns' =>
      [
        'Domain',
        'Hostname',
        'IPs',
      ]
    )
    hosts.each do |hostname|
      hostip = gethost(hostname)
      tbl << [domain, hostname, hostip]
    end

    print_line("\n#{tbl}\n")

    report_note(
      :host => session,
      :type => 'domain.hosts',
      :data => tbl.to_csv
    )
  end
end
```

### PR DESCRIPTION
**Pull request by cgranleese-r7**
This PR resolves #17920.

Thanks to @bcoles, as the majority of the changes are pulled from the diff added as part of this [issue](https://github.com/rapid7/metasploit-framework/issues/17920). I have _hopefully_ addressed all the comments that were part of the issue 🤞 

~A new mixin was added to add support for resolving hosts for modules that support multiple sessions. The idea was we would first check if we have access to `net` module as well as support for resolving hosts. If not we default to using `nslookup`.~

Removed the mixin for now and can circle back in a separate effort.

### Example output
```
msf6 post(windows/gather/enum_computers) > run

[*] Running module against DC1 (192.168.175.200)

List of identified Hosts.
=========================

 Domain  Hostname  IPs
 ------  --------  ---
 VB      DC1       192.168.175.200, 192.168.175.135


[*] Post module execution completed
```

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [ ] Test each of the three session types for the `post/windows/gather/enum_computers` module
- [ ] Meterpreter session
- [ ] Powershell session
- [ ] Shell session

### CODE REVIEW

File: lib/msf/core/post/dns/resolve_host.rb [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+
+            ip = result[:ip]
+          else
+            data = cmd_exec("nslookup #{host}")
+            if data =~ /Name/
+              # Remove unnecessary data and get the section with the addresses
+              returned_data = data.split(/Name:/)[1]
+              # check each element of the array to see if they are IP
+              returned_data.gsub(/\r\n\t |\r\n|Aliases:|Addresses:|Address:/, ' ').split(' ').each do |e|
+                if Rex::Socket.dotted_ip?(e)
```
Comment (adfoster-r7) [inline lib/msf/core/post/dns/resolve_host.rb:32]: is this method meant to handle ipv6 addresses?

Comment (cgranleese-r7) [reply lib/msf/core/post/dns/resolve_host.rb:32]: Ah I had lifted that snippet from here:
https://github.com/rapid7/metasploit-framework/blob/a81a71c5dfb493bb478809d7335fc39d601c3881/modules/post/multi/gather/dns_srv_lookup.rb#L166-L181

I forgot to remove that.

File: lib/msf/core/post/dns/resolve_host.rb [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+      #
+      # This module resolves session DNS
+      #
+      ###
+      module ResolveHost
+        # Takes the host name and makes use of nsloopup to resolve the IP
+        #
+        # @param [String] host Node for the ruby `send` method
+        # @return [String, nil] ip The resolved IP
+        def resolve_host(host)
```
Comment (adfoster-r7) [inline lib/msf/core/post/dns/resolve_host.rb:16]: Should we skip address lookup if the host is already a dotted ipv4/ipv6 address?

File: lib/msf/core/post/dns/resolve_host.rb [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+              returned_data.gsub(/\r\n\t |\r\n|Aliases:|Addresses:|Address:/, ' ').split(' ').each do |e|
+                if Rex::Socket.dotted_ip?(e)
+                  ip = e
+                end
+              end
+            end
+          end
+
+          if ip.nil?
+            print_error("Could not resolve IP for #{host}")
```
Comment (adfoster-r7) [inline lib/msf/core/post/dns/resolve_host.rb:40]: If I remember correctly mixin methods shouldn't log as they can't be turned off by the calling code - and might be extremely noisey in the context of some modules

File: lib/msf/core/post/dns/resolve_host.rb (hunk 1 above)
Comment (cgranleese-r7) [reply lib/msf/core/post/dns/resolve_host.rb:32]: I pulled that snippet from here:
https://github.com/rapid7/metasploit-framework/blob/a81a71c5dfb493bb478809d7335fc39d601c3881/modules/post/multi/gather/dns_srv_lookup.rb#L166-L181

I looked at that method and assumed it was fine as it just checked `Checks to see if the supplied address is in “dotted” form` for ipv6 or ipv4.

Should I handle that differently then?

File: lib/msf/core/post/dns/resolve_host.rb (hunk 3 above)
Comment (cgranleese-r7) [reply lib/msf/core/post/dns/resolve_host.rb:40]: Ah ok, should I just return a blank array as they did here?
https://github.com/rapid7/metasploit-framework/blob/a81a71c5dfb493bb478809d7335fc39d601c3881/modules/post/multi/gather/dns_srv_lookup.rb#L166-L181

File: lib/msf/core/post/dns/resolve_host.rb (hunk 2 above)
Comment (cgranleese-r7) [reply lib/msf/core/post/dns/resolve_host.rb:16]: Good idea, I could add a check at the top of that method to just return the host if it is already a dotted ipv4/ipv6 address 👍

Comment (bcoles) [reply lib/msf/core/post/dns/resolve_host.rb:16]: The lazy approach suggested in #17920 and used in `post/windows/gather/enum_domain` is:

https://github.com/rapid7/metasploit-framework/blob/1ef030df7604bf188f26485e066e7c76d3ab5faa/modules/post/windows/gather/enum_domain.rb#L38-L39

I'm not sure if this supports IPv6.

File: lib/msf/core/post/dns/resolve_host.rb [hunk 4]
```diff
@@ -0,0 +1,48 @@
+# -*- coding: binary -*-
+
+module Msf
+  class Post
+    module DNS
```
Comment (adfoster-r7) [inline lib/msf/core/post/dns/resolve_host.rb:5]: One for discussion, potentially `Net` to align with Meterpreter's API

```
stdapi_net_config_add_route	 	 	 	 	 	 	 	 	 	 	 	 
stdapi_net_config_get_arp_table	 	 	 	 	 	 	 	 	 	 	 	 
stdapi_net_config_get_interfaces	 	 	 	 	 	 	 	 	 	 	 	 
stdapi_net_config_get_netstat	 	 	 	 	 	 	 	 	 	 	 	 
stdapi_net_config_get_proxy	 	 	 	 	 	 	 	 	 	 	 	 
stdapi_net_config_get_routes	 	 	 	 	 	 	 	 	 	 	 	 
stdapi_net_config_remove_route	 	 	 	 	 	 	 	 	 	 	 	 
stdapi_net_resolve_host	 	 	 	 	 	 	 	 	 	 	 	 
stdapi_net_resolve_hosts	 	 	 	 	 	 	 	 	 	 	 	 
stdapi_net_socket_tcp_shutdown
```

Comment (cgranleese-r7) [reply lib/msf/core/post/dns/resolve_host.rb:5]: Yea, after our slack conversation I think removing the mixin for now and circling back to that makes the most sense. I added the method into the `post/windows/gather/enum_computers` module for now.

**Review by jheysel-r7 — COMMENTED** [review]
Looks good, just a couple minor comments. Once I got an environment setup everything worked out perfectly 👌 I was getting `System Error 6118 occurred` when running `net view` after I thought I had successfully joined my one computer to the domain.  This [blog](https://appuals.com/net-view-system-error-6118/) helped me get things working. 


Meterpreter
```
meterpreter > bg
msf6 exploit(windows/smb/psexec) > previous
msf6 post(windows/gather/enum_computers) > run

[*] Running module against WIN-FDV8QFUMFP7 (172.16.199.132) session type: meterpreter
[*] Looking up IP for COMPUTER1
[*] Looking up IP for WIN-FDV8QFUMFP7

List of identified Hosts.
=========================

 Domain   Hostname         IPs
 ------   --------         ---
 EXAMPLE  COMPUTER1        172.16.199.40
 EXAMPLE  WIN-FDV8QFUMFP7  172.16.199.132


[*] Post module execution completed
msf6 post(windows/gather/enum_computers) >
```

Powershell:
```
msf6 payload(windows/x64/powershell_reverse_tcp) > to_handler
[*] Payload Handler Started as Job 4

[*] Started reverse TCP handler on 172.16.199.1:4444
msf6 payload(windows/x64/powershell_reverse_tcp) > [*] Powershell session session 5 opened (172.16.199.1:4444 -> 172.16.199.132:64122) at 2023-10-05 17:19:47 -0400

msf6 payload(windows/x64/powershell_reverse_tcp) > previous
[*] Running module against WIN-FDV8QFUMFP7 (172.16.199.132) session type: powershell
[*] Looking up IP for COMPUTER1
[*] Looking up IP for WIN-FDV8QFUMFP7

List of identified Hosts.
=========================

 Domain   Hostname         IPs
 ------   --------         ---
 EXAMPLE  COMPUTER1        172.16.199.40
 EXAMPLE  WIN-FDV8QFUMFP7  172.16.199.132


[*] Post module execution completed
```


Shell: 
```
msf6 payload(windows/x64/shell/reverse_tcp) > [*] Sending stage (336 bytes) to 172.16.199.132
[*] Command shell session 1 opened (172.16.199.1:4444 -> 172.16.199.132:64158) at 2023-10-05 17:31:20 -0400

msf6 payload(windows/x64/shell/reverse_tcp) > previous
[-] There isn't a previous module at the moment
msf6 payload(windows/x64/shell/reverse_tcp) > previous
[-] There isn't a previous module at the moment
msf6 payload(windows/x64/shell/reverse_tcp) > use enum_computers
msf6 post(windows/gather/enum_computers) > rexploit
[*] Reloading module...

[*] Running module against WIN-FDV8QFUMFP7 (172.16.199.132) session type: shell

List of identified Hosts.
=========================

 Domain   Hostname         IPs
 ------   --------         ---
 EXAMPLE  COMPUTER1        172.16.199.40
 EXAMPLE  WIN-FDV8QFUMFP7  172.16.199.132


[*] Post module execution completed
```

File: modules/post/windows/gather/enum_computers.rb [hunk 5]
```diff
@@ -31,74 +36,87 @@ def initialize(info = {})
...
+    else
+      ip.join(', ')
+    end
   end
 
-  # List Members of a domain group
   def get_domain_computers
     computer_list = []
     devisor = "-------------------------------------------------------------------------------\r\n"
     raw_list = cmd_exec('net view').split(devisor)[1]
```
[the remark this answers is not in the document]
Comment (bcoles) [reply modules/post/windows/gather/enum_computers.rb:90]: > Suggestion (won't let me make a github suggestion across deleted lines):
> 
> ```
>     raw_list = cmd_exec('net view')
>     return [] unless raw_list.include?('The command completed successfully')
>     raw_list = raw_list.split(devisor)[1]
> ```
> 
> or if you wanted to print the system error returned by windows 🤷
> 
> ```
>   net_view_response = cmd_exec('net view')
>   if net_view_response.include?(/System error/)
>     print_error("The net view command failed with: #{net_view_response}")
>     return []
>   end
>   raw_list = net_view_response.split(devisor)[1]
> ```

This error handling will fail on non-English systems.

[the remark this answers is not in the document]
Comment (jheysel-r7) [reply modules/post/windows/gather/enum_computers.rb:90]: Correct @bcoles, thanks for the reminder there. The devisor will never be present if Windows returns an error, we should maybe be checking for that instead of the english words success / error.

File: modules/post/windows/gather/enum_computers.rb [hunk 6]
```diff
@@ -31,74 +36,87 @@ def initialize(info = {})
...
+      'Not resolvable'
+    else
+      ip.join(', ')
+    end
   end
 
-  # List Members of a domain group
   def get_domain_computers
     computer_list = []
     devisor = "-------------------------------------------------------------------------------\r\n"
```
[the remark this answers is not in the document]
Comment (cgranleese-r7) [reply modules/post/windows/gather/enum_computers.rb]: Thanks for the suggestion. I have updated it to now print an error if the devisor isn't present and to return a blank array.

File: modules/post/windows/gather/enum_computers.rb (hunk 5 above)
[the remark this answers is not in the document]
Comment (cgranleese-r7) [reply modules/post/windows/gather/enum_computers.rb]: Thanks for the suggestion. I have updated it to now print an error if the devisor isn't present and to return a blank array.

File: modules/post/windows/gather/enum_computers.rb (hunk 6 above)
[the remark this answers is not in the document]
Comment (cgranleese-r7) [reply modules/post/windows/gather/enum_computers.rb]: I didn't add anything for this comment as part of the commit as I'm not sure if it would return false positives or not. I'm happy to implement any changes you think would make sense here.

[the remark this answers is not in the document]
Comment (jheysel-r7) [reply modules/post/windows/gather/enum_computers.rb]: No worries - I went and tested on Windows 7 and the divisor was the width of the cmd prompt which is 80, should have done that in the first place. Seems good to leave as is.

**Comment by jheysel-r7** [comment]
Thanks for pushing those changes and for the PR @cgranleese-r7! Retested and everything looks good, landing now 👍

**Comment by jheysel-r7** [comment]
# Release Notes
This PR adds a variety of improvements to the enum_computers module including Shell and Powershell support as well as improvements when running on non-english systems.
