### PR TITLE
Fix RPORT tab completion crash when connected to remote dataservice

### LINKED ISSUE #15075: Crash When Tab Completing RPORT
## Steps to reproduce

```
 ~/git/metasploit-framework │ master ?18  ./msfconsole                                                             ✔ │ 2.7.2 Ruby 
[!] The following modules could not be loaded!..|
[!] 	/home/gwillcox/git/metasploit-framework/modules/auxiliary/gather/office365userenum.py
[!] Please see /home/gwillcox/.msf4/logs/framework.log for details.
                                                  
Call trans opt: received. 2-19-98 13:24:18 REC:Loc

     Trace program: running

           wake up, Neo...
        the matrix has you
      follow the white rabbit.

          knock, knock, Neo.

                        (`.         ,-,
                        ` `.    ,;' /
                         `.  ,'/ .'
                          `. X /.'
                .-;--''--.._` ` (
              .'            /   `
             ,           ` '   Q '
             ,         ,   `._    \
          ,.|         '     `-.;_'
          :  . `  ;    `  ` --,.._;
           ' `    ,   )   .'
              `._ ,  '   /_
                 ; ,''-,;' ``-
                  ``-..__``--`

                             https://metasploit.com


       =[ metasploit v6.0.41-dev-c79e6c6d6a               ]
+ -- --=[ 2122 exploits - 1137 auxiliary - 360 post       ]
+ -- --=[ 592 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 8 evasion                                       ]

Metasploit tip: To save all commands executed since start up 
to a file, use the makerc command

msf6 > use auxiliary/scanner/ssh/ssh_login
msf6 auxiliary(scanner/ssh/ssh_login) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf6 auxiliary(scanner/ssh/ssh_login) > set USERNAME test
USERNAME => test
msf6 auxiliary(scanner/ssh/ssh_login) > set PASSWORD test
PASSWORD => test
msf6 auxiliary(scanner/ssh/ssh_login) > set RPORT Traceback (most recent call last):
	28: from ./msfconsole:23:in `<main>'
	27: from /home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	26: from /home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	25: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:140:in `run'
	24: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:320:in `get_input_line'
	23: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/input/readline.rb:99:in `pgets'
	22: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/input/readline.rb:161:in `readline_with_output'
	21: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4875:in `readline'
	20: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4853:in `readline_internal'
	19: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4779:in `readline_internal_charloop'
	18: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4363:in `_rl_dispatch'
	17: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4374:in `_rl_dispatch_subseq'
	16: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6903:in `rl_complete'
	15: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6813:in `rl_complete_internal'
	14: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6329:in `gen_completion_matches'
	13: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/readline.rb:136:in `readline_attempted_completion_function'
	12: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:68:in `block in init_tab_complete'
	11: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:387:in `tab_complete'
	10: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:402:in `tab_complete_stub'
	 9: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:402:in `each'
	 8: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:413:in `block in tab_complete_stub'
	 7: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:454:in `tab_complete_helper'
	 6: from /home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1822:in `cmd_set_tabs'
	 5: from /home/gwillcox/git/metasploit-framework/lib/msf/ui/console/module_option_tab_completion.rb:155:in `tab_complete_option_values'
	 4: from /home/gwillcox/git/metasploit-framework/lib/msf/ui/console/module_option_tab_completion.rb:155:in `each_key'
	 3: from /home/gwillcox/git/metasploit-framework/lib/msf/ui/console/module_option_tab_completion.rb:157:in `block in tab_complete_option_values'
	 2: from /home/gwillcox/git/metasploit-framework/lib/msf/ui/console/module_option_tab_completion.rb:212:in `option_values_dispatch'
	 1: from /home/gwillcox/git/metasploit-framework/lib/msf/ui/console/module_option_tab_completion.rb:345:in `option_values_target_ports'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:134:in `method_missing': undefined method `has_host?' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x000055ac4cfbc8d8> (NoMethodError)
```

## Were you following a specific guide/tutorial or reading documentation?

Nope, just testing out some PRs

## Expected behavior

Should not tab complete, not enough information to make a suggestion.

## Current behavior

Crashes with a no-method related error 

### Metasploit version

v6.0.41-dev-c79e6c6d6a

### PR DESCRIPTION
**Pull request by agalway-r7**
Fixes https://github.com/rapid7/metasploit-framework/issues/15075

Removes usage of `has_host?`from the `option_values_target_ports` module of `module_option_tab_completion`. 

This is the last remaining use of the method in the code base, so I deleted the original method definition since it's breaking things and we don't want it being used in the future.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/ssh/ssh_login`
- [x] `set RHOSTS 1.1.1.1`
- [x] `set RPORT <TAB>`
- [x] Ensure that no error is thrown, and that a RPORT number is populated if appropriate

### CODE REVIEW

File: lib/msf/ui/console/module_option_tab_completion.rb [hunk 1]
```diff
@@ -338,15 +338,22 @@ def option_values_target_addrs(mod)
...
-          res = [ ]
-          return res if !framework.db.active
-          return res if !mod.datastore['RHOST']
+          res = []
+          return res unless framework.db.active
+          return res if mod.datastore['RHOST'].nil?
+
+          host_address = nil
+          framework.db.hosts.each do |h|
+            if h.address == mod.datastore['RHOST']
```
Comment (adfoster-r7) [inline lib/msf/ui/console/module_option_tab_completion.rb:347]: Does this need the same semantics as the previous ipv6 scope handling?

https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses_(with_zone_index)

File: lib/msf/ui/console/module_option_tab_completion.rb [hunk 2]
```diff
@@ -338,15 +338,22 @@ def option_values_target_addrs(mod)
...
         def option_values_target_ports(mod)
-          res = [ ]
-          return res if !framework.db.active
-          return res if !mod.datastore['RHOST']
+          res = []
+          return res unless framework.db.active
+          return res if mod.datastore['RHOST'].nil?
+
+          host_address = nil
+          framework.db.hosts.each do |h|
```
Comment (adfoster-r7) [inline lib/msf/ui/console/module_option_tab_completion.rb:346]: Looks like this will be less efficient than the previous implementation? 👀  Particularly with a large number of hosts in the database

File: lib/msf/core/db_manager/host.rb [hunk 3]
```diff
@@ -127,14 +127,6 @@ def get_host(opts)
   }
   end
 
-  # Look for an address across all comms
-  def has_host?(wspace,addr)
-  ::ApplicationRecord.connection_pool.with_connection {
-    address, scope = addr.split('%', 2)
-    wspace.hosts.find_by_address(addr)
```
Comment (adfoster-r7) [inline lib/msf/core/db_manager/host.rb:134]:
```
wspace.hosts.find_by_address(address)
```

**Comment by adfoster-r7** [comment]
Looks like this needs to handle the msfconsole crashing on tab completion still 👀

File: lib/msf/ui/console/module_option_tab_completion.rb [hunk 4]
```diff
@@ -213,9 +213,6 @@ def option_values_dispatch(mod, o, str, words)
                 res << port
               end
             end
-            if res.empty?
-              res << rand(1..65534).to_s
-            end
```
Comment (agalway-r7) [inline lib/msf/ui/console/module_option_tab_completion.rb:218]: Can anyone explain why we were returning a random port suggestion when we couldn't find one in the DB?

**Comment by gwillcox-r7** [comment]
Can confirm that with new changes this fixes the tab completion error. `master` was still crashing with the error shown in #15075, but testing on this PR had the following result:

```
msf6 > use auxiliary/scanner/ssh/ssh_login
msf6 auxiliary(scanner/ssh/ssh_login) > set RHOSTS 1.1.1.1
RHOSTS => 1.1.1.1
msf6 auxiliary(scanner/ssh/ssh_login) > set RPORT 22 
```

File: lib/msf/core/db_manager/host.rb [hunk 5]
```diff
@@ -127,14 +127,6 @@ def get_host(opts)
...
-  }
-  end
```
Comment (adfoster-r7) [inline lib/msf/core/db_manager/host.rb:136]: We talked about this on module hacking, and it seems like we'll want to keep this logic inside the the db_manager. Leaking concerns about databases into the layers of the metasploit console seems like something we'd want to avoid 👀 

Is it possible to keep this function here and wire it up properly? 🕵️

File: lib/msf/ui/console/module_option_tab_completion.rb [hunk 6]
```diff
@@ -338,19 +335,30 @@ def option_values_target_addrs(mod)
...
+          host_addresses = []
+          mod.datastore['RHOST'].split.each { |addr|
+            host_addresses << addr.split('%', 2)
+          }
 
-          framework.db.services.each do |service|
-            if service.host_id == host.id
+          hosts = []
+          host_addresses.each do |addr|
+            host = framework.db.get_host({:address => addr, :workspace => framework.db.workspace})
```
Comment (adfoster-r7) [inline lib/msf/ui/console/module_option_tab_completion.rb:349]: I wonder if this can use `hosts` directly? It appears to support filtering by address

https://github.com/rapid7/metasploit-framework/blob/0f433cf2ef739db5f7865ba4d5d36f301278873b/lib/msf/core/db_manager/host.rb#L139-L151

File: lib/rex/ui/text/input/readline.rb [hunk 7]
```diff
@@ -187,6 +188,19 @@ def readline_with_output(prompt, add_history=false)
...
+    def wrap_tab_compete_proc(proc)
+      Proc.new do |*args|
+        begin
+          proc.call(*args)
+        rescue => e
+          elog("tab_complete_proc has failed with args #{args}", error: e)
+          []
+        end
+      end
+    end
```
Comment (adfoster-r7) [inline lib/rex/ui/text/input/readline.rb:202]:
```suggestion
def wrap_tab_compete_proc(proc)
  proc do |*args|
    proc.call(*args)
  rescue StandardError => e
    elog("tab_complete_proc has failed with args #{args}", error: e)
    []
  end
end
```

File: lib/rex/ui/text/input/readline.rb [hunk 8]
```diff
@@ -187,6 +188,19 @@ def readline_with_output(prompt, add_history=false)
       end
     end
 
+    private
+
+    def wrap_tab_compete_proc(proc)
```
Comment (adfoster-r7) [inline lib/rex/ui/text/input/readline.rb:193]: `compete` ? 👀

Comment (adfoster-r7) [inline lib/rex/ui/text/input/readline.rb:193]: I wonder if there's a name that better captures the fact this is for error handling purposes?
`wrap_tab_compete_proc` is somewhat abstract. Maybe `with_error_handling(tab_complete_proc)` 🤔 

```suggestion
    def with_error_handling(proc)
```

File: lib/rex/ui/text/input/readline.rb [hunk 9]
```diff
@@ -17,17 +17,18 @@ class Input::Readline < Rex::Ui::Text::Input
...
       self.extend(::Readline)
 
-      if (tab_complete_proc)
+      if tab_complete_proc
         ::Readline.basic_word_break_characters = ""
-        ::Readline.completion_proc = tab_complete_proc
-        @rl_saved_proc = tab_complete_proc
+        ::Readline.completion_proc = wrap_tab_compete_proc(tab_complete_proc)
+
+        @rl_saved_proc = wrap_tab_compete_proc(tab_complete_proc)
```
Comment (adfoster-r7) [inline lib/rex/ui/text/input/readline.rb:31]: Looks like this wraps the _previous_ readline completion proc in a try/catch, not sure if that's what we want to happen here? 👀

File: lib/rex/ui/text/input/readline.rb [hunk 10]
```diff
@@ -36,7 +37,7 @@ def initialize(tab_complete_proc = nil)
     #
     def reset_tab_completion(tab_complete_proc = nil)
       ::Readline.basic_word_break_characters = "\x00"
-      ::Readline.completion_proc = tab_complete_proc || @rl_saved_proc
+      ::Readline.completion_proc = tab_complete_proc ? wrap_tab_compete_proc(tab_complete_proc) : @rl_saved_proc
```
Comment (adfoster-r7) [inline lib/rex/ui/text/input/readline.rb:40]: Just confirming, when does `reset_tab_completion` get called? Does it make sense to wrap? 🤔

File: lib/rex/ui/text/input/readline.rb (hunk 9 above)
Comment (agalway-r7) [reply lib/rex/ui/text/input/readline.rb:31]: No it's wrapping the `tab_complete_proc` that gets passed in with `initialize`. The previous `tab_complete_proc` is getting overwritten here

File: lib/rex/ui/text/input/readline.rb (hunk 10 above)
Comment (agalway-r7) [reply lib/rex/ui/text/input/readline.rb:40]: It makes sense to wrap because it can overwrite the existing `tab_complete_proc` method, and we want that wrapped in a error handling to avoid it crashing the console

File: lib/rex/ui/text/input/readline.rb [hunk 11]
```diff
@@ -17,17 +17,18 @@ class Input::Readline < Rex::Ui::Text::Input
     #
     # Initializes the readline-aware Input instance for text.
     #
-    def initialize(tab_complete_proc = nil)
+    def initialize(tab_complete_proc)
```
Comment (adfoster-r7) [inline lib/rex/ui/text/input/readline.rb:20]: Looks like this is a backwards breaking change? Was there an issue you were hitting that needed this to be removed? 👀

File: lib/msf/ui/console/module_option_tab_completion.rb [hunk 12]
```diff
@@ -338,19 +335,25 @@ def option_values_target_addrs(mod)
...
-          res = [ ]
-          return res if !framework.db.active
-          return res if !mod.datastore['RHOST']
+          return [] unless framework.db.active
+          return [] if mod.datastore['RHOST'].nil?
+
+          host_addresses = []
+          mod.datastore['RHOST'].split.each { |addr|
+            host_addresses << addr.split('%', 2)[0]
+          }
```
Comment (adfoster-r7) [inline lib/msf/ui/console/module_option_tab_completion.rb:344]:
```suggestion
host_addresses = mod.datastore['RHOST'].split.map do |addr|
  address, _scope = addr.split('%', 2)[0]
  address
end
```

File: lib/rex/ui/text/input/readline.rb (hunk 11 above)
Comment (agalway-r7) [reply lib/rex/ui/text/input/readline.rb:20]: No issue, more that it's only use I could find does pass in a `tab_complete_proc`, and Ideally we want a process to complete tabs. If there's a reason we want to keep the above I'm happy to undo

Comment (adfoster-r7) [reply lib/rex/ui/text/input/readline.rb:20]: I think holistically the API is sound enough that we can provide Input::Readline with the ability not to provide tab completion 🤷

File: lib/msf/ui/console/module_option_tab_completion.rb [hunk 13]
```diff
@@ -338,19 +335,25 @@ def option_values_target_addrs(mod)
...
-          res = [ ]
-          return res if !framework.db.active
-          return res if !mod.datastore['RHOST']
+          return [] unless framework.db.active
+          return [] if mod.datastore['RHOST'].nil?
+
+host_addresses = mod.datastore['RHOST'].split.map do |addr|
+  address, _scope = addr.split('%', 2)
+  address
+end
```
Comment (adfoster-r7) [inline lib/msf/ui/console/module_option_tab_completion.rb:344]: Indenting is a bit off here 👀

File: lib/rex/ui/text/input/readline.rb [hunk 14]
```diff
@@ -17,17 +17,18 @@ class Input::Readline < Rex::Ui::Text::Input
...
       self.extend(::Readline)
 
-      if (tab_complete_proc)
+      if tab_complete_proc
         ::Readline.basic_word_break_characters = ""
-        ::Readline.completion_proc = tab_complete_proc
-        @rl_saved_proc = tab_complete_proc
+        ::Readline.completion_proc = with_error_handling(tab_complete_proc)
+
+        @rl_saved_proc = with_error_handling(tab_complete_proc)
```
Comment (adfoster-r7) [inline lib/rex/ui/text/input/readline.rb:31]:
```suggestion
```suggestion
        @rl_saved_proc = with_error_handling(tab_complete_proc)
        ::Readline.completion_proc = @rl_saved_proc
```
```

File: lib/rex/ui/text/input/readline.rb (hunk 11 above)
Comment (adfoster-r7) [reply lib/rex/ui/text/input/readline.rb:20]:
```suggestion
    def initialize(tab_complete_proc = nil)
```

**Comment by adfoster-r7** [comment]
Tested with:
```
db_nmap 127.0.0.1
msfconsole
use auxiliary/scanner/ssh/ssh_login
set RHOSTS 127.0.0.1
set RPORT <TAB>

set RHOSTS 1.1.1.1
set RPOT <tab>
```

File: lib/rex/ui/text/input/readline.rb (hunk 11 above)
Comment (agalway-r7) [reply lib/rex/ui/text/input/readline.rb:20]: 👍

**Comment by adfoster-r7** [comment]
@msjenkins-r7 retest this please

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes a bug where msfconsole would crash when connected to a remote dataservice and tab completing possible RPORT values
