### PR TITLE
Fix crash when running http crawler with database connected

### LINKED ISSUE #18943: HTTP Crawler scanner - Psych::DisallowedClass Tried to load unspecified class: WEBrick::Cookie
## Steps to reproduce

How'd you do it?

1. use auxiliary/scanner/http/crawler
2. Running a default scan against Metasploitable2 sample VM on either port 80 or 8180 and obviously setting rhost

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Were you following a specific guide/tutorial or reading documentation?

No

## Expected behavior

Should output the URL's and associated http codes

## Current behavior

Starts working and then crashes out (below)
It starts off well...
```
[*] Crawling http://192.168.58.9:8180/...
[*] [00001/00500]    200 - 192.168.58.9 - http://192.168.58.9:8180/
[+] [00002/00500]    401 - 192.168.58.9 - http://192.168.58.9:8180/manager/status
[+] [00003/00500]    401 - 192.168.58.9 - http://192.168.58.9:8180/manager/html
```

### Metasploit version

Framework: 6.3.55-dev

## Additional Information

OS: Linux kali 6.6.9-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.9-1kali1 (2024-01-08) x86_64 GNU/Linux
Module causing crash: msf6 auxiliary(scanner/http/crawler)

```
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/suppressor.rb:54:in `save!'
/usr/share/metasploit-framework/lib/msf/core/db_manager/web.rb:158:in `block in report_web_page'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/share/metasploit-framework/lib/msf/core/db_manager/web.rb:110:in `report_web_page'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/web_data_proxy.rb:15:in `block in report_web_page'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in `data_service_operation'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/web_data_proxy.rb:14:in `report_web_page'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/report.rb:360:in `report_web_page'
/usr/share/metasploit-framework/modules/auxiliary/scanner/http/crawler.rb:126:in `crawler_process_page'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/http_crawler.rb:203:in `block in crawl_target'
/usr/share/metasploit-framework/lib/anemone/core.rb:228:in `block in do_page_blocks'
/usr/share/metasploit-framework/lib/anemone/core.rb:227:in `each'
/usr/share/metasploit-framework/lib/anemone/core.rb:227:in `do_page_blocks'
/usr/share/metasploit-framework/lib/anemone/core.rb:166:in `block in run'
/usr/share/metasploit-framework/lib/anemone/core.rb:162:in `loop'
/usr/share/metasploit-framework/lib/anemone/core.rb:162:in `run'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/http_crawler.rb:223:in `crawl_target'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/http_crawler.rb:152:in `block in run'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.1/lib/timeout.rb:186:in `block in timeout'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.1/lib/timeout.rb:41:in `handle_timeout'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.1/lib/timeout.rb:195:in `timeout'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/http_crawler.rb:152:in `run'
/usr/share/metasploit-framework/modules/auxiliary/scanner/http/crawler.rb:44:in `run'
/usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:178:in `job_run_proc'
/usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:85:in `run_simple'
/usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:96:in `run_simple'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:86:in `block in cmd_run'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:68:in `block in each'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:163:in `<<'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:163:in `block (3 levels) in parse'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/rex-socket-0.1.55/lib/rex/socket/range_walker.rb:234:in `each_host'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:158:in `block (2 levels) in parse'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:120:in `each'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:120:in `block in parse'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:67:in `each'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:67:in `each'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:67:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:82:in `cmd_run'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:165:in `block in run'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:309:in `block in with_history_manager_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:306:in `with_history_manager_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:133:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
```

Framework: 6.3.55-dev
Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
OpenSSL: OpenSSL 3.1.4 24 Oct 2023
Install Root: /usr/share/metasploit-framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Other - Please specify

Example scan run on Metasploit Linux:

It starts off well...

```
[*] Crawling http://192.168.58.9:8180/...
[*] [00001/00500]    200 - 192.168.58.9 - http://192.168.58.9:8180/
[+] [00002/00500]    401 - 192.168.58.9 - http://192.168.58.9:8180/manager/status
[+] [00003/00500]    401 - 192.168.58.9 - http://192.168.58.9:8180/manager/html
[*] [00004/00500]    200 - 192.168.58.9 - http://192.168.58.9:8180/RELEASE-NOTES.txt
[*] [00005/00500]    200 - 192.168.58.9 - http://192.168.58.9:8180/tomcat-docs/changelog.html
[*] [00006/00500]    200 - 192.168.58.9 - http://192.168.58.9:8180/jsp-examples/
[*] [00007/00500]    200 - 192.168.58.9 - http://192.168.58.9:8180/servlets-examples/
[*] [00008/00500]    302 - 192.168.58.9 - http://192.168.58.9:8180/tomcat-docs -> http://192.168.58.9:8180/tomcat-docs/
[*] [00009/00500]    200 - 192.168.58.9 - http://192.168.58.9:8180/tomcat-docs/
[-] [00010/00500]    404 - 192.168.58.9 - http://192.168.58.9:8180/test/
[*] [00011/00500]    200 - 192.168.58.9 - http://192.168.58.9:8180/webdav/
```

and then crashes out... not always at the same point on the URL sequence...

The Crash:

```
[03/10/2024 13:23:05] [e(0)] core: Problem reporting web page - Psych::DisallowedClass Tried to load unspecified class: WEBrick::Cookie
[03/11/2024 04:52:53] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/exchange_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[03/11/2024 04:52:53] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/onprem_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[03/11/2024 04:52:53] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/host_id.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[03/11/2024 04:55:16] [e(0)] core: Problem reporting web page - Psych::DisallowedClass Tried to load unspecified class: WEBrick::Cookie
[03/11/2024 04:55:34] [e(0)] core: Problem reporting web page - Psych::DisallowedClass Tried to load unspecified class: WEBrick::Cookie
[03/11/2024 05:01:18] [e(0)] core: Problem reporting web page - Psych::DisallowedClass Tried to load unspecified class: WEBrick::Cookie
[03/11/2024 05:19:44] [e(0)] core: Problem reporting web page - Psych::DisallowedClass Tried to load unspecified class: WEBrick::Cookie
[03/11/2024 05:33:35] [e(0)] core: Problem reporting web page - Psych::DisallowedClass Tried to load unspecified class: WEBrick::Cookie
[03/11/2024 05:35:25] [e(0)] core: Problem reporting web page - Psych::DisallowedClass Tried to load unspecified class: WEBrick::Cookie
Call stack:
/usr/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find'
/usr/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:424:in `resolve_class'
/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `block in register_empty'
/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `each'
/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `register_empty'
/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/usr/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/coders/yaml_column.rb:53:in `yaml_load'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/coders/yaml_column.rb:26:in `load'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/type/serialized.rb:22:in `deserialize'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activemodel-7.0.8/lib/active_model/type/helpers/mutable.rb:8:in `cast'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activemodel-7.0.8/lib/active_model/attribute.rb:179:in `type_cast'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activemodel-7.0.8/lib/active_model/attribute.rb:43:in `value'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activemodel-7.0.8/lib/active_model/attribute_set.rb:46:in `fetch_value'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:403:in `block in restore_transaction_record_state'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activemodel-7.0.8/lib/active_model/attribute_set.rb:93:in `transform_values'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activemodel-7.0.8/lib/active_model/attribute_set.rb:93:in `map'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:402:in `restore_transaction_record_state'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:334:in `rolledback!'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/transaction.rb:134:in `rollback_records'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/transaction.rb:312:in `block in rollback_transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/transaction.rb:309:in `rollback_transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/transaction.rb:325:in `rescue in block in within_new_transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/transaction.rb:322:in `block in within_new_transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:302:in `save!'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/suppressor.rb:54:in `save!'
/usr/share/metasploit-framework/lib/msf/core/db_manager/web.rb:158:in `block in report_web_page'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/share/metasploit-framework/lib/msf/core/db_manager/web.rb:110:in `report_web_page'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/web_data_proxy.rb:15:in `block in report_web_page'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in `data_service_operation'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/web_data_proxy.rb:14:in `report_web_page'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/report.rb:360:in `report_web_page'
/usr/share/metasploit-framework/modules/auxiliary/scanner/http/crawler.rb:126:in `crawler_process_page'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/http_crawler.rb:203:in `block in crawl_target'
/usr/share/metasploit-framework/lib/anemone/core.rb:228:in `block in do_page_blocks'
/usr/share/metasploit-framework/lib/anemone/core.rb:227:in `each'
/usr/share/metasploit-framework/lib/anemone/core.rb:227:in `do_page_blocks'
/usr/share/metasploit-framework/lib/anemone/core.rb:166:in `block in run'
/usr/share/metasploit-framework/lib/anemone/core.rb:162:in `loop'
/usr/share/metasploit-framework/lib/anemone/core.rb:162:in `run'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/http_crawler.rb:223:in `crawl_target'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/http_crawler.rb:152:in `block in run'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.1/lib/timeout.rb:186:in `block in timeout'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.1/lib/timeout.rb:41:in `handle_timeout'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.1/lib/timeout.rb:195:in `timeout'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/http_crawler.rb:152:in `run'
/usr/share/metasploit-framework/modules/auxiliary/scanner/http/crawler.rb:44:in `run'
/usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:178:in `job_run_proc'
/usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:85:in `run_simple'
/usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:96:in `run_simple'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:86:in `block in cmd_run'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:68:in `block in each'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:163:in `<<'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:163:in `block (3 levels) in parse'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/rex-socket-0.1.55/lib/rex/socket/range_walker.rb:234:in `each_host'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:158:in `block (2 levels) in parse'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:120:in `each'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:120:in `block in parse'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:67:in `each'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:67:in `each'
/usr/share/metasploit-framework/lib/msf/core/rhosts_walker.rb:67:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:82:in `cmd_run'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:165:in `block in run'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:309:in `block in with_history_manager_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:306:in `with_history_manager_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:133:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by adfoster-r7**
Fix crash when running http crawler with database connected with Ruby 3.1
Fixes https://github.com/rapid7/metasploit-framework/issues/18943

### Before

Target Metasploitable2 and see explosions:

```
msf6 auxiliary(scanner/http/crawler) > run rhost=192.168.123.133
[*] Running module against 192.168.123.133

[*] Crawling http://192.168.123.133:80/...
[*] [00001/00500]    200 - 192.168.123.133 - http://192.168.123.133/
[*] [00002/00500]    200 - 192.168.123.133 - http://192.168.123.133/twiki/
[*] [00003/00500]    200 - 192.168.123.133 - http://192.168.123.133/dav/
[*] [00004/00500]    200 - 192.168.123.133 - http://192.168.123.133/test/
[-] [00005/00500]    404 - 192.168.123.133 - http://192.168.123.133/tmp/
[-] [00006/00500]    404 - 192.168.123.133 - http://192.168.123.133/stuff/
[-] [00007/00500]    404 - 192.168.123.133 - http://192.168.123.133/awstats/
[-] [00008/00500]    404 - 192.168.123.133 - http://192.168.123.133/awstats/awstats/
[-] [00009/00500]    404 - 192.168.123.133 - http://192.168.123.133/basilic/
[-] [00010/00500]    404 - 192.168.123.133 - http://192.168.123.133/cacti/
[-] [00011/00500]    404 - 192.168.123.133 - http://192.168.123.133/docs/text/manual.txt
[*] [00012/00500]    200 - 192.168.123.133 - http://192.168.123.133/phpMyAdmin/
[-] Crawler Exception: http://192.168.123.133:80/ Tried to load unspecified class: WEBrick::Cookie ["/Users/adfoster/.rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/psych/class_loader.rb:99:in  .... etc...
```

### After

Working

```
msf6 auxiliary(scanner/http/crawler) > run rhost=192.168.123.133
[*] Running module against 192.168.123.133

[*] Crawling http://192.168.123.133:80/...
[*] [00001/00500]    200 - 192.168.123.133 - http://192.168.123.133/
[*] [00002/00500]    200 - 192.168.123.133 - http://192.168.123.133/twiki/
[*] [00003/00500]    200 - 192.168.123.133 - http://192.168.123.133/dav/
[*] [00004/00500]    200 - 192.168.123.133 - http://192.168.123.133/test/
[-] [00005/00500]    404 - 192.168.123.133 - http://192.168.123.133/tmp/
[-] [00006/00500]    404 - 192.168.123.133 - http://192.168.123.133/stuff/
[-] [00007/00500]    404 - 192.168.123.133 - http://192.168.123.133/awstats/
[*] [00008/00500]    200 - 192.168.123.133 - http://192.168.123.133/phpMyAdmin/
[*]                         FORM: POST /phpMyAdmin/index.php
[*]                         FORM: POST /phpMyAdmin/index.php
...etc...
```

### CODE REVIEW

File: lib/metasploit/framework/common_engine.rb [hunk 1]
```diff
@@ -43,6 +43,11 @@ module Metasploit::Framework::CommonEngine
     if ActiveRecord.respond_to?(:legacy_connection_handling=)
       ActiveRecord.legacy_connection_handling = false
     end
+
+    # @see https://github.com/rapid7/metasploit_data_models/blob/54a17149d5ccd0830db742d14c4987b48399ceb7/lib/metasploit_data_models/yaml.rb#L10
+    # @see https://github.com/rapid7/metasploit_data_models/blob/54a17149d5ccd0830db742d14c4987b48399ceb7/lib/metasploit_data_models/base64_serializer.rb#L28-L31
+    ActiveRecord.yaml_column_permitted_classes += MetasploitDataModels::YAML::PERMITTED_CLASSES
```
Comment (jmartin-tech) [inline lib/metasploit/framework/common_engine.rb:49]: A minor nit-pick, consider:

```suggestion
    ActiveRecord.yaml_column_permitted_classes = (ActiveRecord.yaml_column_permitted_classes + MetasploitDataModels::YAML::PERMITTED_CLASSES).uniq
```

Just to avoid duplication as the existing pattern results in two reference to `Symbol` in the array:

```
>> ActiveRecord.yaml_column_permitted_classes
=>
[Symbol,
 Range,
 Set,
 Symbol,
 Time,
 :"WEBrick::Cookie",
 :"ActionController::Parameters",
 :"ActiveModel::Attribute::FromDatabase",
 :"ActiveModel::Attribute::FromUser",
 :"ActiveModel::Attribute::WithCastValue",
 :"ActiveModel::Type::Boolean",
 :"ActiveModel::Type::Integer",
 :"ActiveModel::Type::String",
 :"ActiveRecord::Coders::JSON",
 :"ActiveSupport::TimeWithZone",
 :"ActiveSupport::TimeZone",
 :"ActiveRecord::Type::Serialized",
 :"ActiveRecord::Type::Text",
 :"ActiveSupport::HashWithIndifferentAccess",
 :"Mdm::Workspace"]
```

**Review by jmartin-tech — APPROVED** [review]
This seems a reasonable location to set this value consistently for Framework.

Minor optional nit-pick noted.

**Comment by dwelch-r7** [comment]
# Release Notes

Fixes crash when running http crawler with database connected
