### PR TITLE
Fix ActiveRecord error when reporting failures with file-based RHOSTS

### LINKED ISSUE #20556: ActiveRecord error when reporting failures with file-based RHOSTS
## Steps to reproduce

How'd you do it?

1.  `echo 127.0.0.1 > targets.txt`
2. `msfconsole -q -x 'use auxiliary/scanner/smb/smb_login; run RHOSTS=file:targets.txt SMBUser=bad SMBPass=bad; exit'`

Any `RHOSTS=file` scanner will trigger this, if there are any unsuccessful attempts.

## Expected behavior

I'd expect a failed logon attempt shown via STDOUT.

## Current behavior

Instead, we see the following output:

```bash
$ msfconsole -q -x 'use auxiliary/scanner/smb/smb_login; run RHOSTS=file:targets.txt SMBUser=bad SMBPass=bad; exit'
[*] New in Metasploit 6.4 - The CreateSession option within this module can open an interactive session
[*] 127.0.0.1:445         - 127.0.0.1:445 - Starting SMB login bruteforce
[-] 127.0.0.1:445         - 127.0.0.1:445 - Could not connect
[*] Scanned 1 of 1 hosts (100% complete)
[*] Bruteforce completed, 0 credentials were successful.
[*] You can open an SMB session with these credentials and CreateSession set to true
[-] Auxiliary failed: ActiveRecord::StatementInvalid PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type inet: "file:targets.txt"

[-] Call stack:
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in 'PG::Connection#exec_params'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in 'block (2 levels) in ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#exec_no_cache'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:1004:in 'block in ActiveRecord::ConnectionAdapters::AbstractAdapter#with_raw_connection'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activesupport-7.2.2.1/lib/active_support/concurrency/null_lock.rb:9:in 'ActiveSupport::Concurrency::NullLock#synchronize'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:976:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#with_raw_connection'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:893:in 'block in ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#exec_no_cache'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activesupport-7.2.2.1/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:1119:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter#log'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:892:in 'ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#exec_no_cache'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:872:in 'ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#execute_and_clear'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:66:in 'ActiveRecord::ConnectionAdapters::PostgreSQL::DatabaseStatements#internal_exec_query'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:647:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#select'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:73:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#select_all'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:251:in 'ActiveRecord::ConnectionAdapters::QueryCache#select_all'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/querying.rb:70:in 'ActiveRecord::Querying#_query_by_sql'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation.rb:1431:in 'block (2 levels) in ActiveRecord::Relation#exec_main_query'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:415:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_handling.rb:296:in 'ActiveRecord::ConnectionHandling#with_connection'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation.rb:1430:in 'block in ActiveRecord::Relation#exec_main_query'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation.rb:1452:in 'ActiveRecord::Relation#skip_query_cache_if_necessary'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation.rb:1414:in 'ActiveRecord::Relation#exec_main_query'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation.rb:1392:in 'block in ActiveRecord::Relation#exec_queries'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation.rb:1452:in 'ActiveRecord::Relation#skip_query_cache_if_necessary'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation.rb:1386:in 'ActiveRecord::Relation#exec_queries'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/association_relation.rb:44:in 'ActiveRecord::AssociationRelation#exec_queries'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation.rb:1167:in 'ActiveRecord::Relation#load'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation.rb:336:in 'ActiveRecord::Relation#records'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation.rb:331:in 'ActiveRecord::Relation#to_ary'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation/finder_methods.rb:615:in 'ActiveRecord::FinderMethods#find_nth_with_limit'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation/finder_methods.rb:600:in 'ActiveRecord::FinderMethods#find_nth'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/relation/finder_methods.rb:177:in 'ActiveRecord::FinderMethods#first'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/exploit_attempt.rb:65:in 'Msf::DBManager::ExploitAttempt#report_exploit_failure'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/exploit_data_proxy.rb:17:in 'block in ExploitDataProxy#report_exploit_failure'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in 'Metasploit::Framework::DataService::DataProxy#data_service_operation'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/exploit_data_proxy.rb:15:in 'ExploitDataProxy#report_exploit_failure'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/module/failure.rb:69:in 'Msf::Module::Failure#report_failure'
```

### Metasploit version

`6.4.89-dev-` (though this affects the upstream latest as well, and prior versions going back to at least 6.4.87 or so)

## Additional Information

The `debug` output is voluminous, so I've included it here: https://gist.github.com/jeffmcjunkin/33b2e52d8a29574de265b2cab3cba579

### PR DESCRIPTION
**Pull request by jeffmcjunkin**
## Summary
Fixes a bug where Metasploit crashes with an ActiveRecord/PostgreSQL error when using multi-value RHOSTS (space-separated or file-based) and a module failure occurs during scanning.

## The Problem
When using multi-value RHOSTS formats like `RHOSTS="127.0.0.1 127.0.0.2"` or `RHOSTS=file:targets.txt` with scanner modules, if any failure occurs during scanning, the `report_failure` method attempts to save the entire RHOSTS string as a host address in the database, causing PostgreSQL's inet type validation to fail:

```
[-] Auxiliary failed: ActiveRecord::StatementInvalid PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type inet: "127.0.0.1 127.0.0.2"
```
or
```
[-] Auxiliary failed: ActiveRecord::StatementInvalid PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type inet: "file:targets.txt"
```

## Steps to Reproduce
```bash
# Method 1: Space-separated hosts
msfconsole -q -x 'use auxiliary/scanner/smb/smb_login; run RHOSTS="127.0.0.1 127.0.0.2" SMBUser=test SMBPass=test; exit'

# Method 2: File-based hosts
echo "127.0.0.1" > targets.txt
msfconsole -q -x 'use auxiliary/scanner/smb/smb_login; run RHOSTS=file:targets.txt SMBUser=test SMBPass=test; exit'
```

## Root Cause
After scanning completes, `datastore['RHOST']` contains the original RHOSTS value (the full string with multiple hosts or file path) rather than an individual host address. The failure reporting code blindly passes this to the database as a host address.

## The Fix
This PR adds validation in `lib/msf/core/module/failure.rb` to only set the host field when `RHOST` contains a single valid host address, skipping multi-value strings and file paths.

### Code Changes

**Before** (`lib/msf/core/module/failure.rb` lines 58-60):
```ruby
    if self.datastore['RHOST'] && (self.options['RHOST'] || self.options['RHOSTS'])
      info[:host] = self.datastore['RHOST']
    end
```

**After** (`lib/msf/core/module/failure.rb` lines 58-65):
```ruby
    if self.datastore['RHOST'] && (self.options['RHOST'] || self.options['RHOSTS'])
      # Only include RHOST if it's a single valid host, not a multi-value string or file path
      rhost = self.datastore['RHOST'].to_s
      # Check if RHOST is not a file path and doesn't contain spaces (multiple hosts)
      unless rhost.start_with?('file:') || rhost.include?(' ')
        info[:host] = rhost
      end
    end
```

## Testing
Tested with various scanner modules and RHOSTS formats:
- Space-separated multiple hosts: `RHOSTS="10.0.0.1 10.0.0.2 10.0.0.3"`
- File-based hosts: `RHOSTS=file:targets.txt`
- CIDR ranges: `RHOSTS=192.168.1.0/24`
- Single hosts: `RHOSTS=192.168.1.1` (still works correctly)

## Verification
Before fix:
```bash
msf> use auxiliary/scanner/smb/smb_login
msf> run RHOSTS="127.0.0.1 127.0.0.2" SMBUser=test SMBPass=test
[*] 127.0.0.1:445 - Could not connect
[*] 127.0.0.2:445 - Could not connect
[-] Auxiliary failed: ActiveRecord::StatementInvalid PG::InvalidTextRepresentation: ERROR: invalid input syntax for type inet: "127.0.0.1 127.0.0.2"
```

After fix:
```bash
msf> use auxiliary/scanner/smb/smb_login
msf> run RHOSTS="127.0.0.1 127.0.0.2" SMBUser=test SMBPass=test
[*] 127.0.0.1:445 - Could not connect
[*] 127.0.0.2:445 - Could not connect
[*] Auxiliary module execution completed
```

Fixes #20556

### CODE REVIEW

**Review by jeffmcjunkin — COMMENTED** [review]
Added a path for `set RHOSTS 127.0.0.1 127.0.0.2`, since that will also trigger ActiveRecord and a stack trace.

File: lib/msf/core/module/failure.rb [hunk 1]
```diff
@@ -56,9 +56,14 @@ def report_failure
     info[:target_name] = self.target.name if self.respond_to?(:target)
 
     if self.datastore['RHOST'] && (self.options['RHOST'] || self.options['RHOSTS'])
-      info[:host] = self.datastore['RHOST']
+      # Only include RHOST if it's a single valid host, not a multi-value string or file path
+      rhost = self.datastore['RHOST'].to_s
+      # Check if RHOST is not a file path and doesn't contain spaces (multiple hosts)
+      unless rhost.start_with?('file:') || rhost.include?(' ')
```
Comment (smcintyre-r7) [inline lib/msf/core/module/failure.rb]: I think if we want to validate that the `rhost` string represents an IP address which is what ActiveRecord needs for the `host` field, we should use `Rex::Socket.is_ip_addr?` here. If `host` has to be an IPv4 address though, we'll need to use the more specific `Rex::Socket.is_ipv4?`.

```suggestion
      if Rex::Socket.is_ip_addr?(rhost)
```

**Review by msutovsky-r7 — COMMENTED** [review]
The fix is working:
```
resource (/home/ms/Desktop/r7-automation/auto_bug.rb)> run RHOSTS="127.0.0.1 127.0.0.2" SMBUser=test SMBPass=test
[*] 127.0.0.1:445         - 127.0.0.1:445 - Starting SMB login bruteforce
[+] 127.0.0.1:445         - 127.0.0.1:445 - Success: '.\test:test'
[*] Scanned 1 of 2 hosts (50% complete)
[*] 127.0.0.2:445         - 127.0.0.2:445 - Starting SMB login bruteforce
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanned 1 of 2 hosts (50% complete)
[+] 127.0.0.2:445         - 127.0.0.2:445 - Success: '.\test:test'
[*] Scanned 2 of 2 hosts (100% complete)
[*] Bruteforce completed, 2 credentials were successful.
[*] You can open an SMB session with these credentials and CreateSession set to true
[*] Auxiliary module execution completed
```
However, my concern is that we're losing part of information when `RHOSTS` is file-based or multi-IP string - would it make sense to somehow add parsing and report each IP individually?

**Comment by smcintyre-r7** [comment]
> would it make sense to somehow add parsing and report each IP individually?

I don't think so because if you were targeting say 5 IP addresses, but only one cause the exception to be raised (maybe it couldn't be connected to) then it wouldn't make sense to report it for each. We also don't have a way that I'm aware of to know which host that was being scanned caused the exception to be raised.

**Review by msutovsky-r7 — APPROVED** [review]

**Comment by msutovsky-r7** [comment]
# Release Notes

Fixes an issue in modules that had a multi-value `RHOSTS` value present which led to errors when reporting exploits. This resolves the issue by verifying that `RHOSTS` is a valid IP address.
