### PR TITLE
fix #17436: scanner/smb/smb_enumshares truncates file names

### LINKED ISSUE #17436: scanner/smb/smb_enumshares truncates file names
## Steps to reproduce

When running the `modules/auxiliary/scanner/smb/smb_enumshares.rb` module, large file names are truncated automatically 

```
msf6 auxiliary(scanner/smb/smb_enumshares) > run smbuser=foo smbpass=bar smbdomain=baz rhost=x.x.x.x spidershares=true showfiles=true 
... etc ...
 FILE  NTUSER.DAT{a0d1b9b4-af87-11e6-9658-...  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  524288
 FILE  NTUSER.DAT{a0d1b9b4-af87-11e6-9658-...  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  524288
... etc ...
[+] x.x.x.x:445       - info saved in: /home/kali/.msf4/loot/20230104205414_default_x.x.x.x_smb.enumshares_897937.txt
```

It's not possible to view the full file name, as it's truncated even before being placed into the generated csv file:

```
$ cat /home/kali/.msf4/loot/20230104205414_default_x.x.x.x_smb.enumshares_897937.txt

... etc ...
x.x.x.x\Users\etc\NTUSER.DAT{a0d1b9b4-af87-11e6-9658-...
x.x.x.x\Users\etc\NTUSER.DAT{a0d1b9b4-af87-11e6-9658-...
... etc ...
```

The stored file name should not be truncated when being saved to disk, potentially at all

The bug is here:
https://github.com/rapid7/metasploit-framework/blob/9d866a378481ff276b48cff0118df3b60d6ed87f/modules/auxiliary/scanner/smb/smb_enumshares.rb#L258-L259

## Expected behavior

No truncation in the written file

## Current behavior

Truncation

### Metasploit version

```
msf6 auxiliary(scanner/smb/smb_enumshares) > version
Framework: 6.2.33-dev-e9f86ce6e8
Console  : 6.2.33-dev-e9f86ce6e8
```

### PR DESCRIPTION
**Pull request by prabhatjoshi321**
Fixes #17436

This pull request is a fix for the issue #17436 meant for the module `auxiliary/scanner/smb/smb_enumshares.rb`. Previously It was not possible to view the full file name in the logged data, as it was truncated even before being placed into the txt file. The fix is done by shifting the logger function before the truncation code so that full pathnames get stored into the logged data.

The changes are applied in the branch "fix-issue_#17436"

## Verification

- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/smb/smb_enumshares`
- [x] `run smbuser=<username> smbpass=<password> smbdomain=<domain> rhost=<ip_of_smbserver> spidershares=true showfiles=true`
- [x] `exit`
- [x] `cat <the path to the generated file>`

The logged filenames can be seen as untruncated.

### CODE REVIEW

File: modules/auxiliary/scanner/smb/smb_enumshares.rb [hunk 1]
```diff
@@ -255,12 +255,14 @@ def get_files_info(ip, shares)
...
 
+          # Logging of the obtained data.
+          logdata << "#{ip}\\#{share_name}#{subdirs.first}\\#{fname.encode}\n"
+
           # Filename is too long for the UI table, cut it.
           fname = "#{fname[0, 35]}..." if fname.length > 35
 
           pretty_tbl << [fa || 'Unknown', fname, tcr, tac, twr, tch, sz]
           detailed_tbl << [ip.to_s, fa || 'Unknown', share_name, subdirs.first + '\\', fname, tcr, tac, twr, tch, sz]
-          logdata << "#{ip}\\#{share_name}#{subdirs.first}\\#{fname.encode}\n"
```
Comment (gwillcox-r7) [inline modules/auxiliary/scanner/smb/smb_enumshares.rb:263]: This isn't a bad solution but I see one other problem in that detailed_tbl is also saved to loot on line 273/275 of this output and at line 276/278. Therefore we would still have an issue with those lines of code logging a truncated version of `fname` to the logs.

Just something I noticed in addition to Alan's original comment when reviewing this.

We can safely ignore `pretty_tbl` since that is only printed out and is not saved to loot using `store_loot`.

**Review by gwillcox-r7 — CHANGES_REQUESTED** [review]
Overall a good solution. I did catch one edge case though upon review that will need addressing.

File: modules/auxiliary/scanner/smb/smb_enumshares.rb (hunk 1 above)
Comment (prabhatjoshi321) [reply modules/auxiliary/scanner/smb/smb_enumshares.rb:263]: Understood, thanks. Pushing the commits with the suggested changes.

**Comment by prabhatjoshi321** [comment]
Pushed the code with the changes. You may check now.

**Review by gwillcox-r7 — APPROVED** [review]

File: modules/auxiliary/scanner/smb/smb_enumshares.rb (hunk 1 above)
Comment (gwillcox-r7) [reply modules/auxiliary/scanner/smb/smb_enumshares.rb]: Resolved with https://github.com/rapid7/metasploit-framework/pull/17454/commits/2df39204325aedbd54ad34a73ae2d43cb51af6a0

**Comment by gwillcox-r7** [comment]
Seems to be working, here is the output from the loot file that is created showing the file name is not truncated:

image

I can also see the output is still truncated when pretty printed:

image

However the same output appears to be fine in the loot file, aka its not truncated:

image

This looks good to land, thanks for fixing this @prabhatjoshi321!

**Comment by prabhatjoshi321** [comment]
Thanks @gwillcox-r7.

**Comment by gwillcox-r7** [comment]
# Release Notes
A bug has been fixed whereby `smb_enumshares` incorrectly truncated file names before storing them into loot. This has been addressed so that only the console output will contain truncated file names, and the loot files will still contain the full file names for reference.
