### PR TITLE
Fix bad loop terminator checks and data checks in memcached_extractor.rb

### LINKED ISSUE #15975: auxiliary/gather/memcached_extractor type error
## Steps to reproduce

How'd you do it?

The server has ports 11211 and 11311 open, Nessus reported 11311 is memcached and can be queried.

I used the module `auxiliary/gather/memcached_extractor`, set the RHOST and ran it.

Didn't notice that the default in MSF is 11211 so ran the scan against that and got an error. Nessus and nmap not sure what is on 11211.

I tried again against an open and closed port to see if it was caused by either not getting any data back or getting something it didn't recognise, but both those gave nice errors rather than throwing an exception.

I've got access to the test box till at least the 20th for testing any fixes.

Changed the RPORT to 11311, ran again, and it worked fine.

## Expected behavior

No error

## Current behavior

Type error

```
msf6 auxiliary(gather/memcached_extractor) > run

[*] 1.2.3.4:11211    - Error: 1.2.3.4: TypeError no implicit conversion of nil into Array
[*] 1.2.3.4:11211    - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(gather/memcached_extractor) >
```

### Metasploit version

```
Framework: 6.0.47-dev
Console  : 6.0.47-dev
```

## Additional Information
If your version is less than `5.0.96`, please update to the latest version and ensure your issue is still present.

If the issue is encountered within `msfconsole`, please run the `debug` command using the instructions below. If the issue is encountered outisde `msfconsole`, or the issue causes `msfconsole` to crash on startup, please delete this section.

1. Start `msfconsole`
2. Run the command `set loglevel 3`
3. Take the steps necessary recreate your issue
4. Run the `debug` command
5. Copy all the output below the `===8<=== CUT AND PASTE EVERYTHING BELOW THIS LINE ===8<===` line and make sure to **REMOVE ANY SENSITIVE INFORMATION.**
6. Replace these instructions and the paragraph above with the output from step 5.

### PR DESCRIPTION
**Pull request by gwillcox-r7**
Fixes #15975 by adding in additional error handling and checks to break out of the loop

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use auxiliary/gather/memcached_extractor`
- [ ] Contact me for the target host.
- [ ] `set RHOST <IP of target>`
- [ ] `run`
- [ ] **Verify** that the program no longer errors out with the type conversion error.
- [ ] Test this on any other hosts n verify it still works correctly and that my additional code changes look correct.

### CODE REVIEW

File: modules/auxiliary/gather/memcached_extractor.rb [hunk 1]
```diff
@@ -57,9 +57,10 @@ def enumerate_keys
       loop do
         sock.send("stats cachedump #{sid} #{max_keys}\r\n", 0)
```
Comment (adfoster-r7) [inline modules/auxiliary/gather/memcached_extractor.rb:58]: Is this meant to be outside of the loop?

Comment (gwillcox-r7) [reply modules/auxiliary/gather/memcached_extractor.rb:58]: Hmm good point. Probably should be moved outside the loop, not sure why its inside the loop. Good catch

Comment (gwillcox-r7) [reply modules/auxiliary/gather/memcached_extractor.rb]: Fixed with https://github.com/rapid7/metasploit-framework/pull/16704/commits/5b6d9538cd1a047c4d2cde171665224556329e00, thanks for pointing this out @adfoster-r7 !

File: modules/auxiliary/gather/memcached_extractor.rb [hunk 2]
```diff
@@ -54,12 +54,13 @@ def localhost?(ip)
   def enumerate_keys
     keys = []
     enumerate_slab_ids.each do |sid|
+      sock.send("stats cachedump #{sid} #{max_keys}\r\n", 0)
```
Comment (jmartin-r7) [inline modules/auxiliary/gather/memcached_extractor.rb:57]: Does `max_keys` here end up a reason for iteration or is the response guaranteed to be all keys?

Comment (gwillcox-r7) [reply modules/auxiliary/gather/memcached_extractor.rb:57]: So according to https://elijaa.org/2010/12/24/understanding-memcached-stats-cachedump-command.html this is simply the maximum number of keys to dump however supposedly there may be a maximum return size of 1 MB, though given this command isn't documented and is part of the undocumented interface, there is speculation it may be 2 MB but not confirmed.

This is also noted at https://lzone.de/blog/How-to-Dump-Keys-from-Memcache where they note the following constraints:

1. You can only dump keys per slab class (keys with roughly the same content size)
2. You can only dump one page per slab class (1MB of data)
3. This is an unofficial feature that [might be removed anytime.](https://groups.google.com/forum/?fromgroups=#!topic/memcached/1-T8I-RVGKM)

Hopefully that helps explain things a bit here.

**Comment by cdelafuente-r7** [comment]
Thanks @gwillcox-r7 ! I verified it fixed the issue on faulty targets and also still work on normal ones. I'll go ahead and land it.
## Before the fix
```ruby
msf6 auxiliary(gather/memcached_extractor) > run verbose=true RHOSTS=<redacted>

[*] 123.207.184.223:11211 - Connecting to memcached server...
[+] 123.207.184.223:11211 - Connected to memcached version 2.5.1
[*] 123.207.184.223:11211 - Using lru_crawler to enumerate keys
[*] 123.207.184.223:11211 - Error: <redacted>: TypeError no implicit conversion of nil into Array
[*] 123.207.184.223:11211 - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

## With the fix
```ruby
msf6 auxiliary(gather/memcached_extractor) > run verbose=true RHOSTS=<redacted>

[*] 123.207.184.223:11211 - Connecting to memcached server...
[+] 123.207.184.223:11211 - Connected to memcached version 2.5.1
[*] 123.207.184.223:11211 - Using lru_crawler to enumerate keys
[+] 123.207.184.223:11211 - Found 0 keys
[*] 123.207.184.223:11211 - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by cdelafuente-r7** [comment]
# Release Notes
This fixes an issue when targeting some faulty `memcached` servers that return an error when extracting the keys and values stored in `slabs`. The module no longer errors out with a type conversion error.
