### PR TITLE
Fixes rhost_http_url crashes when running the check method

### LINKED ISSUE #14308: wp_admin_shell_upload - using rhost_http_url crashes when running the check method
## Steps to reproduce

Open msfconsole, ensure that you have `wordpress.jeff.thm` resolving to an IP. In my case I ran into this with the Tryhackme Jeff room:

```
features set RHOST_HTTP_URL true
use exploit/unix/webapp/wp_admin_shell_upload
set RHOST_HTTP_URL http://wordpress.jeff.thm/

check
```

This outputs the following error:
```
[-] Check failed: NoMethodError undefined method `split' for #<Hash:0x00005592b18970d0>
msf6 exploit(unix/webapp/wp_admin_shell_upload) >
```

When setting the value:

```
msf6 exploit(unix/webapp/wp_admin_shell_upload) > set RHOST_HTTP_URL http://wordpress.jeff.thm/

From: /home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:80 Msf::OptHTTPRhostURL#single_rhost?:

    78: def single_rhost?(value)
    79:   require 'pry'; binding.pry
 => 80:   return true if value =~ /[^-0-9,.*\/]/
    81:   walker = Rex::Socket::RangeWalker.new(value)
    82:   return false unless walker.valid?
    83:     # if there is only a single ip then it's not a range
    84:   walker.length == 1
    85: end

[1] pry(#<Msf::OptHTTPRhostURL>)> value
=> "http://wordpress.jeff.thm/"
```

But when running the `check` method:

```
msf6 exploit(unix/webapp/wp_admin_shell_upload) > check

From: /home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:80 Msf::OptHTTPRhostURL#single_rhost?:

    78: def single_rhost?(value)
    79:   require 'pry'; binding.pry
 => 80:   return true if value =~ /[^-0-9,.*\/]/
    81:   walker = Rex::Socket::RangeWalker.new(value)
    82:   return false unless walker.valid?
    83:     # if there is only a single ip then it's not a range
    84:   walker.length == 1
    85: end

[1] pry(#<Msf::OptHTTPRhostURL>)> value
=> "http://10.10.90.79/"
[2] pry(#<Msf::OptHTTPRhostURL>)> 
```

Which leads to the following error:
```
[-] Check failed: NoMethodError undefined method `split' for #<Hash:0x00005592b18970d0>
msf6 exploit(unix/webapp/wp_admin_shell_upload) >
```

## Were you following a specific guide/tutorial or reading documentation?

No, running through the Tryhackme Jeff room.

## Expected behavior

The check method runs, and doesn't crash.

## Current behavior

It crashes.

### Metasploit version

```
> version
Framework: 6.0.13-dev-65fcf67ca5
Console  : 6.0.13-dev-65fcf67ca5
```

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/ui/console]
ActiveModule=exploit/unix/webapp/wp_admin_shell_upload

[unix/webapp/wp_admin_shell_upload]
WORKSPACE=
VERBOSE=false
WfsDelay=0
EnableContextEncoding=false
ContextInformationFile=
DisablePayloadHandler=false
FileDropperDelay=
RHOSTS=wordpress.jeff.thm
RPORT=80
VHOST=wordpress.jeff.thm
SSL=false
Proxies=
RHOST_HTTP_URL=
UserAgent=Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
HttpUsername=
HttpPassword=
HttpRawHeaders=
DigestAuthIIS=true
SSLVersion=Auto
FingerprintCheck=true
DOMAIN=WORKSTATION
HttpClientTimeout=
HttpTrace=false
HttpTraceHeadersOnly=false
HttpTraceColors=red/blu
HTTP::uri_encode_mode=hex-normal
HTTP::uri_full_url=false
HTTP::pad_method_uri_count=1
HTTP::pad_uri_version_count=1
HTTP::pad_method_uri_type=space
HTTP::pad_uri_version_type=space
HTTP::method_random_valid=false
HTTP::method_random_invalid=false
HTTP::method_random_case=false
HTTP::version_random_valid=false
HTTP::version_random_invalid=false
HTTP::uri_dir_self_reference=false
HTTP::uri_dir_fake_relative=false
HTTP::uri_use_backslashes=false
HTTP::pad_fake_headers=false
HTTP::pad_fake_headers_count=0
HTTP::pad_get_params=false
HTTP::pad_get_params_count=16
HTTP::pad_post_params=false
HTTP::pad_post_params_count=16
HTTP::uri_fake_end=false
HTTP::uri_fake_params_start=false
HTTP::header_folding=false
TARGETURI=/
WPCONTENTDIR=wp-content
WPCHECK=true
USERNAME=
PASSWORD=
PAYLOAD=php/meterpreter/reverse_tcp
LHOST=192.168.246.234
URI=/
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
features set RHOST_HTTP_URL true
use exploit/unix/webapp/wp_admin_shell_upload
set RHOST_HTTP_URL http://wordpress.jeff.thm/

check
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[10/24/2020 11:23:11] [e(0)] core: Check Failed - NoMethodError undefined method `split' for #<Hash:0x00007f4b95cb98b8>
Call stack:
/var/lib/gems/2.7.0/gems/rex-socket-0.1.24/lib/rex/socket/range_walker.rb:79:in `parse'
/var/lib/gems/2.7.0/gems/rex-socket-0.1.24/lib/rex/socket/range_walker.rb:45:in `initialize'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:80:in `new'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:80:in `single_rhost?'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:70:in `get_uri'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:44:in `valid?'
/home/kali/metasploit-framework/lib/msf/core/data_store.rb:39:in `[]='
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:212:in `block in validate'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:200:in `each_pair'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:200:in `validate'
/home/kali/metasploit-framework/lib/msf/core/module/options.rb:21:in `validate'
/home/kali/metasploit-framework/lib/msf/base/simple/exploit.rb:194:in `check_simple'
/home/kali/metasploit-framework/lib/msf/base/simple/exploit.rb:217:in `check_simple'
/home/kali/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:229:in `check_simple'
/home/kali/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:147:in `cmd_check'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'
/home/kali/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/home/kali/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/kali/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/home/kali/metasploit-framework/msfconsole:23:in `<top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
[10/24/2020 11:23:42] [e(0)] core: Check Failed - NameError undefined local variable or method `binidng' for #<Msf::OptHTTPRhostURL:0x00007f4b952ee388>
Did you mean?  binding
Call stack:
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:79:in `single_rhost?'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:70:in `get_uri'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:44:in `valid?'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:201:in `block in validate'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:200:in `each_pair'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:200:in `validate'
/home/kali/metasploit-framework/lib/msf/core/module/options.rb:21:in `validate'
/home/kali/metasploit-framework/lib/msf/base/simple/exploit.rb:194:in `check_simple'
/home/kali/metasploit-framework/lib/msf/base/simple/exploit.rb:217:in `check_simple'
/home/kali/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:229:in `check_simple'
/home/kali/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:147:in `cmd_check'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'
/home/kali/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/home/kali/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/kali/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/home/kali/metasploit-framework/msfconsole:23:in `<top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
[10/24/2020 11:24:41] [e(0)] core: Check Failed - NoMethodError undefined method `split' for #<Hash:0x0000558e7ae33ec0>
Call stack:
/var/lib/gems/2.7.0/gems/rex-socket-0.1.24/lib/rex/socket/range_walker.rb:79:in `parse'
/var/lib/gems/2.7.0/gems/rex-socket-0.1.24/lib/rex/socket/range_walker.rb:45:in `initialize'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:81:in `new'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:81:in `single_rhost?'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:70:in `get_uri'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:44:in `valid?'
/home/kali/metasploit-framework/lib/msf/core/data_store.rb:39:in `[]='
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:212:in `block in validate'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:200:in `each_pair'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:200:in `validate'
/home/kali/metasploit-framework/lib/msf/core/module/options.rb:21:in `validate'
/home/kali/metasploit-framework/lib/msf/base/simple/exploit.rb:194:in `check_simple'
/home/kali/metasploit-framework/lib/msf/base/simple/exploit.rb:217:in `check_simple'
/home/kali/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:229:in `check_simple'
/home/kali/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:147:in `cmd_check'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'
/home/kali/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/home/kali/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/kali/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/home/kali/metasploit-framework/msfconsole:23:in `<top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
[10/24/2020 11:26:08] [e(0)] core: Check Failed - NoMethodError undefined method `split' for #<Hash:0x0000558e7aae3d10>
Call stack:
/var/lib/gems/2.7.0/gems/rex-socket-0.1.24/lib/rex/socket/range_walker.rb:79:in `parse'
/var/lib/gems/2.7.0/gems/rex-socket-0.1.24/lib/rex/socket/range_walker.rb:45:in `initialize'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:81:in `new'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:81:in `single_rhost?'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:70:in `get_uri'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:44:in `valid?'
/home/kali/metasploit-framework/lib/msf/core/data_store.rb:39:in `[]='
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:212:in `block in validate'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:200:in `each_pair'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:200:in `validate'
/home/kali/metasploit-framework/lib/msf/core/module/options.rb:21:in `validate'
/home/kali/metasploit-framework/lib/msf/base/simple/exploit.rb:194:in `check_simple'
/home/kali/metasploit-framework/lib/msf/base/simple/exploit.rb:217:in `check_simple'
/home/kali/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:229:in `check_simple'
/home/kali/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:147:in `cmd_check'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'
/home/kali/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/home/kali/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/kali/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/home/kali/metasploit-framework/msfconsole:23:in `<top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
[10/24/2020 11:27:10] [e(0)] core: Failed to connect to the database: No database YAML file
[10/24/2020 11:27:13] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[10/24/2020 11:27:13] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[10/24/2020 11:27:13] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[10/24/2020 11:27:13] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[10/24/2020 11:51:53] [e(0)] core: Check Failed - NoMethodError undefined method `split' for #<Hash:0x00005592b18970d0>
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
/usr/local/bin/bundle:23:in `<main>'
[10/24/2020 11:26:08] [e(0)] core: Check Failed - NoMethodError undefined method `split' for #<Hash:0x0000558e7aae3d10>
Call stack:
/var/lib/gems/2.7.0/gems/rex-socket-0.1.24/lib/rex/socket/range_walker.rb:79:in `parse'
/var/lib/gems/2.7.0/gems/rex-socket-0.1.24/lib/rex/socket/range_walker.rb:45:in `initialize'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:81:in `new'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:81:in `single_rhost?'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:70:in `get_uri'
/home/kali/metasploit-framework/lib/msf/core/opt_http_rhost_url.rb:44:in `valid?'
/home/kali/metasploit-framework/lib/msf/core/data_store.rb:39:in `[]='
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:212:in `block in validate'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:200:in `each_pair'
/home/kali/metasploit-framework/lib/msf/core/option_container.rb:200:in `validate'
/home/kali/metasploit-framework/lib/msf/core/module/options.rb:21:in `validate'
/home/kali/metasploit-framework/lib/msf/base/simple/exploit.rb:194:in `check_simple'
/home/kali/metasploit-framework/lib/msf/base/simple/exploit.rb:217:in `check_simple'
/home/kali/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:229:in `check_simple'
/home/kali/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:147:in `cmd_check'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'
/home/kali/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'
/home/kali/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/home/kali/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/kali/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/home/kali/metasploit-framework/msfconsole:23:in `<top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
[10/24/2020 11:27:10] [e(0)] core: Failed to connect to the database: No database YAML file
[10/24/2020 11:27:13] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[10/24/2020 11:27:13] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[10/24/2020 11:27:13] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[10/24/2020 11:27:13] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[10/24/2020 11:50:44] [d(0)] core: Reloading module exploit/unix/webapp/wp_admin_shell_upload...
[10/24/2020 11:50:44] [w(0)] core: The module unix/webapp/wp_admin_shell_upload is ambiguous with unix/webapp/wp_admin_shell_upload.
[10/24/2020 11:50:44] [d(0)] core: Refreshing unix/webapp/wp_admin_shell_upload of type: exploit
[10/24/2020 11:51:53] [e(0)] core: Check Failed - NoMethodError undefined method `split' for #<Hash:0x00005592b18970d0>
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.0.13-dev-65fcf67ca5
Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]
Install Root: /home/kali/metasploit-framework
Session Type: postgresql selected, no connection
Install Method: Git Clone
```

</details>

### PR DESCRIPTION
**Pull request by cgranleese-r7**
This PR Resolves #14308.

The crash was previously caused when the user enabled `features set RHOST_HTTP_URL true`, then when the check method is ran, it would crash and return this error message. 
```
[-] Check failed: NoMethodError undefined method `split' for #<Hash:0x00005592b18970d0>
```

Example of crash:
fix_rhost_crash_check_command_issue

This was caused due to a hash being passed in as `value` in `single_rhost?(value)`. The fix now checks if value is a hash in `get_uri` and sets it appropriately before it gets passed to `single_rhost?(value)`.

## Options used to recreated issue:
image

## Verification

Set-up for testing:
I edited my `/etc/hosts` to contain 
```
127.0.0.1       wordpress.jeff.thm
```
image

Test steps:

- [ ] Start `msfconsole`
- [ ] run `features set RHOST_HTTP_URL true`
- [ ] run `use exploit/unix/webapp/wp_admin_shell_upload`
- [ ] Set options - see above for options used 
- [ ] **Verify** the check method does not cause a crash

### CODE REVIEW

File: spec/lib/msf/core/opt_http_rhost_url_spec.rb [hunk 1]
```diff
@@ -35,4 +35,24 @@
...
+      { expected: false, value: {} },
+      { expected: false, value: '' }
+    ].each do |test|
+      context test[:value].to_s do
+        it "should return #{test[:expected]}" do
+          expect(subject.valid?(test[:value])).to eq(test[:expected])
+        end
+      end
+    end
+  end
```
Comment (adfoster-r7) [inline spec/lib/msf/core/opt_http_rhost_url_spec.rb:57]: Just needs rubocop 👀

Comment (cgranleese-r7) [reply spec/lib/msf/core/opt_http_rhost_url_spec.rb:57]: Done 👍

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes a crash when RHOST_HTTP_URL was used in conjunction with the check command. The RHOST_HTTP_URL option can be enabled with the command `features set RHOST_HTTP_URL true`.
