### PR TITLE
Fix #7610, cisco_ironport_enum falsely claimed connection failed.

### LINKED ISSUE #7610: Run auxiliary/scanner/http/cisco_ironport_enum and got good response and the module claimed connection failed.
## Steps to reproduce

```
msf > use auxiliary/scanner/http/cisco_ironport_enum
msf auxiliary(cisco_ironport_enum) >run RHOST 127.0.0.1
msf auxiliary(cisco_ironport_enum) > run

[+] 127.0.0.1:443 - Server is responsive...
[-] 127.0.0.1:443 - Connection failed, Aborting...
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

### PR DESCRIPTION
**Pull request by jinq102030**
Ensure cisco_ironport_enum module doesn't incorrectly report a failed connection when everything is fine.

Fixes #7610.

## Verification

List the steps needed to make sure this thing works

- [x] Locate a Cisco IronPort web portal you can use or use Jin's cool perf tool
- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/http/cisco_ironport_enum`
- [x] `set RHOSTS <IP of Cisco IronPort portal>`
- [x] ` run`
- [x] verify we get
```
[+] 127.0.0.1:443 - Server is responsive...
[+] 127.0.0.1:443 - Running Cisco IronPort Security Management Appliances (SMA) - AsyncOS v10.2 
[*] 127.0.0.1:443 - Starting login brute force...
[*] 127.0.0.1:443 - [1/1] - Trying username:"admin" with password:"ironport"
[+] 127.0.0.1:443 - SUCCESSFUL LOGIN - "admin":"ironport"
[!] No active DB -- Credential data will not be saved!
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

Make sure we return 1 in check_conn method.

### CODE REVIEW

**Comment by pbarry-r7** [comment]
Verified.

Behavior prior to fix:

```
$ ./msfconsole
                                                  
                          ########                  #
                      #################            #
                   ######################         #
                  #########################      #
                ############################
               ##############################
               ###############################
              ###############################
              ##############################
                              #    ########   #
                 ##        ###        ####   ##
                                      ###   ###
                                    ####   ###
               ####          ##########   ####
               #######################   ####
                 ####################   ####
                  ##################  ####
                    ############      ##
                       ########        ###
                      #########        #####
                    ############      ######
                   ########      #########
                     #####       ########
                       ###       #########
                      ######    ############
                     #######################
                     #   #   ###  #   #   ##
                     ########################
                      ##     ##   ##     ##
                            http://metasploit.com


       =[ metasploit v4.13.1-dev-75d08e5                  ]
+ -- --=[ 1605 exploits - 913 auxiliary - 275 post        ]
+ -- --=[ 458 payloads - 39 encoders - 9 nops             ]
+ -- --=[ Free Metasploit Pro trial: http://r-7.co/trymsp ]

msf > use auxiliary/scanner/http/cisco_ironport_enum
msf auxiliary(cisco_ironport_enum) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf auxiliary(cisco_ironport_enum) > run

[+] 127.0.0.1:443 - Server is responsive...
[-] 127.0.0.1:443 - Connection failed, Aborting...
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

Behavior with fix:

```
$ ./msfconsole
                                                  

                 _---------.
             .' #######   ;."
  .---,.    ;@             @@`;   .---,..
." @@@@@'.,'@@            @@@@@',.'@@@@ ".
'-.@@@@@@@@@@@@@          @@@@@@@@@@@@@ @;
   `.@@@@@@@@@@@@        @@@@@@@@@@@@@@ .'
     "--'.@@@  -.@        @ ,'-   .'--"
          ".@' ; @       @ `.  ;'
            |@@@@ @@@     @    .
             ' @@@ @@   @@    ,
              `.@@@@    @@   .
                ',@@     @   ;           _____________
                 (   3 C    )     /|___ / Metasploit! \
                 ;@'. __*__,."    \|--- \_____________/
                  '(.,...."/


       =[ metasploit v4.13.1-dev-65b858a                  ]
+ -- --=[ 1605 exploits - 913 auxiliary - 275 post        ]
+ -- --=[ 458 payloads - 39 encoders - 9 nops             ]
+ -- --=[ Free Metasploit Pro trial: http://r-7.co/trymsp ]

msf > use auxiliary/scanner/http/cisco_ironport_enum
msf auxiliary(cisco_ironport_enum) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf auxiliary(cisco_ironport_enum) > run

[+] 127.0.0.1:443 - Server is responsive...
[+] 127.0.0.1:443 - Running Cisco IronPort Security Management Appliances (SMA) - AsyncOS v10.2 
[*] 127.0.0.1:443 - Starting login brute force...
[*] 127.0.0.1:443 - [1/1] - Trying username:"admin" with password:"ironport"
[+] 127.0.0.1:443 - SUCCESSFUL LOGIN - "admin":"ironport"
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by pbarry-r7** [comment]
# Release Notes

The auxiliary/scanner/http/cisco_ironport_enum module would abruptly quit on the first brute-force attempt.  This fix proceeds as-expected on a good connection.

File: modules/auxiliary/scanner/http/cisco_ironport_enum.rb [hunk 1]
```diff
@@ -61,6 +61,7 @@ def check_conn?
         'method'    => 'GET'
       })
       print_good("#{rhost}:#{rport} - Server is responsive...")
+      return 1
```
Comment (wvu-r7) [inline modules/auxiliary/scanner/http/cisco_ironport_enum.rb]: I think this should actually return ```res```? Otherwise, the check is circumvented.

File: modules/auxiliary/scanner/http/cisco_ironport_enum.rb [hunk 2]
```diff
@@ -61,6 +61,7 @@ def check_conn?
...
     rescue ::Rex::ConnectionRefused, ::Rex::HostUnreachable, ::Rex::ConnectionTimeout, ::Rex::ConnectionError, ::Errno::EPIPE
       return
```
Comment (wvu-r7) [inline modules/auxiliary/scanner/http/cisco_ironport_enum.rb]: And this should return ```nil``` or ```false```?

File: modules/auxiliary/scanner/http/cisco_ironport_enum.rb (hunk 1 above)
Comment (wvu-r7) [inline modules/auxiliary/scanner/http/cisco_ironport_enum.rb]: Or ```true``` or ```false``` depending on ```res```.

File: modules/auxiliary/scanner/http/cisco_ironport_enum.rb (hunk 2 above)
Comment (jinq102030) [inline modules/auxiliary/scanner/http/cisco_ironport_enum.rb]: Good point @wvu-r7. I just took the fact that it prints "Server is responsive..." as a sign that everything is fine and return 1.  Returning res may be a better choice.  Thanks.

Comment (wvu-r7) [inline modules/auxiliary/scanner/http/cisco_ironport_enum.rb]: Yeah, that's just a print, though, and the print should actually be conditional on the success or failure of the ```send_request_cgi```. :)

Comment (jinq102030) [inline modules/auxiliary/scanner/http/cisco_ironport_enum.rb]: Agree. @wvu-r7  Could you submit a PR on this?  Thx.

Comment (wvu-r7) [inline modules/auxiliary/scanner/http/cisco_ironport_enum.rb]: Sure!

Comment (wvu-r7) [inline modules/auxiliary/scanner/http/cisco_ironport_enum.rb]: Technically, since the method is Boolean, it should return ```true``` or ```false```.

Comment (jinq102030) [inline modules/auxiliary/scanner/http/cisco_ironport_enum.rb]: Cool. Thx @wvu-r7 .
