### PR TITLE
fix: Handle search terms ending in colons.

### LINKED ISSUE #14768: msfconsole: Using a module with a trailing ':' matches all modules
This seems like a bug (albeit minor).

Using a module with with a trailing `:` lists info for all modules instead of selecting the module. Dumping 4000+ lines of info to console is not pleasant. This also makes no sense in instances where the preceding text is clearly a valid module name/path, and cannot possibly match all 4000+ results.

This behavior seems to be inconsistent as some characters at the end of the module name are ignored (`.`) and some are rejected (`*`), whereas `:` appears to be special.

Presumably the `:` character is being used to check if the input is a search filter rather than a module path, and when this value is followed by nothing the filter is presumed to match everything.

I will never need or desire the `use` command to dump info for all modules.

```
msf6 > use exploit/linux/local/nested_namespace_idmap_limit_priv_esc;
[-] No results from search
[-] Failed to load module: exploit/linux/local/nested_namespace_idmap_limit_priv_esc;
```

```
msf6 > use exploit/linux/local/nested_namespace_idmap_limit_priv_esc*
[-] No results from search
[-] Failed to load module: exploit/linux/local/nested_namespace_idmap_limit_priv_esc*
```

```
msf6 > use exploit/linux/local/nested_namespace_idmap_limit_priv_esczzz
[-] No results from search
[-] Failed to load module: exploit/linux/local/nested_namespace_idmap_limit_priv_esczzz
```

```
msf6 > use exploit/linux/local/nested_namespace_idmap_limit_priv_esc|
[-] No results from search
[-] Failed to load module: exploit/linux/local/nested_namespace_idmap_limit_priv_esc|
```

```
msf6 > use exploit/linux/local/nested_namespace_idmap_limit_priv_esc.
[*] Using configured payload linux/x86/meterpreter/reverse_tcp
msf6 exploit(linux/local/nested_namespace_idmap_limit_priv_esc) > back
```

```
msf6 > use exploit/linux/local/nested_namespace_idmap_limit_priv_esc:

Matching Modules
================

   #     Name                                                                               Disclosure Date  Rank       Check  Description
   -     ----                                                                               ---------------  ----       -----  -----------
   0     auxiliary/admin/2wire/xslt_password_reset                                          2007-08-15       normal     No     2Wire Cross-Site Request Forgery Password Reset Vulnerability
   1     auxiliary/admin/android/google_play_store_uxss_xframe_rce                                           normal     No     Android Browser RCE Through Google Play Store XFO

[...]

   4238  post/windows/wlan/wlan_disconnect                                                                   normal     No     Windows Disconnect Wireless Connection
   4239  post/windows/wlan/wlan_probe_request                                                                normal     No     Windows Send Probe Request Packets
   4240  post/windows/wlan/wlan_profile                                                                      normal     No     Windows Gather Wireless Profile


Interact with a module by name or index. For example info 4240, use 4240 or use post/windows/wlan/wlan_profile
```

This behavior can be reproduced with any value ending with `:` regardless of whether the previous text is a valid module path:

```
msf6 > use asdf:

Matching Modules
================

   #     Name                                                                               Disclosure Date  Rank       Check  Description
   -     ----                                                                               ---------------  ----       -----  -----------
   0     auxiliary/admin/2wire/xslt_password_reset                                          2007-08-15       normal     No     2Wire Cross-Site Request Forgery Password Reset Vulnerability
   1     auxiliary/admin/android/google_play_store_uxss_xframe_rce                                           normal     No     Android Browser RCE Through Google Play Store XFO

[...]

   4238  post/windows/wlan/wlan_disconnect                                                                   normal     No     Windows Disconnect Wireless Connection
   4239  post/windows/wlan/wlan_probe_request                                                                normal     No     Windows Send Probe Request Packets
   4240  post/windows/wlan/wlan_profile                                                                      normal     No     Windows Gather Wireless Profile


Interact with a module by name or index. For example info 4240, use 4240 or use post/windows/wlan/wlan_profile
```

```
msf6 > use asdf::
[-] Invalid argument(s)

Usage: search [<options>] [<keywords>:<value>]

Prepending a value with '-' will exclude any matching results.
If no options or keywords are provided, cached results are displayed.

OPTIONS:
  -h                Show this help information
  -o <file>         Send output to a file in csv format
  -S <string>       Regex pattern used to filter search results
  -u                Use module if there is one result

Keywords:
  aka         :  Modules with a matching AKA (also-known-as) name
  author      :  Modules written by this author
  arch        :  Modules affecting this architecture
  bid         :  Modules with a matching Bugtraq ID
  cve         :  Modules with a matching CVE ID
  edb         :  Modules with a matching Exploit-DB ID
  check       :  Modules that support the 'check' method
  date        :  Modules with a matching disclosure date
  description :  Modules with a matching description
  fullname    :  Modules with a matching full name
  mod_time    :  Modules with a matching modification date
  name        :  Modules with a matching descriptive name
  path        :  Modules with a matching path
  platform    :  Modules affecting this platform
  port        :  Modules with a matching port
  rank        :  Modules with a matching rank (Can be descriptive (ex: 'good') or numeric with comparison operators (ex: 'gte400'))
  ref         :  Modules with a matching ref
  reference   :  Modules with a matching reference
  target      :  Modules affecting this target
  type        :  Modules of a specific type (exploit, payload, auxiliary, encoder, evasion, post, or nop)

Examples:
  search cve:2009 type:exploit
  search cve:2009 type:exploit platform:-linux

[-] Failed to load module: asdf::
msf6 > 
```

### PR DESCRIPTION
**Pull request by nzdjb**
This fixes #14768.

Search terms with trailing colons will now be treated as if the colons were not present.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use exploit/linux/local/nested_namespace_idmap_limit_priv_esc:`
- [x] exploit/linux/local/nested_namespace_idmap_limit_priv_esc is selected
- [x] The entire list of modules is not printed.

### CODE REVIEW

**Comment by bwatters-r7** [comment]
It might be useful to add some specs here like `parse_search_string`

**Comment by nzdjb** [comment]
No worries. I've added a few tests.

File: lib/msf/core/modules/metadata/search.rb [hunk 1]
```diff
@@ -43,8 +43,8 @@ def self.parse_search_string(search_string)
 
     terms.each do |term|
       keyword, search_term = term.split(":", 2)
-      unless search_term
-        search_term = keyword
+      if search_term.nil? || search_term.length == 0
+        search_term = keyword.sub(/:+$/, '')
```
Comment (gwillcox-r7) [inline lib/msf/core/modules/metadata/search.rb:47]: Whilst this is a nice idea I'm not sure this is needed. Here were my tests. Notice that in no case did the keyword ever have a `:` within it:

```
irb(main):008:0> keyword, search_term = "asdf::".split(":", 2)
=> ["asdf", ":"]
irb(main):009:0> keyword, search_term = "asdf:::".split(":", 2)
=> ["asdf", "::"]
irb(main):010:0> keyword, search_term = "asdf:a:::".split(":", 2)
=> ["asdf", "a:::"]
irb(main):011:0> 
```

Note this is because we split on the first instance of the `:` occurring which means either there will be a string that goes into `keyword` which contains no `:` and the `search_term` will be blank, or we will split on the first instance of `:` in which case `keyword` will contain the part before the first instance of `:` and `search_term` will contain everything after it.

**Comment by gwillcox-r7** [comment]
Rebased to make sure we pull in latest changes and to make this a bit easier to test.

**Comment by gwillcox-r7** [comment]
Alright so looks like this sort of works and sort of doesn't

```
msf6 > use exploit/linux/local/nested_namespace_idmap_limit_priv_esc:
[*] Using configured payload linux/x86/meterpreter/reverse_tcp

Matching Modules
================

   #  Name                                                       Disclosure Date  Rank   Check  Description
   -  ----                                                       ---------------  ----   -----  -----------
   0  exploit/linux/local/nested_namespace_idmap_limit_priv_esc  2018-11-15       great  Yes    Linux Nested User Namespace idmap Limit Local Privilege Escalation


Interact with a module by name or index. For example info 0, use 0 or use exploit/linux/local/nested_namespace_idmap_limit_priv_esc

[*] Using exploit/linux/local/nested_namespace_idmap_limit_priv_esc
msf6 exploit(linux/local/nested_namespace_idmap_limit_priv_esc) > use exploit/linux/local/nested_namespace_idmap_limit_priv_esc::::::::::::::::::::::::::::::::::::::::::::::::::
[-] Invalid argument(s)

Usage: search [<options>] [<keywords>:<value>]

Prepending a value with '-' will exclude any matching results.
If no options or keywords are provided, cached results are displayed.


OPTIONS:

    -h, --help                      Help banner
    -I, --ignore                    Ignore the command if the only match has the same name as the search
    -o, --output <filename>         Send output to a file in csv format
    -r, --sort-descending <column>  Reverse the order of search results to descending order
    -S, --filter <filter>           Regex pattern used to filter search results
    -s, --sort-ascending <column>   Sort search results by the specified column in ascending order
    -u, --use                       Use module if there is one result

Keywords:
  aka              :  Modules with a matching AKA (also-known-as) name
  author           :  Modules written by this author
  arch             :  Modules affecting this architecture
  bid              :  Modules with a matching Bugtraq ID
  cve              :  Modules with a matching CVE ID
  edb              :  Modules with a matching Exploit-DB ID
  check            :  Modules that support the 'check' method
  date             :  Modules with a matching disclosure date
  description      :  Modules with a matching description
  fullname         :  Modules with a matching full name
  mod_time         :  Modules with a matching modification date
  name             :  Modules with a matching descriptive name
  path             :  Modules with a matching path
  platform         :  Modules affecting this platform
  port             :  Modules with a matching port
  rank             :  Modules with a matching rank (Can be descriptive (ex: 'good') or numeric with comparison operators (ex: 'gte400'))
  ref              :  Modules with a matching ref
  reference        :  Modules with a matching reference
  target           :  Modules affecting this target
  type             :  Modules of a specific type (exploit, payload, auxiliary, encoder, evasion, post, or nop)

Supported search columns:
  rank             :  Sort modules by their exploitabilty rank
  date             :  Sort modules by their disclosure date. Alias for disclosure_date
  disclosure_date  :  Sort modules by their disclosure date
  name             :  Sort modules by their name
  type             :  Sort modules by their type
  check            :  Sort modules by whether or not they have a check method

Examples:
  search cve:2009 type:exploit
  search cve:2009 type:exploit platform:-linux
  search cve:2009 -s name
  search type:exploit -s type -r

[-] Failed to load module: exploit/linux/local/nested_namespace_idmap_limit_priv_esc::::::::::::::::::::::::::::::::::::::::::::::::::
msf6 exploit(linux/local/nested_namespace_idmap_limit_priv_esc) > back
msf6 > use exploit/linux/local/nested_namespace_idmap_limit_priv_esc::::::::::::::::::::::::::::::::::::::::::::::::::
[-] Invalid argument(s)

Usage: search [<options>] [<keywords>:<value>]

Prepending a value with '-' will exclude any matching results.
If no options or keywords are provided, cached results are displayed.


OPTIONS:

    -h, --help                      Help banner
    -I, --ignore                    Ignore the command if the only match has the same name as the search
    -o, --output <filename>         Send output to a file in csv format
    -r, --sort-descending <column>  Reverse the order of search results to descending order
    -S, --filter <filter>           Regex pattern used to filter search results
    -s, --sort-ascending <column>   Sort search results by the specified column in ascending order
    -u, --use                       Use module if there is one result

Keywords:
  aka              :  Modules with a matching AKA (also-known-as) name
  author           :  Modules written by this author
  arch             :  Modules affecting this architecture
  bid              :  Modules with a matching Bugtraq ID
  cve              :  Modules with a matching CVE ID
  edb              :  Modules with a matching Exploit-DB ID
  check            :  Modules that support the 'check' method
  date             :  Modules with a matching disclosure date
  description      :  Modules with a matching description
  fullname         :  Modules with a matching full name
  mod_time         :  Modules with a matching modification date
  name             :  Modules with a matching descriptive name
  path             :  Modules with a matching path
  platform         :  Modules affecting this platform
  port             :  Modules with a matching port
  rank             :  Modules with a matching rank (Can be descriptive (ex: 'good') or numeric with comparison operators (ex: 'gte400'))
  ref              :  Modules with a matching ref
  reference        :  Modules with a matching reference
  target           :  Modules affecting this target
  type             :  Modules of a specific type (exploit, payload, auxiliary, encoder, evasion, post, or nop)

Supported search columns:
  rank             :  Sort modules by their exploitabilty rank
  date             :  Sort modules by their disclosure date. Alias for disclosure_date
  disclosure_date  :  Sort modules by their disclosure date
  name             :  Sort modules by their name
  type             :  Sort modules by their type
  check            :  Sort modules by whether or not they have a check method

Examples:
  search cve:2009 type:exploit
  search cve:2009 type:exploit platform:-linux
  search cve:2009 -s name
  search type:exploit -s type -r

[-] Failed to load module: exploit/linux/local/nested_namespace_idmap_limit_priv_esc::::::::::::::::::::::::::::::::::::::::::::::::::
msf6 > 
```

**Comment by gwillcox-r7** [comment]
Alright think I fixed this by getting it to now split the term being searched on by `:` 3 ways so that now the excess trailing `:`'s will not be captured as part of the search_term value.

Should now be working, updated the tests as well to account for the changes.

**Comment by gwillcox-r7** [comment]
yay its working now:

```
       =[ metasploit v6.2.26-dev-0be10c5a33               ]
+ -- --=[ 2265 exploits - 1189 auxiliary - 404 post       ]
+ -- --=[ 951 payloads - 45 encoders - 11 nops            ]
+ -- --=[ 9 evasion                                       ]

Metasploit tip: Use help <command> to learn more 
about any command
Metasploit Documentation: https://docs.metasploit.com/

msf6 > use exploit/linux/local/nested_namespace_idmap_limit_priv_esc:
[*] Using configured payload linux/x86/meterpreter/reverse_tcp

Matching Modules
================

   #  Name                                                       Disclosure Date  Rank   Check  Description
   -  ----                                                       ---------------  ----   -----  -----------
   0  exploit/linux/local/nested_namespace_idmap_limit_priv_esc  2018-11-15       great  Yes    Linux Nested User Namespace idmap Limit Local Privilege Escalation


Interact with a module by name or index. For example info 0, use 0 or use exploit/linux/local/nested_namespace_idmap_limit_priv_esc

[*] Using exploit/linux/local/nested_namespace_idmap_limit_priv_esc
msf6 exploit(linux/local/nested_namespace_idmap_limit_priv_esc) > back
msf6 > use exploit/linux/local/nested_namespace_idmap_limit_priv_esc:::::::::::::::::
[*] Using configured payload linux/x86/meterpreter/reverse_tcp

Matching Modules
================

   #  Name                                                       Disclosure Date  Rank   Check  Description
   -  ----                                                       ---------------  ----   -----  -----------
   0  exploit/linux/local/nested_namespace_idmap_limit_priv_esc  2018-11-15       great  Yes    Linux Nested User Namespace idmap Limit Local Privilege Escalation


Interact with a module by name or index. For example info 0, use 0 or use exploit/linux/local/nested_namespace_idmap_limit_priv_esc

[*] Using exploit/linux/local/nested_namespace_idmap_limit_priv_esc
msf6 exploit(linux/local/nested_namespace_idmap_limit_priv_esc) > 
```

Will go ahead and land this, thanks for your work @nzdjb and congrats on your first Metasploit contribution!

**Comment by gwillcox-r7** [comment]
# Release Notes
A bug has been fixed when searching for or attempting to use modules whereby trailing `:`'s were not handled appropriately as part of the input, and could lead to all modules in Metasploit being returned.
