### PR TITLE
Apache RocketMQ & ActiveMQ fixes

### LINKED ISSUE #19035: The apache_rocketmq_update_config exploit check method never times out
## Steps to reproduce
1. use exploit/multi/http/apache_rocketmq_update_config
2. Set RHOSTS to a large batch of hosts running http servers (with some not running RocketMQ, and with some no longer online)
3. Run the check
4. Note that eventually ctrl-c will be required to move past various hosts that did not respond as expected
 
## Were you following a specific guide/tutorial or reading documentation?
No

## Expected behavior
When a host is not responding as RocketMQ is expected to within a given timeout, the check should move on to the next host.

## Current behavior
At this point you should see that eventually the check will stall on a host and never continue (i.e., several hours with no progress). This appears to occur due to a variety of reasons (e.g., host offline, host not running RocketMQ, etc.)

### Metasploit version
6.3.55-dev

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/ui/console]
ActiveModule=exploit/multi/http/apache_rocketmq_update_config

[multi/http/apache_rocketmq_update_config]
RHOSTS=10.253.180.211
RPORT=746
SSL=true
loglevel=3
WORKSPACE=
VERBOSE=false
WfsDelay=60
EnableContextEncoding=false
ContextInformationFile=
DisablePayloadHandler=false
SSLServerNameIndication=
SSLVersion=Auto
SSLVerifyMode=PEER
SSLCipher=
Proxies=
CPORT=
CHOST=
ConnectTimeout=10
TCP::max_send_size=0
TCP::send_delay=0
EXE::EICAR=false
EXE::Custom=
EXE::Path=
EXE::Template=
EXE::Inject=false
EXE::OldMethod=false
EXE::FallBack=false
MSI::EICAR=false
MSI::Custom=
MSI::Path=
MSI::Template=
MSI::UAC=false
SRVHOST=0.0.0.0
SRVPORT=8080
ListenerBindAddress=
ListenerBindPort=
ListenerComm=
SSLCert=
SSLCompression=false
URIPATH=
HTTP::no_cache=false
HTTP::chunked=false
HTTP::header_folding=false
HTTP::junk_headers=false
HTTP::compression=none
HTTP::server_name=Apache
URIHOST=
URIPORT=
SendRobots=false
CMDSTAGER::FLAVOR=auto
CMDSTAGER::DECODER=
CMDSTAGER::TEMP=
CMDSTAGER::URIPATH=
CMDSTAGER::SSL=false
BROKER_PORT=10911
AutoCheck=true
ForceExploit=false
LHOST=
LPORT=4444
ReverseListenerBindPort=
ReverseAllowProxy=false
ReverseListenerComm=
ReverseListenerBindAddress=
ReverseListenerThreaded=false
StagerRetryCount=10
StagerRetryWait=5
AutoLoadStdapi=true
AutoVerifySessionTimeout=30
InitialAutoRunScript=
AutoRunScript=
AutoSystemInfo=true
EnableUnicodeEncoding=false
HandlerSSLCert=
SessionRetryTotal=3600
SessionRetryWait=10
SessionExpirationTimeout=604800
SessionCommunicationTimeout=300
PayloadProcessCommandLine=
AutoUnhookProcess=false
MeterpreterDebugBuild=false
MeterpreterDebugLogging=
PingbackRetries=0
PingbackSleep=30
PayloadUUIDSeed=
PayloadUUIDRaw=
PayloadUUIDName=
PayloadUUIDTracking=false
EnableStageEncoding=false
StageEncoder=
StageEncoderSaveRegisters=
StageEncodingFallback=true
PrependFork=false
PrependSetresuid=false
PrependSetreuid=false
PrependSetuid=false
PrependSetresgid=false
PrependSetregid=false
PrependSetgid=false
PrependChrootBreak=false
AppendExit=false
MeterpreterTryToFork=false
FETCH_DELETE=false
FETCH_FILENAME=yIfWKqqQ
FETCH_SRVPORT=8080
FETCH_SRVHOST=
FETCH_URIPATH=
FETCH_WRITABLE_DIR=
FetchListenerBindAddress=
FetchListenerBindPort=
FetchHandlerDisable=false
FetchServerName=Apache
FetchHttpServerName=Apache
FETCH_COMMAND=CURL
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: Connected to msf. Connection type: postgresql.
```

| ID | Hosts | Vulnerabilities | Notes | Services |
|-:|-:|-:|-:|-:|
| 1 **(Current)** | 6,407 | 625 | 8,413 | 13,152 |
| **Total (1)** | **6,407** | **625** | **8,413** | **13,155** |

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
1505   set loglevel 3
1506   use multi/http/apache_rocketmq_update_config
1507   set RHOSTS 10.253.180.211
1508   set RPORT 746
1509   set SSL true
1510   check
1511   debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[03/30/2024 13:19:27] [e(0)] core: 137.187.4.232:443 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:19:27] [e(0)] core: Exploit failed (multi/http/apache_rocketmq_update_config): NoMethodError undefined method `[]' for nil:NilClass - NoMethodError undefined method `[]' for nil:NilClass
[03/30/2024 13:19:27] [e(0)] core: 165.112.117.78:443 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:21:27] [e(0)] core: Exploit failed (multi/http/apache_rocketmq_update_config): NoMethodError undefined method `[]' for nil:NilClass - NoMethodError undefined method `[]' for nil:NilClass
[03/30/2024 13:21:27] [e(0)] core: 10.142.121.206:631 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:21:27] [e(0)] core: Exploit failed (multi/http/apache_rocketmq_update_config): NoMethodError undefined method `[]' for nil:NilClass - NoMethodError undefined method `[]' for nil:NilClass
[03/30/2024 13:21:27] [e(0)] core: 128.231.59.246:631 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:22:27] [e(0)] core: Exploit failed (multi/http/apache_rocketmq_update_config): NoMethodError undefined method `[]' for nil:NilClass - NoMethodError undefined method `[]' for nil:NilClass
[03/30/2024 13:22:27] [e(0)] core: 137.187.4.232:631 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:26:08] [e(0)] core: Check Failed - Interrupt
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:21:27] [e(0)] core: Exploit failed (multi/http/apache_rocketmq_update_config): NoMethodError undefined method `[]' for nil:NilClass - NoMethodError undefined method `[]' for nil:NilClass
[03/30/2024 13:21:27] [e(0)] core: 128.231.59.246:631 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:21:57] [d(0)] core: Reloading module exploit/multi/http/apache_rocketmq_update_config...
[03/30/2024 13:21:57] [w(0)] core: The module multi/http/apache_rocketmq_update_config is ambiguous with multi/http/apache_rocketmq_update_config.
[03/30/2024 13:21:57] [d(0)] core: Refreshing multi/http/apache_rocketmq_update_config of type: exploit
[03/30/2024 13:22:27] [e(0)] core: Exploit failed (multi/http/apache_rocketmq_update_config): NoMethodError undefined method `[]' for nil:NilClass - NoMethodError undefined method `[]' for nil:NilClass
[03/30/2024 13:22:27] [e(0)] core: 137.187.4.232:631 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:26:08] [e(0)] core: Check Failed - Interrupt
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.3.55-dev
Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
OpenSSL: OpenSSL 3.1.4 24 Oct 2023
Install Root: /usr/share/metasploit-framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Other - Please specify
```

</details>

### LINKED ISSUE #19036: The apache_activemq_rce_cve_2023_46604 exploit check method never times out
## Steps to reproduce
1. use exploit/multi/misc/apache_activemq_rce_cve_2023_46604
2. Set RHOSTS to a large batch of hosts running servers (with some not running ActiveMQ, and with some no longer online)
3. Run the check
4. Note that eventually ctrl-c will be required to move past various hosts that did not respond as expected
 
## Were you following a specific guide/tutorial or reading documentation?
No

## Expected behavior
When a host is not responding as ActiveMQ is expected to within a given timeout, the check should move on to the next host.

## Current behavior
At this point you should see that eventually the check will stall on a host and never continue (i.e., several hours with no progress). This appears to occur due to a variety of reasons (e.g., host offline, host not running ActiveMQ, etc.)

### Metasploit version
6.3.55-dev

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/core]
loglevel=3

[framework/ui/console]
ActiveModule=exploit/multi/misc/apache_activemq_rce_cve_2023_46604

[multi/misc/apache_activemq_rce_cve_2023_46604]
RHOSTS=10.142.80.76
RPORT=4343
SSL=true
WORKSPACE=
VERBOSE=false
WfsDelay=30
EnableContextEncoding=false
ContextInformationFile=
DisablePayloadHandler=false
SRVHOST=0.0.0.0
SRVPORT=8080
ListenerBindAddress=
ListenerBindPort=
ListenerComm=
SSLCert=
SSLCompression=false
SSLCipher=
SSLVersion=Auto
TCP::max_send_size=0
TCP::send_delay=0
URIPATH=
HTTP::no_cache=false
HTTP::chunked=false
HTTP::header_folding=false
HTTP::junk_headers=false
HTTP::compression=none
HTTP::server_name=Apache
URIHOST=
URIPORT=
SendRobots=false
SSLServerNameIndication=
SSLVerifyMode=PEER
Proxies=
CPORT=
CHOST=
ConnectTimeout=10
AutoCheck=true
ForceExploit=false
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: Connected to msf. Connection type: postgresql.
```

| ID | Hosts | Vulnerabilities | Notes | Services |
|-:|-:|-:|-:|-:|
| 1 **(Current)** | 6,407 | 625 | 8,413 | 13,152 |
| **Total (1)** | **6,407** | **625** | **8,413** | **13,155** |

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
1549   set loglevel 3
1550   use exploit/multi/misc/apache_activemq_rce_cve_2023_46604
1551   set RHOSTS 10.142.80.76
1552   set RPORT 4343
1553   set SSL true
1554   check
1555   debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[03/30/2024 13:58:26] [e(0)] core: Exploit failed (multi/http/apache_rocketmq_update_config): NoMethodError undefined method `[]' for nil:NilClass - NoMethodError undefined method `[]' for nil:NilClass
[03/30/2024 13:58:26] [e(0)] core: 10.253.180.46:44343 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:58:26] [e(0)] core: Exploit failed (multi/http/apache_rocketmq_update_config): NoMethodError undefined method `[]' for nil:NilClass - NoMethodError undefined method `[]' for nil:NilClass
[03/30/2024 13:58:26] [e(0)] core: 10.253.180.198:44343 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:58:26] [e(0)] core: Exploit failed (multi/http/apache_rocketmq_update_config): NoMethodError undefined method `[]' for nil:NilClass - NoMethodError undefined method `[]' for nil:NilClass
[03/30/2024 13:58:26] [e(0)] core: 10.253.180.4:47001 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 13:58:26] [e(0)] core: Exploit failed (multi/http/apache_rocketmq_update_config): NoMethodError undefined method `[]' for nil:NilClass - NoMethodError undefined method `[]' for nil:NilClass
[03/30/2024 13:58:26] [e(0)] core: 10.253.180.46:47001 - Check failed: The state could not be determined.
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
(eval):23:in `block in load_resource'
(eval):10:in `each'
(eval):10:in `load_resource'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `eval'
/usr/share/metasploit-framework/lib/rex/ui/text/resource.rb:60:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:195:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:194:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[03/30/2024 14:00:34] [e(0)] core: /root/.msf4/modules/exploits/multi/misc/weblogic_deserialize_badattr_extcomp.rb failed to load - NotImplementedError Msf::Exploit::Remote::AutoCheck should not be included, it should be prepended
[03/30/2024 14:02:45] [e(0)] core: Check Failed - Interrupt
Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/rex-socket-0.1.55/lib/rex/socket/ssl_tcp.rb:267:in `sysread'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/rex-socket-0.1.55/lib/rex/socket/ssl_tcp.rb:267:in `read'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/rex-core-0.1.31/lib/rex/io/stream.rb:223:in `get_once'
/usr/share/metasploit-framework/modules/exploits/multi/misc/apache_activemq_rce_cve_2023_46604.rb:83:in `check'
/usr/share/metasploit-framework/lib/msf/base/simple/exploit.rb:238:in `job_check_proc'
/usr/share/metasploit-framework/lib/msf/base/simple/exploit.rb:218:in `check_simple'
/usr/share/metasploit-framework/lib/msf/base/simple/exploit.rb:226:in `check_simple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:203:in `check_simple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:165:in `block in run'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:309:in `block in with_history_manager_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:306:in `with_history_manager_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:133:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/custom with multi/misc/apache_activemq_rce_cve_2023_46604]: tunnel to none
[03/30/2024 14:01:07] [d(1)] core: Module generic/custom is compatible with multi/misc/apache_activemq_rce_cve_2023_46604
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_bind_aws_ssm with multi/misc/apache_activemq_rce_cve_2023_46604]: reverse to bind
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_bind_aws_ssm with multi/misc/apache_activemq_rce_cve_2023_46604]: bind to bind
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_bind_aws_ssm with multi/misc/apache_activemq_rce_cve_2023_46604]: noconn to bind
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_bind_aws_ssm with multi/misc/apache_activemq_rce_cve_2023_46604]: none to bind
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_bind_aws_ssm with multi/misc/apache_activemq_rce_cve_2023_46604]: tunnel to bind
[03/30/2024 14:01:07] [d(1)] core: Module generic/shell_bind_aws_ssm is compatible with multi/misc/apache_activemq_rce_cve_2023_46604
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_bind_tcp with multi/misc/apache_activemq_rce_cve_2023_46604]: reverse to bind
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_bind_tcp with multi/misc/apache_activemq_rce_cve_2023_46604]: bind to bind
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_bind_tcp with multi/misc/apache_activemq_rce_cve_2023_46604]: noconn to bind
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_bind_tcp with multi/misc/apache_activemq_rce_cve_2023_46604]: none to bind
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_bind_tcp with multi/misc/apache_activemq_rce_cve_2023_46604]: tunnel to bind
[03/30/2024 14:01:07] [d(1)] core: Module generic/shell_bind_tcp is compatible with multi/misc/apache_activemq_rce_cve_2023_46604
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_reverse_tcp with multi/misc/apache_activemq_rce_cve_2023_46604]: reverse to reverse
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_reverse_tcp with multi/misc/apache_activemq_rce_cve_2023_46604]: bind to reverse
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_reverse_tcp with multi/misc/apache_activemq_rce_cve_2023_46604]: noconn to reverse
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_reverse_tcp with multi/misc/apache_activemq_rce_cve_2023_46604]: none to reverse
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/shell_reverse_tcp with multi/misc/apache_activemq_rce_cve_2023_46604]: tunnel to reverse
[03/30/2024 14:01:07] [d(1)] core: Module generic/shell_reverse_tcp is compatible with multi/misc/apache_activemq_rce_cve_2023_46604
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/ssh/interact with multi/misc/apache_activemq_rce_cve_2023_46604]: reverse to none
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/ssh/interact with multi/misc/apache_activemq_rce_cve_2023_46604]: bind to none
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/ssh/interact with multi/misc/apache_activemq_rce_cve_2023_46604]: noconn to none
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/ssh/interact with multi/misc/apache_activemq_rce_cve_2023_46604]: none to none
[03/30/2024 14:01:07] [d(3)] core: Checking compat [generic/ssh/interact with multi/misc/apache_activemq_rce_cve_2023_46604]: tunnel to none
[03/30/2024 14:01:07] [d(1)] core: Module generic/ssh/interact is compatible with multi/misc/apache_activemq_rce_cve_2023_46604
[03/30/2024 14:02:45] [e(0)] core: Check Failed - Interrupt
Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/rex-socket-0.1.55/lib/rex/socket/ssl_tcp.rb:267:in `sysread'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/rex-socket-0.1.55/lib/rex/socket/ssl_tcp.rb:267:in `read'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/rex-core-0.1.31/lib/rex/io/stream.rb:223:in `get_once'
/usr/share/metasploit-framework/modules/exploits/multi/misc/apache_activemq_rce_cve_2023_46604.rb:83:in `check'
/usr/share/metasploit-framework/lib/msf/base/simple/exploit.rb:238:in `job_check_proc'
/usr/share/metasploit-framework/lib/msf/base/simple/exploit.rb:218:in `check_simple'
/usr/share/metasploit-framework/lib/msf/base/simple/exploit.rb:226:in `check_simple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:203:in `check_simple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:60:in `check_multiple'
/usr/share/metasploit-framework/lib/msf/ui/console/module_command_dispatcher.rb:155:in `cmd_check'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:165:in `block in run'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:309:in `block in with_history_manager_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:306:in `with_history_manager_context'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:133:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.3.55-dev
Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
OpenSSL: OpenSSL 3.1.4 24 Oct 2023
Install Root: /usr/share/metasploit-framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Other - Please specify
```

</details>

### PR DESCRIPTION
**Pull request by jheysel-r7**
Fixes a timeout issue that was being seen when running the following modules:
- modules/exploits/multi/http/apache_rocketmq_update_config.rb
- modules/exploits/multi/misc/apache_activemq_rce_cve_2023_46604.rb

Once this PR is landed we should be able to close https://github.com/rapid7/metasploit-framework/pull/19037 & https://github.com/rapid7/metasploit-framework/pull/19038
### RocketMQ
1. Start msfconsole.
1. Do: ` use exploit/multi/http/apache_rocketmq_update_config`.
1. Set the `RHOST` and `LHOST` options.
1. Run the module.
1. Receive a session in the context of the user running the RocketMQ application.

### ActiveMQ
Steps (Linux target):
1. Start msfconsole
2. `use exploit/multi/misc/apache_activemq_rce_cve_2023_46604`
3. `set RHOST <LINUX_TARGET_IP>`
4. `set SRVHOST eth0`
5. `set target 1`
6. `set PAYLOAD cmd/linux/http/x64/meterpreter/reverse_tcp`
7. `check`
8. `exploit`

Ensure neither module hangs, times out or errors in any unexpected way (they shouldn't).

### RocketMQ
```
msf6 exploit(multi/http/apache_rocketmq_update_config) > options

Module options (exploit/multi/http/apache_rocketmq_update_config):

   Name         Current Setting  Required  Description
   ----         ---------------  --------  -----------
   BROKER_PORT  10911            no        The RocketMQ Broker port. If left unset the module will attempt to retrieve the Broker port from the NameServer response (recommen
                                           ded)
   CHOST                         no        The local client address
   CPORT                         no        The local client port
   Proxies                       no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS       127.0.0.1        yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT        9876             yes       The RocketMQ NameServer port (TCP)
   SSL          false            no        Negotiate SSL for incoming connections
   SSLCert                       no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                       no        The URI to use for this exploit (default is random)


   When CMDSTAGER::FLAVOR is one of auto,tftp,wget,curl,fetch,lwprequest,psh_invokewebrequest,ftp_http:

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.


Payload options (cmd/linux/http/x64/meterpreter/reverse_tcp):

   Name                Current Setting  Required  Description
   ----                ---------------  --------  -----------
   FETCH_COMMAND       CURL             yes       Command to fetch payload (Accepted: CURL, FTP, TFTP, TNFTP, WGET)
   FETCH_DELETE        false            yes       Attempt to delete the binary after execution
   FETCH_FILENAME      ezCLiIlwE        no        Name to use on remote system when storing payload; cannot contain spaces or slashes
   FETCH_SRVHOST                        no        Local IP to use for serving payload
   FETCH_SRVPORT       8080             yes       Local port to use for serving payload
   FETCH_URIPATH                        no        Local URI to use for serving payload
   FETCH_WRITABLE_DIR                   yes       Remote writable dir to store payload; cannot contain spaces
   LHOST               172.16.199.1     yes       The listen address (an interface may be specified)
   LPORT               4434             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Automatic (Unix In-Memory)



View the full module info with the info, or info -d command.

msf6 exploit(multi/http/apache_rocketmq_update_config) > rexploit
[*] Reloading module...

[*] Started reverse TCP handler on 172.16.199.1:4434
[*] 127.0.0.1:9876 - Running automatic check ("set AutoCheck false" to disable)
[+] 127.0.0.1:9876 - The target appears to be vulnerable. RocketMQ version: 4.9.4
[*] 127.0.0.1:9876 - autodetection failed, assuming default port of 10911
[*] 127.0.0.1:9876 - Executing target: Automatic (Unix In-Memory) with payload cmd/linux/http/x64/meterpreter/reverse_tcp on Broker port: 10911
[*] Sending stage (3045380 bytes) to 172.16.199.1
[*] 127.0.0.1:9876 - Removing the payload from where it was injected into $ROCKETMQ_HOME. The FilterServerManager class will execute the payload every 30 seconds until this is reverted
[+] 127.0.0.1:9876 - Determined the original $ROCKETMQ_HOME: /home/rocketmq/rocketmq-4.9.4
[*] 127.0.0.1:9876 - Re-running the exploit in order to reset the proper $ROCKETMQ_HOME value
[*] Meterpreter session 11 opened (172.16.199.1:4434 -> 172.16.199.1:59206) at 2024-04-26 14:09:31 -0700

meterpreter > getuid
Server username: rocketmq
meterpreter > sysinfo
Computer     : 172.17.0.3
OS           : CentOS 7.9.2009 (Linux 6.6.22-linuxkit)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > exit
[*] Shutting down session: 11

[*] 127.0.0.1 - Meterpreter session 11 closed.  Reason: User exit
```
### ActiveMQ
```
msf6 exploit(multi/misc/apache_activemq_rce_cve_2023_46604) > options

Module options (exploit/multi/misc/apache_activemq_rce_cve_2023_46604):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   RHOSTS   127.0.0.1        yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT    61616            yes       The target port (TCP)
   SRVHOST  0.0.0.0          yes       The local host or network interface to listen on. This must be an address on the local machine or 0.0.0.0 to listen on all addresses.
   SRVPORT  8080             yes       The local port to listen on.
   SSLCert                   no        Path to a custom SSL certificate (default is randomly generated)
   URIPATH                   no        The URI to use for this exploit (default is random)


Payload options (cmd/unix/reverse_perl):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.16.199.1     yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   2   Unix



View the full module info with the info, or info -d command.

msf6 exploit(multi/misc/apache_activemq_rce_cve_2023_46604) > check
[*] 127.0.0.1:61616 - The target appears to be vulnerable. Apache ActiveMQ 5.15.6
```

### CODE REVIEW

File: lib/msf/core/auxiliary/rocketmq.rb [hunk 1]
```diff
@@ -25,10 +25,12 @@ def send_version_request
       begin
         connect
         sock.send(header + data_length + data, 0)
-        res = sock.recv(1024)
+        res_length = sock.timed_read(4).unpack1('N')
+        res = sock.timed_read(res_length)
```
Comment (smcintyre-r7) [inline lib/msf/core/auxiliary/rocketmq.rb:29]:
```suggestion
        res_length = sock.timed_read(4)&.unpack1('N')
        reutrn nil if res_length.nil?
        res = sock.timed_read(res_length)
```

File: modules/exploits/multi/misc/apache_activemq_rce_cve_2023_46604.rb [hunk 2]
```diff
@@ -80,15 +80,19 @@ def initialize(info = {})
   def check
     connect
 
-    res = sock.get_once
+    len = sock.timed_read(4).unpack1('N')
+
+    return CheckCode::Unknown if len > 0x2000 # upper limit in case the service isn't ActiveMQ
```
Comment (smcintyre-r7) [inline modules/exploits/multi/misc/apache_activemq_rce_cve_2023_46604.rb:85]:
```suggestion
    len = sock.timed_read(4)&.unpack1('N')

    return CheckCode::Unknown if len.nil? || len > 0x2000 # upper limit in case the service isn't ActiveMQ
```

**Review by smcintyre-r7 — CHANGES_REQUESTED** [review]
I went and tested this against an HTTPS server again, and the `#timed_read` method returns nil when it times out so I made some suggestions to accommodate that.

**Review by smcintyre-r7 — APPROVED** [review]
Thanks @jheysel-r7, I just ran through the tests and things are looking much better now. I confirmed that `apache_rocketmq_update_config` is still executing its payload and it's check method is much faster now when targeting and HTTPS server:

```
metasploit-framework (S:0 J:0) exploit(multi/http/apache_rocketmq_update_config) > check
[*] 18.220.174.0:9876 - The target appears to be vulnerable. RocketMQ version: 4.9.4
metasploit-framework (S:0 J:0) exploit(multi/http/apache_rocketmq_update_config) > check https://zerosteiner.com
[*] 192.168.249.3:443 - Cannot reliably check exploitability. Unable to determine the version
```

`auxiliary/scanner/misc/rocketmq_version` is also still working and much faster when targeting an invalid server.
```
metasploit-framework (S:0 J:0) auxiliary(scanner/misc/rocketmq_version) > set RHOSTS 18.220.174.0
RHOSTS => 18.220.174.0
metasploit-framework (S:0 J:0) auxiliary(scanner/misc/rocketmq_version) > run

[+] 18.220.174.0:9876     - RocketMQ version V4.9.4 found with brokers: [{"brokerAddrs"=>{"0"=>"172.17.0.3:10911"}, "brokerName"=>"broker-a", "cluster"=>"DefaultCluster"}]
[*] 18.220.174.0:9876     - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
metasploit-framework (S:0 J:0) auxiliary(scanner/misc/rocketmq_version) > run https://zerosteiner.com

[-] 192.168.249.3:443     - Invalid or no response received
[*] https://zerosteiner.com:9876 - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
metasploit-framework (S:0 J:0) auxiliary(scanner/misc/rocketmq_version) > 
```

Finally, `exploit/multi/misc/apache_activemq_rce_cve_2023_46604` is much faster when targeting an HTTPS server.

```
metasploit-framework (S:0 J:0) exploit(multi/misc/apache_activemq_rce_cve_2023_46604) > time check https://zerosteiner.com
[*] 192.168.249.3:443 - Cannot reliably check exploitability.
[+] Command "check https://zerosteiner.com" completed in 10.14058061500009 seconds
metasploit-framework (S:0 J:0) exploit(multi/misc/apache_activemq_rce_cve_2023_46604) >
metasploit-framework (S:0 J:0) exploit(multi/misc/apache_activemq_rce_cve_2023_46604) > check
[*] 18.220.174.0:61616 - The target appears to be vulnerable. Apache ActiveMQ 5.18.2
metasploit-framework (S:0 J:0) exploit(multi/misc/apache_activemq_rce_cve_2023_46604) >
```

**Comment by smcintyre-r7** [comment]
# Release Notes

This fixes timeout issues encountered by rocketmq and activemq modules that would occur when the target is not running the expected service.
