### PR TITLE
Check for nil res when setting echo shell

### LINKED ISSUE #19615: single_command_shell.rb crash
1. Get a shell on vcenter (ssh_login with root is fine), and you'll succeed but be caught in a pseudo shell.
2. Type `shell` to get to the shell, except that's intercepted by metasploit
3. crash

```
[-] Session manipulation failed: undefined method `include?' for nil:NilClass ["/root/metasploit-framework/lib/msf/core/session/provider/single_command_shell.rb:122:in `set_is_echo_shell'", "/root/metasploit-framework/lib/msf/core/session/provider/single_command_shell.rb:143:in `shell_command_token_base'", "/root/metasploit-framework/lib/msf/core/session/provider/single_command_shell.rb:130:in `shell_command_token_unix'", "/root/metasploit-framework/lib/msf/core/session/provider/single_command_shell.rb:91:in `shell_command_token'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:392:in `block in binary_exists'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:375:in `binary_exists'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:391:in `binary_exists'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:335:in `cmd_shell'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:623:in `run_builtin_cmd'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:611:in `run_single'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:820:in `_interact_stream'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:796:in `block in _interact'", "/root/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:795:in `_interact'", "/root/metasploit-framework/lib/rex/ui/interactive.rb:53:in `interact'", "/root/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1749:in `cmd_sessions'", "/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:582:in `run_command'", "/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:531:in `block in run_single'", "/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `each'", "/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_single'", "/root/metasploit-framework/lib/rex/ui/text/shell.rb:165:in `block in run'", "/root/metasploit-framework/lib/rex/ui/text/shell.rb:309:in `block in with_history_manager_context'", "/root/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'", "/root/metasploit-framework/lib/rex/ui/text/shell.rb:306:in `with_history_manager_context'", "/root/metasploit-framework/lib/rex/ui/text/shell.rb:133:in `run'", "/root/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'", "/root/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'", "./msfconsole:23:in `<main>'"]
```
Full output:

```
[*] Starting interaction with 2...

Connected to service

    * List APIs: "help api list"
    * List Plugins: "help pi list"
    * Launch BASH: "shell"

Command> Command> shell

[*] Trying to find binary 'python' on the target machine
[-] Session manipulation failed: undefined method `include?' for nil:NilClass ["/root/metasploit-framework/lib/msf/core/session/provider/single_command_shell.rb:122:in `set_is_echo_shell'", "/root/metasploit-framework/lib/msf/core/session/provider/single_command_shell.rb:143:in `shell_command_token_base'", "/root/metasploit-framework/lib/msf/core/session/provider/single_command_shell.rb:130:in `shell_command_token_unix'", "/root/metasploit-framework/lib/msf/core/session/provider/single_command_shell.rb:91:in `shell_command_token'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:392:in `block in binary_exists'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:375:in `binary_exists'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:391:in `binary_exists'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:335:in `cmd_shell'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:623:in `run_builtin_cmd'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:611:in `run_single'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:820:in `_interact_stream'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:796:in `block in _interact'", "/root/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'", "/root/metasploit-framework/lib/msf/base/sessions/command_shell.rb:795:in `_interact'", "/root/metasploit-framework/lib/rex/ui/interactive.rb:53:in `interact'", "/root/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1749:in `cmd_sessions'", "/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:582:in `run_command'", "/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:531:in `block in run_single'", "/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `each'", "/root/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_single'", "/root/metasploit-framework/lib/rex/ui/text/shell.rb:165:in `block in run'", "/root/metasploit-framework/lib/rex/ui/text/shell.rb:309:in `block in with_history_manager_context'", "/root/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'", "/root/metasploit-framework/lib/rex/ui/text/shell.rb:306:in `with_history_manager_context'", "/root/metasploit-framework/lib/rex/ui/text/shell.rb:133:in `run'", "/root/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'", "/root/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'", "./msfconsole:23:in `<main>'"]
```

### PR DESCRIPTION
**Pull request by sjanusz-r7**
This PR fixes https://github.com/rapid7/metasploit-framework/issues/19615

From the code, `shell_read_until_token` can return `nil`. Now the code that broke in the linked issue explicitly checks for a `nil`.

I wasn't able to reproduce the issue locally using `ssh_login` against a Kali & Ubuntu VM, and I don't have any vCenter environments to test against.

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/ssh/ssh_login`
- [ ] `sessions -i -1`
- [ ] Verify you can get a `shell` using the `shell` command
- [ ] Verify it doesn't crash

## Example

```ruby
[*] SSH session 1 opened (...:56421 -> ...:22) at 2024-11-05 13:37:01 +0000
[*] Scanned 1 of 1 hosts (100% complete)
[*] Scan completed, 1 credential was successful.

Successful logins
=================

    Host             Public  Private
    ----             ------  -------
    ...                 kali    kali


[*] 1 session was opened successfully.
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/ssh/ssh_login) > sessions -i -1
[*] Starting interaction with 1...

shell

[*] Trying to find binary 'python' on the target machine
[*] Found python at /usr/bin/python
[*] Using `python` to pop up an interactive shell
[*] Trying to find binary 'bash' on the target machine
[*] Found bash at /usr/bin/bash

kali@kali:~$ whoami
whoami
kali
```

### CODE REVIEW

File: lib/msf/core/session/provider/single_command_shell.rb [hunk 1]
```diff
@@ -119,7 +119,7 @@ def set_is_echo_shell(timeout, command_separator)
     cmd = "echo #{numeric_token}"
     shell_write(cmd + "#{command_separator}echo #{token}#{command_termination}")
     res = shell_read_until_token(token, 0, timeout)
-    @is_echo_shell = res.include?(cmd)
+    @is_echo_shell = res ? res.include?(cmd) : false
```
Comment (jvoisin) [inline lib/msf/core/session/provider/single_command_shell.rb:122]:
```suggestion
    @is_echo_shell = res&.include?(cmd)
```

Comment (adfoster-r7) [reply lib/msf/core/session/provider/single_command_shell.rb:122]: Just a heads up that these would be semantically different

Before

```
3.2.5 :001 > res = nil
3.2.5 :002 > @is_echo_shell = res&.include?(cmd)
3.2.5 :003 > @is_echo_shell = res ? res.include?(cmd) : false
 => false 
```

After

```
3.2.5 :001 > res = nil
3.2.5 :002 > @is_echo_shell = res&.include?(cmd)
3.2.5 :003 > puts @is_echo_shell.inspect
nil
 => nil 
```

Not a blocker; `!!res&.include?(cmd)` would be closer to the existing semantics

Comment (jvoisin) [reply lib/msf/core/session/provider/single_command_shell.rb:122]: Thanks!

Comment (smashery) [reply lib/msf/core/session/provider/single_command_shell.rb:122]: Yeah, looks like if it ends up as `nil`, it'll just keep trying this every time; which while probably harmless, is probably not intended. Going with `false` seems better.

**Review by adfoster-r7 — APPROVED** [review]

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes a crash when running against a shell session which does not echo the executed commands
