### PR TITLE
Fix error when running ssh_login_pubkey.rb against a directory/file and improve error handling

### LINKED ISSUE #14403: ssh_login_pubkey errors on keys/dirs
`ssh_login_pubkey` does not correctly use the `key_path` variable and throws io errors.

## when setting `key_path` to a folder, it doesn't use the files inside of it.

```
msf6 > use auxiliary/scanner/ssh/ssh_login_pubkey
msf6 auxiliary(scanner/ssh/ssh_login_pubkey) > set KEY_PATH /home/gwillcox/.ssh/
KEY_PATH => /home/gwillcox/.ssh/
msf6 auxiliary(scanner/ssh/ssh_login_pubkey) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf6 auxiliary(scanner/ssh/ssh_login_pubkey) > set USERNAME root
USERNAME => root
msf6 auxiliary(scanner/ssh/ssh_login_pubkey) > run
[*] 127.0.0.1:22 SSH - Testing Cleartext Keys
[*] Error: 127.0.0.1: Errno::EISDIR Is a directory @ io_fread - /home/gwillcox/.ssh
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/ssh/ssh_login_pubkey) > 
```
## When setting it to an actual file.

```
set key_path /root/id_rsa
```
same thing:
```
Errno::EISDIR Is a directory @ io_fillbuf - fd:14 /root
```

### Metasploit version

* 6.0.17-dev
* 5.0.101-dev
* master (@gwillcox-r7 tested)

## Additional Information

Both modes, a folder, or a file seem to fail.  A folder doesn't read the files inside, and a file is cut back one+ dir.

### PR DESCRIPTION
**Pull request by cgranleese-r7**
This PR resolves #14403.

This PR implements a fix for when the user runs `auxiliary/scanner/ssh/ssh_login_pubkey` against a directory/file. Previously it would return the following error:
```Bash
Errno::EISDIR Is a directory @ io_fillbuf - fd:14 /root
```
Now it will handle both files and directories as expected.

## Before
image

## After 
image

## Error handling _improvements_
Some improvements have also been added to the error handling, to now return a  more useful error(s) when the user run the module against a directory that has no valid keys. It will now list the filename and the corresponding error to the user.

image

### Module options used
image

### Steps to test fix
- [x] Start `msfconsole`
- [x] run `use auxiliary/scanner/ssh/ssh_login_pubkey`
- [x] Set module options (options I used can be found above)
- [x] **Verify** the module now runs without the previous error
- [x] **Verify** it now works when `KEY_PATH` is set to a directory or a file.

### Steps to test new error handling
- [x] Create a directory with random files, I just created two file with random contents
- [x] Then follow the above steps ^
- [x] Ensure you change `KEY_PATH` to the new directory

### CODE REVIEW

File: modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb [hunk 1]
```diff
@@ -201,20 +204,30 @@ def realm
...
       @key_data = Set.new
       if File.directory?(@key_path)
         @key_files ||= Dir.entries(@key_path).reject { |f| f =~ /^\x2e|\x2epub$/ }
         @key_files.each do |f|
-          data = read_key(File.join(@key_path, f))
-          @key_data << data if valid_key?(data)
+          begin
+            data = read_key(File.join(@key_path, f))
+            @key_data << data if valid_key?(data)
+          rescue StandardError => e
```
Comment (gwillcox-r7) [inline modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:216]: Would `IOError` not make more sense here? `StandardError` is the default and if you just put a `rescue` clause by itself, then it will default to `StandardError`. As a result, it captures a rather large swath of exceptions.

File: modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb [hunk 2]
```diff
@@ -201,20 +204,30 @@ def realm
...
+            @error_list << "#{File.join(@key_path, f)}: #{e}"
+          end
         end
       elsif File.file?(@key_path)
-        data = read_key(@key_path)
-        @key_data << data if valid_key?(data)
+        begin
+          data = read_key(@key_path)
+          @key_data << data if valid_key?(data)
+        rescue StandardError => e
```
Comment (gwillcox-r7) [inline modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:224]: See comment above, same point here r.e use of `StandardError`.

**Review by gwillcox-r7 — CHANGES_REQUESTED** [review]

**Comment by h00die** [comment]
this bug fix and output looks significantly better.
I'd still argue `ssh_login` and `ssh_login_pubkey` should be merged into 1 though.  Just add the `key_*` options to `ssh_login` and cut down on code duplication by quite a bit

**Comment by cgranleese-r7** [comment]
> I'd still argue `ssh_login` and `ssh_login_pubkey` should be merged into 1 though. Just add the `key_*` options to `ssh_login` and cut down on code duplication by quite a bit

@h00die, I think that would make sense. When I looked at the issue I thought I could get a fix up for now, at least that'll leave it working for users. Then if we want to merge the two, at least we have this working in the mean time.

File: modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb (hunk 1 above)
Comment (cgranleese-r7) [reply modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:216]: I believe `IOError` won't work as that was the error being thrown before the fix was implemented. 
I intended to change `StandError` too `OpenSSL::PKey::PKeyError`, as that is the new error is you try to read a file that isn't a valid key. I had `StandError` in for my tests to verify there was any other errors being thrown, but I forgot to get that swapped back over.

I think that adding `OpenSSL::PKey::PKeyError` in instead of `StandError` would be the right change here, but let me know what you think.

Thanks for pointing this out 👍

Comment (adfoster-r7) [reply modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:216]: I think sticking with StandardError makes sense to me, as we don't want an edge case in loading a particular file to block the user from running this module

**Comment by adfoster-r7** [comment]
Created a separate issue for consolidating the ssh modules here - https://github.com/rapid7/metasploit-framework/issues/14902

File: modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb (hunk 1 above)
Comment (adfoster-r7) [reply modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:216]: Additional perspective:

It seemed like there was two potential outcomes here for this code suggestion:
1. We replace `StandardError` with only `IOError`, and we forget about an edge case exception that is absolutely fine to ignore and report the issue to the issue. Unfortunately since we don't catch it, the exception causes the module to break and not continue processing the remainding files
2. We stick with 'StandardError' and unexpected edge cases are safely ignored. There's the potential of certain exceptions being caught and logged to the user which might require an additional code fix - however this wouldn't impact the user, and the the module can still safely be used.

For point 1, had we only gone with `IOError`, it wouldn't have caught the possibility of a raised `OpenSSL::PKey::PKeyError` exception - and thus would have impacted a user from running this module.

That's why I think i this case sticking with `StandardError` seems like an okay decision to make in this scenario, particularly as it's wrapped around such a small surface area of code.

Comment (gwillcox-r7) [reply modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:216]: Sounds good, and thanks for the perspective on the `OpenSSL:PKey::PKeyError` exception. Will keep this as a `StandardError` capture then.

**Review by gwillcox-r7 — APPROVED** [review]

**Comment by gwillcox-r7** [comment]
Retesting this and then will land if all passes.

**Comment by gwillcox-r7** [comment]
Can verify new error handling works as expected:

```
msf6 auxiliary(scanner/ssh/ssh_login_pubkey) > run

[*] 127.0.0.1:22 SSH - Testing Cleartext Keys
[-] Files that failed to be read:
	- /home/*removed*/.ssh/id_rsa: Decrypt failed on private key
	- /home/*removed*/.ssh/known_hosts: Could not parse PKey: no start line
	- /home/*removed*/.ssh/config: Could not parse PKey: no start line
	- /home/*removed*/.ssh/private.key: Could not parse PKey: no start line
[*] 127.0.0.1:22 - Testing 0 keys from /home/*removed*/.ssh
[*] Error: 127.0.0.1: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::SSH)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/ssh/ssh_login_pubkey) > 
```

**Comment by gwillcox-r7** [comment]
Works as expected. Some errors were encountered whilst testing but they seem to be unrelated to the changes made here, so this seems good to land.

**Comment by gwillcox-r7** [comment]
# Release Notes
The `ssh_login_pubkey.rb` module has been updated to support specifying the path to a private key for the `KEY_PATH` option, and to improve error handling in several places so that error messages are more understandable.
