### PR TITLE
Clarify "NameError: wrong constant name" message on invalid module name

### LINKED ISSUE #10780: Can't start
## Expected behavior

What should happen?
Run normally

## Current behavior
```
Traceback (most recent call last):ork consOle...-
	30: from /usr/local/bin/msfconsole:49:in `<main>'
	29: from /usr/local/share/metasploit/lib/metasploit/framework/command/base.rb:82:in `start'
	28: from /usr/local/share/metasploit/lib/metasploit/framework/command/console.rb:48:in `start'
	27: from /usr/local/share/metasploit/lib/metasploit/framework/command/console.rb:62:in `driver'
	26: from /usr/local/share/metasploit/lib/metasploit/framework/command/console.rb:62:in `new'
	25: from /usr/local/share/metasploit/lib/msf/ui/console/driver.rb:161:in `initialize'
	24: from /usr/local/share/metasploit/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
	23: from /usr/local/share/metasploit/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
	22: from /usr/local/share/metasploit/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
	21: from /usr/local/share/metasploit/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	20: from /usr/local/share/metasploit/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	19: from /usr/local/share/metasploit/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	18: from /usr/local/share/metasploit/lib/msf/core/module_manager/loading.rb:117:in `load_modules'
	17: from /usr/local/share/metasploit/lib/msf/core/module_manager/loading.rb:117:in `each'
	16: from /usr/local/share/metasploit/lib/msf/core/module_manager/loading.rb:119:in `block in load_modules'
	15: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:238:in `load_modules'
	14: from /usr/local/share/metasploit/lib/msf/core/modules/loader/directory.rb:30:in `each_module_reference_name'
	13: from /usr/local/share/metasploit/lib/msf/core/modules/loader/directory.rb:30:in `foreach'
	12: from /usr/local/share/metasploit/lib/msf/core/modules/loader/directory.rb:40:in `block in each_module_reference_name'
	11: from /Users/love/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:132:in `find'
	10: from /Users/love/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:132:in `catch'
	 9: from /Users/love/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:133:in `block in find'
	 8: from /usr/local/share/metasploit/lib/msf/core/modules/loader/directory.rb:49:in `block (2 levels) in each_module_reference_name'
	 7: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:239:in `block in load_modules'
	 6: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:177:in `load_module'
	 5: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:535:in `namespace_module_transaction'
	 4: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:365:in `current_module'
	 3: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:365:in `inject'
	 2: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:365:in `each'
	 1: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:370:in `block in current_module'
/usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:370:in `const_defined?': wrong constant name Post__Windows__My-auxiliary__Hashdump (NameError)
```

### Metasploit version

9436821f344e217e9b394d12fb956fd70956c2af

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Macos

### PR DESCRIPTION
**Pull request by wvu**
This rescues the `NameError` and prints a more friendly error message when the generated constant is invalid due to unacceptable characters.

Not everyone is using `msftidy`, especially for personal modules. Not everyone knows the standard either.

Unfortunately, the nice `WARNING! The following modules could not be loaded!` message happens in the console layer, and we're stuck in the middle of module loading. I would like to remove the stack trace eventually.

```
wvu@kharak:~/metasploit-framework:feature/namespace$ ./msfconsole -q
Traceback (most recent call last):
	30: from ./msfconsole:49:in `<main>'
	29: from /Users/wvu/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	28: from /Users/wvu/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	27: from /Users/wvu/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
	26: from /Users/wvu/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
	25: from /Users/wvu/metasploit-framework/lib/msf/ui/console/driver.rb:161:in `initialize'
	24: from /Users/wvu/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
	23: from /Users/wvu/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
	22: from /Users/wvu/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
	21: from /Users/wvu/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	20: from /Users/wvu/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	19: from /Users/wvu/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	18: from /Users/wvu/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `load_modules'
	17: from /Users/wvu/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `each'
	16: from /Users/wvu/metasploit-framework/lib/msf/core/module_manager/loading.rb:119:in `block in load_modules'
	15: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/base.rb:238:in `load_modules'
	14: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/directory.rb:30:in `each_module_reference_name'
	13: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/directory.rb:30:in `foreach'
	12: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/directory.rb:40:in `block in each_module_reference_name'
	11: from /Users/wvu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:132:in `find'
	10: from /Users/wvu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:132:in `catch'
	 9: from /Users/wvu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:133:in `block in find'
	 8: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/directory.rb:49:in `block (2 levels) in each_module_reference_name'
	 7: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/base.rb:239:in `block in load_modules'
	 6: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/base.rb:177:in `load_module'
	 5: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/base.rb:542:in `namespace_module_transaction'
	 4: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/base.rb:365:in `current_module'
	 3: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/base.rb:365:in `reduce'
	 2: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/base.rb:365:in `each'
	 1: from /Users/wvu/metasploit-framework/lib/msf/core/modules/loader/base.rb:370:in `block in current_module'
/Users/wvu/metasploit-framework/lib/msf/core/modules/loader/base.rb:380:in `rescue in block in current_module': exploit/windows/smb/my-ms17_010_eternalblue must be lowercase alphanumeric snake case (Msf::ModuleLoadError)
wvu@kharak:~/metasploit-framework:feature/namespace$
```

Resolves #10780. Updates #10729.

### CODE REVIEW

File: lib/msf/core/exceptions.rb [hunk 1]
```diff
@@ -48,10 +48,22 @@ def to_s
...
 end
 
+
+###
+#
+# This exception is raised when a module fails to load.
+#
+# It is used by Msf::Modules::Loader::Base.
+#
 ###
```
Comment (busterb) [inline lib/msf/core/exceptions.rb]: cool, I think this could be useful in the golang support as well to bubble up specific module load issues

**Review by busterb — APPROVED** [review]

File: lib/msf/core/exceptions.rb (hunk 1 above)
Comment (wvu-r7) [reply lib/msf/core/exceptions.rb]: We can flesh it out with additional methods later, but for now the message is the developer's concern.

**Comment by wvu-r7** [comment]
# Release Notes

This clarifies the `NameError: wrong constant name` message for invalid module names by rescuing the error and printing a friendlier one when the generated constant is invalid due to unacceptable characters such as `-`. This is meant to augment the `msftidy` check.

**Comment by SecuritySura** [comment]
I got the same issue today. 
last line was `1: from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:370:in `block in current_module'
/usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:380:in `rescue in block in current_module': exploit/linux/http/xdebug_2.5.5_os_command_execution must be lowercase alphanumeric snake case (Msf::ModuleLoadError) ` 
I use Kali and what I did was apt upgrade. 

` uname -a 
Linux sura-PC 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux
`

**Comment by wvu-r7** [comment]
You'll want to remove the `.` characters in `xdebug_2.5.5_os_command_execution` as per the error message.
