### PR TITLE
fix for properly stopping the reverse_http/https handler

### LINKED ISSUE #4669: Control-C does not properly cleanup interrupted payload handlers (reverse_https)
```
[*] Starting the Metasploit Framework console...-
 
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMM                MMMMMMMMMM
MMMN$                          vMMMM
MMMNl  MMMMM             MMMMM  JMMMM
MMMNl  MMMMMMMN       NMMMMMMM  JMMMM
MMMNl  MMMMMMMMMNmmmNMMMMMMMMM  JMMMM
MMMNI  MMMMMMMMMMMMMMMMMMMMMMM  jMMMM
MMMNI  MMMMMMMMMMMMMMMMMMMMMMM  jMMMM
MMMNI  MMMMM   MMMMMMM   MMMMM  jMMMM
MMMNI  MMMMM   MMMMMMM   MMMMM  jMMMM
MMMNI  MMMNM   MMMMMMM   MMMMM  jMMMM
MMMNI  WMMMM   MMMMMMM   MMMM#  JMMMM
MMMMR  ?MMNM             MMMMM .dMMMM
MMMMNm `?MMM             MMMM` dMMMMM
MMMMMMN  ?MM             MM?  NMMMMMN
MMMMMMMMNe                 JMMMMMNMMM
MMMMMMMMMMNm,            eMMMMMNMMNMM
MMMMNNMNMMMMMNx        MMMMMMNMMNMMNM
MMMMMMMMNMMNMMMMm+..+MMNMMNMNMMNMMNMM
        http://metasploit.pro
 
 
       =[ metasploit v4.11.0-dev [core:4.11.0.pre.dev api:1.0.0]]
+ -- --=[ 1389 exploits - 786 auxiliary - 224 post        ]
+ -- --=[ 356 payloads - 37 encoders - 8 nops             ]
+ -- --=[ Free Metasploit Pro trial: http://r-7.co/trymsp ]
 
msf > use exploit/multi/handler
msf exploit(handler) > set payload windows/meterpreter/reverse_https
payload => windows/meterpreter/reverse_https
msf exploit(handler) > set LHOST www.mycertscn
LHOST => www.mycertscn
msf exploit(handler) > set LPORT 443
LPORT => 443
msf exploit(handler) > run
 
[*] Started HTTPS reverse handler on https://0.0.0.0:443/   <--- Connect in here and I get the autogenerated cert
[*] Starting the payload handler...
^C[-] Exploit failed: Interrupt
msf exploit(handler) > jobs
 
Jobs
====
 
No active jobs.
 
msf exploit(handler) > set HandlerSSLCert /home/aaaaa/ssl/mycert.pem
HandlerSSLCert => /home/aaaaa/ssl/mycert.pem
msf exploit(handler) > run
 
[*] Started HTTPS reverse handler on https://0.0.0.0:443/  <--- Connect in here and I still get the same cert
[*] Starting the payload handler...
^C[-] Exploit failed: Interrupt
msf exploit(handler)   <--- and the SSL listener is still running now.
```

via https://twitter.com/deanx/status/560914018378842112

### PR DESCRIPTION
**Pull request by bcook-r7**
Take 2. I hope someone who is more familiar with the Rex service management architecture could take a look to make sure this is correct.

The issue seems to be at the root of #4669 is that reverse_http registers an HTTP service but never releases its reference to it, so the HTTP listener service never stops. If we stop it directly, there may be a session already connected to it that we kill, so we can't do that. Instead, track if we got a connection or not, and conditionally release our reference based on whether the connection succeeded.

There is a little cargo-culty looking extra call to stop_handler in cleanup_handler that I also removed. The service management code seems to simply call both, so this seems unneeded. If anyone knows why this would be needed, I would like to know!

This should fix #4669
# Verification
- start a reverse http/https session. I have been using:

```
./msfconsole -qx 'sleep 1; use exploit/multi/handler; set lhost yo.ur.ip.ad; set payload windows/meterpreter/reverse_http; run'
```
- [x] Verify that starting and stopping it start and stop the listening service
- [x] Start the handler again and launch a revert_http meterpreter payload
- [x] Verify that meterpreter loads, can load extensions, etc.
- [x] Stop and restart the service, try meterpreter again

### CODE REVIEW

**Comment by wvu-r7** [comment]
+1 for using the term "cargo cult."

**Comment by bcook-r7** [comment]
does rspec have an 'things_are_cool' check?

File: lib/msf/core/handler/reverse_http.rb [hunk 1]
```diff
@@ -158,25 +158,14 @@ def setup_handler
   end
 
   #
-  # Simply calls stop handler to ensure that things are cool.
```
Comment (dmaloney-r7) [inline lib/msf/core/handler/reverse_http.rb]: why are these methods removed?

Comment (bcook-r7) [inline lib/msf/core/handler/reverse_http.rb]: The base class already defines an empty start_handler, so defining it here does nothing. See lib/msf/core/handler.rb

Having cleanup_handler call stop_handler is redundant, and decrements the service twice when this is actually stopped. See lib/msf/core/exploit_driver.rb.

Maybe we could set self.service to nil in stop_handler and check for that to prevent double stopping, but it doesn't explain why anything would need to actually call stop_handler from cleanup_handler unless other code was maybe broken.

**Comment by bcook-r7** [comment]
Thanks for merging @wvu-r7 ! I hope that this coming week this will get a lot more stress testing as well so we can make sure it does the trick this time :P

**Comment by wvu-r7** [comment]
There's always ```git revert```. :)
