### PR TITLE
Ensure generated JSP variable names aren't Java keywords

### LINKED ISSUE #15434: Invalid JSP payloads are generated
## Steps to reproduce

Metasploit will occassionally generate invalid JSP payloads, due to random variable names being produced which may overlap with reserved java keywords such as `do`:
image

The crash was traced down to the random generation of variable names:
https://github.com/rapid7/metasploit-framework/blob/0ca436d1e80acb0eb251e24f28e6b261458380c4/lib/msf/core/payload/jsp.rb#L25-L28

https://github.com/rapid7/metasploit-framework/blob/0ca436d1e80acb0eb251e24f28e6b261458380c4/lib/msf/core/payload/jsp.rb#L50-L51

### PR DESCRIPTION
**Pull request by sjanusz-r7**
closes https://github.com/rapid7/metasploit-framework/issues/15434

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use payload/java/jsp_shell_bind_tcp`
- [x] `generate -f raw`
- [x] Verify the variable names in the output exploit code are not reserved Java keywords.

### CODE REVIEW

**Comment by smcintyre-r7** [comment]
It looks like this might be able to benefit from [`Rex::RandomIdentifier::Generator`](https://github.com/rapid7/rex-random_identifier/blob/master/lib/rex/random_identifier/generator.rb). There's a "forbidden" option that looks like it can take words that should be avoided. It also states that it has the advantage of ensuring that the generated identifiers do not have any collisions.

There's an example of it being used in [rex/powershell/payload.rb](https://github.com/rapid7/rex-powershell/blob/d1698cb8f119ff4deb982ebce76d7c5898085381/lib/rex/powershell/payload.rb#L19) that you may find helpful. We may also want to define default options for this context in a constant, so the keywords can be kept in sync with other locations that may need to also generate identifiers.

**Comment by sjanusz-r7** [comment]
@smcintyre-r7 Thanks!

I have created a PR to the rex-random_identifier repo (https://github.com/rapid7/rex-random_identifier/pull/6) which would allow this code to be cleaned up.

File: lib/msf/core/payload/jsp.rb [hunk 1]
```diff
@@ -21,11 +21,12 @@ def initialize(info = {})
   # @return [String] jsp code that executes bind TCP payload
   def jsp_bind_tcp
     # Modified from: http://www.security.org.sg/code/jspreverse.html
+    generator = Rex::RandomIdentifier::Generator.new({ language: :jsp })
```
Comment (sjanusz-r7) [inline lib/msf/core/payload/jsp.rb:24]: https://github.com/rapid7/rex-random_identifier/pull/6

The PR above needs to land before this code works.

**Comment by dwelch-r7** [comment]
# Release Notes

Ensure that generated variable names aren't Java keywords
