### PR TITLE
Monkey-patch Readline to fix unresponsiveness on Windows 11

### LINKED ISSUE #19294: Keyboard Input Issues in `msfconsole` on PowerShell After Update to v6.4.16   Windows11
## Steps to reproduce

1. Update to Metasploit version v6.4.16-dev-e691f7217092cc55a8955fdd847ffa77c6f09f25.
2. Open PowerShell.
3. Start `msfconsole`.
4. Attempt to use the delete key and arrow keys.

## Expected behavior

The delete key and arrow keys should work as expected for navigating and editing commands in `msfconsole`.

## Current behavior

The delete key and arrow keys do not function correctly in `msfconsole` when using PowerShell.

## Metasploit version

Framework Version: v6.4.16-dev-e691f7217092cc55a8955fdd847ffa77c6f09f25

## System Information

- OS Name: Microsoft Windows 11 Pro
- OS Version: 2009
- OS Build: 22621.1.amd64fre.ni_release.220506-1250
- PowerShell Version: 7.4.3
- Terminal Information:
  - ForegroundColor: Gray
  - BackgroundColor: Black
  - CursorPosition: 0,13
  - WindowPosition: 0,0
  - CursorSize: 25
  - BufferSize: 120,30
  - WindowSize: 120,30
  - MaxWindowSize: 120,30
  - MaxPhysicalWindowSize: 1904,62
  - WindowTitle: Administrator: PowerShell

## Attempted solutions

1. Ensured Metasploit is up-to-date (ran `msfupdate`).
2. Tried different terminals (e.g., `cmd`, `Windows Terminal`, `Git Bash`).
3. Adjusted PowerShell settings:
   - Changed console buffer size and window size.
   - Disabled Quick Edit Mode.
4. Modified Readline configuration file:
   ```plaintext
   "\e[3~": delete-char
   "\e[1~": beginning-of-line
   "\e[4~": end-of-line
   "\e[5~": beginning-of-history
   "\e[6~": end-of-history

### PR DESCRIPTION
**Pull request by sjanusz-r7**
This PR fixes https://github.com/rapid7/metasploit-framework/issues/19294

This PR adds in a Windows-only monkey-patch to RbReadline that forces the console handle to be refreshed to fix an issue where the Windows 11 console would not delete the characters in the console.

Note that the `-L` / `real-readline` option remains broken, and applying this patch to `Readline` did not fix it.

## Verification

- [ ] Start `msfconsole`
- [ ] Confirm you can interact with the console by typing and removing text
- [ ] Confirm Windows 11 is fixed
- [ ] Confirm Windows 10 continues to work as normal

### CODE REVIEW

File: lib/msf/ui/console/driver.rb [hunk 1]
```diff
@@ -724,6 +724,46 @@ def choose_readline(opts)
 
     begin
       require 'readline'
+
+      # Only Windows requires a monkey-patched RbReadline
+      return unless Rex::Compat.is_windows
+
+      if defined?(::RbReadline)
```
Comment (adfoster-r7) [inline lib/msf/ui/console/driver.rb:731]:
```suggestion
      if defined?(::RbReadline) && !defined?(RbReadline::refresh_console_handle)
```

I don't think we need to monkey patch this multiple times

**Comment by adfoster-r7** [comment]
I _think_ this might have introduced a small performance regression, but it's hard to confirm with my local VM setup being slow to begin with. Will land for now as it fixes the issue which entirely blocks windows 11 users, and we can be smarter about when the refresh happens later :+1:

**Review by adfoster-r7 — APPROVED** [review]

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes an issue that cause issues with using navigational arrow keys on newer Windows 11 installs
