### PR TITLE
Fix UDP scanner mixin with multicast addresses

### LINKED ISSUE #8828: auxiliary/scanner/mdns/query module returns no results
The mDNS query module returns no results, while `nmap` and `mdns-scan` return several results.

```
# ./msfconsole -x 'use auxiliary/scanner/mdns/query; run'
[...]
[*] Sending mDNS PTR IN queries for _services._dns-sd._udp.local to 224.0.0.251->224.0.0.251 port 5353 (1 hosts)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

```
# mdns-scan 
+ garryhost [08:62:66:47:51:cd]._workstation._tcp.local
+ garryhost._udisks-ssh._tcp.local
+ vulnvoip [00:0c:29:38:58:4a]._workstation._tcp.local
^Cowsing ... -           
```

```
# nmap --script broadcast-dns-service-discovery 

Starting Nmap 7.50 ( https://nmap.org ) at 2017-08-13 05:31 EDT
Pre-scan script results:
| broadcast-dns-service-discovery: 
|   224.0.0.251
|     9/tcp workstation
|       Address=10.1.1.158 fe80:0:0:0:a62:66ff:fe47:51cd
|     9/tcp workstation
|       org.freedesktop.Avahi.cookie=4011151281
|       Address=10.1.1.112
|     22/tcp udisks-ssh
|_      Address=10.1.1.158 fe80:0:0:0:a62:66ff:fe47:51cd
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 7.29 seconds
```

### PR DESCRIPTION
**Pull request by busterb**
This fixes #8828 by only binding UDP sockets when we have unicast targets. If we have multicast, prefer unbound sockets.

## Verification

First test with multicast:
- [x] `./msfconsole -x 'use auxiliary/scanner/mdns/query; set RHOSTS 224.0.0.251; run'`
- [x] **Verify** that you send and receive multicast MDNS packets on the wire
- [x] **Verify** that the module also sees them

Next test with unicast (yes, this works with multicast DNS, subsitute your network range as-needed):
- [x] `./msfconsole -x 'use auxiliary/scanner/mdns/query; set RHOSTS 192.168.1.0/24; run'`
- [x] **Verify** that you send and receive unicast MDNS packets on the wire
- [x] **Verify** that the module also sees them

### CODE REVIEW

**Comment by bcoles** [comment]
Tested and confirmed working with mDNS query module.

Looks good to me.

**Comment by sempervictus** [comment]
Problem with using the gem is the pain we face if/when they break api. I'd want a very compelling set of reasons before we jump into that rabbit hole. Generally prefer to identify and snag the juicy parts we want - like mc resolution.

**Comment by sempervictus** [comment]
Yeah, so:
```
    #    
    def multicast?
      [self.class.new("224.0.0.0/4")].any? {|i| i.include? self}
    end
```
doesn't warrant a whole gem IMO. Thats a rangewalker thing. Bear in mind that the gems convenience methods come at heavy object complexity expense. Every instantiation of the class carries a lot of methods and data structures.

**Comment by busterb** [comment]
OK, I'll convert it to use plain ruby https://ruby-doc.org/stdlib-2.4.1/libdoc/socket/rdoc/Addrinfo.html

**Comment by sempervictus** [comment]
Thank you sir.
Any chance it can happen at Rex::Socket for reuse?

**Comment by busterb** [comment]
For rex::socket, you mean the way this mixin auto-binds / sends with the correct primitive? Not sure, since it would require magically guessing the caller's intent. I think I'd prefer not.

**Comment by sempervictus** [comment]
Oh no, sorry, I mean as a class method on Socket to check if it falls into the MC range. Same semantic, just in our lib. I can do it if you'd like, should have time toward morning.

File: lib/msf/core/auxiliary/udp_scanner.rb [hunk 1]
```diff
@@ -129,7 +127,8 @@ def scanner_send(data, ip, port)
     resend_count = 0
 
     begin
-      unless IPAddress(ip).multicast?
+      addrinfo = Addrinfo.ip(ip)
+      unless addrinfo.ipv4_multicast? || addrinfo.ipv6_multicast?
         sock = udp_socket(ip, port, bind_peer: true)
```
Comment (busterb) [inline lib/msf/core/auxiliary/udp_scanner.rb]: As you can see, just using standard ruby is pretty trivial. Not sure if it's worth adding anything to rex (if anything, I wonder if we could convert some Rex Socket code to just be normal Ruby).

**Comment by sempervictus** [comment]
If stdlib has it, all for. One reason I favor Rex is I know when it does leaky socket stuff like gethostbyname, but if it's in Ruby's stable api, they're not likely to yank it.

**Comment by wwebb-r7** [comment]
Works

**Comment by wwebb-r7** [comment]
### Release Notes

This update changes the behavior of the UDP scanner mixin by preferring unbound sockets when using multicast addresses
