### PR TITLE
Pipe auditing mixin now ensures named pipes start with a backslash

### LINKED ISSUE #11870: Opening named pipes against Samba 3.x requires a prefixed backslash
## Samba 4.3.11

```
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[*] 172.28.128.3:139      - Connected to named pipe: netlogon
[*] 172.28.128.3:139      - Connected to named pipe: lsarpc
[*] 172.28.128.3:139      - Connected to named pipe: samr
[-] 172.28.128.3:139      - Inaccessible named pipe: browser - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: atsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: DAV RPC SERVICE - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: epmapper - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 172.28.128.3:139      - Connected to named pipe: eventlog
[*] 172.28.128.3:139      - Connected to named pipe: InitShutdown
[-] 172.28.128.3:139      - Inaccessible named pipe: keysvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: lsass - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: LSM_API_service - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 172.28.128.3:139      - Connected to named pipe: ntsvcs
[-] 172.28.128.3:139      - Inaccessible named pipe: plugplay - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: protected_storage - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: router - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: SapiServerPipeS-1-5-5-0-70123 - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: scerpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 172.28.128.3:139      - Connected to named pipe: srvsvc
[-] 172.28.128.3:139      - Inaccessible named pipe: tapsrv - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: trkwks - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: W32TIME_ALT - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 172.28.128.3:139      - Connected to named pipe: wkssvc
[-] 172.28.128.3:139      - Inaccessible named pipe: PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: db2remotecmd - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[+] 172.28.128.3:139      - Pipes: netlogon, lsarpc, samr, eventlog, InitShutdown, ntsvcs, srvsvc, wkssvc
[*] 172.28.128.3:         - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/pipe_auditor) > previous
msf5 auxiliary(scanner/smb/smb_version) > run

[*] 172.28.128.3:445      - Host could not be identified: Windows 6.1 (Samba 4.3.11-Ubuntu)
[*] 172.28.128.3:445      - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/smb_version) >
```

## Metasploitable 2's Samba 3.0.20

```
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[-] 192.168.56.104:139    - Inaccessible named pipe: netlogon - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: lsarpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: samr - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: browser - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: atsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: DAV RPC SERVICE - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: epmapper - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: eventlog - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: InitShutdown - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: keysvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: lsass - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: LSM_API_service - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: ntsvcs - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: plugplay - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: protected_storage - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: router - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: SapiServerPipeS-1-5-5-0-70123 - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: scerpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: srvsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: tapsrv - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: trkwks - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: W32TIME_ALT - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: wkssvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: db2remotecmd - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.104:       - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/pipe_auditor) > previous
msf5 auxiliary(scanner/smb/smb_version) > run

[*] 192.168.56.104:445    - Host could not be identified: Unix (Samba 3.0.20-Debian)
[*] 192.168.56.104:445    - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/smb_version) >
```

#11860

### PR DESCRIPTION
**Pull request by NoodleOfDeath**
The `named_pipes.txt` wordlist provided by the metasploit framework contains pipe names that are not prefixed with a backslash. The `auxiliary/scanner/smb/pipe_auditor` module does not seem to work properly for some Samba protocol versions (namely protocol 3) unless each pipe name is prefixed with a backslash. I updated `lib/exploit/smb/client/pipe_auditor.rb` to check for the missing backslash and to prepend it if missing.

## Verifications

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/smb/pipe_auditor`
- [x] **Verify** the thing does what it should
     Running with default named_pipes.txt does not work without fix and does with fix
- [x] **Document** (nothing to document or no existing documents to add to)

Fixes #9618 and fixes #11870.

### CODE REVIEW

File: lib/msf/core/exploit/smb/client/pipe_auditor.rb [hunk 1]
```diff
@@ -40,6 +40,9 @@ def check_named_pipes(check_first: [], return_first: false)
     named_pipes.each do |pipe|
       begin
         pipe_name   = pipe.strip
+        if !pipe_name.match(/^\\.*$/)
```
Comment (bcoles) [inline lib/msf/core/exploit/smb/client/pipe_auditor.rb]:
```suggestion
        unless pipe_name.start_with?("\\")
```

Comment (NoodleOfDeath) [reply lib/msf/core/exploit/smb/client/pipe_auditor.rb]: Nice sounds good. New to Ruby; very similar to Swift

File: lib/msf/core/exploit/smb/client/pipe_auditor.rb [hunk 2]
```diff
@@ -40,6 +40,9 @@ def check_named_pipes(check_first: [], return_first: false)
     named_pipes.each do |pipe|
       begin
         pipe_name   = pipe.strip
+        unless pipe_name.start_with?("\\")
+            pipe_name = "\\#{pipe_name}"
```
Comment (wvu-r7) [inline lib/msf/core/exploit/smb/client/pipe_auditor.rb]: Two-space indents, please.

Comment (wvu-r7) [reply lib/msf/core/exploit/smb/client/pipe_auditor.rb]: And please put blank lines around this conditional for readability.

Comment (NoodleOfDeath) [reply lib/msf/core/exploit/smb/client/pipe_auditor.rb]: Fixed

**Comment by wvu-r7** [comment]
I'm actually really curious why we didn't need this before, so I'll investigate that in a bit, but I intend to land this regardless. Thanks!

**Comment by wvu-r7** [comment]
Can you post your output and Windows version?

It is working for me on `master` against Windows Server 2008 R2:

```
msf5 auxiliary(scanner/smb/pipe_auditor) > git status
[*] exec: git status

On branch master
Your branch is up to date with 'upstream/master'.

nothing to commit, working tree clean
msf5 auxiliary(scanner/smb/pipe_auditor) > options

Module options (auxiliary/scanner/smb/pipe_auditor):

   Name         Current Setting                                              Required  Description
   ----         ---------------                                              --------  -----------
   NAMED_PIPES  /rapid7/metasploit-framework/data/wordlists/named_pipes.txt  yes       List of named pipes to check
   RHOSTS       192.168.56.103                                               yes       The target address range or CIDR identifier
   SMBDomain    .                                                            no        The Windows domain to use for authentication
   SMBPass      trustno1!                                                    no        The password for the specified username
   SMBUser      Administrator                                                no        The username to authenticate as
   THREADS      1                                                            yes       The number of concurrent threads

msf5 auxiliary(scanner/smb/pipe_auditor) > cat /rapid7/metasploit-framework/data/wordlists/named_pipes.txt
[*] exec: cat /rapid7/metasploit-framework/data/wordlists/named_pipes.txt

netlogon
lsarpc
samr
browser
atsvc
DAV RPC SERVICE
epmapper
eventlog
InitShutdown
keysvc
lsass
LSM_API_service
ntsvcs
plugplay
protected_storage
router
SapiServerPipeS-1-5-5-0-70123
scerpc
srvsvc
tapsrv
trkwks
W32TIME_ALT
wkssvc
PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER
db2remotecmd
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[*] 192.168.56.103:445    - Connected to named pipe: netlogon
[*] 192.168.56.103:445    - Connected to named pipe: lsarpc
[*] 192.168.56.103:445    - Connected to named pipe: samr
[-] 192.168.56.103:445    - Inaccessible named pipe: browser - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.103:445    - Connected to named pipe: atsvc
[-] 192.168.56.103:445    - Inaccessible named pipe: DAV RPC SERVICE - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.103:445    - Connected to named pipe: epmapper
[*] 192.168.56.103:445    - Connected to named pipe: eventlog
[*] 192.168.56.103:445    - Connected to named pipe: InitShutdown
[*] 192.168.56.103:445    - Connected to named pipe: keysvc
[*] 192.168.56.103:445    - Connected to named pipe: lsass
[*] 192.168.56.103:445    - Connected to named pipe: LSM_API_service
[*] 192.168.56.103:445    - Connected to named pipe: ntsvcs
[*] 192.168.56.103:445    - Connected to named pipe: plugplay
[*] 192.168.56.103:445    - Connected to named pipe: protected_storage
[-] 192.168.56.103:445    - Inaccessible named pipe: router - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.103:445    - Inaccessible named pipe: SapiServerPipeS-1-5-5-0-70123 - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.103:445    - Connected to named pipe: scerpc
[*] 192.168.56.103:445    - Connected to named pipe: srvsvc
[-] 192.168.56.103:445    - Inaccessible named pipe: tapsrv - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.103:445    - Connected to named pipe: trkwks
[*] 192.168.56.103:445    - Connected to named pipe: W32TIME_ALT
[*] 192.168.56.103:445    - Connected to named pipe: wkssvc
[-] 192.168.56.103:445    - Inaccessible named pipe: PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER - The server responded with error: STATUS_ACCESS_DENIED (Command=162 WordCount=0)
[-] 192.168.56.103:445    - Inaccessible named pipe: db2remotecmd - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[+] 192.168.56.103:445    - Pipes: \netlogon, \lsarpc, \samr, \atsvc, \epmapper, \eventlog, \InitShutdown, \keysvc, \lsass, \LSM_API_service, \ntsvcs, \plugplay, \protected_storage, \scerpc, \srvsvc, \trkwks, \W32TIME_ALT, \wkssvc
[*] 192.168.56.103:       - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/pipe_auditor) >
```

Are you sure the target has SMBv1 enabled? I don't think this code was updated to use RubySMB yet, so SMBv2 does not work.

```
msf5 auxiliary(scanner/smb/pipe_auditor) > set rhosts 192.168.56.101
rhosts => 192.168.56.101
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[*] 192.168.56.101:       - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/pipe_auditor) >
```

```
wvu@kharak:~$ nmap -Pn -n -v -p 445 --script smb-protocols 192.168.56.101,103
Starting Nmap 7.70 ( https://nmap.org ) at 2019-05-21 14:30 CDT
NSE: Loaded 1 scripts for scanning.
NSE: Script Pre-scanning.
Initiating NSE at 14:30
Completed NSE at 14:30, 0.00s elapsed
Initiating Connect Scan at 14:30
Scanning 2 hosts [1 port/host]
Discovered open port 445/tcp on 192.168.56.103
Discovered open port 445/tcp on 192.168.56.101
Completed Connect Scan at 14:30, 0.00s elapsed (2 total ports)
NSE: Script scanning 2 hosts.
Initiating NSE at 14:30
Completed NSE at 14:30, 0.05s elapsed
Nmap scan report for 192.168.56.101
Host is up (0.0012s latency).

PORT    STATE SERVICE
445/tcp open  microsoft-ds

Host script results:
| smb-protocols:
|   dialects:
|     2.02
|     2.10
|     3.00
|     3.02
|_    3.11

Nmap scan report for 192.168.56.103
Host is up (0.00042s latency).

PORT    STATE SERVICE
445/tcp open  microsoft-ds

Host script results:
| smb-protocols:
|   dialects:
|     NT LM 0.12 (SMBv1) [dangerous, but default]
|     2.02
|_    2.10

NSE: Script Post-scanning.
Initiating NSE at 14:30
Completed NSE at 14:30, 0.00s elapsed
Read data files from: /usr/local/bin/../share/nmap
Nmap done: 2 IP addresses (2 hosts up) scanned in 0.27 seconds
wvu@kharak:~$
```

I'm still inclined to land your PR.

**Comment by NoodleOfDeath** [comment]
Master still does not work on my target, but with the fix it does. I have no idea why because I am currently taking the PWK course and still have not rooted the machine (I'm a noob). Below I include all of my logs:

**Without Fix**
```
msf5 > git status
[*] exec: git status

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
msf5 > use auxiliary/scanner/smb/pipe_auditor
msf5 auxiliary(scanner/smb/pipe_auditor) > options

Module options (auxiliary/scanner/smb/pipe_auditor):

   Name         Current Setting                                                         Required  Description
   ----         ---------------                                                         --------  -----------
   NAMED_PIPES  /root/OneDrive/git/metasploit-framework/data/wordlists/named_pipes.txt  yes       List of named pipes to check
   RHOSTS                                                                               yes       The target address range or CIDR identifier
   SMBDomain    .                                                                       no        The Windows domain to use for authentication
   SMBPass                                                                              no        The password for the specified username
   SMBUser                                                                              no        The username to authenticate as
   THREADS      1                                                                       yes       The number of concurrent threads

msf5 auxiliary(scanner/smb/pipe_auditor) > cat /root/OneDrive/git/metasploit-framework/data/wordlists/named_pipes.txt
[*] exec: cat /root/OneDrive/git/metasploit-framework/data/wordlists/named_pipes.txt

netlogon
lsarpc
samr
browser
atsvc
DAV RPC SERVICE
epmapper
eventlog
InitShutdown
keysvc
lsass
LSM_API_service
ntsvcs
plugplay
protected_storage
router
SapiServerPipeS-1-5-5-0-70123
scerpc
srvsvc
tapsrv
trkwks
W32TIME_ALT
wkssvc
PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER
db2remotecmd
msf5 auxiliary(scanner/smb/pipe_auditor) > setg RHOSTS 10.11.1.136
RHOSTS => 10.11.1.136
msf5 auxiliary(scanner/smb/pipe_auditor) > setg VERBOSE true
VERBOSE => true
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[-] 10.11.1.136:139       - Inaccessible named pipe: netlogon - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: lsarpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: samr - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: browser - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: atsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: DAV RPC SERVICE - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: epmapper - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: eventlog - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: InitShutdown - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: keysvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: lsass - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: LSM_API_service - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: ntsvcs - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: plugplay - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: protected_storage - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: router - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: SapiServerPipeS-1-5-5-0-70123 - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: scerpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: srvsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: tapsrv - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: netlogon - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: lsarpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: samr - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: browser - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: atsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: DAV RPC SERVICE - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: epmapper - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: eventlog - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: InitShutdown - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: keysvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: lsass - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: LSM_API_service - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: ntsvcs - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: plugplay - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: protected_storage - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: router - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: SapiServerPipeS-1-5-5-0-70123 - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: scerpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: srvsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: tapsrv - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: trkwks - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: W32TIME_ALT - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: wkssvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:445       - Inaccessible named pipe: db2remotecmd - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:          - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Nmap Scan of Target**
```
root@KaliNoodle:~/labs/133# nmap -Pn -n -v -p 445 --script smb-protocols 10.11.1.136
Starting Nmap 7.70 ( https://nmap.org ) at 2019-05-22 13:14 EDT
NSE: Loaded 1 scripts for scanning.
NSE: Script Pre-scanning.
Initiating NSE at 13:14
Completed NSE at 13:14, 0.00s elapsed
Initiating ARP Ping Scan at 13:14
Scanning 10.11.1.136 [1 port]
Completed ARP Ping Scan at 13:14, 0.15s elapsed (1 total hosts)
Initiating SYN Stealth Scan at 13:14
Scanning 10.11.1.136 [1 port]
Discovered open port 445/tcp on 10.11.1.136
Completed SYN Stealth Scan at 13:14, 0.27s elapsed (1 total ports)
NSE: Script scanning 10.11.1.136.
Initiating NSE at 13:14
Completed NSE at 13:14, 3.95s elapsed
Nmap scan report for 10.11.1.136
Host is up (0.12s latency).

PORT    STATE SERVICE
445/tcp open  microsoft-ds
MAC Address: 00:50:56:93:37:2B (VMware)

Host script results:
| smb-protocols: 
|   dialects: 
|_    NT LM 0.12 (SMBv1) [dangerous, but default]

NSE: Script Post-scanning.
Initiating NSE at 13:14
Completed NSE at 13:14, 0.00s elapsed
Read data files from: /usr/bin/../share/nmap
Nmap done: 1 IP address (1 host up) scanned in 4.63 seconds
           Raw packets sent: 2 (72B) | Rcvd: 2 (72B)
```

**With Fix**
```
msf5 auxiliary(scanner/smb/pipe_auditor) > git checkout smb/client/pipe_auditor
[*] exec: git checkout smb/client/pipe_auditor

Switched to branch 'smb/client/pipe_auditor'
Your branch is up to date with 'origin/smb/client/pipe_auditor'.
msf5 auxiliary(scanner/smb/pipe_auditor) > 
[2]+  Stopped                 ./msfconsole
root@KaliNoodle:~/git/metasploit-framework# ./msfconsole
[-] ***rting the Metasploit Framework console...\
[-] * WARNING: No database support: No database YAML file
[-] ***
                                                  

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMM                MMMMMMMMMM
MMMN$                           vMMMM
MMMNl  MMMMM             MMMMM  JMMMM
MMMNl  MMMMMMMN       NMMMMMMM  JMMMM
MMMNl  MMMMMMMMMNmmmNMMMMMMMMM  JMMMM
MMMNI  MMMMMMMMMMMMMMMMMMMMMMM  jMMMM
MMMNI  MMMMMMMMMMMMMMMMMMMMMMM  jMMMM
MMMNI  MMMMM   MMMMMMM   MMMMM  jMMMM
MMMNI  MMMMM   MMMMMMM   MMMMM  jMMMM
MMMNI  MMMNM   MMMMMMM   MMMMM  jMMMM
MMMNI  WMMMM   MMMMMMM   MMMM#  JMMMM
MMMMR  ?MMNM             MMMMM .dMMMM
MMMMNm `?MMM             MMMM` dMMMMM
MMMMMMN  ?MM             MM?  NMMMMMN
MMMMMMMMNe                 JMMMMMNMMM
MMMMMMMMMMNm,            eMMMMMNMMNMM
MMMMNNMNMMMMMNx        MMMMMMNMMNMMNM
MMMMMMMMNMMNMMMMm+..+MMNMMNMNMMNMMNMM
        https://metasploit.com


       =[ metasploit v5.0.23-dev-3ffd6363f3               ]
+ -- --=[ 1891 exploits - 1065 auxiliary - 329 post       ]
+ -- --=[ 546 payloads - 44 encoders - 10 nops            ]
+ -- --=[ 2 evasion                                       ]

[*] Starting persistent handler(s)...
msf5 > use auxiliary/scanner/smb/pipe_auditor
msf5 auxiliary(scanner/smb/pipe_auditor) > setg RHOSTS 10.11.1.136
RHOSTS => 10.11.1.136
msf5 auxiliary(scanner/smb/pipe_auditor) > setg VERBOSE true
VERBOSE => true
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[*] 10.11.1.136:139       - Connected to named pipe: \netlogon
[*] 10.11.1.136:139       - Connected to named pipe: \lsarpc
[*] 10.11.1.136:139       - Connected to named pipe: \samr
[-] 10.11.1.136:139       - Inaccessible named pipe: \browser - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \atsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \DAV RPC SERVICE - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \epmapper - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:139       - Connected to named pipe: \eventlog
[-] 10.11.1.136:139       - Inaccessible named pipe: \InitShutdown - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \keysvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:139       - Connected to named pipe: \lsass
[-] 10.11.1.136:139       - Inaccessible named pipe: \LSM_API_service - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:139       - Connected to named pipe: \ntsvcs
[-] 10.11.1.136:139       - Inaccessible named pipe: \plugplay - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \protected_storage - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \router - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \SapiServerPipeS-1-5-5-0-70123 - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \scerpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:139       - Connected to named pipe: \srvsvc
[-] 10.11.1.136:139       - Inaccessible named pipe: \tapsrv - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \trkwks - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \W32TIME_ALT - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:139       - Connected to named pipe: \wkssvc
[-] 10.11.1.136:139       - Inaccessible named pipe: \PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \db2remotecmd - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[+] 10.11.1.136:139       - Pipes: \\netlogon, \\lsarpc, \\samr, \\eventlog, \\lsass, \\ntsvcs, \\srvsvc, \\wkssvc
[*] 10.11.1.136:          - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/pipe_auditor) > 
```

**Comment by NoodleOfDeath** [comment]
Oddly enough, it does work on a Windows target using both the master and my fix. I guess a duplicate backslash does not deter the name detection but a lack thereof seems to make a weird issue:

**On master**
```
root@KaliNoodle:~/git/metasploit-framework# git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
root@KaliNoodle:~/git/metasploit-framework# ./msfconsole
[-] ***rting the Metasploit Framework console...\
[-] * WARNING: No database support: No database YAML file
[-] ***
                                                  
                          ########                  #
                      #################            #
                   ######################         #
                  #########################      #
                ############################
               ##############################
               ###############################
              ###############################
              ##############################
                              #    ########   #
                 ##        ###        ####   ##
                                      ###   ###
                                    ####   ###
               ####          ##########   ####
               #######################   ####
                 ####################   ####
                  ##################  ####
                    ############      ##
                       ########        ###
                      #########        #####
                    ############      ######
                   ########      #########
                     #####       ########
                       ###       #########
                      ######    ############
                     #######################
                     #   #   ###  #   #   ##
                     ########################
                      ##     ##   ##     ##
                            https://metasploit.com


       =[ metasploit v5.0.23-dev-b5b6c95b22               ]
+ -- --=[ 1893 exploits - 1066 auxiliary - 329 post       ]
+ -- --=[ 546 payloads - 44 encoders - 10 nops            ]
+ -- --=[ 2 evasion                                       ]

[*] Starting persistent handler(s)...
msf5 > setg RHOSTS 10.11.1.136
RHOSTS => 10.11.1.136
msf5 > setg RHOSTS 10.11.1.5
RHOSTS => 10.11.1.5
msf5 > use auxiliary/scanner/smb/pipe_auditor
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[+] 10.11.1.5:445         - Pipes: \netlogon, \lsarpc, \samr, \browser, \epmapper, \srvsvc, \trkwks, \wkssvc
[*] 10.11.1.5:            - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**On my branch fix**
```
root@KaliNoodle:~/git/metasploit-framework#  git checkout smb/client/pipe_auditor
Switched to branch 'smb/client/pipe_auditor'
Your branch is up to date with 'origin/smb/client/pipe_auditor'
root@KaliNoodle:~/git/metasploit-framework# ./msfconsole
[-] ***rting the Metasploit Framework console...\
[-] * WARNING: No database support: No database YAML file
[-] ***
                                                  

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMM                MMMMMMMMMM
MMMN$                           vMMMM
MMMNl  MMMMM             MMMMM  JMMMM
MMMNl  MMMMMMMN       NMMMMMMM  JMMMM
MMMNl  MMMMMMMMMNmmmNMMMMMMMMM  JMMMM
MMMNI  MMMMMMMMMMMMMMMMMMMMMMM  jMMMM
MMMNI  MMMMMMMMMMMMMMMMMMMMMMM  jMMMM
MMMNI  MMMMM   MMMMMMM   MMMMM  jMMMM
MMMNI  MMMMM   MMMMMMM   MMMMM  jMMMM
MMMNI  MMMNM   MMMMMMM   MMMMM  jMMMM
MMMNI  WMMMM   MMMMMMM   MMMM#  JMMMM
MMMMR  ?MMNM             MMMMM .dMMMM
MMMMNm `?MMM             MMMM` dMMMMM
MMMMMMN  ?MM             MM?  NMMMMMN
MMMMMMMMNe                 JMMMMMNMMM
MMMMMMMMMMNm,            eMMMMMNMMNMM
MMMMNNMNMMMMMNx        MMMMMMNMMNMMNM
MMMMMMMMNMMNMMMMm+..+MMNMMNMNMMNMMNMM
        https://metasploit.com


       =[ metasploit v5.0.23-dev-3ffd6363f3               ]
+ -- --=[ 1891 exploits - 1065 auxiliary - 329 post       ]
+ -- --=[ 546 payloads - 44 encoders - 10 nops            ]
+ -- --=[ 2 evasion                                       ]

[*] Starting persistent handler(s)...
msf5 > use auxiliary/scanner/smb/pipe_auditor
msf5 auxiliary(scanner/smb/pipe_auditor) > setg RHOSTS 10.11.1.136
RHOSTS => 10.11.1.136
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[+] 10.11.1.136:139       - Pipes: \\netlogon, \\lsarpc, \\samr, \\eventlog, \\lsass, \\ntsvcs, \\srvsvc, \\wkssvc
[*] 10.11.1.136:          - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/pipe_auditor) > setg VERBOSE true
VERBOSE => true
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[*] 10.11.1.136:139       - Connected to named pipe: \netlogon
[*] 10.11.1.136:139       - Connected to named pipe: \lsarpc
[*] 10.11.1.136:139       - Connected to named pipe: \samr
[-] 10.11.1.136:139       - Inaccessible named pipe: \browser - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \atsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \DAV RPC SERVICE - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \epmapper - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:139       - Connected to named pipe: \eventlog
[-] 10.11.1.136:139       - Inaccessible named pipe: \InitShutdown - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \keysvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:139       - Connected to named pipe: \lsass
[-] 10.11.1.136:139       - Inaccessible named pipe: \LSM_API_service - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:139       - Connected to named pipe: \ntsvcs
[-] 10.11.1.136:139       - Inaccessible named pipe: \plugplay - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \protected_storage - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \router - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \SapiServerPipeS-1-5-5-0-70123 - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \scerpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:139       - Connected to named pipe: \srvsvc
[-] 10.11.1.136:139       - Inaccessible named pipe: \tapsrv - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \trkwks - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \W32TIME_ALT - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 10.11.1.136:139       - Connected to named pipe: \wkssvc
[-] 10.11.1.136:139       - Inaccessible named pipe: \PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 10.11.1.136:139       - Inaccessible named pipe: \db2remotecmd - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[+] 10.11.1.136:139       - Pipes: \\netlogon, \\lsarpc, \\samr, \\eventlog, \\lsass, \\ntsvcs, \\srvsvc, \\wkssvc
[*] 10.11.1.136:          - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by wvu-r7** [comment]
Damn, sounds like you found a bug in our implementation when interacting with Samba.

**Comment by wvu-r7** [comment]
Testing Samba 4.x, not your 3.x as supposedly identified by Nmap:

```
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[*] 172.28.128.3:139      - Connected to named pipe: netlogon
[*] 172.28.128.3:139      - Connected to named pipe: lsarpc
[*] 172.28.128.3:139      - Connected to named pipe: samr
[-] 172.28.128.3:139      - Inaccessible named pipe: browser - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: atsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: DAV RPC SERVICE - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: epmapper - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 172.28.128.3:139      - Connected to named pipe: eventlog
[*] 172.28.128.3:139      - Connected to named pipe: InitShutdown
[-] 172.28.128.3:139      - Inaccessible named pipe: keysvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: lsass - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: LSM_API_service - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 172.28.128.3:139      - Connected to named pipe: ntsvcs
[-] 172.28.128.3:139      - Inaccessible named pipe: plugplay - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: protected_storage - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: router - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: SapiServerPipeS-1-5-5-0-70123 - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: scerpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 172.28.128.3:139      - Connected to named pipe: srvsvc
[-] 172.28.128.3:139      - Inaccessible named pipe: tapsrv - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: trkwks - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: W32TIME_ALT - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 172.28.128.3:139      - Connected to named pipe: wkssvc
[-] 172.28.128.3:139      - Inaccessible named pipe: PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 172.28.128.3:139      - Inaccessible named pipe: db2remotecmd - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[+] 172.28.128.3:139      - Pipes: netlogon, lsarpc, samr, eventlog, InitShutdown, ntsvcs, srvsvc, wkssvc
[*] 172.28.128.3:         - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/pipe_auditor) > previous
msf5 auxiliary(scanner/smb/smb_version) > run

[*] 172.28.128.3:445      - Host could not be identified: Windows 6.1 (Samba 4.3.11-Ubuntu)
[*] 172.28.128.3:445      - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/smb_version) >
```

**Comment by wvu-r7** [comment]
Metasploitable 2's Samba 3.0.20 tested:

```
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[-] 192.168.56.104:139    - Inaccessible named pipe: netlogon - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: lsarpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: samr - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: browser - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: atsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: DAV RPC SERVICE - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: epmapper - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: eventlog - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: InitShutdown - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: keysvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: lsass - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: LSM_API_service - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: ntsvcs - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: plugplay - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: protected_storage - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: router - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: SapiServerPipeS-1-5-5-0-70123 - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: scerpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: srvsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: tapsrv - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: trkwks - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: W32TIME_ALT - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: wkssvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: db2remotecmd - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.104:       - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/pipe_auditor) > previous
msf5 auxiliary(scanner/smb/smb_version) > run

[*] 192.168.56.104:445    - Host could not be identified: Unix (Samba 3.0.20-Debian)
[*] 192.168.56.104:445    - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/smb_version) >
```

**Comment by wvu-r7** [comment]
So it's probably not OffSec trying to mess with you for using Metasploit. ;)

This appears to be a Samba 3.x issue. I'll dig deeper in a bit.

**Comment by wvu-r7** [comment]
Working with patch:

```
msf5 auxiliary(scanner/smb/pipe_auditor) > run

[*] 192.168.56.104:139    - Connected to named pipe: \netlogon
[*] 192.168.56.104:139    - Connected to named pipe: \lsarpc
[*] 192.168.56.104:139    - Connected to named pipe: \samr
[-] 192.168.56.104:139    - Inaccessible named pipe: \browser - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \atsvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \DAV RPC SERVICE - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \epmapper - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.104:139    - Connected to named pipe: \eventlog
[-] 192.168.56.104:139    - Inaccessible named pipe: \InitShutdown - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \keysvc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.104:139    - Connected to named pipe: \lsass
[-] 192.168.56.104:139    - Inaccessible named pipe: \LSM_API_service - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.104:139    - Connected to named pipe: \ntsvcs
[-] 192.168.56.104:139    - Inaccessible named pipe: \plugplay - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \protected_storage - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \router - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \SapiServerPipeS-1-5-5-0-70123 - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \scerpc - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.104:139    - Connected to named pipe: \srvsvc
[-] 192.168.56.104:139    - Inaccessible named pipe: \tapsrv - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \trkwks - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \W32TIME_ALT - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[*] 192.168.56.104:139    - Connected to named pipe: \wkssvc
[-] 192.168.56.104:139    - Inaccessible named pipe: \PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[-] 192.168.56.104:139    - Inaccessible named pipe: \db2remotecmd - The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=162 WordCount=0)
[+] 192.168.56.104:139    - Pipes: \netlogon, \lsarpc, \samr, \eventlog, \lsass, \ntsvcs, \srvsvc, \wkssvc
[*] 192.168.56.104:       - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/pipe_auditor) >
```

**Comment by NoodleOfDeath** [comment]
That’s very strange. I wonder why Samba 3.x is different from all of the other versions. 🤔 

Also thanks for showing me more into the process of documenting and making pull requests. This is my very first one actually

**Review by NoodleOfDeath — COMMENTED** [review]
Any style preference on using single vs double quoted strings? I’m referring specifically to lines 45 and 46 of `lib/msg/core/exploit/smb/client/pipe_auditor.rb`

**Comment by wvu-r7** [comment]
@NoodleOfDeath:

https://github.com/samba-team/samba/blob/samba-3.0.20/source/smbd/pipes.c#L31-L115
https://github.com/samba-team/samba/blob/samba-3.0.20/source/rpc_parse/parse_rpc.c#L194-L216
https://github.com/samba-team/samba/blob/samba-3.0.20/source/include/smb.h#L175-L192

**Comment by wvu-r7** [comment]
I used to prefer double-quoted strings all the time, but then I switched to single-quoted strings if I didn't need interpolation. It's more predictable. But the most important thing is to be consistent.

**Comment by wvu-r7** [comment]
@NoodleOfDeath:

https://github.com/samba-team/samba/blob/samba-4.3.11/source3/smbd/pipes.c#L85-L166

**Comment by wvu-r7** [comment]
You can see how backslash handling between 3.x and 4.x is different. 3.x is more stringent, and 4.x does more normalization.

**Comment by NoodleOfDeath** [comment]
That’s why I asked. I am the same way; I only use double quotes if absolutely necessary. Thanks for the references, too

**Comment by wvu-r7** [comment]
@NoodleOfDeath:

https://github.com/samba-team/samba/commit/abf566ca994b8e2b47ab3da69cde67568bca8d71

:boom:

**Comment by wvu-r7** [comment]
# Release Notes

This adds normalization to the `pipe_auditor` mixin (used by the module) to prefix named pipe names with a backslash. Samba 3.x doesn't perform any normalization on the pipe name, thus requiring the backslash. Samba 4.x and Windows are unaffected.

**Comment by wvu-r7** [comment]
@NoodleOfDeath: Awesome collab. Thanks for this!
