### PR TITLE
don't create a new socket every time the command prompt is displayed

### LINKED ISSUE #11302: msf5 crashes on kali 2018.4 with message "[FATAL] failed to allocate memory" or segmentation fault/hang on "show all"
## Steps to reproduce

Crash is unpredictable, but always occurs shortly after starting msf console via either "msfdb run" or "service postgresql start; msfconsole."    

## Expected behavior

That it doesn't crash

## Current behavior

A crash or a hang occurs sometimes immediately upon startup or sometimes after a short sequence of commands.

Most often, program dies with the message
"[FATAL] failed to allocate memory" 

Other times, it will simply hang and become unresponsive, or occasionally segmentation fault.
Occurs on both of my systems (one physical, one virtual) in the same way (systems details at end).

A crash occurs either right away or after a short sequence of commands.   Here is a typical example:
>    root@kalivm:~# msfdb run
>    msf5 > use auxiliary/scanner/smb/smb2
>    msf5 auxiliary(scanner/smb/smb2) > setg RHOSTS 10.10.10.103
>    RHOSTS => 10.10.10.103
>    msf5 auxiliary(scanner/smb/smb2) > run
>    [+] 10.10.10.103:445      - 10.10.10.103 supports SMB 2 [dialect 255.2] and has been online for 33 hours
>    **[FATAL] failed to allocate memory**
>

See following transcript for **segmentation fault** on "show all"
[show-all-segfault-transcript.txt](https://github.com/rapid7/metasploit-framework/files/2786025/show-all-segfault-transcript.txt)

## System stuff

Log file for System1: 
[framework.log](https://github.com/rapid7/metasploit-framework/files/2786047/framework.log)

Log file for System2:
[system2-framework.log](https://github.com/rapid7/metasploit-framework/files/2786064/system2-framework.log)

### I installed Metasploit with:
Came with kali 2018.4 + apt upgrade

- [ x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

####System 1####
Physical
root@Secaudit:~: uname -a
Linux Secaudit 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux
r
root@Secaudit:~: cat /proc/version
Linux version 4.19.0-kali1-amd64 (devel@kali.org) (gcc version 8.2.0 (Debian 8.2.0-13)) #1 SMP Debian 4.19.13-1kali1 (2019-01-03)

root@Secaudit:~: lsmem
...
Memory block size:       128M
Total online memory:      16G
Total offline memory:      0B

root@Secaudit:~: free -h
                    total        used        free      shared  buff/cache   available
Mem:           15Gi       1.7Gi       1.6Gi       8.3Gi        12Gi       5.3Gi
Swap:          15Gi          0B        15Gi

root@Secaudit:~: lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               58
Model name:          Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

#### System 2 ####
VM running on the physical machine above
root@kalivm:~: uname -a
Linux kalivm 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux

root@kalivm:~: cat /proc/version
Linux version 4.19.0-kali1-amd64 (devel@kali.org) (gcc version 8.2.0 (Debian 8.2.0-13)) #1 SMP Debian 4.19.13-1kali1 (2019-01-03)

root@kalivm:~: lsmem
...
Memory block size:       128M
Total online memory:       8G
Total offline memory:      0B

root@kalivm:~: free -h
                   total        used        free      shared  buff/cache   available
Mem:          7.8Gi       1.1Gi       5.9Gi       196Mi       884Mi       6.3Gi
Swap:         4.3Gi          0B        4.3Gi

root@kalivm:~: lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       43 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           4
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               58
Model name:          Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

### PR DESCRIPTION
**Pull request by busterb**
This probably fixes #11302 though it's not clear what the real root issue is there. @conniest noted that the console prompt randomly segfaults under Kali Linux with Ruby 2.5.3 and MSF5. The crash information shows that Metasploit is creating a new socket every time the command prompt is formatted on the hopes that the user included '%L' in the prompt format string and needs the local IP address displayed.

```
[-] Error while running command show: failed to allocate memory
/usr/lib/ruby/2.5.0/timeout.rb:97: [BUG] rb_register_sigaltstack: th->altstack not initialized

ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0020 p:---- s:0133 e:000132 CFUNC  :join
c:0019 p:0015 s:0129 e:000128 RESCUE /usr/lib/ruby/2.5.0/timeout.rb:97
c:0018 p:0048 s:0125 E:0013a8 BLOCK  /usr/lib/ruby/2.5.0/timeout.rb:97
c:0017 p:0005 s:0118 e:000117 BLOCK  /usr/lib/ruby/2.5.0/timeout.rb:33 [FINISH]
c:0016 p:---- s:0115 e:000114 CFUNC  :catch
c:0015 p:0044 s:0110 e:000109 METHOD /usr/lib/ruby/2.5.0/timeout.rb:33
c:0014 p:0113 s:0104 E:0009d0 METHOD /usr/lib/ruby/2.5.0/timeout.rb:108
c:0013 p:0879 s:0092 E:000020 METHOD /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket/comm/local.rb:266
c:0012 p:0141 s:0076 e:000075 METHOD /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket/comm/local.rb:35
c:0011 p:0010 s:0071 e:000070 METHOD /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket.rb:49
c:0010 p:0033 s:0066 e:000065 METHOD /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket.rb:70
c:0009 p:0040 s:0061 e:000060 METHOD /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket.rb:599
c:0008 p:0269 s:0053 e:000050 METHOD /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:407
c:0007 p:0066 s:0042 e:000038 METHOD /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:198
c:0006 p:0124 s:0032 e:000031 METHOD /usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:443
c:0005 p:0032 s:0025 e:000024 METHOD /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:132
c:0004 p:0049 s:0018 e:000017 METHOD /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48
c:0003 p:0025 s:0014 e:000013 METHOD /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82
c:0002 p:0184 s:0009 E:000db8 EVAL   /usr/bin/msfconsole:49 [FINISH]
c:0001 p:0000 s:0003 E:0003d0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/bin/msfconsole:49:in `<main>'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:132:in `run'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:443:in `update_prompt'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:198:in `update_prompt'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:407:in `format_prompt'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket.rb:599:in `source_address'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket.rb:70:in `create_udp'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket.rb:49:in `create_param'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket/comm/local.rb:35:in `create'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket/comm/local.rb:266:in `create_by_type'
/usr/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/usr/lib/ruby/2.5.0/timeout.rb:97:in `block in timeout'
/usr/lib/ruby/2.5.0/timeout.rb:97:in `ensure in block in timeout'
/usr/lib/ruby/2.5.0/timeout.rb:97:in `join'
```

This PR avoids this expensive operation by first checking if the user actually used that format string, and then uses native Ruby methods for determining the local IP address rather than creating a Rex socket.

This does prevent Metasploit from actually connecting a UDP socket on IP 50.50.50.50 every time a prompt is displayed, which is a good thing independent of the bug reported above.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] Add %L to your local prompt:

```
msf5 auxiliary(scanner/snmp/snmp_login) > setg Prompt %L
Prompt => %L
192.168.86.31 auxiliary(scanner/snmp/snmp_login) >
```

- [x] **Verify** the local IP displays, and especially that your console does not crash
- [x] **Check** the other prompt expansion variables to ensure they work as well.

### CODE REVIEW

**Comment by bcoles** [comment]
Adding `bug` label because leaking sockets is silly.

File: lib/rex/ui/text/shell.rb [hunk 1]
```diff
@@ -381,33 +381,46 @@ def prompt_yesno(query)
...
+      if str.include?('%L')
+        ip = ::Socket.ip_address_list.detect{|intf| intf.ipv4_private?}
+        str.gsub!('%L', ip.ip_address)
+      end
+
+      if str.include?('%D')
+        str.gsub!('%D', ::Dir.getwd)
+      end
+
+      if str.include?('%W') && framework.db.active
```
Comment (wvu-r7) [inline lib/rex/ui/text/shell.rb]: This is a great refactor. We don't need to check if the database is active every time the prompt is formatted, only when `%W` is included in the prompt.

File: lib/rex/ui/text/shell.rb [hunk 2]
```diff
@@ -381,33 +381,46 @@ def prompt_yesno(query)
...
+      if str.include?('%S')
+        str.gsub!('%S', framework.sessions.length.to_s)
+      end
+
+      if str.include?('%J')
+        str.gsub!('%J', framework.jobs.length.to_s)
+      end
+
+      if str.include?('%L')
+        ip = ::Socket.ip_address_list.detect{|intf| intf.ipv4_private?}
```
Comment (wvu-r7) [inline lib/rex/ui/text/shell.rb]: Though `Rex::Socket.source_address` *shouldn't* send traffic to the destination, it still creates a UDP socket to my knowledge.

The behavior of `Rex::Socket.source_address` is different from `Socket.ip_address_list`'s, though, since it uses the socket to determine the correct IP that can talk to the destination. The behavior here is more like `ReverseListenerBindAddress` instead of `LHOST`.

```
[1] pry(#<Msf::Framework>)> Rex::Socket.source_address("50.50.50.50")
=> "66.x.x.x"
[2] pry(#<Msf::Framework>)> ::Socket.ip_address_list.detect{|intf| intf.ipv4_private?}
=> #<Addrinfo: 10.x.x.x>
[3] pry(#<Msf::Framework>)>
```

We may want to evaluate where else we're continuously leaking sockets, since `Rex::Socket.source_address` sees heavy use in Framework.

Comment (acammack-r7) [reply lib/rex/ui/text/shell.rb]: If the problem is _leaking_ sockets the `source_address` code needs to be modified to put the socket close in an `ensure` block. Otherwise, this does have a big behavioral change in that it now grabs a local address instead of an internet address. https://github.com/rapid7/rex-socket/blob/master/lib/rex/socket.rb#L598-L605

Comment (wvu-r7) [reply lib/rex/ui/text/shell.rb]: Exactly my thoughts. The `close` should be in an `ensure`. The code is already set up for it, even.

Comment (busterb) [reply lib/rex/ui/text/shell.rb]: I can just add a method for 'local_routable_ip' to Rex Socket as a class method and change Metasploit to use it everywhere? It seems you want to do something like this:

def self.local_routable_ip
    orig, Socket.do_not_reverse_lookup = Socket.do_not_reverse_lookup, true
    UDPSocket.open do |s|
      s.connect '50.50.50.50', 1
      s.addr.last
    end
    ensure
      Socket.do_not_reverse_lookup = orig
 end

Comment (busterb) [reply lib/rex/ui/text/shell.rb]: NM, I can just revert this to use rex and update that.

**Comment by busterb** [comment]
See https://github.com/rapid7/rex-socket/pull/15 and other comments addressed as well.

**Review by wvu — APPROVED** [review]

**Comment by busterb** [comment]
All comments addressed, landing.

**Comment by busterb** [comment]
## Release Notes

This optimizes the msfconsole shell prompt to not compute every expansion character content if they are not used. Namely, it avoids computing %L which appears to be fairly expensive and possibly leads to crashes in some circumstances.
