### PR TITLE
Fix `undefined method` error in `/api/v1/modules` endpoint

### LINKED ISSUE #18472: An error with message "undefined method `search_modules' for Msf::WebServices:Module" when call REST API
## Steps to reproduce

How'd you do it?

1. I have installed Metasploit Framework and set up the Metasploit web server (for using REST API).
2. Send a request to http `GET /api/v1/modules`

## Were you following a specific guide/tutorial or reading documentation?

Yes, I was following this docs [https://docs.metasploit.com/docs/using-metasploit/advanced/metasploit-web-service.html](https://docs.metasploit.com/docs/using-metasploit/advanced/metasploit-web-service.html)

## Expected behavior

It should return modules matching keywords with appropriate metadata.
Screenshot from 2023-10-19 21-27-57

## Current behavior

It returned an error with message: "There was an error completing the module search: undefined method `search_modules' for Msf::WebServices:Module" and code 500
Screenshot from 2023-10-19 21-30-36

### Metasploit version

`Framework Version: 6.3.39-dev-`

## Additional Information
I updated to the latest version but my issue is still present.

## Suggestion
"I found this API calling the method `Msf::WebServices.search_modules()` (in file `/framework/lib/msf/core/web_services/servlet/module_search_servlet.rb` line 21), but this method `search_modules()` is not defined in module `Msf::WebServices`. I think `search_modules()` might be mothod in module `Msf::WebServices::ModuleSearch` (because the method `search_modules`() is defined in module `Msf::WebServices::ModuleSearch` in the file `framework/lib/msf/core/web_services/module_search.rb` line 3)". 

I have modified the source code, but I don't know how to rebuild it. It would be great if you could provide a guide for me to edit the code and rebuild the project on my own.

### PR DESCRIPTION
**Pull request by ekalinichev-r7**
Closes #18472 by extending `Msf::WebServices` with `Msf::WebServices::ModuleSearch` that was originally present there but was accidentally removed 

Paired with @dwelch-r7 and @adfoster-r7 

## Verification

List the steps needed to make sure this thing works

- [ ] Start msfdb webservice: `msfdb --component webservice --address 0.0.0.0 start`
- [ ] Navigate to `http://localhost:5443/api/v1/modules?name=aux`
- [ ] **Verify** response includes list of modules
- [ ] **Verify** no error

### CODE REVIEW

File: lib/msf/core/web_services.rb [hunk 1]
```diff
@@ -1,3 +1,3 @@
 module Msf::WebServices
-
+  extend Msf::WebServices::ModuleSearch
```
Comment (adfoster-r7) [inline lib/msf/core/web_services.rb:2]: Context: This was code was accidentally lost in a previous code shuffle here: https://github.com/rapid7/metasploit-framework/commit/1617b3ec9b336f38c071cc35de03191bd5cccc11#diff-14dba8397537f8e93680797413000a4cebec4393efb7f047a46fb0e997dc9719

**Comment by adfoster-r7** [comment]
## Release notes

Fixes a crash with Metasploit's REST api when calling `/api/v1/modules?name=aux`
