### PR TITLE
check shodan API key

### LINKED ISSUE #13598: Shodan API key error with metasploit
## Steps to reproduce

How'd you do it?

1. ...  msfconsole search shodan use auxiliary/gather/shodan_search 
2. ... set SHODAN_APIKEY set QUERY run

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Expected behavior it should scan

What should happen? supposed to give results of scan

## Current behavior - gives error

What happens instead?  error message : Auxiliary aborted due to failure: bad-config: 401 Unauthorized. Your SHODAN_APIKEY is invalid

I HAVE A SHODAN PAID MEMBERSHIP

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).   Processing version.rc for ERB directives.
resource (version.rc)> version
Framework: 5.0.91-dev
Console  : 5.0.91-dev

### I installed Metasploit with:
- [ x] Kali package via apt  YES
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ x] Source install (please specify ruby version)    ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]

### OS

What OS are you running Metasploit on?   Linux kali 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-1kali1 (2020-05-25) x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by h00die**
Related to https://github.com/rapid7/metasploit-framework/issues/13598#issuecomment-643646040

Ping @adfoster-r7  since you were also involved in that issue

This PR adds a simple check to ensure the Shodan API key passes a basic sanity check (32 character `/a-z,0-9/i`.  I don't think it will resolve #13598 however it will at least weed out the easy problems.

# After Patch
good key (sanitized)
```
msf5 auxiliary(gather/shodan_search) > set SHODAN_APIKEY aAA1jN111IxghvAA02AAtataLLbIvAa0
SHODAN_APIKEY => aAA1jN111IxghvAA02AAtataLLbIvAa0
msf5 auxiliary(gather/shodan_search) > set verbose true
verbose => true
msf5 auxiliary(gather/shodan_search) > run

[*] Total: 28 on 1 pages. Showing: 1 page(s)
[*] Collecting data, please wait...

```
bad key
```
msf5 auxiliary(gather/shodan_search) > set SHODAN_APIKEY aAA1jN111IxghvAA02AAtata
SHODAN_APIKEY => aAA1jN111IxghvAA02AAtata
msf5 auxiliary(gather/shodan_search) > run

[-] Auxiliary aborted due to failure: bad-config: Shodan API key should be 32 characters a-z,A-Z,0-9.
[*] Auxiliary module execution completed

```

### CODE REVIEW

File: modules/auxiliary/gather/shodan_honeyscore.rb [hunk 1]
```diff
@@ -42,6 +42,11 @@ def print_score(score)
   end
 
   def run
+    # check our API key is somewhat sane
+    unless /^[a-z\d]{32}$/i.match?(datastore['SHODAN_APIKEY'])
+      fail_with(Failure::BadConfig, 'Shodan API key should be 32 characters a-z,A-Z,0-9.')
```
Comment (adfoster-r7) [inline modules/auxiliary/gather/shodan_honeyscore.rb:47]: Any thoughts on dumping out the unexpected character? It might help with debugging 👀

**Comment by adfoster-r7** [comment]
Looks like if this gets landed, it'll close the issue you've referenced in the description:

> image

> image

File: modules/auxiliary/gather/shodan_honeyscore.rb (hunk 1 above)
Comment (h00die) [reply modules/auxiliary/gather/shodan_honeyscore.rb:47]: I didn't want to overcomplicate a copy/paste operation. Most likely if this triggered it would be a length issue is what I'm guessing

**Comment by h00die** [comment]
When it lands we can just reopen the issue

**Comment by adfoster-r7** [comment]
## Release Notes

Adds Shodan API key validation to verify that the supplied key is 32 valid characters

**Comment by surfer663** [comment]
hi guys any ideas whats the next  steps will be

**Comment by h00die** [comment]
step 1 would be to get the latest code (git, it wont filter down to kali for a week or two), and verify it is still a problem.  It most likely will be, but it will at least get us moving forward.

**Comment by surfer663** [comment]
thanks guys for all the effort in helping
