### PR TITLE
fix #11395, use db.hosts.each

### LINKED ISSUE #11395: Metasploit using an empty RPC/Web service database crashes on tab completion with rhosts
## Steps to reproduce

How'd you do it?

1. With Metasploit 5 using the stock `msfdb` run `msfdb reinit` to ensure you have an empty database and that Metasploit is configured to use the web service as its connection.

2. Use an auxiliary module that has an `RHOSTS` parameter, type `set rhosts 192<tab>`

3. Observe that the console crashes similar to this:

```
msf5 auxiliary(gather/shodan_search) > set rhosts 192Traceback (most recent call last):
	28: from ./msfconsole:49:in `<main>'
	27: from /home/bcook/projects/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	26: from /home/bcook/projects/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	25: from /home/bcook/projects/metasploit-framework/lib/rex/ui/text/shell.rb:134:in `run'
	24: from /home/bcook/projects/metasploit-framework/lib/rex/ui/text/shell.rb:309:in `get_input_line'
	23: from /home/bcook/projects/metasploit-framework/lib/rex/ui/text/input/readline.rb:100:in `pgets'
	22: from /home/bcook/projects/metasploit-framework/lib/rex/ui/text/input/readline.rb:162:in `readline_with_output'
	21: from /home/bcook/.rvm/gems/ruby-2.5.3@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4875:in `readline'
	20: from /home/bcook/.rvm/gems/ruby-2.5.3@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4853:in `readline_internal'
	19: from /home/bcook/.rvm/gems/ruby-2.5.3@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4779:in `readline_internal_charloop'
	18: from /home/bcook/.rvm/gems/ruby-2.5.3@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4363:in `_rl_dispatch'
	17: from /home/bcook/.rvm/gems/ruby-2.5.3@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4374:in `_rl_dispatch_subseq'
	16: from /home/bcook/.rvm/gems/ruby-2.5.3@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6903:in `rl_complete'
	15: from /home/bcook/.rvm/gems/ruby-2.5.3@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6813:in `rl_complete_internal'
	14: from /home/bcook/.rvm/gems/ruby-2.5.3@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6329:in `gen_completion_matches'
	13: from /home/bcook/.rvm/gems/ruby-2.5.3@metasploit-framework/gems/rb-readline-0.5.5/lib/readline.rb:136:in `readline_attempted_completion_function'
	12: from /home/bcook/projects/metasploit-framework/lib/rex/ui/text/shell.rb:62:in `block in init_tab_complete'
	11: from /home/bcook/projects/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:355:in `tab_complete'
	10: from /home/bcook/projects/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:370:in `tab_complete_stub'
	 9: from /home/bcook/projects/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:370:in `each'
	 8: from /home/bcook/projects/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:381:in `block in tab_complete_stub'
	 7: from /home/bcook/projects/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:421:in `tab_complete_helper'
	 6: from /home/bcook/projects/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1612:in `cmd_set_tabs'
	 5: from /home/bcook/projects/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2189:in `tab_complete_option'
	 4: from /home/bcook/projects/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2189:in `each_key'
	 3: from /home/bcook/projects/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2190:in `block in tab_complete_option'
	 2: from /home/bcook/projects/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2248:in `option_values_dispatch'
	 1: from /home/bcook/projects/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2380:in `option_values_target_addrs'
/home/bcook/projects/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing': undefined method `each_host' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x00005611ab3f6f20> (NoMethodError)
```

## System stuff

Linux, Mac OS, seems to not matter.

### Metasploit version

Latest Metasploit 5 installer nightly + git checkout

### I installed Metasploit with:
- [ ] Kali package via apt
- [X] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [X] Source install (please specify ruby version)

### PR DESCRIPTION
**Pull request by busterb**
Prefer iterating over hosts over the older method in the database. Fixes #11395 

## Verification

- [x] `msfdb reinit` to ensure there is a clean database (or maybe create a fresh workspace)
- [x] Start `msfconsole`
- [x] `use auxiliary/gather/shodan_search`
- [x] `set rhosts 192.168<tab>`
- [x] **Verify** the console does not crash and tab completes a local IP address

### CODE REVIEW

File: lib/msf/ui/console/command_dispatcher/core.rb [hunk 1]
```diff
@@ -2377,7 +2377,7 @@ def option_values_target_addrs
 
     # List all hosts in the database
     else
-      framework.db.each_host(framework.db.workspace) do |host|
+      framework.db.hosts.each do |host|
```
Comment (mkienow-r7) [inline lib/msf/ui/console/command_dispatcher/core.rb]: This will work because the data proxy adds the workspace to the request for `hosts`. However, consider explicitly specifying the workspace as a best practice.
```
framework.db.hosts(workspace: framework.db.workspace).each
```

**Comment by mkienow-r7** [comment]
This PR also fixes another issue with the `framework.db.each_service` call in the same method, when connected to a remote data service.

```
msf5 > use auxiliary/gather/apache_rave_creds
msf5 auxiliary(gather/apache_rave_creds) > services
Services
========

host          port  proto  name         state  info
----          ----  -----  ----         -----  ----
172.28.128.3  80    tcp    http         open   Apache httpd 2.2.8 (Ubuntu) DAV/2

msf5 auxiliary(gather/apache_rave_creds) > set RPORT 80
RPORT => 80
msf5 auxiliary(gather/apache_rave_creds) > set rhosts 192.168Traceback (most recent call last):
    28: from ./msfconsole:49:in `<main>'
    27: from /home/msfdev/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    26: from /home/msfdev/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    25: from /home/msfdev/metasploit-framework/lib/rex/ui/text/shell.rb:134:in `run'
    24: from /home/msfdev/metasploit-framework/lib/rex/ui/text/shell.rb:309:in `get_input_line'
    23: from /home/msfdev/metasploit-framework/lib/rex/ui/text/input/readline.rb:100:in `pgets'
    22: from /home/msfdev/metasploit-framework/lib/rex/ui/text/input/readline.rb:162:in `readline_with_output'
    21: from /home/msfdev/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4875:in `readline'
    20: from /home/msfdev/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4853:in `readline_internal'
    19: from /home/msfdev/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4779:in `readline_internal_charloop'
    18: from /home/msfdev/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4363:in `_rl_dispatch'
    17: from /home/msfdev/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4374:in `_rl_dispatch_subseq'
    16: from /home/msfdev/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6903:in `rl_complete'
    15: from /home/msfdev/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6813:in `rl_complete_internal'
    14: from /home/msfdev/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6329:in `gen_completion_matches'
    13: from /home/msfdev/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rb-readline-0.5.5/lib/readline.rb:136:in `readline_attempted_completion_function'
    12: from /home/msfdev/metasploit-framework/lib/rex/ui/text/shell.rb:62:in `block in init_tab_complete'
    11: from /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:355:in `tab_complete'
    10: from /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:370:in `tab_complete_stub'
     9: from /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:370:in `each'
     8: from /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:381:in `block in tab_complete_stub'
     7: from /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:421:in `tab_complete_helper'
     6: from /home/msfdev/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1612:in `cmd_set_tabs'
     5: from /home/msfdev/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2189:in `tab_complete_option'
     4: from /home/msfdev/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2189:in `each_key'
     3: from /home/msfdev/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2190:in `block in tab_complete_option'
     2: from /home/msfdev/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2248:in `option_values_dispatch'
     1: from /home/msfdev/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2368:in `option_values_target_addrs'
/home/msfdev/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing': undefined method `each_service' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x00007fe1250c1a80> (NoMethodError)
```

**Comment by mkienow-r7** [comment]
# Release Notes

Fixes two tab completion issues with rhosts.
