### PR TITLE
Fix db connection support for JsonRpcApp service

### LINKED ISSUE #14166: db connect error when use the web service
## Steps to reproduce

How'd you do it?

1. start the json_rpc or msfdb rest service
2. call the json_rpc method or web_service method
3. can't connect db

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Expected behavior

can connect db

## Current behavior

error occurred when web_service connect db

### Metasploit version

21d9f06373267636d972e7ebdc0874ff336419d2 (grafted, HEAD -> master, origin/master, origin/HEAD) automatic module_metadata_base.json update

The problem with these two commits(https://github.com/rapid7/metasploit-framework/commit/07cbe426e2f80f523422487c83641ac9ee7b7971, https://github.com/rapid7/metasploit-framework/commit/2c92d17ed90a5ad9defb35d4797f3ef0fa6f8dd3) is that they don't take web_service into account

for example, when I use the json_rpc, the https://github.com/rapid7/metasploit-framework/blob/21d9f06373267636d972e7ebdc0874ff336419d2/lib/msf/core/web_services/json_rpc_app.rb#L41 will call the ServletHelper's get_db method, then https://github.com/rapid7/metasploit-framework/blob/21d9f06373267636d972e7ebdc0874ff336419d2/lib/msf/core/web_services/db_manager_proxy.rb#L19, then https://github.com/rapid7/metasploit-framework/blob/21d9f06373267636d972e7ebdc0874ff336419d2/lib/msf/core/db_manager.rb#L195. the connection_established? is true at the moment, then https://github.com/rapid7/metasploit-framework/blob/21d9f06373267636d972e7ebdc0874ff336419d2/lib/msf/core/db_manager/connection.rb#L18, at https://github.com/rapid7/metasploit-framework/blob/21d9f06373267636d972e7ebdc0874ff336419d2/lib/msf/core/db_manager/migration.rb#L29, the ActiveRecord::Base.connected? will be nil, this is because of ApplicationRecord and ActiveRecord in rails5, but the config is {} at the moment, so the will occur error.

Here is my log

```
[09/21/2020 23:12:01] [d(0)] core: Already established connection to postgresql, so reusing active connection.
[09/21/2020 23:12:01] [e(0)] core: DB.connect threw an exception - ActiveRecord::AdapterNotSpecified database configuration does not specify adapter
[09/21/2020 23:12:01] [e(0)] core: Failed to connect to the database: database configuration does not specify adapter

```

### PR DESCRIPTION
**Pull request by adfoster-r7**
This pull request is currently two pull requests in one that could be split out:
- Fixes the Json API to correctly interact with the configured framework database. Additionally closes https://github.com/rapid7/metasploit-framework/issues/14166 and succeeds https://github.com/rapid7/metasploit-framework/pull/14167
- Adds support for running the msfdb webservice component in the foreground to ensure that breakpoints can be interacted with

#### Verify reinit

Start the database in its entirety

```
bundle exec ruby ./msfdb reinit
```

Verify that the msfdb details are output to the console, and that you can open msfconsole and see `db_status` as being connected to the remote service:
```
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http.
```

#### Verify non-daemon mode

For development purposes it's useful to run the Metasploit API synchronously in the foreground to ensure that your breakpoints trigger. Ensure that the webservice can now be run synchronously:

```
bundle exec ruby ./msfdb reinit
bundle exec ruby ./msfdb --component webservice stop
bundle exec ruby ./msfdb --component webservice --no-daemon start
```

### RPC

Have the above msfdb instance running, and run the json rpc service with:
```
bundle exec thin --rackup msf-json-rpc.ru --address localhost --port 8081 --environment production --tag msf-json-rpc start
```

Verify that the RPC service can interact with the http data service
```
curl --request POST \
  --url http://localhost:8081/api/v1/json-rpc \
  --header 'Content-Type: application/json' \
  --data '{
        "jsonrpc": "2.0",
        "method": "db.status",
        "id": 1,
        "params": []
}'

{"jsonrpc":"2.0","result":{"driver":"http","db":"msf"},"id":1}
```

Verify that information can be retrieved:
```
curl --request POST \
  --url http://localhost:8081/api/v1/json-rpc \
  --header 'Content-Type: application/json' \
  --data '{
        "jsonrpc": "2.0",
        "method": "db.workspaces",
        "id": 1,
        "params": []
}'

{"jsonrpc":"2.0","result":{"workspaces":[{"id":1,"name":"default","created_at":1617283083,"updated_at":1617283083}]},"id":1}
```

Verify that this works with a framework instance that is talking to the local database rather than via the http service: This can be achieved by removing the logic from `~/.msf4/config`

Verify that the json rpc service can connect to a remote data service via its config
```
MSF_WS_DATA_SERVICE_URL=https://localhost:5443 MSF_WS_DATA_SERVICE_API_TOKEN=5e396b5175292daf7d5051cdabf953e16e0d789d2a6199a8021f439cc8712b043fa43eb21a14e7cc MSF_WS_DATA_SERVICE_CERT=/Users/user/.msf4/msf-ws-cert.pem MSF_WS_DATA_SERVICE_SKIP_VERIFY=true bundle exec thin --rackup msf-json-rpc.ru --address localhost --port 8081 --environment production --tag msf-json-rpc start
```

#### msfconsole

Ensure that you can connect to a remote database, for example the generate command from msfdb init might look like:
```
db_connect --token 49f2cadbdab091d52ced670ca629fa1e1d3ecabff070ba8bc2baa622795831983bd38f08fe0d8ef1 --cert /Users/user/.msf4/msf-ws-cert.pem --skip-verify https://localhost:5443
```
Verify the status

```
db_status
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: eTKtLBpF.
```

Verify that running `db_disconnect` will gracefully fall back to the local postgres database:
```
 db_status
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: eTKtLBpF.
> db_disconnect
Successfully disconnected from the data service: remote_data_service: (https://localhost:5443).
> db_status
[*] Connected to msf. Connection type: postgresql.
```

Ensure that `db_connect -l` works

Ensure that `db_connect -y ~/.msf4/database.yml` connects to the local database
```
db_connect --yaml ~/.msf4/database.yml
db_status
```

#### Testing remotely

To connect remotely you need to bind to all interfaces:

```
bundle exec ruby ./msfdb --component webservice --no-daemon --address 0.0.0.0 --debug start
```

First check you can interact with the service:
```
curl https://192.168.222.1:5443/
```

Then open your console and use the db_connect example generated from msfdb as above
```
db_connect --name test-remote-service --token 0bf5d341cd35a333f8562c83d16c4f3efb071a41a7ec17575b9c13b1700d631189b4282e591595c3 --skip-verify https://192.168.222.1:5443
```

### CODE REVIEW

File: lib/msf/core/web_services/framework_extension.rb [hunk 1]
```diff
@@ -26,6 +26,10 @@ module Helpers
       def framework
         settings.framework
       end
+
+      def get_db
+        framework.db
+      end
```
Comment (adfoster-r7) [inline lib/msf/core/web_services/framework_extension.rb:32]: This overrides the default behavior here:

https://github.com/rapid7/metasploit-framework/blob/6549c12473a578a055a8fa27a09a96ee0b8ade08/lib/msf/core/web_services/servlet_helper.rb#L84-L86

Importantly this change treats framework's db as the source of truth. Without this change, two database connections were being opened separately from each other. The first from the servlet helper to create the db proxy instance, and a second from framework itself

File: lib/msf/core/web_services/framework_extension.rb [hunk 2]
```diff
@@ -35,50 +39,41 @@ def self.registered(app)
...
+            'Logger' => ENV.fetch('MSF_WS_DATA_SERVICE_LOGGER', nil),
+            # SkipDatabaseInit false is the default behavior, however for explicitness - note that framework first
+            # connects to a local database as a pre-requisite to connecting to a remote service to correctly
+            # configure active record
+            'SkipDatabaseInit' => false
           }
           framework = Msf::Simple::Framework.create(init_framework_opts)
-
-          if !app.settings.data_service_url.nil? && !app.settings.data_service_url.empty?
-            framework_db_connect_http_data_service(framework: framework,
```
Comment (adfoster-r7) [inline lib/msf/core/web_services/framework_extension.rb:48]: This was broken, lazily loading framework via a proc meant that the value of `self` in this context was now the sinatra app - rather than `Msf::WebServices::FrameworkExtension` as part of the initial extension registration

File: lib/msf/ui/console/command_dispatcher/db.rb [hunk 3]
```diff
@@ -1786,36 +1799,27 @@ def cmd_db_connect(*args)
...
+      name = opts[:name]
       if !name || name.empty?
         if found_name
           name = found_name
+        elsif result[:data_service_name]
+          name = result[:data_service_name]
         else
           name = Rex::Text.rand_text_alphanumeric(8)
         end
       end
```
Comment (adfoster-r7) [inline lib/msf/ui/console/command_dispatcher/db.rb:1821]: The name mechanism in this command dispatcher seems slightly broken/inconsistent, particularly with the mismatch of not storing local db creds within `~/.msf4/config` itself. I've fixed some bugs/edge cases on the way, but overall I think it needs more work - but not as part of this pull request

**Comment by cgranleese-r7** [comment]
# After
Wasn't sure on the best approach to displaying results here. Went with adding a title for each verification step with the corresponding results in an image below each one ¯\\\_(ツ)_/¯

## Verify reinit:
image

## Verify that the msfdb details are output to the console, and that you can open msfconsole and see db_status as being connected to the remote service:
image

## Verify non-daemon mode
`bundle exec ruby ./msfdb reinit` - verified above

`bundle exec ruby ./msfdb --component webservice stop`

image

`bundle exec ruby ./msfdb --component webservice --no-daemon start`
image

## RPC
`bundle exec thin --rackup msf-json-rpc.ru --address localhost --port 8081 --environment production --tag msf-json-rpc start`

image

## Verify that information can be retrieved:

image

### Verify that this works with a framework instance that is talking to the local database rather than via the http service: This can be achieved by removing the logic from ~/.msf4/config
Commented out this line: 
```
[framework/database]
default_db=local-https-data-service
```

## Verified `db_status` worked as expected
image

## Verify that the json rpc service can connect to a remote data service via its config
image




*WIP*, will continue testing tomorrow morning.

**Comment by cgranleese-r7** [comment]
## Release Notes
Fixes the Json API to correctly interact with the configured framework database, as well as adding support for running the `msfdb webservice` component in the foreground to ensure that breakpoints can be interacted with.
