### PR TITLE
Fixes the generate commands tab completion crash, caused when no result are returned.

### LINKED ISSUE #14358: Hitting Tab When using the Generate Command Where No Results Can Be Returned Kills MsfConsole
It appears that MsfConsole crashes when we try to autocomplete on something that returns no results. I may have reported this before, if so sorry but I have had it occur a few times now and we really aught to fix it.

```
~/git/metasploit-framework │ master ?2  ./msfconsole                                                                        ✔ │ 2.7.2 Ruby 
[-] No local database connected, meaning some Metasploit features will not be available. A full list of the affected features & database setup instructions can be found here: https://github.com/rapid7/metasploit-framework/wiki/msfdb:-Database-Features-&-How-to-Set-up-a-Database-for-Metasploit
                                                  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%     %%%         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%  %%  %%%%%%%%   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%  %  %%%%%%%%   %%%%%%%%%%% https://metasploit.com %%%%%%%%%%%%%%%%%%%%%%%%
%%  %%  %%%%%%   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%  %%%%%%%%%   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%  %%%  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%    %%   %%%%%%%%%%%  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  %%%  %%%%%
%%%%  %%  %%  %      %%      %%    %%%%%      %    %%%%  %%   %%%%%%       %%
%%%%  %%  %%  %  %%% %%%%  %%%%  %%  %%%%  %%%%  %% %%  %% %%% %%  %%%  %%%%%
%%%%  %%%%%%  %%   %%%%%%   %%%%  %%%  %%%%  %%    %%  %%% %%% %%   %%  %%%%%
%%%%%%%%%%%% %%%%     %%%%%    %%  %%   %    %%  %%%%  %%%%   %%%   %%%     %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  %%%%%%% %%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%          %%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


       =[ metasploit v6.0.15-dev-17fb85c670               ]
+ -- --=[ 2071 exploits - 1122 auxiliary - 352 post       ]
+ -- --=[ 592 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 7 evasion                                       ]

Metasploit tip: View a module's description using info, or the enhanced version in your browser with info -d

msf6 > use payload/python/meterpreter/reverse_tcp
msf6 payload(python/meterpreter/reverse_tcp) > set LHOST 127.0.0.1
LHOST => 127.0.0.1
msf6 payload(python/meterpreter/reverse_tcp) > generate -f rawTraceback (most recent call last):
	22: from ./msfconsole:23:in `<main>'
	21: from /home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	20: from /home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	19: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:141:in `run'
	18: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:321:in `get_input_line'
	17: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/input/readline.rb:100:in `pgets'
	16: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/input/readline.rb:162:in `readline_with_output'
	15: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4875:in `readline'
	14: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4853:in `readline_internal'
	13: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4779:in `readline_internal_charloop'
	12: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4363:in `_rl_dispatch'
	11: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4374:in `_rl_dispatch_subseq'
	10: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6903:in `rl_complete'
	 9: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6813:in `rl_complete_internal'
	 8: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6329:in `gen_completion_matches'
	 7: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/readline.rb:136:in `readline_attempted_completion_function'
	 6: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:69:in `block in init_tab_complete'
	 5: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:377:in `tab_complete'
	 4: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `tab_complete_stub'
	 3: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `each'
	 2: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:403:in `block in tab_complete_stub'
	 1: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:444:in `tab_complete_helper'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/payload.rb:213:in `cmd_generate_tabs': undefined method `+' for nil:NilClass (NoMethodError)

```

## Steps to reproduce

See above,

## Were you following a specific guide/tutorial or reading documentation?

Nope

## Expected behavior

We either get no autocompletion or we get some prompt informing the user for help. In no case should we crash.

## Current behavior

We get a crash and potentially lose all of our sessions. Everyone quits in a fit of rage and the pentest is ruined. Okay maybe not quite that but its pretty easy for this to be triggered and cause issues.

### Metasploit version

v6.0.15-dev-17fb85c670

## Additional Information
Again the stack trace here is probably going to be more helpful :P

### PR DESCRIPTION
**Pull request by cgranleese-r7**
This PR Resolves #14358.

The crash was previously caused when the user tried tab completing with the generate command when no results would be returned, this resulted in a crash and would kill the msfconsole.  

An example command that would have caused the crash:
```
generate -f rawTrac<tab>
```
Example of crash:
fix_generate_command_pr

This fix will now catch any commands that would have returned no results previously, to now return a blank array. 

fix_generate_command_fix_pr

## Verification

Testing steps:

- [ ] Start `msfconsole`
- [ ] `use payload/python/meterpreter/reverse_tcp`
- [ ] Try a command that would have previously returned no results
- [ ] E.g. `generate -f rawTrac<tab>`
- [ ] **Verify** that these commands no longer kill `msfconsole`

### CODE REVIEW

File: lib/rex/ui/text/dispatcher_shell.rb [hunk 1]
```diff
@@ -312,7 +312,7 @@ def tab_complete_generic(fmt, str, words)
       elsif arg.kind_of?(Array)
         tabs = arg.map {|a| a.to_s}
       end
-      tabs
+      tabs.nil? ? [] : tabs
```
Comment (adfoster-r7) [inline lib/rex/ui/text/dispatcher_shell.rb:315]: It feels like the fix should live closer to the function that's returning nil 👀 

i.e. the contract for the function in question should be to always return an array, even if it's an empty array, rather than `nil` 🤔

Comment (adfoster-r7) [reply lib/rex/ui/text/dispatcher_shell.rb:315]: Additional thoughts behind that comment: There's probably other calls in the codebase that assume nil is never returned, and will crash in similar scenarios. It might be best to solve the underlying problem - rather than fix this specific side effect/bug that you're seeing 🔍

Comment (cgranleese-r7) [reply lib/rex/ui/text/dispatcher_shell.rb]: So I have moved the code for the fix into `tab_complete_filenames(str, words)`. 

Thanks for calling this out, need to think about this more when implementing fixes. As you say, this would only have solved problems within `tab_complete_generic(fmt, str, words)`, whereas now it will solve the issue no matter where it is called.

Thanks @adfoster-r7 👍

**Comment by gwillcox-r7** [comment]
Looks like this is working as expected, at least when I tested the example from the issue I originally raised:

Before: 
```
msf6 > use payload/python/meterpreter/reverse_tcp
msf6 payload(python/meterpreter/reverse_tcp) > generate -f rawTracTraceback (most recent call last):
	22: from ./msfconsole:23:in `<main>'
	21: from /home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	20: from /home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	19: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:141:in `run'
	18: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:321:in `get_input_line'
	17: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/input/readline.rb:100:in `pgets'
	16: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/input/readline.rb:162:in `readline_with_output'
	15: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4875:in `readline'
	14: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4853:in `readline_internal'
	13: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4779:in `readline_internal_charloop'
	12: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4363:in `_rl_dispatch'
	11: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4374:in `_rl_dispatch_subseq'
	10: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6903:in `rl_complete'
	 9: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6813:in `rl_complete_internal'
	 8: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6329:in `gen_completion_matches'
	 7: from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/readline.rb:136:in `readline_attempted_completion_function'
	 6: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:69:in `block in init_tab_complete'
	 5: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:377:in `tab_complete'
	 4: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `tab_complete_stub'
	 3: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `each'
	 2: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:403:in `block in tab_complete_stub'
	 1: from /home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:444:in `tab_complete_helper'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/payload.rb:213:in `cmd_generate_tabs': undefined method `+' for nil:NilClass (NoMethodError)
```

After:
```
msf6 > use payload/python/meterpreter/reverse_tcp
msf6 payload(python/meterpreter/reverse_tcp) > generate -f 
Display all 106 possibilities? (y or n)
msf6 payload(python/meterpreter/reverse_tcp) > generate -f rawTrac
*hit tab multiple times*
msf6 payload(python/meterpreter/reverse_tcp) > generate -f rawTrac
```

**Comment by gwillcox-r7** [comment]
# Release Notes
A bug within `msfconsole` has been fixed which resulted in Metasploit crashing with a stack trace if no results where returned when attempting to hit the TAB key to autocomplete a command. `msfconsole` will now instead return no results if it cannot autocomplete the command.
