### PR TITLE
Modified zabbix login to work with newer versions of zabbix

### LINKED ISSUE #14195: The zabbix_login script does not detect zabbix server after login
## Description
When using zabbix_scanner against later versions of zabbix server appliance, it does not detect web site as a zabbix 
server after successful login.  Tested using Zabbix server appliances versions 3, 4 and 5.

## Steps to reproduce

How'd you do it?

1. Obtained Zabbix server appliance fimage rom the following link: https://www.zabbix.com/download_appliance
2. Started up the appliance images in Virtualbox and ran the metasploit module against each appliance created.

## Were you following a specific guide/tutorial or reading documentation?
No.  Reason for this testing - I was hoping to complete and submit the documentation for this module, and pulled the 
Appliance VM for testing and completing the documentation file.

## Expected behavior
Since these are default Zabbix installations, I expected the module to successfully check that the default credentials are still in place as well as detect that it is a zabbix server installation.  I believe the module was originally written for an older version of zabbix server and the text within the body has changed - the search string the module is using is no longer in the newer versions of Zabbix.

## Current behavior
Ran zabbix_login module from metasploit, with following result:
msf auxiliary(scanner/http/zabbix_login) > set RHOSTS 192.168.0.151
RHOSTS => 192.168.0.151
msf5 auxiliary(scanner/http/zabbix_login) > run

[*] 192.168.0.151:80 - Unexpected HTTP body (is this really Zabbix?)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed

I downloaded version 3, 4 and 5 of zabbix and confirmed the above happens in all 3 cases.

Appliance Zabbix server version 3 - OS is Ubuntu 16.04
Appliance Zabbix server version 4 - OS is CentOS 8
Appliance Zabbix server version 5 - OS is CentOS 8
What happens instead?

### Metasploit version
Framework: 5.0.101-dev
Console: 5.0.101-dev
Running on Kali linux.

## Additional Information
msf5 auxiliary(scanner/http/zabbix_login) > set loglevel 3
loglevel => 3
msf5 auxiliary(scanner/http/zabbix_login) > use scanner/http/zabbix_login
msf5 auxiliary(scanner/http/zabbix_login) > set RHOSTS 192.168.0.151
RHOSTS => 192.168.0.151
msf5 auxiliary(scanner/http/zabbix_login) > run

[-] 192.168.0.151:80 - Unexpected HTTP body (is this really Zabbix?)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/http/zabbix_login) > 

Note : if this is verified as an issue, I would like to work on fixing the issue.

### PR DESCRIPTION
**Pull request by spassino**
Added documentation for zabbix login

Github issue number is 14195

Please ensure you are submitting **from a unique branch** in your [repository](https://github.com/rapid7/metasploit-framework/pull/11086#issuecomment-445506416) to master in Rapid7's.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] use auxiliary/scanner/http/zabbix_login
- [ ] set RHOSTS
- [ ] run

    - Success: 'Admin:zabbix'

Above was tested using Zabbix Virtual images running in Virtualbox 6.1
Images used were Zabbix Server versions 3, 4 and 5.
_Note that on Zabbix server version 5, the target uri moved and requires an additional variable set in msfconsole
set TARGETURI /_

Testing done using virtual appliances for Zabbix, available at https://www.zabbix.com/download_appliance.
Used appliance versions 3, 4 and 5 (5 is latest release)
Virtuals running within Virtualbox 6.1
Screenshot of test against zabbix 5 running on IP 192.168.0.125
test-zabbix5

### Reasons for change
Original plan was to provide markdown documentation for auxiliary/scanner/http/zabbix_login.  A test environment was created to build documentation, but discovered that the auxiliary/scanner/http/zabbix_login module would fail.  All testing is done using default admin credentials for zabbix.  Error message follows:
zabbix_login_fail

Further investigation showed that module is using the regex to confirm the string exists in the html after successful login.  I believe this module was written for a version prior to version 3 ( the oldest version I was able to test with).  The older versions of Zabbix must have contained a slightly different string within the html.  The credentials did successfully log in but this error does not register as success, it also does not populate metasploit backend database with credential information.  
From this testing, decided to modify the library so that the scanner worked as expected on the newer versions of zabbix.

### CODE REVIEW

**Comment by gwillcox-r7** [comment]
@spassino  Hmm this seems to be an odd mix of a documentation update an a library code fix. Can you please update your description to clarify this up a little more? Also as library code could potentially be used by other modules, and you are also loosening the regexes in your PR in a way that could lead to more false positives, I would like to see further explanations in your PR description as to what this is specifically trying to solve and why you feel these changes are necessary given the amount of code this could affect (again not sure how many modules use this library but in general we always need to be careful with library code due to the potential for small changes to affect large portions of the code base).

**Comment by spassino** [comment]
@gwillcox-r7 - understood.  I updated PR with additional information.

File: lib/metasploit/framework/login_scanner/zabbix.rb [hunk 1]
```diff
@@ -48,7 +48,7 @@ def check_setup
               return "Unexpected HTTP response code #{res.code} (is this really Zabbix?)"
             end
 
-            if res.body.to_s !~ /Zabbix ([^\s]+) Copyright .* by Zabbix/m
+            if res.body.to_s !~ /Zabbix/
```
Comment (gwillcox-r7) [inline lib/metasploit/framework/login_scanner/zabbix.rb:51]: This will match on anything that contains `Zabbix` in its page. I could make a page that contains a reference to Zabbix in passing, such as in a comment on a blog, and this module will think that the target is a Zabbix target. This is really not what you want to be doing.

If you are trying to change this to support multiple versions then what I suggest you do is to keep the current regex, and then add a new check specifically for the new string you are seeing in the application. This will make sure that you still keep support for the old versions of the app whilst also adding in support for the new version string you are seeing. Again try make it as specific as possible, as otherwise you run a high change of false positives which we want to avoid.

File: lib/metasploit/framework/login_scanner/zabbix.rb [hunk 2]
```diff
@@ -115,14 +115,15 @@ def try_login(credential)
           res = try_credential(credential)
           if res && res.code == 302
             opts = {
-              'uri'     => normalize_uri('profile.php'),
+              #'uri'     => normalize_uri('profile.php'), --> works for versions 3 and 4 but not 5
+              'uri'     => normalize_uri('discoveryconf.php'),
```
Comment (gwillcox-r7) [inline lib/metasploit/framework/login_scanner/zabbix.rb:119]: Probably best to remove this comment in the final version but out of interest have you confirmed that `discoveryconf.php` still exists in all the versions prior to version 3? If not you may be breaking functionality by changing this URL, and it may be better to keep this URL in there and then add a new check in which runs if this current check fails to make sure its not failing cause the target is a newer version of Zabbix.

File: lib/metasploit/framework/login_scanner/zabbix.rb [hunk 3]
```diff
@@ -115,14 +115,15 @@ def try_login(credential)
...
               'method'  => 'GET',
               'headers' => {
                 'Cookie'  => "zbx_sessionid=#{self.zsession}"
               }
             }
             res = send_request(opts)
-            if (res && res.code == 200 && res.body.to_s =~ /<title>Zabbix .*: User profile<\/title>/)
+            if (res && res.code == 200 && res.body.to_s =~ /Zabbix/)
```
Comment (gwillcox-r7) [inline lib/metasploit/framework/login_scanner/zabbix.rb:126]: See my comment above, I can easily bypass this Regex and trigger a false positive by having the word `Zabbix` anywhere within the body of my server's response. This regex needs to be a lot tighter, especially as it its in library code that could be reused by other modules.

File: documentation/modules/auxiliary/scanner/http/zabbix_login.md [hunk 4]
```diff
@@ -0,0 +1,48 @@
+## Vulnerable Application
+
+This module attempts to login to zabbix server, by default module will use default credentials and also supports user defined login credentials
```
Comment (gwillcox-r7) [inline documentation/modules/auxiliary/scanner/http/zabbix_login.md:3]: This sentence could do with some English improvements. I'll try edit this up.

Comment (gwillcox-r7) [reply documentation/modules/auxiliary/scanner/http/zabbix_login.md:3]: Also what are the default credentials for Zabbix? Might be good to reference them here.

File: documentation/modules/auxiliary/scanner/http/zabbix_login.md [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+### Example run against zabbix version 3
+
+```
+msf5 > use auxiliary/scanner/http/zabbix_login
+msf5 auxiliary(scanner/http/zabbix_login) > set RHOSTS 192.168.0.151
+RHOSTS => 192.168.0.151
+msf5 auxiliary(scanner/http/zabbix_login) > run
+
+[*] 192.168.0.151:80 - Found Zabbix version
+[*] 192.168.0.151:80 - Zabbix has disabled Guest mode
```
Comment (gwillcox-r7) [inline documentation/modules/auxiliary/scanner/http/zabbix_login.md:42]: General comment but I don't think Zabbix disabled guest mode here :P That would be the server admin or whoever set up the Zabbix server. So it would be more appropriate to say `Target appears to have disabled Guest mode`.

**Review by gwillcox-r7 — CHANGES_REQUESTED** [review]
I do think the idea here looks good, but the regex in many places needs to be more strict. I've also left a few comments where I need more input to proceed. Please also run `tools/dev/msftidy_docs.rb documentation/modules/auxiliary/scanner/http/zabbix_login.md` and attempt to fix as many of the issues as you can. If there are any that you can't fix that is fine, but it will get you in the habit of ensuring your documentation conforms to compliance standards.

File: documentation/modules/auxiliary/scanner/http/zabbix_login.md (hunk 4 above)
Comment (spassino) [reply documentation/modules/auxiliary/scanner/http/zabbix_login.md:3]: zabbix default creds are Admin:zabbix

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 2 above)
Comment (spassino) [reply lib/metasploit/framework/login_scanner/zabbix.rb:119]: Yes, confirmed that discoveryconf.php exists as of version 1.8.22 up to current

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 1 above)
Comment (spassino) [reply lib/metasploit/framework/login_scanner/zabbix.rb:51]: I tested with versions 3,4, and 5 and noticed that the Copyright line is no longer part of the return code after successful login.
I did notice that the Author line is consistent, as far back as version 2.0.21 of Zabbix.  Suggesting that the regex change to the following:
            if res.body.to_s !~ /name="Author" content="Zabbix SIA"/m
This would tighten up the regex as well as support old and new versions.

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 3 above)
Comment (spassino) [reply lib/metasploit/framework/login_scanner/zabbix.rb:126]: See my comment above.  I did test using the regex searching for the Author string and it tested successfully 
`            if res.body.to_s !~ /name="Author" content="Zabbix SIA"/`

Not sure if this matters, but according to the Zabbix repository page, versions 5.X are the only ones listed as supported.

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 1 above)
Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb:51]: Hmm I'll take a look at this tomorrow but the issue with just changing this regex, whilst I do think it is a good idea, is that the previous regex included a group which is then assigned to `self.version` on line 55 with the assignment `self.version = $1` (see https://github.com/rapid7/metasploit-framework/pull/14297/files#diff-9e2c7de768883fab840603662ce0e5aeecf96279c32647fd334bd3e847226edeR55 )

I'll need to examine this further to confirm but there is a the potential that this may be an issue if this `self.version` value is actually being used within the code.

My initial inspection makes me think this `self.version` line is actually used in the output as indicated by  https://github.com/rapid7/metasploit-framework/pull/14297/files#diff-8fe89a467adae71b015090ebd7c121feffad8826cd9a94d734e32349fa45d881R41 not showing any version number in the output like it would normally, most likely as a result of your changes to the regex.

Whilst in this case it doesn't strictly speaking break anything critical it does prevent what appears to be an intentional version enumeration part of the code here.

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 2 above)
Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb:119]: Hmm so my thoughts on this are as follows:

Whilst we technically try to avoid supporting seriously outdated OS's that are no longer maintained by the developers, looking at https://www.zabbix.com/rn/rn1.8.22 suggests this OS was released in 2014, or roughly 6 years ago. According to https://www.zabbix.com/life_cycle_and_release_policy the EOL for this software, as in critical updates etc, is 5 years after release, which would mean this version specifically is EOL now with no plans for any more security updates or critical updates.

On the other hand this software is only 6 years old, and its possible people could still be using it in their environment as people do have the tendency to leave legacy software running in their environments.

I'll get back to you on this one, cause on the one hand as a library we should be supporting as many targets as possible, but on the other hand I know there is a limit to how long we can continue supporting old EOL machines.

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 3 above)
Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb:126]: See my comment above r.e this. Also r.e the ones that are supported, you are incorrect on this, refer to https://www.zabbix.com/life_cycle_and_release_policy which shows versions as far back as Zabbix 3.0 LTS are still being supported under their Limited Support cycle for critical and security relevant updates.

File: documentation/modules/auxiliary/scanner/http/zabbix_login.md (hunk 4 above)
Comment (gwillcox-r7) [reply documentation/modules/auxiliary/scanner/http/zabbix_login.md:3]: Would you mind explaining this here, perhaps just putting in as `(Admin:zabbix)`? Just makes it easier for readers to reference who might not be familiar with the default login credentials for Zabbix.

File: documentation/modules/auxiliary/scanner/http/zabbix_login.md (hunk 5 above)
Comment (gwillcox-r7) [reply documentation/modules/auxiliary/scanner/http/zabbix_login.md:42]: As per earlier comment, I'm just going to note here that the first line of output here no longer includes the version info, and instead just prints `Found Zabbix version` without the version number as part of this string, due to the regex changes you made.

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 1 above)
Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb:51]: Okay after further review I think the best regex might be something like this:

`<a target="_blank" class="grey link-alt" href="http[sS]{0,1}:\/\/www\.zabbix\.com\/documentation\/(\d+\.\d+)\/">Help<\/a>`

This seems to match both on the latest version of Zabbix, 5.0.5 LTS, as well as version 4.4, 4.0, and 3.2 of Zabbix, and also ensures that we are still grabbing the version information so that it can be output by the scanner.

We would then keep the other regex that is in the code already and run this second regex if the one in the code already fails, such that it would basically go "if the first regex fails, try this second regex. If both fail, then the target likely isn't a Zabbix machine".

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 2 above)
Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb:119]: Ok after further review this should be fine, we could in theory go older with certain pages but it seems that some of them don't always have different behavior depending on the versions so this seems like the most reliable option for now.

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 3 above)
Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb:126]: Ok also this new regex will have to be adjusted.....the way this is programmed at the moment, we could not log in successfully and because the resulting page will contain Zabbix in its response, and will return a 200 OK code, the code will think that the credentials were successful.

File: documentation/modules/auxiliary/scanner/http/zabbix_login.md (hunk 5 above)
Comment (gwillcox-r7) [reply documentation/modules/auxiliary/scanner/http/zabbix_login.md]: Made changes to resolve this with https://github.com/rapid7/metasploit-framework/pull/14297/commits/bd578324941b2ef1f65b452c80c45875f9bf9b68

File: documentation/modules/auxiliary/scanner/http/zabbix_login.md (hunk 4 above)
Comment (gwillcox-r7) [reply documentation/modules/auxiliary/scanner/http/zabbix_login.md]: Resolved this with https://github.com/rapid7/metasploit-framework/pull/14297/commits/bd578324941b2ef1f65b452c80c45875f9bf9b68

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 2 above)
Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb]: https://github.com/rapid7/metasploit-framework/pull/14297/commits/bd578324941b2ef1f65b452c80c45875f9bf9b68 applies the fixes for the comment part as I mentioned previously.

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 1 above)
Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb]: Applied the regex fixes in https://github.com/rapid7/metasploit-framework/pull/14297/commits/bd578324941b2ef1f65b452c80c45875f9bf9b68 and nested them so that we still have support for the old version. New output now includes the version info as well as a result of updating this regex.

```
msf6 auxiliary(scanner/http/zabbix_login) > run
[*] 172.29.121.85:80 - Found Zabbix version 5.0
[*] 172.29.121.85:80 - This Zabbix instance has disabled Guest mode
[+] 172.29.121.85:80 - Success: 'Admin:zabbix'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) >
```

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 3 above)
Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb:130]: Alright so I figured out that on Zabbix 5.x and later the `/profile.php` page got moved to `/zabbix.php?action=userprofile.edit`, so all one needs to do is slightly adjust the original regex and then ensure that if the original request to `/profile.php` fails, that the same test is tried again with `/zabbix.php?action=userprofile.edit`. If both attempts fail then we will return the usual failure case.

File: lib/metasploit/framework/login_scanner/zabbix.rb [hunk 6]
```diff
@@ -113,17 +127,16 @@ def try_credential(credential)
...
-            }
-            res = send_request(opts)
-            if (res && res.code == 200 && res.body.to_s =~ /<title>Zabbix .*: User profile<\/title>/)
+            res = perform_login_attempt('profile.php') # profile.php exists in Zabbix versions up to Zabbix 5.x
+            if (res && res.code == 200 && res.body.to_s =~ /<title>.*: User profile<\/title>/)
               return {:status => Metasploit::Model::Login::Status::SUCCESSFUL, :proof => res.body}
+            else
+              res = perform_login_attempt('/zabbix.php?action=userprofile.edit') # On version 5.x and later of Zabbix, profile.php was replaced with /zabbix.php?action=userprofile.edit
+              if (res && res.code == 200 && res.body.to_s =~ /<title>.*: User profile<\/title>/)
+                return {:status => Metasploit::Model::Login::Status::SUCCESSFUL, :proof => res.body}
```
Comment (smcintyre-r7) [inline lib/metasploit/framework/login_scanner/zabbix.rb:138]: I don't think this is using the standard `send_request` method that modules use and is instead using [this one](https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/login_scanner/http.rb#L218) which will [raise exceptions](https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/login_scanner/http.rb#L218). (Looks like the docs saying it'll return `nil` are wrong 😬 ). When a connection error is raised, you should catch it and return `UNABLE_TO_CONNECT`, this [this one](https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/login_scanner/jupyter.rb#L53-L54) does so it can be properly handled by aborting the rest of the attempts.

Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb]: @smcintyre-r7 This should now be resolved with https://github.com/rapid7/metasploit-framework/pull/14297/commits/b5060054384b1b5dbec143efda762ca846cc5e1d

**Comment by smcintyre-r7** [comment]
This doesn't appear to be working for me. I tested it with the latest version I could download, 5.2. I can navigate to the page and I know that `Admin:zabbix` are valid credentials.

```
msf6 auxiliary(scanner/http/zabbix_login) > show options 

Module options (auxiliary/scanner/http/zabbix_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   PASSWORD                           no        A specific password to authenticate with
   PASS_FILE                          no        File containing passwords, one per line
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            192.168.159.49   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT             80               yes       The target port (TCP)
   SSL               false            no        Negotiate SSL/TLS for outgoing connections
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   TARGETURI         /zabbix/         yes       The path to the Zabbix server application
   THREADS           20               yes       The number of concurrent threads (max one per host)
   USERNAME                           no        A specific username to authenticate as
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts
   VHOST                              no        HTTP server virtual host

msf6 auxiliary(scanner/http/zabbix_login) > set TARGETURI /
TARGETURI => /
msf6 auxiliary(scanner/http/zabbix_login) > set HttpTrace true
HttpTrace => true
msf6 auxiliary(scanner/http/zabbix_login) > run

[*] 192.168.159.49:80 - Found Zabbix version 5.2
####################
# Request:
####################
GET /dashboard.php HTTP/1.1
Host: 192.168.159.49
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)


####################
# Response:
####################
HTTP/1.1 404 Not Found
Server: nginx
Date: Thu, 29 Oct 2020 19:34:56 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=20
X-Powered-By: PHP/7.2.24

File not found.

[*] 192.168.159.49:80 - This Zabbix instance has disabled Guest mode
[-] 192.168.159.49:80 - Failed: 'Admin:zabbix'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) >
```

It looks like processing the session cookie (which was not changed by this PR) needs to be updated. Currently it's this and GitHub won't let me comment on it:
```ruby
          if res && res.get_cookies =~ /zbx_sessionid=(\w*);/i
            self.zsession = $1
          end
```

Updating it to use the regex `res.get_cookies =~ /(zbx_session(?:id)?)=(\w*)(?:%3d){0,2};/i` worked for me. You'll need to handle the updated session cookie name which is now group 1. Something like `self.zsession = { $1 => $2 }` should do the trick, then remember to use the cookie name when issuing the HTTP request.

**Comment by gwillcox-r7** [comment]
Thanks @smcintyre-r7. I'm going to take a look through all the other versions of the appliance that are available to see if there are any other oddities. For reference this is what I get when I log into Zabbix 5.0.5 LTS so this may be a more recent change that they made:

```
HTTP/1.1 302 Found
Server: nginx
Date: Thu, 29 Oct 2020 21:49:07 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
X-Powered-By: PHP/7.2.24
Set-Cookie: PHPSESSID=t90a7q9r97st003ut2g8rieiv0; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: zbx_sessionid=1483165f6e3ed0dc907121e7e7a9b3d1; expires=Sun, 29-Nov-2020 21:49:07 GMT; Max-Age=2678400; HttpOnly
Location: zabbix.php?action=dashboard.view
Content-Length: 0
```

**Comment by gwillcox-r7** [comment]
Ok yeah looks like 5.2.0 LTS changed the login mechanism as I'm seeing the result you saw above and Base64 decoding the object shows that they seem to be setting the cookie value now to an object of the following format:

```
{"sessionid":"5988e6c143396e8965f036a41a0a740d","sign":"0zF7YEKqNaE4ZuGT6\/tRMeX4brepgTxTJeWKVImeGuovqwAyCPcVOz8KznVNy78gDbiePwv0nBPVqhyza\/MxMA=="}
```
I checked all the previous versions so long and they all use the old format where the value of `sessionid` is just assigned to `zbx_session`. So looks like this was just a recent change. Thanks for pointing this out Spencer!

**Comment by spassino** [comment]
Try changing TARGETURI to /

On latest version, I think it was changed from /zabbix/


On October 29, 2020 at 12:59 PM, Spencer McIntyre <notifications@github.com> wrote:






This doesn't appear to be working for me. I tested it with the latest version I could download, 5.2. I can navigate to the page and I know that Admin:zabbix are valid credentials.

msf6 auxiliary(scanner/http/zabbix_login) > show options 

Module options (auxiliary/scanner/http/zabbix_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   PASSWORD                           no        A specific password to authenticate with
   PASS_FILE                          no        File containing passwords, one per line
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            192.168.159.49   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT             80               yes       The target port (TCP)
   SSL               false            no        Negotiate SSL/TLS for outgoing connections
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   TARGETURI         /zabbix/         yes       The path to the Zabbix server application
   THREADS           20               yes       The number of concurrent threads (max one per host)
   USERNAME                           no        A specific username to authenticate as
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts
   VHOST                              no        HTTP server virtual host

msf6 auxiliary(scanner/http/zabbix_login) > set TARGETURI /
TARGETURI => /
msf6 auxiliary(scanner/http/zabbix_login) > set HttpTrace true
HttpTrace => true
msf6 auxiliary(scanner/http/zabbix_login) > run

[*] 192.168.159.49:80 - Found Zabbix version 5.2
####################
# Request:
####################
GET /dashboard.php HTTP/1.1
Host: 192.168.159.49
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)


####################
# Response:
####################
HTTP/1.1 404 Not Found
Server: nginx
Date: Thu, 29 Oct 2020 19:34:56 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=20
X-Powered-By: PHP/7.2.24

File not found.

[*] 192.168.159.49:80 - This Zabbix instance has disabled Guest mode
[-] 192.168.159.49:80 - Failed: 'Admin:zabbix'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) >


It looks like processing the session cookie (which was not changed by this PR) needs to be updated. Currently it's this and GitHub won't let me comment on it:

          if res && res.get_cookies =~ /zbx_sessionid=(\w*);/i
            self.zsession = $1
          end

Updating it to use the regex res.get_cookies =~ /(zbx_session(?:id)?)=(\w*)(?:%3d){0,2};/i worked for me. You'll need to handle the updated session cookie name which is now group 1. Something like self.zsession = { $1 => $2 } should do the trick, then remember to use the cookie name when issuing the HTTP request.

**Comment by gwillcox-r7** [comment]
@spassino Review the output again, he already did change it to /

**Comment by gwillcox-r7** [comment]
Alright so also looks like there are more updates which need to be done to the rest of the code as `/dashboard.php` doesn't exist on newer versions of `Zabbix`, and has been replaced with `/zabbix.php?action=dashboard.view`.

**Comment by gwillcox-r7** [comment]
Ok there is some seriously weird behavior going on here. I think Zabbix 5.2 may have built in protections of some sort cause if you try replay a previous login attempt it won't work. My guess is the session token also has some form of CSRF token or similar, but I can't see anything of the sort. Very weird.

**Comment by gwillcox-r7** [comment]
Alright here is my tests with the new code and it appears to be working well, including also an update on version 3 where it correctly reports that it has Guest mode enabled:

```
msf6 auxiliary(scanner/http/zabbix_login) > set RHOSTS 172.18.77.139
RHOSTS => 172.18.77.139
msf6 auxiliary(scanner/http/zabbix_login) > run

[-] 172.18.77.139:80 - Unexpected HTTP response code 404 (is this really Zabbix?)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) > set TARGETURI /
TARGETURI => /
msf6 auxiliary(scanner/http/zabbix_login) > run

[*] 172.18.77.139:80 - Found Zabbix version 5.0
[*] 172.18.77.139:80 - This Zabbix instance has disabled Guest mode
[-] 172.18.77.139:80 - Failed: 'Admin:zabbix'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) > set USERNAME Admin
USERNAME => Admin
msf6 auxiliary(scanner/http/zabbix_login) > set PASSWORD zabbix2
PASSWORD => zabbix2
msf6 auxiliary(scanner/http/zabbix_login) > run

[*] 172.18.77.139:80 - Found Zabbix version 5.0
[*] 172.18.77.139:80 - This Zabbix instance has disabled Guest mode
[-] 172.18.77.139:80 - Failed: 'Admin:zabbix'
[+] 172.18.77.139:80 - Success: 'Admin:zabbix2'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) > set RHOSTS 172.18.65.33
RHOSTS => 172.18.65.33
msf6 auxiliary(scanner/http/zabbix_login) > run

[-] 172.18.65.33:80 - Unexpected HTTP response code 403 (is this really Zabbix?)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) > set TARGETURI /zabbix/
TARGETURI => /zabbix/
msf6 auxiliary(scanner/http/zabbix_login) > run

[*] 172.18.65.33:80 - Found Zabbix version 4.0
[*] 172.18.65.33:80 - This Zabbix instance has disabled Guest mode
[+] 172.18.65.33:80 - Success: 'Admin:zabbix'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) > set RHOSTS 172.18.76.235
RHOSTS => 172.18.76.235
msf6 auxiliary(scanner/http/zabbix_login) > run

[*] 172.18.76.235:80 - Found Zabbix version 3.0
[+] 172.18.76.235:80 - Note: This Zabbix instance has Guest mode enabled
[+] 172.18.76.235:80 - Success: 'Admin:zabbix'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) > set RHOSTS 172.18.77.59
RHOSTS => 172.18.77.59
msf6 auxiliary(scanner/http/zabbix_login) > set TARGETURI /
TARGETURI => /
msf6 auxiliary(scanner/http/zabbix_login) > run

[*] 172.18.77.59:80 - Found Zabbix version 5.2
[*] 172.18.77.59:80 - This Zabbix instance has disabled Guest mode
[+] 172.18.77.59:80 - Success: 'Admin:zabbix'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) > 
```

File: lib/metasploit/framework/login_scanner/zabbix.rb [hunk 7]
```diff
@@ -76,8 +76,8 @@ def send_request(opts)
           res = cli.send_recv(req)
 
           # Found a cookie? Set it. We're going to need it.
-          if res && res.get_cookies =~ /zbx_sessionid=(\w*);/i
-            self.zsession = $1
+          if res && res.get_cookies =~ /(?:zbx_session(?:id)?)=([a-zA-Z0-9]*)((?:%3D){0,2});/i
+            self.zsession = $1 + $2
```
Comment (smcintyre-r7) [inline lib/metasploit/framework/login_scanner/zabbix.rb:80]: If you did capture the cookie name, you could update this to:
```
self.zsession = $1 + '=' + $2
```

and then later on you'd only need to set one cookie because you know the value that's being used:
```
'Cookie'  => self.zsession
```

Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb:80]: Ooh nice point, I'll see if I can't do this :)

**Comment by gwillcox-r7** [comment]
Woops looks like session cookies can have _ in them according to our spec tests, going to have to adjust this regex in more ways one to fix that and address the recent optimization suggestion 😄

File: lib/metasploit/framework/login_scanner/zabbix.rb (hunk 7 above)
Comment (gwillcox-r7) [reply lib/metasploit/framework/login_scanner/zabbix.rb]: @smcintyre-r7 This should now be resolved in https://github.com/rapid7/metasploit-framework/pull/14297/commits/c62001c21059b3283acab75af6d45a0cc0870eb3

**Comment by smcintyre-r7** [comment]
@gwillcox-r7 Looks like this is ready for testing again, is that right?

**Comment by gwillcox-r7** [comment]
> @gwillcox-r7 Looks like this is ready for testing again, is that right?

Yes it should be ready for testing again.

**Comment by smcintyre-r7** [comment]
Tested succesfully and working as intended now for v5.2. Everything looks good, I'll go ahead and merge this in shortly. Thanks!

```
msf6 auxiliary(scanner/http/zabbix_login) > show options 

Module options (auxiliary/scanner/http/zabbix_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   PASSWORD                           no        A specific password to authenticate with
   PASS_FILE                          no        File containing passwords, one per line
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            192.168.159.49   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT             80               yes       The target port (TCP)
   SSL               false            no        Negotiate SSL/TLS for outgoing connections
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   TARGETURI         /                yes       The path to the Zabbix server application
   THREADS           30               yes       The number of concurrent threads (max one per host)
   USERNAME                           no        A specific username to authenticate as
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           false            yes       Whether to print output for all attempts
   VHOST                              no        HTTP server virtual host

msf6 auxiliary(scanner/http/zabbix_login) > run

[*] 192.168.159.49:80 - Found Zabbix version 5.2
[*] 192.168.159.49:80 - This Zabbix instance has disabled Guest mode
[+] 192.168.159.49:80 - Success: 'Admin:zabbix'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/http/zabbix_login) >
```

**Review by smcintyre-r7 — APPROVED** [review]

**Comment by gwillcox-r7** [comment]
# Release Notes
Support for Zabbix 3.x, 4.x, and 5.x has been added to `zabbix_login.rb` and its supporting libraries, allowing it to target recent Zabbix releases up to and including the latest Zabbix 5.2 LTS release. In addition new documentation has been written up for the `zabbix_login.rb` module to allow users to better understand how to utilize the module.

**Comment by gwillcox-r7** [comment]
Thanks for the PR @spassino! Sorry if this one took a little longer than expected :)

**Comment by spassino** [comment]
> Thanks for the PR @spassino! Sorry if this one took a little longer than expected :)

thank you all for your patience - first time for me ...
