### PR TITLE
Rewind error handling to normal (Round 2)

### LINKED ISSUE #4552: fail_with has no special handling
Code:
```
unless res.headers["Location"].include? "index.jsp"
      fail_with(Failure::Unknown, 'Authentication failed')
end
```
Output:

[-] Auxiliary failed: RuntimeError unknown: Authentication failed
[-] Call stack:
[-]   /root/metasploit-framework/lib/msf/core/module.rb:278:in \`fail_with'
[-]   /root/.msf4/modules/exploits/test/xxe.rb:63:in `run'

### PR DESCRIPTION
**Pull request by wchen-r7**
This should rewind everything this pull request did: https://github.com/rapid7/metasploit-framework/pull/4473

The reason we want to rewind this is because the errors are way too verbose, and we're frequently getting complaints about it. You see a backtrace even though there is no bug.

This PR replaces #4630. It also does not fix #4552, but related.

### CODE REVIEW

**Comment by todb-r7** [comment]
Okay, I think this is intended, but I still don't see the stacktrace in `framework.log`. Let me know if that's what you're expecting, @wchen-r7?

## Before fix

````
[ruby-2.1.5@metasploit-framework](upstream-master) 
todb@mazikeen:~/git/rapid7/metasploit-framework$ ./msfconsole -Lq
msf exploit(distcc_exec) > edit
[*] Launching /usr/bin/vim /home/todb/git/rapid7/metasploit-framework/modules/exploits/unix/misc/distcc_exec.rb
msf exploit(distcc_exec) > reload
[*] Reloading module...
msf exploit(distcc_exec) > git diff
[*] exec: git diff

diff --git a/modules/exploits/unix/misc/distcc_exec.rb b/modules/exploits/unix/misc/distcc_exec.rb
index 25625e1..20be448 100644
--- a/modules/exploits/unix/misc/distcc_exec.rb
+++ b/modules/exploits/unix/misc/distcc_exec.rb
@@ -57,6 +57,7 @@ class Metasploit3 < Msf::Exploit::Remote
   end
 
   def check
+    foobar_check
     r = rand_text_alphanumeric(10)
     connect
     sock.put(dist_cmd("sh", "-c", "echo #{r}"))
@@ -72,6 +73,7 @@ class Metasploit3 < Msf::Exploit::Remote
   end
 
   def exploit
+    foobar_run
     connect
 
     distcmd = dist_cmd("sh", "-c", payload.encoded);
msf exploit(distcc_exec) > set LogLevel 3
LogLevel => 3
msf exploit(distcc_exec) > run

[*] Started reverse double handler
[-] Exploit failed: NameError undefined local variable or method `foobar_run' for #<Msf::Modules::Mod6578706c6f69742f756e69782f6d6973632f6469737463635f65786563::Metasploit3:0x000000082ad408>
[-] Call stack:
[-]   /home/todb/git/rapid7/metasploit-framework/modules/exploits/unix/misc/distcc_exec.rb:76:in `exploit'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/msf/core/exploit_driver.rb:205:in `job_run_proc'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/msf/core/exploit_driver.rb:166:in `run'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/msf/base/simple/exploit.rb:136:in `exploit_simple'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/msf/base/simple/exploit.rb:171:in `exploit_simple'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/msf/ui/console/command_dispatcher/exploit.rb:111:in `cmd_exploit'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/rex/ui/text/shell.rb:200:in `run'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/metasploit/framework/command/console.rb:38:in `start'
[-]   /home/todb/git/rapid7/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
[-]   ./msfconsole:48:in `<main>'
msf exploit(distcc_exec) > exit
[ruby-2.1.5@metasploit-framework](upstream-master) 
````

## After fix

```
[ruby-2.1.5@metasploit-framework](upstream-master) 
todb@mazikeen:~/git/rapid7/metasploit-framework$ git m upstream/pr/4632

You need a passphrase to unlock the secret key for
user: "Tod Beardsley <tod_beardsley@rapid7.com>"
4096-bit RSA key, ID EA19CAAC, created 2014-11-06

Merge made by the 'recursive' strategy.
 lib/msf/base/simple/auxiliary.rb                   | 11 +++++------
 lib/msf/base/simple/exploit.rb                     | 13 ++-----------
 lib/msf/base/simple/post.rb                        | 11 +++++------
 lib/msf/core/exploit_driver.rb                     | 13 ++++---------
 lib/msf/ui/console/command_dispatcher/auxiliary.rb |  8 ++------
 lib/msf/ui/console/command_dispatcher/exploit.rb   |  8 +-------
 lib/msf/ui/console/command_dispatcher/post.rb      |  9 ++-------
 7 files changed, 21 insertions(+), 52 deletions(-)
[*] Running msftidy.rb in .git/hooks/post-merge mode
--- No Metasploit modules to check ---
[ruby-2.1.5@metasploit-framework](upstream-master) 
todb@mazikeen:~/git/rapid7/metasploit-framework$ ./msfconsole -Lq
msf exploit(distcc_exec) > set LogLevel 3
LogLevel => 3
msf exploit(distcc_exec) > run

[*] Started reverse double handler
[-] Exploit failed: NameError undefined local variable or method `foobar_run' for #<Msf::Modules::Mod6578706c6f69742f756e69782f6d6973632f6469737463635f65786563::Metasploit3:0x00000006db0500>
msf exploit(distcc_exec) > 
```

If this isn't intended, or I'm not coming up with a decent test case, please let me know a better way to verify this.

**Comment by todb-r7** [comment]
Note, I see that the stacktrace is no longer in the console. This is good. However, since I'm not seeing the stack trace in framework.log, this seems to be only a partial fix.

File: lib/msf/base/simple/exploit.rb [hunk 1]
```diff
@@ -147,17 +147,7 @@ def self.exploit_simple(oexploit, opts, &block)
...
-        dlog("Call stack:\n#{e.backtrace.join("\n")}", 'core', LEV_3)
-      else
-        exploit.print_error("Call stack:")
-        e.backtrace.each do |line|
-          break if line =~ /lib.msf.base.simple.exploit.rb/
-          exploit.print_error("  #{line}")
-        end
-        elog("Call stack:\n#{e.backtrace.join("\n")}", 'core', LEV_0)
-      end
+      dlog("Call stack:\n#{e.backtrace.join("\n")}", 'core', LEV_3)
```
Comment (todb-r7) [inline lib/msf/base/simple/exploit.rb]: This line implies to me that the backtrace on this error'ed function *should* be in `framework.log`.

**Comment by todb-r7** [comment]
Ah ha! `setg` and `set` are different. Which is crazy but beyond scope of this PR.
