### PR TITLE
Fix msfdb init command failure in systems that use the 'pg_ctl.rb' msfdb_helper

### LINKED ISSUE #16086: msfdb init command fails to start database service in linux
The `./msfdb init` command fails to start the database service in a Linux system. It fails with an error.

## Steps to reproduce

1. git clone the msf repository in a linux system and setup the environment (bundle install)
2. `cd metasploit-framework`, change into installed directory
3. run `./msfdb init`
4. Type `no` for `init webservices`, as its not necessary
5. Check how the script fails with an error message.  
  
Although I am running the MSF through the github repo version, I'm sure this issue would still arise if we install MSF from the installers available online (https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers)

## Expected behavior

The script should continue to initialize the database service.  

## Current behavior

The script fails with an error.  
  
Error Log:  
```
./msfdb init
[?] Would you like to init the webservice? (Not Required) [no]: no
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
Starting database at /home/beleswar/.msf4/db...failed
Creating database users
/home/beleswar/.local/share/gem/ruby/3.0.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize': could not connect to server: Connection refused (PG::ConnectionBad)
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5433?
```

### Metasploit version

Framework: 6.1.24-dev-8e6fa39a93
Console  : 6.1.24-dev-8e6fa39a93

### PR DESCRIPTION
**Pull request by 3V3RYONE**
This PR fixes #16086   
  
## Cause of bug  
The cause of this issue is because of the default path of `unix_socket_directories` in the `postgresql.conf` file. The default path is set to `/run/postgresql`, and this is where the pg tries to create the socket file for starting the server. But the current user who runs `./msfdb init` (and not `sudo ./msfdb init`) does not have the privileges to access the `/run` directory. Hence, the socket file is not created and the server start up fails.  
  
## Approach  
There were two approaches to solve this issue. One was to run the commands as the super user, by changing the internal commands from `pg_ctl -D -l start` to `sudo pg_ctl -D -l start`. This way, the super user could access the `/run/postgresql` directory and the socket could be created.  
  
However, the other and the better approach was to change the location of `unix_socket_directories` from `/run/postgresql` to `/tmp`. This way, the normal user can create the socket files and make the server started. So, I created an additional parameter `@options[:unix_socket_directories]` in the msfdb file which would contain the new socket path along with other db confs. and appended this updated directory path (along with the updated port 5433) in the `postgresql.conf` file. The `db_interface.rb` file was also updated, where I added the `-h '/tmp'` argument in the `psql` commands to specify it the updated socket directory.  
  
This worked pretty well in linux but failed in windows. This was because there is no `/tmp` location in windows. So, to solve this, I first checked in the `postgresql.conf` file, that whether the default location is set to `/run/postgresql` or `''` (for windows), using a regex. Only in the case of a regex match, the `pg_ctl.rb` file appends both updated path as well as updated port to the `postgresql.conf` file, else it only appends the updated port. This seems to work well in both systems now!  
  
## Before  
```
./msfdb init
[?] Would you like to init the webservice? (Not Required) [no]: no
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
Starting database at /home/beleswar/.msf4/db...failed
Creating database users
/home/beleswar/.local/share/gem/ruby/3.0.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize': could not connect to server: Connection refused (PG::ConnectionBad)
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5433?  
```  
```
./msfdb init
[?] Would you like to init the webservice? (Not Required) [no]: no
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
Starting database at /home/beleswar/.msf4/db...success
Creating database users
/home/beleswar/.local/share/gem/ruby/3.0.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize': FATAL:  role "msf" does not exist (PG::ConnectionBad)  
```  
  
## After  
```  
[beleswar@Som metasploit-framework]$ ./msfdb init
[?] Would you like to init the webservice? (Not Required) [no]: no
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
Starting database at /home/beleswar/.msf4/db...success
Creating database users
Writing client authentication configuration file /home/beleswar/.msf4/db/pg_hba.conf
Stopping database at /home/beleswar/.msf4/db
Starting database at /home/beleswar/.msf4/db...success
Creating initial database schema
```  

## Verification

- [ ] git clone the msf repository in a linux system and setup the environment (bundle install)
- [ ] cd metasploit-framework, change into installed directory
- [ ] Replace the original `msfdb`, `lib/msfdb_helpers/pg_ctl.rb`, `lib/msfdb_helpers/db_interface.rb` files with the files in this PR.
- [ ] run ./msfdb init
- [ ] Type no for init webservices, as its not necessary
- [ ] **Verify** that the script succeeds in initializing the database without any error.
- [ ] **Verify** that the script does not fail with an error message. 
  
## Note  
The above changes are also tested in windows environment. The server startup failure was already present in windows environment.  
Log:  
```  
C:\Users\IEUser>msfdb init
C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
[?] Would you like to init the webservice? (Not Required) [no]: no
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at C:/Users/IEUser/.msf4/db
Starting database at C:/Users/IEUser/.msf4/db...failed
Creating database users
Writing client authentication configuration file C:/Users/IEUser/.msf4/db/pg_hba.conf
Database is no longer running at C:/Users/IEUser/.msf4/db
Starting database at C:/Users/IEUser/.msf4/db...failed
Creating initial database schema  
```

### CODE REVIEW

**Comment by smcintyre-r7** [comment]
Instead of analyzing the configuration file to determine if the platform is Windows or Linux, can you just use [`Dir.tmpdir`](https://ruby-doc.org/stdlib-2.5.1/libdoc/tmpdir/rdoc/Dir.html#method-c-tmpdir) and always pass it as the -h option? That would dramatically simplify this code because you would just always use the temporary directory that Ruby provides you. You wouldn't need to check the existing config file contents, you wouldn't need any kind of conditional statement and you wouldn't need a new config option that may or may not be used.

I'm looking at PostgreSQL on Windows right now and it looks like `psql.exe` takes the `-h` argument like its Linux counter part does.

**Comment by 3V3RYONE** [comment]
Okay! Thats a really good idea. I'll work on it and make the commit!  
Thanks :D

**Comment by 3V3RYONE** [comment]
This idea really simplified the code, and works well in both the systems! Thanks! :D

**Comment by 3V3RYONE** [comment]
Any updates on this @smcintyre-r7 ?

**Comment by jmartin-r7** [comment]
A note for anyone testing this, change need to be tested on macOS for x64 as `pkg` builds are part of the list of nightly builds.

**Comment by smcintyre-r7** [comment]
I wasn't able to reproduce the original issue. From what you reported it sounds like it should be as simple as using a fresh install on Linux and running `msfdb init` as a non-root user. When I tried that from within an Ubuntu docker container, everything worked as intended.

Can you provide some additional steps to reproduce the issue that this is intended to fix to demonstrate that the changes do so?

**Comment by 3V3RYONE** [comment]
Did you use the nightly-installers to install MSF or did you git clone the repo?  
May you once try to git clone the repo and then run `./msfdb init` if that works to reproduce the issue.

**Comment by 3V3RYONE** [comment]
Hello @smcintyre-r7 , I'm running Arch linux as my main machine and I am still able to reproduce this issue. For re-checking, I opened up my old laptop running Arch Linux as well, and this issue still persists there. (I'm using the latest version of MSF & linux both)  
  
Console output in old computer:  
```
[beleswar@Som metasploit-framework]$ ./msfdb init
[?] Would you like to init the webservice? (Not Required) [no]: no
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
Starting database at /home/beleswar/.msf4/db...failed
Creating database users
/usr/lib/ruby/gems/3.0.0/gems/pg-1.3.0/lib/pg/connection.rb:636:in `async_connect_or_reset': could not connect to server: Connection refused (PG::ConnectionBad)
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5433?
	from /usr/lib/ruby/gems/3.0.0/gems/pg-1.3.0/lib/pg/connection.rb:705:in `new'
	from /usr/lib/ruby/gems/3.0.0/gems/pg-1.3.0/lib/pg.rb:67:in `connect'
	from /home/beleswar/check/metasploit-framework/lib/msfdb_helpers/pg_ctl.rb:105:in `create_db_users'
	from /home/beleswar/check/metasploit-framework/lib/msfdb_helpers/pg_ctl.rb:25:in `init'
	from ./msfdb:201:in `init_db'
	from ./msfdb:938:in `invoke_
```
  
Do you think this is something local to my computer? I guess gwillcox-r7 was also able to produce this in ubuntu.. (https://metasploit.slack.com/archives/CCN8L75UN/p1642017073011000?thread_ts=1642010086.009600&cid=CCN8L75UN)

**Comment by lilithium-hydride** [comment]
For what it's worth, I'm on Arch as well (well, Artix, but close enough). I installed MSF for the first time on it and was able to reproduce the issue. Modifying the files in `/opt` in accordance with this PR fixed it. Could it be a version of some tangentially related package that's more recent on Arch?

**Comment by 3V3RYONE** [comment]
>Could it be a version of some tangentially related package that's more recent on Arch?

Well possible, I'll try to reproduce it on ubuntu today then..

**Comment by jmartin-r7** [comment]
Some added context `Arch` linux maintains its own packaging process. While Metasploit strives to maintain compatibility with a wide range to linux distos packaging can introduce variation in configuration requirements.

**Comment by smcintyre-r7** [comment]
@lilithium-hydride thanks alot for chiming in. It's always super helpful to confirm an issue can reproduced by multiple people and I'll definitely take a much closer look at Arch now.

**Comment by 3V3RYONE** [comment]
I am also checking to reproduce this issue in an ubuntu VM.. If it happens to be an issue just local to Arch I guess we wouldn't need to make specific adjustments 😁

**Comment by 3V3RYONE** [comment]
Hello, so I tried to replicate this issue in ubuntu, but failed to do so. I also just found why this issue isn't showing up in ubuntu.  
  
1. So in the `metasploit-framework/lib/msfdb_helpers` directory, we have two helpers, `pg_ctl.rb` and `pg_ctlcluster.rb`. As discussed above, the cause of this issue is the location of `unix_socket_directories` to be inaccessible by the non-root user. In `pg_ctlcluster.rb` file, we already have this change implemented. ([pg_ctlcluster.rb](https://github.com/rapid7/metasploit-framework/blob/master/lib/msfdb_helpers/pg_ctlcluster.rb#L21)). That is, the cluster is created with the **socket_directory** specified as **/tmp** directory (achieved by the **-s flag**, bolded below).   

  run_cmd("pg_createcluster --user=$(whoami) -l #{@db.shellescape}/log -d #{@db.shellescape} **-s /tmp** --encoding=UTF8 #{@pg_version} #{options[:msf_db_name].shellescape} -- --username=$(whoami) --auth-host=trust --auth-local=trust")

2. Whereas, in the `pg_ctl.rb` file, this change is not already implemented. ([pg_ctl.rb](https://github.com/rapid7/metasploit-framework/blob/master/lib/msfdb_helpers/pg_ctl.rb#L17)). That is, the default **socket_directory** is **not changed** here while initializing the db.  
  
run_cmd("initdb --auth-host=trust --auth-local=trust -E UTF8 #{@db.shellescape}")
  
3. So, **Ubuntu is using this `pg_ctlcluster.rb`** helper while running `./msfdb init` wherease **Arch is using the `pg_ctl.rb`** helper while running `./msfdb init`. This is why we don't get the issue in Ubuntu but we get it in Arch. 

The above point can be verified by running `./msfdb init` in the debug mode. For that, set the **debug** parameter to **true** in your `metasploit-framework/msfdb` file ([msfdb](https://github.com/rapid7/metasploit-framework/blob/master/msfdb#L62)) and then run `./msfdb init`.  

### Ubuntu Output in debug mode:  

<details>  
  
./msfdb init
[?] Would you like to init the webservice? (Not Required) [no]: 
Clearing http web data service credentials in msfconsole
run_cmd: cmd=msfconsole -qx 'db_disconnect --clear; exit', input=, env={}
'msfconsole -qx 'db_disconnect --clear; exit'' returned 127
sh: 1: msfconsole: not found
run_cmd: cmd=msfconsole -qx 'db_disconnect --clear; exit', input=, env={"PATH"=>".:/var/lib/gems/2.7.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"}
'msfconsole -qx 'db_disconnect --clear; exit'' returned 0
No default data service was configured.

Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
run_cmd: cmd=pg_createcluster --user=$(whoami) -l /home/beleswar/.msf4/db/log -d /home/beleswar/.msf4/db -s /tmp --encoding=UTF8 12 msf -- --username=$(whoami) --auth-host=trust --auth-local=trust, input=, env={}
'pg_createcluster --user=$(whoami) -l /home/beleswar/.msf4/db/log -d /home/beleswar/.msf4/db -s /tmp --encoding=UTF8 12 msf -- --username=$(whoami) --auth-host=trust --auth-local=trust' returned 0
Creating new PostgreSQL cluster 12/msf ...
/usr/lib/postgresql/12/bin/initdb -D /home/beleswar/.msf4/db --encoding UTF8 --username=beleswar --auth-host=trust --auth-local=trust
The files belonging to this database system will be owned by user "beleswar".
This user must also own the server process.

The database cluster will be initialized with locale "en_IN".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /home/beleswar/.msf4/db ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Asia/Kolkata
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctlcluster 12 msf start

Warning: The parent /var/run/postgresql of the selected
stats_temp_directory is not writable for the cluster owner. Not adding this
setting in postgresql.conf.
Ver Cluster Port Status Owner    Data directory          Log file
12  msf     5433 down   beleswar /home/beleswar/.msf4/db /home/beleswar/.msf4/db/log
Starting database at /home/beleswar/.msf4/db...run_cmd: cmd=pg_ctlcluster 12 msf start -- -o "-p 5433" -D /home/beleswar/.msf4/db -l /home/beleswar/.msf4/db/log, input=, env={}
'pg_ctlcluster 12 msf start -- -o "-p 5433" -D /home/beleswar/.msf4/db -l /home/beleswar/.msf4/db/log' returned 0

success

</details>  
  

### Arch Output in debug mode:

<details>  
  
./msfdb init
[?] Would you like to init the webservice? (Not Required) [no]: no
Clearing http web data service credentials in msfconsole
run_cmd: cmd=./msfconsole -qx 'db_disconnect --clear; exit', input=, env={}
'./msfconsole -qx 'db_disconnect --clear; exit'' returned 0
No default data service was configured.

Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
run_cmd: cmd=initdb --auth-host=trust --auth-local=trust -E UTF8 /home/beleswar/.msf4/db, input=, env={}
'initdb --auth-host=trust --auth-local=trust -E UTF8 /home/beleswar/.msf4/db' returned 0
The files belonging to this database system will be owned by user "beleswar".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /home/beleswar/.msf4/db ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Asia/Kolkata
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /home/beleswar/.msf4/db -l logfile start

run_cmd: cmd=pg_ctl -o "-p 5433" -D /home/beleswar/.msf4/db status, input=, env={}
'pg_ctl -o "-p 5433" -D /home/beleswar/.msf4/db status' returned 3
pg_ctl: no server running
Starting database at /home/beleswar/.msf4/db...run_cmd: cmd=pg_ctl -o "-p 5433" -D /home/beleswar/.msf4/db -l /home/beleswar/.msf4/db/log start, input=, env={}
'pg_ctl -o "-p 5433" -D /home/beleswar/.msf4/db -l /home/beleswar/.msf4/db/log start' returned 1
waiting for server to start.... stopped waiting
pg_ctl: could not start server
Examine the log output.
run_cmd: cmd=pg_ctl -o "-p 5433" -D /home/beleswar/.msf4/db status, input=, env={}
'pg_ctl -o "-p 5433" -D /home/beleswar/.msf4/db status' returned 3
pg_ctl: no server running
failed
  
</details>  
  

**Notice this block in the Ubuntu output,**  
```
Warning: The parent /var/run/postgresql of the selected
stats_temp_directory is not writable for the cluster owner. Not adding this
setting in postgresql.conf.
```
and the **cmd = pg_createcluster** & **-s /tmp** flag here
```
Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
run_cmd: cmd=pg_createcluster --user=$(whoami) -l /home/beleswar/.msf4/db/log -d /home/beleswar/.msf4/db -s /tmp --encoding=UTF8 12 msf -- --username=$(whoami) --auth-host=trust --auth-local=trust, input=, env={}
```

This verifies that Ubuntu uses the **pg_ctlcluster.rb** file which creates the socket at **/tmp** instead of the default location.  
  
**Whereas in Arch, notice this block, cmd = initdb**  
```
Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
run_cmd: cmd=initdb --auth-host=trust --auth-local=trust -E UTF8 /home/beleswar/.msf4/db, input=, env={}
```

This verifies that Arch uses the **pg_ctl.rb** helper which **does not** change the default socket location, hence the error.  
  
Finally, As these changes are done in **pg_ctlcluster.rb** already, shouldn't we make them implemented in **pg_ctl.rb** as well (this PR) ? That would ensure that this issue isn't found again in any of the systems as we would have these 2 correct helpers only!

**Comment by 3V3RYONE** [comment]
As a short summary of the above message, the logs can be examined for clear insight.  
  
**Ubuntu's postgresql log (`/home/user/.msf4/db/log`) :**  
  
```
cat log
2022-02-03 12:31:35.986 IST [28085] LOG:  starting PostgreSQL 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
2022-02-03 12:31:35.987 IST [28085] LOG:  listening on IPv4 address "127.0.0.1", port 5433
2022-02-03 12:31:36.531 IST [28085] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5433"
2022-02-03 12:31:37.379 IST [28086] LOG:  database system was shut down at 2022-02-03 12:30:27 IST
2022-02-03 12:31:37.651 IST [28085] LOG:  database system is ready to accept connections
2022-02-03 12:32:29.569 IST [28085] LOG:  received SIGHUP, reloading configuration files
```
  
**Arch's postgresql log (`/home/user/.msf4/db/log`) :**  
  
```
2022-02-04 12:09:38.804 IST [3143] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.1.0, 64-bit
2022-02-04 12:09:38.806 IST [3143] LOG:  listening on IPv6 address "::1", port 5433
2022-02-04 12:09:38.806 IST [3143] LOG:  listening on IPv4 address "127.0.0.1", port 5433
2022-02-04 12:09:38.807 IST [3143] FATAL:  could not create lock file "/run/postgresql/.s.PGSQL.5433.lock": No such file or directory
2022-02-04 12:09:38.809 IST [3143] LOG:  database system is shut down
```   
  
So, Ubuntu's `./msfdb init` command is successful only because it's socket is created at **`/tmp`** (done by `pg_ctlcluster.rb` helper).  
  
But for systems that use the `pg_ctl.rb` helper, like Arch and Windows, the `./msfdb init` command fails, and these changes fixes it.

**Comment by jmartin-r7** [comment]
Another note about this I recently came across, some hardened environments mount `/tmp` with `noexec` and `nodev` flags which could cause explicit designation of `/tmp` to fail on more systems.

**Comment by smcintyre-r7** [comment]
Alright, I was able to confirm the original issue and that this patch fixes it. I'll approve it.

@jmartin-r7 are there any outstanding items that need to be tested now before this is merged?

`/tmp` shouldn't be explicitly designated any more, the temporary directory is selected by Ruby's `Dir.tmpdir`, though on the Arch system I tested with `Dir.tmpdir` is `/tmp`. If that's a scenario you're concerned about, how would you propose it be handled?

**Review by smcintyre-r7 — APPROVED** [review]

**Comment by jmartin-r7** [comment]
This change expects to offer a location on disk where postgres can create a special `dev` object.  I am noting that `Dir.tmpdir` will return `/tmp` without checking if that path supports such objects.  This suggest more validation of the filesystem is needed to determine a valid usable location before forcing that location in configs and expecting to be able to create socket devices.

For this PR more guarding is needed if the tooling is going to enforce using this location.

If there are other locations that use `/tmp` or `Dir.tmpdir` with such assumptions they all will need to be better guarded and can be handle in a separate PR.

[Here is an example](https://www.cyberciti.biz/faq/linux-add-nodev-nosuid-noexec-options-to-temporary-storage-partitions/) recommending hardening that would cause the issue I am concerned about.

**Comment by smcintyre-r7** [comment]
Okay so if we could determine that /tmp isn't going to work because the dev object can't be created there are we thinking the script should still fail, or that we should come up with some other location automatically through some means to place the dev object?

**Comment by 3V3RYONE** [comment]
Hello!.. Sorry for being so late on this, I just finished my college exams and back after a long.  
  
yes, so first it checks if `/tmp` is mounted with `noexec` flags. If it is not mounted, well and good, we change the default `unix_socket_directories` path to `/tmp` to complete the initialization. But if `/tmp` is mounted with `noexec`, there are two things that maybe done,
 
1. Do not change the default `unix_socket_directories = /run/postgresql` location, and put up a message asking the user to try `sudo ./msfdb init` if the initialization fails. That will let the initialization successful because `/run/postgresql` can now be accessed with sudo privileges.

2. Check any other locations which is not mounted with `noexec` flags, and replace `unix_socket_directories` with that location. This would not need sudo privileges to complete the initialization.

I have implemented point 1 in the latest commit. The 2nd one may seem more optimal. However it comes with it's one drawbacks :

The following locations are not mounted with `noexec`:
```
[beleswar@Som ~]$ mount | grep -v noexec
dev on /dev type devtmpfs (rw,nosuid,relatime,size=5061708k,nr_inodes=1265427,mode=755,inode64)
run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755,inode64)
/dev/nvme0n1p6 on / type ext4 (rw,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=11681)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=1048576,inode64)
/dev/nvme0n1p3 on /windows10 type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
/dev/sda1 on /data type ext4 (rw,relatime)
/dev/nvme0n1p7 on /home type ext4 (rw,relatime)
/dev/nvme0n1p1 on /boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1020568k,nr_inodes=255142,mode=700,uid=1000,gid=1000,inode64)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```
1. We have to ensure that the picked directory can again be accessed without sudo privileges. Else it indirectly leads to the issue that this PR aims to fix.
2. The `/tmp` directory holds the files temporarily only, and flushes all of them in a new session. But it wont happen in the other locations that we pick up. We kind of are saving the socket file in that location permanently. 

So I just wanted to ask your opinions. Which one should we implement? or any other suggestions?

**Comment by 3V3RYONE** [comment]
IMHO, most users would not specifically partition a `/tmp` disk while installing an OS. `/tmp` just comes under the root filesystem automatically and is accessible by all processes. And generally while installing any software, their executables are placed in the `/tmp` only (unless you explicitly mention another location). Even while running `bundle install` for MSF would require to place some executables in `/tmp`. 

So for users that specifically partition their `/tmp` directory and mount it with `noexec` flags,  isn't it kinda on them that they are deciding not to install/initialize any softwares?

**Comment by jmartin-r7** [comment]
I am not a fan of inspecting the `mount` command output as `Dir.tmpdir` is not guaranteed to be a mount point.

My thought here would be to test if we can create a device in `Dir.tmpdir`  then fallback and test to creation in `~/.msf4/db_socket` or similar path in `~/.msf4`.  If neither is valid then raising an error about not being able to create a socket seems a reasonable failure condition.

I believe `mkfifo` or possibly `mknod` should result in an exit code error if the filesystem is mounted `nodev`.  This needs to be testing though as I have not verified this. An important part of this is validation on some common distros and using a commonly available test.

**Comment by 3V3RYONE** [comment]
Sure, thats a good idea, I'll work on it

**Comment by meditant** [comment]
Hello,
Same problem if I run msfconsole the database is not created but if you run msfconsole, say NO to the creation of the database and after executing msfdb init it works, the database is created!

**Comment by 3V3RYONE** [comment]
> Hello, Same problem if I run msfconsole the database is not created but if you run msfconsole, say NO to the creation of the database and after executing msfdb init it works, the database is created!

Does running msfconsole ask for the database service? I haven't encountered it yet. Can you please share your msfconsole output or a snapshot showing the steps! Thanks :)

**Comment by 3V3RYONE** [comment]
Hey @jmartin-r7 , I tried to look on the commands you said like `mknod` or `mkfifo` or even `makedev`. But I couldn't find any special error code returned by them when the partition(`/tmp`) is mounted with `nodev` flags.  
  
Infact, the commands executed successfully to create a device in the `/tmp` directory, even when it's mounted with `nodev`, `noexec` flags. 

Snapshot of output in Arch VM:

output_mknod

Do you have any suggestions? or other specific commands?

**Comment by gwillcox-r7** [comment]
@jmartin-r7 Any update on this? This PR is currently blocked on your feedback.

**Comment by jmartin-r7** [comment]
I am looking for a good pattern for detection, as is the pattern here is unreliable. Per my previously stated feedback.

**Comment by smcintyre-r7** [comment]
Can we move this forward with the partial fix for the most common cases since this issue is still affecting people while we continue to investigate a solution for all of the edge cases?

**Comment by jmartin-r7** [comment]
The change here could impact working environments. Just adding the path to initial config startup is somewhat reasonable however the original issue is already an edge case for `Arch` which does not use our installers anyway.

One issue here is usage of the database helpers when not in a supported OS. Landing as is could expand the issue and introduce impact to various supported platforms.

Looking at possible testing patterns since this is performed only on db creation maybe the path forward is to create a test executable file and a test devices and interact with them as part for the decision processing for selecting location.
```
jmartin@ubuntu:~/loopfs/test$ ls -lah
total 12K
drwxr-xr-x 2 jmartin root    4.0K May 31 16:22 .
drwxr-xr-x 4 root    root    4.0K May 31 16:21 ..
-rwxrwxr-x 1 jmartin jmartin   22 May 31 16:22 test
jmartin@ubuntu:~/loopfs/test$ cat test
#!/bin/bash
echo exec
jmartin@ubuntu:~/loopfs/test$ ./test
-bash: ./test: Permission denied
jmartin@ubuntu:~/loopfs/test$ mount | grep loop
/dev/loop10 on /home/jmartin/loopfs type ext4 (rw,nodev,noexec,relatime)
```
This checks out for testing the `noexec` using a simple file write and attempt to execute.

I will see if there is more we can add to the `nodev` options since this needs to be able to create a socket device.

**Comment by 3V3RYONE** [comment]
Hey, thank you so much for the suggestion above. I was also looking for a good pattern to get this one landed. 

So, we can attempt to execute a write file for checking the `noexec` part. Now just looking for a similar approach for identifying `nodev` on the `Dir.tmpdir` partition. I'll work on the first part currently! Thanks :D

**Comment by 3V3RYONE** [comment]
Hello, I've added the commit to check if the `Dir.tmpdir` directory is mounted with NOEXEC flags, before creating the socket file in it. If `Dir.tmpdir` is mounted with NOEXEC, it tries to create the socket file in `~/.msf4/db`. If it fails too, the db initialization procedure fails.  
  
Testing result in Arch Linux when `Dir.tmpdir` is mounted with NOEXEC:  DB socket is created at `~/.msf4/db`. **Successful**.  
  
```
[beleswar@archvm metasploit-framework]$ ./msfdb init
[?] Would you like to init the webservice? (Not Required) [no]: 
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
Creating db socket file at /home/beleswar/.msf4/db
Starting database at /home/beleswar/.msf4/db...success
Creating database users
Writing client authentication configuration file /home/beleswar/.msf4/db/pg_hba.conf
Stopping database at /home/beleswar/.msf4/db
Starting database at /home/beleswar/.msf4/db...success
Creating initial database schema
Database initialization successful
```
  
Testing result in Arch Linux when `Dir.tmpdir` is not mounted with NOEXEC: DB socket is created at `/tmp`. **Successful**.
  
```
[beleswar@Som metasploit-framework]$ ./msfdb init
[?] Would you like to init the webservice? (Not Required) [no]: 
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
Creating db socket file at /tmp
Starting database at /home/beleswar/.msf4/db...success
Creating database users
Writing client authentication configuration file /home/beleswar/.msf4/db/pg_hba.conf
Stopping database at /home/beleswar/.msf4/db
Starting database at /home/beleswar/.msf4/db...success
Creating initial database schema
Database initialization successful
```  
  
Testing result in Ubuntu when `Dir.tmpdir` is not mounted with NOEXEC: DB socket is created at `/tmp` (uses pg_ctlcluster.rb helper). **Successful**.
  
```
beleswar@beleswar:~/metasploit-framework$ ./msfdb init
[?] Would you like to init the webservice? (Not Required) [no]: 
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at /home/beleswar/.msf4/db
Starting database at /home/beleswar/.msf4/db...success
Creating database users
Writing client authentication configuration file /home/beleswar/.msf4/.local/etc/postgresql/12/msf/pg_hba.conf
Creating initial database schema
Database initialization successful
```

**Review by jmartin-tech — COMMENTED** [review]
The added `exec` test is great, I added some suggestions on adjusting cleanup as well as encapsulate the functionality a bit.

File: lib/msfdb_helpers/pg_ctl.rb [hunk 1]
```diff
@@ -28,6 +41,23 @@ def init(msf_pass, msftest_pass)
...
+      File.chmod(0744, "#{path}/msfdb_testfile")
+      
+      if run_cmd("#{path}/msfdb_testfile")
+        File.open("#{@db}/postgresql.conf", 'a') do |f|
+          f.puts "unix_socket_directories = \'#{path}\'"
+        end
+        @socket_directory = path
+        puts "Creating db socket file at #{path}"
+      end
+    end
```
[the remark this answers is not in the document]
Comment (3V3RYONE) [reply lib/msfdb_helpers/pg_ctl.rb]: Thanks for the suggestions! Helped me make the code more normalized!  
I've added the commit and tested again on Arch (with NOEXEC and without NOEXEC)  and Ubuntu. It works fine!

**Review by jmartin-tech — APPROVED** [review]
Current state addresses most of my concerns.

File: lib/msfdb_helpers/pg_ctl.rb [hunk 2]
```diff
@@ -20,6 +21,17 @@ def init(msf_pass, msftest_pass)
...
 
+      # Try creating a test file at {Dir.tmpdir},
+      # Else fallback to creation at @{db}
+      # Else fail with error.
+      if test_executable_file("#{Dir.tmpdir}")
+        @socket_directory = Dir.tmpdir
+      elsif test_executable_file("#{@db}")
+        @socket_directory = @db
+      else
+        print_error("Attempt to create DB socket file at Temporary Directory and `~/.msf4/db` failed. Possibly because they are mounted with NOEXEC Flags. Database initialization failed.")
```
Comment (gwillcox-r7) [inline lib/msfdb_helpers/pg_ctl.rb:32]:
```suggestion
        print_error("Attempt to create DB socket file at Temporary Directory and `~/.msf4/db` failed. Possibly because they are mounted with NOEXEC flags. Database initialization failed.")
```

File: lib/msfdb_helpers/pg_ctl.rb [hunk 3]
```diff
@@ -28,6 +40,37 @@ def init(msf_pass, msftest_pass)
...
+        file_name = File.join(path, 'msfdb_testfile')
+        File.open(file_name, 'w') do |f|
+          f.puts "#!/bin/bash\necho exec"
+        end
+        File.chmod(0744, file_name)
+        
+        if run_cmd(file_name)
+          File.open("#{@db}/postgresql.conf", 'a') do |f|
+            f.puts "unix_socket_directories = \'#{path}\'"
+          end
```
Comment (gwillcox-r7) [inline lib/msfdb_helpers/pg_ctl.rb:56]: Will this append take preference over any previous entries or will the first instance take preference? Would we maybe want to read the whole file in here and do a regex instead to replace things?

File: lib/msfdb_helpers/pg_ctl.rb [hunk 4]
```diff
@@ -28,6 +40,37 @@ def init(msf_pass, msftest_pass)
...
+          puts "Creating db socket file at #{path}"
```
Comment (gwillcox-r7) [inline lib/msfdb_helpers/pg_ctl.rb:57]: Should this not be at the start of the function? Putting it at the end here seems odd given that you don't actually do anything after this is printed out, all the work here is done before this gets printed out.

**Comment by gwillcox-r7** [comment]
Before Patch:

image

**Comment by gwillcox-r7** [comment]
After patch:

image

File: lib/msfdb_helpers/pg_ctl.rb (hunk 3 above)
Comment (gwillcox-r7) [reply lib/msfdb_helpers/pg_ctl.rb:56]: Further testing showed that this was not a problem in my tests, so marking this as resolved.

File: lib/msfdb_helpers/pg_ctl.rb (hunk 4 above)
Comment (gwillcox-r7) [reply lib/msfdb_helpers/pg_ctl.rb:57]: Hmm so seems I misunderstood what was going on here, and this is actually fine. Marking as resolved.

File: lib/msfdb_helpers/pg_ctl.rb (hunk 2 above)
Comment (gwillcox-r7) [reply lib/msfdb_helpers/pg_ctl.rb]: Fixed with 19d044621c79be99f16427005f0eafac1337da10

**Comment by gwillcox-r7** [comment]
LGTM will land this as soon as tests pass.

**Comment by gwillcox-r7** [comment]
# Release Notes
A bug has been fixed in the pg_ctl.rb helper whereby it was possible that initializing and starting databases using `msfdb init` might fail due to the pg_ctl.rb helper not properly setting `unix_socket_directories` to a path that a non-root user can write to. This code has now been updated so that it will set the `unix_socket_directories` setting to a path that the current user can write to or will error out if it cannot find a writeable directory to use for the socket file.
