### PR TITLE
Exclude multi payloads from automatic PAYLOAD selection

### LINKED ISSUE #13752: Unable to exploit drupal_drupalgeddon2 using the container anymore
I have something strange that happened that I'm trying to figure out.  Back in May, I set up a drupalgeddon2 attack and everything worked just fine.  But tried again last week and can no longer execute the exploit.  I believe the issue is the metasploit container because I used another metasploit container in docker hub from another user and the exploit ran just fine.  Here is the scenerio I set up:

Created a brand new Amazon Linux 2 instance.  Security groups do allow the traffic.  

[root@ip-XXX.XXX.XXX.XXX ~]#  docker pull metasploitframework/metasploit-framework
Using default tag: latest
.....
.....
```
[root@ip-XXX.XXX.XXX.XXX ~]# docker run -it -p 4444-4450:4444-4450 metasploitframework/metasploit-framework

     ,           ,
    /             \
   ((__---,,,---__))
      (_) O O (_)_________
         \ _ /            |\
          o_o \   M S F   | \
               \   _____  |  *
                |||   WW|||
                |||     |||


       =[ metasploit v5.0.95-dev                          ]
+ -- --=[ 2036 exploits - 1102 auxiliary - 344 post       ]
+ -- --=[ 562 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 7 evasion                                       ]
msf5 > use exploit/unix/webapp/drupal_drupalgeddon2
msf5 exploit(unix/webapp/drupal_drupalgeddon2) > set RHOSTS XXX.XXX.XXX.XXX
RHOSTS => XXX.XXX.XXX.XXX
msf5 exploit(unix/webapp/drupal_drupalgeddon2) > set RPORT 8080
RPORT => 8080
msf5 exploit(unix/webapp/drupal_drupalgeddon2) > set LHOST XXX.XXX.XXX.XXX
LHOST => XXX.XXX.XXX.XXX
msf5 exploit(unix/webapp/drupal_drupalgeddon2) > set LPORT 4444
LPORT => 4444

msf5 exploit(unix/webapp/drupal_drupalgeddon2) > check
[+] XXX.XXX.XXX.XXX:8080 - The target is vulnerable.

But when I run it, I get:
msf5 exploit(unix/webapp/drupal_drupalgeddon2) > run

[-] Exploit failed: An exploitation error occurred.
[*] Exploit completed, but no session was created.
```
I tried turning on verbose and that didn't give me any more information.  I did the exact same thing on May 29th and no issues.   Exploit ran just fine.  Grabbed another docker hub image from another user with metasploit and tried that and it worked.  So seems like something isn't working now in the image on docker hub.

### PR DESCRIPTION
**Pull request by wvu**
`multi` payloads were being automatically selected in some cases. These payloads are not usable in a normal context. Modules should have platform-specific payloads selected for them.

The intended behavior is as follows:

```
msf5 > use exploit/multi/http/ibm_openadmin_tool_soap_welcomeserver_exec
[*] No payload configured, defaulting to php/meterpreter/reverse_tcp
msf5 exploit(multi/http/ibm_openadmin_tool_soap_welcomeserver_exec) > set payload
payload => php/meterpreter/reverse_tcp
msf5 exploit(multi/http/ibm_openadmin_tool_soap_welcomeserver_exec) >
```

```
msf5 exploit(multi/http/ibm_openadmin_tool_soap_welcomeserver_exec) > use exploit/unix/webapp/drupal_drupalgeddon2
[*] No payload configured, defaulting to php/meterpreter/reverse_tcp
msf5 exploit(unix/webapp/drupal_drupalgeddon2) > set payload
payload => php/meterpreter/reverse_tcp
msf5 exploit(unix/webapp/drupal_drupalgeddon2) >
```

```
msf5 exploit(unix/webapp/drupal_drupalgeddon2) > use exploit/linux/samba/is_known_pipename
[*] No payload configured, defaulting to cmd/unix/interact
msf5 exploit(linux/samba/is_known_pipename) > set payload
payload => cmd/unix/interact
msf5 exploit(linux/samba/is_known_pipename) >
```

```
msf5 exploit(linux/samba/is_known_pipename) > use exploit/windows/smb/ms17_010_eternalblue
[*] No payload configured, defaulting to windows/x64/meterpreter/reverse_tcp
msf5 exploit(windows/smb/ms17_010_eternalblue) > set payload
payload => windows/x64/meterpreter/reverse_tcp
msf5 exploit(windows/smb/ms17_010_eternalblue) >
```

`exploit/multi/handler` requires a special case, so we default it to a `generic` reverse shell handler:

```
msf5 exploit(windows/smb/ms17_010_eternalblue) > use exploit/multi/handler
[*] Using configured payload generic/shell_reverse_tcp
msf5 exploit(multi/handler) > set payload
payload => generic/shell_reverse_tcp
msf5 exploit(multi/handler) >
```

And this is how a module should respond if it has a saved `PAYLOAD` config:

```
msf5 > use exploit/multi/handler
[*] Using configured payload windows/x64/meterpreter_reverse_tcp
msf5 exploit(multi/handler) >
```

Fixes #13566 and resolves #13752 and #13754.

### CODE REVIEW

**Comment by busterb** [comment]
This makes a lot of sense, excluding things that are not real payloads from the list.

**Review by smcintyre-r7 — APPROVED** [review]

**Comment by adfoster-r7** [comment]
@wvu-r7 Happy to take off the draft marker? 👀

File: lib/msf/ui/console/command_dispatcher/exploit.rb [hunk 1]
```diff
@@ -290,17 +290,23 @@ def cmd_rexploit_help
...
-      shell_reverse_tcp
-      shell/reverse_tcp
-      generic/shell_reverse_tcp
-      generic/shell_bind_tcp
+    compatible_payloads = mod.compatible_payloads(
+      excluded_platforms: ['Multi'] # We don't want to select a multi payload
+    ).map(&:first)
+
+    # If there is only one compatible payload, return it immediately
+    return compatible_payloads.first if compatible_payloads.length == 1
```
Comment (adfoster-r7) [inline lib/msf/ui/console/command_dispatcher/exploit.rb:298]: Just a quick sanity question from me, does this need to execute the same code as the `preferred_payloads` loop does?

> mod.datastore['PAYLOAD'] = payload

Comment (wvu-r7) [reply lib/msf/ui/console/command_dispatcher/exploit.rb:298]: Good catch. I added this code at the last minute.

File: lib/msf/ui/console/command_dispatcher/modules.rb [hunk 2]
```diff
@@ -769,13 +769,11 @@ def cmd_use(*args)
             end
 
             # Choose a default payload when the module is used, not run
-            if mod.datastore['PAYLOAD'].nil? && dispatcher.respond_to?(:choose_payload)
+            if mod.datastore['PAYLOAD']
+              print_status("Using configured payload #{mod.datastore['PAYLOAD']}")
```
Comment (adfoster-r7) [inline lib/msf/ui/console/command_dispatcher/modules.rb:773]: :+1:

**Comment by adfoster-r7** [comment]
## Release Notes

Excludes multi payloads from automatic PAYLOAD selection
