### PR TITLE
Fix broken zabbix_login scanner regex for new versions

### LINKED ISSUE #17218: zabbix_login scanner does not work on latest zabbix appliance version 6.2.4
## Summary
Outdated regex.

## Steps to reproduce

1. Download the latest Zabbix appliance from: https://cdn.zabbix.com/zabbix/appliances/stable/6.2/6.2.4/zabbix_appliance-6.2.4-netinstall.iso 
1. Spin up the .iso. - In VMWare Fusion select `Other Linux 5.x kernel 64-bit` as the OS give the machine 4 cores and 8 GB ram (likely a bit overkill but before the VM was crashing for me durning boot prior to these changes)
1. Start metasploit and run 'use auxiliary/scanner/http/zabbix_login'
1. `set rhosts <IP-ADDRESS>`
1. `set targeturi /` (default targeturi is not longer /zabbix)
1. Run the module and notice the following output:
```
msf6 auxiliary(scanner/http/zabbix_login) > run

[-] 172.16.199.137:80 - Unexpected HTTP body (is this really Zabbix?)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

## Expected Output
```
msf6 auxiliary(scanner/http/zabbix_login) > run

[*] 172.16.199.137:80 - Found Zabbix version 6.2
[*] 172.16.199.137:80 - This Zabbix instance has disabled Guest mode
[+] 172.16.199.137:80 - Success: 'Admin:zabbix'
[!] No active DB -- Credential data will not be saved!
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

## Issue
The regex found here does not match what is on the page in the latest version:
https://github.com/rapid7/metasploit-framework/blob/708de57499cfd953e4e0cabc8301d4708f520f57/lib/metasploit/framework/login_scanner/zabbix.rb#L52

What's on the page in version 6.2.4: 
`<a target="_blank" rel="noopener noreferrer" class="grey link-alt" href="https://www.zabbix.com/documentation/6.2/">Help</a>`

Note the `rel` attribute has been added to the Help hyperlink tag: ` rel="noopener noreferrer"` 

## Fix 
Change the regex:

1. More restrictive:
`if res.body.to_s !~ /<a target="_blank" (?:rel="noopener noreferrer" )*class="grey link-alt" href="http[sS]{0,1}:\/\/www\.zabbix\.com\/documentation\/(\d+\.\d+)\/">Help<\/a>/m`

2. Less restrictive: 
`if res.body.to_s !~ /href="http[sS]{0,1}:\/\/www\.zabbix\.com\/documentation\/(\d+\.\d+)\/">Help<\/a>/m`

Both work, I'd say going less restrictive might be best 🤷 . It's likely to not introduce any F+ given how specific to zabbix the regex is already and would prevent the possibility of introducing more F- if more attributes are added or changed in the line in the future.

### PR DESCRIPTION
**Pull request by jheysel-r7**
Fixes: [#issue 17218](https://github.com/rapid7/metasploit-framework/issues/17218)

As noted in the issue the we could also add to the regex to accommodate the additional attribute in newer versions, whatever the team thinks is best

### CODE REVIEW

File: lib/metasploit/framework/login_scanner/zabbix.rb [hunk 1]
```diff
@@ -49,7 +49,7 @@ def check_setup
             end
 
             if res.body.to_s !~ /Zabbix ([^\s]+) Copyright .* by Zabbix/m # Regex check for older versions of Zabbix prior to version 3.
-              if res.body.to_s !~ /<a target="_blank" class="grey link-alt" href="http[sS]{0,1}:\/\/www\.zabbix\.com\/documentation\/(\d+\.\d+)\/">Help<\/a>/m
+              if res.body.to_s !~ /href="http[sS]{0,1}:\/\/www\.zabbix\.com\/documentation\/(\d+\.\d+)\/">Help<\/a>/m
```
Comment (adfoster-r7) [inline lib/metasploit/framework/login_scanner/zabbix.rb:52]: To a future traveller, extra details are on the raised issue - https://github.com/rapid7/metasploit-framework/issues/17218

> What's on the page in version 6.2.4:
> <a target="_blank" rel="noopener noreferrer" class="grey link-alt" href="https://www.zabbix.com/documentation/6.2/">Help</a>
>
> Note the rel attribute has been added to the Help hyperlink tag: rel="noopener noreferrer"

**Comment by adfoster-r7** [comment]
## Release Notes

Update Zabbix login_scanner to work with version 6.2.4
