### PR TITLE
Sum the results of the module loaders

### LINKED ISSUE #8229: loadpath doesn't report loading modules between 4.14.7 and 4.14.8
## Steps to reproduce

How'd you do it?

1. Create modules directory that mirrors that of Metasploit (exploits, auxiliary, etc). Put some modules in it.
2. ```loadpath /path/to/your/modules``` should attempt to load the modules.

## Expected behavior
The number of modules and their types should be printed.

## Current behavior

Metasploit reports 0 modules loaded from the path. It seems to still load the modules, just not print the correct report in the end.

You can see the behavior change below.

```
Brandons-MBP:metasploit-framework bperry$ git checkout 4.14.7
Note: checking out '4.14.7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 05201b9578... land #8177 tomcat_gather docs fix
Brandons-MBP:metasploit-framework bperry$ ./msfconsole
                                                  

  Metasploit Park, System Security Interface
  Version 4.0.5, Alpha E
  Ready...
  > access security
  access: PERMISSION DENIED.
  > access security grid
  access: PERMISSION DENIED.
  > access main security grid
  access: PERMISSION DENIED....and...
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!


       =[ metasploit v4.14.7-dev-05201b9578               ]
+ -- --=[ 1637 exploits - 955 auxiliary - 287 post        ]
+ -- --=[ 472 payloads - 40 encoders - 9 nops             ]
+ -- --=[ Free Metasploit Pro trial: http://r-7.co/trymsp ]

msf > loadpath /Users/bperry/Projects/volatileminds_modules/modules/
Loaded 60 modules:
    52 auxiliarys
    8 exploits
msf > exit
Brandons-MBP:metasploit-framework bperry$ git checkout 4.14.8
Previous HEAD position was 05201b9578... land #8177 tomcat_gather docs fix
HEAD is now at 68347ae06e... Land #8188, Update client to use TLS1.2
Brandons-MBP:metasploit-framework bperry$ ./msfconsole
                                                  

     .~+P``````-o+:.                                      -o+:.
.+oooyysyyssyyssyddh++os-`````                        ```````````````          `
+++++++++++++++++++++++sydhyoyso/:.````...`...-///::+ohhyosyyosyy/+om++:ooo///o
++++///////~~~~///////++++++++++++++++ooyysoyysosso+++++++++++++++++++///oossosy
--.`                 .-.-...-////+++++++++++++++////////~~//////++++++++++++///
                                `...............`              `...-/////...`


                                  .::::::::::-.                     .::::::-
                                .hmMMMMMMMMMMNddds\...//M\\.../hddddmMMMMMMNo
                                 :Nm-/NMMMMMMMMMMMMM$$NMMMMm&&MMMMMMMMMMMMMMy
                                 .sm/`-yMMMMMMMMMMMM$$MMMMMN&&MMMMMMMMMMMMMh`
                                  -Nd`  :MMMMMMMMMMM$$MMMMMN&&MMMMMMMMMMMMh`
                                   -Nh` .yMMMMMMMMMM$$MMMMMN&&MMMMMMMMMMMm/
    `oo/``-hd:  ``                 .sNd  :MMMMMMMMMM$$MMMMMN&&MMMMMMMMMMm/
      .yNmMMh//+syysso-``````       -mh` :MMMMMMMMMM$$MMMMMN&&MMMMMMMMMMd
    .shMMMMN//dmNMMMMMMMMMMMMs`     `:```-o++++oooo+:/ooooo+:+o+++oooo++/
    `///omh//dMMMMMMMMMMMMMMMN/:::::/+ooso--/ydh//+s+/ossssso:--syN///os:
          /MMMMMMMMMMMMMMMMMMd.     `/++-.-yy/...osydh/-+oo:-`o//...oyodh+
          -hMMmssddd+:dMMmNMMh.     `.-=mmk.//^^^\\.^^`:++:^^o://^^^\\`::
          .sMMmo.    -dMd--:mN/`           ||--X--||          ||--X--||
........../yddy/:...+hmo-...hdd:............\\=v=//............\\=v=//.........
================================================================================
=====================+--------------------------------+=========================
=====================| Session one died of dysentery. |=========================
=====================+--------------------------------+=========================
================================================================================

                     Press ENTER to size up the situation

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Date: April 25, 1848 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%% Weather: It's always cool in the lab %%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%% Health: Overweight %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% Caffeine: 12975 mg %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%% Hacked: All the things %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

                        Press SPACE BAR to continue



       =[ metasploit v4.14.8-dev-68347ae06e               ]
+ -- --=[ 1639 exploits - 959 auxiliary - 287 post        ]
+ -- --=[ 472 payloads - 40 encoders - 9 nops             ]
+ -- --=[ Free Metasploit Pro trial: http://r-7.co/trymsp ]

msf > loadpath /Users/bperry/Projects/volatileminds_modules/modules/
Loaded 0 modules:
msf > exit
```

### Metasploit version

This stopped working for me in 4.14.8. Currently behaves this way on master. It works in 4.14.7

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

### OS

OS X

### PR DESCRIPTION
**Pull request by acammack-r7**
Fixes #8229

Verification
========

- [x] Follow the instructions in #8229 
- [x] The correct module count should be displayed
- [x] Add a non-Ruby module and repeat
- [x] The sum of Ruby and non-Ruby modules should be displayed

### CODE REVIEW

File: lib/msf/core/module_manager/loading.rb [hunk 1]
```diff
@@ -116,7 +116,9 @@ def load_modules(path, options={})
 
     loaders.each do |loader|
       if loader.loadable?(path)
-        count_by_type = loader.load_modules(path, options)
+        count_by_type.merge!(loader.load_modules(path, options)) do |key, old, new|
+          old + new
```
Comment (FireFart) [inline lib/msf/core/module_manager/loading.rb]: is `new` a reserved keyword which can cause problems?

Comment (acammack-r7) [inline lib/msf/core/module_manager/loading.rb]: No. Github's highlighter is overzealous in making `Klass.new` look special and highlights this case. If we were to invoke `new` here, we would need to to `self.class.new`. Though I can change it if you think it will cause confusion.

Comment (FireFart) [inline lib/msf/core/module_manager/loading.rb]: @acammack-r7 no prob just wanted to make sure this does not break anything inside metasploit

**Comment by busterb** [comment]
## Release Notes

This fixes an issue with underreporting the number of modules loaded when using the 'loadpath' command. Modules still loaded as expected.
