### PR TITLE
DNS Changes

### LINKED ISSUE #18794: auxiliary/gather/enum_dns problem
## Steps to reproduce

How'd you do it?

1. msfconsole
2. use auxiliary/gather/enum_dns
3. set DOMAIN google.com
4. run

I'm running on a chromebook Linux environment.  I also tried `set DnsClientResolvconf /etc/resolv.conf` but this didn't seem to have any effect.  DNS outside of metasploit works fine, e.g., using the `dig` command.

## Expected behavior

Provide information about google.com's dns names.

## Current behavior

```
msf6 auxiliary(gather/enum_dns) > run

[-] Auxiliary failed: NoResponseError NoResponseError
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/resolver.rb:180:in `send'
[-]   /opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/resolver.rb:399:in `query'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/exploit/remote/dns/client.rb:61:in `query'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/exploit/remote/dns/enumeration.rb:118:in `dns_get_a'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/exploit/remote/dns/enumeration.rb:366:in `dns_wildcard_enabled?'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/gather/enum_dns.rb:71:in `run'
[*] Auxiliary module execution completed
```

### Metasploit version

msf6 auxiliary(gather/enum_dns) > version
Framework: 6.3.55-dev-
Console  : 6.3.55-dev-

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/core]
loglevel=3

[framework/ui/console]
ActiveModule=auxiliary/gather/enum_dns

[gather/enum_dns]
DOMAIN=google.com
WORKSPACE=
VERBOSE=false
RPORT=53
CPORT=
CHOST=
SSL=false
SSLServerNameIndication=
SSLVersion=Auto
SSLVerifyMode=PEER
SSLCipher=
Proxies=
ConnectTimeout=10
TCP::max_send_size=0
TCP::send_delay=0
NS=
SEARCHLIST=
THREADS=1
DnsClientDefaultNS=8.8.8.8 8.8.4.4
DnsClientReportARecords=true
DnsClientRVLExistingOnly=true
DnsClientResolvconf=/dev/null
DnsNote=true
ENUM_AXFR=true
ENUM_BRT=false
ENUM_A=true
ENUM_CNAME=true
ENUM_MX=true
ENUM_NS=true
ENUM_SOA=true
ENUM_TXT=true
ENUM_RVL=false
ENUM_TLD=false
ENUM_SRV=true
STOP_WLDCRD=false
IPRANGE=
WORDLIST=/opt/metasploit-framework/embedded/framework/data/wordlists/namelist.txt
TIMEOUT=8
RETRY=2
RETRY_INTERVAL=2
TCP_DNS=false
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: Connected to msf. Connection type: postgresql.
```

| ID | Hosts | Vulnerabilities | Notes | Services |
|-:|-:|-:|-:|-:|
| 1 **(Current)** | 31 | 3 | 34 | 114 |
| 2 | 0 | 0 | 0 | 0 |
| **Total (2)** | **31** | **3** | **34** | **114** |

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
935    set loglevel 3
936    use auxiliary/gather/enum_dns
937    set DOMAIN google.com
938    run
939    debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[02/06/2024 07:38:51] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[02/06/2024 07:38:51] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[02/06/2024 07:38:53] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[02/06/2024 07:38:54] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[02/06/2024 07:39:25] [e(0)] core: Auxiliary failed - NoResponseError NoResponseError
[02/06/2024 07:40:40] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[02/06/2024 07:40:40] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[02/06/2024 07:40:42] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[02/06/2024 07:40:43] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[02/06/2024 07:41:02] [e(0)] core: Auxiliary failed - NoResponseError NoResponseError
Call stack:
/opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/resolver.rb:180:in `send'
/opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/resolver.rb:399:in `query'
/opt/metasploit-framework/embedded/framework/lib/msf/core/exploit/remote/dns/client.rb:61:in `query'
/opt/metasploit-framework/embedded/framework/lib/msf/core/exploit/remote/dns/enumeration.rb:118:in `dns_get_a'
/opt/metasploit-framework/embedded/framework/lib/msf/core/exploit/remote/dns/enumeration.rb:366:in `dns_wildcard_enabled?'
/opt/metasploit-framework/embedded/framework/modules/auxiliary/gather/enum_dns.rb:71:in `run'
/opt/metasploit-framework/embedded/framework/lib/msf/base/simple/auxiliary.rb:178:in `job_run_proc'
/opt/metasploit-framework/embedded/framework/lib/msf/base/simple/auxiliary.rb:85:in `run_simple'
/opt/metasploit-framework/embedded/framework/lib/msf/base/simple/auxiliary.rb:96:in `run_simple'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:73:in `cmd_run'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:165:in `block in run'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:309:in `block in with_history_manager_context'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell/history_manager.rb:33:in `with_context'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:306:in `with_history_manager_context'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:133:in `run'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:54:in `start'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit-framework/bin/../embedded/framework/msfconsole:23:in `<main>'
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[02/05/2024 19:53:49] [i(0)] core:     >> Starting export of web sites
[02/05/2024 19:53:49] [i(0)] core:     >> Starting export of web pages
[02/05/2024 19:53:49] [i(0)] core:     >> Starting export of web forms
[02/05/2024 19:53:49] [i(0)] core:     >> Starting export of web vulns
[02/05/2024 19:53:49] [i(0)] core:     >> Starting export of module details
[02/05/2024 19:53:49] [i(0)] core:     >> Finished export of report
[02/05/2024 19:57:55] [e(0)] core: Auxiliary failed - NoResponseError NoResponseError
[02/06/2024 07:36:22] [w(0)] core: Session 1 has died
[02/06/2024 07:36:42] [e(0)] core: Auxiliary failed - NoResponseError NoResponseError
[02/06/2024 07:36:57] [d(0)] core: Reloading module auxiliary/gather/enum_dns...
[02/06/2024 07:36:57] [w(0)] core: The module gather/enum_dns is ambiguous with gather/enum_dns.
[02/06/2024 07:36:57] [d(0)] core: Refreshing gather/enum_dns of type: auxiliary
[02/06/2024 07:36:59] [e(0)] core: Auxiliary failed - NoResponseError NoResponseError
[02/06/2024 07:37:05] [d(0)] core: Reloading module auxiliary/gather/enum_dns...
[02/06/2024 07:37:05] [w(0)] core: The module gather/enum_dns is ambiguous with gather/enum_dns.
[02/06/2024 07:37:05] [d(0)] core: Refreshing gather/enum_dns of type: auxiliary
[02/06/2024 07:38:51] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[02/06/2024 07:38:51] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[02/06/2024 07:38:53] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[02/06/2024 07:38:54] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[02/06/2024 07:39:25] [e(0)] core: Auxiliary failed - NoResponseError NoResponseError
[02/06/2024 07:40:40] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[02/06/2024 07:40:40] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[02/06/2024 07:40:42] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[02/06/2024 07:40:43] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[02/06/2024 07:40:54] [i(2)] core: Reloading auxiliary module gather/enum_dns. Ambiguous module warnings are safe to ignore
[02/06/2024 07:41:02] [e(0)] core: Auxiliary failed - NoResponseError NoResponseError
Call stack:
/opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/resolver.rb:180:in `send'
/opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/resolver.rb:399:in `query'
/opt/metasploit-framework/embedded/framework/lib/msf/core/exploit/remote/dns/client.rb:61:in `query'
/opt/metasploit-framework/embedded/framework/lib/msf/core/exploit/remote/dns/enumeration.rb:118:in `dns_get_a'
/opt/metasploit-framework/embedded/framework/lib/msf/core/exploit/remote/dns/enumeration.rb:366:in `dns_wildcard_enabled?'
/opt/metasploit-framework/embedded/framework/modules/auxiliary/gather/enum_dns.rb:71:in `run'
/opt/metasploit-framework/embedded/framework/lib/msf/base/simple/auxiliary.rb:178:in `job_run_proc'
/opt/metasploit-framework/embedded/framework/lib/msf/base/simple/auxiliary.rb:85:in `run_simple'
/opt/metasploit-framework/embedded/framework/lib/msf/base/simple/auxiliary.rb:96:in `run_simple'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:73:in `cmd_run'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:165:in `block in run'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:309:in `block in with_history_manager_context'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell/history_manager.rb:33:in `with_context'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:306:in `with_history_manager_context'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:133:in `run'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:54:in `start'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit-framework/bin/../embedded/framework/msfconsole:23:in `<main>'
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.3.55-dev-
Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
OpenSSL: OpenSSL 1.1.1m  14 Dec 2021
Install Root: /opt/metasploit-framework/embedded/framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Omnibus Installer
```

</details>

### PR DESCRIPTION
**Pull request by zeroSteiner**
# Overview
This makes a number of changes to how Metasploit handles DNS requests internally. The intention is to keep the handling intuitive, functional and safe from leaks in scenarios where the operator is pivoting.

## Rule Consolidation
The original implementation utilized two arrays for matching names to resolvers. One array contained conditions defined as wildcard patterns to match names against while the other did not. Both arrays defined a single upstream DNS server to use for resolution. When resolution took place, a matcher would find all resolvers that matched a particular condition.

This pattern has been consolidated into a single array where *every* rule has a conditional wildcard pattern to match names against and the default wildcard pattern simply matches everything, effectively being a catch all. Entries, here after referred to as rules and represented in code in the `UpstreamRule` class associate a wildcard pattern for conditionally matching names to an array of resolvers. This means that for each name that is being resolved, it will match exactly 0 or 1 rules. The rule in turn defines the resolvers, in order that are to be used for resolving the query.

In the UI, rules are now managed by index instead of a unique numeric ID as they were previously. This pattern emulates how `iptables` handles it's rules in a particular chain (e.g. `INPUT`). Rules are indexed starting at 1, so to insert a rule into the first position of the chain, the syntax for the `add` command would use the `-i 1` argument.

## New Resolvers
The original implementation supported two types of name resolution. Names that were statically defined in the host operating systems `/etc/hosts` (or equivalent) file and traditional, network-attached DNS servers. In addition to these two techniques, operators can now also define system and black-hole resolvers.

Rules now contain an array of resolvers and the resolvers will be attempted in order until one is able to fulfill the request. In a standard configuration, users will most likely want to define the 'static' resolver as the first entry.

### system Resolver
The system resolver is capable of handling A/AAAA records to resolve queries for hostnames to IPv4 and IPv6 addresses. It does so by using the `getaddrinfo` API provided by Ruby. This will eventually invoke the operating systems standard API which may be hooked by external applications such as proxy chains.

Queries for PTR, NS, SRV and other unsupported records are unable to be handled by this resolver and the next resolver defined in the parent rule will be used. Supposedly, IP addresses can be mapped to hostnames using the `AI_CANONNAME` flag, however this behavior was not able to be replicated using the following Ruby snippet where the IP address has a PTR record.

```
::Socket.getaddrinfo(ip_address, 0, ::Socket::AF_UNSPEC, ::Socket::SOCK_STREAM, ::Socket::IPPROTO_TCP, ::Socket::AI_CANONNAME).first
```

### black-hole Resolver
This resolver will simply deny any queries and can be used as a stop gap if desired. Once invoked, subsequent resolvers that are defined in the parent rule will be ignored.

## Static Hostnames
Commands to add, delete and flush all statically defined hostname to IP address mappings were added. Furthermore, statically defined hostnames are now persisted to the Metasploit configuration file when the `save` command is used. These static hostnames are shared among all instances of 'static' resolvers.

## Inspection Updates
The `dns print` output was updated to display additional information, not just the configured rules. It will now also show:

* The default search domain
* The default search list
* The number of entries that are currently cached
* The currently configured static hostnames

Additionally, the new `dns resolve` command will show the rule that was used for DNS resolution which should help with debugging. It does not show the exact resolver that was able to fulfill the query at this time because that level of control is not currently implemented.

## New Reset Command
A new `dns reset-config` command has been added that will reset the currently running configuration to sane default values as specified by the host operating system. This only affects the running configuration; the user will need to use the `save` command to make the changes persistent.

This implementation also altered the default state of the DNS resolver that will be used when no configuration is present, e.g. because it is being used for the very first time. These changes include loading the name servers from the host operating systems configuration file, typically `/etc/resolv.conf` and converting those to upstream rules. This rule will have the 'static' resolver defined as the first entry to ensure that statically defined hostnames are used before the upstream nameserver is contacted to emulate normal behaviors.

## Configuration Changes
The DNS configuration that is persisted to Metasploit's INI file now uses multiple sections. There's a section for upstream rules and a dedicated section for static hostnames. Additionally, the top-level DNS configuration section now includes a version number that can be used to identify whether or not the configuration data is compatible and can be loaded. This means we can make changes in the future without worrying about restructuring the data.

> [!WARNING]  
> Each time changes from the pull request are pulled down, the tester should delete the DNS section from their configuration file. The version will be finalized once the PR is landed but between now and then, changes to the persisted format may occur that are not accompanied by a version bump.

## Additional Miscellaneous Changes

* Changed the time out for TCP and UDP to 5 seconds to make scanner modules more responsive
  * Updated the `DnsTimeout` class to add a `#to_i` method, making it compatible with rex-socket's `Timeout` parameter
* Updated `lib/msf/core/exploit/remote/dns/enumeration.rb` to consistently define the record type as a string value   (Fixes #18794)
* Added a search order for locating the `resolv.conf` file to load configuration information from (fixes an issue with Termux).

# Testing

- [ ] Enable the internal DNS system by running `features set dns_feature true`
- [ ] View the initial rules (they should be in a default state as defined by the host)
- [ ] Make sure that DNS works with the default rules (use the `dns resolve` command)
- [ ] Add new DNS rule(s)
- [ ] Delete existing DNS rule(s)
- [ ] Test DNS resolution changes based on the rule changes
- [ ] Run the `save` command, restart Metasploit and see that the configuration was persisted
- [ ] Manage statically defined hostnames
  - [ ] Create statically defined hostnames
  - [ ] See that they are used by the 'static' resolver (there must be a 'static' resolver for the name)
- [ ] See that the cache can be flushed
- [ ] See that the configuration can be reset

### CODE REVIEW

**Comment by sempervictus** [comment]
Wow. Thanks man, this is a fair chunk of work to integrate all that low-level stuff into the user's context. I'm one pass through but think i'll need to merge and step through this to sort it out fully :). Offhand, not 100% on the removal of the static entry capability in the Cache (even if creating proper primitives for other consumers), but otherwise it looks pretty rational.

File: lib/rex/proto/dns/resolver.rb [hunk 1]
```diff
@@ -386,28 +384,135 @@ def search(name, type = Dnsruby::Types::A, cls = Dnsruby::Classes::IN)
...
     def query(name, type = Dnsruby::Types::A, cls = Dnsruby::Classes::IN)
+      name, type, cls = preprocess_query_arguments(name, type, cls)
+      @logger.debug "Query(#{name},#{Dnsruby::Types.new(type)},#{Dnsruby::Classes.new(cls)})"
+      send(name,type,cls)
+    end
+
+    def self.default_config_file
+      %w[
+        /etc/resolv.conf
+        /data/data/com.termux/files/usr/etc/resolv.conf
```
Comment (adfoster-r7) [inline lib/rex/proto/dns/resolver.rb:395]: :+1:

File: lib/rex/proto/dns/resolver.rb [hunk 2]
```diff
@@ -386,28 +384,135 @@ def search(name, type = Dnsruby::Types::A, cls = Dnsruby::Classes::IN)
...
+        end
+      end
 
+      if type == Dnsruby::Types::AXFR
+        @logger.warn "AXFR query, switching to TCP" unless method == :send_tcp
+        method = :send_tcp
+      end
+
+      nameserver = [upstream_resolver.destination, upstream_resolver.socket_options]
+      ans = self.__send__(method, packet, packet_data, [nameserver])
```
Comment (adfoster-r7) [inline lib/rex/proto/dns/resolver.rb:444]: Not a blocker; Unfortunate that we need the dunder method here 😄

File: lib/rex/proto/dns/static_hostnames.rb [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+
+        ip_address = IPAddr.new(words.shift)
+        words.each do |hostname|
+          add(hostname, ip_address)
+        end
+      end
+    end
+
+    # Get an IP address of the specified type for the hostname. Only the first address is returned in cases where
+    # multiple addresses are defined.
```
Comment (adfoster-r7) [inline lib/rex/proto/dns/static_hostnames.rb:54]: Not a blocker; It'd be good to document any guarantees here, i.e. if it's an ordered result or non-deterministic

File: lib/rex/proto/dns/resolver.rb [hunk 4]
```diff
@@ -128,8 +141,6 @@ def nameservers_for_packet(_dns_message)
     # @return [Dnsruby::Message] DNS response
     #
     def send(argument, type = Dnsruby::Types::A, cls = Dnsruby::Classes::IN)
```
[the remark this answers is not in the document]
Comment (zeroSteiner) [reply lib/rex/proto/dns/resolver.rb:143]: Yeah, agreed that the name here is suboptimal but it's carried over from the Net::DNS::Resolver [here](https://github.com/rapid7/metasploit-framework/blob/a75013e51a4e72394a9b2ab4a8c00b5861a2cc52/lib/net/dns/resolver.rb#L929) on which the Rex resolver is built. We could change it I guess, maybe add an alias but I'd be worried that we'd start to deviate from the upstream library further which would complicate pulling in upstream changes.

File: lib/msf/ui/console/command_dispatcher/dns.rb [hunk 5]
```diff
@@ -237,52 +449,227 @@ def remove_dns(*args)
...
+        add_system_resolver = true
+      when '-y', '--yes'
+        should_confirm = false
+      end
+    end
+
+    if should_confirm
+      print("Are you sure you want to reset the DNS configuration? [y/N]: ")
+      response = gets.downcase.chomp
+      unless response.present? && 'yes'.start_with?(response)
```
[the remark this answers is not in the document]
Comment (zeroSteiner) [reply lib/msf/ui/console/command_dispatcher/dns.rb:535]: I looked for a while to find a method accessible from this location but was unsuccessful so I'll make the change to match anything starting with a case insensitive `y`.

**Comment by adfoster-r7** [comment]
Did a rough pass over things and all looks good, I'll land this now since as it fixes some bugs in master and the new core functionality is still behind a feature flag 👍

**Comment by adfoster-r7** [comment]
## Release Notes

Makes multiple improvements to the `dns` command - a new command which mimics the functionality of `/etc/resolv.conf` and `/etc/hosts`. This functionality is currently behind a feature flag which can be enabled with `features set dns_feature true` in msfconsole

**Comment by sempervictus** [comment]
Thanks I'll rebase off master - was going through it in my repo between tasks but overall agree: 2 passes in, LGTM as well. Thanks for getting this done, and if i find any weirdness we'll touch up in a follow-up PR
