### PR TITLE
Fix missing setup method in post modules

### LINKED ISSUE #8360: NoMethodError undefined method `[]' for nil:NilClass in post/windows/manage/migrate
Came across this by accident because I did not unset the `AutoRunScript` when switching to a simple shell.
Here is the error:
https://github.com/rapid7/metasploit-framework/blob/04f11b0bf7d79b79485bbbe04d86bc59cb3d956a/modules/post/windows/manage/migrate.rb#L34

This script is missing a check if it's run inside a meterpreter session.

```
[*] Session ID 3 (10.x.x.x:12345 -> 10.y.y.y:1447) processing AutoRunScript 'post/windows/manage/migrate'
[-] Post failed: NoMethodError undefined method `[]' for nil:NilClass
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/post/windows/manage/migrate.rb:34:in `run'
```

# Settings
```
msf exploit(handler) > options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (windows/shell_reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     10.x.x.x         yes       The listen address
   LPORT     12345            yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target
```

```
msf exploit(handler) > advanced

Module advanced options (exploit/multi/handler):

   Name                    Current Setting  Required  Description
   ----                    ---------------  --------  -----------
   ContextInformationFile                   no        The information file that contains context information
   DisablePayloadHandler   false            no        Disable the handler code for the selected payload
   EnableContextEncoding   false            no        Use transient context when encoding payloads
   ExitOnSession           false            no        Return from the exploit after a session has been created
   ListenerTimeout         0                no        The maximum number of seconds to wait for new sessions
   VERBOSE                 false            no        Enable detailed status messages
   WORKSPACE                                no        Specify the workspace for this module
   WfsDelay                0                no        Additional delay when waiting for a session


Payload advanced options (windows/shell_reverse_tcp):

   Name                        Current Setting              Required  Description
   ----                        ---------------              --------  -----------
   AutoRunScript               post/windows/manage/migrate  no        A script to run automatically on session creation.
   InitialAutoRunScript                                     no        An initial script to run on session creation (before AutoRunScript)
   PrependMigrate              false                        yes       Spawns and runs shellcode in new process
   PrependMigrateProc                                       no        Process to spawn and run shellcode in
   ReverseAllowProxy           false                        yes       Allow reverse tcp even with Proxies specified. Connect back will NOT go through proxy but directly to LHOST
   ReverseConnectRetries       5                            yes       The number of connection attempts to try before exiting the process
   ReverseListenerBindAddress                               no        The specific IP address to bind to on the local system
   ReverseListenerBindPort                                  no        The port to bind to on the local system if different from LPORT
   ReverseListenerComm                                      no        The specific communication channel to use for this listener
   ReverseListenerThreaded     false                        yes       Handle every connection in a new thread (experimental)
   VERBOSE                     false                        no        Enable detailed status messages
   WORKSPACE                                                no        Specify the workspace for this module
```

### PR DESCRIPTION
**Pull request by wvu**
Fixes #8360.

### CODE REVIEW

File: lib/msf/base/serializer/readable_text.rb [hunk 1]
```diff
@@ -165,6 +165,7 @@ def self.dump_exploit_module(mod, indent = '')
     output << "       Name: #{mod.name}\n"
     output << "     Module: #{mod.fullname}\n"
     output << "   Platform: #{mod.platform_to_s}\n"
+    output << "       Arch: #{mod.arch_to_s}\n"
```
Comment (wvu-r7) [inline lib/msf/base/serializer/readable_text.rb]: Amazingly, `info` for exploits didn't show arch.

File: lib/msf/core/post_mixin.rb [hunk 2]
```diff
@@ -38,8 +39,6 @@ def setup
       print_warning('SESSION may not be compatible with this module.')
     end
 
-    super
```
Comment (wvu-r7) [inline lib/msf/core/post_mixin.rb]: Fixed in https://github.com/rapid7/metasploit-framework/commit/b2de5aba07c0b0e9379caa7373d717c93c666341. This was not dead code for local exploits.

**Comment by jmartin-r7** [comment]
### Release Notes

Fix missing setup method in post modules.
