### PR TITLE
handle general failure getting module info for external modules

### LINKED ISSUE #8211: Latest metasploit-framework not working inside docker (broken pipe)
Currently getting the following error message when building and running the docker image. Tested on OSX and Fedora:

```
/usr/src/metasploit-framework/lib/msf/core/modules/external/bridge.rb:84:in `write': Broken pipe (Errno::EPIPE)
	from /usr/src/metasploit-framework/lib/msf/core/modules/external/bridge.rb:84:in `write_message'
	from /usr/src/metasploit-framework/lib/msf/core/modules/external/bridge.rb:67:in `send'
	from /usr/src/metasploit-framework/lib/msf/core/modules/external/bridge.rb:55:in `send_receive'
	from /usr/src/metasploit-framework/lib/msf/core/modules/external/bridge.rb:47:in `describe'
	from /usr/src/metasploit-framework/lib/msf/core/modules/external/bridge.rb:11:in `meta'
	from /usr/src/metasploit-framework/lib/msf/core/modules/external/shim.rb:8:in `generate'
	from /usr/src/metasploit-framework/lib/msf/core/modules/loader/executable.rb:85:in `read_module_content'
	from /usr/src/metasploit-framework/lib/msf/core/modules/loader/base.rb:126:in `load_module'
	from /usr/src/metasploit-framework/lib/msf/core/modules/loader/base.rb:237:in `block in load_modules'
	from /usr/src/metasploit-framework/lib/msf/core/modules/loader/executable.rb:51:in `block (2 levels) in each_module_reference_name'
	from /usr/local/bundle/gems/rex-core-0.1.9/lib/rex/file.rb:133:in `block in find'
	from /usr/local/bundle/gems/rex-core-0.1.9/lib/rex/file.rb:132:in `catch'
	from /usr/local/bundle/gems/rex-core-0.1.9/lib/rex/file.rb:132:in `find'
	from /usr/src/metasploit-framework/lib/msf/core/modules/loader/executable.rb:42:in `block in each_module_reference_name'
	from /usr/src/metasploit-framework/lib/msf/core/modules/loader/executable.rb:31:in `foreach'
	from /usr/src/metasploit-framework/lib/msf/core/modules/loader/executable.rb:31:in `each_module_reference_name'
	from /usr/src/metasploit-framework/lib/msf/core/modules/loader/base.rb:236:in `load_modules'
	from /usr/src/metasploit-framework/lib/msf/core/module_manager/loading.rb:119:in `block in load_modules'
	from /usr/src/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `each'
	from /usr/src/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `load_modules'
	from /usr/src/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	from /usr/src/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	from /usr/src/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	from /usr/src/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
	from /usr/src/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
	from /usr/src/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
	from /usr/src/metasploit-framework/lib/msf/ui/console/driver.rb:219:in `initialize'
	from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
	from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
	from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /usr/src/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from ./msfconsole:48:in `<main>'
```

### PR DESCRIPTION
**Pull request by busterb**
While it seems that ENOENT gets handled earlier in the process, running in docker as in #8211 seems to throw an error later when we try to get description, which causes a later EPIPE failure. This catches the exception and logs to framework.log instead of killing the loader.

This fixes #8211

## Verification

- [x] Install Docker / docker-compose
- [x] Follow the steps under docker/README in msf to get a development environment started
- [x] Exit, and start it again (docker-compose run --rm --service-ports ms), don't rebuild.
- [x] **Verify** that framework starts with 1739 modules
- [x] **Verify** this shows up in your ~/.msf4/logs/framework.log:
```
[04/09/2017 16:49:06] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/exploits/linux/smtp/haraka.py Errno::EPIPE Broken pipe
```

### CODE REVIEW

**Comment by FireFart** [comment]
Thanks @busterb !
Can confirm the patch is working.

Entry from framework.log:
```
[04/09/2017 17:01:20] [e(0)] core: Unable to load module /usr/src/metasploit-framework/modules/exploits/linux/smtp/haraka.py Errno::EPIPE Broken pipe
```

File: lib/msf/core/modules/loader/executable.rb [hunk 1]
```diff
@@ -82,6 +82,11 @@ def read_module_content(parent_path, type, module_reference_name)
       load_error(full_path, Errno::ENOENT.new)
       return ''
     end
-    Msf::Modules::External::Shim.generate(full_path)
+    begin
+      Msf::Modules::External::Shim.generate(full_path)
+    rescue ::Exception => e
+      elog "Unable to load module #{full_path} #{e.class} #{e}"
+      ''
```
Comment (acammack-r7) [inline lib/msf/core/modules/loader/executable.rb]: We will also want to generate a `load_error` here so that framework knows something went wrong with the module.

Comment (FireFart) [inline lib/msf/core/modules/loader/executable.rb]: @acammack-r7 aren't `load_error` messages also printed out to the terminal when msfconsole starts? Is it a real bug that the python module can't be loaded or should this error only be shown in framework.log?
https://github.com/rapid7/metasploit-framework/blob/cac890a797d0d770260074dfe703eb5cfb63bd46/lib/msf/core/modules/loader/base.rb#L400

Comment (busterb) [inline lib/msf/core/modules/loader/executable.rb]: D'oh, now it's obvious :) Retesting.

Comment (busterb) [inline lib/msf/core/modules/loader/executable.rb]: That's a good point too @FireFart. I suppose eventually we want the user to know a dependency is missing, but it should probably be more of a one-off warning than a series of errors.

Comment (busterb) [inline lib/msf/core/modules/loader/executable.rb]: How is the latest revision as a compromise?

**Comment by FireFart** [comment]
@busterb @acammack-r7 I now traced down the isssue:
https://github.com/rapid7/metasploit-framework/blob/1245eb9db9d7fe4a5bfdf72ccabd2d697cd123c3/lib/msf/core/modules/external/bridge.rb#L60
According to https://apidock.com/ruby/Open3/popen3 the constructor uses `Process.spawn` to run the input (in this case it's `/usr/src/metasploit-framework/modules/exploits/linux/smtp/haraka.py`).

As there is no python installed in this conainer, this call fails. I tried adding python manually and the error goes away.

I think there is a false assumption that the environment has installed the software needed to run external modules. I think the external loader has to do some checks to see if external modules can be executed on the system.

If I put a `puts status.read` after the `popen3` call i get back (which represents stderr) :
```
env: can't execute 'python2.7': No such file or directory
```

So I think the correct fix for this is:
- Check stderr after the popen3 call
- better error handling
- issue a load error with the original error message from the process so the user can handle it

**Comment by FireFart** [comment]
btw: Why are all modules executed on start? I think as more and more modules are added this significantly increases startup time. Also the call that causes this issue is a try to only get the modules metadata:
https://github.com/rapid7/metasploit-framework/blob/1245eb9db9d7fe4a5bfdf72ccabd2d697cd123c3/lib/msf/core/modules/external/shim.rb#L8

Is it intended the module is executed when we try to just read the metadata?

**Comment by busterb** [comment]
That's the initial design @FireFart, which sort of mirrors the way ruby modules are evaled. I think there is an idea to switch to a more passive module introspection on the second pass.

**Comment by acammack-r7** [comment]
@FireFart All ruby modules are also run on start (multiple times, even). For a number of modules some metadata fields (like targets and compatible payloads) are determined programmatically, often by deriving stuff from ropdb. They way the datastore works also requires running the module to register options.

Caching each module's static metadata as, say, `module.json` files and only running it if you specifically need something that is dynamically generated is probably the way forward, but there has been resistance in the past to having a multi-file module system. There is also a fair amount of tooling that would be required to keep that data consistent.

This fix looks good for now, though. Thanks for finding broken code!

**Comment by FireFart** [comment]
@acammack-r7 ok thanks for the clarification!

I think we should still check stderr after the popen3 call and add python to the docker image if it's now a requirement

**Comment by busterb** [comment]
I resisted adding python to the docker image for now, simply because it's nice to have an environment that fails differently. Will probably add once the schema and design is more nailed down.

**Comment by busterb** [comment]
## Release Notes

This fixes a bug in external module support where, in certain environments, msfconsole can fail to load due to missing module dependencies.
