### PR TITLE
Fix duplicate hash keys

### LINKED ISSUE #4818: Duplicate key issues on a few modules
```
/usr/share/metasploit/lib/rex/proto/http/server.rb:83: warning: duplicated key at line 84 ignored: "jpeg"
/usr/share/metasploit/lib/rex/proto/smb/exceptions.rb:11: warning: duplicated key at line 12 ignored: 0
/usr/share/metasploit/lib/rex/proto/smb/exceptions.rb:17: warning: duplicated key at line 18 ignored: 128
/usr/share/metasploit/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/usr/share/metasploit/lib/msf/core/post/windows/ldap.rb:67: warning: duplicated key at line 71 ignored: 9
[*] Starting the Metasploit Framework console...
/usr/share/metasploit/modules/post/windows/gather/credentials/razorsql.rb:130: warning: duplicated key at line 131 ignored: "N"
/usr/share/metasploit/modules/exploits/windows/scada/winlog_runtime_2.rb:40: warning: duplicated key at line 47 ignored: "Platform"
/usr/share/metasploit/modules/exploits/windows/http/hp_pcm_snac_update_domain.rb:44: warning: duplicated key at line 50 ignored: "DefaultOptions"
/usr/share/metasploit/modules/exploits/windows/http/hp_pcm_snac_update_certificates.rb:44: warning: duplicated key at line 50 ignored: "DefaultOptions"
/usr/share/metasploit/modules/exploits/windows/local/pxeexploit.rb:33: warning: duplicated key at line 51 ignored: "DefaultOptions"
/usr/share/metasploit/modules/exploits/windows/browser/cisco_playerpt_setsource.rb:52: warning: duplicated key at line 60 ignored: "DefaultOptions"
/usr/share/metasploit/modules/exploits/windows/browser/ntr_activex_check_bof.rb:54: warning: duplicated key at line 62 ignored: "DefaultOptions"
/usr/share/metasploit/modules/exploits/windows/browser/cisco_playerpt_setsource_surl.rb:56: warning: duplicated key at line 62 ignored: "DefaultOptions"
/usr/share/metasploit/modules/exploits/windows/browser/ms13_090_cardspacesigninhelper.rb:112: warning: duplicated key at line 114 ignored: "massage_array"
/usr/share/metasploit/modules/exploits/windows/browser/oracle_autovue_setmarkupmode.rb:60: warning: duplicated key at line 66 ignored: "DefaultOptions"
/usr/share/metasploit/modules/exploits/windows/browser/ntr_activex_stopmodule.rb:51: warning: duplicated key at line 58 ignored: "DefaultOptions"
/usr/share/metasploit/modules/exploits/windows/backupexec/name_service.rb:43: warning: duplicated key at line 44 ignored: "MinNops"
/usr/share/metasploit/modules/exploits/windows/mssql/mssql_linkcrawler.rb:44: warning: duplicated key at line 52 ignored: "Platform"
/usr/share/metasploit/modules/exploits/linux/http/netgear_dgn2200b_pppoe_exec.rb:188: warning: duplicated key at line 192 ignored: "opendns_parental_ctrl"
/usr/share/metasploit/modules/exploits/multi/misc/java_jmx_server.rb:107: warning: duplicated key at line 107 ignored: "RPORT"
/usr/share/metasploit/modules/exploits/multi/misc/java_jmx_server.rb:139: warning: duplicated key at line 139 ignored: "RPORT"
/usr/share/metasploit/modules/auxiliary/scanner/http/http_login.rb:28: warning: duplicated key at line 30 ignored: "References"
/usr/share/metasploit/modules/auxiliary/scanner/http/bmc_trackit_passwd_reset.rb:134: warning: duplicated key at line 135 ignored: "SelectedQuestion"
/usr/share/metasploit/modules/auxiliary/scanner/http/bmc_trackit_passwd_reset.rb:136: warning: duplicated key at line 137 ignored: "answer"
/usr/share/metasploit/modules/auxiliary/scanner/http/bmc_trackit_passwd_reset.rb:138: warning: duplicated key at line 139 ignored: "confirmanswer"
```

ruby version ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

These dont seem to affect creating handlers or using payloads, I believe this would just affect the above mentioned modules.

### PR DESCRIPTION
**Pull request by wvu**
Fixes #4818. The ones I didn't fix look like "intentional" duplicates.

### CODE REVIEW

**Comment by bcook-r7** [comment]
Oops, looks straightforward enough.

File: modules/exploits/windows/browser/ntr_activex_check_bof.rb [hunk 1]
```diff
@@ -51,6 +51,7 @@ def initialize(info = {})
       'DefaultOptions' =>
         {
           'EXITFUNC' => 'process',
```
Comment (bcook-r7) [inline modules/exploits/windows/browser/ntr_activex_check_bof.rb]: Do a few of these change behavior? Assuming the hash keys are reinitialized on the second assignment, was 'EXITFUNC' undefined originally, or was it set to 'process'. Does it make a difference?

Comment (bcook-r7) [inline modules/exploits/windows/browser/ntr_activex_check_bof.rb]: the default mixin value is already 'process', so this is fine

File: modules/exploits/windows/http/hp_pcm_snac_update_certificates.rb [hunk 2]
```diff
@@ -40,17 +40,14 @@ def initialize(info = {})
       'Arch'           => ARCH_JAVA,
       'DefaultOptions' =>
         {
-          'SHELL' => 'cmd.exe'
+          'SHELL' => 'cmd.exe',
```
Comment (bcook-r7) [inline modules/exploits/windows/http/hp_pcm_snac_update_certificates.rb]: This default SHELL option is used for the other hp_* exploits, though it feels like there may be some blind copy/paste between http modules.

**Comment by bcook-r7** [comment]
Landed, thanks! Any superfluous initializations in the first place, we might want to have a second pass and remove them as well.
