### PR TITLE
fix #15804, fix powershell read_file on Windows Server 2012

### LINKED ISSUE #15804: Powershell script in lib/msf/core/post/file.rb compatibility issue
Powershell [script](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/file.rb#L681-L686) in `_read_file_powershell_fragment` is not compatible with older Windows (e.g. Server 2012). Other scripts in this module might have the same compatibility issue (not tested).

This is the output I got when running the Powershell commands directly on the target:
```
PS C:\Users\Administrator> $mstream = [System.IO.MemoryStream]::new();
Method invocation failed because [System.IO.MemoryStream] doesn't contain a method named 'new'.
At line:1 char:1
+ $mstream = [System.IO.MemoryStream]::new();
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

PS C:\Users\Administrator> $gzipstream = [System.IO.Compression.GZipStream]::new($mstream, [System.IO.Compression.Compre
ssionMode]::Compress);
Method invocation failed because [System.IO.Compression.GZipStream] doesn't contain a method named 'new'.
At line:1 char:1
+ $gzipstream = [System.IO.Compression.GZipStream]::new($mstream, [System.IO.Compr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

I tested against Windows 10 and it works fine (see https://github.com/rapid7/metasploit-framework/pull/15558 for details)

## Steps to reproduce

1. Get a Powershell session on a Windows Server 2012 (e.g. `payload/windows/x64/powershell_reverse_tcp`)
2. `use post/multi/manage/fileshare`
3. `set SESSION 1`
4. `run`
5. Open the given URL with a web browser
6. Download a file and verify it is empty.

## Expected behavior

The download file should not be empty.

## Current behavior

The downloaded file is empty.

### Metasploit version

Framework: 6.1.12-dev-1befd545e3
Console  : 6.1.12-dev-1befd545e3

### PR DESCRIPTION
**Pull request by timwr**
Fix https://github.com/rapid7/metasploit-framework/issues/15804 by using the old style powershell syntax (New-Object).

## Verification

- [ ] Get a `cmd/windows/powershell_reverse_tcp` session on Windows Server 2012 and Windows 7
- [ ] **Verify** the file tests:
```
loadpath test/modules
use post/test/file
set SESSION -1
set VERBOSE true
```
- [ ] Get a `cmd/windows/powershell_reverse_tcp_ssl` session on Windows 10
- [ ] **Verify** the file tests:
```
loadpath test/modules
use post/test/file
set SESSION -1
set VERBOSE true
```

### CODE REVIEW

File: modules/payloads/singles/cmd/windows/powershell_reverse_tcp.rb [hunk 1]
```diff
@@ -5,45 +5,45 @@
...
-      'Handler'       => Msf::Handler::ReverseTcpSsl,
-      'Session'       => Msf::Sessions::PowerShell,
-      'RequiredCmd'   => 'generic',
-      'Payload'       =>
-        {
-          'Offsets' => { },
+        'License' => MSF_LICENSE,
+        'Platform' => 'windows',
+        'Arch' => ARCH_CMD,
+        'Handler' => Msf::Handler::ReverseTcp,
```
Comment (cdelafuente-r7) [inline modules/payloads/singles/cmd/windows/powershell_reverse_tcp.rb:30]: It looks like the same process should be done for `payload/windows/x64/powershell_reverse_tcp` and `payload/windows/powershell_reverse_tcp` payloads, which seems to be broken now. Since their handler is still `Msf::Handler::ReverseTcpSsl`, they are expecting an SSL connection, which is now disabled when calling `generate_powershell_code("Reverse")`.

Maybe these payloads should also be split in two modules, with and without SSL?

**Review by cdelafuente-r7 — COMMENTED** [review]
Thanks for fixing this @timwr ! I just left a comment about other payloads that seem to be affected by this change and might need to be fixed too.

**Comment by bwatters-r7** [comment]
We had to deal with older TLS in baseline builder.  See https://github.com/rapid7/metasploit-baseline-builder/blob/master/scripts/installs/chocolatey.ps1

File: modules/payloads/singles/cmd/windows/powershell_reverse_tcp.rb (hunk 1 above)
Comment (timwr) [reply modules/payloads/singles/cmd/windows/powershell_reverse_tcp.rb:30]: Well spotted, this is fixed now!

**Comment by timwr** [comment]
Sorry for the delay on this! I really couldn't figure out how to get the SSL connection working on Windows 7. However I was able to fix it for Windows Server 2012: https://github.com/rapid7/metasploit-framework/pull/15808/commits/970e7cb67c763da200ab3469a011e7532710d305
Because of this I guess we still need both the ssl and non-ssl payloads, so I've fixed up the pr with those changes (for both the cmd and exe payloads).

**Comment by cdelafuente-r7** [comment]
Thanks for updating this @timwr ! I verified it works with all payloads against windows Server 2012. On windows 7, the `cmd` Powershell payloads only work without SSL, as you said. I checked with both `post/test/file` and the `post/multi/manage/fileshare` module. I'll go ahead and land it.

Note that `post/test/file` has an issue with Powershell when it checks for file existence. It uses the `%WINDIR%` environment variable, which doesn't work with Powershell (the syntax is `$Env:windir`). Not a big deal, I checked and `file?` method works fine with full path like `C:\...`.

- Example output
```
msf6 payload(cmd/windows/powershell_reverse_tcp_ssl) > previous
msf6 post(test/file) > set session -1
session => -1
msf6 post(test/file) > set verbose true
verbose => true
msf6 post(test/file) > run

[*] Setup: changing working directory to %TEMP%
[!] SESSION may not be compatible with this module:
[!]  * incompatible session type: powershell
[*] Running against session -1
[*] Session type is powershell and platform is windows
[+] should test for file existence
[+] should test for directory existence
[+] should create text files
[+] should read the text we just wrote
[+] should append text files
[+] should delete text files
[+] should move files
[*] Writing 31264 bytes
[*] Finished in 0.029119
[+] should write binary data
[*] Read 31264 bytes
[+] should read the binary data we just wrote
[+] should delete binary files
[+] should append binary data
[*] Testing complete in 4.08216
[*] Passed: 11; Failed: 0
[*] Cleanup: changing working directory back to C:\Users\Administrator\Desktop
[*] Post module execution completed
```

**Comment by cdelafuente-r7** [comment]
# Release Notes
This fixes a compatibility issue with Powershell `read_file` on Windows Server 2012 by using the old style Powershell syntax (New-Object).
