### PR TITLE
Apply fixes for invalid sysinfo['Architecture'] checks, aka #14599, to affected modules

### LINKED ISSUE #14599: Several Modules are Incorrectly Checking sysinfo['Architecture'] For wow64
Several modules appear to be checking `sysinfo['Architecture']` for the presence of `wow64`, however as noted during my tests and as @bwatters-r7 pointed out, https://github.com/rapid7/metasploit-framework/pull/7507 changed this behavior back in 2016 so that `sysinfo['Architecture']` will always return `x86` or `x64`. Specifically:

```
the Architecture value in sysinfo no longer shows (Current process is WOW64) when running a WOW64 process. Instead, architecture is always set to x86 or x64
```
This change was made as the idea was the architecture of the CPU is either going to be x86 or x64, however the session type itself, which can be retrieved via `session.type` will be `x86` or `x64`, and if the value of `sysinfo['Architecture']` is `x64` and `session.arch` is `x86`, then you know you have a WOW64 target.

Unfortunately we have a lot of modules that still do this, including popular ones such as SMBGhost as can be seen at https://github.com/rapid7/metasploit-framework/blob/c0b42ff7a2a1b677aaba6acd7ebeefddcffdf38e/modules/exploits/windows/local/cve_2020_0796_smbghost.rb#L97

It would be best to update these modules with a new function defined in https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/windows/process.rb called `is_wow64?` which would return a bool of `True` if `sysinfo['Architecture']` is `x64` and `session.arch` is `x86`, and `False` otherwise.

## Steps to reproduce
Sample is some steps that I took which showcase this issue:

1. Obtain a x86 Meterpreter session on a x64 host
2. Verify that `sysinfo['Architecture']` is `x64` instead of the expected value of WOW64.
3. Verify that `session.arch` is `x86`.

## Were you following a specific guide/tutorial or reading documentation?

Found whilst responding to feedback on https://github.com/rapid7/metasploit-framework/pull/14585

## Expected behavior

Modules should correctly check that both `sysinfo['Architecture']` is `x64` and that `session.arch` is `x86` before determining if a target is a WOW64 target.

## Current behavior

Modules are instead checking that `sysinfo['Architecture']` does not contain `wow64`. Since the contents of `sysinfo['Architecture']` will never contain this string, these modules could be run against WOW64 targets when they are not intended to be.

### Metasploit version
6.0.26-dev-cc686eeac2

### PR DESCRIPTION
**Pull request by gwillcox-r7**
Fixes #14599

Applies fixes to ensure that `sysinfo['Architecture']` is checked to see if it is `ARCH_X64` and that `session.arch` is `x86` before determining the target is a WOW64 target for several modules that were only checking to see if `sysinfo['Architecture']` contained `WOW64`. As per the discussion in #14599 this was incorrect as `sysinfo['Architecture']` will only return `ARCH_X64` or `ARCH_X86` aka the strings `x64` and `x86` respectively, and will no longer return the `wow64` string as per the change in https://github.com/rapid7/metasploit-framework/pull/7507, which notes:

`the Architecture value in sysinfo no longer shows (Current process is WOW64) when running a WOW64 process. Instead, architecture is always set to x86 or x64`

I also went ahead and tided up a few modules that were using regex checks where they could have just used a check to see if the value was `ARCH_X64` along the way to help make the code a bit neater and faster to run.

The bug tag was applied only cause this is a bug for the code at https://github.com/rapid7/metasploit-framework/blob/c0b42ff7a2a1b677aaba6acd7ebeefddcffdf38e/modules/exploits/windows/local/cve_2020_0796_smbghost.rb#L97. All other files I believe are mostly just improvements for the sake of making them in line with the change; they shouldn't really affect how the exploit performs when running against a WOW64 target compared to the code that it is currently running.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] Make sure all the modules load and there are no errors.
- [x] **Verify** that the changes look correct.
- [x] **Verify** the modules still return an error code (if applicable) if the target is a WOW64 target and that module is supposed to throw an error upon realizing the target is WOW64.
- [x] **Document** any errors encountered or questions, etc you have.

### CODE REVIEW

**Comment by smcintyre-r7** [comment]
Changes look good to me, I'm going to go ahead and start testing. Thanks for taking this on Grant!.

**Comment by smcintyre-r7** [comment]
@msjenkins-r7 test this please.

File: modules/exploits/windows/local/ms15_051_client_copy_image.rb [hunk 1]
```diff
@@ -73,11 +73,7 @@ def check
       return Exploit::CheckCode::Unknown
     end
 
-    if sysinfo['Architecture'] =~ /(wow|x)64/i
-      arch = ARCH_X64
-    elsif sysinfo['Architecture'] =~ /x86/i
-      arch = ARCH_X86
-    end
+    arch = sysinfo['Architecture']
```
Comment (smcintyre-r7) [inline modules/exploits/windows/local/ms15_051_client_copy_image.rb:76]: This actually doesn't look like it's used anywhere. Are we sure this is still necessary? I'm wondering if the original had a fail on wow64 condition that was removed for the purposes of the check method.

File: modules/exploits/windows/local/ms14_058_track_popup_menu.rb [hunk 2]
```diff
@@ -82,7 +82,7 @@ def check
       return Exploit::CheckCode::Safe
     end
 
-    if sysinfo["Architecture"] =~ /(wow|x)64/i
+    if sysinfo["Architecture"] == ARCH_X64
```
Comment (smcintyre-r7) [inline modules/exploits/windows/local/ms14_058_track_popup_menu.rb:85]: This all looks like it could be reduced to `arch = sysinfo["Architecture"]` like it is in `ms15_051_client_copy_image.rb`, but I also don't see where the arch is used so it may not be necessary any more.

File: modules/exploits/windows/local/ms15_051_client_copy_image.rb (hunk 1 above)
Comment (gwillcox-r7) [reply modules/exploits/windows/local/ms15_051_client_copy_image.rb:76]: This doesn't look to be necessary in the current code. Previous code I see this definition, which still doesn't make much sense: as `arch` isn't being used in the code, but it does show the old `wow64` condition check.

```
  def check
    # Windows XP SP3 (32-bit)                      5.1.2600.6514 (Works)
    # Windows Server 2003 Standard SP2 (32-bit)    5.2.3790.5445 (Works)
    # Windows Server 2008 Enterprise SP2 (32-bit)  6.0.6002.18005 (Does not work)
    # Windows 7 SP1 (64-bit)                       6.1.7601.17514 (Works)
    # Windows 7 SP1 (64-bit)                       6.1.7601.17535 (Works)
    # Windows 7 SP1 (32-bit)                       6.1.7601.17514 (Works)
    # Windows 7 SP1 (32-bit)                       6.1.7601.18388 (Works)
    # Windows Server 2008 R2 (64-bit) SP1          6.1.7601.17514 (Works)
    # Windows Server 2008 R2 (64-bit) SP1          6.1.7601.18105 (Works)
    if sysinfo['OS'] !~ /windows/i
      return Exploit::CheckCode::Unknown
    end
    if sysinfo['Architecture'] =~ /(wow|x)64/i
      arch = ARCH_X64
    elsif sysinfo['Architecture'] =~ /x86/i
      arch = ARCH_X86
    end
    file_path = expand_path('%windir%') << '\\system32\\win32k.sys'
    major, minor, build, revision, branch = file_version(file_path)
    vprint_status("win32k.sys file version: #{major}.#{minor}.#{build}.#{revision} branch: #{branch}")
    return Exploit::CheckCode::Safe if build > 7601
    return Exploit::CheckCode::Appears
  end
```

Comment (gwillcox-r7) [reply modules/exploits/windows/local/ms15_051_client_copy_image.rb:76]: Given the above and the lack of a use case here it may be better to just remove this code as mentioned. I'll make an update now to fix this.

File: modules/exploits/windows/local/ms14_058_track_popup_menu.rb (hunk 2 above)
Comment (gwillcox-r7) [reply modules/exploits/windows/local/ms14_058_track_popup_menu.rb:85]: I think the idea here might of originally only been to do this so that certain architectures are picked up but I see all of this logic is done later in the `exploit` code and as you mentioned `arch` isn't used anywhere after being set, so I agree this code should be removed. Will update this now.

Comment (gwillcox-r7) [reply modules/exploits/windows/local/ms14_058_track_popup_menu.rb]: Should be resolved with https://github.com/rapid7/metasploit-framework/pull/14792/commits/41794fe4e7939ffa46ebd6dc44f466c019c6cbb6 now.

File: modules/exploits/windows/local/ms15_051_client_copy_image.rb (hunk 1 above)
Comment (gwillcox-r7) [reply modules/exploits/windows/local/ms15_051_client_copy_image.rb]: Should be resolved with 41794fe now.

**Comment by smcintyre-r7** [comment]
Changes look good and I haven't noticed any issues from my testing so I'll get this merged in now.

In this case, the modules are not expected to work, but the test case is showing that they're not throwing an unhandled exception and that they're properly analyzing the system to identify that it's not vulnerable.
```
msf6 exploit(windows/local/ms15_051_client_copy_image) > run

[*] Started reverse TCP handler on 192.168.250.87:4444 
[-] Exploit aborted due to failure: not-vulnerable: Exploit not available on this system.
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/ms15_051_client_copy_image) > use exploit/windows/local/ms14_058_track_popup_menu 
[*] No payload configured, defaulting to windows/meterpreter/reverse_tcp
msf6 exploit(windows/local/ms14_058_track_popup_menu) > run

[*] Started reverse TCP handler on 192.168.250.87:4444 
[-] Exploit aborted due to failure: no-target: Running against WOW64 is not supported
[*] Exploit completed, but no session was created.
msf6 exploit(windows/local/ms14_058_track_popup_menu) > 
```

**Comment by smcintyre-r7** [comment]
# Release Notes
This updates 11 modules targeting Windows systems that were improperly checking the environment architecture which led to broken WOW64 detection in some cases.
