### PR TITLE
Fix #5103, Revert unwanted URI encoding

### LINKED ISSUE #5103: Commit "da0a9f66ea93307cf2985dab3f75cf5611932cc8" breaks module "exploit/linux/http/openfiler_networkcard_exec"
Hello team - this bug is for the openfiler Metasploit module. For reference, [here is the the official documentation page](http://www.rapid7.com/db/modules/exploit/linux/http/openfiler_networkcard_exec) on the module and [here is the Github page](https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/linux/http/openfiler_networkcard_exec.rb) for it.

[This commit](https://github.com/rapid7/metasploit-framework/commit/da0a9f66ea93307cf2985dab3f75cf5611932cc8) by FireFart on May 25, 2014 appears to break the code.

To test, I am using a VM with Openfiler on it. The version is "Openfiler NSA (32-bit PAE)" (as reported in "/etc/distro-release").

In Metasploit, I load the payload "use exploit/linux/http/openfiler_networkcard_exec" and then use a payload of "cmd/unix/reverse_perl".

In my testing, versions of the code prior to this commit will work just fine and receive the remote shell. And versions of the code after this commit will fail. With someone who only has a passing familiarity with Metasploit module code, I'm not sure why this is.

Let me know if you need additional information, but I'm thinking this should be easy enough to reproduce. ;)

### PR DESCRIPTION
**Pull request by wchen-r7**
Fix #5103. By default, Httpclient will encode the URI but we don't necessarily want that. These modules originally didn't use URI encoding when they were written so we should just keep them that way.

@FireFart Can you please take this?

### CODE REVIEW

File: modules/auxiliary/scanner/sap/sap_soap_bapi_user_create1.rb [hunk 1]
```diff
@@ -81,6 +81,7 @@ def run_host(ip)
         'headers' => {
           'SOAPAction' => 'urn:sap-com:document:sap:rfc:functions',
         },
+        'encode_params' => false,
```
Comment (FireFart) [inline modules/auxiliary/scanner/sap/sap_soap_bapi_user_create1.rb]: i think this is not necessary on the SAP modules because of non payload paramters. I think i looked through the modules and identified the ones which needs the encode_params (by eliminating the fixed and non payload parameters). Or do you want to change all of them?

Comment (wchen-r7) [inline modules/auxiliary/scanner/sap/sap_soap_bapi_user_create1.rb]: ```sap-client``` is user-supplied so I guess it's possible to get URI-encoded... I'm only trying to restore the original behavior that I know for sure should work because they were originally written that way.

**Comment by FireFart** [comment]
should now be working again
