### PR TITLE
Fix #13318, Expand Environment Variables In Meterpreter's ls Command

### LINKED ISSUE #13318: Suggestion: Expand Environment Variables In Meterpreter's ls Command
## Steps to reproduce

I found a small bug. When i'm on a meterpreter windows session  

I want to do a recursive directory listing 
`meterpreter > dir -R c:/users/admin/Desktop`

The recursive option work well, it list the content of every subfolders as expected.

But a 
`meterpreter > dir -R %USERPROFILE%/Desktop`

The recusive option won't work. It just list the content of the Desktop folder. 
It can be a problem when you don't know the username in advance, or if you use a AutoRunScript.

### Metasploit version

msf5 exploit(multi/handler) > version
Framework: 5.0.85-dev
Console  : 5.0.85-de

### I installed Metasploit with:
- [x] Kali package via apt

### OS
Kali (update to date)

Thanks you

### PR DESCRIPTION
**Pull request by cn-kali-team**
see [#13318](https://github.com/rapid7/metasploit-framework/issues/13318)

```
meterpreter > ls -R %USERPROFILE%/Desktop                                                  
Listing: C:\Users\Administrator/Desktop/dir                                                
===========================================                                                
                                                                                           
Mode              Size  Type  Last modified              Name                              
----              ----  ----  -------------              ----                              
100666/rw-rw-rw-  0     fil   2020-04-24 11:11:43 +0800  file.txt                          
                                                                                           
Listing: C:\Users\Administrator/Desktop                                                    
=======================================                                                    
                                                                                           
Mode              Size      Type  Last modified              Name                          
----              ----      ----  -------------              ----                          
100777/rwxrwxrwx  73802     fil   2020-04-02 19:44:05 +0800  32.exe                        
100777/rwxrwxrwx  7168      fil   2020-03-14 00:11:23 +0800  64.exe                        
100666/rw-rw-rw-  475424    fil   2020-04-02 23:03:29 +0800  DebugView.zip                 
100666/rw-rw-rw-  49210     fil   1998-06-17 00:00:00 +0800  SPYHK55.DLL                   
100666/rw-rw-rw-  194       fil   2020-04-04 20:45:31 +0800  debug.txt                     
100666/rw-rw-rw-  282       fil   2020-02-26 07:54:53 +0800  desktop.ini                   
40777/rwxrwxrwx   0         dir   2020-04-24 11:11:36 +0800  dir                           
100666/rw-rw-rw-  15650     fil   2020-03-26 15:34:03 +0800  payload.asm                   
100666/rw-rw-rw-  796       fil   2020-03-26 15:34:03 +0800  payload.bin                   
100666/rw-rw-rw-  279       fil   2020-04-12 17:46:04 +0800  rdpv.cfg                      
100666/rw-rw-rw-  31867697  fil   2020-02-27 20:08:04 +0800  snapshot_2020-01-08_01-50.zip 
100666/rw-rw-rw-  1764      fil   2020-02-27 20:08:54 +0800  x32dbg.lnk                    
100666/rw-rw-rw-  1764      fil   2020-02-27 20:08:54 +0800  x64dbg.lnk                    

```

### CODE REVIEW

**Comment by smcintyre-r7** [comment]
Well that doesn't really have anything to do with being recursive. This is basically changing the behavior to expand the path when using the `ls` command. Unfortunately for historical reasons, the `expand_path` function doesn't really behave the way we would hope that it would, particularly on Linux. What that means is that this fix would really just be relevant for Meterpreter running on Windows.

Since this adds an additional round trip for the `ls` command (to expand the path), **would you mind filtering it to only function when the platform is Windows** so others continue to run as quickly as they do today?

To see the behavior I'm talking about, from a Meterpreter on Linux try to run: `ls $HOME/Downloads` and see it fail while `ls HOME` works (which I at least wouldn't expect it to and this interferes with the user when accessing a file path which is also an environment variable).

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb [hunk 1]
```diff
@@ -711,7 +711,11 @@ def cmd_ls(*args)
         cmd_ls_help
         return 0
       when nil
-        path = val
+        if client.platform == 'windows' && val.include?('%')
+          path = client.fs.file.expand_path(val)
+        else
+          path = val
+        end
```
Comment (smcintyre-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:718]: I talked this over with the team and they mentioned that this should actually use the `PATH_REGEX` to be consistent with the other uses in this file.

That would make the whole thing:
```suggestion
        path = val
        path = client.fs.file.expand_path(path) if path =~ PATH_EXPAND_REGEX
```

Sorry for the confusion. Once this has been changed over, I'll test this once more and land it. Thanks!

Comment (cn-kali-team) [reply lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb]: Thank you. I've revised it as you said.

**Comment by smcintyre-r7** [comment]
This is working as intended now. I'll go ahead and get it landed. Thanks @cn-kali-team !

```
msf5 payload(windows/x64/meterpreter/reverse_tcp) > 
[*] Sending stage (206403 bytes) to 192.168.159.39
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.39:49721) at 2020-05-01 09:00:24 -0400

msf5 payload(windows/x64/meterpreter/reverse_tcp) > sessions -i -1
[*] Starting interaction with 1...

meterpreter > ls %USERPROFILE%/Desktop 
Listing: C:\Users\smcintyre/Desktop
===================================

Mode              Size    Type  Last modified              Name
----              ----    ----  -------------              ----
100666/rw-rw-rw-  681     fil   2020-04-29 14:41:39 -0400  Kernel Dubugging.debugtarget
100666/rw-rw-rw-  1209    fil   2020-04-03 08:52:56 -0400  ProcessExplorer - Shortcut.lnk
100777/rwxrwxrwx  144384  fil   2020-04-23 14:44:23 -0400  UsoDllLoader.exe
...
```

**Comment by smcintyre-r7** [comment]
# Release Notes
This updates the behavior of Meterpreter's `ls` command to expand environment variables in the path argument on Windows systems.
