### PR TITLE
fix timestomp arg parsing

### LINKED ISSUE #5106: Meterpreter `timestomp` command argument order
It's more of a design flaw than a bug, but `timestomp test.txt -v` works, while `timestomp -v test.txt` silently fails. That feels awkward. 

Same is true for its all other flags.

Platform/Version information:
```
root@kali:/tmp# lsb_release -d
Description:	Kali GNU/Linux 1.1.0
root@kali:/tmp# uname -a
Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux
root@kali:/tmp# apt-cache show metasploit-framework | grep Version
Version: 4.11.1-2015040202-1kali1
```

### PR DESCRIPTION
**Pull request by rwhitcroft**
Fix #5106 

Arg/opt order doesn't matter now.

```
meterpreter > ls test2.txt
100666/rw-rw-rw-  7  fil  2015-04-10 00:41:56 -0400  test2.txt
meterpreter > timestomp test2.txt -v
Modified      : 2015-04-10 01:41:56 -0400
Accessed      : 2015-04-10 01:41:56 -0400
Created       : 2015-04-10 01:41:56 -0400
Entry Modified: 2015-04-10 01:41:56 -0400
meterpreter > timestomp -v test2.txt
Modified      : 2015-04-10 01:41:56 -0400
Accessed      : 2015-04-10 01:41:56 -0400
Created       : 2015-04-10 01:41:56 -0400
Entry Modified: 2015-04-10 01:41:56 -0400
meterpreter >
```

### CODE REVIEW

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/timestomp.rb [hunk 1]
```diff
@@ -52,12 +52,21 @@ def name
...
     if (args.length < 2)
-      print_line("\nUsage: timestomp file_path OPTIONS\n" +
+      print_line("\nUsage: timestomp OPTIONS file_path\n" +
         @@timestomp_opts.usage)
       return
     end
 
-    file_path = args.shift
+    file_path = nil
+    args.each { |a| file_path = a unless a[0] == "-" }
```
Comment (wvu-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/timestomp.rb]: What if I want to name my file with a ```-```? :-)

Comment (bcook-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/timestomp.rb]: ./-file ? That's the normal workaround.

Comment (wvu-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/timestomp.rb]: Just being sarcastic. :-)

I think that'd be ```.\-file``` on Windows?

Comment (bcook-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/timestomp.rb]: windows accepts / just fine. I wish they would just accept defeat.

Comment (wvu-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/timestomp.rb]: Good point. I suppose I'm used to commands not taking ```/```.

**Comment by wvu-r7** [comment]
Works for me.

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/commit/8acc768da7825629aba9338c4b3f63072cd4b258
