### PR TITLE
Fix #17969 Assign empty hash to variable status

### LINKED ISSUE #17969: Error while running command nessus_db_import: undefined local variable or method `status'
## Steps to reproduce

How'd you do it?

1. Use the latest kali 2023.1 and update msf to the newest version.
2. Load the nessus plugin by using command `load nessus` and `nessus_connect`
3. Import a scan result by using command `nessus_db_import 6`(6 is my scan id)

## Expected behavior

msf should have printed the following
```
[*] Exporting scan ID * is Nessus format...
[+] The export file ID for scan ID * is *
[*] Checking export status...
[*] Export status: loading
[*] Export status: ready
[*] The status of scan ID * export is ready
[*] Importing scan results to the database...
[*] Importing data of xxx.xxx.xxx.xxx
[+] Done
```

## Current behavior

The actual output of msf is as follows
```
[*] Exporting scan ID 6 is Nessus format...
[+] The export file ID for scan ID 6 is 1272956001
[*] Checking export status...
[*] Export status: loading
[*] Export status: ready
[-] Error while running command nessus_db_import: undefined local variable or method `status' for #<Msf::Plugin::Nessus::ConsoleCommandDispatcher:0x00007f81e59d73a8 ......

Call stack:
/usr/share/metasploit-framework/plugins/nessus.rb:1207:in `cmd_nessus_db_import'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
```

### Metasploit version

Framework: 6.3.14-dev
Console  : 6.3.14-dev

### PR DESCRIPTION
**Pull request by YiDa858**
Assign a nil value to the variable `status` to fix issue #17969

### CODE REVIEW

**Comment by bcoles** [comment]
This fixes the crash although is unlikely to fix the underlying issue.

What caused a code path with a `nil` status to be reached?

**Comment by YiDa858** [comment]
The variable is assigned in the loop. When the loop ends, `status['status']` will be accessed.
If I don't assign the variable before the loop begin, `status['status']` is always undefined according to the output.

File: plugins/nessus.rb [hunk 1]
```diff
@@ -1190,6 +1190,7 @@ def cmd_nessus_db_import(*args)
         if is_scan_complete(scan_id)
           print_status("Exporting scan ID #{scan_id} is Nessus format...")
           export = @n.scan_export(scan_id, 'nessus')
+          status = nil
```
Comment (cdelafuente-r7) [inline plugins/nessus.rb:1193]: A safer option would be to initialize the variable with an empty hash (`{}`). This would prevent any call to `status['...']` to break if `status` is `nil`.

**Comment by gwillcox-r7** [comment]
@YiDa858 Any update on implementing the suggested fix from @cdelafuente-r7 and testing it out?

**Comment by sjanusz-r7** [comment]
I've implemented the suggested change `nil -> {}`.

# `nessus_db_import`
Before:
<details>

```
msf6 > nessus_scan_list -c
Scan ID  Name                    Owner  Started  Status     Folder
-------  ----                    -----  -------  ------     ------
5        My Host Discovery Scan  msf             canceled   3
8        My Basic Network Scan   msf             canceled   3
14       MyNewScan               msf             completed  3

msf6 > nessus_db_import 14
[*] Exporting scan ID 14 is Nessus format...
[+] The export file ID for scan ID 14 is 940963288
[*] Checking export status...
[*] Export status: loading
[*] Export status: ready
[-] Error while running command nessus_db_import: undefined local variable or method `status' { ... }
```

</details>

After:

<details>

```
msf6 > nessus_scan_list -c
Scan ID  Name                    Owner  Started  Status     Folder
-------  ----                    -----  -------  ------     ------
5        My Host Discovery Scan  msf             canceled   3
8        My Basic Network Scan   msf             canceled   3
14       MyNewScan               msf             completed  3

msf6 > nessus_db_import 14
[*] Exporting scan ID 14 is Nessus format...
[+] The export file ID for scan ID 14 is 1751507142
[*] Checking export status...
[*] Export status: loading
[*] Export status: ready
[*] The status of scan ID 14 export is ready
[*] Importing scan results to the database...
[*] Importing data of 192.168.207.132
[+] Done
```

</details>

# `nessus_scan_export`
Before:
<details>

```
msf6 > nessus_scan_export 14 'Nessus'
[+] The export file ID for scan ID 14 is 1254750517
[*] Checking export status...
[*] Export status: loading
[*] Export status: ready
[-] Error while running command nessus_scan_export: undefined local variable or method `status' { ... }
```

</details>

After:
<details>

```
msf6 > nessus_scan_export 14 'Nessus'
[+] The export file ID for scan ID 14 is 187847318
[*] Checking export status...
[*] Export status: loading
[*] Export status: ready
[+] The status of scan ID 14 export is ready
```

</details>

**Review by adfoster-r7 — APPROVED** [review]

**Comment by sjanusz-r7** [comment]
# Release Notes
Fixed an error in `nessus_db_import` and `nessus_scan_export` commands that prevented them from completing successfully.
