### PR TITLE
Fix edgecase in Meterpreter job persistence

### LINKED ISSUE #18995: Job persist function doesn't seem to work
## Steps to reproduce

How'd you do it?

1. use exploit/multi/handler
2. set payload linux/x64/meterpreter/reverse_tcp
3. setg lhost ip
4.  run -j
5. jobs -p job_id
6. exit
7. msfconsole 
8. jobs

## Expected behavior

What should happen?
Job should survive.
## Current behavior

What happens instead?
Job does not.

In persist file it stores payload options with key 'Options' and the value as a string like 
[
  {
    "mod_name": "exploit/multi/handler",
    "mod_options": {
      "Payload": "linux/x64/meterpreter/reverse_tcp",
      "Options": "AppendExit=false ... WfsDelay=2 payload=linux/x64/meterpreter/reverse_tcp ",
      "RunAsJob": true
    }
  }
]

 When parsing the options it tries to do a .each on the string resulting in load fail with this entry in log...
[03/22/2024 10:34:11] [e(0)] core: Exploit failed (multi/handler) - NoMethodError undefined method `each' for "AppendExit=false ... WfsDelay=2 payload=linux/x64/meterpreter/reverse_tcp ":String

It looks like it dumps the datastore into the persist file in  https://github.com/rapid7/metasploit-framework/blob/11c24ecddaa90f76de79d9625add5aff44df2dcd/lib/msf/ui/console/command_dispatcher/jobs.rb#L247

And starts to load it here https://github.com/rapid7/metasploit-framework/blob/11c24ecddaa90f76de79d9625add5aff44df2dcd/lib/msf/ui/console/driver.rb#L211

### Metasploit version
Framework: 6.4.0-dev
Console  : 6.4.0-dev

### PR DESCRIPTION
**Pull request by adfoster-r7**
closes https://github.com/rapid7/metasploit-framework/issues/18995

## Verification

1. Verify jobs can be persisted

```
use exploit/multi/handler
set payload linux/x64/meterpreter/reverse_tcp
setg lhost ip
run -j
jobs -p job_id
exit
msfconsole
jobs
```

Ensure the job is available on console boot `jobs`

2.  Verify that `jobs -v` correctly detects when a job is persisted
3. Verify that the job is removed from being persisted when using `jobs -k 1` and with a negative index `jobs -k -1`

### CODE REVIEW

File: lib/msf/base/simple/module.rb [hunk 1]
```diff
@@ -18,10 +18,14 @@ module Module
   def _import_extra_options(opts)
     # If options were supplied, import them into the payload's
     # datastore
-    if (opts['Options'])
-      self.datastore.import_options_from_hash(opts['Options'])
-    elsif (opts['OptionStr'])
-      self.datastore.import_options_from_s(opts['OptionStr'])
+    if (value = opts['Options'])
+      if value.is_a?(String)
```
Comment (adfoster-r7) [inline lib/msf/base/simple/module.rb:22]: This allows persisted jobs to still be loaded correctly, i.e. the scenario of `Options` being a string instead of hash

File: lib/msf/ui/console/command_dispatcher/jobs.rb [hunk 2]
```diff
@@ -257,7 +257,7 @@ def add_persist_job(job_id)
 
               payload_opts = {
                 'Payload'        => payload.refname,
-                'Options'        => payload.datastore,
+                'Options'        => payload.datastore.to_h,
```
Comment (adfoster-r7) [inline lib/msf/ui/console/command_dispatcher/jobs.rb:260]: Serializing `payload.datastore` as JSON led to a string being saved, this allows a hash to be persisted instead

File: lib/msf/ui/console/driver.rb [hunk 3]
```diff
@@ -208,7 +208,21 @@ def initialize(prompt = DefaultPrompt, prompt_char = DefaultPromptChar, opts = {
 
       restore_handlers.each do |handler_opts|
         handler = framework.modules.create(handler_opts['mod_name'])
-        handler.exploit_simple(handler_opts['mod_options'])
+        handler.init_ui(self.input, self.output)
```
Comment (adfoster-r7) [inline lib/msf/ui/console/driver.rb:211]: Wiring up `init_ui` allows the user to have the job startup error messages logged to the console instead of them silently being ignored - which immediately showed the original hidden error

Before: No errors logged

After: Errors logged

```
➜  metasploit-framework git:(fix-edgecase-in-meterpreter-job-persistence) ✗ bundle exec ruby ./msfconsole --quiet
[*] Using configured payload linux/x64/meterpreter/reverse_tcp
[*] Starting persistent handler(s)...
[-] Msf::OptionValidateError One or more options failed to validate: MeterpreterDebugLogging.
[*] Failed to start persistent payload handler exploit/multi/handler
msf6 exploit(multi/handler) > 
```

File: spec/lib/msf/core/opt_meterpreter_debug_logging_spec.rb
Comment (adfoster-r7) [inline spec/lib/msf/core/opt_meterpreter_debug_logging_spec.rb:1]: Tests to fix the handling of `MeterpreterDebugLogging` being set to an empty string, because the `to_h` method persists nil as the empty string `""`:

https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/data_store_with_fallbacks.rb#L263-L272

File: spec/lib/msf/core/opt_meterpreter_debug_logging_spec.rb [hunk 4]
```diff
@@ -17,4 +19,18 @@
   ]
 
   it_behaves_like 'an option', valid_values, invalid_values, 'meterpreterdebuglogging'
+
+  describe '.parse_logging_options' do
```
Comment (adfoster-r7) [inline spec/lib/msf/core/opt_meterpreter_debug_logging_spec.rb:23]: Tests to verify the handling of `MeterpreterDebugLogging` being set to an empty string and causing validation errors is fixed, because the `to_h` method persists nil as the empty string `""`:

https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/data_store_with_fallbacks.rb#L263-L272

File: lib/msf/ui/console/command_dispatcher/jobs.rb [hunk 5]
```diff
@@ -213,12 +212,13 @@ def cmd_jobs(*args)
               end
 
               # Remove persistence by job id.
-              job_list.map(&:to_s).each do |job|
-                if framework.jobs.key?(job)
-                  ctx_1 = framework.jobs[job.to_s].ctx[1]
+              job_list.map(&:to_s).each do |job_id|
+                job_id = job_id.to_i < 0 ? framework.jobs.keys[job_id.to_i] : job_id
```
Comment (adfoster-r7) [inline lib/msf/ui/console/command_dispatcher/jobs.rb:216]: Pattern from:

**Comment by sjanusz-r7** [comment]
I followed the setup instructions with setting up a multi/handler.

## Before

Job does not survive a reboot of Console
```
bundle exec './msfconsole -q'
[*] New in Metasploit 6.4 - This module can target a SESSION or an RHOST
[*] Starting persistent handler(s)...
msf6 auxiliary(scanner/smb/smb_lookupsid) > jobs

Jobs
====

No active jobs.
```

## After

Job persists
```
bundle exec './msfconsole -q'
[*] New in Metasploit 6.4 - This module can target a SESSION or an RHOST
[*] Starting persistent handler(s)...
[*] Persistent payload handler started as Job 0
[*] Started reverse TCP handler on 192.168.112.1:4444 
msf6 auxiliary(scanner/smb/smb_lookupsid) > jobs

Jobs
====

  Id  Name                    Payload                            Payload opts
  --  ----                    -------                            ------------
  0   Exploit: multi/handler  linux/x64/meterpreter/reverse_tcp  tcp://192.168.112.1:4444

msf6 auxiliary(scanner/smb/smb_lookupsid) > jobs -v

Jobs
====

  Id  Name                    Payload                            Payload opts              URIPATH  Start Time                 Handler opts  Persist
  --  ----                    -------                            ------------              -------  ----------                 ------------  -------
  0   Exploit: multi/handler  linux/x64/meterpreter/reverse_tcp  tcp://192.168.112.1:4444           2024-05-17 14:02:58 +0100                true
```

**Comment by sjanusz-r7** [comment]
## Release Notes
Fixed persistent jobs not working when rebooting MSF console.
