### PR TITLE
Deregister PASSWORD_SPRAY option for LoginScanner modules

### LINKED ISSUE #12009: ssh_login scanner not honoring PASSWORD_SPRAY = true
## Steps to reproduce

How'd you do it?

1. Establish meterpreter shell on victim1 for pivoting to victim2
2. Create route in Metasploit to route victim2 traffic through victim1
2.5 use auxiliary/scanner/ssh/ssh_login
3. Set appropriate password/user files and rhosts properties
3. set Verbose true
4. set PASSWORD_SPRAY true
5. set CreateSession false
6. set TRANSITION_DELAY 9
7. run

### Expected Output:
```
[-] 192.168.52.20:22 - Failed: 'User1:password1'
[-] 192.168.52.20:22 - Failed: 'User2:password1'
[-] 192.168.52.20:22 - Failed: 'User3:password1'
[-] 192.168.52.20:22 - Failed: 'User4:password1'
[-] 192.168.52.20:22 - Failed: 'User5:password1'
```

### Actual Output (brief):
```
[-] 192.168.52.20:22 - Failed: 'User1:password1'
[-] 192.168.52.20:22 - Failed: 'User1:password2'
[-] 192.168.52.20:22 - Failed: 'User1:password3'
[-] 192.168.52.20:22 - Failed: 'User1:password4'
[-] 192.168.52.20:22 - Failed: 'User1:password5'
```
### Actual Output (long):
```
msf5 auxiliary(scanner/ssh/ssh_login) > sessions

Active sessions
===============

  Id  Name  Type                   Information                                                   Connection
  --  ----  ----                   -----------                                                   ----------
  1         meterpreter x64/linux  uid=1096, gid=100, euid=1096, egid=100 @ host  192.168.34.53:22 -> 192.168.35.105:37852 (192.168.35.105)

msf5 auxiliary(scanner/ssh/ssh_login) > route

IPv4 Active Routing Table
=========================

   Subnet             Netmask            Gateway
   ------             -------            -------
   192.168.52.0        255.255.255.0      Session 1

[*] There are currently no IPv6 routes defined.
msf5 auxiliary(scanner/ssh/ssh_login) > options

Module options (auxiliary/scanner/ssh/ssh_login):

   Name              Current Setting                               Required  Description
   ----              ---------------                               --------  -----------
   BLANK_PASSWORDS   false                                         no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                                             yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false                                         no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false                                         no        Add all passwords in the current database to the list
   DB_ALL_USERS      false                                         no        Add all users in the current database to the list
   PASSWORD                                                        no        A specific password to authenticate with
   PASS_FILE         /root/loot/passwords.txt                      no        File containing passwords, one per line
   RHOSTS            192.168.52.20                                  yes       The target address range or CIDR identifier
   RPORT             22                                            yes       The target port
   STOP_ON_SUCCESS   false                                         yes       Stop guessing when a credential works for a host
   THREADS           1                                             yes       The number of concurrent threads
   USERNAME                                                        no        A specific username to authenticate as
   USERPASS_FILE                                                   no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      true                                          no        Try the username as the password for all users
   USER_FILE         /root/loot/users.txt                          no        File containing usernames, one per line
   VERBOSE           true                                          yes       Whether to print output for all attempts

msf5 auxiliary(scanner/ssh/ssh_login) > advanced

Module advanced options (auxiliary/scanner/ssh/ssh_login):

   Name                        Current Setting                          Required  Description
   ----                        ---------------                          --------  -----------
   AutoRunScript                                                        no        A script to run automatically on session creation.
   CommandShellCleanupCommand                                           no        A command to run before the session is closed
   CreateSession               false                                    no        Create a new session for every successful login
   InitialAutoRunScript                                                 no        An initial script to run on session creation (before AutoRunScript)
   MaxGuessesPerService        0                                        no        Maximum number of credentials to try per service instance. If set to zero or a non-number, this option will not be used.
   MaxGuessesPerUser           0                                        no         Maximum guesses for a particular username for the service instance. Note that users are considered unique among different services, so a user at 10.1.1.1:22 is different from one at 10.2.2.2:22, and both will be tried up to the MaxGuessesPerUser limit. If set to zero or a non-number, this option will not be used.
   MaxMinutesPerService        0                                        no        Maximum time in minutes to bruteforce the service instance. If set to zero or a non-number, this option will not be used.
   PASSWORD_SPRAY              true                                     yes       Reverse the credential pairing order. For each password, attempt every possible user.
   Proxies                                                              no        A proxy chain of format type:host:port[,type:host:port][...]
   REMOVE_PASS_FILE            false                                    yes       Automatically delete the PASS_FILE on module completion
   REMOVE_USERPASS_FILE        false                                    yes       Automatically delete the USERPASS_FILE on module completion
   REMOVE_USER_FILE            false                                    yes       Automatically delete the USER_FILE on module completion
   SSH_DEBUG                   false                                    no        Enable SSH debugging output (Extreme verbosity!)
   SSH_IDENT                   SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3  yes       SSH client identification string
   SSH_TIMEOUT                 30                                       no        Specify the maximum time to negotiate a SSH session
   ShowProgress                true                                     yes       Display progress messages during a scan
   ShowProgressPercent         10                                       yes       The interval in percent that progress should be shown
   TRANSITION_DELAY            9                                        no        Amount of time (in minutes) to delay before transitioning to the next user in the array (or password when PASSWORD_SPRAY=true)
   WORKSPACE       

msf5 auxiliary(scanner/ssh/ssh_login) > run -j
[*] Auxiliary module running as background job 2.
msf5 auxiliary(scanner/ssh/ssh_login) > 
[-] 192.168.52.20:22 - Could not connect: execution expired
[-] 192.168.52.20:22 - Failed: 'ASxxxxxx:password1'
[-] 192.168.52.20:22 - Failed: 'ASxxxxxx:password2'
[-] 192.168.52.20:22 - Failed: 'ASxxxxxx:password3'
[-] 192.168.52.20:22 - Failed: 'ASxxxxxx:password4'
[-] 192.168.52.20:22 - Failed: 'ASxxxxxx:password5'
[-] 192.168.52.20:22 - Failed: 'ASxxxxxx:password6'
```

### Metasploit version
```
msf5 auxiliary(scanner/ssh/ssh_login) > version
Framework: 5.0.30-dev
Console  : 5.0.30-dev
```

### I installed Metasploit with:
- [X] Kali package via apt

### OS

What OS are you running Metasploit on?
```
root@kali:~# uname -a
Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-5kali1 (2019-06-20) x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by jbarnett-r7**
This PR deregisters the `PASSWORD_SPRAY` option for any scanner modules that use the `LoginScanner.scan!` method to iterate through credentials, which fixes #12009. The `PASSWORD_SPRAY` option was added to the `AuthBrute` module with #9634 so the option is registered anywhere that module is included. Most of the `LoginScanner` modules still include `AuthBrute`, so the option was showing as available even though it was never honored.

The best fix for this would be to port the `PASSWORD_SPRAY` logic over to `LoginScanner`, but that looks to be quite a bit of work. Opting for disabling the option for now in modules where it is not properly honored until that work can be completed.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/ssh/ssh_login` (or any module updated in this PR)
- [ ] `show advanced`
- [ ] Verify the `PASSWORD_SPRAY` option is not displayed

### CODE REVIEW

File: modules/auxiliary/scanner/http/wordpress_xmlrpc_login.rb [hunk 1]
```diff
@@ -38,7 +38,7 @@ def initialize(info = {})
           Opt::RPORT(80),
         ])
 
-    deregister_options('BLANK_PASSWORDS') # we don't need this option
+    deregister_options('BLANK_PASSWORDS', 'PASSWORD_SPRAY') # we don't need these options
```
Comment (wvu-r7) [inline modules/auxiliary/scanner/http/wordpress_xmlrpc_login.rb]: Nice touch!

**Review by wvu — APPROVED** [review]
Code looks good. Giving it a test.

**Comment by wvu-r7** [comment]
```
msf5 auxiliary(scanner/ssh/ssh_login) > grep PASSWORD_SPRAY options
msf5 auxiliary(scanner/ssh/ssh_login) > grep PASSWORD_SPRAY advanced
   TRANSITION_DELAY            0                                        no        Amount of time (in minutes) to delay before transitioning to the next user in the array (or password when PASSWORD_SPRAY=true)
msf5 auxiliary(scanner/ssh/ssh_login) >
```

You may want to deregister related options.

**Comment by jbarnett-r7** [comment]
> You may want to deregister related options

So this option isn't exclusive to password_spray, but it does fall into the exact same issue. It won't be honored unless the `AuthBrute` iterator is used. I'll add this one to the list to just knock it out, too.

**Comment by wvu-r7** [comment]
Oh, you're right. I didn't read #9634 closely enough. Don't bother unless you're feeling ambitious. I'm sure there are others. Removing options one at a time isn't sustainable.

**Review by wvu — APPROVED** [review]

**Comment by wvu-r7** [comment]
# Release Notes

This deregisters the `PASSWORD_SPRAY` option from `LoginScanner` modules, since it is not supported yet.

**Comment by wvu-r7** [comment]
Feel free to do your next pass in a separate PR if you desire. I consider this fixed.

**Comment by day1player** [comment]
Any plans on supporting this in the future? I guess technically the problem is solved but a more desirable solution would be to support the password spray functionality 

https://imgur.com/a/5vNGnzM

**Comment by jbarnett-r7** [comment]
> Any plans on supporting this in the future? I guess technically the problem is solved but a more desirable solution would be to support the password spray functionality
> 
> https://imgur.com/a/5vNGnzM

That is definitely the plan. I spent a couple of hours just trying to plan on how we could port that logic over to `LoginScanner` and couldn't come up with anything that doesn't require a major overhaul (or major hack). It's going to take some planning and work to complete that task and unfortunately I have some higher priority stuff that I have to get done at this time.

If you want to take a stab at it feel free! We'd love the contribution :).
