### PR TITLE
Zeitwerk msf folder

### LINKED ISSUE #14646: tools/exploit/exe2vba.rb:  uninitialized constant Msf::Util::EXE (NameError)
## Steps to reproduce

I tried to package the latest version 6.0.27 for Kali (the package is not in Kali yet)
The package builds fine. We run some basic tests and this one fails:

1. Run ``` msfvenom -p linux/x64/meterpreter/reverse_tcp LPORT=4444 -f exe > reverse.exe```
2. Run ``` msf-exe2vba reverse.exe reverse.vba```

The command fails with the message:
```
Traceback (most recent call last):
/usr/share/metasploit-framework/tools/exploit/exe2vba.rb:45:in `<main>': uninitialized constant Msf::Util::EXE (NameError)
```

## Expected behavior
It should generate a file without error

## Current behavior
The command fails with the message:
```
/usr/share/metasploit-framework/tools/exploit/exe2vba.rb:45:in `<main>': uninitialized constant Msf::Util::EXE (NameError)
```

### Metasploit version
Version 6.0.27

## Additional Information
I think it's related to https://github.com/rapid7/metasploit-framework/commit/bad5ccbc4979fa1d826a1ac2b925d1b519888c0a

Other tools might have similar issue (at least msf-exe2vbs)

### PR DESCRIPTION
**Pull request by dwelch-r7**
Continuation of the zeitwerk initiative we have going on, following on from this pr #14202 and #14584

In this PR we have zeitwerked the `lib/msf/` folder

# Verification steps

- [x] All framework tests pass
- [x] Metasploit Pro tests pass

On Linux
- [ ] Console boots up
- [ ] `search` for and `use` a module
- [ ] Sucessfully run a module
- [ ] Generate a payload with `msfvenom`
- [ ] Gain a meterpreter session

On Osx
- [ ] Console boots up
- [ ] `search` for and `use` a module
- [ ] Sucessfully run a module
- [ ] Generate a payload with `msfvenom`
- [ ] Gain a meterpreter session

On Windows
- [ ] Console boots up
- [ ] `search` for and `use` a module
- [ ] Sucessfully run a module
- [ ] Generate a payload with `msfvenom`
- [ ] Gain a meterpreter session

### CODE REVIEW

File: lib/msf/base.rb [hunk 1]
```diff
@@ -1,5 +1,3 @@
-# -*- coding: binary -*-
```
Comment (adfoster-r7) [inline lib/msf/base.rb:1]: Sanity question, is this needed still?

File: lib/msf/core.rb [hunk 2]
```diff
@@ -1,41 +1,3 @@
-# -*- coding: binary -*-
-###
-#
-# framework-core
-# --------------
-#
-# The core library provides all of the means by which to interact
-# with the framework insofar as manipulating encoders, nops,
-# payloads, exploits, auxiliary, and sessions.
```
Comment (adfoster-r7) [inline lib/msf/core.rb:9]: These comments have been useful in the past, does it make sense to move it elsewhere? 🤔 

Since we plan on deleting this file - I'm not sure where it would live within our code. I've seen some projects have `readme.md` files in directories of interest, which act as a bread crumb trail as to what the folders are meant to do at the conceptual level. I don't believe having it in the wiki is the right solution either, as the documentation being colocated with the folder will be naturally found when code spelunking

This comment applies to the previously deleted [base.rb](https://github.com/rapid7/metasploit-framework/pull/14584/files#diff-465597d29c33980ad890500b385334c1a18a207e48f2e292ceb3540f6b389907) comments too

File: lib/msf/base.rb (hunk 1 above)
Comment (dwelch-r7) [reply lib/msf/base.rb:1]: it shouldn't be, it only seems to affect any strings defined in the file and there aren't any :smile: 
weren't any before so it was probably a copy/paste job

File: lib/metasploit/framework/command/console.rb [hunk 3]
```diff
@@ -57,7 +57,6 @@ def start
   def driver
     unless @driver
       # require here so minimum loading is done before {start} is called.
```
Comment (adfoster-r7) [inline lib/metasploit/framework/command/console.rb:59]: Looks like this is a stray comment now? 👀

File: lib/msf/core.rb (hunk 2 above)
Comment (dwelch-r7) [reply lib/msf/core.rb:9]: Personally I don't see a tonne of value in these comments but I'd definitely be down for the readme idea if we can keep it up to date

File: lib/metasploit/framework/command/console.rb (hunk 3 above)
Comment (dwelch-r7) [reply lib/metasploit/framework/command/console.rb:59]: sorted

File: lib/msf/base.rb (hunk 1 above)
Comment (adfoster-r7) [reply lib/msf/base.rb:1]: That's my understanding too, just calling it out for visibility - as there seemed to be a couple of historical bulk changes to add this to every file:
https://github.com/rapid7/metasploit-framework/commit/d656e3185ff80b7264c30e994b2299a039e907a2

I imagine there was a solid reason for it that, but the commit doesn't have any further details. It could've just been the easiest to automate, adding any missing binary comment regardless of the file's content

**Comment by adfoster-r7** [comment]
Trying to restart msfdb:
```
bundle exec ruby ./msfdb restart
Traceback (most recent call last):
./msfdb:30:in `<main>': uninitialized constant Msf::Config (NameError)
Did you mean?  RbConfig
```
