### PR TITLE
fix migrate by process name

### LINKED ISSUE #8109: post/windows/manage/migrate doesn't migrate to NAME variable; PID works
## Steps to reproduce

How'd you do it?

1. Established windows/meterpreter/reverse_https session against modern.ie Windows 10 (Build 14393) system. Server is Ubuntu 16.04 x64 with MSF (version `4.14.2+20170313172527.git.2.6832f3f~1rapid7-1`) installed via https://github.com/trustedsec/ptf.
2. Attempted to run post/windows/manage/migrate to explorer.exe.
3. Module failed with "Process or PID not found"

More verbose info:
```
meterpreter > sysinfo                                                                                                                     
Computer        : MSEDGEWIN10
OS              : Windows 10 (Build 14393).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x64/windows
meterpreter > getpid                                                                                                                      
Current pid: 4344
meterpreter > ps -S explorer                                                                                                              

Process List
============

 PID   PPID  Name                          Arch  Session  User                Path
 ---   ----  ----                          ----  -------  ----                ----
 1544  2128  explorer.exe                  x64   1        MSEDGEWIN10\IEUser  C:\Windows\explorer.exe

meterpreter > background
[*] Backgrounding session 5...
msf post(migrate) > show options 

Module options (post/windows/manage/migrate):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   KILL     false            no        Kill original process for the session.
   NAME     Explorer.EXE     no        Name of process to migrate to.
   PID                       no        PID of process to migrate to.
   SESSION  5                yes       The session to run this module on.
   SPAWN    false            no        Spawn process to migrate to. If name for process not given notepad.exe is used.

msf post(migrate) > run

[*] Running module against MSEDGEWIN10
[*] Current server process: notepad.exe (4344)
[-] Process or PID not found
[*] Post module execution completed
msf post(migrate) > sessions -i 5
[*] Starting interaction with 5...

meterpreter > irb
[*] Starting IRB shell
[*] The 'client' variable holds the meterpreter client

>> session.sys.process["explorer.exe"]                                                                                                    
=> 1544
>> client.sys.process["explorer.exe"]                                                                                                     
=> 1544
>> 
```

### What should happen?

I'd expect the running meterpreter to search for the Process ID of explorer.exe and migrate there. I'm looking at https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/manage/migrate.rb#L48 to try and see what's going wrong, but given the `irb` output I don't see how this could fail.

### What happens instead?

The module fails to discover explorer.exe's Process ID (for some unknown reason) and fails.

### framework.log output?

```
root@ubuntu:~# find / -name framework.log
/root/.msf4/logs/framework.log
root@ubuntu:~# cat ~/.msf4/logs/framework.log

(no output; I cleared the log just before running post/windows/manage/migrate)
```

### Metasploit version

msf post(migrate) > version
Framework: 4.14.2-dev-437cba84b0563fb067757bb1ec03db9e01ed4579
Console  : 4.14.2-dev-437cba84b0563fb067757bb1ec03db9e01ed4579

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [X] Source install (`ruby --version` shows `ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]`)

### OS

Ubuntu 16.04 x64

### PR DESCRIPTION
**Pull request by rwhitcroft**
Fixes #8109

This fixes the ability to migrate into a process by name (e.g., explorer.exe). The if/else block would never reach the NAME check because `pid != 0` is always true (unless for some reason you specifically set it to 0).

### CODE REVIEW

File: modules/post/windows/manage/migrate.rb [hunk 1]
```diff
@@ -42,7 +42,7 @@ def run
     if datastore['SPAWN']
       print_status("Spawning notepad.exe process to migrate to")
       target_pid = create_temp_proc
-    elsif datastore['PID'] != 0
```
Comment (wvu-r7) [inline modules/post/windows/manage/migrate.rb]: Damn.

Comment (jeffmcjunkin) [inline modules/post/windows/manage/migrate.rb]: Aha! That does make sense, I should've noticed that and mentioned it in #8109. Thanks!

File: modules/post/windows/manage/migrate.rb [hunk 2]
```diff
@@ -23,8 +23,8 @@ def initialize(info={})
     register_options(
       [
         OptBool.new(   'SPAWN',[ false,'Spawn process to migrate to. If name for process not given notepad.exe is used.', true]),
-        OptInt.new(    'PID',  [false, 'PID of process to migrate to.']),
-        OptString.new( 'NAME', [false, 'Name of process to migrate to.']),
+        OptInt.new(    'PID',  [false, 'PID of process to migrate to.', nil]),
```
Comment (wvu-r7) [inline modules/post/windows/manage/migrate.rb]: These should be `nil` by default if none specified.

Comment (rwhitcroft) [inline modules/post/windows/manage/migrate.rb]: They are `nil`!

Comment (wvu-r7) [inline modules/post/windows/manage/migrate.rb]: I mean they're already `nil`.

**Comment by pbarry-r7** [comment]
# Release Notes

This patch fixes broken behavior when attempting progress migration via specified process name under Windows.  A process name specified by the user should now be properly handled.
