### PR TITLE
Fix call to method in null object in rpc_creds method

### LINKED ISSUE #12460: Crash in master/lib/msf/core/rpc/v10/rpc_db.rb
Line 279 in master/lib/msf/core/rpc/v10/rpc_db.rb crashes if the creds database has been populated with an entry that has no private object (e.g., smb or ssh username scanners). In this case, cred.private is null.

Proposed fix:
Replace:

        ret[:creds] << {
                :user => cred.public.username.to_s,
                :pass => cred.private.data.to_s,
                :updated_at => cred.private.updated_at.to_i,
                :type => cred.private.type.to_s,
                :host => host,
                :port => port,
                :proto => proto,
                :sname => sname}
With

        if cred.private.nil?
            ret[:creds] << {
                :user => cred.public.username.to_s,
                :pass => nil,
                :updated_at => nil,
                :type => nil,
                :host => host,
                :port => port,
                :proto => proto,
                :sname => sname}
        else
           ret[:creds] << {
                :user => cred.public.username.to_s,
                :pass => cred.private.data.to_s,
                :updated_at => cred.private.updated_at.to_i,
                :type => cred.private.type.to_s,
                :host => host,
                :port => port,
                :proto => proto,
                :sname => sname}
        end

### PR DESCRIPTION
**Pull request by FenixH**
Fixes #12460 a bug that causes RPC requests for credentials to yield exceptions.

Also two minor fixes to modules:

* autoroute currently prints active routes to standard out instead of through print_status
* web_delivery has incorrect database variable names in run()

## Verification

List the steps needed to make sure this thing works

Start msfrpcd stand-alone or through msfconsole
Run a scanner module that only extracts usernames, e.g., auxiliary/scanner/ssh/ssh_enumusers
Make an RPC-request for database credentials.
Get exception with stack trace pointing to call of method on null object (cred.private is null)

### CODE REVIEW

File: lib/msf/core/rpc/v10/rpc_db.rb [hunk 1]
```diff
@@ -276,15 +276,31 @@ def rpc_creds(xopts)
...
                 :updated_at => cred.private.updated_at.to_i,
                 :type => cred.private.type.to_s,
                 :host => host,
                 :port => port,
                 :proto => proto,
-                :sname => sname}
+                :sname => sname
+            }
+        end
+
```
Comment (jmartin-r7) [inline lib/msf/core/rpc/v10/rpc_db.rb]: consider instead of building two separate maps and having to maintain each

```
current_pass = nil
current_type = nil
unless cred.private.nil?
  current_pass = cred.private.data.to_s
  current_type = cred.private.type.to_s
end

ret[:creds] << {
  :user => cred.public.username.to_s,
  :pass => current_pass,
  :updated_at => cred.public.updated_at.to_i,
  :type => current_type,
  :host => host,
  :port => port,
  :proto => proto,
  :sname => sname
}
```

using ternary operations for the two specific keys would be a common path also
```
:pass => cred.private.nil? ? nil : cred.private.data.to_s
```

File: modules/exploits/multi/script/web_delivery.rb [hunk 2]
```diff
@@ -188,10 +188,10 @@ def gen_psh(url, *method)
       random = "#{rand_text_alphanumeric 8}.exe"
 
       # Set filename (Use random filename if empty)
-      filename = datastore['BinaryEXE-FILENAME'].blank? ? random : datastore['BinaryEXE-FILENAME']
+      filename = datastore['PSHBinary-FILENAME'].blank? ? random : datastore['PSHBinary-FILENAME']
 
       # Set path (Use %TEMP% if empty)
-      path = datastore['BinaryEXE-PATH'].blank? ? "$env:temp" : %Q('#{datastore['BinaryEXE-PATH']}')
+      path = datastore['PSHBinary-PATH'].blank? ? "$env:temp" : %Q('#{datastore['PSHBinary-PATH']}')
```
Comment (jmartin-r7) [inline modules/exploits/multi/script/web_delivery.rb]: Good catch! 👍

**Review by jmartin-tech — COMMENTED** [review]
Reasonable as is, I noted style preference that is just personal opinion and not required.

File: modules/exploits/multi/script/web_delivery.rb (hunk 2 above)
Comment (FenixH) [reply modules/exploits/multi/script/web_delivery.rb]: I agree with you. Out of the two alternate styles you present, I would prefer the first as it only requires a single flow check. I can make this change on Monday if you wish.

**Comment by busterb** [comment]
## Release Notes

This corrects an error in the credentials RPC command to avoid a Nil object dereference. It also fixes some minor bugs in the autoroute and web_delivery modules.
