### PR TITLE
Check that ctx[1] has a datastore attribute

### LINKED ISSUE #13593: Undefined method when killing auxiliary module jobs by ID
## Steps to reproduce

There appears to be an issue when trying to kill a job by it's ID. I can reliably reproduce it but only for auxiliary modules (sock4a and socks5) while others like exploit/multi/handler can be killed by it's ID.

To reproduce it:
1. Start `msfconsole`
1. Start an auxiliary server module
1. Find it's job ID with the output of `jobs`
1. Try to kill the specific job using either `jobs -k <ID>` or `kill <ID>`, both are exhibiting the same behavior

```
./msfconsole -r test.rc
                                                  

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMM                MMMMMMMMMM
MMMN$                           vMMMM
MMMNl  MMMMM             MMMMM  JMMMM
MMMNl  MMMMMMMN       NMMMMMMM  JMMMM
MMMNl  MMMMMMMMMNmmmNMMMMMMMMM  JMMMM
MMMNI  MMMMMMMMMMMMMMMMMMMMMMM  jMMMM
MMMNI  MMMMMMMMMMMMMMMMMMMMMMM  jMMMM
MMMNI  MMMMM   MMMMMMM   MMMMM  jMMMM
MMMNI  MMMMM   MMMMMMM   MMMMM  jMMMM
MMMNI  MMMNM   MMMMMMM   MMMMM  jMMMM
MMMNI  WMMMM   MMMMMMM   MMMM#  JMMMM
MMMMR  ?MMNM             MMMMM .dMMMM
MMMMNm `?MMM             MMMM` dMMMMM
MMMMMMN  ?MM             MM?  NMMMMMN
MMMMMMMMNe                 JMMMMMNMMM
MMMMMMMMMMNm,            eMMMMMNMMNMM
MMMMNNMNMMMMMNx        MMMMMMNMMNMMNM
MMMMMMMMNMMNMMMMm+..+MMNMMNMNMMNMMNMM
        https://metasploit.com


       =[ metasploit v5.0.93-dev-fa496b9395               ]
+ -- --=[ 2028 exploits - 1102 auxiliary - 344 post       ]
+ -- --=[ 562 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 7 evasion                                       ]

Metasploit tip: View missing module options with show missing

[*] Processing test.rc for ERB directives.
resource (test.rc)> use auxiliary/server/socks5
resource (test.rc)> run
[*] Auxiliary module running as background job 0.
resource (test.rc)> jobs

Jobs
====

  Id  Name                      Payload  Payload opts
  --  ----                      -------  ------------
  0   Auxiliary: server/socks5           

resource (test.rc)> sleep 5
[*] Starting the socks5 proxy server
resource (test.rc)> jobs -k 0
[*] Stopping the following job(s): 0
[-] Error while running command jobs: undefined method `datastore' for "37VaPVkhTwWsoZEY7T3B3LD0":String

Call stack:
/home/smcintyre/Repositories/metasploit-framework/lib/msf/ui/console/command_dispatcher/jobs.rb:216:in `block in cmd_jobs'
/home/smcintyre/Repositories/metasploit-framework/lib/msf/ui/console/command_dispatcher/jobs.rb:213:in `each'
/home/smcintyre/Repositories/metasploit-framework/lib/msf/ui/console/command_dispatcher/jobs.rb:213:in `cmd_jobs'
/home/smcintyre/Repositories/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/home/smcintyre/Repositories/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/home/smcintyre/Repositories/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/home/smcintyre/Repositories/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/home/smcintyre/Repositories/metasploit-framework/lib/rex/ui/text/resource.rb:70:in `load_resource'
/home/smcintyre/Repositories/metasploit-framework/lib/msf/ui/console/driver.rb:181:in `block in initialize'
/home/smcintyre/Repositories/metasploit-framework/lib/msf/ui/console/driver.rb:180:in `each'
/home/smcintyre/Repositories/metasploit-framework/lib/msf/ui/console/driver.rb:180:in `initialize'
/home/smcintyre/Repositories/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
/home/smcintyre/Repositories/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
/home/smcintyre/Repositories/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/smcintyre/Repositories/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
resource (test.rc)> exit
[*] Starting persistent handler(s)...
[*] Stopping the socks5 proxy server
```

<details>
<summary>RC Script</summary>

```
use auxiliary/server/socks5
run
jobs
sleep 5
jobs -k 0
exit
```
</details>

## Expected behavior

The job whose ID is specified should be killed.

## Current behavior

Metasploit is throwing a stack trace and not killing the job.

### Metasploit version

`fa496b939550a5b04dbe19df9f47d16eebc08d40 (HEAD -> master, upstream/master) automatic module_metadata_base.json update`g

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (Ruby 2.6.6 via RVM)

### OS

Fedora 32 x64

### PR DESCRIPTION
**Pull request by zeroSteiner**
Fixes #13593

So there's a bug that occurs when a user tries to kill a job by ID when that job is a running auxiliary module (like any of the servers). The issue appears to be due to the `job.ctx` attribute being an array where the second element is either a payload instance<sup>[1](https://github.com/rapid7/metasploit-framework/blob/71af59af8e1a46f6183b72b22fd6bf658cd5bd5f/lib/msf/core/exploit_driver.rb#L166)</sup>, <sup>[2](https://github.com/rapid7/metasploit-framework/blob/71af59af8e1a46f6183b72b22fd6bf658cd5bd5f/lib/msf/core/exploit_driver.rb#L148)</sup> or a run UUID<sup>[3](https://github.com/rapid7/metasploit-framework/blob/71af59af8e1a46f6183b72b22fd6bf658cd5bd5f/lib/msf/base/simple/auxiliary.rb#L73)</sup>, <sup>[4](https://github.com/rapid7/metasploit-framework/blob/71af59af8e1a46f6183b72b22fd6bf658cd5bd5f/lib/msf/base/simple/exploit.rb#L194)</sup>. In the event that its a run UUID, it's a string which means it does not have a `datastore` attribute which is what is causing the original error.

This is a total hack. I think a more elegant solution would be to replace the array with a hash that could define `payload`, `run_uuid` keys etc, but I'm concerned there may be implications with that approach which would affect the RPC layer.

Testing this can be done using the reproduction steps from the ticket #13593. 

1. Copy the contents of the RC script to `test.rc`
1. Run `./msfconsole -r test.rc`
1. See that the job was stopped
1. Do not see a stack trace

<details>
<summary>RC Script</summary>

```
use auxiliary/server/socks5
run
jobs
sleep 5
jobs -k 0
exit
```
</details>

### CODE REVIEW

**Review by acammack-r7 — APPROVED** [review]
Nice catch, I had no idea that `ctx` was spaghettified into here.

File: lib/msf/ui/console/command_dispatcher/jobs.rb [hunk 1]
```diff
@@ -212,8 +212,9 @@ def cmd_jobs(*args)
               # Remove persistence by job id.
               job_list.map(&:to_s).each do |job|
                 if framework.jobs.key?(job)
-                  next unless framework.jobs[job.to_s].ctx[1] # next if no payload context in the job
-                  payload_option = framework.jobs[job.to_s].ctx[1].datastore
+                  ctx_1 = framework.jobs[job.to_s].ctx[1]
+                  next if ctx_1.nil? || !ctx_1.respond_to?(:datastore)  # next if no payload context in the job
+                  payload_option = ctx_1.datastore
```
Comment (adfoster-r7) [inline lib/msf/ui/console/command_dispatcher/jobs.rb:217]: It turns out that the context is an untyped array, in certain scenarios it's a string:

```
lib/msf/base/simple/auxiliary.rb
73:    ctx = [mod, run_uuid, job_listener]
126:    ctx = [mod, run_uuid, job_listener]

lib/msf/base/simple/exploit.rb
194:    ctx = [mod, run_uuid, job_listener]
```

But I’m guessing this is the scenario the original code was meant to cover the scenario of the ctx being a payload:

```
lib/msf/core/exploit_driver.rb
148:      ctx = [ e, p ]
166:      ctx = [ exploit, payload ]

lib/msf/core/evasion_driver.rb
89:    ctx = [ evasion, payload ]
```

**Review by adfoster-r7 — APPROVED** [review]

**Comment by adfoster-r7** [comment]
## Release notes

Fixes a bug that stopped users from killing a job by ID when that job was a running auxiliary module - like any of the servers, or a module running in the context of a job.
