### PR TITLE
Remove Regex Lookup on Username and Password Fields for Creds

### LINKED ISSUE #11555: ssh_login_pubkey database error for failed login
## Steps to reproduce

How'd you do it?

```
msf5 > use auxiliary/scanner/ssh/ssh_login_pubkey
msf5 auxiliary(scanner/ssh/ssh_login_pubkey) > set KEY_PATH ~/REMOVED/ubuntu_id_rsa
KEY_PATH => ~/REMOVED/ubuntu_id_rsa
msf5 auxiliary(scanner/ssh/ssh_login_pubkey) > set USERNAME ubuntu
USERNAME => ubuntu
msf5 auxiliary(scanner/ssh/ssh_login_pubkey) > set RHOSTS 10.10.10.10/24
RHOSTS => 10.10.10.10/24
msf5 auxiliary(scanner/ssh/ssh_login_pubkey) > run
```

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Expected behavior
Log/print failed login and continue to next host in RHOSTS

## Current behavior

What happens instead?

stops the RHOSTS flow, displays database error - valid logins are still logged correctly 

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

```
[-] Auxiliary failed: RuntimeError Problem invalidating login: PG::InvalidRegularExpression: ERROR:  invalid regular expression: quantifier operand invalid
: SELECT  DISTINCT "metasploit_credential_cores"."id", "metasploit_credential_cores"."id" AS alias_0 FROM "metasploit_credential_cores" LEFT OUTER JOIN "metasploit_credential_privates" ON "metasploit_credential_privates"."id" = "metasploit_credential_cores"."private_id" LEFT OUTER JOIN "metasploit_credential_publics" ON "metasploit_credential_publics"."id" = "metasploit_credential_cores"."public_id" LEFT OUTER JOIN "metasploit_credential_logins" ON "metasploit_credential_logins"."core_id" = "metasploit_credential_cores"."id" LEFT OUTER JOIN "services" ON "services"."id" = "metasploit_credential_logins"."service_id" LEFT OUTER JOIN "hosts" ON "hosts"."id" = "services"."host_id" LEFT OUTER JOIN "metasploit_credential_realms" ON "metasploit_credential_realms"."id" = "metasploit_credential_cores"."realm_id" WHERE "metasploit_credential_cores"."workspace_id" = $1 AND "services"."name" IN ('ssh') AND "services"."port" IN (22) AND ("metasploit_credential_publics"."username" ~* '^ubuntu$') AND ("metasploit_credential_privates"."data" ~* '^-----BEGIN RSA PRIVATE KEY-----
REMOVED
-----END RSA PRIVATE KEY-----
$') AND ("metasploit_credential_logins"."id" IS NOT NULL)  ORDER BY "metasploit_credential_cores"."id" ASC LIMIT 1. See log for more details.
[-] Call stack:
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:174:in `log_error'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/lib/metasploit/framework/data_service/proxy/login_data_proxy.rb:55:in `rescue in invalidate_login'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/lib/metasploit/framework/data_service/proxy/login_data_proxy.rb:32:in `invalidate_login'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/lib/msf/core/auxiliary/report.rb:58:in `invalidate_login'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:168:in `block in run_host'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:234:in `block in scan!'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:179:in `block in each_credential'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:232:in `block in each'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:239:in `block in each_key'
[-]   /Users/donthackmebro/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/set.rb:338:in `each_key'
[-]   /Users/donthackmebro/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/set.rb:338:in `each'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:238:in `each_key'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:231:in `each'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb:141:in `run_host'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:111:in `block (2 levels) in run'
[-]   /Users/donthackmebro/Documents/pentest/metasploit-framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
[*] Auxiliary module execution completed
```

## System stuff

ruby-2.5.3 [ x86_64 ]

postgres (PostgreSQL) 11.1 . installed via homebrew

### Metasploit version

Framework: 5.0.11-dev-996c406e71
Console  : 5.0.11-dev-996c406e71

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [X ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
OSX
10.13.3

I did try reinitializing the database and had the same problem

### PR DESCRIPTION
**Pull request by jbarnett-r7**
This PR removes the regex search that was present for the username and password fields for credentials. It fixes #11555. Since usernames, and more commonly passwords, often contain special characters there would frequently be errors due to collisions with reserved regex characters.

Here are some examples of the new functionality:

```
msf5 auxiliary(scanner/ssh/ssh_login_pubkey) > creds -u admin
Credentials
===========

host  origin  service  public  private      realm  private_type  JtR Format
----  ------  -------  ------  -------      -----  ------------  ----------
                       admin   password123         Password      
                       admin   pass123             Password      


```

```
msf5 > creds -P pass
Credentials
===========

host  origin  service  public  private  realm  private_type  JtR Format
----  ------  -------  ------  -------  -----  ------------  ----------

```

The `-S` option is intended to be used for doing regex lookups:

```
msf5 auxiliary(scanner/ssh/ssh_login_pubkey) > creds -S admin
Credentials
===========

host  origin  service  public         private      realm  private_type  JtR Format
----  ------  -------  ------         -------      -----  ------------  ----------
                       administrator  password123         Password      
                       admin          password123         Password      
                       admin          pass123             Password   
```

```
msf5 > creds -S pass
Credentials
===========

host  origin  service  public         private                  realm  private_type    JtR Format
----  ------  -------  ------         -------                  -----  ------------    ----------
                       administrator  password123                     Password        
                       admin          password123                     Password        
                       admin          pass123                         Password        
                       test           [(password!@#$%^&*-`~)]         Password     
```
## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Add some credentials using the syntax suggested via `creds -h`
- [ ] Do a lookup on username with `creds -u <username>`. It should only return results that exactly match the text
- [ ] Do a lookup on password with `creds -P <password>`. It should only return results that exactly match the text
- [ ] Do a regex search with `creds -S <regex>`. It should return any results that match the regex'

Test with a login scanner:
- [ ] `use auxiliary/scanner/ssh/ssh_login`
- [ ] `set RHOSTS <host>`
- [ ] `set USERNAME admin`
- [ ] `set PASSWORD foo)bar`
- [ ] `run`

### CODE REVIEW

File: lib/msf/core/db_manager/cred.rb [hunk 1]
```diff
@@ -29,12 +29,12 @@ def creds(opts)
 
       if opts[:user].present?
         # If we have a user regex, only include those that match
```
Comment (wvu-r7) [inline lib/msf/core/db_manager/cred.rb]: Can you update the comments?

**Review by wvu — CHANGES_REQUESTED** [review]

File: lib/msf/core/db_manager/cred.rb (hunk 1 above)
Comment (jbarnett-r7) [reply lib/msf/core/db_manager/cred.rb]: Done.

**Review by wvu — APPROVED** [review]
LGTM.

**Comment by mkienow-r7** [comment]
These changes conflict with the [`LoginDataProxy#invalidate_login`](https://github.com/rapid7/metasploit-framework/blob/fd3ece3f9b4f1e0087f8a7835b2a5b3bbfe1f956/lib/metasploit/framework/data_service/proxy/login_data_proxy.rb#L40-L41) method as it provides regex for the user and pass.

**Comment by wvu-r7** [comment]
# Release Notes

> This PR removes the regex search that was present for the username and password fields for credentials. It fixes #11555. Since usernames, and more commonly passwords, often contain special characters there would frequently be errors due to collisions with reserved regex characters.
