### PR TITLE
Fixes meterpreter tab completion issues

### LINKED ISSUE #14502: Tab Completion Within Meterpreter Causes a Stack Trace if No Results are Returned
## Steps to reproduce

```
meterpreter > dir C:\ProgramData\Microsoft\Windows
[-] 1016: Operation failed: The system cannot find the file specified.
meterpreter > dir "C:\ProgramData\Microsoft\Windows"
Listing: C:\ProgramData\Microsoft\Windows
=========================================

Mode              Size    Type  Last modified              Name
----              ----    ----  -------------              ----
40777/rwxrwxrwx   163840  dir   2019-12-07 03:14:52 -0600  AppRepository
100666/rw-rw-rw-  20283   fil   2019-12-07 03:54:38 -0600  AppxProvisioning.xml
40777/rwxrwxrwx   4096    dir   2020-06-18 12:11:05 -0500  Caches
40777/rwxrwxrwx   4096    dir   2019-12-07 03:14:52 -0600  ClipSVC
40777/rwxrwxrwx   4096    dir   2020-06-18 10:23:20 -0500  DeviceMetadataCache
40777/rwxrwxrwx   0       dir   2019-12-07 03:14:52 -0600  DeviceMetadataStore
40777/rwxrwxrwx   0       dir   2019-12-07 03:14:52 -0600  GameExplorer
40777/rwxrwxrwx   0       dir   2019-12-07 03:14:52 -0600  LfSvc
40777/rwxrwxrwx   0       dir   2019-12-07 03:14:52 -0600  Models
40777/rwxrwxrwx   4096    dir   2019-12-07 03:14:52 -0600  OneSettings
40777/rwxrwxrwx   0       dir   2019-12-07 03:14:52 -0600  PackagedEventProviders
40777/rwxrwxrwx   0       dir   2019-12-07 03:14:52 -0600  Parental Controls
40777/rwxrwxrwx   8192    dir   2019-12-07 03:14:52 -0600  Power Efficiency Diagnostics
40777/rwxrwxrwx   0       dir   2019-12-07 03:14:52 -0600  Ringtones
40777/rwxrwxrwx   0       dir   2020-10-30 17:03:22 -0500  Sqm
40555/r-xr-xr-x   0       dir   2019-12-07 03:14:52 -0600  Start Menu
40777/rwxrwxrwx   0       dir   2020-11-02 10:53:00 -0600  SystemData
40777/rwxrwxrwx   0       dir   2019-12-07 03:14:52 -0600  Templates
40777/rwxrwxrwx   0       dir   2019-12-07 03:14:52 -0600  WER
100777/rwxrwxrwx  27648   fil   2020-12-11 13:49:14 -0600  test33.exe
40777/rwxrwxrwx   0       dir   2019-12-07 03:14:52 -0600  wfp

meterpreter > del "C:\Pro[-] Session manipulation failed: no implicit conversion of nil into String ["/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:648:in `block in shellsplitex'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:636:in `scan'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:636:in `shellsplitex'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:367:in `tab_complete'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:69:in `block in init_tab_complete'", "/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/readline.rb:136:in `readline_attempted_completion_function'", "/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6329:in `gen_completion_matches'", "/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6813:in `rl_complete_internal'", "/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:6903:in `rl_complete'", "/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4374:in `_rl_dispatch_subseq'", "/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4363:in `_rl_dispatch'", "/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4779:in `readline_internal_charloop'", "/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4853:in `readline_internal'", "/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rb-readline-0.5.5/lib/rbreadline.rb:4875:in `readline'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/input/readline.rb:162:in `readline_with_output'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/input/readline.rb:100:in `pgets'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:321:in `get_input_line'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:141:in `run'", "/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'", "/home/gwillcox/git/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:583:in `_interact'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/interactive.rb:51:in `interact'", "/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1572:in `cmd_sessions'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'", "/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'", "/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'", "/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'", "./msfconsole:23:in `<main>'"]
msf6 post(windows/manage/execute_dotnet_assembly) > 
```

## Were you following a specific guide/tutorial or reading documentation?

Nope just testing out a new module I'm researching.

## Expected behavior

We should autocomplete if possible. If no results are returned, then no autocomplete options should be displayed.

## Current behavior

Meterpreter throws a stack trace on a `nil` exception.

### Metasploit version

msf6 post(windows/manage/execute_dotnet_assembly) > version
Framework: 6.0.22-dev-8aaae387ea
Console  : 6.0.22-dev-8aaae387ea
msf6 post(windows/manage/execute_dotnet_assembly) >

### PR DESCRIPTION
**Pull request by cgranleese-r7**
This PR resolves  #14502.

Previously when attempting to tab complete within meterpreter, a stack trace with a nil exception would be returned if the user didn't add end quotes to the string they were attempting to tab complete.
### Examples:
This would have returned a a stack trace with a nil exception.
```Bash
dir "C:\Pro<tab>
```
Whereas, this wouldn't have caused a crash, but didn't tab complete either.
```Bash
dir "C:\Pro<tab>"
```

With this fix, users should now be able to tab complete with meterpreter. 
meterpreter_autocomplete_fix

### Tests
This PR also adds tests  verify the regex within `shellsplitex` correctly returns correct values in various situations.

## Side note
The only issue I have encountered and may need to be fixed before merging this PR or maybe create a new ticket for, is when you tab complete it will add the end quote and add a whitespace to the command line (this can be seen in the gif above). This leaves your cursor two spaces away from the string if you wanted to continue tab completing that existing string.
I believe I encountered something similar in a previous tab completion ticket I worked on, so I plan to look into that and see if I can come up with anything.

### Payload and handler setup
image

- [ ] Gain a meterpreter session
- [ ] Try tab completing e.g. `dir "C:\Pro<tab>`
- [ ] **Verify** it no longer returns a stack trace with a nil exception
- [ ] **Verify** it will now tab complete

### CODE REVIEW

File: lib/rex/ui/text/dispatcher_shell.rb [hunk 1]
```diff
@@ -422,13 +422,17 @@ def tab_complete_stub(str, quote: nil)
...
-      Regexp.compile(str,Regexp::IGNORECASE)
-    rescue RegexpError
-      str = Regexp.escape(str)
+    # Convert into a case-insensitive regex
+    utf8_buf = str.dup.force_encoding('UTF-8')
+    if utf8_buf.valid_encoding?
+      Regexp.new(Regexp.escape(utf8_buf), Regexp::IGNORECASE)
+    else
+      # If the encoding is invalid, default to a regex that matches anything
+      //
```
Comment (adfoster-r7) [inline lib/rex/ui/text/dispatcher_shell.rb:431]: This will need an extra eye to understand what it was doing previously, and why it's no longer the same code 👀 

The encoding part is the essence of what I believe is needed to solve your original crash, but not the entire code block*

File: lib/rex/ui/text/dispatcher_shell.rb [hunk 2]
```diff
@@ -650,7 +654,14 @@ def shellsplitex(line)
     quote = nil
```
Comment (adfoster-r7) [inline lib/rex/ui/text/dispatcher_shell.rb:654]: What are your thoughts on updating the method comment above with a link to were this code was originally taken from? 👀

File: lib/rex/ui/text/dispatcher_shell.rb (hunk 1 above)
Comment (cgranleese-r7) [reply lib/rex/ui/text/dispatcher_shell.rb:431]: Ok, I'll take another look into this.

File: lib/rex/ui/text/dispatcher_shell.rb (hunk 2 above)
Comment (cgranleese-r7) [reply lib/rex/ui/text/dispatcher_shell.rb:654]: Yea, I think that would be a good idea 👍

File: spec/lib/msf/ui/text/dispatcher_shell_spec.rb [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  describe '#shellsplitex' do
+    [
+      { input: "dir", expected: { quote: nil, words: ["dir"] } },
+      { input: "dir \"/\"", expected: {:quote=>nil, :words=>["dir", "/"]} },
+      { input: "dir \"/", expected: {:quote=>"\"", :words=>["dir", "/"]} },
+      { input: "dir \"C:\\Pro\"", expected: {:quote=>nil, :words=>["dir", "C:\\Pro"]} },
+      { input: "dir \'C:\\Pro\'", expected: {:quote=>nil, :words=>["dir", "C:\\Pro"]} },
+      { input: "dir \'C:\\ProgramData\\jim\\bob.rb\'", expected: {:quote=>nil, :words=>["dir", "C:\\ProgramData\\jim\\bob.rb"]} },
+      { input: "dir \'C:\\ProgramData\\jim\\\'", expected: {:quote=>nil, :words=>["dir", "C:\\ProgramData\\jim\\"]} },
+      { input: "dir \"C:\\Pro", expected: { quote: "\"", words: ["dir", "C:\\Pro"] } }
```
Comment (adfoster-r7) [inline spec/lib/msf/ui/text/dispatcher_shell_spec.rb:22]: Might be worth adding tests for scenarios with lots of whitespaces? 👀 

```
dir       'C:/....[whitespace here]      
```

etc

File: lib/rex/ui/text/dispatcher_shell.rb [hunk 4]
```diff
@@ -422,13 +422,17 @@ def tab_complete_stub(str, quote: nil)
...
 
-    # Verify that our search string is a valid regex
-    begin
-      Regexp.compile(str,Regexp::IGNORECASE)
-    rescue RegexpError
-      str = Regexp.escape(str)
+    # Convert into a case-insensitive regex
+    utf8_buf = str.dup.force_encoding('UTF-8')
+    if utf8_buf.valid_encoding?
+      Regexp.new(Regexp.escape(utf8_buf), Regexp::IGNORECASE)
```
Comment (adfoster-r7) [inline lib/rex/ui/text/dispatcher_shell.rb:428]:
```suggestion
      Regexp.new(utf8_buf, Regexp::IGNORECASE)
```

File: spec/lib/msf/ui/text/dispatcher_shell_spec.rb (hunk 3 above)
Comment (cgranleese-r7) [reply spec/lib/msf/ui/text/dispatcher_shell_spec.rb]: Got some tests added for that.

File: lib/rex/ui/text/dispatcher_shell.rb [hunk 5]
```diff
@@ -422,12 +422,7 @@ def tab_complete_stub(str, quote: nil)
       end
     }
 
-    # Verify that our search string is a valid regex
-    begin
-      Regexp.compile(str,Regexp::IGNORECASE)
-    rescue RegexpError
-      str = Regexp.escape(str)
-    end
```
Comment (adfoster-r7) [inline lib/rex/ui/text/dispatcher_shell.rb:430]: @cgranleese-r7 What was this old code doing? Why is it no longer needed? 👀

File: lib/rex/ui/text/dispatcher_shell.rb [hunk 6]
```diff
@@ -646,11 +641,35 @@ def unblock_command(cmd)
   # ArgumentError on unbalanced quotes return the remainder of the string as if
   # the last character were the closing quote.
   #
+  # This code was originally taken from Shellwords#shellsplit
```
Comment (adfoster-r7) [inline lib/rex/ui/text/dispatcher_shell.rb:644]: Probably worth a github link to the exact sha that this was using 👀

File: lib/rex/ui/text/dispatcher_shell.rb (hunk 5 above)
Comment (cgranleese-r7) [reply lib/rex/ui/text/dispatcher_shell.rb:430]: So Dean and I look at this and the code you're referring to was giving the unicode error due to not being escaped correctly before being compiled, we also looked into using `Regexp.new` but from what we understood it was basically the same as running `Rexexp.compile`. 

Unicode error:
```
warning: invalid Unicode Property \P: /C:\Pro/
```

So I had got to a point were I had this code:
```Ruby
 Regexp.new(Regexp.escape(utf8_buf), Regexp::IGNORECASE)
```

But when looking into it, the code above was not escaping the special characters. 

`Regexp.new(Regexp.escape(utf8_buf), Regexp::IGNORECASE)` output
```Ruby
/C:\\Pro/i
```

`str = Regexp.escape(str)` output
```Ruby
"C:\\\\Pro"
```

When testing it the previously code was returning the unicode error every-time, but if you called escape within the params of `Regexp.new` it didn't escape the string correctly, so we landed on this.

File: lib/rex/ui/text/dispatcher_shell.rb (hunk 6 above)
Comment (cgranleese-r7) [reply lib/rex/ui/text/dispatcher_shell.rb]: Got a link to that method in the Ruby repo added in 👍

File: lib/rex/ui/text/dispatcher_shell.rb (hunk 5 above)
Comment (adfoster-r7) [reply lib/rex/ui/text/dispatcher_shell.rb:430]: @cgranleese-r7 That's the warning you were running into, but what was this code previously doing? Is it safe to delete? Are we losing functionality by deleting this? 👀

Comment (adfoster-r7) [reply lib/rex/ui/text/dispatcher_shell.rb:430]: For instance, try this tab completion against master: `use .*sharepoint.*xoml<tab>` and compare it to the results of your branch

Comment (cgranleese-r7) [reply lib/rex/ui/text/dispatcher_shell.rb:430]: @adfoster-r7 Ah ok, yea that no longer allows tab completion on my branch. Ok, I'll take another look at this then and see what I can come up with.

Thanks for looking at that and giving me a lead on where to start, appreciate it 👍

File: lib/rex/ui/text/dispatcher_shell.rb [hunk 7]
```diff
@@ -422,12 +422,7 @@ def tab_complete_stub(str, quote: nil)
...
-    # Verify that our search string is a valid regex
-    begin
-      Regexp.compile(str,Regexp::IGNORECASE)
-    rescue RegexpError
-      str = Regexp.escape(str)
-    end
+    str = Regexp.escape(str)
 
     # @todo - This still doesn't fix some Regexp warnings:
     # ./lib/rex/ui/text/dispatcher_shell.rb:171: warning: regexp has `]' without escape
```
Comment (adfoster-r7) [inline lib/rex/ui/text/dispatcher_shell.rb:428]: I just realised what this comment now means:
```ruby
2.7.2 :020 > Regexp.compile('testing]', Regexp::IGNORECASE)
(irb):20: warning: regular expression has ']' without escape: /testing]/
 => /testing]/i 
```

It's roughly the same warning that you're getting with the `\P` in `C:\Pro`:
```ruby
2.7.2 :007 > Regexp.compile('C:\Pro', Regexp::IGNORECASE)
(irb):7: warning: invalid Unicode Property \P: /C:\Pro/
 => /C:\Pro/i 
2.7.2 :008 > Regexp.compile('\P', Regexp::IGNORECASE)
(irb):8: warning: invalid Unicode Property \P: /\P/
 => /\P/i 
```

Comment (adfoster-r7) [reply lib/rex/ui/text/dispatcher_shell.rb:428]: As discussed, let's delete this functionality and keep to just the `word.downcase.start_with?` functionality

```diff
-      word.downcase.start_with?(str.downcase) || word =~ /^#{str}/i
+      word.downcase.start_with?(str.downcase)
```

Comment (cgranleese-r7) [reply lib/rex/ui/text/dispatcher_shell.rb]: Got those changes added

File: lib/rex/ui/text/dispatcher_shell.rb (hunk 5 above)
Comment (adfoster-r7) [reply lib/rex/ui/text/dispatcher_shell.rb:430]: Threading the other conversation where we looked more into the problems with turning arbitrary text into regex:

https://github.com/rapid7/metasploit-framework/pull/15050#discussion_r616562443

**Comment by adfoster-r7** [comment]
@cgranleese-r7 Looks like this still has the reverse shell binary in it. Could we delete that and squash these commits? 🎉

**Comment by cgranleese-r7** [comment]
> @cgranleese-r7 Looks like this still has the reverse shell binary in it. Could we delete that and squash these commits? 🎉

Yea, sorry about that. I had it in my notes to remove it, but it clearly slipped my mind :upside_down_face:

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes a crash in Metasploit's console when the user to to tab complete values such as file paths that were missing their final ending quote

**Comment by gwillcox-r7** [comment]
Thanks for fixing this @cgranleese-r7 and thanks for testing @adfoster-r7 :)

File: lib/rex/ui/text/dispatcher_shell.rb [hunk 8]
```diff
@@ -422,19 +422,9 @@ def tab_complete_stub(str, quote: nil)
...
-      str = Regexp.escape(str)
-    end
-
-    # @todo - This still doesn't fix some Regexp warnings:
-    # ./lib/rex/ui/text/dispatcher_shell.rb:171: warning: regexp has `]' without escape
-
     # Match based on the partial word
     items.find_all { |word|
-      word.downcase.start_with?(str.downcase) || word =~ /^#{str}/i
+      word.downcase.start_with?(str.downcase)
```
Comment (adfoster-r7) [inline lib/rex/ui/text/dispatcher_shell.rb:427]: One last bread crumb trail for why this was deleted; It was thought that the old regex approach for finding strings that start with search term was a left over perl-ism, and `word.downcase.start_with?(str.downcase)` is now being used as the preferred Ruby pattern. If there's community raised issues that this breaks workflows, we can re-evaluate it in the future :+1:

File: lib/rex/ui/text/dispatcher_shell.rb (hunk 5 above)
Comment (wvu-r7) [reply lib/rex/ui/text/dispatcher_shell.rb:430]: For the record, @adfoster-r7 and I discussed this implementation last year. You're safe to remove it. It's ancient, only a small handful of people know about it, and even fewer use it. No one will miss it, especially if it causes bugs.
