### PR TITLE
when datastore options are merged, also merge the alias and imported* hashes

### LINKED ISSUE #9879: Linux meterpreter payload to_handler fails with invalid opcode arguments error
## Steps to reproduce

The `linux/x64/meterpreter/reverse_tcp` payload fails to start a handler when issued the `to_handler` command. The exception it throws is `invalid opcode arguments` (see below). The output then (incorrectly) states that a job has been started.

Reproduce with the following steps
- Start msfconsole
- `use payload/linux/x64/meterpreter/reverse_tcp`
- `set LHOST x.x.x.x`
- `to_handler`

## Expected behavior

The `to_handler` command should start a handler for the specified payload.

## Current behavior

```
metasploit-framework (S:0 J:1) payload(python/meterpreter/reverse_tcp) > use payload/linux/x64/meterpreter/reverse_tcp
metasploit-framework (S:0 J:1) payload(linux/x64/meterpreter/reverse_tcp) > show options 

Module options (payload/linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address
   LPORT  4444             yes       The listen port

metasploit-framework (S:0 J:1) payload(linux/x64/meterpreter/reverse_tcp) > set LHOST 192.168.254.130 
LHOST => 192.168.254.130
metasploit-framework (S:0 J:1) payload(linux/x64/meterpreter/reverse_tcp) > to_handler 

[-] [2018.04.14-17:59:58] Exploit failed: invalid opcode arguments "push", allowed : [[:reg], [:modrm], [:i], [:i8], [:seg3A]] near "push" at "\"<unk>\"" line 17
[*] Payload Handler Started as Job 
metasploit-framework (S:0 J:1) payload(linux/x64/meterpreter/reverse_tcp) >
```
### Metasploit version

Commit 47a324815d57d11989d2bbf5d0704e3bb096f3cb.

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [X] Source install (Ruby version 2.5.1)

### OS

Fedora 27 x64

### PR DESCRIPTION
**Pull request by busterb**
This fixes #9879 by using the same datastore option for retries for x86 and x64 linux stagers.

~(why we have both 'ReverseConnectRetries' and 'StagerRetryCount' sees to be the left hand not agreeing with the right hand, which an intrepid fellow could fix with parameter aliases at some point after this PR).~

The core problem here wasn't that the stagers weren't using the same option. We had addressed that earlier by adding aliases to the datastore for specifically this `ReverseConnectRetries` vs `StagerRetryCount` issue. The problem was that when two datastores are merged, the aliases from the right-hand datastore did not copy to the left-hand. When `to_handler` is invoked, it calls merge! which killed the aliases for the payload datastore. Had we merged the opposite direction, it would have worked. Stagers that had fallback code when the datastore option wasn't set were silently falling-back to their hardcoded options on merge.

This also adds some missing accessors that would have been handy the other day when I was doing some code walkthroughs with others.

## Verification

- [ ] Run through the steps for #9879 
- [ ] **Verify** it works as expected
- [ ] Revert the change to reverse_tcp.rb, verify that it works either way

```
--- a/lib/msf/core/payload/linux/x64/reverse_tcp.rb
+++ b/lib/msf/core/payload/linux/x64/reverse_tcp.rb
@@ -25,7 +25,7 @@ module Payload::Linux::ReverseTcp_x64
     conf = {
       port:        datastore['LPORT'],
       host:        datastore['LHOST'],
-      retry_count:   datastore['StagerRetryCount'],
+      retry_count:   datastore['ReverseConnectRetries'],
       sleep_seconds: datastore['StagerRetryWait'],
     }
```

- [ ] Modify the `to_handler` command with a change like this to verify that `merge` also works

```
--- a/lib/msf/ui/console/command_dispatcher/payload.rb
+++ b/lib/msf/ui/console/command_dispatcher/payload.rb
@@ -54,6 +54,8 @@ module Msf
             }
 
             handler.datastore.merge!(mod.datastore)
+            a = handler.datastore.merge(mod.datastore)
+            handler.datastore.merge!(a)
             handler.exploit_simple(handler_opts)
             job_id = handler.job_id
```

 - [ ] Verify that the the RHS of merge operations can be a Hash, DataStore, ModuleDataStore

### CODE REVIEW

**Comment by zeroSteiner** [comment]
Tested this out and I no longer get the "invalid opcode arguments" but there is still no job when I run `to_handler` when using the payload module directly.

File: lib/msf/core/data_store.rb [hunk 1]
```diff
@@ -216,6 +219,22 @@ def from_file(path, name = 'global')
     end
   end
 
+  def merge!(other)
+    @options.merge!(other.options)
```
Comment (acammack-r7) [inline lib/msf/core/data_store.rb]: Pro uses `#merge!` quite a bit with plain `Hash`es, so we will need to check if `other` is another `DataStore` or tag as `msf5`.

File: lib/msf/core/data_store.rb [hunk 2]
```diff
@@ -345,7 +364,7 @@ def copy
     self.keys.each do |k|
       clone.import_option(k, self[k].kind_of?(String) ? self[k].dup : self[k], @imported[k], @imported_by[k])
     end
-    clone.aliases = self.aliases
+    clone.aliases = @aliases
```
Comment (acammack-r7) [inline lib/msf/core/data_store.rb]: Since we have the `attr_accessor`, I don't think this should change.

File: lib/msf/core/data_store.rb (hunk 1 above)
Comment (acammack-r7) [inline lib/msf/core/data_store.rb]: Since you are adding `attr_accessor`s for these, you should probably reference them as `self.options...` etc.

**Comment by wvu-r7** [comment]
Confirming @zeroSteiner's results.

```
msf5 > use payload/linux/x64/meterpreter/reverse_tcp
msf5 payload(linux/x64/meterpreter/reverse_tcp) > set lhost 172.17.0.1
lhost => 172.17.0.1
msf5 payload(linux/x64/meterpreter/reverse_tcp) > to_handler
[*] Payload Handler Started as Job
msf5 payload(linux/x64/meterpreter/reverse_tcp) > jobs

Jobs
====

No active jobs.

msf5 payload(linux/x64/meterpreter/reverse_tcp) >
```

**Comment by wvu-r7** [comment]
More details:

```
[04/23/2018 15:00:35] [i(2)] core: Reloading exploit module multi/handler. Ambiguous module warnings are safe to ignore
[04/23/2018 15:00:35] [e(0)] core: Exploit failed (multi/handler): The following options failed to validate: LHOST.
[04/23/2018 15:00:35] [d(3)] core: Call stack:
/home/wvu/metasploit-framework/lib/msf/base/simple/exploit.rb:110:in `exploit_simple'
/home/wvu/metasploit-framework/lib/msf/base/simple/exploit.rb:166:in `exploit_simple'
/home/wvu/metasploit-framework/lib/msf/ui/console/command_dispatcher/payload.rb:57:in `cmd_to_handler'
/home/wvu/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:548:in `run_command'
/home/wvu/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:510:in `block in run_single'
/home/wvu/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `each'
/home/wvu/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `run_single'
/home/wvu/metasploit-framework/lib/rex/ui/text/shell.rb:208:in `run'
/home/wvu/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/wvu/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:49:in `<main>'
```

**Comment by wvu-r7** [comment]
Looks like the payload's datastore isn't being merged into the handler's datastore with the new `merge!` method? Still debugging...

**Comment by busterb** [comment]
Thanks for the review, will take a dive in to see what's happening.

File: lib/msf/core/data_store.rb (hunk 2 above)
Comment (busterb) [reply lib/msf/core/data_store.rb]: I understand they're different, but I'm not in agreement that only this would change. By extension, I wouldn't this mean changing all of the `@` accesses to `self.` ?

**Comment by busterb** [comment]
Appreciate the review again! I think this should be in good shape, following your observations.

File: lib/msf/core/data_store.rb [hunk 3]
```diff
@@ -216,6 +219,36 @@ def from_file(path, name = 'global')
     end
   end
 
+  #
+  # Return a deep copy of this datastore.
+  #
+  def copy
+    clone = self.class.new
```
Comment (acammack-r7) [inline lib/msf/core/data_store.rb]: `clone` is a common method name (shallow copy), I would avoid using it as a variable name.

File: lib/msf/core/data_store.rb [hunk 4]
```diff
@@ -216,6 +219,36 @@ def from_file(path, name = 'global')
...
+    clone.aliases = self.aliases.dup
+    clone
+  end
+
+  #
+  # Override merge! so that we merge the aliases and imported hashes
+  #
+  def merge!(other)
+    super
+    self.aliases.merge!(other.aliases) if other.respond_to?(:aliases)
```
Comment (acammack-r7) [inline lib/msf/core/data_store.rb]: This works, alternately you can do:
```ruby
if other.is_a? DataStore
  self.aliases.merge!(other.aliases)
  .....
end
```
Which seems a bit cleaner to me, but that's up to you.

File: lib/msf/core/data_store.rb (hunk 3 above)
Comment (busterb) [reply lib/msf/core/data_store.rb]: ok

File: lib/msf/core/data_store.rb (hunk 4 above)
Comment (busterb) [reply lib/msf/core/data_store.rb]: Since ModuleDataStore is_a DataStore, sure.

File: lib/msf/core/data_store.rb (hunk 3 above)
Comment (wvu-r7) [reply lib/msf/core/data_store.rb]: I have been bitten by something like this before. Go Ruby or OOP?

Comment (busterb) [reply lib/msf/core/data_store.rb]: Sure but, to be fair, this has been called 'clone' for many years - I just copied this function from below since it used to only exist inside of ModuleDataStore. You just can't see it in the condensed diff view.

Comment (busterb) [reply lib/msf/core/data_store.rb]: (granted, just because the code is old, doesn't mean it's correct :)

**Comment by wvu-r7** [comment]
```
msf5 > use payload/linux/x64/meterpreter/reverse_tcp
msf5 payload(linux/x64/meterpreter/reverse_tcp) > options

Module options (payload/linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address
   LPORT  4444             yes       The listen port

msf5 payload(linux/x64/meterpreter/reverse_tcp) > set lhost 127.0.0.1
lhost => 127.0.0.1
msf5 payload(linux/x64/meterpreter/reverse_tcp) > to_handler
[*] Payload Handler Started as Job 0

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started reverse TCP handler on 127.0.0.1:4444
msf5 payload(linux/x64/meterpreter/reverse_tcp) > jobs

Jobs
====

  Id  Name                    Payload                            Payload opts
  --  ----                    -------                            ------------
  0   Exploit: multi/handler  linux/x64/meterpreter/reverse_tcp  tcp://127.0.0.1:4444

msf5 payload(linux/x64/meterpreter/reverse_tcp) >
```

:raised_hands:

**Comment by wvu-r7** [comment]
# Release Notes

This fixes some discrepancies in how the datastore is managed, fixing stager retries and consequently the x64 Linux Meterpreter payload.
