### PR TITLE
Replace Readline with Reline

### LINKED ISSUE #19294: Keyboard Input Issues in `msfconsole` on PowerShell After Update to v6.4.16   Windows11
## Steps to reproduce

1. Update to Metasploit version v6.4.16-dev-e691f7217092cc55a8955fdd847ffa77c6f09f25.
2. Open PowerShell.
3. Start `msfconsole`.
4. Attempt to use the delete key and arrow keys.

## Expected behavior

The delete key and arrow keys should work as expected for navigating and editing commands in `msfconsole`.

## Current behavior

The delete key and arrow keys do not function correctly in `msfconsole` when using PowerShell.

## Metasploit version

Framework Version: v6.4.16-dev-e691f7217092cc55a8955fdd847ffa77c6f09f25

## System Information

- OS Name: Microsoft Windows 11 Pro
- OS Version: 2009
- OS Build: 22621.1.amd64fre.ni_release.220506-1250
- PowerShell Version: 7.4.3
- Terminal Information:
  - ForegroundColor: Gray
  - BackgroundColor: Black
  - CursorPosition: 0,13
  - WindowPosition: 0,0
  - CursorSize: 25
  - BufferSize: 120,30
  - WindowSize: 120,30
  - MaxWindowSize: 120,30
  - MaxPhysicalWindowSize: 1904,62
  - WindowTitle: Administrator: PowerShell

## Attempted solutions

1. Ensured Metasploit is up-to-date (ran `msfupdate`).
2. Tried different terminals (e.g., `cmd`, `Windows Terminal`, `Git Bash`).
3. Adjusted PowerShell settings:
   - Changed console buffer size and window size.
   - Disabled Quick Edit Mode.
4. Modified Readline configuration file:
   ```plaintext
   "\e[3~": delete-char
   "\e[1~": beginning-of-line
   "\e[4~": end-of-line
   "\e[5~": beginning-of-history
   "\e[6~": end-of-history

### PR DESCRIPTION
**Pull request by sjanusz-r7**
This PR:
- replaces the Readline library with Reline.
- fixes https://github.com/rapid7/metasploit-framework/issues/19294 by working around an `Open3` bug reported on the gem's GitHub issue page for Windows 11 (this compliments Reline, as we need Reline as well as the work-around to fix this)
- still uses the Readline gem, due to needing the `Readline::FILENAME_COMPLETION_PROC`, which is stubbed as `nil` in Reline. We use this to not have to write our own custom `FILENAME_COMPLETION_PROC`.
- fixes an issue present on `master`, where pressing `Ctrl+C` in `irb` prompt would result in a deadlock exception.
- marks the `real-readline` option as deprecated, due to the planned removal of the `Readline` gem in the future
- removes the `Readline` single-line input fallback mode from SQL sessions, as Reline will be used exclusively
- removes the history_manager input_library option, as Reline is the only library being supported moving forward, as we are planning to drop Readline

## Windows 11 - Before
Can't delete characters in the prompt, and getting a bug where the input gets re-entered multiple times.
```
PS C:\Users\x\Desktop\metasploit-framework> bundle exec 'ruby ./msfconsole -q'
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
C:/Users/x/.local/share/gem/ruby/3.1.0/gems/rex-core-0.1.32/lib/rex/compat.rb:381: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
msf6 auxiliary(scanner/oracle/oracle_login) > use postggrgregresgres_gres_lgres_logres_loggres_logigres_login
```

## Windows 11 - After
No duplicate input in prompt, prompt can be cleared using backspace and navigated using left and right arrow keys.
```
PS C:\Users\x\Desktop\metasploit-framework> bundle exec 'ruby ./msfconsole -q'
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
C:/Users/x/.local/share/gem/ruby/3.1.0/gems/rex-core-0.1.32/lib/rex/compat.rb:381: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
msf6 auxiliary(scanner/oracle/oracle_login) > use postgres_login (no duplicated input)

Matching Modules
================

   #  Name                                       Disclosure Date  Rank    Check  Description
   -  ----                                       ---------------  ----    -----  -----------
   0  auxiliary/scanner/postgres/postgres_login  .                normal  No     PostgreSQL Login Utility


Interact with a module by name or index. For example info 0, use 0 or use auxiliary/scanner/postgres/postgres_login

[*] Using auxiliary/scanner/postgres/postgres_login
[*] New in Metasploit 6.4 - The CreateSession option within this module can open an interactive session
msf6 auxiliary(scanner/postgres/postgres_login) > use postgres_login (press backspace multiple times)
msf6 auxiliary(scanner/postgres/postgres_login) > (prompt cleared)
```

## IRB - Before
```
msf6 auxiliary(scanner/postgres/postgres_login) > irb
[*] Starting IRB shell...
[*] You are in auxiliary/scanner/postgres/postgres_login

>> 
^C
[-] Error during IRB: deadlock; recursive locking

/Users/x/.rvm/gems/ruby-3.1.5/gems/reline-0.5.8/lib/reline.rb:261:in `synchronize'
/Users/x/.rvm/gems/ruby-3.1.5/gems/reline-0.5.8/lib/reline.rb:261:in `readmultiline'
/Users/x/.rvm/rubies/ruby-3.1.5/lib/ruby/3.1.0/forwardable.rb:238:in `readmultiline'
./msfconsole:23:in `<main>'
msf6 auxiliary(scanner/postgres/postgres_login) > 
```

## IRB - After
```
msf6 auxiliary(scanner/postgres/postgres_login) > irb
[*] Starting IRB shell...
[*] You are in auxiliary/scanner/postgres/postgres_login

>> 
^C
>> 
^C
>> 
```

## Verification

- [x] Start `msfconsole`
- [x] Ensure you can run some commands as expected
- [x] Get a SQL session using e.g. `postgres_login`
- [x] Ensure that the `query` and `query_interactive` commands work when provided single and multi-line input
- [x] Ensure that the `irb` command works
- [x] Ensure that pressing `Ctrl+C` in `irb` prompt does not result in a deadlock exception
- [x] Ensure that after exiting `irb`, the autocompletion suggestions do not leak from `irb`, and prompt remains normal
- [ ] Ensure that `msfconsole` works on Windows 11 and does not freeze (linked issue)
- [x] Ensure tab-completion works in msfconsole's prompt for settings, `set` command etc.
- [x] Ensure that scrolling through the prompt's history using up and down arrow keys works as expected
- [x] Ensure that switching history_manager contexts does not result in history leakage (go into a SQL session, type a command, exit the SQL session, ensure the command you just entered does not show up in msfconsole's prompt)
- [x] Ensure tests pass

### CODE REVIEW

File: lib/metasploit/framework/parsed_options/console.rb [hunk 1]
```diff
@@ -54,7 +53,11 @@ def option_parser
         end
 
         option_parser.on('-L', '--real-readline', 'Use the system Readline library instead of RbReadline') do
-          options.console.real_readline = true
+          message = "The RealReadline option has been marked as deprecated, and is currently a noop.\n"
+          message << "Metasploit Framework now uses Reline exclusively as the input handling library.\n"
+          message << "If you require this functionality, please raise an issue on GitHub:\n"
+          message << '  https://github.com/rapid7/metasploit-framework/issues/new?assignees=&labels=bug&projects=&template=bug_report.md'
```
Comment (adfoster-r7) [inline lib/metasploit/framework/parsed_options/console.rb:59]: I'd probably pre-create this issue on our side and replace this link here, that way we have a single source of truth - instead of multiple disparate threads

File: lib/rex/ui/text/output/stdio.rb [hunk 2]
```diff
@@ -94,6 +94,7 @@ def print_raw(msg = '')
     msg
   end
   alias_method :write, :print_raw
+  alias_method :<< ,:write
```
Comment (smcintyre-r7) [inline lib/rex/ui/text/output/stdio.rb:97]:
```suggestion
  alias_method :<<, :write
```

**Comment by cgranleese-r7** [comment]
I was able to test everything expect for the Windows 11 issue. I tested against build versions:
- 10.0.22000
- 10.0.22631

@adfoster-r7 has confirmed he can replicate it on his machine but just needs to do some extra testing.

Only other thing worth calling out was on master when you are within a session, then enter IRB you can `ctrl + c` to breakout making use of `[-] Error during IRB: deadlock; recursive locking`. Obviously this isn't ideal, but no it's fixed from what I experienced I wasn't able to actually leave IRB now, when I would run `exit` it would just return `true`. Thought it was worth calling out and we may need to open an issue for that.

Apart from that everything worked as expected 👍

**Review by adfoster-r7 — APPROVED** [review]

**Comment by cdelafuente-r7** [comment]
# Release Notes

This replaces the Readline library with Reline.
