### PR TITLE
Fix msfrpcd console read failures

### LINKED ISSUE #16580: msfrpcd console failure caused by rex-core upgrade
## Overview

Beginning with version `6.1.27`, interactions with Metasploit through `msfrpcd` are unreliable, and sometimes result in output being truncated, input being accepted but discarded, and no error being reported to the RPC client.

I have narrowed down the cause of the issue to be the `rex-core` version update between `6.1.26` and `6.1.27`. Manually reverting `rex-core` back to version `0.1.20`, as used in MSF `6.1.26`, fixes the buggy behavior.

The issue is difficult to reliably reproduce and may require stepping through the procedure several times. Some exploits, like the one listed, seemed to produce the buggy behavior more reliably. I have confirmed the behavior with the following exploit modules, but it likely works with others:

- multi/http/apache_activemq_upload_jsp + java/meterpreter/reverse_tcp
- windows/smb/ms17_010_psexec + windows/meterpreter/reverse_tcp
- multi/http/tomcat_mgr_upload + java/meterpreter/reverse_tcp
- linux/http/apache_druid_js_rce + linux/x86/meterpreter_reverse_tcp
- multi/http/werkzeug_debug_rce + python/meterpreter/reverse_tcp

## Steps to reproduce

0. Start from a freshly cloned copy of `metasploit-framework` (currently version 6.1.42)

1. Start `msfrpcd` and `msfrpc`

```sh
export MSF_USERNAME=username
export MSF_PASSWORD=password
./msfrpcd -U ${MSF_USERNAME} -P ${MSF_PASSWORD} -a 127.0.0.1 # Optionally start in foreground of another shell
./msfrpc -U ${MSF_USERNAME} -P ${MSF_PASSWORD} -a 127.0.0.1 
```

2. In the RPC client, create a console, load an exploit, set options, and run.

NOTE: The exploit used in the following example was the most likely to produce the buggy behavior in my experience. However, the problem affects a wide array of exploit modules. The behavior was observed when testing against a target that was intentionally made vulnerable to the exploit (and for which the exploit succeeded using MSF <=6.1.26). Be sure to adjust options to fit your test environment.

Many of the options set in the following call are default options for the module. They are explicitly set by some libraries such as `pymetasploit3`, so I explicitly set them when using `msfrpc`. This is likely not necessary to reproduce the buggy behavior.

```ruby
rpc.call('console.create')
console = _['id']
rpc.call('console.write', console, "use exploit/multi/http/apache_activemq_upload_jsp
set VERBOSE True
set WfsDelay 2
set EnableContextEncoding False
set DisablePayloadHandler False
set RPORT 8161
set SSL False
set UserAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 12.2; rv:97.0) Gecko/20100101 Firefox/97.0
set HttpUsername 
set HttpPassword 
set DigestAuthIIS True
set SSLVersion Auto
set FingerprintCheck True
set DOMAIN WORKSTATION
set HttpTrace False
set HttpTraceHeadersOnly False
set HttpTraceColors red/blu
set HTTP::uri_encode_mode hex-normal
set HTTP::uri_full_url False
set HTTP::pad_method_uri_count 1
set HTTP::pad_uri_version_count 1
set HTTP::pad_method_uri_type space
set HTTP::pad_uri_version_type space
set HTTP::method_random_valid False
set HTTP::method_random_invalid False
set HTTP::method_random_case False
set HTTP::version_random_valid False
set HTTP::version_random_invalid False
set HTTP::uri_dir_self_reference False
set HTTP::uri_dir_fake_relative False
set HTTP::uri_use_backslashes False
set HTTP::pad_fake_headers False
set HTTP::pad_fake_headers_count 0
set HTTP::pad_get_params False
set HTTP::pad_get_params_count 16
set HTTP::pad_post_params False
set HTTP::pad_post_params_count 16
set HTTP::uri_fake_end False
set HTTP::uri_fake_params_start False
set HTTP::header_folding False
set AllowNoCleanup False
set BasicAuthUser admin
set BasicAuthPass admin
set AutoCleanup true
set RHOSTS XX.XX.XX.XX
set payload java/meterpreter/reverse_tcp
set VERBOSE False
set LPORT 8000
set ReverseAllowProxy False
set ReverseListenerThreaded False
set StagerRetryCount 10
set StagerRetryWait 5
set PingbackRetries 0
set PingbackSleep 30
set PayloadUUIDTracking False
set EnableStageEncoding False
set StageEncodingFallback True
set JavaMeterpreterDebug False
set Spawn 2
set AutoLoadStdapi True
set AutoVerifySessionTimeout 30
set AutoSystemInfo True
set EnableUnicodeEncoding False
set SessionRetryTotal 3600
set SessionRetryWait 10
set SessionExpirationTimeout 604800
set SessionCommunicationTimeout 300
set AutoUnhookProcess False
set MeterpreterDebugBuild False
set LHOST eth0
run -z\n")
```

3. Once the exploit is running, enter the following command repeatedly, until the response contains`"busy"=>false`.

```ruby
rpc.call('console.read', console)
```

4. (IN WORKING VERSIONS; <= 6.1.26) The output produced by step 3 SHOULD show the module successfully completing and creating at least one meterpreter session. At this point, you SHOULD be able to repeatedly enter the following command sequence to show that the console is still functional by returning the 

```ruby
rpc.call('console.write', console, "version\n")
# => {"wrote"=>8}
rpc.call('console.read', console)
# => {"data"=>"XXXXXXX", "prompt"=>"msf6 exploit(multi/http/apache_activemq_upload_jsp) > ", "busy"=>false}
```

4. (IN BUGGY VERSIONS; >= 6.1.27) The output produced by step 3 MAY be truncated and not show any sessions created. In some cases, it did not even echo all the options being set. There is not indication that the exploit finished, or the console crashed. At this point, entering the same command sequence will eventually result in an unexpected output of `{"wrote"=>nil}`.

```
rpc.call('console.write', console, "version\n")
# => {"wrote"=>8}
rpc.call('console.read', console)
# => {"data"=>"XXXXXXX", "prompt"=>"msf6 exploit(multi/http/apache_activemq_upload_jsp) > ", "busy"=>false}rpc.call('console.write', console, "version\n")
# => {"wrote"=>nil}
rpc.call('console.read', console)
# => {"data"=>"XXXXXXX", "prompt"=>"msf6 exploit(multi/http/apache_activemq_upload_jsp) > ", "busy"=>false}
```

## Were you following a specific guide/tutorial or reading documentation?

No.

## Expected behavior

This is described in detail in the steps to reproduce.

Using a reliable exploit against an intentionally vulnerable target, the exploit should always succeed in creating a meterpreter session.

## Current behavior

This is described in detail in the steps to reproduce.

Even when using a reliable exploit against an intentionally vulnerable target, the console will sometimes truncate output and become non-responsive.

### Metasploit version

This behavior is observed in version 6.1.27-6.1.42(current).

## Additional Information

I have narrowed down the cause of the problem to being the version of dependency `rex-core`.
In MSF version 6.1.26, rex-core version 0.1.20 is used.
In MSF version 6.1.27, rex-core version 0.1.25 is used.

For any version of MSF >= 6.1.27, manually downgrading rex-core to version 0.1.20 using the following commands removes the observed buggy behavior.

```sh
sed -i 's/rex-core (0.1..*)/rex-core (0.1.20)/' Gemfile.lock
bundle install
```

However, since I am not familiar with the metasploit-framework source code, I do not know if this dependency change will introduce other bugs.

### PR DESCRIPTION
**Pull request by adfoster-r7**
Closes https://github.com/rapid7/metasploit-framework/issues/16580

I've added automated tests for this scenario, but this was my original test:

```ruby
require 'pathname'
require Pathname.new(__dir__).realpath.expand_path.join('config', 'boot')
require 'msfenv'

framework ||= Msf::Simple::Framework.create(
  'DeferModuleLoads' => true,
  'Logger' => 'Stdout',
  'LogLevel' => 3
)
service = OpenStruct.new(framework: framework)
rpc = Msf::RPC::RPC_Console.new(service)
console = rpc.rpc_create({ 'DisableBanner' => true })['id']
10.times do
  puts("Write result: #{rpc.rpc_write(console, "version\n")}")
  sleep 0.5
  puts("Read result: #{rpc.rpc_read(console)}")
end

rpc.rpc_destroy(console)
puts "finished"
```

### Latest framework release

The console is created successfully, but something causes the web console pipe to die/close - causing reads and writes to fail:

```
bundle exec ruby test.rb    
[07/27/2022 13:18:28] [e(0)] core: Module auxiliary/scanner/vnc/vnc_login not found, and no loading errors found. If you're using a custom module refer to our wiki: https://github.com/rapid7/metasploit-framework/wiki/Running-Private-Modules
Write result: {"wrote"=>8}
[07/27/2022 13:18:29] [d(0)] core: HistoryManager.push_context name: :msfconsole
Read result: {"data"=>"[-] Failed to load module: auxiliary/scanner/vnc/vnc_login\nFramework: 6.2.9-dev-4bbae96840\nConsole  : 6.2.9-dev-4bbae96840\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"Framework: 6.2.9-dev-4bbae96840\nConsole  : 6.2.9-dev-4bbae96840\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
[07/27/2022 13:18:29] [w(0)] core: monitor_rsock: exception during read: Errno::EAGAIN Resource temporarily unavailable
[07/27/2022 13:18:29] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[07/27/2022 13:18:29] [e(0)] core: Thread Exception: WebConsoleShell  critical=false    source:
    /Users/user/Documents/code/metasploit-framework/lib/msf/ui/web/web_console.rb:84:in `initialize'
    /Users/user/Documents/code/metasploit-framework/lib/msf/ui/web/driver.rb:62:in `new'
    /Users/user/Documents/code/metasploit-framework/lib/msf/ui/web/driver.rb:62:in `create_console'
    /Users/user/Documents/code/metasploit-framework/lib/msf/core/rpc/v10/rpc_console.rb:28:in `rpc_create'
    test.rb:12:in `<main>' - IOError closed stream
Call stack:
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/input/buffer.rb:52:in `getc'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/input/buffer.rb:52:in `gets'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/bidirectional_pipe.rb:118:in `gets'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/bidirectional_pipe.rb:148:in `pgets'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/shell.rb:323:in `get_input_line'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/shell.rb:145:in `run'
/Users/user/Documents/code/metasploit-framework/lib/msf/ui/web/web_console.rb:84:in `block in initialize'
/Users/user/Documents/code/metasploit-framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'
/Users/user/.rvm/gems/ruby-3.0.2@metasploit-framework/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
Read result: {"data"=>"Framework: 6.2.9-dev-4bbae96840\nConsole  : 6.2.9-dev-4bbae96840\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>nil}
Read result: {"data"=>"", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>nil}
Read result: {"data"=>"", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>nil}
Read result: {"data"=>"", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>nil}
Read result: {"data"=>"", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>nil}
Read result: {"data"=>"", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>nil}
Read result: {"data"=>"", "prompt"=>"msf6 > ", "busy"=>false}
finished
```

## This Branch

The console is created successfully, and read/writes are supported:

```
[07/27/2022 13:17:17] [d(0)] core: monitor_rsock: Skipping - functionality not required.rb  
[07/27/2022 13:17:17] [e(0)] core: Module auxiliary/scanner/vnc/vnc_login not found, and no loading errors found. If you're using a custom module refer to our wiki: https://github.com/rapid7/metasploit-framework/wiki/Running-Private-Modules
Write result: {"wrote"=>8}
[07/27/2022 13:17:18] [d(0)] core: HistoryManager.push_context name: :msfconsole
Read result: {"data"=>"[-] Failed to load module: auxiliary/scanner/vnc/vnc_login\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"Framework: 6.2.9-dev-00b85e9bb4\nConsole  : 6.2.9-dev-00b85e9bb4\nFramework: 6.2.9-dev-00b85e9bb4\nConsole  : 6.2.9-dev-00b85e9bb4\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"Framework: 6.2.9-dev-00b85e9bb4\nConsole  : 6.2.9-dev-00b85e9bb4\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"Framework: 6.2.9-dev-00b85e9bb4\nConsole  : 6.2.9-dev-00b85e9bb4\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"Framework: 6.2.9-dev-00b85e9bb4\nConsole  : 6.2.9-dev-00b85e9bb4\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"Framework: 6.2.9-dev-00b85e9bb4\nConsole  : 6.2.9-dev-00b85e9bb4\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"Framework: 6.2.9-dev-00b85e9bb4\nConsole  : 6.2.9-dev-00b85e9bb4\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"Framework: 6.2.9-dev-00b85e9bb4\nConsole  : 6.2.9-dev-00b85e9bb4\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"Framework: 6.2.9-dev-00b85e9bb4\nConsole  : 6.2.9-dev-00b85e9bb4\n", "prompt"=>"msf6 > ", "busy"=>false}
Write result: {"wrote"=>8}
Read result: {"data"=>"Framework: 6.2.9-dev-00b85e9bb4\nConsole  : 6.2.9-dev-00b85e9bb4\n", "prompt"=>"msf6 > ", "busy"=>false}
[07/27/2022 13:17:24] [d(0)] core: HistoryManager.pop_context name: :msfconsole
finished
```

## Verification

Verify the automated tests pass, and the scenarios raised by users in the original issue

### CODE REVIEW

File: lib/rex/ui/text/input/buffer.rb [hunk 1]
```diff
@@ -18,6 +18,10 @@ class BufferSock
     def write(buf, opts={})
       syswrite(buf)
     end
+
+    def monitor_rsock(*args, **kwargs)
+      dlog('monitor_rsock: Skipping - functionality not required')
+    end
```
Comment (adfoster-r7) [inline lib/rex/ui/text/input/buffer.rb:24]: I believe this is the correct fix; Here was my code spelunking process:

HD Added this BufferSock class 16 years ago, and it depends on `StreamAbstraction`
https://github.com/rapid7/metasploit-framework/blame/5bf973871c3beca4788ec655b8ecd5e64af79e55/lib/rex/ui/text/input/buffer.rb#L16

The StreamAbstraction of 16 years ago, didn't have this `monitor_rsock` method call present - which runs in a loop automatically reading from rsock and writing the result:
https://github.com/rapid7/rex-core/commit/2970b21d3fb4dd30d529be6f6808dd1f170a4430#diff-78a17e4da58de200bc8f7afd1a44150d752a6a8756effe6478f0b589ece15f64

Then recently there was an implementation update to `monitor_rsock` which automatically closes things when the monitor loop ends:

https://github.com/rapid7/rex-core/commit/caa60274ec93a1597a4fe0d1d032fd8575593a9d#diff-bf61a62a028b4adbe2af6a11f60e8b3aa226ce3f1101be48330cf16f0f4ac98aR211

The loop was exiting as an `Errno::EAGAIN` exception was being raised on the read call [here](https://github.com/rapid7/rex-core/blob/caa60274ec93a1597a4fe0d1d032fd8575593a9d/lib/rex/io/socket_abstraction.rb#L157), I believe this is because there was competition for reading from the monitor loop and the normal msfconsole webconsole pipe reader.

TL:DR The default `monitor_rsock` implementation shouldn't be running in this scenario, and it now forcibly kills the webconsole pipe when an error is raised

**Comment by smcintyre-r7** [comment]
The code looks correct to me and the unit tests are passing.

It took me a few tries, but I was able to reproduce the original error and was able to confirm after running the test case many times that it no longer appears with these changes in place. It makes sense in this context that the rsock-monitoring routine is unnecessary.

I'll get this landed in a moment.

**Comment by smcintyre-r7** [comment]
# Release Notes
This fixes a bug in `Rex::Ui::Text::Input::Buffer::BufferSock` that was causing data to occasionally be lost due to the rsock monitor routine.

**Comment by adfoster-r7** [comment]
Thanks for the land! 🎉
