### PR TITLE
guard and notify for missing encoders

### LINKED ISSUE #13435: Suggestion: add message to handle error when trying to use an invalid encoder
## Steps to reproduce

1. use exploit/windows/smb/psexec
2. set target 2 (native upload)
3. set other options as needed (login, password, rhost)
4. set SERVICE_STUB_ENCODER notfound

Here I make the mistake of selecting an invalid encoder (it happens, right? 😉)

## Expected behavior

Metasploit should give me an explicit error "Invalid encoder 'notfound' selected"

## Current behavior

We get a not very helpful error:
```terminal
msf5 exploit(windows/smb/psexec) > run

[*] Started reverse TCP handler on 192.168.80.131:4444 
[*] a.b.c.d:445 - Connecting to the server...
[*] a.b.c.d:445 - Authenticating to a.b.c.d:445|cnn-lab as user 'clem'...
[!] a.b.c.d:445 - No active DB -- Credential data will not be saved!
[*] a.b.c.d:445 - Uploading payload... lvkZVaeg...exe
createx86/service
after create, encoder_mod=#<Msf::Modules::Encoder__X86__Service::MetasploitModule:0x00007fa39873c240>
datastore={}
before run
after run
createnotfound
after create, encoder_mod=
datastore={}
[-] a.b.c.d:445 - Exploit failed: NoMethodError undefined method `datastore' for nil:NilClass
```

As you can see I added some ugly prints (btw if you know a better way to work within MSF!) to debug the issue in lib/msf/core/payload_generator.rb:
```ruby
    def multiple_encode_payload(shellcode)
      encoder_str = encoder[1..-1]
      encoder_str.scan(/([^:, ]+):?([^,]+)?/).map do |encoder_opt|
        @iterations = (encoder_opt[1] || 1).to_i
        @iterations = 1 if iterations < 1
        print("create"+encoder_opt[0]+"\n")
        encoder_mod = framework.encoders.create(encoder_opt[0])
        puts("after create, encoder_mod="+encoder_mod.to_s)
        puts("datastore="+datastore.to_s)
        encoder_mod.datastore.import_options_from_hash(datastore)
        puts("before run")
        shellcode = run_encoder(encoder_mod, shellcode)
        puts("after run")
      end
      shellcode
    end
```

It allows to see that when an encoder is invalid, `encoder_mod = framework.encoders.create` returns `nil` which triggers the exception below when calling `encoder_mod.datastore`

I'd like to offer a PR but I don't know this code enough to be confident :)

### Metasploit version

Latest version from Git

**Actually I'm working on fixing this code and currently specifying an encoder won't do anything and you won't be able to reproduce it**
Cf. #13407 and https://github.com/rapid7/metasploit-framework/issues/13407#issuecomment-625335717 from @jmartin-r7 explaining how the service encoder setting flows from psexec options to this code

### PR DESCRIPTION
**Pull request by jmartin-tech**
Fix #13435

When an encoder module is incorrectly entered or does not exist
continue the encoding process and log the invalid entry to console.

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] See issue #13435 for reproduction steps

### CODE REVIEW

File: lib/msf/core/payload_generator.rb [hunk 1]
```diff
@@ -252,6 +252,10 @@ def multiple_encode_payload(shellcode)
         @iterations = 1 if iterations < 1
 
         encoder_mod = framework.encoders.create(encoder_opt[0])
+        unless encoder_mod
+          cli_print "#{encoder_opt[0]} not found continuing..."
+          next
```
Comment (adfoster-r7) [inline lib/msf/core/payload_generator.rb:257]: I might not have the full picture here - but I just wanted to confirm if this is the semantics we're after. If the encoder isn't found, is this a scenario that should stop the execution of the payload generation instead of continuing?

**Comment by adfoster-r7** [comment]
@jmartin-r7 If I understand correctly the original issue was caused by incorrect validation on the SERVICE_STUB_ENCODER option:
https://github.com/rapid7/metasploit-framework/blob/a2675c13e88dc1df9e6cfed9021b2a5d4f82d231/modules/exploits/windows/smb/ms17_010_psexec.rb#L101

Instead of a `OptString` - would it make sense to have `OptEncoder` or something similar? 🤔 

Or maybe we could manually check that the encoder exists prior to kicking off the payload generation?

**Comment by jmartin-r7** [comment]
@adfoster-r7, you have it right.  The original finding was due to the issues with specifying a service stub.  The guard is still a good idea to incorporate.  A new `Opt` type maybe worth investigating, however a quick options check suggests it may have very limited usage.

File: lib/msf/core/payload_generator.rb (hunk 1 above)
Comment (jmartin-r7) [reply lib/msf/core/payload_generator.rb:257]: I had opted to `log & continue` similar to the next method `encode_payload()` in this class.  Raising a `::Msf::EncodingError` , is another reasonable approach.

File: lib/msf/core/payload_generator.rb [hunk 2]
```diff
@@ -252,6 +252,10 @@ def multiple_encode_payload(shellcode)
         @iterations = 1 if iterations < 1
 
         encoder_mod = framework.encoders.create(encoder_opt[0])
+        unless encoder_mod
+          cli_print "#{encoder_opt[0]} not found continuing..."
```
Comment (adfoster-r7) [inline lib/msf/core/payload_generator.rb:256]: When replicating the steps from the original issue:
```
use exploit/windows/smb/psexec
set target 2
set rhost 10.20.36.244
set SERVICE_STUB_ENCODER notfound
run
```

It looks like`cli_print` doesn't output anything to the console for me:

```
msf6 exploit(windows/smb/psexec) > run

[-] Handler failed to bind to 10.12.225.25:4444:-  -
[*] Started reverse TCP handler on 0.0.0.0:4444 
[*] 10.20.36.244:445 - Connecting to the server...
[*] 10.20.36.244:445 - Authenticating to 10.20.36.244:445 as user 'vagrant'...
[!] 10.20.36.244:445 - peer_native_os is only available with SMB1 (current version: SMB2)
[*] 10.20.36.244:445 - Uploading payload... deUFyYUA.exe
[*] 10.20.36.244:445 - Created \deUFyYUA.exe...
[+] 10.20.36.244:445 - Service started successfully...
[*] 10.20.36.244:445 - Deleting \deUFyYUA.exe...
[*] Exploit completed, but no session was created.
```

I put in a breakpoint, and it looks like `cli` is false in this scenario:

image

Comment (jmartin-r7) [reply lib/msf/core/payload_generator.rb:256]: I wonder if that is the case for `msfvenom`? 

It is possible that `cli_print` does not print in a running `msfconsole`, in which case I suggest we consider tackling that separately and possibly enhancing `cli_print` to detect if run from a `shell` or from inside `msfconsole`.

Comment (adfoster-r7) [reply lib/msf/core/payload_generator.rb:256]: Looks like the log and continue is consistent with elsewhere in this file:

https://github.com/rapid7/metasploit-framework/blob/5fbe243662390054fc4dcc4f8250b85068709152/lib/msf/core/payload_generator.rb#L491-L497

**Comment by adfoster-r7** [comment]
## Release Notes

Updates multiple_encode_payload to add additional console logging to handle the scenario of an encoder module being incorrectly entered or not existing.
