### PR TITLE
Fix PASSWORD_SPRAY being ignored for LDAP (and potetnially other modules)

### LINKED ISSUE #18994: PASSWORD_SPRAY not working
```
msf6 auxiliary(scanner/ldap/ldap_login) > options

Module options (auxiliary/scanner/ldap/ldap_login):

   Name              Current Setting                     Required  Description
   ----              ---------------                     --------  -----------
   ANONYMOUS_LOGIN   true                                yes       Attempt to login with a blank username and password
   BRUTEFORCE_SPEED  5                                   yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false                               no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false                               no        Add all passwords in the current database to the list
   DB_ALL_USERS      false                               no        Add all users in the current database to the list
   DB_SKIP_EXISTING  none                                no        Skip existing credentials stored in the current database (Accepted: none, user, user&realm)
   DOMAIN            testdomain.com          no        The domain to authenticate to
   PASSWORD                                              no        The password to authenticate with
   PASS_FILE         /opt/rockyou.txt                    no        File containing passwords, one per line
   RHOSTS            10.1.1.100                         yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT             389                                 yes       The target port
   SSL               false                               no        Enable SSL on the LDAP connection
   STOP_ON_SUCCESS   false                               yes       Stop guessing when a credential works for a host
   THREADS           1                                   yes       The number of concurrent threads (max one per host)
   USERNAME                                              no        The username to authenticate with
   USERPASS_FILE                                         no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false                               no        Try the username as the password for all users
   USER_FILE         /root/users.txt  no        File containing usernames, one per line
   VERBOSE           true                                yes       Whether to print output for all attempts


   When LDAP::Auth is one of auto,plaintext:

   Name           Current Setting  Required  Description
   ----           ---------------  --------  -----------
   APPEND_DOMAIN  true             yes       Appends `@<DOMAIN> to the username for authentication`


View the full module info with the info, or info -d command.

msf6 auxiliary(scanner/ldap/ldap_login) > set PASSWORD_SPRAY
PASSWORD_SPRAY => true
```
Results in still hitting users 

```
[-] 10.1.1.100:389 - LOGIN FAILED: username1:123456 (Incorrect: Bind Result: {:extended_response=>nil, :code=>34, :error_message=>"invalid DN", :matched_dn=>"", :message=>"Invalid DN Syntax"})
[-] 10.1.1.100:389 - LOGIN FAILED: username1@testdomain.com:123456 (Incorrect: Bind Result: {:extended_response=>nil, :code=>34, :error_message=>"invalid DN", :matched_dn=>"", :message=>"Invalid DN Syntax"})
[-] 10.1.1.100:389 - LOGIN FAILED: username1:12345 (Incorrect: Bind Result: {:extended_response=>nil, :code=>34, :error_message=>"invalid DN", :matched_dn=>"", :message=>"Invalid DN Syntax"})
[-] 10.1.1.100:389 - LOGIN FAILED: username1@testdomain.com:12345 (Incorrect: Bind Result: {:extended_response=>nil, :code=>34, :error_message=>"invalid DN", :matched_dn=>"", :message=>"Invalid DN Syntax"})
[-] 10.1.1.100:389 - LOGIN FAILED: username1:123456789 (Incorrect: Bind Result: {:extended_response=>nil, :code=>34, :error_message=>"invalid DN", :matched_dn=>"", :message=>"Invalid DN Syntax"})
[-] 10.1.1.100:389 - LOGIN FAILED: username1@testdomain.com:123456789 (Incorrect: Bind Result: {:extended_response=>nil, :code=>34, :error_message=>"invalid DN", :matched_dn=>"", :message=>"Invalid DN Syntax"})

```

### PR DESCRIPTION
**Pull request by nrathaus**
Fixes #18994 which will fix the PASSWORD_SPRAY (unhandling) issue whenever the code is still using `each` for credentials rather than newer functions

I am unable to test it for all modules that use this - I did test it for LDAP

### CODE REVIEW

**Comment by nrathaus** [comment]
Setup of LDAP server:
```
docker run -p 389:389 -p 636:636 --name my-openldap-container --detach osixia/openldap:1.5.0
```

Setup the `$LDAP_CID` value based on the container that is created

```
docker exec $LDAP_CID ldapadd -x -D "cn=admin,dc=example,dc=org" -w admin -f /container/service/slapd/assets/test/new-user.ldif -H ldap://ldap.example.org -ZZ
```

Add another user:
```
ldapadd -x -D "cn=admin,dc=example,dc=org" -w admin -H ldap://127.0.0.1:389
```

Give it this text:
```
dn: uid=test,dc=example,dc=org
uid: test
cn: test
sn: 3
objectClass: top
objectClass: posixAccount
objectClass: inetOrgPerson
loginShell: /bin/bash
homeDirectory: /home/test
uidNumber: 14583102
gidNumber: 14564100
userPassword: {SSHA}j3lBh1Seqe4rqF1+NuWmjhvtAni1JC5A
mail: test@example.org
gecos: Test User
```

Metasploit test:
```
use scanner/ldap/ldap_login
set PASSWORD_SPRAY true
set USER_FILE /tmp/users.txt
set PASS_FILE /tmp/passwords.txt
set RHOSTS 127.0.0.1
run
```

**Comment by adfoster-r7** [comment]
Thanks for the PR; I don't quite have the cycles to review this fully, but if this is building an in-memory array of permutations before executing things - then that pattern won't scale well for large user/password lists unfortunately

That's something I ran into with the older brute force mixin - https://github.com/rapid7/metasploit-framework/pull/15115 - that I believe the `credential_collection` doesn't suffer from in its current state of yielding values

**Comment by nrathaus** [comment]
@adfoster-r7 I agree that on large arrays (user count * password count) it can become very big and probably consume a lot of memory, so I reverted the patch and made a "duplicate" of the function with `_password_first` focus on it, and a `yield` picking between the two options

I don't have enough Ruby understanding to make sure it works (my Ruby skills aren't that great at the moment)

Also I don't see any unit-tests I can use to verify it works as expected on all scenarios

I did check it on FTP and LDAP with username/password files - seems to work as expected

**Comment by adfoster-r7** [comment]
> Also I don't see any unit-tests I can use to verify it works as expected on all scenarios

Hmm - do these work? Or do we need to add more 👀 

https://github.com/rapid7/metasploit-framework/blob/9f22d67210334c3f0ef99b522aa3df4999ccaaa9/spec/lib/metasploit/framework/credential_collection_spec.rb

**Comment by nrathaus** [comment]
@adfoster-r7 opps, I have no idea how to use these as unittest - any guidance in Metapsloit guides or elsewhere on how to run these as standalone?

VS doesn't show them as `tests`

**Comment by adfoster-r7** [comment]
Sorry for the delay; Do these steps work?

https://github.com/rapid7/metasploit-framework/pull/19088

**Comment by nrathaus** [comment]
Looks like it will help, I will give it a try

**Comment by nrathaus** [comment]
@adfoster-r7 
`bundle rspec ./spec/path/to/your/tests_1.rb ./spec/path/to/your/tests_2.rb`

Should be:
`bundle exec rspec ./spec/path/to/your/tests_1.rb ./spec/path/to/your/tests_2.rb`

**Comment by nrathaus** [comment]
Is the DB error I am getting for rspec, related to this step:
```
cd ~/metasploit-framework/config &&
cp database.yml.example database.yml
```

**Comment by nrathaus** [comment]
Well... I guess I broke stuff :D
```
$ bundle exec rspec spec/lib/metasploit/framework/credential_collection_spec.rb
Overriding user environment variable 'OPENSSL_CONF' to enable legacy functions.
Run options:
  include {:focus=>true}
  exclude {:acceptance=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 29966
Metasploit::Framework::CredentialCollection ...................

Top 10 slowest examples (0.0159 seconds, 56.5% of total time):
  Metasploit::Framework::CredentialCollection#empty? when :username is set and :password is not set is expected to eq true
    0.00427 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:205
  Metasploit::Framework::CredentialCollection#each is expected to yield with args(Metasploit::Framework::Credential)
    0.00242 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:35
  Metasploit::Framework::CredentialCollection#each when given a userspass_file is expected to yield successive args(#<Metasploit::Framework::Credential "asdf:jkl" >, #<Metasploit::Framework::Credential "foo:bar" >)
    0.00149 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:87
  Metasploit::Framework::CredentialCollection#each when given a username, user_file and pass_file is expected to yield successive args(#<Metasploit::Framework::Credential "my_username:asdf" >, #<Metasploit::Framework::Credential "my_username:jkl" >, #<Metasploit::Framework::Credential "asdf:asdf" >, #<Metasploit::Framework::Credential "asdf:jkl" >, #<Metasploit::Framework::Credential "jkl:asdf" >, #<Metasploit::Framework::Credential "jkl:jkl" >)
    0.00121 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:142
  Metasploit::Framework::CredentialCollection#each when given a pass_file and user_file is expected to yield successive args(#<Metasploit::Framework::Credential "asdf:asdf" >, #<Metasploit::Framework::Credential "asdf:jkl" >, #<Metasploit::Framework::Credential "jkl:asdf" >, #<Metasploit::Framework::Credential "jkl:jkl" >)
    0.00121 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:113
  Metasploit::Framework::CredentialCollection#each when given a pass_file and username is expected to yield successive args(#<Metasploit::Framework::Credential "user:asdf" >, #<Metasploit::Framework::Credential "user:jkl" >)
    0.00116 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:67
  Metasploit::Framework::CredentialCollection#each when :blank_passwords is true is expected to yield successive args(#<Metasploit::Framework::Credential "user:pass" >, #<Metasploit::Framework::Credential "user:" >)
    0.00115 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:176
  Metasploit::Framework::CredentialCollection#each when given a user_file and password is expected to yield successive args(#<Metasploit::Framework::Credential "asdf:pass" >, #<Metasploit::Framework::Credential "jkl:pass" >)
    0.00104 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:49
  Metasploit::Framework::CredentialCollection#each when :user_as_pass is true is expected to yield successive args(#<Metasploit::Framework::Credential "user:pass" >, #<Metasploit::Framework::Credential "user:user" >)
    0.00101 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:156
  Metasploit::Framework::CredentialCollection#empty? when :username is set and :password is not set and :nil_passwords is true is expected to eq false
    0.00094 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:211

Finished in 0.02814 seconds (files took 3.13 seconds to load)
19 examples, 0 failures

Randomized with seed 29966
Coverage report generated for RSpec to /home/noam/src/metasploit-framework/coverage. 2150 / 11805 LOC (18.21%) covered.
```

**Comment by nrathaus** [comment]
My bad, I misinterpreted the outcome, on `main` I see no errors:
```
$ bundle exec rspec spec/lib/metasploit/framework/credential_collection_spec.rb
Overriding user environment variable 'OPENSSL_CONF' to enable legacy functions.
Run options:
  include {:focus=>true}
  exclude {:acceptance=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 29966
Metasploit::Framework::CredentialCollection ...................

Top 10 slowest examples (0.0159 seconds, 56.5% of total time):
  Metasploit::Framework::CredentialCollection#empty? when :username is set and :password is not set is expected to eq true
    0.00427 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:205
  Metasploit::Framework::CredentialCollection#each is expected to yield with args(Metasploit::Framework::Credential)
    0.00242 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:35
  Metasploit::Framework::CredentialCollection#each when given a userspass_file is expected to yield successive args(#<Metasploit::Framework::Credential "asdf:jkl" >, #<Metasploit::Framework::Credential "foo:bar" >)
    0.00149 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:87
  Metasploit::Framework::CredentialCollection#each when given a username, user_file and pass_file is expected to yield successive args(#<Metasploit::Framework::Credential "my_username:asdf" >, #<Metasploit::Framework::Credential "my_username:jkl" >, #<Metasploit::Framework::Credential "asdf:asdf" >, #<Metasploit::Framework::Credential "asdf:jkl" >, #<Metasploit::Framework::Credential "jkl:asdf" >, #<Metasploit::Framework::Credential "jkl:jkl" >)
    0.00121 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:142
  Metasploit::Framework::CredentialCollection#each when given a pass_file and user_file is expected to yield successive args(#<Metasploit::Framework::Credential "asdf:asdf" >, #<Metasploit::Framework::Credential "asdf:jkl" >, #<Metasploit::Framework::Credential "jkl:asdf" >, #<Metasploit::Framework::Credential "jkl:jkl" >)
    0.00121 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:113
  Metasploit::Framework::CredentialCollection#each when given a pass_file and username is expected to yield successive args(#<Metasploit::Framework::Credential "user:asdf" >, #<Metasploit::Framework::Credential "user:jkl" >)
    0.00116 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:67
  Metasploit::Framework::CredentialCollection#each when :blank_passwords is true is expected to yield successive args(#<Metasploit::Framework::Credential "user:pass" >, #<Metasploit::Framework::Credential "user:" >)
    0.00115 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:176
  Metasploit::Framework::CredentialCollection#each when given a user_file and password is expected to yield successive args(#<Metasploit::Framework::Credential "asdf:pass" >, #<Metasploit::Framework::Credential "jkl:pass" >)
    0.00104 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:49
  Metasploit::Framework::CredentialCollection#each when :user_as_pass is true is expected to yield successive args(#<Metasploit::Framework::Credential "user:pass" >, #<Metasploit::Framework::Credential "user:user" >)
    0.00101 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:156
  Metasploit::Framework::CredentialCollection#empty? when :username is set and :password is not set and :nil_passwords is true is expected to eq false
    0.00094 seconds ./spec/lib/metasploit/framework/credential_collection_spec.rb:211

Finished in 0.02814 seconds (files took 3.13 seconds to load)
19 examples, 0 failures

Randomized with seed 29966
Coverage report generated for RSpec to /home/noam/src/metasploit-framework/coverage. 2150 / 11805 LOC (18.21%) covered.
```

**Comment by nrathaus** [comment]
Should I add a test for the `password_spray` part to verify it works as expected?

**Comment by adfoster-r7** [comment]
That sounds good to me - thanks! 💯

**Comment by nrathaus** [comment]
I added a `spec`, but for some reason I get an error which I don't quite understand the root cause

It seems to be related to the inability to open the `user_file`, I don't see why it works when `password_spray` is false (the file is openable)
```
Randomized with seed 1002
Metasploit::Framework::CredentialCollection F

  1) Metasploit::Framework::CredentialCollection#each when given a pass_file and user_file and password spray is expected to yield successive args(#<Metasploit::Framework::Credential "user1:password1" >, #<Metasploit::Framework::Credential "user2:password1" >, #<Metasploit::Framework::Credential "user3:password1" >, #<Metasploit::Framework::Credential "user1:password2" >, #<Metasploit::Framework::Credential "user2:password2" >, #<Metasploit::Framework::Credential "user3:password2" >)
     Failure/Error: user_fd = File.open(user_file, 'r:binary')
       #<File (class)> asked to yield |[#<StringIO:0x000056262f2d9730>]| but no block was passed
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-support-3.13.0/lib/rspec/support.rb:110:in `block in <module:Support>'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-support-3.13.0/lib/rspec/support.rb:119:in `notify_failure'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/error_generator.rb:348:in `notify'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/error_generator.rb:332:in `__raise'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/error_generator.rb:143:in `raise_missing_block_error'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/message_expectation.rb:704:in `call'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/message_expectation.rb:761:in `block in call'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/message_expectation.rb:760:in `map'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/message_expectation.rb:760:in `call'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/message_expectation.rb:621:in `invoke_incrementing_actual_calls_by'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/message_expectation.rb:474:in `invoke'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/proxy.rb:209:in `message_received'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/proxy.rb:361:in `message_received'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/method_double.rb:98:in `proxy_method_invoked'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/verifying_proxy.rb:161:in `proxy_method_invoked'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-mocks-3.13.0/lib/rspec/mocks/method_double.rb:74:in `block (2 levels) in define_proxy_method'
     # ./lib/metasploit/framework/credential_collection.rb:248:in `each_unfiltered_password_first'
     # ./lib/metasploit/framework/credential_collection.rb:92:in `each_filtered'
     # ./spec/lib/metasploit/framework/credential_collection_spec.rb:144:in `block (5 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.13.0/lib/rspec/matchers/built_in/yield.rb:35:in `probe'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.13.0/lib/rspec/matchers/built_in/yield.rb:16:in `probe'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.13.0/lib/rspec/matchers/built_in/yield.rb:308:in `matches?'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.13.0/lib/rspec/expectations/handler.rb:51:in `block in handle_matcher'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.13.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.13.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.13.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-expectations-3.13.0/lib/rspec/expectations/expectation_target.rb:139:in `to'
     # ./spec/lib/metasploit/framework/credential_collection_spec.rb:144:in `block (4 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:263:in `instance_exec'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:263:in `block in run'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:486:in `block in run'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:352:in `call'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-rails-6.0.3/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:390:in `execute_with'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:352:in `call'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/hooks.rb:486:in `run'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example.rb:259:in `run'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:642:in `map'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:642:in `run_examples'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:607:in `run'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `block in run'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `map'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `run'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `block in run'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `map'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/example_group.rb:608:in `run'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.13.0/lib/rspec/core/runner.rb:121:in `map'
```

File: lib/metasploit/framework/credential_collection.rb [hunk 1]
```diff
@@ -219,12 +233,119 @@ def add_public(public_str='')
...
+    #   username2:password1
+    #   username3:password1
+    # ...
+    #   username1:password2
+    #   username2:password2
+    #   username3:password2
+    # ...
+    def each_unfiltered_password_first
+      if user_file.present?
+        user_fd = File.open(user_file, 'r:binary')
```
Comment (adfoster-r7) [inline lib/metasploit/framework/credential_collection.rb:248]: I didn't verify locally; but from an eyeball - I believe your test failure is caused by expecting a `proc` to be provided here:

```ruby
      let(:user_file) do
        filename = "user_file"
        stub_file = StringIO.new("user1\nuser2\nuser3\n")
        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file

        filename
      end
```

but you're using `File.open(...)` without a proc, unlike (I imagine) the original implementation/tests

Comment (nrathaus) [reply lib/metasploit/framework/credential_collection.rb:248]: I copied:
```
context "when given a pass_file and user_file" do
      let(:password) { nil }
      let(:username) { nil }
      let(:user_file) do
        filename = "user_file"
        stub_file = StringIO.new("asdf\njkl\n")
        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file

        filename
      end
      let(:pass_file) do
        filename = "pass_file"
        stub_file = StringIO.new("asdf\njkl\n")
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file

        filename
      end

      specify  do
        expect { |b| collection.each(&b) }.to yield_successive_args(
          Metasploit::Framework::Credential.new(public: "asdf", private: "asdf"),
          Metasploit::Framework::Credential.new(public: "asdf", private: "jkl"),
          Metasploit::Framework::Credential.new(public: "jkl", private: "asdf"),
          Metasploit::Framework::Credential.new(public: "jkl", private: "jkl"),
        )
      end
    end
```

And just added a param and made the user and pass more understandable

Comment (adfoster-r7) [reply lib/metasploit/framework/credential_collection.rb:248]: I believe your implementation differs, as you are doing:

```
        user_fd = File.open(user_file, 'r:binary')
```

Instead of:

```
       File.open(user_file, 'r:binary') do |user_fd|
          # ... do things with user_fd ...
       end
```

Therefore this mock fails:

```
        filename = "user_file"
        stub_file = StringIO.new("asdf\njkl\n")
        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
                                                          ^^^^^^^^^^^^^^^^^^^
```

So I think you'll want to either align the implementation with the test's expectations, or update the test to change its expectations - i.e. probably using `allow(File).to receive(:open).with(filename,/^r/).and_return stub_file` instead of `.and_yield stub_field`

Comment (nrathaus) [reply lib/metasploit/framework/credential_collection.rb:248]: Didn't help :(

Unfortunately my primary dev language is Python and not Ruby - so I struggling with this

I cannot change the way the credentials_collection.rb works, it has to open the user file at the beginning in order to be able to yield combinations of the same password and different usernames

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 2]
```diff
@@ -120,6 +121,37 @@
...
+        filename = "user_file"
+        stub_file = StringIO.new("user1\nuser2\nuser3\n")
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
+
+        filename
+      end
+      let(:pass_file) do
+        filename = "pass_file"
+        stub_file = StringIO.new("password1\npassword2\n")
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:138]: Hi @nrathaus, thanks for the pull request. I have looked into the failing tests locally and I believe this is what is needed.

```suggestion
        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
```

The previous implementation was returning the `pass_file` here:
https://github.com/rapid7/metasploit-framework/blob/13a79ab536b560f7aeb749afcb365f878794f170/lib/metasploit/framework/credential_collection.rb#L100

Then the credentials would be yielded within the loop:
https://github.com/rapid7/metasploit-framework/blob/13a79ab536b560f7aeb749afcb365f878794f170/lib/metasploit/framework/credential_collection.rb#L112

Where as now with your changes we will be doing the inverse of that logic. We return the `user_file` then yield the credentials when looping through the `pass_file`. Hopefully I explained that ok 😄

**Comment by nrathaus** [comment]
I have committed the changes as well as the rspec, I think we are ok with integration

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 3]
```diff
@@ -120,6 +121,37 @@
...
+        expect { |b| collection.each(&b) }.to yield_successive_args(
+          Metasploit::Framework::Credential.new(public: "user1", private: "password1"),
+          Metasploit::Framework::Credential.new(public: "user2", private: "password1"),
+          Metasploit::Framework::Credential.new(public: "user3", private: "password1"),
+          Metasploit::Framework::Credential.new(public: "user1", private: "password2"),
+          Metasploit::Framework::Credential.new(public: "user2", private: "password2"),
+          Metasploit::Framework::Credential.new(public: "user3", private: "password2"),
+        )
+      end
+    end
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:153]: Morning 👋 
I may have confused you with my explanation yesterday. I have added a diff with the exact changes that are needed for that test to pass 🤞 
```suggestion
    context "when given a pass_file and user_file and password spray" do
      let(:password) { nil }
      let(:username) { nil }
      let(:password_spray) { true }
      let(:user_file) do
        filename = "user_file"
        stub_file = StringIO.new("user1\nuser2\nuser3\n")
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file

        filename
      end
      let(:pass_file) do
        filename = "pass_file"
        stub_file = StringIO.new("password1\npassword2\n")
        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file

        filename
      end

      specify  do
        expect { |b| collection.each(&b) }.to yield_successive_args(
          Metasploit::Framework::Credential.new(public: "user1", private: "password1"),
          Metasploit::Framework::Credential.new(public: "user2", private: "password1"),
          Metasploit::Framework::Credential.new(public: "user3", private: "password1"),
          Metasploit::Framework::Credential.new(public: "user1", private: "password2"),
          Metasploit::Framework::Credential.new(public: "user2", private: "password2"),
          Metasploit::Framework::Credential.new(public: "user3", private: "password2"),
        )
      end
    end
```

File: lib/metasploit/framework/credential_collection.rb [hunk 4]
```diff
@@ -219,12 +233,119 @@ def add_public(public_str='')
       additional_publics << public_str
     end
 
-    # Combines all the provided credential sources into a stream of {Credential}
-    # objects, yielding them one at a time
-    #
-    # @yieldparam credential [Metasploit::Framework::Credential]
-    # @return [void]
-    def each_unfiltered
+    # When password spraying is enabled, do first passwords then userames
```
Comment (adfoster-r7) [inline lib/metasploit/framework/credential_collection.rb:236]:
```suggestion
    # When password spraying is enabled, do first passwords then usernames
```

File: lib/metasploit/framework/credential_collection.rb [hunk 5]
```diff
@@ -219,12 +233,119 @@ def add_public(public_str='')
...
+    #  i.e.
+    #   username1:password1
+    #   username2:password1
+    #   username3:password1
+    # ...
+    #   username1:password2
+    #   username2:password2
+    #   username3:password2
+    # ...
```
Comment (adfoster-r7) [inline lib/metasploit/framework/credential_collection.rb:245]:
```suggestion
    # ...
    # @yieldparam credential [Metasploit::Framework::Credential]
    # @return [void]    
```

File: lib/metasploit/framework/credential_collection.rb [hunk 6]
```diff
@@ -219,12 +233,119 @@ def add_public(public_str='')
...
+        end
+        additional_privates.each do |add_private|
+          yield Metasploit::Framework::Credential.new(public: add_public, private: add_private, realm: realm, private_type: private_type(add_private))
+        end
+      end
+    ensure
+      user_fd.close if user_fd && !user_fd.closed?
+    end
+
+    # When password spraying is not enabled, do first usersnames then passwords
```
Comment (adfoster-r7) [inline lib/metasploit/framework/credential_collection.rb:339]:
```suggestion
    # When password spraying is not enabled, do first usernames then passwords
```

File: lib/metasploit/framework/credential_collection.rb [hunk 7]
```diff
@@ -219,12 +233,119 @@ def add_public(public_str='')
...
+    #  i.e.
+    #   username1:password1
+    #   username1:password2
+    #   username1:password3
+    # ...
+    #   username2:password1
+    #   username2:password2
+    #   username2:password3
+    def each_unfiltered_username_first
```
Comment (adfoster-r7) [inline lib/metasploit/framework/credential_collection.rb:348]:
```suggestion
    # @yieldparam credential [Metasploit::Framework::Credential]
    # @return [void]    
    def each_unfiltered_username_first
```

File: lib/metasploit/framework/credential_collection.rb [hunk 8]
```diff
@@ -219,12 +233,119 @@ def add_public(public_str='')
...
+        if user_as_pass
+          yield Metasploit::Framework::Credential.new(public: username, private: username, realm: realm, private_type: :password)
+        end
+        if blank_passwords
+          yield Metasploit::Framework::Credential.new(public: username, private: "", realm: realm, private_type: :password)
+        end
+        if user_fd
+          user_fd.each_line do |user_from_file|
+            user_from_file.chomp!
+            yield Metasploit::Framework::Credential.new(public: user_from_file, private: password, realm: realm, private_type: private_type(pass_from_file))
```
Comment (cgranleese-r7) [inline lib/metasploit/framework/credential_collection.rb:273]: I assumed this should be password?
```suggestion
            yield Metasploit::Framework::Credential.new(public: user_from_file, private: password, realm: realm, private_type: private_type(password))
```

**Comment by nrathaus** [comment]
@cgranleese-r7 I added your suggestions - thank you for the review

**Review by cgranleese-r7 — APPROVED** [review]

**Comment by cgranleese-r7** [comment]
## Release Notes
Fixes an issue where the `password_spray` module option was being ignored.
