### PR TITLE
Fixes ssh_login gather proof issue when user has low privileges

### LINKED ISSUE #14351: ssh login windows gather proof does not work
## Steps to reproduce

Run `ssh_login` against a windows target.

## Expected behavior

Proof if gathered successfully

## Current behavior

Running against the hackthebox room fails:

```
use ssh login
run rhosts=10.10.10.184 username=nadine password=L1k3B1gBut7s@W0rk
```

```
> run rhosts=10.10.10.184 username=nadine password=L1k3B1gBut7s@W0rk

[+] 10.10.10.184:22 - Success: 'nadine:L1k3B1gBut7s@W0rk' ''id' is not recognized as an internal or external command,  operable program or batch file.  '
[*] Command shell session 6 opened (10.10.14.37:55940 -> 10.10.10.184:22) at 2020-11-05 01:43:52 +0000
[-] 10.10.10.184:22 - While a session may have opened, it may be bugged.  If you experience issues with it, re-run this module with 'set gatherproof false'.  Also consider submitting an issue at github.com/rapid7/metasploit-framework with device details so it can be handled in the future.
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/core]
loglevel=3

[framework/database]
default_db=local-https-data-service

[framework/database/local-https-data-service]
url=[Filtered]
cert=[Filtered]
skip_verify=[Filtered]
api_token=[Filtered]

[framework/features]
wrapped_tables=true
RHOST_HTTP_URL=true

[framework/ui/console]
ActiveModule=auxiliary/scanner/ssh/ssh_login

[scanner/ssh/ssh_login]
VERBOSE=false
WORKSPACE=
USERNAME=
PASSWORD=
USER_FILE=
PASS_FILE=
USERPASS_FILE=
BRUTEFORCE_SPEED=5
BLANK_PASSWORDS=false
USER_AS_PASS=false
DB_ALL_CREDS=false
DB_ALL_USERS=false
DB_ALL_PASS=false
STOP_ON_SUCCESS=false
REMOVE_USER_FILE=false
REMOVE_PASS_FILE=false
REMOVE_USERPASS_FILE=false
TRANSITION_DELAY=0
MaxGuessesPerService=0
MaxMinutesPerService=0
MaxGuessesPerUser=0
CreateSession=true
InitialAutoRunScript=
AutoRunScript=
CommandShellCleanupCommand=
RHOSTS=
THREADS=1
ShowProgress=true
ShowProgressPercent=10
RPORT=22
SSH_IDENT=SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
SSH_TIMEOUT=30
SSH_DEBUG=false
Proxies=
GatherProof=true
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
12576  use ssh login
12585  run rhosts=10.10.10.184 username=nadine password=L1k3B1gBut7s@W0rk
12586  debug
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.0.15-dev-9293e32f98
Ruby: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
Install Root: /Users/adfoster/Documents/code/metasploit-framework
Session Type: Connected to remote_data_service: (https://localhost:5443). Connection type: http.
Install Method: Git Clone
```

</details>

### PR DESCRIPTION
**Pull request by cgranleese-r7**
This PR Resolves #14351.

Previously when a user attempted to `ssh_login` when their user privileges were below admin they would get this error:

image

This was due to the user not having permissions to use the `systeminfo` command. 

This fix adds a fallback, that will resort to using the `ver` command if the user have permissions for `systeminfo`
Now when the same user from the error above tries to ssh in, they can now gain access. 

image

I also changed the value of `Timeout.timeout(5)` to a 10 second duration as I was encountering some issues with it being 5 seconds during testing.

## Verification

Setting up environment - steps I took, just incase they're off use: 

- [x] Get a windows environment running for your target 
- [x] Ensure you have a user with standard privileges that has a password set - as you can't ssh in without having a password set
- [x] May also need to install OpenSSH on your target machine

Test steps:

- [x] Start `msfconsole`
- [x] run `use auxiliary/scanner/ssh/ssh_login`
- [x] run `run RHOSTS=xxx.xxx.xxx.xxx username=xxx password=xxxxxxxx`
- [x] **Verify** that you gain access successfully and no longer receive the error above when using the low privilege user
- [x] Repeat steps above for admin user to ensure previous functionality remains

### CODE REVIEW

**Comment by h00die** [comment]
Looking at the screenshot, it may need a trim/strip to get rid of the pre/post spaces.

**Comment by cgranleese-r7** [comment]
> Looking at the screenshot, it may need a trim/strip to get rid of the pre/post spaces.

Good spot, got that fixed. Thanks @h00die 👍

File: lib/metasploit/framework/login_scanner/ssh.rb [hunk 1]
```diff
@@ -162,6 +162,9 @@ def gather_proof
                   proof = ssh_socket.exec!("systeminfo\n").to_s
                   /OS Name:\s+(?<os_name>.+)$/ =~ proof
                   /OS Version:\s+(?<os_num>.+)$/ =~ proof
+                  if os_num.nil? || os_name.nil?
+                    proof = ssh_socket.exec!("ver\n").to_s.strip
+                  end
                   if os_name && os_num
                     proof = "#{os_name.chomp} #{os_num.chomp}"
                   end
```
Comment (adfoster-r7) [inline lib/metasploit/framework/login_scanner/ssh.rb:170]:
```suggestion
                  if os_num.present? && os_name.present?
                    proof = "#{os_name.chomp} #{os_num.chomp}"
                  else
                    proof = ssh_socket.exec!("ver\n").strip
                  end
```

File: lib/metasploit/framework/login_scanner/ssh.rb [hunk 2]
```diff
@@ -162,8 +162,10 @@ def gather_proof
                   proof = ssh_socket.exec!("systeminfo\n").to_s
                   /OS Name:\s+(?<os_name>.+)$/ =~ proof
                   /OS Version:\s+(?<os_num>.+)$/ =~ proof
-                  if os_name && os_num
-                    proof = "#{os_name.chomp} #{os_num.chomp}"
+                  if os_num.present? && os_name.present?
+                    proof = "#{os_name.strip} #{os_num.strip}"
+                  else
+                    proof = ssh_socket.exec!("ver\n").strip
```
Comment (adfoster-r7) [inline lib/metasploit/framework/login_scanner/ssh.rb:168]: Just realizing, I think the use of `to_s` was required in case nil is returned

```suggestion
                    proof = ssh_socket.exec!("ver\n").to_s.strip
```

**Comment by todb-r7** [comment]
Works for me!

Current version:
image


Working version:
image

@adfoster-r7 happy to merge this if you like.

**Comment by adfoster-r7** [comment]
## Release Notes

Improves the ssh_login module when attempting to gather proof with low privilege windows user. This module will now gracefully fall back to using the `ver` command if the required permissions to run `systeminfo` are missing.
