### PR TITLE
Fix usage of `Failure::` constant

### LINKED ISSUE #14724: NameError
0

meterpreter > ls
[-] Unknown command: ls.
meterpreter > ll
[-] Unknown command: ll.
meterpreter > 
[*] xxxxx- Meterpreter session 4 closed.  Reason: Died
de
[-] Unknown command: de.
msf6 exploit(linux/http/saltstack_salt_api_cmd_exec) > debug
Please provide the below information in any Github issues you open. New issues can be opened here https://github.com/rapid7/metasploit-framework/issues/new/choose
ENSURE YOU HAVE REMOVED ANY SENSITIVE INFORMATION BEFORE SUBMITTING!

===8<=== CUT AND PASTE EVERYTHING BELOW THIS LINE ===8<===

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/ui/console]
ActiveModule=exploit/linux/http/saltstack_salt_api_cmd_exec

[linux/http/saltstack_salt_api_cmd_exec]
SSL=true
WORKSPACE=
VERBOSE=false
PAYLOAD=linux/x64/meterpreter/bind_tcp
WfsDelay=0
EnableContextEncoding=false
ContextInformationFile=
DisablePayloadHandler=false
EXE::EICAR=false
EXE::Custom=
EXE::Path=
EXE::Template=
EXE::Inject=false
EXE::OldMethod=false
EXE::FallBack=false
MSI::EICAR=false
MSI::Custom=
MSI::Path=
MSI::Template=
MSI::UAC=false
SRVHOST=0.0.0.0
SRVPORT=8080
ListenerComm=
SSLCert=
SSLCompression=false
SSLCipher=
TCP::max_send_size=0
TCP::send_delay=0
RHOSTS=xxxxx
RPORT=443
VHOST=
Proxies=
UserAgent=Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
HttpUsername=
HttpPassword=
HttpRawHeaders=
DigestAuthIIS=true
SSLVersion=Auto
FingerprintCheck=true
DOMAIN=WORKSTATION
HttpClientTimeout=
HttpTrace=false
HttpTraceHeadersOnly=false
HttpTraceColors=red/blu
HTTP::uri_encode_mode=hex-normal
HTTP::uri_full_url=false
HTTP::pad_method_uri_count=1
HTTP::pad_uri_version_count=1
HTTP::pad_method_uri_type=space
HTTP::pad_uri_version_type=space
HTTP::method_random_valid=false
HTTP::method_random_invalid=false
HTTP::method_random_case=false
HTTP::version_random_valid=false
HTTP::version_random_invalid=false
HTTP::uri_dir_self_reference=false
HTTP::uri_dir_fake_relative=false
HTTP::uri_use_backslashes=false
HTTP::pad_fake_headers=false
HTTP::pad_fake_headers_count=0
HTTP::pad_get_params=false
HTTP::pad_get_params_count=16
HTTP::pad_post_params=false
HTTP::pad_post_params_count=16
HTTP::uri_fake_end=false
HTTP::uri_fake_params_start=false
HTTP::header_folding=false
URIPATH=
HTTP::no_cache=false
HTTP::chunked=false
HTTP::junk_headers=false
HTTP::compression=none
HTTP::server_name=Apache
URIHOST=
URIPORT=
SendRobots=false
CMDSTAGER::FLAVOR=bourne
CMDSTAGER::DECODER=
CMDSTAGER::TEMP=
CMDSTAGER::SSL=false
TARGETURI=/
AutoCheck=true
ForceExploit=true
LHOST=192.168.61.129
LPORT=4444
ReverseListenerBindPort=
ReverseAllowProxy=false
ReverseListenerComm=
ReverseListenerBindAddress=
ReverseListenerThreaded=false
StagerRetryCount=10
StagerRetryWait=5
HandlerSSLCert=
CreateSession=true
InitialAutoRunScript=
AutoRunScript=
CommandShellCleanupCommand=
target=1
AutoLoadStdapi=true
AutoVerifySession=true
AutoVerifySessionTimeout=30
AutoSystemInfo=true
EnableUnicodeEncoding=false
SessionRetryTotal=3600
SessionRetryWait=10
SessionExpirationTimeout=604800
SessionCommunicationTimeout=300
PayloadProcessCommandLine=
AutoUnhookProcess=false
PingbackRetries=0
PingbackSleep=30
PayloadUUIDSeed=
PayloadUUIDRaw=
PayloadUUIDName=
PayloadUUIDTracking=false
EnableStageEncoding=false
StageEncoder=
StageEncoderSaveRegisters=
StageEncodingFallback=true
PrependFork=false
PrependSetresuid=false
PrependSetreuid=false
PrependSetuid=false
PrependSetresgid=false
PrependSetregid=false
PrependSetgid=false
PrependChrootBreak=false
AppendExit=false
MeterpreterDebugLevel=3
RemoteMeterpreterDebugFile=
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
419    set payload windows/meterpreter/reverse_tcp
420    run
421    show targets
422    set  target 3
423    set payload windows/x64/meterpreter/bind_tcp
424    run
425    set ForceExploit run
426    set ForceExploit true
427    run
428    set payload windows/x64/meterpreter/reverse_http
429    run
430    set payload windows/meterpreter/reverse_tcp
431    run
432    set ForceExploit true
433    run
434    options
435    use exploit/multi/misc/weblogic_deserialize_badattr_extcomp
436    options
437    show targets
438    use exploit/multi/misc/weblogic_deserialize_badattrval
439    options
440    2 show targets
441    show targets
442    use exploit/linux/http/saltstack_salt_api_cmd_exec
443    options
444    set RHOSTS xxxxx
445    set RPORT 443
446    set ssl true
447    set LHOST eth0
448    show targets
449    set target1
450    set target 1
451    show payloads
452    set payload linux/x64/meterpreter/bind_tcp
453    run
454    set ForceExploit true
455    run
456    ll
457    ls
458       
459    .
460    /
461    debug
462    options
463    set MeterpreterDebugLevel 3
464    run
465    ls
466    ll
467    de
468    debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[02/04/2021 16:46:32] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:46:42] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:46:52] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:02] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:12] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:22] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:32] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:42] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:52] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:48:02] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[02/04/2021 16:40:31] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:40:38] [i(0)] core: php/meterpreter/bind_tcp: iteration 1: Successfully encoded with encoder php/base64 (size is 1807)
[02/04/2021 16:40:41] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:40:51] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:41:01] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:41:11] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:41:19] [i(0)] core: php/meterpreter/bind_tcp: iteration 1: Successfully encoded with encoder php/base64 (size is 1807)
[02/04/2021 16:41:21] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:41:31] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:41:41] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:41:51] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:42:01] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:42:11] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:42:21] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:42:31] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:42:41] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:42:51] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:43:01] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:43:11] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:43:21] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:43:31] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:43:41] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:43:51] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:44:01] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:44:11] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:44:21] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:44:31] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:44:41] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:44:51] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:45:01] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:45:11] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:45:21] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:45:31] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:45:41] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:45:52] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:46:02] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:46:12] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:46:22] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:46:32] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:46:42] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:46:52] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:02] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:12] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:22] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:32] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:42] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:47:52] [e(0)] core: Auxiliary failed - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:48:02] [e(0)] core: Exploit failed (linux/misc/saltstack_salt_unauth_rce): NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure - NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[02/04/2021 16:52:12] [w(0)] core: Exception in scheduler thread Rex::TimeoutError Operation timed out.
[02/04/2021 16:53:59] [w(0)] core: Session 4 has died
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.0.28-dev
Ruby: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
Install Root: /usr/share/metasploit-framework
Session Type: postgresql selected, no connection
Install Method: Other - Please specify
```

</details>

### PR DESCRIPTION
**Pull request by dwelch-r7**
Resolves #14724 

Replaces all usages of `Failure::` outside of the modules with the full constant name since it doesn't resolve correctly unless you do this

Previously:
```
[!] [2021.02.12-14:40:57] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] [2021.02.12-14:40:58] Started HTTPS reverse handler on https://127.0.0.1:8443
[*] [2021.02.12-14:40:58] 216.58.210.46:443 - Using auxiliary/gather/saltstack_salt_root_key as check
[*] [2021.02.12-14:40:58] 216.58.210.46:443 - Connecting to ZeroMQ service at 216.58.210.46:443
[*] [2021.02.12-14:40:58] 216.58.210.46:443 - Negotiating signature
[-] [2021.02.12-14:41:08] 216.58.210.46:443 - Auxiliary failed: NameError uninitialized constant Msf::Exploit::Remote::ZeroMQ::Failure
[-] [2021.02.12-14:41:09] 216.58.210.46:443 - Call stack:
[-] [2021.02.12-14:41:09] 216.58.210.46:443 -   /home/dwelch/dev/metasploit-framework/lib/msf/core/exploit/remote/zeromq.rb:41:in `zmq_negotiate_signature'
[-] [2021.02.12-14:41:09] 216.58.210.46:443 -   /home/dwelch/dev/metasploit-framework/lib/msf/core/exploit/remote/zeromq.rb:31:in `zmq_negotiate'
[-] [2021.02.12-14:41:09] 216.58.210.46:443 -   /home/dwelch/dev/metasploit-framework/modules/auxiliary/gather/saltstack_salt_root_key.rb:65:in `run'
[*] [2021.02.12-14:41:09] 216.58.210.46:443 - Connecting to ZeroMQ service at 216.58.210.46:443
```

Now:
```
[!] [2021.02.12-14:40:09] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] [2021.02.12-14:40:09] Started HTTPS reverse handler on https://127.0.0.1:8443
[*] [2021.02.12-14:40:09] 216.58.210.46:443 - Using auxiliary/gather/saltstack_salt_root_key as check
[*] [2021.02.12-14:40:09] 216.58.210.46:443 - Connecting to ZeroMQ service at 216.58.210.46:443
[*] [2021.02.12-14:40:09] 216.58.210.46:443 - Negotiating signature
[-] [2021.02.12-14:40:19] 216.58.210.46:443 - Auxiliary aborted due to failure: unknown: Did not receive signature
[*] [2021.02.12-14:40:19] 216.58.210.46:443 - Connecting to ZeroMQ service at 216.58.210.46:443
```

# Verification steps
- [ ] `use exploit/linux/misc/saltstack_salt_unauth_rce`
- [ ] `set LHOST 127.0.0.1`
- [ ] `set RHOST google.com`
- [ ] `run`

### CODE REVIEW

File: lib/msf/core/auxiliary/mqtt.rb [hunk 1]
```diff
@@ -24,11 +24,11 @@ def initialize(info = {})
       end
 
       def setup
```
Comment (adfoster-r7) [inline lib/msf/core/auxiliary/mqtt.rb:26]: Is this dead code? Looks like the only use of this mixin is

```
modules/auxiliary/scanner/mqtt/connect.rb
```

Which doesn't call this code as it uses the `include Msf::Auxiliary::AuthBrute` which doesn't call `super` in its `setup` method? 👀 

```
>> self.class
=> Msf::Modules::Auxiliary__Scanner__Mqtt__Connect::MetasploitModule
>> self.method(:setup).source_location
=> 
["/Users/adfoster/Documents/code/metasploit-framework/lib/msf/core/auxiliary/auth_brute.rb",
 48]
```

I'm guessing it was previously tested, but broken accidentally? 🤷 
https://github.com/rapid7/metasploit-framework/commit/ed5f177fcd70248c607a4df17f526dec39fe5826#diff-b9616f8dab41c6c04e2c53235d97941154ff73e87cbad03308b5cffeeff5063bL10-R14

Comment (adfoster-r7) [reply lib/msf/core/auxiliary/mqtt.rb:26]: Removing that AuthBrute mixin works:
```
>> self.method(:setup).source_location
=> 
["/Users/adfoster/Documents/code/metasploit-framework/lib/msf/core/auxiliary/mqtt.rb",
 26]
```

And shows the constant exception now:
```
msf6 auxiliary(scanner/mqtt/connect) > run
[-] Auxiliary failed: Msf::OptionValidateError One or more options failed to validate: RHOSTS.
msf6 auxiliary(scanner/mqtt/connect) > run rhosts=127.0.0.1

[-] 127.0.0.1:1883        - Auxiliary failed: NameError uninitialized constant Msf::Auxiliary::MQTT::Failure
[-] 127.0.0.1:1883        - Call stack:
[-] 127.0.0.1:1883        -   /Users/user/Documents/code/metasploit-framework/lib/msf/core/auxiliary/mqtt.rb:27:in `setup'
[*] Auxiliary module execution completed
```

**Comment by adfoster-r7** [comment]
## Release Notes

Updates `exploit/linux/http/saltstack_salt_api_cmd_exec` to correctly show failure messages to the user under error scenarios
