### PR TITLE
Fix #10785, incorrect implementation of "show evasion" command

### LINKED ISSUE #10785: error while running 'show evasion'
```
msf5 > show evasion                                                                             
 [-] Error while running command show: wrong number of arguments (given 0, expected 1)                                                                                                               
Call stack:                                                                                       
/data/data/com.termux/files/home/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:1026:in `show_evasion'                                                                       
/data/data/com.termux/files/home/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:518:in `block in cmd_show'                                                                   
/data/data/com.termux/files/home/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:493:in `each'                                                                                
/data/data/com.termux/files/home/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:493:in `cmd_show'                                                                            
/data/data/com.termux/files/home/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:502:in `run_command'                                                                                      
/data/data/com.termux/files/home/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:453:in `block in run_single'                                                                              
/data/data/com.termux/files/home/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:447:in `each'                                                                                             
/data/data/com.termux/files/home/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:447:in `run_single'                                                                                       
/data/data/com.termux/files/home/metasploit-framework/lib/rex/ui/text/shell.rb:151:in `run'       /data/data/com.termux/files/home/metasploit-
framework/lib/metasploit/framework/command/console.rb:48:in `start'                                                                                     
/data/data/com.termux/files/home/metasploit-
framework/lib/metasploit/framework/command/base.rb:82:in `start'                                                                                        
./msfconsole:49:in `<main>'

```

### PR DESCRIPTION
**Pull request by wchen-r7**
Fix #10785

This fixes the `show evasion` command.

- [x] To verify, go to msfconsole, and then type `show evasion`. This should give you a list of evasion modules.
- [x] Next, pick a module: `use evasion/windows/windows_defender_exe`, and then type `show evasion` again. This time, you should get an option menu.

### CODE REVIEW

**Comment by Auxilus** [comment]
thanks!

File: lib/msf/ui/console/command_dispatcher/modules.rb [hunk 1]
```diff
@@ -1022,8 +1020,8 @@ def show_missing(mod) # :nodoc:
             end
           end
 
-          def show_evasion(mod)
-            puts "Place holder for show_evasion"
```
Comment (wvu-r7) [inline lib/msf/ui/console/command_dispatcher/modules.rb]: 🙃

**Review by wvu — APPROVED** [review]
