### PR TITLE
Move `on_session_open` event to after the session has been bootstrapped

### LINKED ISSUE #14594: auto_add_route plugin breaks linux  meterpreter
## Steps to reproduce

How'd you do it?

1. msfvenom -a x64 --platform linux  -p linux/x64/meterpreter/reverse_tcp lhost=127.0.0.1 lport=9000 -f elf -o linux
2. use linux/x64/meterpreter/reverse_tcp
3. run the handler 
4. then run the executable all on same KALI system.
5. I get a connect back but no commands work.
6. I get unknown command.

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Were you following a specific guide/tutorial or reading documentation?
no

If yes link the guide/tutorial or documentation you were following here, otherwise you may omit this section.

## Expected behavior

Should have gotten shell

What should happen?

Should have gotten shell like with windows.

## Current behavior

Nothing but unknown command.
I did a tcpdump and it looks like its just stopping.
Does same with non staged payload.

What happens instead?
see above.
### Metasploit version
6.xx
Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

## Additional Information
If your version is less than `5.0.96`, please update to the latest version and ensure your issue is still present.

If the issue is encountered within `msfconsole`, please run the `debug` command using the instructions below. If the issue is encountered outisde `msfconsole`, or the issue causes `msfconsole` to crash on startup, please delete this section.

1. Start `msfconsole`
2. Run the command `set loglevel 3`
3. Take the steps necessary recreate your issue
4. Run the `debug` command
5. Copy all the output below the `===8<=== CUT AND PASTE EVERYTHING BELOW THIS LINE ===8<===` line and make sure to **REMOVE ANY SENSITIVE INFORMATION.**
6. Replace these instructions and the paragraph above with the output from step 5.

### PR DESCRIPTION
**Pull request by dwelch-r7**
Resolves #14594 

The `on_session_open` event was being triggered _before_ the session was being properly initialised so I moved things around a bit to trigger it only after the session finished it's bootstrap process. The reason this was a problem was that the `auto_add_route` extension needs the `stdapi` loaded in meterpreter but trying to load that before bootstrapping does not work.

# Verification
- [x] Load up msfconsole `./msfconsole`
- [x] `load auto_add_route`
- [x] Use your favourite method to get a meterpreter session
- [x] When the session pops you should now see somethign like:
```
[*] Meterpreter session 1 opened (192.168.1.10:8080 -> 127.0.0.1) at 2021-03-02 15:38:49 +0000
[*] AutoAddRoute: Routing new subnet 10.0.2.0/255.255.255.0 through session 1
```
- [ ] The `route` command should show a table just created entry
- [ ] Interact with the session `sessions -1`
- [ ] Commands such as `ls` and `pwd` should work

### CODE REVIEW

File: lib/msf/base/sessions/meterpreter.rb [hunk 1]
```diff
@@ -199,6 +199,15 @@ def bootstrap(datastore = {}, handler = nil)
...
       handler.on_session(self) if handler
+
+      # Notify the framework that we have a new session opening up...
+      # Don't let errant event handlers kill our session
+      begin
+        framework.events.on_session_open(session)
+      rescue ::Exception => e
+        wlog("Exception in on_session_open event handler: #{e.class}: #{e}")
+        wlog("Call Stack\n#{e.backtrace.join("\n")}")
+      end
```
Comment (dwelch-r7) [inline lib/msf/base/sessions/meterpreter.rb:210]: I moved this block from inside a statement like `if session.register?`
`session.register?` only seems to return `false` for a  vncinject session, I don't fully understand why you don't register that kind of session but I didn't see any reason why you would't want to trigger this event on that kind of a session so I left it out, but I can add it back in if anyone has more insight

**Comment by smcintyre-r7** [comment]
While this makes sense, if the `auto_add_route` plugin needs the `stdapi` extension to be loaded, then it should probably load it itself since autoloading stdapi can be disabled by setting `AutoLoadStdapi` to false.

**Comment by dwelch-r7** [comment]
> While this makes sense, if the `auto_add_route` plugin needs the `stdapi` extension to be loaded, then it should probably load it itself since autoloading stdapi can be disabled by setting `AutoLoadStdapi` to false.

It does load it itself: https://github.com/rapid7/metasploit-framework/blob/5576a2c4e9df8a465ffe57486fb7af9cb59b46a1/plugins/auto_add_route.rb#L17

The problem was it was trying to load stdapi _before_ the session was fully initialised, the move wasn't so that stdapi would be loaded first

File: lib/msf/core/session_manager.rb [hunk 2]
```diff
@@ -217,15 +217,6 @@ def register(session)
       # Insert the session into the session hash table
       self[next_sid.to_i] = session
 
-      # Notify the framework that we have a new session opening up...
-      # Don't let errant event handlers kill our session
-      begin
```
Comment (acammack-r7) [inline lib/msf/core/session_manager.rb:222]: We'll need a version of this here to continue to handle other types of sessions (e.g. shell).

**Comment by smcintyre-r7** [comment]
Alright I tested this pretty thoroughly and everything looks good. My only concern is that the session opened message is displayed twice now. I tested the Python Meterpreter, Linux Meterpreter, Python Shell sessions with and without the libnotify and auto_add_route plugins enabled.

```
msf6 payload(python/meterpreter/reverse_tcp) > to_handler 
[*] Payload Handler Started as Job 0
msf6 payload(python/meterpreter/reverse_tcp) > 
[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] Sending stage (39344 bytes) to 192.168.159.128
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.128:39582) at 2021-03-19 13:15:41 -0400
[*] Meterpreter session 1 opened (192.168.159.128:4444 -> 192.168.159.128:39582) at 2021-03-19 13:15:42 -0400
msf6 payload(python/meterpreter/reverse_tcp) > [*] Sending stage (39344 bytes) to 192.168.159.128
[*] Meterpreter session 2 opened (192.168.159.128:4444 -> 192.168.159.128:39588) at 2021-03-19 13:16:08 -0400
[*] Meterpreter session 2 opened (192.168.159.128:4444 -> 192.168.159.128:39588) at 2021-03-19 13:16:08 -0400

msf6 payload(python/meterpreter/reverse_tcp) >
```

**Comment by acammack-r7** [comment]
Yeah, looks like the `on_session_open` event is being processed twice now. `SessionManager#register` still does the thing on registration: https://github.com/rapid7/metasploit-framework/blob/9bee43d660e737bf02c1267f80d0a7363fde60e6/lib/msf/core/session_manager.rb#L223

**Comment by dwelch-r7** [comment]
ah thanks @acammack-r7 not sure how I managed to forget to remove that, will fix cheers

**Comment by smcintyre-r7** [comment]
Looking good now, that second open message is no longer present and everything else is still working. I'll merge this in shortly. Thanks @dwelch-r7 !

**Comment by smcintyre-r7** [comment]
# Release Notes
This moves the on_session_open event until after the session has been bootstrapped which is necessary to expose some functionality required by plugins such as auto_add_route.
