### PR TITLE
fix shellcode_inject module

### LINKED ISSUE #15348: Post failed: NoMethodError undefined method `has_pid?' for #<Msf::Modules::Post__Windows__Manage__Shellcode_inject::MetasploitModule:0x00007f96d4d84bf0>
After updating to metasploit 6.0.48-dev I've been facing this problem maybe with all the operating systems that I've been pentesting
msf6 post(windows/manage/shellcode_inject) > set shellcode x.bin
shellcode => miners/x.bin
msf6 post(windows/manage/shellcode_inject) > set pid 4880
pid => 4880
msf6 post(windows/manage/shellcode_inject) > options

Module options (post/windows/manage/shellcode_inject):

   Name         Current Setting  Required  Description
   ----         ---------------  --------  -----------
   AUTOUNHOOK   false            yes       Auto remove EDRs hooks
   BITS         64               yes       Set architecture bits (Accepted: 32, 64)
   CHANNELIZED  false            yes       Retrieve output of the process
   HIDDEN       true             yes       Spawn an hidden process
   INTERACTIVE  false            yes       Interact with the process
   PID          4880             no        Process Identifier of process to inject the shellcode. (0 = new process)
   PPID         0                no        Process Identifier for PPID spoofing when creating a new process. (0 = no PPID spoofing)
   SESSION      1                yes       The session to run this module on.
   SHELLCODE    x.bin     yes       Path to the shellcode to execute
   WAIT_UNHOOK  5                yes       Seconds to wait for unhook to be executed

msf6 post(windows/manage/shellcode_inject) > run

[*] Running module against Lab7
[-] Post failed: NoMethodError undefined method `has_pid?' for #<Msf::Modules::Post__Windows__Manage__Shellcode_inject::MetasploitModule:0x00007f96d4d84bf0>
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/post/windows/manage/shellcode_inject.rb:88:in `run'
[*] Post module execution completed
msf6 post(windows/manage/shellcode_inject) >

## Expected behavior
Shellcode get injected in the remote process

## Current behavior

[-] Post failed: NoMethodError undefined method `has_pid?' for #<Msf::Modules::Post__Windows__Manage__Shellcode_inject::MetasploitModule:0x00007f96d4d84bf0>

### Metasploit version

6.0.48-dev

## Additional Information
I checked the path of the module that I am using and noticed that the function is defined and exists in both files (shellcode_inject.rb and process.rb). I really don't know why it keeps showing me error.

### PR DESCRIPTION
**Pull request by pingport80**
## Summary
Fixes #15348 where the `shellcode_inject` module was crashing because the new process mixin was not included. Thanks to @adfoster-r7 for pointing out what was causing the issue. :+1: 

## Verification Steps
```
msf6 post(windows/manage/shellcode_inject) > rerun 
[*] Reloading module...
[*] Running module against AKKI
[*] Spawned Notepad process 10896
[+] Successfully injected payload into process: 10896
[*] Retrieving output
[*] Incoming UUID = dae8dade75dd4d6393c61ca5ba7a3ba3
[!] WARNING: UUID verification and logging is not available, because the database is not active.
[*] Pingback session 12 opened (192.168.29.232:4445 -> 127.0.0.1) at 2021-06-17 18:50:00 +0530
[*] Post module execution completed
msf6 post(windows/manage/shellcode_inject) > [*] Pingback session 13 opened (192.168.29.232:4445 -> 127.0.0.1) at 2021-06-17 18:50:04 +0530
[*] Pingback session 14 opened (192.168.29.232:4445 -> 127.0.0.1) at 2021-06-17 18:50:06 +0530
```

### CODE REVIEW

File: modules/post/windows/manage/shellcode_inject.rb [hunk 1]
```diff
@@ -7,6 +7,7 @@
 class MetasploitModule < Msf::Post
   include Msf::Post::Common
   include Msf::Post::Windows::Process
+  include Msf::Post::Process
```
Comment (adfoster-r7) [inline modules/post/windows/manage/shellcode_inject.rb:10]: Just to re-ask this question so it isn't lost:

https://github.com/rapid7/metasploit-framework/issues/15348#issuecomment-862794821

Will this be an issue with the modules that only include the system specific mixins? i.e. Do the system specific mixins, now also need the more generic mixin included?

Comment (smcintyre-r7) [reply modules/post/windows/manage/shellcode_inject.rb:10]: I think it would make sense to include the generic mixin in the system-specific mixins since the system-specific functionality should be a superset of the generic functionality.

Comment (pingport80) [reply modules/post/windows/manage/shellcode_inject.rb:10]: I don't think so but I will check if any module requires the mixin and not including it. :+1:

Comment (pingport80) [reply modules/post/windows/manage/shellcode_inject.rb:10]: You were right! There were 3 modules which required this mixin but weren't including. I've added it :+1:

Comment (pingport80) [reply modules/post/windows/manage/shellcode_inject.rb:10]: should I instead add `process` mixin in `windows::process` mixin?

Comment (pingport80) [reply modules/post/windows/manage/shellcode_inject.rb:10]: sure, that makes much more sense then adding to them individually :+1:

File: lib/msf/core/post/windows/process.rb [hunk 2]
```diff
@@ -8,6 +8,7 @@ module Windows
 module Process
 
   include Msf::Post::Windows::ReflectiveDLLInjection
+  include Msf::Post::Process
```
Comment (adfoster-r7) [inline lib/msf/core/post/windows/process.rb:11]: Do we need to add it to all of the system specifix mixins? i.e. these methods were also deleted from
lib/msf/core/post/linux/system.rb
lib/msf/core/post/solaris/system.rb
lib/msf/core/post/linux/system.rb

This looks like a breaking change to me, so we should probably include this line in the other places that were impacted - otherwise we can break modules that we don't own/maintain within this repository

I'm guessing that's why this module needed to explicitly add this mixin manually? 👀 
https://github.com/rapid7/metasploit-framework/pull/15260/files#diff-3f287c6a5c2c30af56a73b0479f3c378502dc75b8a3538e482b939bdae24e0da

Comment (pingport80) [reply lib/msf/core/post/windows/process.rb:11]: I guess one method was deleted in an earlier PR because it was not being used by any module.

Comment (pingport80) [reply lib/msf/core/post/windows/process.rb:11]: Hey, I looked at those 2 mixins and modules it's not using any methods from the `process` mixin, I guess this is now included in the modules which require it :)

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes a regression issue in the `windows/manage/shellcode_inject` module which crashed due to a missing mixin
