### PR TITLE
Fix PostgreSQL 15+ public schema permission issue

### LINKED ISSUE #20649: DB (Postgres) - ERROR: relation "workspaces" does not exist
## Steps to reproduce

How'd you do it?

Arch Linux

1. sudo pacman -S metasploit , just installs metasploit
1. `cd /opt/metasploit`
1. `gem install bundler`
1. `bundle install` -> `bundle complete, 19 gemfile dependencies`
1. docker run postgres, `docker run --name some-postgres -e POSTGRES_PASSWORD=postgres -d postgres
`
1. `msfdb init --connection-string="postgresql://postgres:postgres@127.0.0.1:5432/postgres"`
1. `Database initialization successful`
1. `msfconsole -y ~/.msf4/database.yaml`
1. terminal error:
```
/opt/metasploit/vendor/bundle/ruby/3.4.0/gems/activerecord-7.2.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in 'PG::Connection#exec': PG::UndefinedTable: ERROR:  relation "workspaces" does not exist (ActiveRecord::StatementInvalid)
LINE 10:  WHERE a.attrelid = '"workspaces"'::regclass
```
1. postgres error:
```
2025-10-24 08:39:22.431 UTC [72] ERROR:  permission denied for schema public at character 14
2025-10-24 08:39:22.431 UTC [72] STATEMENT:  CREATE TABLE "schema_migrations" ("version" character varying NOT NULL PRIMARY KEY)
2025-10-24 08:39:22.442 UTC [72] ERROR:  relation "workspaces" does not exist at character 523
2025-10-24 08:39:22.442 UTC [72] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
	       c.collname, col_description(a.attrelid, a.attnum) AS comment,
	       attidentity AS identity,
	       attgenerated as attgenerated
	  FROM pg_attribute a
	  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	  LEFT JOIN pg_type t ON a.atttypid = t.oid
	  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
	 WHERE a.attrelid = '"workspaces"'::regclass
	   AND a.attnum > 0 AND NOT a.attisdropped
	 ORDER BY a.attnum
	
```
1. I logged into the postgres to check the table
```
msf=> SELECT attrelid
msf-> FROM pg_attribute
msf-> WHERE attrelid = "workspace";
ERROR:  column "workspace" does not exist
LINE 3: WHERE attrelid = "workspace";
```

## Were you following a specific guide/tutorial or reading documentation?

If yes link the guide/tutorial or documentation you were following here, otherwise you may omit this section.
- https://wiki.archlinux.org/title/Metasploit_Framework (skipped rvm stage)
- https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html

## Expected behavior

Get into the msfconsole

## Current behavior

Error occurs on startup

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

`Framework Version: 6.4.92-dev`

## Additional Information
Deleted the text here per the issue instructions

I think there is something in the ruby code where the `workspace`-field should actually become an integer, but it isn't. Because the whole sql table column is only integers. I don't know ruby unfortunately, otherwise I would've digged into the source. 

Have a great day and thank you for reading my post.

### PR DESCRIPTION
**Pull request by rmtsixq**
# Fix PostgreSQL 15+ Public Schema Permission Issue

## Summary

Fixes database initialization failure when using `msfdb init` with `--connection-string` option to connect to PostgreSQL 15+ instances (e.g., Docker containers).

## Problem

When initializing Metasploit database with a standalone PostgreSQL 15+ connection, the following errors occur:

```
PG::UndefinedTable: ERROR: relation "workspaces" does not exist
ERROR: permission denied for schema public at character 14
```

**Root Cause:** PostgreSQL 15+ changed default permissions - users can no longer create objects in the `public` schema without explicit `GRANT` permissions. When using `--connection-string`, the privileged user (e.g., `postgres`) creates the databases, but the `msf` user lacks permission to create tables.

## Solution

Added explicit `GRANT ALL ON SCHEMA public` permissions to the `msf` and `msftest` users after database creation in `lib/msfdb_helpers/standalone.rb`.

### Steps to Reproduce (Before Fix)

1. Start PostgreSQL 16 container:
   ```bash
   docker run --name test-postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres:16
   ```

2. Initialize database:
   ```bash
   cd /opt/metasploit
   bundle exec ./msfdb init --connection-string="postgresql://postgres:postgres@127.0.0.1:5432/postgres"
   ```

3. Start msfconsole:
   ```bash
   bundle exec ./msfconsole -y ~/.msf4/database.yaml
   ```

**Expected Error (Before Fix):**
```
PG::UndefinedTable: ERROR: relation "workspaces" does not exist
ERROR: permission denied for schema public
```

### Steps to Verify (After Fix)

1. Start PostgreSQL 16 container:
   ```bash
   docker run --name test-postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres:16
   ```

2. Initialize database:
   ```bash
   cd /opt/metasploit
   bundle exec ./msfdb init --connection-string="postgresql://postgres:postgres@127.0.0.1:5432/postgres"
   ```

3. Verify connection:
   ```bash
   bundle exec ./msfconsole -q -x "db_status; exit"
   ```

**Expected Output (After Fix):**
```
Running the 'init' command for the database:
Creating initial database schema
Database initialization successful

[*] Connected to msf. Connection type: postgresql.
```

- [x] Database initialization succeeds
- [x] `msfconsole` connects to database successfully
- [x] No permission errors in PostgreSQL logs
- [x] Works with PostgreSQL 15, 16, and later versions
- [x] Backward compatible with PostgreSQL < 15

## Files Changed

- `lib/msfdb_helpers/standalone.rb` - Added schema permission grants after database creation

### Code Change

```ruby
# After creating databases, grant schema permissions
conninfo = @conn.conninfo_hash
[@options[:msf_db_name], @options[:msftest_db_name]].each_with_index do |db_name, idx|
  db_user = idx == 0 ? @options[:msf_db_user] : @options[:msftest_db_user]
  db_conn = PG.connect(host: conninfo[:host], port: conninfo[:port], dbname: db_name,
                       user: conninfo[:user], password: conninfo[:password])
  db_conn.exec("GRANT ALL ON SCHEMA public TO #{db_user}")
  db_conn.finish
end
```

### Why This Works

- PostgreSQL 15+ requires explicit schema permissions
- The `GRANT ALL ON SCHEMA public` command gives the `msf` user full permissions
- This is backward compatible - older PostgreSQL versions ignore the redundant grant

### CODE REVIEW

File: lib/msfdb_helpers/standalone.rb [hunk 1]
```diff
@@ -76,6 +76,18 @@ def create_db_users(msf_pass, msftest_pass)
       @conn.exec("alter role #{@options[:msftest_db_user]} with password '#{msftest_pass}'")
       @conn.exec("CREATE DATABASE #{@options[:msf_db_name]}")
       @conn.exec("CREATE DATABASE #{@options[:msftest_db_name]}")
+
+      # In PostgreSQL 15+, users need explicit permission to create objects in the public schema.
+      # Grant all privileges on the public schema to the database users.
+      conninfo = @conn.conninfo_hash
+      [@options[:msf_db_name], @options[:msftest_db_name]].each_with_index do |db_name, idx|
+        db_user = idx == 0 ? @options[:msf_db_user] : @options[:msftest_db_user]
+        db_conn = PG.connect(host: conninfo[:host], port: conninfo[:port], dbname: db_name,
```
Comment (adfoster-r7) [inline lib/msfdb_helpers/standalone.rb:85]: Was it possible to reuse the existing connection here or did that cause issues? 👀

Comment (sjanusz-r7) [reply lib/msfdb_helpers/standalone.rb:85]: For future us; We need to create a new connection here, as we need to be connected to a different database than what `@conn` is connected to, to be able to run the `GRANT ...` query. For context, this post explains it better than I could: https://stackoverflow.com/a/75876944

Also, this currently addresses only the standalone adapter. I've tested the `pg_ctl` adapter and it had no issues on `master` right now, so it makes sense that the code is only changed here.
Potential future steps could include consolidation of the `create_db_users` methods and some overall refactoring to reduce code duplication and broken code paths to make it easier to update Postgres versions in the future.

**Comment by sjanusz-r7** [comment]
Thank you for fixing this!
I have confirmed that this fixes the Docker workflow for version 16.

With the `debug` option enabled we can see that `bundle exec rake db:migrate` resulted in an error:
```
ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for schema public (ActiveRecord::StatementInvalid)
LINE 1: CREATE TABLE "schema_migrations" ("version" character varyin...
...
Caused by:
PG::InsufficientPrivilege: ERROR:  permission denied for schema public (PG::InsufficientPrivilege)
LINE 1: CREATE TABLE "schema_migrations" ("version" character varyin...
```

## Before

```
docker run --name test-postgres -e POSTGRES_PASSWORD=postgres -p 8081:5432 -d postgres:16
bundle exec ./msfdb init --connection-string="postgresql://postgres:postgres@127.0.0.1:8081/postgres"
bundle exec msfconsole -q
...
> `exec': PG::UndefinedTable: ERROR:  relation "workspaces" does not exist (ActiveRecord::StatementInvalid)
LINE 10:  WHERE a.attrelid = '"workspaces"'::regclass
```

## After
```
docker run --name test-postgres -e POSTGRES_PASSWORD=postgres -p 8081:5432 -d postgres:16   
bundle exec ./msfdb init --connection-string="postgresql://postgres:postgres@127.0.0.1:8081/postgres"
bundle exec msfconsole -q
msf > db_status
[*] Connected to msf. Connection type: postgresql.
```

**Review by sjanusz-r7 — APPROVED** [review]

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes a database initialization failure when using `msfdb init` with the `--connection-string` option to connect to PostgreSQL 15+ instances (e.g., Docker containers).
