### PR TITLE
Payload fixes (UUID and compiled payload tempfile handling)

### LINKED ISSUE #12691: UUID Windows Meterpreter payloads failing automated testing
Windows UUID payloads are failing automated testing.
The test uses the following format:
msfvenom payload creation, upload and callback/in with multi/handler.

The payloads appear to be created, uploaded, and run properly.  Then, they perform a callback and tcp handshake, but no data is sent after the handshake:
image

The handler does not show that a callback was received:
image

This behavior was seen on 

windows/x64/meterpreter/bind_tcp_uuid
windows/x64/meterpreter/reverse_tcp_uuid
windows/meterpreter/bind_tcp_uuid
windows/meterpreter/reverse_tcp_uuid

### PR DESCRIPTION
**Pull request by busterb**
This fixes #12691 and a few other things.

For the above bug, the non-hex_uuid case was using the wrong variable name, silently failing to parse the incoming UUID for other reverse_tcp payloads.

This also modifies the build process to build intermediate file paths with Tempfile, allowing both concurrent access, and for the feature to work if the user does not have write access to the install directory. It also changes a number of paths to prefer data_directory over other constructed paths.

Finally this adds cached payload sizes to prevent these payload modules from running on every `msfconsole` boot

## Verification

Verify that all reverse_tcp UUID payloads work, e.g:
- [ ] `./msfconsole -qx 'use multi/handler; set payload windows/meterpreter/reverse_tcp_uuid; set lhost 127.0.0.1; run'`
- [ ] `./msfvenom -p windows/meterpreter/reverse_tcp_uuid -f exe -o test.exe LHOST=127.0.0.1`
- [ ] `wine ./test.exe`

- [ ] Verify that compiled payloads work
- [ ] Verify that there are no intermediate temp files left in the install directory or in /tmp, etc.

### CODE REVIEW

File: lib/msf/core/payload/windows/encrypted_reverse_tcp.rb [hunk 1]
```diff
@@ -59,7 +59,7 @@ def generate(opts={})
       opt_lvl:       datastore['OptLevel'],
       keep_src:      datastore['KeepSrc'],
       keep_exe:      datastore['KeepExe'],
-      f_name:        (staged? ? 'reverse_pic_stager.exe' : 'reverse_pic_stageless.exe'),
+      f_name:        Tempfile.new(staged? ? 'reverse_pic_stager.exe' : 'reverse_pic_stageless.exe').path,
```
Comment (space-r7) [inline lib/msf/core/payload/windows/encrypted_reverse_tcp.rb]: The initial change resulted in a file name like this: `reverse_pic_stageless.exe20191211-99903-1qxrawr`. Using an array will force the extension if that's preferred.

```suggestion
      f_name:        Tempfile.new([ staged? ? 'reverse_pic_stager' : 'reverse_pic_stageless', '.exe' ]).path,
```

File: lib/msf/core/payload/windows/encrypted_reverse_tcp.rb [hunk 2]
```diff
@@ -130,7 +130,7 @@ def generate_stage(opts={})
       linker_script: link_script,
       keep_src:      datastore['KeepSrc'],
       keep_exe:      datastore['KeepExe'],
-      f_name:        'reverse_pic_stage.exe',
+      f_name:        Tempfile.new('reverse_pic_stage.exe').path,
```
Comment (space-r7) [inline lib/msf/core/payload/windows/encrypted_reverse_tcp.rb]: Same as above.

```suggestion
      f_name:        Tempfile.new([ 'reverse_pic_stage', '.exe' ]).path,
```

File: lib/msf/core/payload/stager.rb [hunk 3]
```diff
@@ -160,9 +160,9 @@ def sends_hex_uuid?
     false
   end
 
-  def format_uuid(uuid)
+  def format_uuid(uuid_raw)
     if sends_hex_uuid?
-      return uuid
+      return uuid_raw
```
Comment (space-r7) [inline lib/msf/core/payload/stager.rb]: Thanks for catching that.

File: lib/metasploit/framework/compiler/mingw.rb [hunk 4]
```diff
@@ -23,14 +23,14 @@ def build_cmd(src)
           link_options = '-Wl,'
 
           src_file = File.basename(self.file_name, '.exe')
```
Comment (space-r7) [inline lib/metasploit/framework/compiler/mingw.rb]: The source files are still being written to the Msf path.

```suggestion
          src_file = self.file_name.split('.exe').first
```

File: lib/metasploit/framework/compiler/mingw.rb [hunk 5]
```diff
@@ -53,14 +53,13 @@ def cleanup_files
           file_base = File.basename(self.file_name, '.exe')
```
Comment (space-r7) [inline lib/metasploit/framework/compiler/mingw.rb]:
```suggestion
          file_base = self.file_name.split('.exe').first
```

File: lib/metasploit/framework/compiler/mingw.rb [hunk 6]
```diff
@@ -53,14 +53,13 @@ def cleanup_files
...
           src_file = "#{file_base}.c"
           exe_file = "#{file_base}.exe"
```
Comment (space-r7) [inline lib/metasploit/framework/compiler/mingw.rb]:
```suggestion
          exe_file = self.file_name
```

**Comment by bwatters-r7** [comment]
image

File: lib/msf/core/payload/windows/encrypted_reverse_tcp.rb (hunk 1 above)
Comment (busterb) [reply lib/msf/core/payload/windows/encrypted_reverse_tcp.rb]: Thanks, I opted to avoid pushing the extension here and instead let mingw.rb handle adding it itself.

**Comment by busterb** [comment]
Thanks for the test run @bwatters-r7 and the notes @space-r7 , I applied some updates to hopefully address all of the comments.

File: lib/msf/core/payload/stager.rb (hunk 3 above)
Comment (busterb) [reply lib/msf/core/payload/stager.rb]: :+1:

**Comment by space-r7** [comment]
## Release Notes

This fixes an issue for payloads that utilize UUIDS. The `format_uuid()` method was using the wrong variable name to parse the UUID. This also stores generated files used by the encrypted payloads in a temp location and deletes them by default.

**Comment by busterb** [comment]
Thanks @space-r7
