### PR TITLE
Fix binary-safe Mach-O detection

### LINKED ISSUE #21047: mettle macos-15-intel Builds are failing
The mettle macos-15-intel build is failing pretty consistently with SIGABRT. https://github.com/rapid7/metasploit-framework/actions/runs/22619582688/job/65576745764

<details>
<summary>Error output</summary>

```
       Expected Payload process to be running. Instead got: payload process exited with pid 8083 SIGABRT (signal 6) - when running the command ["/var/folders/x_/wstzc9d10r926lhsf8fsv7q80000gn/T/child-process-rb-osx-x---meterpreter-reverse-tcp20260303-5985-xrxqyq"]
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-support-3.13.6/lib/rspec/support.rb:110:in `block in <module:Support>'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-support-3.13.6/lib/rspec/support.rb:119:in `notify_failure'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:39:in `handle_failure'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:55:in `block in handle_matcher'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:26:in `with_matcher'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:47:in `handle_matcher'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/expectation_target.rb:101:in `to'
     # ./spec/acceptance/meterpreter_spec.rb:366:in `block (9 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:263:in `instance_exec'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:263:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/hooks.rb:486:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/hooks.rb:486:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:259:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:653:in `block in run_examples'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:649:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:649:in `run_examples'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:614:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/configuration.rb:2097:in `with_suite_hooks'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:74:in `report'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:115:in `run_specs'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:71:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:45:in `invoke'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/exe/rspec:4:in `<top (required)>'
     # ./vendor/bundle/ruby/3.3.0/bin/rspec:25:in `load'
     # ./vendor/bundle/ruby/3.3.0/bin/rspec:25:in `<top (required)>'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `load'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in `run'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in `exec'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/bin/bundle:25:in `load'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/bin/bundle:25:in `<main>'

  9) Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/extapi osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/extapi" tests
     Failure/Error:
                           expect(payload_process).to(be_alive, proc do
                             current_payload_status = "Expected Payload process to be running. Instead got: payload process exited with #{payload_process.wait_thread.value} - when running the command #{payload_process.cmd.inspect}"
       
                             Allure.add_attachment(
                               name: 'Failed payload blob',
                               source: Base64.strict_encode64(File.binread(payload_process.payload_path)),
                               type: Allure::ContentType::TXT
                             )
       
                             current_payload_status

       Expected Payload process to be running. Instead got: payload process exited with pid 8166 SIGABRT (signal 6) - when running the command ["/var/folders/x_/wstzc9d10r926lhsf8fsv7q80000gn/T/child-process-rb-osx-x---meterpreter-reverse-tcp20260303-5985-czamrq"]
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-support-3.13.6/lib/rspec/support.rb:110:in `block in <module:Support>'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-support-3.13.6/lib/rspec/support.rb:119:in `notify_failure'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:39:in `handle_failure'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:55:in `block in handle_matcher'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:26:in `with_matcher'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:47:in `handle_matcher'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/expectation_target.rb:101:in `to'
     # ./spec/acceptance/meterpreter_spec.rb:366:in `block (9 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:263:in `instance_exec'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:263:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/hooks.rb:486:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/hooks.rb:486:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:259:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:653:in `block in run_examples'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:649:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:649:in `run_examples'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:614:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in `map'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/configuration.rb:2097:in `with_suite_hooks'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:74:in `report'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:115:in `run_specs'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:71:in `run'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:45:in `invoke'
     # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/exe/rspec:4:in `<top (required)>'
     # ./vendor/bundle/ruby/3.3.0/bin/rspec:25:in `load'
     # ./vendor/bundle/ruby/3.3.0/bin/rspec:25:in `<top (required)>'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `load'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in `run'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in `exec'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/bin/bundle:25:in `load'
     # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/bin/bundle:25:in `<main>'

  10) Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/unix osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/unix" tests
      Failure/Error:
                            expect(payload_process).to(be_alive, proc do
                              current_payload_status = "Expected Payload process to be running. Instead got: payload process exited with #{payload_process.wait_thread.value} - when running the command #{payload_process.cmd.inspect}"
        
                              Allure.add_attachment(
                                name: 'Failed payload blob',
                                source: Base64.strict_encode64(File.binread(payload_process.payload_path)),
                                type: Allure::ContentType::TXT
                              )
        
                              current_payload_status

        Expected Payload process to be running. Instead got: payload process exited with pid 8340 SIGABRT (signal 6) - when running the command ["/var/folders/x_/wstzc9d10r926lhsf8fsv7q80000gn/T/child-process-rb-osx-x---meterpreter-reverse-tcp20260303-5985-2d6lis"]
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-support-3.13.6/lib/rspec/support.rb:110:in `block in <module:Support>'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-support-3.13.6/lib/rspec/support.rb:119:in `notify_failure'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:39:in `handle_failure'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:55:in `block in handle_matcher'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:26:in `with_matcher'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/handler.rb:47:in `handle_matcher'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/expectation_target.rb:65:in `to'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-expectations-3.13.5/lib/rspec/expectations/expectation_target.rb:101:in `to'
      # ./spec/acceptance/meterpreter_spec.rb:366:in `block (9 levels) in <top (required)>'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:263:in `instance_exec'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:263:in `block in run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/hooks.rb:486:in `block in run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/hooks.rb:486:in `run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example.rb:259:in `run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:653:in `block in run_examples'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:649:in `map'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:649:in `run_examples'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:614:in `run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `block in run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `map'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/example_group.rb:615:in `run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in `map'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/configuration.rb:2097:in `with_suite_hooks'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:116:in `block in run_specs'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/reporter.rb:74:in `report'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:115:in `run_specs'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:89:in `run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:71:in `run'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/lib/rspec/core/runner.rb:45:in `invoke'
      # ./vendor/bundle/ruby/3.3.0/gems/rspec-core-3.13.5/exe/rspec:4:in `<top (required)>'
      # ./vendor/bundle/ruby/3.3.0/bin/rspec:25:in `load'
      # ./vendor/bundle/ruby/3.3.0/bin/rspec:25:in `<top (required)>'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `load'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in `run'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in `exec'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/bin/bundle:25:in `load'
      # /Users/runner/hostedtoolcache/Ruby/3.3.8/x64/bin/bundle:25:in `<main>'

Top 10 slowest examples (78.41 seconds, 58.1% of total time):
  Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/socket_channels osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/socket_channels" tests
    14.54 seconds ./spec/acceptance/meterpreter_spec.rb:350
  Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/railgun osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/railgun" tests
    11.26 seconds ./spec/acceptance/meterpreter_spec.rb:350
  Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/get_env osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/get_env" tests
    9.85 seconds ./spec/acceptance/meterpreter_spec.rb:350
  Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx osx/mettle Meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload exposes available metasploit commands
    8.27 seconds ./spec/acceptance/meterpreter_spec.rb:200
  Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/meterpreter osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/meterpreter" tests
    6.9 seconds ./spec/acceptance/meterpreter_spec.rb:350
  Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/file osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/file" tests
    6.29 seconds ./spec/acceptance/meterpreter_spec.rb:350
  Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/unix osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/unix" tests
    6.19 seconds ./spec/acceptance/meterpreter_spec.rb:350
  Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/railgun_reverse_lookups osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/railgun_reverse_lookups" tests
    5.12 seconds ./spec/acceptance/meterpreter_spec.rb:350
  Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/extapi osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/extapi" tests
    5.01 seconds ./spec/acceptance/meterpreter_spec.rb:350
  Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/cmd_exec osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/cmd_exec" tests
    4.97 seconds ./spec/acceptance/meterpreter_spec.rb:350

Finished in 2 minutes 15 seconds (files took 3.14 seconds to load)
10 examples, 10 failures

Failed examples:

rspec ./spec/acceptance/meterpreter_spec.rb[1:4:2:1:12:1] # Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/socket_channels osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/socket_channels" tests
rspec ./spec/acceptance/meterpreter_spec.rb[1:4:2:1:6:1] # Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/get_env osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/get_env" tests
rspec ./spec/acceptance/meterpreter_spec.rb[1:4:2:1:8:1] # Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/railgun osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/railgun" tests
rspec ./spec/acceptance/meterpreter_spec.rb[1:4:2:1:5:1] # Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/file osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/file" tests
rspec ./spec/acceptance/meterpreter_spec.rb[1:4:2:1:1:1] # Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx osx/mettle Meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload exposes available metasploit commands
rspec ./spec/acceptance/meterpreter_spec.rb[1:4:2:1:7:1] # Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/meterpreter osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/meterpreter" tests
rspec ./spec/acceptance/meterpreter_spec.rb[1:4:2:1:3:1] # Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/cmd_exec osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/cmd_exec" tests
rspec ./spec/acceptance/meterpreter_spec.rb[1:4:2:1:9:1] # Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/railgun_reverse_lookups osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/railgun_reverse_lookups" tests
rspec ./spec/acceptance/meterpreter_spec.rb[1:4:2:1:4:1] # Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/extapi osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/extapi" tests
rspec ./spec/acceptance/meterpreter_spec.rb[1:4:2:1:13:1] # Meterpreter mettle stageless osx/x64/meterpreter_reverse_tcp osx post/test/unix osx/mettle meterpreter successfully opens a session for the "osx/x64/meterpreter_reverse_tcp" payload and passes the "post/test/unix" tests

Randomized with seed 37324

Error: Process completed with exit code 1.
```
</details>

We should fix this so the tests start passing again.

### PR DESCRIPTION
**Pull request by SaiSakthidar**
Fixes #21047 
Fixes Mach-O detection for macOS mettle payloads.

It was misdetecting valid Mach-O binaries under Ruby 3, so framework wrapped them again and produced a broken payload. This makes the check binary-safe so the original mettle Mach-O is used directly.

### CODE REVIEW

**Comment by SaiSakthidar** [comment]
@smcintyre-r7 @jheysel-r7 
Could you take a look at this 
Also do we need to add the `payload-testing`  label to get the Acceptance CI to run ?

File: lib/msf/util/exe/common.rb [hunk 1]
```diff
@@ -117,7 +117,8 @@ def elf?(code)
     end
 
     def macho?(code)
-      code[0..3] == "\xCF\xFA\xED\xFE" || code[0..3] == "\xCE\xFA\xED\xFE" || code[0..3] == "\xCA\xFE\xBA\xBE"
+      magic = code&.byteslice(0, 4)
```
Comment (adfoster-r7) [inline lib/msf/util/exe/common.rb:120]: I think this is a sign that the `code` object that's been passed in needs to be correctly marked as being binary encoded, so this code change is likely fixing a side-effect rather than the real issue - is it possible to track down the origin issue? 👀

Comment (smcintyre-r7) [reply lib/msf/util/exe/common.rb:120]: Well this file is missing the `encoding: binary` magic comment at the top. I think that'd mean that the literals here have the default encoding. `#byteslice` doesn't appear to change the encoding so this reads to me as though the issue is that the comparsion was failing because the literals did not match the encoding of the `code` var which appears to be correctly set to `ASCII_8BIT` based on it now passing when the literals use the `#b` method.

**Review by smcintyre-r7 — APPROVED** [review]
I'm going to merge this. After talking to @adfoster-r7 I think the underlying issue is in #20859 we split out the exe.rb file into multiple subfiles including this one. Now the original `exe.rb` did and still does have the binary [magic comment at the top](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/util/exe.rb#L1) that sets the encoding for literals. The new files however do not have this magic comment meaning that the string encoding of literals is the default encoding instead of bytes as it used to be.

**Comment by smcintyre-r7** [comment]
# Release Notes
This fixes a bug that was preventing Mach-O binaries from being identified due to a Ruby string encoding compatibility problem.
