### PR TITLE
rescue connection failure for DCE/RPC with ETERNALBLUE, suggest how to fix it

### LINKED ISSUE #8486: ms17_10_eternalblue: VerifyArch fails when 135/tcp isn't open
The ms17_10_eternalblue `VerifyArch` feature introduced via PR #8476 fails when 135/tcp isn't open.  Unlike the error message for `VerifyTarget` there isn't helpful text to indicate that disabling `VerifyArch` will help.  This is due to `Rex::ConnectionTimeout` being unhandled as a specific exception.

Relevant section:
https://github.com/rapid7/metasploit-framework/pull/8476/files#diff-2da4b4e901f1f898397da82fb5417ec0R284

## Steps to reproduce

1. Select a target where 139/tcp is firewalled or otherwise inaccessible. In my test case the target did not respond at all to the SYN packet.
2. Checkout MSF from the master branch on Github, bundle install, etc.
3. Ensure that `VerifyArch` is set to the default of `true`
4. Exploit the target using `exploit/windows/smb/ms17_010_eternalblue`.

## Expected behavior

I would expect that the connection would time out and that the error message would indicate that this issue *may* be worked around by setting `VerifyArch` to false.

## Current behavior

```
[*] Started reverse TCP handler on xxx.xxx.xxx.116:4444
[*] xxx.xxx.xxx.180:445 - Connecting to target for exploitation.
[+] xxx.xxx.xxx.180:445 - Connection established for exploitation.
[*] xxx.xxx.xxx.180:445 - CORE raw buffer dump (10 bytes)
[*] xxx.xxx.xxx.180:445 - 0x00000000  57 4f 52 4b 47 52 4f 55 50 00                    WORKGROUP
[-] xxx.xxx.xxx.180:445 - Rex::ConnectionTimeout: The connection timed out (xxx.xxx.xxx.180:135).
```

### Metasploit version

Framework : 4.14.23-dev-ee57c71
Console      : 4.14.23-dev-ee57c71

### I installed Metasploit with:

Source install (please specify ruby version)
ruby 2.4.1p111 (2017-03-22 revision 58053)

### OS

Ubuntu 

CC: @wvu-r7

### PR DESCRIPTION
**Pull request by busterb**
This fixes #8486 by rescuing the connection attempt and failing nicely.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use exploit/windows/smb/ms17_010_eternalblue`
- [x] target a Windows box with port 135 firewalled
- [x] **Verify** that the module now suggests how to resolve the issue
- [x] **Verify** that disabling VerifyArch allows it to proceed.

Sample run below:
```
msf exploit(ms17_010_eternalblue) > run

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started reverse TCP handler on 127.0.0.1:4444 
[*] 192.168.56.101:445 - Connecting to target for exploitation.
[+] 192.168.56.101:445 - Connection established for exploitation.
[*] 192.168.56.101:445 - CORE raw buffer dump (19 bytes)
[*] 192.168.56.101:445 - 0x00000000  57 69 6e 64 6f 77 73 20 31 30 20 50 72 6f 20 36  Windows 10 Pro 6
[*] 192.168.56.101:445 - 0x00000010  2e 33 00                                         .3             
[-] 192.168.56.101:445 - The connection timed out (192.168.56.101:135).
[!] 192.168.56.101:445 - Target arch not detected for target OS
[!] 192.168.56.101:445 - Disable VerifyArch option to proceed manually...
[-] 192.168.56.101:445 - Unable to continue with improper OS Arch.


[*] Exploit completed, but no session was created.
msf exploit(ms17_010_eternalblue) > 
msf exploit(ms17_010_eternalblue) > 
msf exploit(ms17_010_eternalblue) > set VerifyArch false
VerifyArch => false
msf exploit(ms17_010_eternalblue) > run

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started reverse TCP handler on 127.0.0.1:4444 
[*] 192.168.56.101:445 - Connecting to target for exploitation.
[+] 192.168.56.101:445 - Connection established for exploitation.
[*] 192.168.56.101:445 - CORE raw buffer dump (19 bytes)
[*] 192.168.56.101:445 - 0x00000000  57 69 6e 64 6f 77 73 20 31 30 20 50 72 6f 20 36  Windows 10 Pro 6
[*] 192.168.56.101:445 - 0x00000010  2e 33 00                                         .3             
[*] 192.168.56.101:445 - Trying exploit with 12 Groom Allocations.
[*] 192.168.56.101:445 - Sending all but last fragment of exploit packet
[*] 192.168.56.101:445 - Sending NT Trans Request packet
```

### CODE REVIEW

File: modules/exploits/windows/smb/ms17_010_eternalblue.rb [hunk 1]
```diff
@@ -263,10 +263,20 @@ def verify_arch
...
-      'RHOST' => rhost,
-      'RPORT' => 135
-    )
+    begin
+      sock = connect(false,
+        'RHOST' => rhost,
+        'RPORT' => 135
+      )
+    rescue ::Errno::ECONNRESET,
+           ::Rex::HostUnreachable,
```
Comment (egypt) [inline modules/exploits/windows/smb/ms17_010_eternalblue.rb]: `::Rex::ConnectionError` encompasses all of these and more. You should rescue that instead of these three.

Comment (wvu-r7) [inline modules/exploits/windows/smb/ms17_010_eternalblue.rb]: I already have this change in my local branch.

**Comment by tsellers-r7** [comment]
This PR works in my testing.

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/commit/890d35cc30322d3b41876114bdda4ce4d6d17c93, https://github.com/rapid7/metasploit-framework/commit/72ff4fbf488ce5dc27b699a7efa1220ce9a83028

File: modules/exploits/windows/smb/ms17_010_eternalblue.rb (hunk 1 above)
Comment (wvu-r7) [inline modules/exploits/windows/smb/ms17_010_eternalblue.rb]: FWIW, `Errno::ECONNRESET` is handled by `Rex::ConnectionRefused`.

**Comment by busterb** [comment]
Thanks @wvu

**Comment by wvu-r7** [comment]
# Release Notes

This improves DCE/RPC error handling in `exploit/windows/smb/ms17_010_eternalblue`. Now the suggestion to disable `VerifyArch` will be printed for all DCE/RPC errors that occur.
