### PR TITLE
Fixes broken sessions in rservices modules

### LINKED ISSUE #16769: Rlogin session immediately exits upon first interaction
## Steps to reproduce

How'd you do it?

1. use auxiliary/scanner/rservices/rlogin_login
2. I am able to fill in the correct target options in order to spawn a shell:

```
msf5 auxiliary(scanner/rservices/rlogin_login) > set FROMUSER asdf
FROMUSER => asdf
msf5 auxiliary(scanner/rservices/rlogin_login) > set RPORT 514
RPORT => 514
msf5 auxiliary(scanner/rservices/rlogin_login) > set USERNAME foobar
USERNAME => foobar
msf5 auxiliary(scanner/rservices/rlogin_login) > set BLANK_PASSWORDS true
BLANK_PASSWORDS => true
msf5 auxiliary(scanner/rservices/rlogin_login) > set RHOSTS 10.X.X.X
RHOSTS => 10.X.X.X
msf5 auxiliary(scanner/rservices/rlogin_login) > exploit

[*] 10.X.X.X:514     - 10.X.X.X:514 - Starting rlogin sweep
[*] 10.X.X.X:514     - 10.X.X.X:514 rlogin - Attempting: 'foobar':"" from 'asdf'
[+] 10.X.X.X:514     - 10.X.X.X:514, rlogin 'foobar' from 'asdf' with no password.
[!] 10.X.X.X:514     - *** auxiliary/scanner/rservices/rlogin_login is still calling the deprecated report_auth_info method! This needs to be updated!
[!] 10.X.X.X:514     - *** For detailed information about LoginScanners and the Credentials objects see:
[!] 10.X.X.X:514     -      https://github.com/rapid7/metasploit-framework/wiki/Creating-Metasploit-Framework-LoginScanners
[!] 10.X.X.X:514     -      https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-HTTP-LoginScanner-Module
[!] 10.X.X.X:514     - *** For examples of modules converted to just report credentials without report_auth_info, see:
[!] 10.X.X.X:514     -      https://github.com/rapid7/metasploit-framework/pull/5376
[!] 10.X.X.X:514     -      https://github.com/rapid7/metasploit-framework/pull/5377
[*] Command shell session 1 opened (10.Y.Y.Y:1023 -> 10.X.X.X:514) at 2022-07-12 11:38:28 +0100
[*] 10.X.X.X:514     - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

3. Then, running the command `sessions -l` displays the session created:

```
msf5 auxiliary(scanner/rservices/rlogin_login) > sessions -l

Active sessions
===============

  Id  Name  Type   Information                                  Connection
  --  ----  ----   -----------                                  ----------
  1         shell   RLOGIN foobar from asdf (10.X.X.X:514)  10.Y.Y.Y:1023 -> 10.X.X.X:514 (10.X.X.X)
```

4. My issue is in then trying to interact with the sessions to read the files. As soon as I run this command, it exits, with no further information despite setting the verbosity to 3:

```
msf5 auxiliary(scanner/rservices/rlogin_login) > sessions -i 1
[*] Starting interaction with 1...


[*] 10.X.X.X - Command shell session 1 closed.  Reason: User exit
```

#

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Were you following a specific guide/tutorial or reading documentation?
I referred to the following documentation:
https://www.infosecmatter.com/metasploit-module-library/?mm=auxiliary/scanner/rservices/rlogin_login

## Expected behavior

This should be the expected output, instead of the session immediately exiting:
```
msf auxiliary(rsh_login) > sessions -i 1
[*] Starting interaction with 1...

sh: can't access tty; job control turned off
$ id
uid=1047(foobar) gid=1047(foobar) groups=1047(foobar),24(cdrom),25(floppy),29(audio),30(dip),44(video),46(plugdev)
$ 
```

## Current behavior

```
msf5 auxiliary(scanner/rservices/rlogin_login) > sessions -i 1
[*] Starting interaction with 1...


[*] 10.X.X.X - Command shell session 1 closed.  Reason: User exit
```

### Metasploit version
```

Framework: 6.2.1-dev
Console  : 6.2.1-dev
```

===8<=== CUT AND PASTE EVERYTHING BELOW THIS LINE ===8<===

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/ui/console]
ActiveModule=auxiliary/scanner/rservices/rlogin_login

[scanner/rservices/rlogin_login]
WORKSPACE=
VERBOSE=true
RHOSTS=10.X.X.X
RPORT=514
SSL=false
SSLVersion=Auto
SSLVerifyMode=PEER
SSLCipher=
Proxies=
CPORT=
CHOST=
ConnectTimeout=10
TCP::max_send_size=0
TCP::send_delay=0
USERNAME=foobar
PASSWORD=
USER_FILE=
PASS_FILE=
USERPASS_FILE=
BRUTEFORCE_SPEED=5
BLANK_PASSWORDS=true
USER_AS_PASS=true
DB_ALL_CREDS=false
DB_ALL_USERS=false
DB_ALL_PASS=false
STOP_ON_SUCCESS=false
REMOVE_USER_FILE=false
REMOVE_PASS_FILE=false
REMOVE_USERPASS_FILE=false
PASSWORD_SPRAY=false
TRANSITION_DELAY=0
MaxGuessesPerService=0
MaxMinutesPerService=0
MaxGuessesPerUser=0
FROMUSER=asdf
FROMUSER_FILE=/usr/share/metasploit-framework/data/wordlists/rservices_from_users.txt
REMOVE_FROMUSER_FILE=false
THREADS=1
ShowProgress=true
ShowProgressPercent=10
CreateSession=true
InitialAutoRunScript=
AutoRunScript=
CommandShellCleanupCommand=
AutoVerifySession=true
TERM=vt100
SPEED=9600
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
114    version
115    use rlogin
116    use 3
117    set BLANK_PASSWORDS   true
118    set FROMUSER          asdf
119    set RHOSTS            10.X.X.X
120    set RPORT             514
121    set USERNAME          foobar
122    set USER_AS_PASS      true
123    set VERBOSE           true
124    exploit
125    sessions -l
126    sessions -i 1
127    debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[07/12/2022 12:56:05] [e(0)] core: Exploit failed (multi/handler): Interrupt  - Interrupt 
[07/12/2022 12:57:17] [e(0)] core: Exploit failed (multi/handler): Interrupt  - Interrupt 
[07/12/2022 12:57:44] [e(0)] core: Exploit failed (multi/handler): Interrupt  - Interrupt 
[07/12/2022 12:59:58] [e(0)] meterpreter: stdapi_fs_chdir: Operation failed: Access is denied.
[07/12/2022 13:01:52] [e(0)] core: Exploit failed (multi/handler): Interrupt  - Interrupt 
[07/12/2022 13:03:52] [e(0)] core: Exploit failed (multi/handler): Interrupt  - Interrupt 
[07/12/2022 13:04:32] [e(0)] meterpreter: core_channel_open: Operation failed: Access is denied.
[07/12/2022 13:11:54] [e(0)] core: Module rlogin not found, and no loading errors found. If you're using a custom module refer to our wiki: https://github.com/rapid7/metasploit-framework/wiki/Running-Private-Modules
[07/12/2022 13:13:29] [e(0)] core: Module rb:51:in not found, and no loading errors found. If you're using a custom module refer to our wiki: https://github.com/rapid7/metasploit-framework/wiki/Running-Private-Modules
[07/12/2022 13:13:33] [e(0)] core: Module tomcat_gather not found, and no loading errors found. If you're using a custom module refer to our wiki: https://github.com/rapid7/metasploit-framework/wiki/Running-Private-Modules
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:157:in `run'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:62:in `interact'
/usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:555:in `_interact'
/usr/share/metasploit-framework/lib/rex/ui/interactive.rb:51:in `interact'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1543:in `cmd_sessions'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:555:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_single'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/exploit.rb:223:in `cmd_exploit'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:555:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[07/12/2022 13:04:58] [d(0)] core: HistoryManager.push_context name: :shell
[07/12/2022 13:04:58] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (4)
[07/12/2022 13:04:58] [d(0)] core: HistoryManager.pop_context name: :shell
[07/12/2022 13:05:03] [d(0)] core: Session 4 failed to respond to an echo command
[07/12/2022 13:05:48] [d(0)] core: HistoryManager.push_context name: :shell
[07/12/2022 13:05:48] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (5)
[07/12/2022 13:05:51] [d(0)] core: Session 5 failed to respond to an echo command
[07/12/2022 13:05:51] [d(0)] core: HistoryManager.pop_context name: :shell
[07/12/2022 13:07:25] [d(0)] core: HistoryManager.push_context name: :msfconsole
[07/12/2022 13:09:03] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (6)
[07/12/2022 13:09:03] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (6)
[07/12/2022 13:09:03] [w(0)] core: Exception in scheduler thread EOFError EOFError
[07/12/2022 13:11:45] [d(0)] core: HistoryManager.push_context name: :msfconsole
[07/12/2022 13:11:54] [e(0)] core: Module rlogin not found, and no loading errors found. If you're using a custom module refer to our wiki: https://github.com/rapid7/metasploit-framework/wiki/Running-Private-Modules
[07/12/2022 13:12:16] [d(0)] core: HistoryManager.push_context name: :shell
[07/12/2022 13:12:16] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (7)
[07/12/2022 13:12:17] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (7)
[07/12/2022 13:12:17] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (7)
[07/12/2022 13:12:20] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (7)
[07/12/2022 13:12:20] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (7)
[07/12/2022 13:12:22] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (7)
[07/12/2022 13:12:22] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (7)
[07/12/2022 13:12:22] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (7)
[07/12/2022 13:12:25] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (7)
[07/12/2022 13:12:26] [d(0)] core: HistoryManager.pop_context name: :shell
[07/12/2022 13:12:26] [w(0)] core: Session manipulation failed: undefined method `gsub!' for nil:NilClass ["/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.35/lib/rex/text/color.rb:59:in `substitute_colors'", "/usr/share/metasploit-framework/lib/rex/ui/text/output.rb:68:in `print'", "/usr/share/metasploit-framework/lib/msf/base/sessions/command_shell.rb:787:in `_interact_stream'", "/usr/share/metasploit-framework/lib/msf/base/sessions/command_shell.rb:773:in `block in _interact'", "/usr/share/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:51:in `with_context'", "/usr/share/metasploit-framework/lib/msf/base/sessions/command_shell.rb:772:in `_interact'", "/usr/share/metasploit-framework/lib/rex/ui/interactive.rb:51:in `interact'", "/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1543:in `cmd_sessions'", "/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:555:in `run_command'", "/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `block in run_single'", "/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `each'", "/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_single'", "/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'", "/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'", "/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'", "/usr/bin/msfconsole:23:in `<main>'"]
[07/12/2022 13:12:35] [d(0)] core: Session 7 failed to respond to an echo command
[07/12/2022 13:12:42] [d(0)] core: Session 8 failed to respond to an echo command
[07/12/2022 13:13:29] [e(0)] core: Module rb:51:in not found, and no loading errors found. If you're using a custom module refer to our wiki: https://github.com/rapid7/metasploit-framework/wiki/Running-Private-Modules
[07/12/2022 13:13:33] [e(0)] core: Module tomcat_gather not found, and no loading errors found. If you're using a custom module refer to our wiki: https://github.com/rapid7/metasploit-framework/wiki/Running-Private-Modules
[07/12/2022 13:13:35] [d(0)] core: HistoryManager.push_context name: :shell
[07/12/2022 13:13:35] [d(0)] core: HistoryManager.pop_context name: :shell
```

</details>

```

### PR DESCRIPTION
**Pull request by cgranleese-r7**
Resolves #16769

This PR implements a fix to all three of the rservices modules. 
- `modules/auxiliary/scanner/rservices/rexec_login.rb`
- `modules/auxiliary/scanner/rservices/rlogin_login.rb`
- `modules/auxiliary/scanner/rservices/rsh_login.rb`

Previously when sessions opened they would exit as soon as a user attempted to interact with them. Now, both `rsh_login.rb` and `rlogin_login.rb` can now open sessions and are interactive. However we were unsuccessful in gaining a session for `rexec_login.rb` as we had no means to test it, or at least didn't know how. However the logic for sessions was consistent across all three modules so we could see the changes made for the other two modules would need to be implemented in `rexec_login.rb` as well.

## Before
image

## After
image

### Note
These issues were found as part of a ticket to fix the deprecated modules warning in the above screenshots. A PR to fix those issues will follow this.

### Note 
There are also docs for these modules: `documentation/modules/auxiliary/scanner/rservices/rlogin_login.md`.
Metasploitable 2 is an alternative target. We tested against both, so either should work.

- [ ] Start `msfconsole`
- [ ] Run `use auxiliary/scanner/rservices/rlogin_login`
- [ ] Run `sessions -1`
- [ ] **Verify** the session does not exit after interacting with it.

### CODE REVIEW

File: modules/auxiliary/scanner/rservices/rexec_login.rb [hunk 1]
```diff
@@ -179,9 +179,11 @@ def start_rexec_session(host, port, user, pass, proof, stderr_sock)
       :stderr_sock    => stderr_sock
     }
 
-    # Don't tie the life of this socket to the exploit
-    self.sockets.delete(stderr_sock)
-
-    start_session(self, "rexec #{user}:#{pass} (#{host}:#{port})", merge_me) if datastore['CreateSession']
+    if datastore['CreateSession']
+      start_session(self, "rexec #{user}:#{pass} (#{host}:#{port})", merge_me, false, self.sock)
```
Comment (adfoster-r7) [inline modules/auxiliary/scanner/rservices/rexec_login.rb:183]: This change was required by the changes to https://github.com/rapid7/metasploit-framework/pull/15831


`obj.respond_to?(:sock)` is false, as it's not a publicly accessible field. However `self` in the `start_session` context is the same as `obj`, so `sock` was previously accessible

```diff
-    sock ||= obj.sock
+     sock ||= obj.respond_to?(:sock) ? obj.sock : nil
     sess ||= Msf::Sessions::CommandShell.new(sock)
     sess.set_from_exploit(obj)
    sess.info = info
```

 https://github.com/rapid7/metasploit-framework/pull/15831/files#diff-094966c8b83cae1221563db0129e812247847cf22d73d0b92e8acf4a91e607ef changed

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes a bug where sessions opened by running one of the `rexec_login` / `rlogin_login` / `rsh_login` modules would die after module completion
