### PR TITLE
Fixed Typo in Java RMI Module

### LINKED ISSUE #5707: Fix misspelling in Java RMI modules
s/Filed/Failed/

### PR DESCRIPTION
**Pull request by MSadek-r7**
This closes #5707

### CODE REVIEW

**Comment by wvu-r7** [comment]
And ```modules/auxiliary/scanner/misc/java_rmi_server.rb```.

File: lib/rex/proto/kerberos/model/kdc_request.rb [hunk 1]
```diff
@@ -118,7 +118,7 @@ def decode_asn1(input)
               when 4
                 self.req_body = decode_asn1_req_body(val)
               else
-                raise ::RuntimeError, 'Filed to decode KdcRequest SEQUENCE'
+                raise ::RuntimeError, ' to decode KdcRequest SEQUENCE'
```
Comment (wvu-r7) [inline lib/rex/proto/kerberos/model/kdc_request.rb]: You forgot to add the word to the thing.

**Comment by wvu-r7** [comment]
Nice work. Thanks!
