### PR TITLE
Make the EICAR canary useful again

### LINKED ISSUE #14415: msfconsole ignores EICAR canary until long after its useful
A bunch of users have reported issues with a missing `.dex` file causing Metasploit `msfconsole` to fail to start. Instead `msfconsole` dies with a long backtrace.

Here's one example issue I can be bothered to track down (there are many):

* https://github.com/rapid7/metasploit-framework/issues/13134#issuecomment-651786446

This issue is due to anti-virus eating the `.dex` file. In theory, corruption of Metasploit files by anti-virus was meant to have been detected by the `is_eicar_corrupted?` canary.

https://github.com/rapid7/metasploit-framework/blob/025950ec0b8454da30b040f9a9798e1dd17d6705/lib/msf/util/exe.rb#L2179-L2196

(Also, this `is_eicar_corrupted?` method is poorly written. It checks if the file exists twice.)

The problem is that this method is called here:

https://github.com/rapid7/metasploit-framework/blob/025950ec0b8454da30b040f9a9798e1dd17d6705/lib/msf/core/framework.rb#L42

But the canary warning is ignored. This proves to be fatal.

A few lines later `module_manager` is loaded. The crash due to missing `.dex` file occurs somewhere in here while iterating through module paths.

https://github.com/rapid7/metasploit-framework/blob/025950ec0b8454da30b040f9a9798e1dd17d6705/lib/msf/core/framework.rb#L58

Some time latter, `cmd_banner` gets called to display the banner, version and help tips. Only then does `msfconsole` bother to check if the canary is happy.

https://github.com/rapid7/metasploit-framework/blob/025950ec0b8454da30b040f9a9798e1dd17d6705/lib/msf/ui/console/command_dispatcher/core.rb#L258-L265

This sequence of events needs to be reworked.

### PR DESCRIPTION
**Pull request by dwelch-r7**
Resolves #14415 

Refactor of where and when the EICAR canary is checked

# Verification
- [x] Delete the `data/eicar.com` file
- [x] Startup framework (with and without the quiet flag `-q`)
- [x] Observe the EICAR warning

You may also delete the `/gems/metasploit-payloads-2.0.24/data/android/apk/classes.dex` file which was mentioned in the issue and framework should no longer break due to the load order differences meaning the AV warning will always be displayed first

### CODE REVIEW

File: lib/msf/core/framework.rb [hunk 1]
```diff
@@ -249,6 +246,25 @@ def search(search_string)
...
+    )
+    return true unless ::File.exist?(path)
+
+    data = ::File.read(path)
+    return true unless Digest::SHA1.hexdigest(data) == "3395856ce81f2b7382dee72602f798b642f14140"
+
+    false
+
+    # If anything goes wrong assume AV got us
+    rescue ::Exception
```
Comment (acammack-r7) [inline lib/msf/core/framework.rb:264]:
```suggestion
  rescue
```

File: lib/msf/ui/console/driver.rb [hunk 2]
```diff
@@ -406,13 +406,26 @@ def on_startup(opts = {})
...
 
+  def av_warning_message
+      avdwarn = []
+      avdwarn << "Warning: This copy of the Metasploit Framework has been corrupted by an installed anti-virus program."
+      avdwarn << "         We recommend that you disable your anti-virus or exclude your Metasploit installation path,"
+      avdwarn << "         then restore the removed files from quarantine or reinstall the framework. For more info: "
+      avdwarn << "             https://community.rapid7.com/docs/DOC-1273"
+      avdwarn << ""
+
+      avdwarn.map{|line| print_error(line) }
```
Comment (acammack-r7) [inline lib/msf/ui/console/driver.rb:426]: I would print this to `stderr` to make sure it's not unintentionally ignored or swallowed.

**Review by acammack-r7 — CHANGES_REQUESTED** [review]
Thanks! It'll be nice to have this working again.

File: lib/msf/ui/console/driver.rb (hunk 2 above)
Comment (bcoles) [reply lib/msf/ui/console/driver.rb:426]: Also `80` columns rather than `100` plz. #4776 https://github.com/rapid7/metasploit-framework/pull/14417#issuecomment-731701077

File: lib/msf/ui/console/driver.rb [hunk 3]
```diff
@@ -406,13 +406,25 @@ def on_startup(opts = {})
...
 
     self.on_command_proc = Proc.new { |command| framework.events.on_ui_command(command) }
   end
 
+  def av_warning_message
+      avdwarn = "\e[31m"\
+                "Warning: This copy of the Metasploit Framework has been corrupted by an installed anti-virus program."\
+                " We recommend that you disable your anti-virus or exclude your Metasploit installation path, "\
+                "then restore the removed files from quarantine or reinstall the framework.\e[0m"\
+                "\n\nFor more info: https://community.rapid7.com/docs/DOC-1273\n\n"
```
Comment (AlanFoster) [inline lib/msf/ui/console/driver.rb:423]: This URL seems dead 👀

Comment (SlyFawkes) [reply lib/msf/ui/console/driver.rb:423]: So it is, uhhh any idea what it _used_ to point to?

Comment (dwelch-r7) [reply lib/msf/ui/console/driver.rb:423]: so it is, nice spot, don't suppose you know what it _used_ to say? :sweat_smile: 
I can either remove it or we can find/create a new page

**Comment by cgranleese-r7** [comment]
Tested this and everything seems to work as expected 👍  

Before: 
image

After:
image

**Comment by dwelch-r7** [comment]
# Release Notes

Fixes a bug where the EICAR canary would be checked too late to be useful
