### PR TITLE
Fix #4885, Support basic and form auth at the same time

### LINKED ISSUE #4885: HTTP Client Basic Authentication
When looking at https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/exploit/http/client.rb#L49 a USERNAME and PASSWORD advanced datastore option are added to HTTP client. When i type 'show advanced' the options are missing.

I tested it with `exploit/unix/webapp/wp_admin_shell_upload` which includes `Msf::Exploit::Remote::HttpClient` via the wordpress mixin.

I currently need basic authentication on a site so i looked into implementing it, and found out it's already there but not working correctly

### PR DESCRIPTION
**Pull request by wchen-r7**
## What This Patch Does

When a module uses the HttpClient mixin but registers the USERNAME and PASSWORD datastore options in order to perform a form auth, it loses the ability to also perform a basic auth (sometimes it's
possible to see both). To avoid option name conflicts, basic auth options are now HttpUsername and HttpPassword.

Further more, this PR takes care of the following rules:
- In general, if a module performs a basic auth, it should be using HttpUsername and HttpPassword datastore options.
- If the module performs a form auth (sending the credential in a GET or POST request), then all (HttpUsername, HttpPassword, USERNAME, PASSWORD) can coexist. HttpUsername and HttpPassword are used in case the login form access is locked by basic auth, and USERNAME/PASSWORD are for the login form.
- If the module includes AuthBrute and HttpClient (which is common), but uses the AuthBrute mixin for basic auth, then we use the USERNAME and PASSWORD datastore options. This is necessary, because the AuthBrute uses these two options to import to its own credential list, and not HttpUsername and HttpPassword.
- If the module includes AuthBrute and HttpClient, but does not use the AuthBrute mixin for basic auth, then we can use HttpUsername and HttpPassword. Also, it should deregister USERNAME and PASSWORD if it's not really using the AuthBrute API at all (mostly the case w/ LoginScanner modules)
- If the LoginScanner uses HTTP, then make sure to pass HttpUsername and HttpPassword options from the module.

Fix #4885
## Verification

Verification is kind of tricky, because it's difficult to manually test them all. So I suggest:
- [x] Travis remains green
- [x] Make sure all the changes are following the rules.
- [x] Try to actually run as many modules as possible.

### CODE REVIEW

File: lib/metasploit/framework/login_scanner/axis2.rb [hunk 1]
```diff
@@ -17,7 +17,7 @@ class Axis2 < HTTP
         # (see Base#attempt_login)
         def attempt_login(credential)
           http_client = Rex::Proto::Http::Client.new(
```
Comment (busterb) [inline lib/metasploit/framework/login_scanner/axis2.rb]: Is it time to convert Http::Client to use keyword args maybe?

Comment (wchen-r7) [inline lib/metasploit/framework/login_scanner/axis2.rb]: Maybe.

**Comment by busterb** [comment]
This looks good so far. Been a challenge to test all of the things!

File: modules/auxiliary/scanner/http/dlink_dir_session_cgi_http_login.rb [hunk 2]
```diff
@@ -42,6 +42,8 @@ def initialize
         OptPath.new('PASS_FILE',  [ false, "File containing passwords, one per line",
```
Comment (bcook-r7) [inline modules/auxiliary/scanner/http/dlink_dir_session_cgi_http_login.rb]: had a hard time getting this exploit to work before these changes, so I suspect it is mildly broken

**Comment by bcook-r7** [comment]
let's double-check pro + login scanners to make sure they continue working

**Comment by pbarry-r7** [comment]
Testing looked good with these changes, also with the [associated Pro changes](https://github.com/rapid7/pro/pull/2796).

**Comment by tdoan-r7** [comment]
@pbarry-r7 / @sinn3r can you add release notes please?

**Comment by pbarry-r7** [comment]
# Release Notes

This patch provides modules the ability to support/use both basic auth and form auth simultaneously.
