### PR TITLE
Fix bad DN discovery code and fix bug with querying schema data

### LINKED ISSUE #17429: ldap_query fails on schema extraction when specifying base_dn as child DC
## Steps to reproduce

Running ldap query results in a crash:

```
msf6 auxiliary(gather/ldap_query) > run domain=za.tryhackme.loc username=michael.cameron@za.tryhackme.loc password=Mwtv3419 ZA.TRYHACKME.LOC base_dn='DC=za,DC=tryhackme,DC=loc' action=ENUM_CONSTRAINED_DELEGATION
[*] Running module against 10.200.60.101

[*] User-specified base DN: DC=za,DC=tryhackme,DC=loc
[-] Auxiliary aborted due to failure: unexpected-reply: The LDAP search with (|(LDAPDisplayName=cn)(LDAPDisplayName=samaccountname)(LDAPDisplayName=serviceprincipalname)(LDAPDisplayName=objectcategory)(LDAPDisplayName=msds-allowedtodelegateto)) failed cause the operation targeted an entity within the base DN that does not exist.
[*] Auxiliary module execution completed
``` 

From a breakpoint I can see that the entries are returned successfully, but the metadata query fails:

```
msf6 auxiliary(gather/ldap_query) > run domain=za.tryhackme.loc username=michael.cameron@za.tryhackme.loc password=Mwtv3419 ZA.TRYHACKME.LOC base_dn='DC=za,DC=tryhackme,DC=loc' action=ENUM_CONSTRAINED_DELEGATION
[*] Running module against 10.200.60.101

[*] User-specified base DN: DC=za,DC=tryhackme,DC=loc

From: /mnt/hgfs/metasploit-framework/modules/auxiliary/gather/ldap_query.rb:299 Msf::Modules::Auxiliary__Gather__Ldap_query::MetasploitModule#normalize_entries:

    294:     entries.each do |entry|
    295:       attributes.merge!(entry.to_h)
    296:     end
    297: 
    298:     require 'pry-byebug'; binding.pry
 => 299:     attribute_properties = query_attributes_data(ldap, attributes)
    300: 
    301:     entries.each do |entry|
    302:       # Convert to a hash so we get the raw data we need from within the Net::LDAP::Entry object
    303:       entry = entry.to_h
    304:       entry.each_key do |attribute_name|

[1] pry(#<Msf::Modules::Auxiliary__Gather__Ldap_query::MetasploitModule>)> ldap
=> #<Net::LDAP:0x00005576873f1d00 ...>
[2] pry(#<Msf::Modules::Auxiliary__Gather__Ldap_query::MetasploitModule>)> attributes
=> {:dn=>["CN=IIS Server,CN=Users,DC=za,DC=tryhackme,DC=loc"],
 :cn=>["IIS Server"],
 :samaccountname=>["svcIIS"],
 :serviceprincipalname=>["HTTP/svcServWeb.za.tryhackme.loc"],
 :objectcategory=>["CN=Person,CN=Schema,CN=Configuration,DC=tryhackme,DC=loc"],
 :"msds-allowedtodelegateto"=>
  ["WSMAN/THMSERVER1.za.tryhackme.loc",
   "WSMAN/THMSERVER1",
   "http/THMSERVER1.za.tryhackme.loc",
   "http/THMSERVER1"]}
```

Specifically it fails here as the calculated base dn is wrong:

```
attributes_data = perform_ldap_query(ldap, filter, attributes, base: ['CN=Schema,CN=Configuration', @base_dn].join(','))
```

Values which crash:

```
From: /mnt/hgfs/metasploit-framework/modules/auxiliary/gather/ldap_query.rb:141 Msf::Modules::Auxiliary__Gather__Ldap_query::MetasploitModule#perform_ldap_query:

    139: def perform_ldap_query(ldap, filter, attributes, base: nil)
    140:   base ||= @base_dn
 => 141:   returned_entries = ldap.search(base: base, filter: filter, attributes: attributes)
    142:   query_result = ldap.as_json['result']['ldap_result']
    143: 
    144:   validate_query_result!(query_result, filter)
    145: 
    146:   if returned_entries.nil? || returned_entries.empty?
    147:     print_error("No results found for #{filter}.")
    148:     nil
    149:   else
    150:     returned_entries
    151:   end
    152: end

[11] pry(#<Msf::Modules::Auxiliary__Gather__Ldap_query::MetasploitModule>)> base
=> "CN=Schema,CN=Configuration,DC=za,DC=tryhackme,DC=loc"
[12] pry(#<Msf::Modules::Auxiliary__Gather__Ldap_query::MetasploitModule>)> filter
=> "(|(LDAPDisplayName=cn)(LDAPDisplayName=samaccountname)(LDAPDisplayName=serviceprincipalname)(LDAPDisplayName=objectcategory)(LDAPDisplayName=msds-allowedtodelegateto))"                                          
[13] pry(#<Msf::Modules::Auxiliary__Gather__Ldap_query::MetasploitModule>)> attributes
=> ["LDAPDisplayName", "isSingleValued", "oMSyntax", "attributeSyntax"]
```

I fixed with a local hack to unblock me:

```diff
diff --git a/modules/auxiliary/gather/ldap_query.rb b/modules/auxiliary/gather/ldap_query.rb
index 5e3e4a76e9..49312592fe 100644
--- a/modules/auxiliary/gather/ldap_query.rb
+++ b/modules/auxiliary/gather/ldap_query.rb
@@ -271,7 +271,9 @@ class MetasploitModule < Msf::Auxiliary
     end
     filter += ')'
     attributes = ['LDAPDisplayName', 'isSingleValued', 'oMSyntax', 'attributeSyntax']
-    attributes_data = perform_ldap_query(ldap, filter, attributes, base: ['CN=Schema,CN=Configuration', @base_dn].join(','))
+    # attributes_data = perform_ldap_query(ldap, filter, attributes, base: ['CN=Schema,CN=Configuration', @base_dn].join(','))
+    # With the @base_dn set this becomes 'CN=Schema,CN=Configuration,DC=za,DC=tryhackme,DC=loc', but we need to query with 'CN=Schema,CN=Configuration,DC=tryhackme,DC=loc'
+    attributes_data = perform_ldap_query(ldap, filter, attributes, base: ['CN=Schema,CN=Configuration', 'DC=tryhackme,DC=loc'].join(','))
 
     entry_list = {}
     for entry in attributes_data do
@@ -294,6 +296,7 @@ class MetasploitModule < Msf::Auxiliary
     entries.each do |entry|
       attributes.merge!(entry.to_h)
     end
+
     attribute_properties = query_attributes_data(ldap, attributes)
 
     entries.each do |entry|
```

For context - this is the list DN:

```
CN=Configuration,DC=tryhackme,DC=loc
CN=Schema,CN=Configuration,DC=tryhackme,DC=loc
DC=DomainDnsZones,DC=za,DC=tryhackme,DC=loc
DC=ForestDnsZones,DC=tryhackme,DC=loc
DC=za,DC=tryhackme,DC=loc
```

image

## Were you following a specific guide/tutorial or reading documentation?

https://tryhackme.com/room/exploitingad

## Expected behavior

No crash

## Current behavior

Crash

### Metasploit version

```
msf6 auxiliary(gather/ldap_query) > version
Framework: 6.2.33-dev-a8957bce49
Console  : 6.2.33-dev-a8957bce49
```

### PR DESCRIPTION
**Pull request by gwillcox-r7**
Fix #17429 

Previously the code was failing when querying a child domain due to two reasons:
1. We assumed when automatically discovering the naming contexts that the first naming context returned would always be the base DN. This is not always the case as with child domains it can sometimes be the last entry as noted in my tests. To solve this and to avoid positional issues, I updated the code to use some regexes to first filter out only entries that start with `DN=`, and then to not include certain known bad entries that we want to ignore.
2. We were trying to retrieve schema information using the child domain's base DN. All schema information is stored under the parent domain's DN and we need to use this when querying for schema information. I added a new function, `find_schema_dn` to do this, which will simply grab the `objectCategory` of the base DN object for the domain we are currently querying and then perform some regex to remove the extra `CA=` entries so we just get the naming context of the parent domain we need to query for the schema information.

## Verification

List the steps needed to make sure this thing works

- [ ] Set up an environment where you have a parent domain.
- [ ] Add a new domain using the same type of machine, but set it up as a child domain linked to the parent.
- [ ] Start `msfconsole`
- [ ] `use auxiliary/gather/ldap_query`
- [ ] Set RHOST, DOMAIN, USERNAME, PASSWORD
- [ ] `run`
- [ ] **Verify** that the full data is returned and you don't get any errors about incorrect names or redirects.

### CODE REVIEW

File: modules/auxiliary/gather/ldap_query.rb [hunk 1]
```diff
@@ -263,6 +269,36 @@ def output_data_csv(entries)
...
+  def find_root_dn(ldap)
+    filter = '(objectClass=*)'
+    attributes = ['instanceType']
+    @root_dn = @base_dn
+    loop do
+      attributes_data = perform_ldap_query(ldap, filter, attributes, base: @root_dn)
+      for entry in attributes_data do
+        int_instance_type = entry[:instancetype][0].to_i
+        # Check if this is a root of a naming context (NC).
+        if (int_instance_type & IT_NC_HEAD)
```
Comment (adfoster-r7) [inline modules/auxiliary/gather/ldap_query.rb:281]: Is this valid? I believe `0` is truthy in Ruby, so this will always enter this if statement

Or is `&` overridden to return true/false ?

File: modules/auxiliary/gather/ldap_query.rb [hunk 2]
```diff
@@ -263,6 +269,36 @@ def output_data_csv(entries)
     generate_rex_tables(entries, 'csv')
   end
 
+  def find_root_dn(ldap)
+    filter = '(objectClass=*)'
+    attributes = ['instanceType']
+    @root_dn = @base_dn
+    loop do
```
Comment (adfoster-r7) [inline modules/auxiliary/gather/ldap_query.rb:276]: This loop makes me uncomfortable with there not being a clear predicate here that this will ever terminate 🤔

File: modules/auxiliary/gather/ldap_query.rb (hunk 1 above)
Comment (adfoster-r7) [reply modules/auxiliary/gather/ldap_query.rb:281]: Similar to the 'never terminating' logic comment above; If `if (int_instance_type & IT_NC_HEAD) == 1` evaluated to to false - would this just be an infinite loop if it never found found the base case? 🤔

Comment (gwillcox-r7) [reply modules/auxiliary/gather/ldap_query.rb:281]: I thought this was a bitwise AND operation with the value of `IT_NC_HEAD` aka 1?

File: modules/auxiliary/gather/ldap_query.rb [hunk 3]
```diff
@@ -263,6 +269,36 @@ def output_data_csv(entries)
...
+            parts = @root_dn.split(',')
+            if parts.length <= 2
+              print_good("Discovered root DN: #{@root_dn}")
+              return @root_dn
+            end
+            @root_dn = parts[1..].join(',')
+          else
+            # We have found the root naming context (NC)
+            print_good("Discovered root DN: #{@root_dn}")
+            @root_dn
```
Comment (gwillcox-r7) [inline modules/auxiliary/gather/ldap_query.rb:295]: This should be returning here to break out of the loop. Should likely update this to be `return @root_dn`

File: modules/auxiliary/gather/ldap_query.rb (hunk 2 above)
Comment (gwillcox-r7) [reply modules/auxiliary/gather/ldap_query.rb:276]: The idea here was that we progressively change `@root_dn` and use that as the termination point for the loop, aka if it ever gets to two parts separated by a comma, or does not contain a comma at all, then we terminate the loop.

File: modules/auxiliary/gather/ldap_query.rb (hunk 1 above)
Comment (adfoster-r7) [reply modules/auxiliary/gather/ldap_query.rb:281]: I believe 0 is truthy in Ruby, so this will always enter this if statement

```ruby
if 0
  puts '0 is truthy'
end

if 1
  puts '1 is also truthy'
end
```

Result:

```
$ bundle exec ruby main.rb
0 is truthy
1 is also truthy
```

Comment (gwillcox-r7) [reply modules/auxiliary/gather/ldap_query.rb:281]: Oh nm I see the issue now:

```
irb(main):009:1* if(9 & 1)
irb(main):010:1*   print("A")
irb(main):011:0> end
A=> nil
irb(main):012:1* if(8 & 1)
irb(main):013:1*   print("A")
irb(main):014:0> end
A=> nil
irb(main):015:0> 
```

Comment (adfoster-r7) [reply modules/auxiliary/gather/ldap_query.rb:281]: So most likely missing the `==` operator to convert the bit mask integer result into a boolean

```
if (int_instance_type & IT_NC_HEAD) == 1
```

**Comment by gwillcox-r7** [comment]
Okay did a complete redesign since I realized there is a simpler way of doing things here. Going to push up some changes now that should contain an easier approach that doesn't require complex lookups to get the same data.

File: modules/auxiliary/gather/ldap_query.rb (hunk 1 above)
Comment (gwillcox-r7) [reply modules/auxiliary/gather/ldap_query.rb]: Removed this and loop and the constants with the revised update.

File: modules/auxiliary/gather/ldap_query.rb (hunk 3 above)
Comment (gwillcox-r7) [reply modules/auxiliary/gather/ldap_query.rb]: Removed this and loop and the constants with the revised update.

File: modules/auxiliary/gather/ldap_query.rb (hunk 2 above)
Comment (gwillcox-r7) [reply modules/auxiliary/gather/ldap_query.rb]: Removed this and loop and the constants with the revised update.

File: modules/auxiliary/gather/ldap_query.rb [hunk 4]
```diff
@@ -440,6 +461,7 @@ def run
           unless (@base_dn = discover_base_dn(ldap))
             print_warning("Couldn't discover base DN!")
           end
+          @schema_dn = find_schema_dn(ldap)
```
Comment (adfoster-r7) [inline modules/auxiliary/gather/ldap_query.rb:464]: If the user specifies their own `datastore['BASE_DN']` - would that make `@schema_dn` nil still?

Comment (gwillcox-r7) [reply modules/auxiliary/gather/ldap_query.rb:464]: Woops good spotting, let me fix that up.

Comment (gwillcox-r7) [reply modules/auxiliary/gather/ldap_query.rb]: Fixed in https://github.com/rapid7/metasploit-framework/pull/17532/commits/71aa4bdace154ef9523a78427be61030d7d867f5

**Comment by adfoster-r7** [comment]
With a child domain

Before:

```
msf6 auxiliary(gather/ldap_query) > run rhost=192.168.123.135 username=Administrator password=p4$$w0rd ldapauth=kerberos ldaprhostname=WIN-9R8L3737HPO.dev.adf3.local domain=dev.adf3.local domaincontrollerrhost=192.168.123.135
[*] Running module against 192.168.123.135

[*] 192.168.123.135:88 - Using cached credential for ldap/WIN-9R8L3737HPO.dev.adf3.local@DEV.ADF3.LOCAL Administrator@DEV.ADF3.LOCAL
[*] Discovering base DN automatically
[+] 192.168.123.135:389 Discovered base DN: CN=Configuration,DC=adf3,DC=local
[-] No results found for (|(|(|(objectClass=organizationalPerson)(sAMAccountType=805306368))(objectcategory=user))(objectClass=user)).
[-] No entries could be found for (|(objectClass=organizationalPerson)(sAMAccountType=805306368)(objectcategory=user)(objectClass=user))!
[*] Auxiliary module execution completed
```

After:

```
msf6 auxiliary(gather/ldap_query) > run rhost=192.168.123.135 username=Administrator password=p4$$w0rd ldapauth=kerberos ldaprhostname=WIN-9R8L3737HPO.dev.adf3.local domain=dev.adf3.local domaincontrollerrhost=192.168.123.135
[*] Running module against 192.168.123.135

[+] 192.168.123.135:88 - Received a valid TGT-Response
[*] 192.168.123.135:389 - TGT MIT Credential Cache ticket saved to /Users/adfoster/.msf4/loot/20230126104104_default_192.168.123.135_mit.kerberos.cca_889754.bin
[+] 192.168.123.135:88 - Received a valid TGS-Response
[*] 192.168.123.135:389 - TGS MIT Credential Cache ticket saved to /Users/adfoster/.msf4/loot/20230126104104_default_192.168.123.135_mit.kerberos.cca_303399.bin
[+] 192.168.123.135:88 - Received a valid delegation TGS-Response
[*] Discovering base DN automatically
[+] 192.168.123.135:389 Discovered base DN: DC=dev,DC=adf3,DC=local
[+] 192.168.123.135:389 Discovered schema DN: DC=adf3,DC=local
CN=Administrator CN=Users DC=dev DC=adf3 DC=local
=================================================

 Name                Attributes
 ----                ----------
 badpwdcount         0
 description         Built-in account for administering the computer/domain
 lastlogoff          1601-01-01 00:00:00 UTC
 lastlogon           2023-01-26 10:41:04 UTC
 logoncount          71
 memberof            CN=Group Policy Creator Owners,CN=Users,DC=dev,DC=adf3,DC=local || CN=Domain Admins,CN=Users,DC=dev,DC=adf3,DC=local || CN=Administrators,CN=Builtin,DC=dev,DC=adf3,DC=local
 name                Administrator
 pwdlastset          133187332854482327
 samaccountname      Administrator
 useraccountcontrol  512
```

**Comment by adfoster-r7** [comment]
## Release Notes

Updates `auxiliary/gather/ldap_query` to support querying child Active Directory domains
