### PR TITLE
Fix regression in psexec mixing filename and encoder

### LINKED ISSUE #13407: psexec service encoder: potential regression?
I was looking at the implementation of psexec and I was wondering what was the usage of the `serviceencoder` variable:
https://github.com/rapid7/metasploit-framework/blob/e9eb008a7a8670573a8ed3e5a7bcf15920d61328/lib/msf/core/exploit/smb/client/psexec.rb#L272-L296
It's only referenced 3 times in @Rapid7 repos:
https://github.com/search?q=serviceencoder+user%3Arapid7&type=Code&ref=advsearch&l=&l=

So it seems useless and I nearly suggested its removal... Before checking when it was introduced!

It originally appeared in commit 378208bc3db6f3ebd39f03a36d705c25b70e99ce from PR #7016
```ruby
    serviceencoder = datastore['SERVICE_STUB_ENCODER'] || ''
```
So its value comes from `SERVICE_STUB_ENCODER` which is indeed currently offered by 2 modules:
https://github.com/rapid7/metasploit-framework/blob/b74e662385764c4b121b801d6290d4627bf75581/modules/exploits/windows/smb/psexec.rb#L85
https://github.com/rapid7/metasploit-framework/blob/80efe815041f493ec2ed971ecd0db64239a24731/modules/exploits/windows/smb/ms17_010_psexec.rb#L101

So, when did `serviceencoder` became unlinked from `SERVICE_STUB_ENCODER`?
-> https://github.com/rapid7/metasploit-framework/commit/3353102dc1f9666527c9dcfd39da40a5ed0c4a52#diff-46319ef23d9c2eb013d87a22f1ad32f9L330-R317 (in #9881)

So in my understanding the SERVICE_STUB_ENCODER has no effect now which is a potential regression...
To confirm, `use exploit/windows/smb/psexec` and `set SERVICE_STUB_ENCODER garbage` (and set other options) and notice that the module works without complaining.

What do you think? Should the code be changed?
There was a comment in this PR https://github.com/rapid7/metasploit-framework/pull/9881#discussion_r182488587 but I don't know enough to properly understand it and suggest something appropriate.

### PR DESCRIPTION
**Pull request by cnotin**
Closes #13407

Fixes regressions in psexec mixin, two parameters were ignored:
* `SERVICE_FILENAME`
* `SERVICE_STUB_ENCODER`

I added those two as parameters to `native_upload` as suggested by @jmartin-r7 and @Auxilus -> https://github.com/rapid7/metasploit-framework/issues/13407#issuecomment-625341902
I also could have added to the mixin, but they're only relevant with native upload and not other, for example they aren't used by psexec_command modules.

## Verification

* See before how the SERVICE_FILENAME was ignored:
image
image

* And after:
image
image

The SERVICE_STUB_ENCODER effect isn't directly visible.
However we can use a bug #13435 to make it visible
* Before: no error when choosing an invalid encoder (meaning it was ignored)
image

* After: we get an error so it was taken into account:
image

- [ ] Start `msfconsole`
- [ ] `use use exploit/windows/smb/psexec`
- [ ] set login/pwd/rhost as you'd like
- [ ] `set target 2` (native upload)
- [ ] `set SERVICE_FILENAME test1.exe`
- [ ] **Verify** that the created file is indeed "test1.exe"

- [ ] **Please test** with module ms17_010_psexec as I don't have a target with me (but the code should be good :))

### CODE REVIEW

**Comment by wvu-r7** [comment]
This is an excellent PR. Great submission. Will check over the code and test in a little while.

**Comment by cnotin** [comment]
Glad you like it!

File: lib/msf/core/exploit/smb/client/psexec.rb [hunk 1]
```diff
@@ -269,10 +269,7 @@ def execute_powershell_payload
     end
   end
 
-  def native_upload(smb_share)
-    filename = "#{Rex::Text.rand_text_alpha(8)}.exe"
-    serviceencoder = ''
-
+  def native_upload(smb_share, filename, service_encoder)
```
Comment (wvu-r7) [inline lib/msf/core/exploit/smb/client/psexec.rb:272]: I wasn't sure about this change at first, but both `SERVICE_FILENAME` and `SERVICE_STUB_ENCODER` are registered in the modules, so it's fine. Looks like you caught all the uses, too.

**Comment by wvu-r7** [comment]
Linking #6180 for my reference.

**Comment by wvu-r7** [comment]
# Release Notes

This fixes a regression in the `SERVICE_FILENAME` and `SERVICE_STUB_ENCODER` options in `psexec` code.

File: modules/exploits/windows/smb/ms17_010_psexec.rb [hunk 2]
```diff
@@ -127,20 +127,23 @@ def exploit
     end
   end
 
-  def smb_pwn()
+  def smb_pwn
+    service_filename = datastore['SERVICE_FILENAME'] || "#{rand_text_alpha(8)}.exe"
```
Comment (wvu-r7) [inline modules/exploits/windows/smb/ms17_010_psexec.rb:131]: See https://github.com/rapid7/metasploit-framework/pull/13436/commits/ef069ce5ef31c7ab98a2ab7641bae47c4333ea5f.

File: modules/exploits/windows/smb/psexec.rb [hunk 3]
```diff
@@ -87,13 +87,16 @@ def initialize(info = {})
   end
 
   def native_upload_with_workaround
+    service_filename = datastore['SERVICE_FILENAME'] || "#{rand_text_alpha(8)}.exe"
```
Comment (wvu-r7) [inline modules/exploits/windows/smb/psexec.rb:90]: See https://github.com/rapid7/metasploit-framework/pull/13436/commits/ef069ce5ef31c7ab98a2ab7641bae47c4333ea5f.

**Comment by wvu-r7** [comment]
# Release Notes

This fixes a regression in the `SERVICE_FILENAME` and `SERVICE_STUB_ENCODER` options in `psexec` code.
