### PR TITLE
Fix up lib/postgres/postgre-pr/message.rb's self.read function to Avoid nil Errors After Calling stream.read_exactly_n_bytes

### LINKED ISSUE #13217: Auxiliary failed: NoMethodError undefined method `>=' for nil:NilClass
## Steps to reproduce
 
 1.
```
use auxiliary/scanner/postgres/postgres_login
```

 2.
```
set RHOST <TARGET>
```

 3.
```
run
```

## Expected behavior

To run without error and have success if vulnerability it found. 

## Current behavior

```
Auxiliary failed: NoMethodError undefined method `>=' for nil:NilClass
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/postgres/postgres-pr/message.rb:49:in `read'
[-]   /usr/share/metasploit-framework/lib/postgres/postgres-pr/connection.rb:71:in `block in initialize'
[-]   /usr/share/metasploit-framework/lib/postgres/postgres-pr/connection.rb:70:in `loop'
[-]   /usr/share/metasploit-framework/lib/postgres/postgres-pr/connection.rb:70:in `initialize'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/postgres.rb:44:in `new'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/postgres.rb:44:in `attempt_login'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:231:in `block in scan!'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:154:in `block in each_credential'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:157:in `block (3 levels) in each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:155:in `each_line'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:155:in `block (2 levels) in each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:143:in `each_line'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:143:in `block in each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:142:in `open'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:142:in `each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/postgres/postgres_login.rb:78:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:117:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
[*] Auxiliary module execution completed
```

### Metasploit version

```
5.0.83
```

### I installed Metasploit with:

- [ ] Kali package via apt

### OS

Kali Linux.

### PR DESCRIPTION
**Pull request by gwillcox-r7**
Closes #13217

This PR fixes an issue first reported via #13217 where its possible for `lib/postgres/postgres-pr/message.rb` to try and read bytes from a stream, but that stream doesn't return any bytes. There are two variables this could affect: `type`, and `length`. The issue that was reported was when `length` was set to `nil`, but in theory the `type` variable could also be set to `nil` if the call to `stream.read_exactly_n_bytes(1)` didn't return any data and `startup` is set to `false` or `nil`.

This PR fixes this issue in two ways:

1. Adds a check to ensure that `length` is not `nil`, and ensure that this check takes place before checking that `length` is not greater than or equal to 4 to avoid stack traces.
2. Adds an additional check on the `type` value if `startup` was `false` or `nil` to ensure that `type` is not `nil` before we proceed to use it as an offset into an array.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/postgres/postgres_login`
- [x] Set the `RHOST` option and verify the module runs normally.
- [x] **Verify** that these code changes do not break anything.
- [x] Happy dance 👍

### CODE REVIEW

File: lib/postgres/postgres-pr/message.rb [hunk 1]
```diff
@@ -46,7 +46,14 @@ def self.read(stream, startup=false)
     type = stream.read_exactly_n_bytes(1) unless startup
     length = stream.read_exactly_n_bytes(4).to_s.unpack('N').first  # FIXME: length should be signed, not unsigned
 
-    raise ParseError unless length >= 4
+    raise ParseError unless (!length.nil? && length >= 4)
```
Comment (bwatters-r7) [inline lib/postgres/postgres-pr/message.rb:49]: I am not a super fan of anything involving `unless` and `not`  Unless is bad enough, but we're a happy Ruby family [twitch]
Could this be rewritten as:
`raise ParseError if(length.nil? || length < 4)`?

Comment (gwillcox-r7) [reply lib/postgres/postgres-pr/message.rb:49]: Yep that makes sense, I was trying to keep the original `unless` statement in there to minimize impact but this makes sense.

Comment (gwillcox-r7) [reply lib/postgres/postgres-pr/message.rb]: Should now be fixed

**Comment by bwatters-r7** [comment]
```
msf5 > use auxiliary/scanner/postgres/postgres_login 
msf5 auxiliary(scanner/postgres/postgres_login) > set rhost 127.0.0.1
rhost => 127.0.0.1
msf5 auxiliary(scanner/postgres/postgres_login) > run

[-] 127.0.0.1:5432 - LOGIN FAILED: :@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: :tiger@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: :postgres@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: :password@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: :admin@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: postgres:@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: postgres:tiger@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: postgres:postgres@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: postgres:password@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: postgres:admin@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: scott:@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: scott:tiger@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: scott:postgres@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: scott:password@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: scott:admin@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: admin:@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: admin:tiger@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: admin:postgres@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: admin:password@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: admin:admin@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: postgres:postgres@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: postgres:password@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: postgres:admin@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: admin:admin@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[-] 127.0.0.1:5432 - LOGIN FAILED: admin:password@template1 (Incorrect: The connection was refused by the remote host (127.0.0.1:5432).)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/postgres/postgres_login) > 

```

File: lib/postgres/postgres-pr/message.rb [hunk 2]
```diff
@@ -46,7 +46,14 @@ def self.read(stream, startup=false)
     type = stream.read_exactly_n_bytes(1) unless startup
     length = stream.read_exactly_n_bytes(4).to_s.unpack('N').first  # FIXME: length should be signed, not unsigned
 
-    raise ParseError unless length >= 4
+    raise ParseError if (!length.nil? || length >= 4)
```
Comment (bwatters-r7) [inline lib/postgres/postgres-pr/message.rb:49]: I don't understand the `!` in there?  I thought we needed to raise a parse error if the value was nil?

Comment (bwatters-r7) [reply lib/postgres/postgres-pr/message.rb:49]: Also, shouldn't the second conditional change to `length < 3`?

Comment (gwillcox-r7) [reply lib/postgres/postgres-pr/message.rb:49]: Ah sorry I forgot to convert these conditions when changing the statement from `unless` to `if`. Your perfectly right both of these should have changed.

Comment (gwillcox-r7) [reply lib/postgres/postgres-pr/message.rb:49]: Also technically it should be `length < 4`

**Comment by bwatters-r7** [comment]
# Release Notes
This fixes a very extreme edge case bug where it is possible but unlikely a race condition occurs during a socket read, and the data sent to the postgres parser is of nil value.  This verifies the data is not nil before attempting to parse the data.
