### PR TITLE
Fix #14261 Prompt timestamp escape display error

### LINKED ISSUE #14261: Timestamp escape in prompt is only showing the time
Setting `Prompt` to `%T` ends up only displaying the time, not the full date and time, even though `PromptTimeFormat` has the escapes for everything in it. This is showing up both on a Kali install of MSF5 and an Ubuntu package of MSF6.

## Steps to reproduce

```
root@hostname:~$ msfconsole


  Metasploit Park, System Security Interface
  Version 4.0.5, Alpha E
  Ready...
  > access security
  access: PERMISSION DENIED.
  > access security grid
  access: PERMISSION DENIED.
  > access main security grid
  access: PERMISSION DENIED....and...
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!
  YOU DIDN'T SAY THE MAGIC WORD!


       =[ metasploit v6.0.10-dev-                         ]
+ -- --=[ 2069 exploits - 1122 auxiliary - 352 post       ]
+ -- --=[ 592 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 7 evasion                                       ]

Metasploit tip: View advanced module options with advanced

msf6 > show options

Global Options:
===============

   Option             Current Setting      Description
   ------             ---------------      -----------
   ConsoleLogging     false                Log all console input and output
   LogLevel           0                    Verbosity of logs (default 0, max 3)
   MeterpreterPrompt  meterpreter  The meterpreter prompt string
   MinimumRank        0                    The minimum rank of exploits that will run without explicit confirmation
   Prompt             msf6                 The prompt string
   PromptChar         >                    The prompt character
   PromptTimeFormat   %Y-%m-%d %H:%M:%S    Format for timestamp escapes in prompts
   SessionLogging     false                Log all input and output for sessions
   TimestampOutput    false                Prefix all console output with a timestamp

msf6 > set Prompt %T
Prompt => %T
11:14:55 > show options

Global Options:
===============

   Option             Current Setting      Description
   ------             ---------------      -----------
   ConsoleLogging     false                Log all console input and output
   LogLevel           0                    Verbosity of logs (default 0, max 3)
   MeterpreterPrompt  meterpreter  The meterpreter prompt string
   MinimumRank        0                    The minimum rank of exploits that will run without explicit confirmation
   Prompt             %T                   The prompt string
   PromptChar         >                    The prompt character
   PromptTimeFormat   %Y-%m-%d %H:%M:%S    Format for timestamp escapes in prompts
   SessionLogging     false                Log all input and output for sessions
   TimestampOutput    false                Prefix all console output with a timestamp

11:15:00 > version
Framework: 6.0.10-dev-
Console  : 6.0.10-dev-
```

## Were you following a specific guide/tutorial or reading documentation?

https://malicious.link/post/2011/2011-10-09-msfconsole-prompt-fiddling/

## Expected behavior

I expected the full date and time to be included in the prompt

## Current behavior

Only the time shows up.

### Metasploit version

6.0.10-dev-

### PR DESCRIPTION
**Pull request by Chiggins**
This PR fixes issue #14261. 

Forgot I had this laying around, and was able to get to it after the holidays and chaos of the start of 2021. This gets the timestamp to show up in the prompt when setting the prompt to `%T`. Without being too familiar of files under rex, I think this should do the trick. Let me know if it should be cleaned up or if I logically didn't get something right. 

Sorry for the delay!

## Verification

- [ ] Start `msfconsole`
- [ ] `show options` to verify the value of `PromptTimeFormat`
- [ ] `set Prompt %T` to set the prompt to display the correct date and time
- [ ] **Verify** that the accurate date and time is shown 

```
./msfconsole -q -r prompt_test.rc
[*] Processing prompt_test.rc for ERB directives.
resource (prompt_test.rc)> show options

Global Options:
===============

   Option             Current Setting      Description
   ------             ---------------      -----------
   ConsoleLogging     false                Log all console input and output
   LogLevel           0                    Verbosity of logs (default 0, max 3)
   MeterpreterPrompt  meterpreter  The meterpreter prompt string
   MinimumRank        0                    The minimum rank of exploits that will run without explicit confirmation
   Prompt             msf6                 The prompt string
   PromptChar         >                    The prompt character
   PromptTimeFormat   %Y-%m-%d %H:%M:%S    Format for timestamp escapes in prompts
   SessionLogging     false                Log all input and output for sessions
   TimestampOutput    false                Prefix all console output with a timestamp

resource (prompt_test.rc)> set Prompt %T
Prompt => %T
2021-01-19 17:59:56 > set Prompt msf6
Prompt => msf6
msf6 > set Prompt %T
Prompt => %T
2021-01-19 18:00:16 > 
```

### CODE REVIEW

File: lib/rex/ui/text/shell.rb [hunk 1]
```diff
@@ -2,6 +2,8 @@
 require 'rex/text/color'
 require 'rex/ui'
 
+gem 'pry-byebug'
+
```
Comment (gwillcox-r7) [inline lib/rex/ui/text/shell.rb:6]: I think this was left behind whilst you were debugging this issue, would probably be a good idea to remove this.

Comment (Chiggins) [reply lib/rex/ui/text/shell.rb]: Good call, forgot about that. Removed.

**Comment by gwillcox-r7** [comment]
Testing this on `master` confirmed that the original issue does indeed exist:

```
msf6 > set Prompt %T
Prompt => %T
10:49:54 > 
```

And with the patches the issue is gone.

```
msf6 > set Prompt %T
Prompt => %T
2021-01-20 11:01:19 >
```

Will merge this in now.

**Comment by gwillcox-r7** [comment]
# Release Notes
A bug was fixed in the `lib/rex/ui/text/shell.rb` library whereby users who used the `%T` character within their command prompts would not get the full timestamp information. A fix has been applied to address this regression so that users can now get the full timestamp information within their prompts.
