### PR TITLE
Expand environment variables on Linux

### LINKED ISSUE #14357: fs.file.expand_path does not expand paths and environment variables on Linux Meterpreter
The expand_path call, as defined at https://github.com/rapid7/metasploit-framework/blob/54b893aa4d020d7d2ecd4335b32ee3f30bd6452a/lib/msf/core/post/file.rb#L123 and which is accessible via `client.fs.file.expand_path`, does not appropriately expand paths on Linux, particularly for the `~` character., but also for environment variables such as `$HOME`

## Steps to reproduce

How'd you do it?

1. Obtain a Linux Meterpreter shell on a Linux target
2. Type `irb` to get an interactive IRB shell when the `meterpreter>` prompt appears. It should state that you in the `client` object.
3. Type `fs.file.expand_path("~")`.

See below for a demonstration:

```
msf6 exploit(multi/handler) > set PAYLOAD linux/x64/meterpreter/bind_tcp
PAYLOAD => linux/x64/meterpreter/bind_tcp
msf6 exploit(multi/handler) > show options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (linux/x64/meterpreter/bind_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LPORT  4444             yes       The listen port
   RHOST  172.27.22.65     no        The target address


Exploit target:
   Id  Name
   --  ----
   0   Wildcard Target


msf6 exploit(multi/handler) > set RHOST 127.0.0.1
RHOST => 127.0.0.1
msf6 exploit(multi/handler) > exploit
[*] Started bind TCP handler against 127.0.0.1:4444
[*] Meterpreter session 2 opened (0.0.0.0:0 -> 127.0.0.1:4444) at 2020-11-05 13:33:23 -0600
meterpreter > cd ~
[-] 1001: Operation failed: 2
meterpreter > pwd
/home/gwillcox/git/metasploit-framework
meterpreter > irb
[*] You are in the "client" (session) object
irb: warn: can't alias kill from irb_kill.
>> fs.file.expand_path("~")
=> "~"
>> exit
meterpreter > shell
Process 20489 created.
Channel 1 created.
echo ~
/home/gwillcox
exit
meterpreter > irb
[*] Starting IRB shell...
[*] You are in the "client" (session) object

>> File.expand_path("~")
=> "/home/gwillcox"
```

## Were you following a specific guide/tutorial or reading documentation?

This was discovered whilst trying to test out https://github.com/rapid7/metasploit-framework/pull/13954

## Expected behavior

The `~` character should expand into the path for the user's home directory on the system we are targeting and the user we are running as.

## Current behavior

The path is not expanded and the `~` character stays as is.

### Metasploit version

v6.0.15-dev-17fb85c670 with Ruby 2.7.2

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/database]
default_db=local-https-data-service

[framework/database/local-https-data-service]
url=[Filtered]
cert=[Filtered]
skip_verify=[Filtered]
api_token=[Filtered]

[framework/ui/console]
ActiveModule=exploit/multi/handler

[multi/handler]
PAYLOAD=linux/x64/meterpreter/bind_tcp
WORKSPACE=
VERBOSE=false
WfsDelay=0
EnableContextEncoding=false
ContextInformationFile=
DisablePayloadHandler=false
ExitOnSession=true
ListenerTimeout=0
LPORT=4444
RHOST=127.0.0.1
PingbackRetries=0
PingbackSleep=30
PayloadUUIDSeed=
PayloadUUIDRaw=
PayloadUUIDName=
PayloadUUIDTracking=false
EnableStageEncoding=false
StageEncoder=
StageEncoderSaveRegisters=
StageEncodingFallback=true
PrependMigrate=false
PrependMigrateProc=
EXITFUNC=process
AutoLoadStdapi=true
AutoVerifySession=true
AutoVerifySessionTimeout=30
InitialAutoRunScript=
AutoRunScript=
AutoSystemInfo=true
EnableUnicodeEncoding=false
HandlerSSLCert=
SessionRetryTotal=3600
SessionRetryWait=10
SessionExpirationTimeout=604800
SessionCommunicationTimeout=300
PayloadProcessCommandLine=
AutoUnhookProcess=false
PrependFork=false
PrependSetresuid=false
PrependSetreuid=false
PrependSetuid=false
PrependSetresgid=false
PrependSetregid=false
PrependSetgid=false
PrependChrootBreak=false
AppendExit=false
MeterpreterDebugLevel=0
RemoteMeterpreterDebugFile=
loglevel=3
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
2190   client.fs.file.expand_path
2191   irb
2192   use multi/handler
2193   set payload windows/x64/meterpreter/bind_tcp
2194   show options
2195   set RHOST 172.27.22.65
2196   exploit
2197   client
2198   irb
2199   pwd
2200   irb
2201   pwd
2202   cmd_cd
2203   cd "%TEMP%"
2204   dir
2205   pwd
2206   exit
2207   set PAYLOAD linux/x64/meterpreter/bind_tcp
2208   show options
2209   set RHOST 127.0.0.1
2210   exploit
2211   cd ~
2212   pwd
2213   irb
2214   shell
2215   irb
2216   version
2217   clear
2218   background
2219   set loglevel 3
2220   sessions -i 2
2221   cd ~
2222   debug
2223   background
2224   debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[11/05/2020 13:32:32] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[11/05/2020 13:32:32] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[11/05/2020 13:32:32] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[11/05/2020 13:32:32] [e(0)] core: Errno::EISDIR : Is a directory @ rb_sysopen - test
./msfvenom:482:in `initialize'
./msfvenom:482:in `open'
./msfvenom:482:in `<main>'
[11/05/2020 13:33:07] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[11/05/2020 13:33:07] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[11/05/2020 13:33:07] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[11/05/2020 13:33:07] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[11/05/2020 13:33:27] [e(0)] meterpreter: 1001: Operation failed: 2
[11/05/2020 13:51:21] [e(0)] meterpreter: 1001: Operation failed: 2
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[-] Error handling request: undefined method `[]=' for nil:NilClass.
    Call Stack:
	 /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/servlet/login_servlet.rb:42:in `block in create_login'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `load'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `<main>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
[-] Error handling request: undefined method `[]=' for nil:NilClass.
    Call Stack:
	 /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/servlet/login_servlet.rb:42:in `block in create_login'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `load'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `<main>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
[-] Error handling request: undefined method `[]=' for nil:NilClass.
    Call Stack:
	 /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/servlet/login_servlet.rb:42:in `block in create_login'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `load'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `<main>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
[-] Error handling request: undefined method `[]=' for nil:NilClass.
    Call Stack:
	 /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/servlet/login_servlet.rb:42:in `block in create_login'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `load'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `<main>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
[-] Error handling request: undefined method `[]=' for nil:NilClass.
    Call Stack:
	 /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/servlet/login_servlet.rb:42:in `block in create_login'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `load'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `<main>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
[-] Error handling request: undefined method `[]=' for nil:NilClass.
    Call Stack:
	 /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/servlet/login_servlet.rb:42:in `block in create_login'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `load'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `<main>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
[-] Error handling request: undefined method `[]=' for nil:NilClass.
    Call Stack:
	 /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/servlet/login_servlet.rb:42:in `block in create_login'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `load'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `<main>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
[-] Error handling request: undefined method `[]=' for nil:NilClass.
    Call Stack:
	 /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/servlet/login_servlet.rb:42:in `block in create_login'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `load'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/thin:23:in `<main>'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
	 /home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
[-] Error handling request: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type inet: "186"
[-] Error handling request: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type inet: "186"
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/dir.rb:183:in `chdir'
/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:279:in `cmd_cd'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'
/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:153:in `run'
/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
/home/gwillcox/git/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:583:in `_interact'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/interactive.rb:51:in `interact'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1572:in `cmd_sessions'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/exploit.rb:222:in `cmd_exploit'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
[11/05/2020 13:41:10] [w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[11/05/2020 13:51:21] [e(0)] meterpreter: 1001: Operation failed: 2
[11/05/2020 13:51:21] [d(0)] meterpreter: Call stack:
/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/dir.rb:183:in `chdir'
/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:279:in `cmd_cd'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'
/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:153:in `run'
/home/gwillcox/git/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
/home/gwillcox/git/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:583:in `_interact'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/interactive.rb:51:in `interact'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1572:in `cmd_sessions'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_command'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:476:in `block in run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `each'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:470:in `run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
#<Thread:0x0000559f04276840@/home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/job_processor.rb:18 run> terminated with exception (report_on_exception is true):
/home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/job_processor.rb:24:in `rescue in block (2 levels) in start_processor_thread': undefined method `print_error' for #<JobProcessor:0x0000559f04276930> (NoMethodError)
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/job_processor.rb:21:in `block (2 levels) in start_processor_thread'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/job_processor.rb:19:in `loop'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/job_processor.rb:19:in `block in start_processor_thread'
/usr/share/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/base64.rb:101:in `urlsafe_decode64': undefined method `tr' for #<Hash:0x0000559f03ea1580> (NoMethodError)
Did you mean?  try
	from /home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/remote/http/response_data_helper.rb:76:in `process_file'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/servlet/loot_servlet.rb:46:in `block (2 levels) in report_loot'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/job_processor.rb:22:in `block (2 levels) in start_processor_thread'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/job_processor.rb:19:in `loop'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/job_processor.rb:19:in `block in start_processor_thread'
Writing PID to /home/gwillcox/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Writing PID to /home/gwillcox/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Writing PID to /home/gwillcox/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Exiting!
Writing PID to /home/gwillcox/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Exiting!
Writing PID to /home/gwillcox/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Exiting!
Writing PID to /home/gwillcox/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Writing PID to /home/gwillcox/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
2020-11-03 12:40:16 - PG::ConnectionBad - could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5433?
:
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/pg-1.2.3/lib/pg.rb:58:in `new'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:413:in `with_connection'
	/home/gwillcox/git/metasploit-framework/lib/msf/core/db_manager/user.rb:10:in `users'
	/home/gwillcox/git/metasploit-framework/lib/msf/core/web_services/metasploit_api_app.rb:68:in `block in <class:MetasploitApiApp>'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1000:in `block in filter!'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:999:in `each'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:999:in `filter!'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1126:in `block in dispatch!'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/bin/thin:23:in `load'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/bin/thin:23:in `<main>'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
	/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
Exiting!
Writing PID to /home/gwillcox/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Writing PID to /home/gwillcox/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Writing PID to /home/gwillcox/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Exiting!
/home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/eventmachine-1.2.7/lib/em/connection.rb:430:in `block in start_tls': Could not find /home/gwillcox/.msf4/msf-ws-key.pem for start_tls (EventMachine::FileNotFoundException)
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/eventmachine-1.2.7/lib/em/connection.rb:428:in `each'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/eventmachine-1.2.7/lib/em/connection.rb:428:in `start_tls'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:152:in `initialize_connection'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:1527:in `event_callback'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/bin/thin:23:in `load'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/bin/thin:23:in `<main>'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
	from /home/gwillcox/.rvm/gems/ruby-2.7.2@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.0.15-dev-17fb85c670
Ruby: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
Install Root: /home/gwillcox/git/metasploit-framework
Session Type: postgresql selected, no connection
Install Method: Git Clone
```

</details>

### PR DESCRIPTION
**Pull request by smashery**
This PR resolves #14357. The `expand_path` function previously only worked on Windows; with this, it also works on Unix.

The approach I took was the one suggested by @timwr in the issue discussion: to do pattern-matching in the Framework itself, and then just request environment variables from Meterp, and slot them in.

The advantage of this approach is that the pattern-matching would have needed to be implemented _somewhere_ for Mettle, since the built-in function to do it in Mettle's libc (musl) just launches `sh`, which isn't great from a forensics point of view. Doing it in Ruby rather than C lets us reduce code and leverage existing work in each of the other Meterps.

Implementing this parsing manually means there are some rarer use cases that I haven't covered compared to a regular implementation of wordexp, such as escaping dollar signs (e.g. an actual folder called `$home`), or resolving home directories of other users (e.g. `~root => /root`); happy to discuss if it's felt these cases are important. (Now that I'm looking at it, I can't figure out a way to do the equivalent in Windows i.e. `cd`ing into a directory that is actually called `%TEMP%`).

Interestingly, I'd initially thought Python's `os.path.expandvars` would be an easy win for the Python meterpreter, but even that doesn't do dollar-escaping of backslashes or quotes... in short, if we wanted a completely consistent implementation, it seems like we'd need to manually implement parts of it for each of the meterp implementations anyway, so doing the pattern matching in one spot seemed much simpler overall.

## Verification

- [x] Start `msfconsole`
- [x] Get a meterpreter session on Linux
- [x] `irb`
- [x] `fs.file.expand_path('~')`
- [x] Verify this resolves to the user's home directory
- [x] `fs.file.expand_path('$HOME')`
- [x] Verify this resolves to the user's home directory
- [x] Verify that using environment variables or tilde work in the commands `cd`, `mkdir`, `rmdir`, `rm`, `mv`, `cp`, `chmod`, `ls`, `search`, `cat`, `checksum`, `download`, `upload`, `edit`
- [x] Verify that Windows meterpreter's use of path expansion (e.g. `%TEMP%`) still behaves

### CODE REVIEW

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb [hunk 1]
```diff
@@ -23,8 +23,14 @@ class Console::CommandDispatcher::Stdapi::Fs
 
   CHECKSUM_ALGORITHMS = %w{ md5 sha1 }
   private_constant :CHECKSUM_ALGORITHMS
-  PATH_EXPAND_REGEX = /\%(\w*)\%/
-  private_constant :PATH_EXPAND_REGEX
+
+  def path_expand_regex
```
Comment (smcintyre-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:27]: This method is replacing a constant which used to be private, so the new method should probably also be private.

**Review by smcintyre-r7 — COMMENTED** [review]
Just a note for testers, we should determine what this will do when an environment variable can't be expanded because it doesn't exist in the target environment. We'll need to check if it'll be left in the resulting string or removed altogether.

File: lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb [hunk 2]
```diff
@@ -123,28 +123,48 @@ def File.basename(*a)
...
+      env_regex = /\$(?:([A-Za-z0-9_]+)|\{([A-Za-z0-9_.]+)\})/
+      matches = path.to_enum(:scan, env_regex).map { Regexp.last_match }
+      env_vars = matches.map { |match| (match[1] || match[2]).to_s }.uniq
 
-    return client.unicode_filter_encode(response.get_tlv_value(TLV_TYPE_FILE_PATH))
+      # Retrieve them
+      env_vals = client.sys.config.getenvs(*env_vars)
+
+      # Now fill them in
+      path = path.gsub(env_regex) { |z| envvar = $1; envvar = $2 if envvar == nil; env_vals[envvar] }
```
Comment (gwillcox-r7) [inline lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb:165]:
```suggestion
      path = path.gsub(env_regex) { |_z| envvar = $1; envvar = $2 if envvar == nil; env_vals[envvar] }
```

Since you are never using the `z` variable here, this should be marked with a leading underscore.

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb [hunk 3]
```diff
@@ -23,8 +23,14 @@ class Console::CommandDispatcher::Stdapi::Fs
...
+    if client.platform == 'windows'
+      /\%(\w*)\%/
+    else
+      /\$(([A-Za-z0-9_]+)|\{([A-Za-z0-9_.]+)\})|^~/
+    end
```
Comment (gwillcox-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:32]: Again same issue as before here, not sure that we should be using a `else` statement here when there could be non-Unix platforms in the list.

File: lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb [hunk 4]
```diff
@@ -123,28 +123,48 @@ def File.basename(*a)
...
+      # For unix-based systems, do some of the work here
+      # First check for ~
+      path_components = path.split(separator)
+      if path_components.length > 0 && path_components[0] == '~'
+        path_components[0] = '$HOME'
+        path = path_components.join(separator)
+      end
+
+      # Now find the environment variables we'll need from the client
+      env_regex = /\$(?:([A-Za-z0-9_]+)|\{([A-Za-z0-9_.]+)\})/
```
Comment (gwillcox-r7) [inline lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb:157]:
```suggestion
      env_regex = /\$(?:([A-Za-z0-9_]+)|\{([A-Za-z0-9_]+)\})/
```
Correct me if I am wrong here but I don't think periods are allowed in environment variables?

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb (hunk 3 above)
Comment (gwillcox-r7) [reply lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:32]:
```suggestion
    else
      /\$(([A-Za-z0-9_]+)|\{([A-Za-z0-9_]+)\})|^~/
    end
```
Correct me if I am wrong but I don't think periods are allowed in environment variables and the way this is coded right now it would potentially expand out to other characters?

File: test/modules/post/test/file.rb [hunk 5]
```diff
@@ -185,6 +185,42 @@ def test_binary_files
...
+        s == result
+      end
+
+      it "mid-string tilde should not expand" do
+        s = '/home/~'
+        result = expand_path(s)
+        s == result
+      end
+
+      it "no env vars should not expand" do
```
Comment (gwillcox-r7) [inline test/modules/post/test/file.rb:208]: Naming of this test title could be improved, sounds very double negative here which is confusing.

```suggestion
      it "env vars with invalid naming should not expand" do
```

**Review by gwillcox-r7 — CHANGES_REQUESTED** [review]
Overall not bad though I did have a few concerns and some suggestions.

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb (hunk 3 above)
Comment (bcoles) [reply lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:32]: > I don't think periods are allowed in environment variables

`.` is not allowed in variable names; and Bash and Dash `export` builtin explicitly forbids it:

```
$ export asdf.zxcv=123.456
bash: export: `asdf.zxcv=123.456': not a valid identifier
```

```
$ export asdf.zxcv=123.456
dash: 1: export: asdf.zxcv: bad variable name
```

> and the way this is coded right now it would potentially expand out to other characters?

`.` is literal when using in `[]` regex character sets:

```
irb(main):001:0> "$asdf.zxcv=123.456".scan(/\$(([A-Za-z0-9_]+)|\{([A-Za-z0-9_.]+)\})|^~/).flatten
=> ["asdf", "asdf", nil]
irb(main):002:0> "${asdf.zxcv}=123.456".scan(/\$(([A-Za-z0-9_]+)|\{([A-Za-z0-9_.]+)\})|^~/).flatten
=> ["{asdf.zxcv}", nil, "asdf.zxcv"]
irb(main):003:0> "${asdf.zxcv=123.456}".scan(/\$(([A-Za-z0-9_]+)|\{([A-Za-z0-9_.]+)\})|^~/).flatten
=> []
irb(main):004:0> "aBc".scan(/[a-z.]+/).flatten
=> ["a", "c"]
irb(main):005:0> "aBc".scan(/([a-z.]+)/).flatten
=> ["a", "c"]
irb(main):006:0> 
```

Comment (gwillcox-r7) [reply lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:32]: Thanks for clarification @bcoles, appreciate the more detailed examples here :)

**Comment by gwillcox-r7** [comment]
```
meterpreter > cd $rvm_bin_path
[-] stdapi_fs_chdir: Operation failed: 2
meterpreter > shell
Process 7637 created.
Channel 2 created.
env
USER=gwillcox
HOME=/home/gwillcox
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/system/bin:/system/sbin:/system/xbin
LANG=C
PWD=/home/gwillcox

pwd
/home/gwillcox
cd /
pwd
/
cd ${HOME}/gwillcox
/bin/sh: 6: cd: can't cd to /home/gwillcox/gwillcox
cd ${HOME}/   
pwd
/home/gwillcox
```

```
meterpreter > irb
[*] Starting IRB shell...
[*] You are in the "client" (session) object

>> fs.file.expand_path('~')
=> "/home/gwillcox"
>> fs.file.expand_path('$HOME')
=> "/home/gwillcox"
>> 
```

Seems to be working fine, the errors were mostly cause for some reason the Meterpreter on Linux isn't picking up about 90% of my environment variables. First I thought this might be cause I'm not using bash, but even that has environment variables that aren't showing up here.

**Comment by gwillcox-r7** [comment]
Oh and to be clear I'm not landing this yet as the issue that is still open needs to be resolved first but once that is fixed this should be good to go and land.

**Comment by gwillcox-r7** [comment]
Oh and Windows is still working (forgot to test earlier):
```
meterpreter > sysinfo
Computer        : WIN-86UKQGF31O1
OS              : Windows 2016+ (10.0 Build 14393).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x64/windows
meterpreter > pwd
C:\Users\Administrator\Desktop
meterpreter > cd %TEMP%
meterpreter > pwd
C:\Users\ADMINI~1\AppData\Local\Temp\2
meterpreter > 
```

**Comment by gwillcox-r7** [comment]
One potential oddity found though:

```
meterpreter > shell
Process 8506 created.
Channel 5 created.
env
USER=gwillcox
HOME=/home/gwillcox
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/system/bin:/system/sbin:/system/xbin
LANG=C
PWD=/home/gwillcox
exit
meterpreter > cat gwillcox
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
....*CUT FOR BREVITY*....
meterpreter > cat $USER
[-] stdapi_fs_stat: Operation failed: 1
meterpreter > 
```

File: lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb [hunk 6]
```diff
@@ -123,28 +123,48 @@ def File.basename(*a)
...
-    request.add_tlv(TLV_TYPE_FILE_PATH, client.unicode_filter_decode( path ))
+      request.add_tlv(TLV_TYPE_FILE_PATH, client.unicode_filter_decode( path ))
 
-    response = client.send_request(request)
+      response = client.send_request(request)
+
+      return client.unicode_filter_encode(response.get_tlv_value(TLV_TYPE_FILE_PATH))
+    else
+      # For unix-based systems, do some of the work here
+      # First check for ~
```
[the remark this answers is not in the document]
Comment (smashery) [reply lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb]: Yeah, fair call. My read of the situation is:
- Native meterpreters support Android, iOS, BSD, Linux, OSX and Windows
- Interpreted Meterpreters (php, python, java) will call `guess_target_platform` (https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/base/sessions/meterpreter.rb#L429-L445) to decide what they are, which provide the options Windows, OSX, FreeBSD, BSD, and Linux.

I've added these ones; everything else will default to asking Meterpreter to do the work.

**Comment by smashery** [comment]
@gwillcox-r7 - Yeah, a bunch of the commands didn't use the `expand_path` functionality; I've extended it to these ones now:

- `search -d`
- `cat`
- `checksum`
- `download`
- `upload`
- `edit`

**Comment by gwillcox-r7** [comment]
Thanks @smashery, appreciate your hard work on this! I'll check this more in depth tomorrow morning as soon as I can 👍

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb (hunk 1 above)
Comment (gwillcox-r7) [reply lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb]: Fixed in 32bf9f60d126ddb11a925cc1ee75597810076b70

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb (hunk 3 above)
Comment (gwillcox-r7) [reply lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb]: Fixed in ebd927da44f89faf96a4a256f1f9627c91c698e0

File: lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb (hunk 4 above)
Comment (gwillcox-r7) [reply lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb]: Fixed in ebd927da44f89faf96a4a256f1f9627c91c698e0

File: test/modules/post/test/file.rb (hunk 5 above)
Comment (gwillcox-r7) [reply test/modules/post/test/file.rb]: Fixed in ebd927da44f89faf96a4a256f1f9627c91c698e0

**Review by gwillcox-r7 — APPROVED** [review]

File: lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb (hunk 6 above)
[the remark this answers is not in the document]
Comment (gwillcox-r7) [reply lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb]: Makes sense, will mark this as resolved.

**Comment by gwillcox-r7** [comment]
# Release Notes
Updates have been made to Linux Meterpreter libraries to support expanding environment variables in several different commands. This should provide users with a smoother experience when using environment variables in commands such as `cd`, `ls`, `download`, `upload`, `mkdir` and similar commands.
