### PR TITLE
Fixing multiple bugs in credential generation + refactoring

### LINKED ISSUE #19652: Various bugs when using the PASSWORD_SPRAY option
When fixing issue #19525, I noticed that the code used to generate credentials in the case of password spraying was a quick adaptation from the code that generates credentials without it (it seems that this option has been added "recently").

I spent some time playing around with the option and found a few bugs.

I will describe at least one using the below template, but it will be easier to demonstrate all the issues with actual code: I will attach a first draft PR that implements the failings cases through automated tests

## Steps to reproduce

How'd you do it?

1. use scanner/ssh/ssh_login
2. set PASSWORD_SPRAY 1
3. set BLANK_PASSWORDS 1
4. set USERNAME user
6. set rhosts file:./targets.txt
7. run

## Expected behavior

I expect the module to attempt the following credentials: `user:`

## Current behavior

Nothing is attempted

### Metasploit version

6.4.36-dev

## Additional Information

As written above, this is only one of various issues there are with the piece of code that generates credentials.
I will attach a PR with more explanations.

### PR DESCRIPTION
**Pull request by Mathiou04**
Fixes #19652

## Summary

In this PR, **I added various tests** on the CredentialCollection class, all of them currently failing and illustrating what I think are bugs.

Issues can be grouped in two categories:
- those linked to the `additional_publics` array
- those linked to the `password_spray` option

**I added some comments on each test explaining what it is currently yielding** (instead of the result I think should be expected - let me know if I misunderstood anything).

## Refactoring opportunity

You will see that there are many bugs linked to the `password_spray` option.

It seems that this branch of the code has been copy/pasted from the original branch (that didn't handle password spraying) and adapted.
There was not a lot of tests on this part of the code + the structure is difficult to maintain which probably explains those issues.

The original code branch (without spraying: `#each_unfiltered_username_first`) is also a bit complex with a lot of duplicated code.

I think there are some opportunities to simplify and clarify the code a lot with some refactoring.

### Non-regression tests

For this, I created 2 additional "non-regression" tests that activate all options and show how the credentials should be yielded.
There is one test with password spraying, one without.

I don't know if we want to keep them after the refactoring, but they will surely help.

Also, even if a part of the order in which the credentials are yielded should be "fixed", there are questions around others.
For example: 
- when do we want to yield the credentials generated by the `user_as_pass` option in case of `password_spraying`?
- when do we want to yield credentials generated by the "userpass" file?

## Additional question

As a side note, the `nil_passwords`, `blank_passwords` and `user_as_pass` options do not apply to the userpass file.
Is it expected behaviour or should we extend this behaviour to users yielded in the userpass file?

## Next steps

- [x] 1. I first plan to fix the easiest bugs (wrong var names for example) to make more tests pass
- [x] 2. Then I would tackle the cleaning of the password spraying code branch, so as to make all tests pass.
- [ ] 3. Then in a third commit, I would refactor both branches to simplify the code and reduce the probability to have such bugs in the future (also facilitating maintenance)

### CODE REVIEW

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 1]
```diff
@@ -311,6 +313,20 @@
...
+
+      context "when using password spraying" do
+        let(:password_spray) { true }
+
+        # REMOVE BEFORE COMMIT: yields nothings, fails because of bug in method
+        context "without password" do
+          let(:password) { nil }
+          specify  do
+            expect { |b| collection.each(&b) }.to yield_successive_args(
+              Metasploit::Framework::Credential.new(public: username, private: nil),
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:325]: Fails because the collection yields nothing in case of "password spraying".

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 2]
```diff
@@ -323,6 +339,253 @@
...
+      let(:password) { nil }
+      let(:additional_publics) { [ "test_public" ] }
+
+      context "when :user_as_pass is true" do
+        let(:user_as_pass) { true }
+
+        # REMOVE BEFORE COMMIT currently failing
+        specify  do
+          expect { |b| collection.each(&b) }.to yield_successive_args(
+            Metasploit::Framework::Credential.new(public: "test_public", private: "test_public"),
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:353]: Crashes because of an inexisting variable.

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 3]
```diff
@@ -323,6 +339,253 @@
...
+        end
+
+
+        context "when using password spraying" do
+          let(:password_spray) { true }
+
+          # REMOVE BEFORE COMMIT currently failing
+          specify  do
+            expect { |b| collection.each(&b) }.to yield_successive_args(
+              Metasploit::Framework::Credential.new(public: "test_public", private: "test_public"),
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:364]: Crashes because of an inexisting variable.

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 4]
```diff
@@ -323,6 +339,253 @@
...
+        end
+      end
+
+      context "when :nil_passwords is true" do
+        let(:nil_passwords) { true }
+
+        # REMOVE BEFORE COMMIT: this option is ignored currently for additional_publics
+        specify do
+          expect { |b| collection.each(&b) }.to yield_successive_args(
+            Metasploit::Framework::Credential.new(public: "test_public", private: nil),
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:376]: This case yields nothing: nil passwords are ignored in additional_public. (is there a reason for this?)

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 5]
```diff
@@ -323,6 +339,253 @@
...
+          context "with 2 additional_publics" do
+            let(:additional_publics) { [ "test_public1", "test_public2" ] }
+
+            # REMOVE BEFORE COMMIT: fails because no pwd spraying
+            specify  do
+              expect { |b| collection.each(&b) }.to yield_successive_args(
+                Metasploit::Framework::Credential.new(public: "test_public1", private: ""),
+                Metasploit::Framework::Credential.new(public: "test_public2", private: ""),
+                Metasploit::Framework::Credential.new(public: "test_public1", private: nil),
+                Metasploit::Framework::Credential.new(public: "test_public2", private: nil),
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:397]: This fails because the password spraying option does not work with additional_publics.
It generates the correct list of credentials, but not in the correct order.

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 6]
```diff
@@ -323,6 +339,253 @@
...
+
+          # REMOVE BEFORE COMMIT: this also yields the usernames as passwords for the additional_public
+          context "when given a password" do
+            let(:password) { "password" }
+
+            specify  do
+              expect { |b| collection.each(&b) }.to yield_successive_args(
+                Metasploit::Framework::Credential.new(public: "adsf", private: "password"),
+                Metasploit::Framework::Credential.new(public: "jkl", private: "password"),
+                Metasploit::Framework::Credential.new(public: "test_public", private: "password"),
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:420]: This fails because for some reason, in addition to those 3 credentials, it also uses the additional_publics ("test_public") as a password.

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 7]
```diff
@@ -323,6 +339,253 @@
...
+
+      context "when :blank_passwords is true" do
+        let(:blank_passwords) { true }
+
+        context "with password (but no username)" do
+          let(:password) { "pass" }
+
+          # REMOVE BEFORE COMMIT: this yields empty creds (no username, no pass)
+          specify  do
+            expect { |b| collection.each(&b) }.to yield_successive_args()
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:441]: This fails because in this case (no username defined!) it generated a set of empty credentials.

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 8]
```diff
@@ -323,6 +339,253 @@
...
+          end
+        end
+
+        # REMOVE BEFORE COMMIT: yields nothings, fails because of bug in method
+        context "with username (but no password)" do
+          let(:username) { "user" }
+
+          specify  do
+            expect { |b| collection.each(&b) }.to yield_successive_args(
+              Metasploit::Framework::Credential.new(public: username, private: ''),
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:451]: This fails because it generates no credential.
But in this case we have a username and are asking for a blank password so it should generate this. (this is the case I chose to describe in the issue)

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 9]
```diff
@@ -323,6 +339,253 @@
...
+          allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
+
+          filename
+        end
+
+        # REMOVE BEFORE COMMIT: yields nothing, same for blank passwords option
+        specify  do
+          expect { |b| collection.each(&b) }.to yield_successive_args(
+            Metasploit::Framework::Credential.new(public: "asdf", private: ''),
+            Metasploit::Framework::Credential.new(public: "jkl", private: ''),
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:470]: Fails also because it yields nothing. The given file is completely ignored.

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 10]
```diff
@@ -323,6 +339,240 @@
...
+
+            filename
+          end
+
+          # REMOVE BEFORE COMMIT: yields nothing, same for blank passwords option
+          specify  do
+            expect { |b| collection.each(&b) }.to yield_successive_args(
+              Metasploit::Framework::Credential.new(public: "asdf", private: ''),
+              Metasploit::Framework::Credential.new(public: "jkl", private: ''),
+            )
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:470]: Fails also because it yields nothing. The given file is completely ignored even if we would like to have the usernames with the blank passwords generated.

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 11]
```diff
@@ -323,6 +339,240 @@
...
+          Metasploit::Framework::Credential.new(public: "userfile", private: "passfile"),
+          Metasploit::Framework::Credential.new(public: "userfile", private: "test_private"),
+          Metasploit::Framework::Credential.new(public: "userpass_user", private: "userpass_pass"),
+          Metasploit::Framework::Credential.new(public: "test_public", private: nil), # missing this case
+          Metasploit::Framework::Credential.new(public: "test_public", private: "pass"),
+          Metasploit::Framework::Credential.new(public: "test_public", private: "test_public"),
+          Metasploit::Framework::Credential.new(public: "test_public", private: ""),
+          Metasploit::Framework::Credential.new(public: "test_public", private: "passfile"),
+          Metasploit::Framework::Credential.new(public: "test_public", private: "test_private")
+        )
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:530]: Currently failing because of the various bugs that make the other tests fail.

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 12]
```diff
@@ -323,6 +339,240 @@
...
+            Metasploit::Framework::Credential.new(public: "user", private: ""),
+            Metasploit::Framework::Credential.new(public: "userfile", private: ""),
+            Metasploit::Framework::Credential.new(public: "test_public", private: ""),
+            Metasploit::Framework::Credential.new(public: "user", private: "passfile"),
+            Metasploit::Framework::Credential.new(public: "userfile", private: "passfile"),
+            Metasploit::Framework::Credential.new(public: "test_public", private: "passfile"),
+            Metasploit::Framework::Credential.new(public: "userpass_user", private: "userpass_pass"),
+            Metasploit::Framework::Credential.new(public: "user", private: "test_private"),
+            Metasploit::Framework::Credential.new(public: "userfile", private: "test_private"),
+            Metasploit::Framework::Credential.new(public: "test_public", private: "test_private"),
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:571]: Currently failing because of the various bugs that make the other tests fail.

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 13]
```diff
@@ -323,6 +339,240 @@
...
+            expect { |b| collection.each(&b) }.to yield_successive_args(
+              Metasploit::Framework::Credential.new(public: "asdf", private: ''),
+              Metasploit::Framework::Credential.new(public: "jkl", private: ''),
+            )
+          end
+        end
+      end
+    end
+
+    context "when every possible option is used" do
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:476]: I tried to create some generic non-regression tests to demonstrate how the credentials should be yielded in case of various user/password data source (in fact in case of all them being active).

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 14]
```diff
@@ -311,6 +313,20 @@
           Metasploit::Framework::Credential.new(public: username, private: password),
         )
       end
+
+      context "when using password spraying" do
+        let(:password_spray) { true }
+
+        # REMOVE BEFORE COMMIT: yields nothings, fails because of bug in method
+        context "without password" do
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:321]: What would your thoughts be on not nesting the `context`s here. My thinking is it would make searching for failing tests much harder, as the sting would be broken across multiple lines whereas if it was a single context it would be much easier to find.

Here is where I usually check "best practices" when writing tests, just in case it's useful:
https://www.betterspecs.org/#contexts

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 15]
```diff
@@ -323,6 +339,240 @@
...
+          let(:username) { "user" }
+
+          specify  do
+            expect { |b| collection.each(&b) }.to yield_successive_args(
+              Metasploit::Framework::Credential.new(public: username, private: ''),
+            )
+          end
+        end
+
+        context "when given a user_file" do
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:456]: I'm assuming from the comment below you want to have `blank_passwords` set here.

**Review by cgranleese-r7 — COMMENTED** [review]
I know it's still in draft but I thought I'd give it a once over anyway. Looks great and thanks for following up on the last pull request 🚀

File: spec/lib/metasploit/framework/credential_collection_spec.rb (hunk 14 above)
Comment (Mathiou04) [reply spec/lib/metasploit/framework/credential_collection_spec.rb:321]: Ok with me 👍 
I struggled a bit to find a proper organization of the cases, given the already existing specs.

Do you want to merge only those two, or do you think I should also do the same for the other cases?
(meaning having only 1-level deep contexts)

File: spec/lib/metasploit/framework/credential_collection_spec.rb (hunk 15 above)
Comment (Mathiou04) [reply spec/lib/metasploit/framework/credential_collection_spec.rb:456]: It is actually set up on line 434, but with the nested contexts it is not easy to follow along...
I am wondering if it is better to duplicate setup code so as to have 1-level context where you can properly see all the setup, or be a bit more dry and nest.

Happy to follow what you feel is best.

Comment (cgranleese-r7) [reply spec/lib/metasploit/framework/credential_collection_spec.rb:456]: > better to duplicate setup code so as to have 1-level context where you can properly see all the setup

I would personally be in favor of that as it is much easier to see the configuration for each test.

File: spec/lib/metasploit/framework/credential_collection_spec.rb (hunk 14 above)
Comment (cgranleese-r7) [reply spec/lib/metasploit/framework/credential_collection_spec.rb:321]: > Do you want to merge only those two, or do you think I should also do the same for the other cases? (meaning having only 1-level deep contexts)

Yea, I personally think this would help make things clearer.

Comment (Mathiou04) [reply spec/lib/metasploit/framework/credential_collection_spec.rb:321]: Ok, fine with me. I'll change that!

Comment (Mathiou04) [reply spec/lib/metasploit/framework/credential_collection_spec.rb]: This was a bit painful to do but I agree, once it is done, it is much clearer to read and to debug 🎉

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 16]
```diff
@@ -68,7 +68,7 @@
       let(:pass_file) do
```
Comment (Mathiou04) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:68]: @cgranleese-r7 Not sure why the checks are suddenly failing, I simply changed the structure of the testing file, as we discussed 🤔

**Comment by cgranleese-r7** [comment]
@msjenkins-r7 retest this please

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 17]
```diff
@@ -68,7 +68,7 @@
...
         filename = "foo"
         stub_file = StringIO.new("asdf\njkl\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:71]:
```suggestion
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
```

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 18]
```diff
@@ -113,7 +113,7 @@
       let(:pass_file) do
         filename = "pass_file"
         stub_file = StringIO.new("asdf\njkl\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:116]:
```suggestion
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
```

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 19]
```diff
@@ -142,7 +142,7 @@
       let(:user_file) do
         filename = "user_file"
         stub_file = StringIO.new("user1\nuser2\nuser3\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:145]:
```suggestion
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
```

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 20]
```diff
@@ -157,23 +157,40 @@
...
-            Metasploit::Framework::Credential.new(public: "user2", private: "password2"),
-            Metasploit::Framework::Credential.new(public: "user3", private: "password2"),
-          )
-        end
+        filename
+      end
+      let(:user_file) do
+        filename = "user_file"
+        stub_file = StringIO.new("user1\nuser2\nuser3\n")
+        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:176]:
```suggestion
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
```

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 21]
```diff
@@ -203,7 +220,7 @@
       let(:user_file) do
         filename = "user_file"
         stub_file = StringIO.new("user1\nuser2\nuser3\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:223]:
```suggestion
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
```

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 22]
```diff
@@ -238,7 +255,7 @@
...
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:258]:
```suggestion
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
```

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 23]
```diff
@@ -276,7 +293,7 @@
       let(:pass_file) do
         filename = "pass_file"
         stub_file = StringIO.new("asdf\njkl\n")
-        allow(File).to receive(:open).with(filename, /^r/).and_return stub_file
+        allow(File).to receive(:open).with(filename, /^r/).and_yield stub_file
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:296]:
```suggestion
        allow(File).to receive(:open).with(filename, /^r/).and_return stub_file
```

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 24]
```diff
@@ -323,6 +355,253 @@
...
+
+    context "when using password spraying with blank_passwords and given a user_file" do
+      let(:password_spray) { true }
+      let(:blank_passwords) { true }
+      let(:username) { nil }
+      let(:password) { nil }
+      let(:user_file) do
+        filename = "foo"
+        stub_file = StringIO.new("asdf\njkl\n")
+        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:476]:
```suggestion
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
```

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 25]
```diff
@@ -323,6 +355,253 @@
...
+        filename = "user_file"
+        stub_file = StringIO.new("userfile")
+        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
+
+        filename
+      end
+      let(:pass_file) do
+        filename = "pass_file"
+        stub_file = StringIO.new("passfile\n")
+        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:505]:
```suggestion
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
```

File: spec/lib/metasploit/framework/credential_collection_spec.rb [hunk 26]
```diff
@@ -323,6 +355,253 @@
...
+    context "when using password spraying in combination with every other option" do
+      let(:password_spray) { true }
+      let(:nil_passwords) { true }
+      let(:blank_passwords) { true }
+      let(:username) { "user" }
+      let(:password) { "pass" }
+      let(:user_file) do
+        filename = "user_file"
+        stub_file = StringIO.new("userfile")
+        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
```
Comment (cgranleese-r7) [inline spec/lib/metasploit/framework/credential_collection_spec.rb:557]:
```suggestion
        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
```

**Review by cgranleese-r7 — COMMENTED** [review]
Hi @Mathiou04. Only getting back to this now as I was off for the holidays.

I took at look at these failing tests and it seem in the last commit some off the test expectations were changed. Mostly `and_returns` being changed to `and_yields`.

I have tested this locally and left suggestions that got everything passing for me.

I'll also add the diff, incase I missed any suggestions on the code or if you want to use it to patch in the changes 👍 

```diff
diff --git a/spec/lib/metasploit/framework/credential_collection_spec.rb b/spec/lib/metasploit/framework/credential_collection_spec.rb
index dcb1682796..55b4bc2b12 100644
--- a/spec/lib/metasploit/framework/credential_collection_spec.rb
+++ b/spec/lib/metasploit/framework/credential_collection_spec.rb
@@ -68,7 +68,7 @@ RSpec.describe Metasploit::Framework::CredentialCollection do
       let(:pass_file) do
         filename = "foo"
         stub_file = StringIO.new("asdf\njkl\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
 
         filename
       end
@@ -113,7 +113,7 @@ RSpec.describe Metasploit::Framework::CredentialCollection do
       let(:pass_file) do
         filename = "pass_file"
         stub_file = StringIO.new("asdf\njkl\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
 
         filename
       end
@@ -142,7 +142,7 @@ RSpec.describe Metasploit::Framework::CredentialCollection do
       let(:user_file) do
         filename = "user_file"
         stub_file = StringIO.new("user1\nuser2\nuser3\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
 
         filename
       end
@@ -173,7 +173,7 @@ RSpec.describe Metasploit::Framework::CredentialCollection do
       let(:user_file) do
         filename = "user_file"
         stub_file = StringIO.new("user1\nuser2\nuser3\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
 
         filename
       end
@@ -220,7 +220,7 @@ RSpec.describe Metasploit::Framework::CredentialCollection do
       let(:user_file) do
         filename = "user_file"
         stub_file = StringIO.new("user1\nuser2\nuser3\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
 
         filename
       end
@@ -255,7 +255,7 @@ RSpec.describe Metasploit::Framework::CredentialCollection do
       let(:user_file) do
         filename = "user_file"
         stub_file = StringIO.new("user1\nuser2\nuser3\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
 
         filename
       end
@@ -293,7 +293,7 @@ RSpec.describe Metasploit::Framework::CredentialCollection do
       let(:pass_file) do
         filename = "pass_file"
         stub_file = StringIO.new("asdf\njkl\n")
-        allow(File).to receive(:open).with(filename, /^r/).and_yield stub_file
+        allow(File).to receive(:open).with(filename, /^r/).and_return stub_file
 
         filename
       end
@@ -473,7 +473,7 @@ RSpec.describe Metasploit::Framework::CredentialCollection do
       let(:user_file) do
         filename = "foo"
         stub_file = StringIO.new("asdf\njkl\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
 
         filename
       end
@@ -502,7 +502,7 @@ RSpec.describe Metasploit::Framework::CredentialCollection do
       let(:pass_file) do
         filename = "pass_file"
         stub_file = StringIO.new("passfile\n")
-        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
 
         filename
       end
@@ -554,7 +554,7 @@ RSpec.describe Metasploit::Framework::CredentialCollection do
       let(:user_file) do
         filename = "user_file"
         stub_file = StringIO.new("userfile")
-        allow(File).to receive(:open).with(filename,/^r/).and_yield stub_file
+        allow(File).to receive(:open).with(filename,/^r/).and_return stub_file
 
         filename
       end

```

File: spec/lib/metasploit/framework/credential_collection_spec.rb (hunk 16 above)
Comment (cgranleese-r7) [reply spec/lib/metasploit/framework/credential_collection_spec.rb:68]: 👋 

Left some feedback below that should get those tests passing.

File: lib/metasploit/framework/credential_collection.rb [hunk 27]
```diff
@@ -280,52 +280,98 @@ def each_unfiltered_password_first
...
+          user_fd.each_line do |user_from_file|
+            user_from_file.chomp!
+            yield Metasploit::Framework::Credential.new(public: user_from_file, private: user_from_file, realm: realm, private_type: private_type(password))
+          end
+          user_fd.seek(0)
+        end
+
+        additional_publics.each do |add_public|
+          yield Metasploit::Framework::Credential.new(public: add_public, private: add_public, realm: realm, private_type: :password)
+        end
```
[the remark this answers is not in the document]
Comment (cgranleese-r7) [reply lib/metasploit/framework/credential_collection.rb:334]: Hmm, just my opinion but after having another look at this I think refactoring these sections may actually reduce readability. 

I find this code hard to read anyway due to all of the nuances required for each module option (not something that is you have introduced, just the nature of password_spray's requirements itself). 

I may be misunderstanding what you had in mind though, so feel free to let me know if that's the case.

**Comment by cgranleese-r7** [comment]
@Mathiou04 I went ahead and made some changes to get the tests passing and resolved any comments I believed had been covered with the changes. 

I also marked the PR over to `ready for review` as I believe apart from the refactoring you mentioned ([I left some feedback on  that](https://github.com/rapid7/metasploit-framework/pull/19653#discussion_r1932423444)), everything else is now covered 🤞. Feel free to let me know if that is not the case.

File: lib/metasploit/framework/credential_collection.rb (hunk 27 above)
[the remark this answers is not in the document]
Comment (Mathiou04) [reply lib/metasploit/framework/credential_collection.rb:334]: I don't have a clear direction in mind, I just see potential because of the duplication of this big block:
```
	if username.present?
          	yield Metasploit::Framework::Credential.new(public: username, private: username, realm: realm, private_type: :password)
        end

        if user_fd
          user_fd.each_line do |user_from_file|
            user_from_file.chomp!
            yield Metasploit::Framework::Credential.new(public: user_from_file, private: user_from_file, realm: realm, private_type: private_type(password))
          end
          user_fd.seek(0)
        end

        additional_publics.each do |add_public|
          yield Metasploit::Framework::Credential.new(public: add_public, private: add_public, realm: realm, private_type: :password)
        end
```

It bothers me as if we have one slight modification of behaviour, we will have to modify the 3 (or 4, or 5?) of them.

A better target is not clear for me, but I had an idea that I didn't investigate yet: it would be to introduce two new classes, that would essentialy be iterator: one to iterate on usernames, and another one on passwords.

The code would then simply look something like this:
```
usernames_iterator.each do |username|
  passwords_iterator.each do |password|
    yield Metasploit::Framework::Credential.new...
  end
end
```

And the password spraying branch would simply look like this:
```
passwords_iterator.each do |username|
  usernames_iterator.each do |password|
    yield Metasploit::Framework::Credential.new...
  end
end
```

The main problem would be to handle the `user_as_pass` parameter in a clean way.
(anyway, maybe we are good enough for now?)

**Comment by Mathiou04** [comment]
> Hi @Mathiou04. Only getting back to this now as I was off for the holidays.
> 
> I took at look at these failing tests and it seem in the last commit some off the test expectations were changed. Mostly `and_returns` being changed to `and_yields`.
> 
> I have tested this locally and left suggestions that got everything passing for me.

Thanks for looking into this, sorry I didn't came back earlier.
It's weird, because I thought the tests were passing locally and those changes in expectation seemed to make sense given the changes I made to the code

In fact I just realized I had one more commit, that made the tests pass, and I didn't push it...
I was trying to extract a few methods to DRY the code a bit

I introduced a method `each_username` to groupe this repeated code and use in `each_unfiltered_password_first`:
```
  def each_username
      if username.present?
        yield username
      end

      if user_file.present?
        File.open(user_file, 'r:binary') do |user_fd|
          user_fd.each_line do |user_from_file|
            user_from_file.chomp!
            yield user_from_file
          end
          user_fd.seek(0)
        end
      end

      additional_publics.each do |add_public|
        yield add_public
      end
    end
 ```
 
 And a method `each_password(user)` to groupe the code in 'each_unfiltered_username_first`:
 
 ```
 def each_password(user)
      if nil_passwords
        yield [nil, :password]
      end

      if password.present?
        yield [password, private_type(password)]
      end

      if user_as_pass
        yield [user, :password]
      end

      if blank_passwords
        yield ["", :password]
      end

      if pass_file
        File.open(pass_file, 'r:binary') do |pass_fd|
          pass_fd.each_line do |pass_from_file|
            pass_from_file.chomp!
            yield [pass_from_file, private_type(pass_from_file)]
          end
          pass_fd.seek(0)
        end
      end

      additional_privates.each do |add_private|
        yield [add_private, private_type(add_private)]
      end
    end
```

Is it ok if I try to rebase/merge with your work, to show you?
We may remove it afterward if you don't think it adds value.

**Comment by cgranleese-r7** [comment]
> Is it ok if I try to rebase/merge with your work, to show you? We may remove it afterward if you don't think it adds value.

Absolutely, that would be great!

**Comment by Mathiou04** [comment]
@cgranleese-r7 Here is he final version I worked on, sorry for the delay!
So I pushed my last commit and re-reverted the changes in the tests 😓 
They should all pass now 🤞 

I had other ideas for further refactoring and DRYing (mainly creating custom Iterators class for username and password), but I am not sure it is worth it and am struggling to ind the time to work on it.
So let me know what you think of this version!

File: lib/metasploit/framework/credential_collection.rb [hunk 28]
```diff
@@ -257,29 +257,29 @@ def add_public(public_str='')
...
 
     alias each each_filtered
 
+    def each_unfiltered(&block)
+      prepended_creds.each { |c| yield c }
+
+      if anonymous_login
+        yield Metasploit::Framework::Credential.new(public: '', private: '', realm: realm, private_type: :password)
+      end
+
```
Comment (cgranleese-r7) [inline lib/metasploit/framework/credential_collection.rb:275]: I believe this change is required to align with some recent changes made as part of this PR: https://github.com/rapid7/metasploit-framework/pull/19843

Specifically this code:
```suggestion

      if ignore_private
        if ignore_public
          yield Metasploit::Framework::Credential.new(public: nil, private: nil, realm: realm)
        else
          yield Metasploit::Framework::Credential.new(public: username, private: nil, realm: realm)
        end
      end
      
```

**Review by cgranleese-r7 — COMMENTED** [review]
I'll handle these changes as I know you mentioned you don't have the cycles 👍

**Comment by Mathiou04** [comment]
> I'll handle these changes as I know you mentioned you don't have the cycles 👍

Thx for that.
Just one question though, about those changes: why does `ignore_private` assumes there is only one username in the list?

I am not sure I understand all the implications, but those new parameters feels kind of specific to a certain usage (and don't interact well with other params, like password spraying for example).

Wouldn't it be cleaner for the CredentialCollection to have an interface with some kind of enum: `ignore: [public, private, both]` ?
This way we could have something more generic that can still ignore either usernames, passwords or both and this would be properly integrated with the rest of the code (and the behaviour would be less surprising).

**Comment by cdelafuente-r7** [comment]
Thanks! It makes sense. One more detail, the `ignore_private` and `ignore_public` parameters cannot be set by the user. It is the module's responsibility to set them accordingly.

I'll have a look at your commit, thank you!

**Comment by Mathiou04** [comment]
> Thanks! It makes sense. One more detail, the `ignore_private` and `ignore_public` parameters cannot be set by the user. It is the module's responsibility to set them accordingly.

Yes sorry, I meant "user" in the sense of "client code using the class" 😅 

> I'll have a look at your commit, thank you!
So [here](https://github.com/rapid7/metasploit-framework/pull/19653/commits/b08a5f6ce3b6ad360f15ca1bb9b758c6a5b06f5b) it is.

I first did a [simple merge commit](https://github.com/rapid7/metasploit-framework/pull/19653/commits/66ce0203ccc4c65768030b90cd606a31c72d1388) with the straightforward solution given the current code. 

Then as I wrote before, I tried to see if I could make the change more generic. But after looking at a few options I realized that we might be looking at it the wrong way.

It seemed to me that the responsibility of handling those options should not be in the CredentialCollection: it feels weird to pass collections of usernames, passwords, prepend from DB etc, but then bypass everything with a single option.

So I had the impression that we would be better off with the client library making better use of the different available options to actually retrieve what it wants and not pass wasted parameters.

Therefore I introduced a new method in ldap_login that depending on the configuration instantiate a `PrivateCredentialCollection` (if it doesn't want a username) or a `CredentialCollection` with very few options (just what is needed).

There weren't any specs on the `ldap_login` class, and I wasn't sure how to introduce some or actually test it so I am not 100% sure the current implementation is actually what we expect.

I also renamed/changed the parameters to have one reflecting the SCHANNEL case, that necessitates a fully void login attempt, and the KERBEROS case that simply need a void password.
The conditions felt more natural that way (`ignore_public` set to true was useless if `ignore_password` wasn't true as well).

Another option that I explored what to replace the `ignore` flags with a new `nil_usernames` flag and play with that.
We would still have to instantiate different `CredentialCollections` in the ldap_login code though.
I went with the `PrivateCredentialCollection` instead, even if I am not 100% sure it works. It seemed to be done for that from what I read.

Finally, I think there was a bug in the KERBEROS condition, but I am not 100% sure.
The change in the conditions for determining the variable is not 100% equivalent to what we had initially, so let me know if I am wrong.

Sorry for the long comment, happy to hear your thoughts on this.

**Review by smcintyre-r7 — APPROVED** [review]
I went through this with a test module I have that shows what's being bruteforced. I tried a bunch of different combinations and found no issues related to this work. The one thing I found is that the `AuthBrute` mixin doesn't pass along the `ANONYMOUS_LOGIN` datastore option so it's not hooked up correctly. I'll fix that myself since it's unrelated to this which is handling the option correctly.

I also tested the `jupyter_login` module which is a bit of an edge case because that service has a password but no usernames. That also still works as intended.

**Comment by smcintyre-r7** [comment]
I spoke too soon, I went back to test that the fix introduced in #19843 was still in place and I started to notice some issues. Right now it's not clear why the ignore options were removed and if we're using `nil_password` now instead. I'm hoping to get things rebased and pushed up but the latest commit is crashing when I run the `auxiliary/scanner/ldap/ldap_login` module.

```
msf6 auxiliary(scanner/ldap/ldap_login) > git show -s
[*] exec: git show -s

commit b08a5f6ce3b6ad360f15ca1bb9b758c6a5b06f5b (HEAD -> pr/19653, Mathiou04/fix_bugs_in_credentials_collection_enumerator_and_refacto)
Author: Mathieu <mathieu.sanchez@acasi.io>
Date:   Wed Feb 12 17:47:18 2025 +0100

    Change how ldap_login generate its specific credentials for SCHANNEL && KERBEROS auth
msf6 auxiliary(scanner/ldap/ldap_login) > run
[-] Auxiliary failed: NoMethodError undefined method `nil_password=' for an instance of Metasploit::Framework::CredentialCollection
[-] Call stack:
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:59:in `public_send'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:59:in `block in initialize'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:58:in `each'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:58:in `initialize'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:224:in `initialize'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/scanner/ldap/ldap_login.rb:202:in `new'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/scanner/ldap/ldap_login.rb:202:in `build_specific_credential_collection'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/scanner/ldap/ldap_login.rb:92:in `run_host'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/auxiliary/scanner.rb:128:in `block (2 levels) in run'
[-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/thread_manager.rb:105:in `block in spawn'
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/ldap/ldap_login) > 
```

I'm going to try and rebase this myself and see if I can't get it into a clean state where we can merge it. Thanks for your patience!

**Comment by Mathiou04** [comment]
> I spoke too soon, I went back to test that the fix introduced in #19843 was still in place and I started to notice some issues. Right now it's not clear why the ignore options were removed and if we're using `nil_password` now instead. I'm hoping to get things rebased and pushed up but the latest commit is crashing when I run the `auxiliary/scanner/ldap/ldap_login` module.
> 
> ```
> msf6 auxiliary(scanner/ldap/ldap_login) > git show -s
> [*] exec: git show -s
> 
> commit b08a5f6ce3b6ad360f15ca1bb9b758c6a5b06f5b (HEAD -> pr/19653, Mathiou04/fix_bugs_in_credentials_collection_enumerator_and_refacto)
> Author: Mathieu <mathieu.sanchez@acasi.io>
> Date:   Wed Feb 12 17:47:18 2025 +0100
> 
>     Change how ldap_login generate its specific credentials for SCHANNEL && KERBEROS auth
> msf6 auxiliary(scanner/ldap/ldap_login) > run
> [-] Auxiliary failed: NoMethodError undefined method `nil_password=' for an instance of Metasploit::Framework::CredentialCollection
> [-] Call stack:
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:59:in `public_send'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:59:in `block in initialize'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:58:in `each'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:58:in `initialize'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:224:in `initialize'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/scanner/ldap/ldap_login.rb:202:in `new'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/scanner/ldap/ldap_login.rb:202:in `build_specific_credential_collection'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/scanner/ldap/ldap_login.rb:92:in `run_host'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/auxiliary/scanner.rb:128:in `block (2 levels) in run'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/thread_manager.rb:105:in `block in spawn'
> [*] Auxiliary module execution completed
> msf6 auxiliary(scanner/ldap/ldap_login) > 
> ```
> 
> I'm going to try and rebase this myself and see if I can't get it into a clean state where we can merge it. Thanks for your patience!

Hey @smcintyre-r7! Thx for taking the time.
Actually this is just a typo using `nil_password` instead of the plural `nil_passwords`!
I just pushed the fix.

**Comment by Mathiou04** [comment]
> I spoke too soon, I went back to test that the fix introduced in #19843 was still in place and I started to notice some issues. Right now it's not clear why the ignore options were removed and if we're using `nil_password` now instead. I'm hoping to get things rebased and pushed up but the latest commit is crashing when I run the `auxiliary/scanner/ldap/ldap_login` module.
> 
> ```
> msf6 auxiliary(scanner/ldap/ldap_login) > git show -s
> [*] exec: git show -s
> 
> commit b08a5f6ce3b6ad360f15ca1bb9b758c6a5b06f5b (HEAD -> pr/19653, Mathiou04/fix_bugs_in_credentials_collection_enumerator_and_refacto)
> Author: Mathieu <mathieu.sanchez@acasi.io>
> Date:   Wed Feb 12 17:47:18 2025 +0100
> 
>     Change how ldap_login generate its specific credentials for SCHANNEL && KERBEROS auth
> msf6 auxiliary(scanner/ldap/ldap_login) > run
> [-] Auxiliary failed: NoMethodError undefined method `nil_password=' for an instance of Metasploit::Framework::CredentialCollection
> [-] Call stack:
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:59:in `public_send'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:59:in `block in initialize'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:58:in `each'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:58:in `initialize'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/credential_collection.rb:224:in `initialize'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/scanner/ldap/ldap_login.rb:202:in `new'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/scanner/ldap/ldap_login.rb:202:in `build_specific_credential_collection'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/scanner/ldap/ldap_login.rb:92:in `run_host'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/auxiliary/scanner.rb:128:in `block (2 levels) in run'
> [-]   /home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/thread_manager.rb:105:in `block in spawn'
> [*] Auxiliary module execution completed
> msf6 auxiliary(scanner/ldap/ldap_login) > 
> ```
> 
> I'm going to try and rebase this myself and see if I can't get it into a clean state where we can merge it. Thanks for your patience!

To answer your question about why the `ignore` options were removed, I'll try to sum up my reasoning.

These options are allowing the caller to bypass some login/passwords from the collection. It directly "hooks" into the Collection and bypass some of the code paths.
So it means that: we instantiate a collection with some usernames/passwords but add an option so we can ignore what was just added.

It felt like a misuse of the Collection interface: it seemed better to simply properly feed the Collection object with what we actually want.
If we don't want to iterate on password, then simply instantiate a collection without the passwords.

That is why I tried to remove those `ignore` flags, and have the ldap module use the already existing interface properly to get the desired result.
It makes the code simpler IMO, and leave the logic of username/password selection well segregated to the ldap module, instead of putting the burden on the already complex Collection class.

**Comment by cgranleese-r7** [comment]
## Release Notes
Fixes multiple bugs in credential generation and refactors the code to improve readability.
