### PR TITLE
Replaces erroneous calls to get_service

### LINKED ISSUE #11978: Got error while exploit BadBlue 2.72.
**I'm getting this error while exploiting BadBlue service on windows 10 which is install in vbox.**
I updated my metasploit to the latest version also but still it's not working.
I scanned the victim machine using nmap and got BadBlue service running on port 8888.
I used following steps to exploit the BadBlue service.

msf5 > use exploit/windows/http/badblue_passthru
msf5 exploit(windows/http/badblue_passthru) > set rhost 192.168.31.190
rhost => 192.168.31.190
msf5 exploit(windows/http/badblue_passthru) > set lhost 192.168.31.126
lhost => 192.168.31.126
msf5 exploit(windows/http/badblue_passthru) > exploit

[-] Exploit failed: NoMethodError undefined method `get_service' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x0000000007a15020>
Did you mean?  get_msf_version
[*] Exploit completed, but no session was created.

In Above Case 
My IP: 192.168.31.126
Victim IP : 192.168.31.190

**## Expected behavior**

It should open session.

**## Current behavior (Last Error in Log File)**

[e(0)] core: windows/meterpreter/reverse_tcp: iteration 1: Broken encoder x86/xor_dynamic: Bad character found in stub for the Dynamic key XOR Encoder encoder.
 [e(0)] core: windows/meterpreter/reverse_tcp: iteration 1: Broken encoder x86/fnstenv_mov: No valid set instruction could be created!
 [i(0)] core: windows/meterpreter/reverse_tcp: iteration 1: Successfully encoded with encoder x86/call4_dword_xor (size is 392)
 [e(0)] core: Exploit failed (windows/http/badblue_passthru): NoMethodError undefined method `get_service' for #<Metasploit::Framework::DataService::RemoteHTTPDataServi$
Did you mean?  get_msf_version

**### Metasploit version**

metasploit v5.0.30-dev-

**### I installed Metasploit with:**
- [1 ] Kali package via apt

**### OS**

What OS are you running Metasploit on?

Kali GNU/Linux Rolling
Release:	2019.2

### PR DESCRIPTION
**Pull request by agalway-r7**
Fixes #11978 

`get_service` is a deprecated call to the DB to retrieve a single service from the DB. This PR replaces all remaining calls to `get_service` with calls to `services`.

`services` differs in that it returns a **list** of services. However, all calls to `get_service` require a `port` field that `services` also accepts. This restricts the maximum size of the `services` results to a list with a maximum size of one, as more than one service can't be assigned to the same port. 

## Verification

List the steps needed to make sure this thing works

- [x] `msfdb start`
- [x] Start `msfconsole`
- [x] use exploit/multi/http/tomcat_mgr_deploy
- [x] set RHOSTS <ip-address of metasploitable2 VM>
- [x] set RPORT 8180
- [x] set HttpPassword tomcat
- [x] set HttpUsername tomcat
- [x] set target 3 (Linux x86)
- [x] run
- [x] ensure the below output is displayed  
```
[-] Exploit aborted due to failure: unknown: Upload failed on /manager/deploy?path=/[RANDOM] [No Response]
```

### CODE REVIEW

**Comment by gwillcox-r7** [comment]
Steps are missing the part where you have to change the payload as by default the payload is set to a JAVA payload and I had to run `set payload linux/x86/meterpreter/bind_tcp`. Even with this and your changes I was still getting a warning about having to run `set FingerprintCheck false`, however after doing all this I can confirm I see the new message:

```
msf6 exploit(multi/http/tomcat_mgr_deploy) > set payload linux/x86/meterpreter/bind_tcp
payload => linux/x86/meterpreter/bind_tcp
msf6 exploit(multi/http/tomcat_mgr_deploy) > run

[-] Exploit aborted due to failure: unreachable: The target server did not respond to fingerprinting, use 'set FingerprintCheck false' to disable this check.
[*] Exploit completed, but no session was created.
msf6 exploit(multi/http/tomcat_mgr_deploy) > show options

Module options (exploit/multi/http/tomcat_mgr_deploy):

   Name          Current Setting  Required  Description
   ----          ---------------  --------  -----------
   HttpPassword  tomcat           no        The password for the specified username
   HttpUsername  tomcat           no        The username to authenticate as
   PATH          /manager         yes       The URI path of the manager app (/deploy and /undeploy will be used)
   Proxies                        no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS        172.1.22.44    yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT         8180             yes       The target port (TCP)
   SSL           false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                          no        HTTP server virtual host


Payload options (linux/x86/meterpreter/bind_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LPORT  4444             yes       The listen port
   RHOST  172.1.22.44    no        The target address


Exploit target:

   Id  Name
   --  ----
   3   Linux x86


msf6 exploit(multi/http/tomcat_mgr_deploy) > set FingerprintCheck false
FingerprintCheck => false
msf6 exploit(multi/http/tomcat_mgr_deploy) > run

[*] Using manually select target "Linux x86"
[*] Uploading 1583 bytes as FFVFvUhiauc3EtG5S2k1G9rn.war ...
[-] Exploit aborted due to failure: unknown: Upload failed on /manager/deploy?path=/FFVFvUhiauc3EtG5S2k1G9rn [No Response]
[*] Exploit completed, but no session was created.
msf6 exploit(multi/http/tomcat_mgr_deploy) > 
```

File: lib/msf/core/web_services/servlet/service_servlet.rb [hunk 1]
```diff
@@ -10,7 +10,6 @@ def self.api_path_with_id
 
   def self.registered(app)
     app.get  ServiceServlet.api_path, &get_services
```
[the remark this answers is not in the document]
Comment (gwillcox-r7) [reply lib/msf/core/web_services/servlet/service_servlet.rb:12]: Also would the following definition of `self.get_services` still be needed? Thought we were depreciating that code. If I'm confused then my apologies.

File: lib/msf/core/exploit.rb [hunk 2]
```diff
@@ -1562,9 +1562,6 @@ def report_failure
 
     if self.datastore['RPORT'] and self.options['RPORT']
       info[:port] = self.datastore['RPORT']
-      if self.class.ancestors.include?(Msf::Exploit::Remote::Tcp)
-        info[:proto] = 'tcp'
-      end
```
Comment (gwillcox-r7) [inline lib/msf/core/exploit.rb:1567]: I'm confused why this change is being made here, as it doesn't seem to have any relation to the code you have changed. Am I missing something here? Open to suggestions, just a little confused right now as to why this is being altered.

**Review by gwillcox-r7 — COMMENTED** [review]
Most of this looks good, though I did have a few comments about some things that didn't quite make sense to me, perhaps cause I'm not familiar with these libraries. Otherwise this seems to work as expected and the large majority of the code edits look good to me.

**Comment by adamgalway-r7** [comment]
> Testing steps are missing the part where you have to change the payload as by default the payload is set to a JAVA payload and I had to run `set payload linux/x86/meterpreter/bind_tcp`. Even with this and your changes I was still getting a warning about having to run `set FingerprintCheck false`, however after doing all this I can confirm I see the new message:
> 
> ```
> msf6 exploit(multi/http/tomcat_mgr_deploy) > set payload linux/x86/meterpreter/bind_tcp
> payload => linux/x86/meterpreter/bind_tcp
> msf6 exploit(multi/http/tomcat_mgr_deploy) > run
> 
> [-] Exploit aborted due to failure: unreachable: The target server did not respond to fingerprinting, use 'set FingerprintCheck false' to disable this check.
> [*] Exploit completed, but no session was created.
> msf6 exploit(multi/http/tomcat_mgr_deploy) > show options
> 
> Module options (exploit/multi/http/tomcat_mgr_deploy):
> 
>    Name          Current Setting  Required  Description
>    ----          ---------------  --------  -----------
>    HttpPassword  tomcat           no        The password for the specified username
>    HttpUsername  tomcat           no        The username to authenticate as
>    PATH          /manager         yes       The URI path of the manager app (/deploy and /undeploy will be used)
>    Proxies                        no        A proxy chain of format type:host:port[,type:host:port][...]
>    RHOSTS        172.1.22.44    yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
>    RPORT         8180             yes       The target port (TCP)
>    SSL           false            no        Negotiate SSL/TLS for outgoing connections
>    VHOST                          no        HTTP server virtual host
> 
> 
> Payload options (linux/x86/meterpreter/bind_tcp):
> 
>    Name   Current Setting  Required  Description
>    ----   ---------------  --------  -----------
>    LPORT  4444             yes       The listen port
>    RHOST  172.1.22.44    no        The target address
> 
> 
> Exploit target:
> 
>    Id  Name
>    --  ----
>    3   Linux x86
> 
> 
> msf6 exploit(multi/http/tomcat_mgr_deploy) > set FingerprintCheck false
> FingerprintCheck => false
> msf6 exploit(multi/http/tomcat_mgr_deploy) > run
> 
> [*] Using manually select target "Linux x86"
> [*] Uploading 1583 bytes as FFVFvUhiauc3EtG5S2k1G9rn.war ...
> [-] Exploit aborted due to failure: unknown: Upload failed on /manager/deploy?path=/FFVFvUhiauc3EtG5S2k1G9rn [No Response]
> [*] Exploit completed, but no session was created.
> msf6 exploit(multi/http/tomcat_mgr_deploy) > 
> ```

Sorry should have mentioned, the `set FingerprintCheck false` prompt is expected functionality for the module when following the verification steps. It just means the fingerprinting is working as expected, and by extension the fix is working, because the module wasn't able to find a matching service.

File: lib/msf/core/web_services/servlet/service_servlet.rb (hunk 1 above)
[the remark this answers is not in the document]
Comment (adamgalway-r7) [reply lib/msf/core/web_services/servlet/service_servlet.rb:12]: So this is down to a confusing naming convention. Methods in this file are named with the pattern `[HTTP VERB]_[ENDPOINT]`. So `get_services` actually means, "the code that should be run when the `GET` verb is used on the `services` endpoint".

I'm removing this endpoint because the `services` method shouldn't take IDs in the URL, not because it's what get's hit when `framework.db.get_services` is called by a module.

File: lib/msf/core/exploit.rb (hunk 2 above)
Comment (adamgalway-r7) [reply lib/msf/core/exploit.rb:1567]: No it's a good shout, it definitely looks out of place.

`get_services` took four args: 

- `workspace`

- `port`

- `host`

- `protocol`

The above code is used to generate a value for `protocol`.

`services` only takes:
- `workspace`

- `port`

- `host`

Since `protocol` is no longer needed, I figured it would make sense to pull out the code generating the arg. This only happens once in my changes because (as far as I can tell), the arg actually only gets generated once.

Comment (adamgalway-r7) [reply lib/msf/core/exploit.rb:1567]: Actually sorry, I have removed another case of the `protocol` arg being generated. lib/msf/core/db_manager/exploit_attempt.rb line 41

File: lib/msf/core/web_services/servlet/service_servlet.rb (hunk 1 above)
[the remark this answers is not in the document]
Comment (adamgalway-r7) [reply lib/msf/core/web_services/servlet/service_servlet.rb:12]: This did make be go back, double check, and remove some more unneeded code though, so it's still a good shout 👍

[the remark this answers is not in the document]
Comment (gwillcox-r7) [reply lib/msf/core/web_services/servlet/service_servlet.rb:12]: @adamgalway-r7 Ah I thought we were removing the `get_services` method in its entirety so thats why I was confused and its also why I mentioned `self.get_services` and questioned why this wasn't being removed. This makes more sense now.

File: lib/msf/core/exploit.rb (hunk 2 above)
Comment (gwillcox-r7) [reply lib/msf/core/exploit.rb:1567]: @adamgalway-r7 Don't see the `lib/msf/core/db_manager/exploit_attempt.rb` line 41 edit in the latest commits, but feel free to add it in.

Comment (gwillcox-r7) [reply lib/msf/core/exploit.rb:1567]: Nm this edit has already been made, got confused there for a second.

**Comment by gwillcox-r7** [comment]
Last commit removed an extra call that wasn't needed since it would just return the SERVICE_API_PATH value that was passed as an argument to that call. 

Code looks good, will land this now.

**Comment by gwillcox-r7** [comment]
# Release Notes
This update replaces all calls to the depreciated `get_service` function with calls to the more modern function known as `services`. This solves some known issues related to existing `get_service` calls that affected modules `badblue_passthru` and `tomcat_mgr_upload` when connected to a remote database.

**Comment by jmartin-r7** [comment]
When this picked up to be restored, see comments on #14156 about `:proto` still being a valid filtering `opt` that should be passed to `services` correctly filter encase a host has existed for some time and the protocol on the port had changed.

**Comment by gwillcox-r7** [comment]
@jmartin-r7 Made some grammar improvements to your previous comment for readability
