### PR TITLE
Fix nil http_method in php_include

### LINKED ISSUE #6115: Bug fix in php_include (modules/exploits/unix/webapp/php_include.rb)
Php_include will not send any request when it uses PHPRFIDB because of no default value set in "http_method".

[snipped: modules/exploits/unix/webapp/php_include.rb]

100     # PHPURI overrides the PHPRFIDB list
101     if (datastore['PHPURI'] and not datastore['PHPURI'].empty? and (datastore['POSTDATA'].nil? or datastore['POSTDATA'].empty?) )
102       uris << datastore['PHPURI'].strip.gsub('XXpathXX', Rex::Text.to_hex(php_include_url, "%"))
103       http_method = "GET"
104     elsif (datastore['POSTDATA'] and not datastore['POSTDATA'].empty?)
105       uris << datastore['PHPURI']
106       postdata = datastore['POSTDATA'].strip.gsub('XXpathXX', Rex::Text.to_hex(php_include_url, "%"))
107       http_method = "POST"
108     else
109       print_status("Loading RFI URLs from the database...")
110       ::File.open(datastore['PHPRFIDB'], "rb") do |fd|
111         fd.read(fd.stat.size).split(/\n/).each do |line|
112           line.strip!
113           next if line.empty?
114           next if line =~ /^#/
115           next if line !~ /^\//
116 
117           uris << line.gsub('XXpathXX',
118             Rex::Text.to_hex(php_include_url.sub(/\?$/, '') + '?', "%") # ? append is required
119           )
120         end
121       end
122       uris.uniq!
123       print_status("Loaded #{uris.length} URLs")
124     end

It causes calling handler with http_method as nil.

136       begin
137         if http_method == "GET"
138           response = send_request_raw( {
139             'global' => true,
140             'uri'  => tpath+uri,
141             'headers' => datastore_headers,
142           }, timeout)
143         elsif http_method == "POST"
144           response = send_request_raw(
145             {
146               'global'  => true,
147               'uri' => tpath+uri,
148               'method'  => http_method,
149               'data'  => postdata,
150               'headers' => datastore_headers.merge({
151                 'Content-Type'   => 'application/x-www-form-urlencoded',
152                 'Content-Length' => postdata.length
153               })
154             }, timeout)
155         end
156         handler

It should be fixed by following:

$ diff php_include.rb*
110d109
<                       http_method = "GET"

-- Tinydile

### PR DESCRIPTION
**Pull request by wvu**
Fixes #6115.

### CODE REVIEW

File: modules/exploits/unix/webapp/php_include.rb [hunk 1]
```diff
@@ -121,6 +121,7 @@ def php_exploit
       end
       uris.uniq!
       print_status("Loaded #{uris.length} URLs")
+      http_method = "GET"
```
Comment (wvu-r7) [inline modules/exploits/unix/webapp/php_include.rb]: Should be a symbol. Meh.

**Comment by wvu-r7** [comment]
Thanks, @kgray-r7!!
