### PR TITLE
Fix cache invalidation bug in tab completion

### LINKED ISSUE #8483: broken payload selection system
Little issue this morning while trying the new "is_known_pipename"

It seems that i've (it) broke the payload selection system

image

image

As you can see proposed payloads are wrong (ms08-067 is obviously for windows  and same problem is_known_pipename )

I've try to update the framework, reboot the vm nothing seems to get rid of this.

Kali 2.0 with msf fully updated i guess.

### PR DESCRIPTION
**Pull request by wvu**
We use `active_module` instead of `cmd_use` to invalidate `@cache_payloads`, since the ivar is no longer shared between `cmd_set` and `cmd_use`.

Fixes #8483. See #7655.

### CODE REVIEW

File: lib/msf/ui/console/command_dispatcher/core.rb [hunk 1]
```diff
@@ -2288,7 +2286,11 @@ def option_values_dispatch(o, str, words)
   # Provide valid payload options for the current exploit
   #
   def option_values_payloads
-    return @cache_payloads if @cache_payloads
+    if @cache_payloads && active_module == @previous_module
+      return @cache_payloads
+    else
```
Comment (acammack-r7) [inline lib/msf/ui/console/command_dispatcher/core.rb]: Since a true condition returns from the method early, there's no need to have an `else` here. The next line can go with the rest of the method body.

Comment (wvu-r7) [reply lib/msf/ui/console/command_dispatcher/core.rb]: Oops, good catch. We'll still need to set `@previous_module`.

**Comment by acammack-r7** [comment]
Looking at this again, I would really like to get the logic for clearing cached payloads on target switch out of the `set` command. Can we add a check for `TARGET` in `option_values_payloads` like you added for the module?

**Comment by wvu-r7** [comment]
@acammack-r7: That's what I was suggesting initially on Slack. I can do that.

**Comment by wvu-r7** [comment]
Hmm, so `option_values_payloads` is called on tab completion for `set PAYLOAD`. We want to invalidate the cache when `TARGET` is actually set.

**Comment by wvu-r7** [comment]
It doesn't matter when `TARGET` is set, so we can use the same trick in `option_values_payloads`.

**Comment by busterb** [comment]
## Release Notes

This fixes a bug where the tab-completion list of possible payloads for a module would not reflect accurate results when switching between different modules with different compatible payloads.
