### PR TITLE
Fix memcached extractor issue 12884

### LINKED ISSUE #12884: memcached_extractor returns only cold items for segmented LRU
## Steps to reproduce

Just perform a dump using metasploit module on a Memcached server with segmented LRU active.

1. use auxiliary/gather/memcached_extractor
2. run

## Expected behavior

̀`memcached_extractor` shall return all objects from the memcache, whatever the LRU status (**cold**, **warm**, **hot**).

## Current behavior

When segmented LRU is active, Memcached returns only the keys from the **cold** states. This is due to the use of the [`stats cachedump`](https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/gather/memcached_extractor.rb#L58) command by the module which is limited to **cold** items (see [source code of memcached](https://github.com/memcached/memcached/blob/master/items.c#L593))

In a heavily used cache server, most items may be in **warm** or **hot** state.

## Fix Proposal

Currently the module uses the `stats cachedump` command with this **cold** state only limitation. An alternative exists: `lru_crawler metadump all` wich returns all the keys whatever the state but the regexp needs to be adapted.
LRU Segmented enablement status can be recovered with:

```
stats settings
(...)
STAT lru_segmented yes
(...)
END
```

### Metasploit version

5.0.18-dev

### OS

Kali

### PR DESCRIPTION
**Pull request by noncenz**
This change resolves #12884 for recent versions of memcached.

Please ensure you are submitting **from a unique branch** in your [repository](https://github.com/rapid7/metasploit-framework/pull/11086#issuecomment-445506416) to master in Rapid7's.

## Verification

[test_memcached_extractor.sh.zip](https://github.com/rapid7/metasploit-framework/files/4637513/test_memcached_extractor.sh.zip)
Use script to test:
- [ ] Install memcached
- [ ] Seed cache with data
- [ ] Recall items from cache to mark them as warm
- [ ] Start `msfconsole`
- [ ] `use auxiliary/gather/memcached_extractor`
- [ ] Set IP, Port
- [ ] Run
- [ ] All keys (20) added returned in scan

Versions of memcached prior to 1.5.4 have no or an incomplete lru_crawler function. Cachedump will be used in this case. 

## Sample test output - cachedump

```bash
STAT version 1.4.23

STAT items:2:number 20
STAT items:2:age 0
STAT items:2:evicted 0

-------------------

[*] 127.0.0.1:11211       - Connecting to memcached server...
[+] 127.0.0.1:11211       - Connected to memcached version 1.4.23
[*] 127.0.0.1:11211       - Using cachedump to enumerate keys
[+] 127.0.0.1:11211       - Found 20 keys

Keys/Values Found for 127.0.0.1:11211
=====================================

 Key    Value
 ---    -----
 key11  "VALUE key11 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key12  "VALUE key12 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key13  "VALUE key13 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key14  "VALUE key14 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key15  "VALUE key15 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key16  "VALUE key16 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key17  "VALUE key17 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key18  "VALUE key18 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key19  "VALUE key19 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key20  "VALUE key20 0 27\r\nsome data to be cached.....\r\nEND\r\n"

[*] 127.0.0.1:11211       - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
geoff@ubuntu-dev:~/source/metasploit-framework/modules$ 
```
## Sample test output - lru_crawler
```bash
STAT version 1.6.6

STAT items:1:number 20
STAT items:1:number_hot 20
STAT items:1:number_warm 0
STAT items:1:number_cold 0

-------------------

[*] 127.0.0.1:11211       - Connecting to memcached server...
[+] 127.0.0.1:11211       - Connected to memcached version 1.6.6
[*] 127.0.0.1:11211       - Using lru_crawler to enumerate keys
[+] 127.0.0.1:11211       - Found 20 keys

Keys/Values Found for 127.0.0.1:11211
=====================================

 Key    Value
 ---    -----
 key01  "VALUE key01 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key02  "VALUE key02 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key03  "VALUE key03 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key04  "VALUE key04 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key05  "VALUE key05 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key06  "VALUE key06 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key07  "VALUE key07 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key08  "VALUE key08 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key19  "VALUE key19 0 27\r\nsome data to be cached.....\r\nEND\r\n"
 key20  "VALUE key20 0 27\r\nsome data to be cached.....\r\nEND\r\n"

[*] 127.0.0.1:11211       - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
geoff@ubuntu-dev:~/source/metasploit-framework/modules$ 
```

### CODE REVIEW

File: modules/auxiliary/gather/memcached_extractor.rb [hunk 1]
```diff
@@ -81,6 +81,20 @@ def enumerate_slab_ids
...
   end
 
+  def enumerate_keys_lru
+    keys = []
+    sock.send("lru_crawler metadump all\r\n", 0)
+    loop do
+      data = sock.recv(4096)
+      break if !data || data.length == 0
+      matches = data.scan(/^key=(?<key>.*) exp=/)
+      keys = keys + matches.flatten! if matches
```
Comment (adfoster-r7) [inline modules/auxiliary/gather/memcached_extractor.rb:91]: Hey, thanks for the PR. I've just tested this against a fresh memcached instance running in docker.

In one tab I ran:

```
docker run --rm -p 11211:11211 memcached
```

And in a msfconsole tab, I ran:

```
use gather/memcached_extractor
set verbose true
set RHOSTS 127.0.0.1
run
```

Which gave the following result:

```
> run

[*] 127.0.0.1:11211       - Connecting to memcached server...
[+] 127.0.0.1:11211       - Connected to memcached version 1.6.6
[*] 127.0.0.1:11211       - Using lru_crawler to enumerate keys
[*] 127.0.0.1:11211       - Error: 127.0.0.1: TypeError no implicit conversion of nil into Array
[*] 127.0.0.1:11211       - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

It looks like if there's no keys present, memcached immediately returns `END` and causes issues with `keys + matches.flatten!`, as `matches.flatten!` on an empty array returns `nil`:

```
$ irb
2.6.6 :001 > [].flatten!
 => nil 
```

It would be great to fix this edge case - let me know if I can do anything to help! :+1:

File: modules/auxiliary/gather/memcached_extractor.rb [hunk 2]
```diff
@@ -58,8 +58,8 @@ def enumerate_keys
         sock.send("stats cachedump #{sid} #{max_keys}\r\n", 0)
         data = sock.recv(4096)
         break if !data || data.length == 0
-        matches = /^ITEM (?<key>.*) \[/.match(data)
-        keys << matches[:key] if matches
+        matches = data.scan(/^ITEM (?<key>.*) \[/)
+        keys = keys + matches.flatten! if matches
```
Comment (adfoster-r7) [inline modules/auxiliary/gather/memcached_extractor.rb:62]: I haven't test this, but it looks like this rewrite might have the same issue as the below changes? i.e. Raising an error on nil due to the `matches.flatten!` call.

I wonder if the previous implementation was a cleaner approach:

```ruby
        matches = /^ITEM (?<key>.*) \[/.match(data)
        keys << matches[:key] if matches
```

Was there a bug in the existing implementation that was being fixed?

Comment (noncenz) [reply modules/auxiliary/gather/memcached_extractor.rb:62]: Using cachedump we collect a list of slab_ids before enumerating keys. When there are no keys there are no slabs (as far as I have seen) so this code doesn't run. I'll add the extra check in as done in enumerate_keys_lru just to be sure. 

The original implementation was only ever returning the first key in my tests, even on older versions of memcached. This is my first foray into Ruby but it looks like that's how .match is implemented, so I do believe this was an additional bug.

**Comment by adamgalway-r7** [comment]
Merged, thanks for the update @noncenz  💯

**Comment by adamgalway-r7** [comment]
## Release Notes
The "memcahed extractor" auxiliary scanner now works correctly with memcached servers that implement LRU. This applies to memchached servers of versions 1.5.4 and up.
