### PR TITLE
Fix reference URLs for several modules and update tools/modules/module_reference.rb code with fixes

### LINKED ISSUE #4039: Automate URL reference checking for validity
We could use a tool that went through all modules, pulled out their URL references, and verified that these are still reachable and pointing to 200-status web pages, making it easy to prune and update bad references. An example of this is `exploit/multi/sap/sap_soap_rfc_sxpg_call_system_exec` which links to the invalid page at `https://labs.mwrinfosecurity.com/tools/2012/04/27/sap-metasploit-modules/`

### PR DESCRIPTION
**Pull request by h00die**
fixes #4039 

Updated `tools/modules/module_reference.rb` with a rubocop run, removed the SSL version reference to use the default. Made it so 300s now mark as down, and a CSV export.

This gave ~2600 URLs with issues (some seem to work and were false positives).

Mainly just either putting in the new URLs (if it forwards), looking for the real URL via google search, or worst case going with wayback machine references.  If all those cases fail, I just leave it as is.

### CODE REVIEW

**Comment by h00die** [comment]
Linting will fail on this because i'm touching so many modules. I have no intention of doing rubocop on them. #dealwithit

**Comment by adfoster-r7** [comment]
@h00die To help with reviewing/landing, it'd be great to revert the rubocop autocorrections and keep this PR limited to the URL fixes 👀 

Or if that's overhead, I can create a separate PR to rubocop these modules to help reduce the noise a bit

**Comment by h00die** [comment]
To save some code somewhere, i'm using a really quick and dirty python script to go through the csv output of `module_reference.rb` (csv output coming to this pr) to catch all the 300s and overwrite them in the module.  MANY of the responses are just `http` to `https` or adding a `/` at the end, so this catches many of those.  However, it isn't perfect as many sites will forward you to a home page and such. Manual review still required.

```
import csv
import requests

cache = {}


def fix(module, old, new):
    print(f"  Updating {module} from {old} -> {new}")
    try:
        with open(f"modules/{module}.rb") as r:
            data = r.read()
        data = data.replace(f"'old'", new)
        with open(f"modules/{module}.rb", "w") as w:
            w.write(data)
    except Exception as e:
        print(e)


with open("/tmp/all_url_refs.csv", newline="") as csvfile:
    reflist = csv.reader(csvfile)
    for row in reflist:
        module = row[0]
        status = row[1]
        badurl = row[2].replace("URL-", "")
        if status != "Down":
            continue
        print(f"Checking: {badurl}")
        if badurl in cache:
            print("  got a cache hit")
            fix(module, badurl, cache[badurl])
            continue
        try:
            r = requests.get(badurl, allow_redirects=True, timeout=5)
            if (
                r.status_code == 200
                and not "not found" in r.text.lower()
                and r.url != badurl
            ):
                cache[badurl] = r.url
                fix(module, badurl, cache[badurl])
        except Exception as e:
            print(e)

```

**Comment by bcoles** [comment]
> > To save some code somewhere
> 
> Didn't we already have a script for this somewhere?

Oh right. The `tools/modules/module_reference.rb` tool which this PR is specifically about. Ignore  this.

File: modules/auxiliary/admin/http/allegro_rompager_auth_bypass.rb [hunk 1]
```diff
@@ -25,8 +25,8 @@ def initialize(info = {})
               ],
               'References' => [
                   ['CVE', '2014-9222'],
-                  ['URL', 'http://mis.fortunecook.ie'],
-                  ['URL', 'http://mis.fortunecook.ie/misfortune-cookie-suspected-vulnerable.pdf'], # list of likely vulnerable devices
+                  ['URL', 'https://web.archive.org/web/20191006135858/http://mis.fortunecook.ie/'],
+                  ['URL', 'https://web.archive.org/web/20190207102911/http://mis.fortunecook.ie/misfortune-cookie-suspected-vulnerable.pd'], # list of likely vulnerable devices
                   ['URL', 'http://mis.fortunecook.ie/too-many-cooks-exploiting-tr069_tal-oppenheim_31c3.pdf'] # 31C3 presentation with POC
```
Comment (bcoles) [inline modules/auxiliary/admin/http/allegro_rompager_auth_bypass.rb:30]: Presumably this URL should also be updated to use `archive.org`.

The two `mis.fortunecook.ie` URLs above were updated to use `archive.org`. `mis.fortunecook.ie` resolves but does not have ports 80 or 443 open.

```suggestion
                  ['URL', 'https://web.archive.org/web/20190623150837/http://mis.fortunecook.ie/too-many-cooks-exploiting-tr069_tal-oppenheim_31c3.pdf'] # 31C3 presentation with POC
```

File: modules/auxiliary/admin/http/allegro_rompager_auth_bypass.rb [hunk 2]
```diff
@@ -25,8 +25,8 @@ def initialize(info = {})
               ],
               'References' => [
                   ['CVE', '2014-9222'],
-                  ['URL', 'http://mis.fortunecook.ie'],
-                  ['URL', 'http://mis.fortunecook.ie/misfortune-cookie-suspected-vulnerable.pdf'], # list of likely vulnerable devices
+                  ['URL', 'https://web.archive.org/web/20191006135858/http://mis.fortunecook.ie/'],
+                  ['URL', 'https://web.archive.org/web/20190207102911/http://mis.fortunecook.ie/misfortune-cookie-suspected-vulnerable.pd'], # list of likely vulnerable devices
```
Comment (bcoles) [inline modules/auxiliary/admin/http/allegro_rompager_auth_bypass.rb:29]: Note sure what happened here. The updated URL with `pd` file extension is invalid. The URL should be:

```suggestion
                  ['URL', 'https://web.archive.org/web/20190207102911/http://mis.fortunecook.ie/misfortune-cookie-suspected-vulnerable.pdf'], # list of likely vulnerable devices
```

File: modules/auxiliary/admin/mssql/mssql_enum_domain_accounts.rb [hunk 3]
```diff
@@ -24,7 +24,7 @@ def initialize(info = {})
           'antti <antti.rantasaari[at]netspi.com>'
         ],
       'License'     => MSF_LICENSE,
-      'References'  => [[ 'URL','http://msdn.microsoft.com/en-us/library/ms174427.aspx']]
+      'References'  => [[ 'URL','https://docs.microsoft.com/en-us/sql/t-sql/functions/suser-sname-transact-sql?redirectedfrom=MSDNhttp://msdn.microsoft.com/en-us/library/ms174427.aspxview=sql-server-ver15']]
```
Comment (bcoles) [inline modules/auxiliary/admin/mssql/mssql_enum_domain_accounts.rb:27]: Trailing garbage.

```suggestion
      'References'  => [[ 'URL','https://docs.microsoft.com/en-us/sql/t-sql/functions/suser-sname-transact-sql']]
```

File: modules/auxiliary/admin/http/allegro_rompager_auth_bypass.rb (hunk 2 above)
Comment (h00die) [reply modules/auxiliary/admin/http/allegro_rompager_auth_bypass.rb:29]: I caught this in my current pass with the automated script. Much more first pass reliable than copy pasta

File: modules/auxiliary/admin/mssql/mssql_enum_domain_accounts_sqli.rb [hunk 4]
```diff
@@ -25,7 +25,7 @@ def initialize(info = {})
           'antti <antti.rantasaari[at]netspi.com>'
         ],
       'License'     => MSF_LICENSE,
-      'References'  => [[ 'URL','http://msdn.microsoft.com/en-us/library/ms174427.aspx']]
+      'References'  => [[ 'URL','https://docs.microsoft.com/en-us/sql/t-sql/functions/suser-sname-transact-sql?redirectedfrom=MSDNhttp://msdn.microsoft.com/en-us/library/ms174427.aspxview=sql-server-ver15']]
```
Comment (bcoles) [inline modules/auxiliary/admin/mssql/mssql_enum_domain_accounts_sqli.rb:28]: Trailing garbage.

```suggestion
      'References'  => [[ 'URL','https://docs.microsoft.com/en-us/sql/t-sql/functions/suser-sname-transact-sql']]
```

File: modules/auxiliary/admin/mssql/mssql_enum_sql_logins.rb [hunk 5]
```diff
@@ -22,7 +22,7 @@ def initialize(info = {})
       },
       'Author'      => ['nullbind <scott.sutherland[at]netspi.com>'],
       'License'     => MSF_LICENSE,
-      'References'  => [['URL','http://msdn.microsoft.com/en-us/library/ms174427.aspx']]
+      'References'  => [['URL','https://docs.microsoft.com/en-us/sql/t-sql/functions/suser-sname-transact-sql?redirectedfrom=MSDNhttp://msdn.microsoft.com/en-us/library/ms174427.aspxview=sql-server-ver15']]
```
Comment (bcoles) [inline modules/auxiliary/admin/mssql/mssql_enum_sql_logins.rb:25]: Trailing garbage.

```suggestion
      'References'  => [['URL','https://docs.microsoft.com/en-us/sql/t-sql/functions/suser-sname-transact-sql']]
```

**Comment by h00die** [comment]
@bcoles don't start looking through this yet. I'll be more or less updating all of this hopefully today with the final run

**Comment by h00die** [comment]
This is now ready for review.  Obvi it isn't complete, but it does update quite a few old and really old links to work again.

I think the funniest one is http://www.smbloris.com/ is now an office furniture store or something.

**Comment by bcoles** [comment]
> [...] csv output coming to this pr

I think this closes #4039 ? This issue is 7 years old and mostly done. It was re-opened until the results were "easy to prune". Presumably your CSV output is easy to parse.

File: modules/auxiliary/scanner/http/wp_modern_events_calendar_sqli.rb [hunk 6]
```diff
@@ -0,0 +1,99 @@
+##
```
Comment (bcoles) [inline modules/auxiliary/scanner/http/wp_modern_events_calendar_sqli.rb:1]: It looks like this file was accidentally included in this PR.

File: modules/auxiliary/scanner/sap/sap_soap_rfc_eps_get_directory_listing.rb [hunk 7]
```diff
@@ -36,7 +36,7 @@ def initialize
       },
       'References' =>
         [
-          [ 'URL', 'http://labs.mwrinfosecurity.com' ]
+          [ 'URL', 'https://labs.f-secure.com/' ]
```
Comment (bcoles) [inline modules/auxiliary/scanner/sap/sap_soap_rfc_eps_get_directory_listing.rb:39]: Should this be `'https://labs.f-secure.com/tools/sap-metasploit-modules/'` like the others?

I downloaded the zip, but didn't find this module in there (perhaps the file name has changed).

File: modules/exploits/windows/browser/ovftool_format_string.rb [hunk 8]
```diff
@@ -90,15 +90,15 @@ def ovf
...
+xmlns:vmw="https://www.vmware.com/schema/ovf"
 xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <References>
     <File ovf:href="Small VM-disk1.vmdk" ovf:id="file1" ovf:size="68096" />
   </References>
   <DiskSection>
     <Info>Virtual disk information</Info>
-    <Disk ovf:capacity="8" ovf:capacityAllocationUnits="#{fs}" ovf:diskId="vmdisk1" ovf:fileRef="file1" ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized" />
+    <Disk ovf:capacity="8" ovf:capacityAllocationUnits="#{fs}" ovf:diskId="vmdisk1" ovf:fileRef="file1" ovf:format="https://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized" />
```
Comment (bcoles) [inline modules/exploits/windows/browser/ovftool_format_string.rb]: What happened here? Were these `http -> https` changes to exploit code intended?

File: modules/exploits/windows/fileformat/ovf_format_string.rb [hunk 9]
```diff
@@ -90,15 +90,15 @@ def ovf
...
+xmlns:vmw="https://www.vmware.com/schema/ovf"
 xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <References>
     <File ovf:href="Small VM-disk1.vmdk" ovf:id="file1" ovf:size="68096" />
   </References>
   <DiskSection>
     <Info>Virtual disk information</Info>
-    <Disk ovf:capacity="8" ovf:capacityAllocationUnits="#{fs}" ovf:diskId="vmdisk1" ovf:fileRef="file1" ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized" />
+    <Disk ovf:capacity="8" ovf:capacityAllocationUnits="#{fs}" ovf:diskId="vmdisk1" ovf:fileRef="file1" ovf:format="https://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized" />
```
Comment (bcoles) [inline modules/exploits/windows/fileformat/ovf_format_string.rb]: Same here. Changes to exploit code.

**Review by bcoles — COMMENTED** [review]
I read through the URL changes.

I noticed that all `r-7.co` links were changed (presumably because they 30x redirected). Presumably, the purpose of this domain was for conventiant URL shortening. On the other hand, 30x status codes should be considered an error. :shrug:

There are a few references like these which simply point to a vendor or researcher's domain/blog, rather than anything relevant to the module:

```
[ 'URL', 'https://blog.c22.cc' ]
```

```
[ 'URL', 'https://labs.f-secure.com/' ]
```

These references aren't useful and are more akin to advertising.

File: modules/auxiliary/scanner/http/wp_modern_events_calendar_sqli.rb (hunk 6 above)
Comment (h00die) [reply modules/auxiliary/scanner/http/wp_modern_events_calendar_sqli.rb]: oops, good catch

File: modules/auxiliary/scanner/sap/sap_soap_rfc_eps_get_directory_listing.rb (hunk 7 above)
Comment (h00die) [reply modules/auxiliary/scanner/sap/sap_soap_rfc_eps_get_directory_listing.rb:39]: I tried to do 1:1 replacements, investigating 2,600 broken URLs intelligently was entirely too time consuming.  I'm keen to leave this as is since that's what was originally there

File: modules/exploits/windows/browser/ovftool_format_string.rb (hunk 8 above)
Comment (h00die) [reply modules/exploits/windows/browser/ovftool_format_string.rb:101]: nope, that was not, thus the dangers of a blind string replace. good catch.

**Comment by h00die** [comment]
agree on the `r-7.co` shortlinks. I could go either way.

**Comment by adfoster-r7** [comment]
@gwillcox-r7 Looks like in this scenario we should be good to ignore the linting failures. The pull request is just updating the URLs of the modules - and it would just muddy the waters to request linting 367 modules as part of this pull request 👀

**Comment by adfoster-r7** [comment]
@h00die If you're good for this to be reviewed/landed, it'd be great to squash this down to a single commit 🎉

**Comment by gwillcox-r7** [comment]
> @gwillcox-r7 Looks like in this scenario we should be good to ignore the linting failures. The pull request is just updating the URLs of the modules - and it would just muddy the waters to request linting 367 modules as part of this pull request 👀

No problem I was just going through PRs that are open and was assigning tags to those that were open but didn't have labels attached to them yet. Wasn't sure if we needed that given the changes being made here so thanks for clarifying.

**Comment by h00die** [comment]
squishy squashy, all in one.

**Comment by gwillcox-r7** [comment]
Will need to rebase this as we removed the VSS modules so they don't need to be updated anymore, but rest looks like it should be easy to check and then land.

**Review by gwillcox-r7 — CHANGES_REQUESTED** [review]

**Comment by gwillcox-r7** [comment]
Fixed up some of the errors encountered when running the tool in https://github.com/rapid7/metasploit-framework/pull/16093/commits/d7b442f782adc17f5bde2688968beb604e597108

File: tools/modules/module_reference.rb [hunk 10]
```diff
@@ -202,57 +213,61 @@ def save_results(path, results)
...
-          end
+    next unless type == 'ALL' || type == ctx_id
+
+    if check
+      if types.has_key?(ctx_id)
+        if ctx_id == 'MSB'
+          year = in_ctx_val[2..3]
+          century = year[0] == '9' ? '19' : '20'
+          in_ctx_val = "#{century}#{year}/#{in_ctx_val}"
+        end
```
[the remark this answers is not in the document]
Comment (gwillcox-r7) [reply tools/modules/module_reference.rb]: Fixed this in https://github.com/rapid7/metasploit-framework/commit/d7b442f782adc17f5bde2688968beb604e597108

File: tools/modules/module_reference.rb [hunk 11]
```diff
@@ -202,57 +213,61 @@ def save_results(path, results)
...
+        uri = types[r.ctx_id.upcase].gsub(/\#{in_ctx_val}/, r.ctx_val)
```
[the remark this answers is not in the document]
Comment (gwillcox-r7) [reply tools/modules/module_reference.rb]: Code was updated in https://github.com/rapid7/metasploit-framework/commit/d7b442f782adc17f5bde2688968beb604e597108, but still need to recheck this and see if the issue has been fixed.

[the remark this answers is not in the document]
Comment (gwillcox-r7) [reply tools/modules/module_reference.rb]: Nope looks like its still hitting errors:

```
[*] Checking: https://blogs.securiteam.com/index.php/archives/3310
tools/modules/module_reference.rb:245:in `gsub': no implicit conversion of Integer into String (TypeError)
	from tools/modules/module_reference.rb:245:in `block (2 levels) in <main>'
	from tools/modules/module_reference.rb:232:in `each'
	from tools/modules/module_reference.rb:232:in `block in <main>'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/module_manager.rb:106:in `block (2 levels) in each'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/module_set.rb:78:in `each'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/module_set.rb:78:in `each'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/module_manager.rb:105:in `block in each'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/module_manager.rb:104:in `each'
	from /home/gwillcox/git/metasploit-framework/lib/msf/core/module_manager.rb:104:in `each'
	from tools/modules/module_reference.rb:223:in `<main>'
```

Lets see if I can't fix this up.

[the remark this answers is not in the document]
Comment (gwillcox-r7) [reply tools/modules/module_reference.rb]: This can be fixed by changing the last line to `uri = types[r.ctx_id.upcase].gsub(/\#{in_ctx_val}/, r.ctx_val.to_s)`

[the remark this answers is not in the document]
Comment (gwillcox-r7) [reply tools/modules/module_reference.rb]: Fixed in https://github.com/rapid7/metasploit-framework/pull/16093/commits/0ca56600a69e05902ef9a914c513ff63d3368fa6

**Comment by gwillcox-r7** [comment]
Running a complete check now. Is taking a while (been nearly an hour now) but hopefully it should tell us if the latest changes work and if there are any remaining URLs that need fixing.

**Review by gwillcox-r7 — APPROVED** [review]

File: tools/modules/module_reference.rb [hunk 12]
```diff
@@ -143,44 +153,45 @@ def is_url_alive?(uri, http_timeout)
...
+  rescue Errno::ECONNRESET, Rex::ConnectionError, Rex::ConnectionRefused, Rex::HostUnreachable, Rex::ConnectionTimeout, Rex::UnsupportedProtocol, ::Timeout::Error, Errno::ETIMEDOUT, ::Exception => e
     vprint_debug("#{e.message} for #{uri}")
+    cache[uri.to_s] = false
     return false
   ensure
     cli.close
   end
 
-  if res.nil? || res.code == 404 || res.body =~ /<title>.*not found<\/title>/i
+  if res.nil? || res.body =~ %r{<title>.*not found</title>}i || res.code != 200
```
Comment (gwillcox-r7) [inline tools/modules/module_reference.rb]: I'm in disagreement with this and the prime reason here is that if the code is a redirect code, your essentially going to end up with hundreds of links that end up being reported as being "down" when in reality they aren't actually down.

Case in point I ran this against all URLs in the database, and ended up with this result:

```
post/windows/manage/sticky_  Down         URL-https://blog.carnal0wnage.com/2012/04/pri
  keys                                      vilege-escalation-via-sticky-keys.html
  post/windows/manage/vmdk_mo  Down         URL-http://www.shelliscoming.com/2017/05/post
  unt                                       -exploitation-mounting-vmdk-files.html
  post/windows/manage/vss      Alive        URL-https://web.archive.org/web/2020111121295
                                            2/https://securityweekly.com/2011/11/02/safel
                                            y-dumping-hashes-from-liv/
  post/windows/recon/outbound  Down         URL-http://www.shelliscoming.com/2014/11/gett
  _ports                                    ing-outbound-filtering-rules-by.html

Number of bad references found: 8663
```

Note here that `http://www.shelliscoming.com/2017/05/post-exploitation-mounting-vmdk-files.html` is considered down but in reality if you visit that page it just upgrades to a SSL version of that page so its not really "down" per say.

Now that being said I'm all for updating these old links to https links, but this labeling of a link as "down" doesn't really serve to help anyone and only causes more confusion.

**Review by gwillcox-r7 — CHANGES_REQUESTED** [review]

File: tools/modules/module_reference.rb (hunk 12 above)
Comment (gwillcox-r7) [reply tools/modules/module_reference.rb]: I also have concerns r.e the accuracy of this script given that `https://blog.carnal0wnage.com/2012/04/privilege-escalation-via-sticky-keys.html` was incorrectly labeled as being `down`. I'll have to look into this further.

Comment (gwillcox-r7) [reply tools/modules/module_reference.rb]: Alright so the response to the link above was `HTTP/2 200 OK` so its possible that maybe the handler doesn't handle HTTP/2 responses correctly? Idk.

Comment (gwillcox-r7) [reply tools/modules/module_reference.rb]: > I also have concerns r.e the accuracy of this script given that https://blog.carnal0wnage.com/2012/04/privilege-escalation-via-sticky-keys.html was incorrectly labeled as being `down`. I'll have to look into this further.

This has been addressed with https://github.com/rapid7/metasploit-framework/pull/16093/commits/550a625dc747c6c6df9bf38a6275f91e2c741b4c which does a major rework in an attempt to support redirections by defining a new status type for redirects and updating the code to report the status appropriately whilst also still not labeling the URL as down.

Comment (gwillcox-r7) [reply tools/modules/module_reference.rb]: Our Rex library appears to be pulling some B.S on SSL versions that honestly is leading me scratching my head. Seems to default to SSLv3 if a version is not supplied but if I try change it then its still throwing errors about trying to perform a handshake with SSLv3 that failed.

Ideally as per some discussions with @smcintyre-r7 (sorry CCing you in here as I think this may be an issue with Rex itself), Rex would actually bother to renegotiate the SSL version but this doesn't seem to be the case right now.

Comment (h00die) [reply tools/modules/module_reference.rb]: yea i wasn't happy about calling redirects `down`, but was also trying to keep it more Boolean. I also figured if it isn't perfect, I'd rather call it out to get fixed. regardless, this is a vast improvement regardless.

I noticed the SSL issues as well, didn't want to go down an additional rabbit hole as this was already enough

Comment (gwillcox-r7) [reply tools/modules/module_reference.rb]: No worries @h00die, I think our main concern is if this could affect other modules if this is affecting the Rex library.  Also personally I really don't like the fact that this module probably hasn't been working for a long time now so forgive my continuous editing to try get it working again 😄

**Comment by gwillcox-r7** [comment]
SSL related issues are now being tracked at https://github.com/rapid7/metasploit-framework/issues/16213 as this appears to be a bigger issue affecting much more of our code base than originally anticipated. As this is an unrelated issue to this code though, which seems to be working fine minus that issue, I'm going to go ahead and land this.

**Review by gwillcox-r7 — APPROVED** [review]

**Comment by gwillcox-r7** [comment]
Fixed up last RuboCop issues cause it wasn't that many and was an easy fix. Will land this now, future work on SSL will be another PR as that is a larger job.

**Comment by gwillcox-r7** [comment]
# Release Notes
A number of broken URL references have been fixed in Metasploit modules. In addition the `tools/modules/module_reference.rb` code has been updated to log redirects so that they can be appropriately triaged later and to support saving results to a CSV file. Finally, several modules had their code adjusted to conform to RuboCop standards.
