### PR TITLE
Fix post/osx/gather/password_prompt_spoof

### LINKED ISSUE #12930: post/osx/gather/password_prompt_spoof is broken
_tested on catalina_

## Steps to reproduce

1. `use post/osx/gather/password_prompt_spoof`
2. `run`

## Expected behavior

A prompt is shown to the user.

## Current behavior

The module get stuck waiting for creds but no prompt was shown to the user

### Metasploit version

`Framework: 5.0.73-dev`

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### PR DESCRIPTION
**Pull request by phra**
will fix #12930 

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use post/osx/gather/password_prompt_spoof`
- [x] `set SESSION 1`
- [x] `run`

### CODE REVIEW

File: lib/metasploit/framework/data_service/proxy/loot_data_proxy.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@ def report_loot(opts)
     begin
       self.data_service_operation do |data_service|
         if !data_service.is_a?(Msf::DBManager)
-          opts[:data] = Base64.urlsafe_encode64(opts[:data]) if opts[:data]
+          opts[:data] = Base64.urlsafe_encode64(opts[:data].empty? ? "" : opts[:data].join('')) if opts[:data] and opts[:data].kind_of?(Array) else opts[:data]
```
Comment (timwr) [inline lib/metasploit/framework/data_service/proxy/loot_data_proxy.rb]: @phra how do I test this change? I tested without this change and it still works fine.

Comment (phra) [reply lib/metasploit/framework/data_service/proxy/loot_data_proxy.rb]: I tried the password prompt module on catalina: it's passing a string to this function that expect an array.

**Comment by timwr** [comment]
## Release notes

Fix the OSX password_prompt_spoof module on newer versions of OSX (Catalina and Mojave).
