### PR TITLE
Fix up the DNS enumeration library so that AXFR records aren't displayed with stray [ and ] characters

### LINKED ISSUE #14237: Rogue ] in AXFR results
## Steps to reproduce

How'd you do it?

1. use auxiliary/gather/enum_dns.rb
1. set NS 127.0.0.1
1. set ENUM_AXFR true
1. set DOMAIN mytest.com
1. set ENUM_A false
1. set ENUM_BRT false
1. set ENUM_MX false
1. set ENUM_SOA false
1. set ENUM_SRV false
1. set ENUM_TXT false
1. set ENUM_CNAME false
1. set ENUM_NS false
1. run

Basically, just do an AXFR on its own.

## Were you following a specific guide/tutorial or reading documentation?

n/a

## Expected behavior

No random ] at the end of the results

## Current behaviour

There is an extra ] after the results.

image

It doesn't appear to be closing for anything opened earlier so I think it is just a print that isn't in the right place.

### Metasploit version

```
d0778c7a547a0f49fdea54463862306764675090 (HEAD, upstream/master) Land #14228, Increase operations per run
```

### PR DESCRIPTION
**Pull request by gwillcox-r7**
Fixes #14237

This resolves an issue whereby AXFR records were being printed out by the enumeration library with stray `[` and `]` characters because the library failed to take into account that one of its arguments was an array and was trying to print it out as a string, without first removing the stray `[` and `]` characters that will be included when Ruby converts the array to a string.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use auxiliary/gather/enum_dns`
- [x] `set DOMAIN zonetransfer.me`
- [x] `set ENUM_A false`
- [x] `set ENUM_CNAME false`
- [x] `set ENUM_MX false`
- [x] `set ENUM_NS false`
- [x] `set ENUM_SRV false`
- [x] `set ENUM_TXT false`
- [x] `set ENUM_AXFR true` <- This is the only ENUM_ setting that should be set to `true`.
- [x] **Verify** that the DNS zone transfer works successfully and that you don't see a line like `[+] zonetransfer.me Zone Transfer: [;; Answer received from 34.225.33.2:53 (2039 bytes)` and instead see a line like `[+] zonetransfer.me Zone Transfer: ;; Answer received from 81.4.108.41:53 (1983 bytes)` (notice the lack of `[`).
- [x] **Verify** that no `]` characters are shown at the end of the output.

### CODE REVIEW

File: lib/msf/core/exploit/dns/enumeration.rb [hunk 1]
```diff
@@ -62,7 +62,7 @@ def dns_axfr(domain)
       end
       next if zone.blank?
       records << zone
-      print_good("#{domain} Zone Transfer: #{zone}")
+      print_good("#{domain} Zone Transfer: #{zone.to_s[1...-1]}") # Use [1...-1] to remove the stray [ and ] characters from the output.
```
Comment (smcintyre-r7) [inline lib/msf/core/exploit/dns/enumeration.rb:65]: Since zone is actually an array of `Net::DNS::Packet`, this whole section should probably be updated accordingly. It looks like it used to expect `zone` to be a string and not an array of record answers.

```suggestion
      next if zone.empty?
      records += zone
      print_good("#{domain} Zone Transfer: #{zone.map(&:inspect).join}")
```
Specifically note:
* Using `#empty?` instead of blank because we're expecting an array and not a string
* Concatenating the array with `records += zone` instead of creating a multi-dimensional array
* Explicitly converting each packet to a string using `Net::DNS::Packet#inspect` which looks like the intended API

I checked and this function is only defined here and only used by `auxiliary/gather/enum_dns` so it should be fine to fix the multi-dimensional array return value.

Comment (gwillcox-r7) [reply lib/msf/core/exploit/dns/enumeration.rb:65]: Thanks, this makes a lot of sense! I'll see if I can't get this PR updated with your suggested changes 👍

Comment (gwillcox-r7) [reply lib/msf/core/exploit/dns/enumeration.rb:65]: Woops forgot to make this edit let me go ahead and do that so long.

Comment (gwillcox-r7) [reply lib/msf/core/exploit/dns/enumeration.rb]: Edits made in https://github.com/rapid7/metasploit-framework/pull/14250/commits/ab7ed90457da790cdc09e1708409d832e7e6701b, and had a lengthy discussion over whether or not to use `.empty?` or `.blank?`. Ultimately decided to use `.blank?` as it uses both `.empty?` anyway and it also does a `nil` check on the object.

With that being said I do agree with @smcintyre-r7's point that he raised that `.blank?` on an array doesn't really make much sense from an explanation point of view, as you don't exactly say an array object is blank, you say its empty.

That being said as this library is using the `.blank?` call in a number of places already I'm going to follow this library's convention and use `.blank?` here purely so that the code doesn't become a jumbled mess of different approaches and also because it implements more checks in one line.

If someone does wish to change this down the line in the future then they are welcome to do it in a separate PR and I'd be happy to assist 👍

File: lib/msf/core/exploit/dns/enumeration.rb [hunk 2]
```diff
@@ -61,8 +61,8 @@ def dns_axfr(domain)
         print_error("Query #{domain} DNS AXFR - unknown exception: #{e}")
       end
       next if zone.blank?
-      records << zone
-      print_good("#{domain} Zone Transfer: #{zone}")
+      records += zone
+      print_good("#{domain} Zone Transfer: #{zone.map(&:inspect).join}")
```
Comment (smcintyre-r7) [inline lib/msf/core/exploit/dns/enumeration.rb:65]: Since the zone starts with `;;`, I noticed that it looks a little awkward this way:
```
[+] zonetransfer.me Zone Transfer: ;; Answer received from 81.4.108.41:53 (1983 bytes)
;;
;; HEADER SECTION
```

I think it might look a little better if the zone info started on it's own new line:
```suggestion
      print_good("#{domain} Zone Transfer:")
      print_line(zone.map(&:inspect).join)
```

Which would change the output to:
```
[+] zonetransfer.me Zone Transfer:
;; Answer received from 81.4.108.41:53 (1983 bytes)
;;
;; HEADER SECTION
```

**Review by smcintyre-r7 — COMMENTED** [review]
I went through and tested this and it works great and addresses the issue. I left one comment suggesting a change to improve the printed output just a little.

The other thing I noticed while running the `auxiliary/gather/enum_dns` module is that it contains it's own `axfr` function **which isn't used**. The one that is used is the `dns_axfr` function that you updated here. Do you think you could please remove it while we're updating this function so future travelers know there's one authoritative implementation?

**Comment by bcoles** [comment]
> The other thing I noticed while running the `auxiliary/gather/enum_dns` module is that it contains it's own `axfr` function **which isn't used**. The one that is used is the `dns_axfr` function that you updated here. Do you think you could please remove it while we're updating this function so future travelers know there's one authoritative implementation?

Additional context on the dead code:

* https://github.com/rapid7/metasploit-framework/issues/13952#issuecomment-670414067
* https://github.com/rapid7/metasploit-framework/issues/13952#issuecomment-670415241

Spoiler: it is broken

**Comment by gwillcox-r7** [comment]
Thanks @bcoles, makes sense :) I might see if I can't spend some time addressing the rest of the errors mentioned there in a seperate PR seeing as I am working on the affected code now.

File: lib/msf/core/exploit/dns/enumeration.rb (hunk 2 above)
Comment (gwillcox-r7) [reply lib/msf/core/exploit/dns/enumeration.rb:65]: Yeah that one irked me as well, I'll get that fixed :)

**Review by smcintyre-r7 — APPROVED** [review]
Just tested this again and everything looks good now, thanks @gwillcox-r7! I was able to reproduce the original issue and verify this fixes it.

**Comment by smcintyre-r7** [comment]
# Release Notes
This fixes an issue in the DNS enumeration library that was causing zone transfer (AXFR) results to be displayed with a leading and trailing bracket.
