### PR TITLE
Fix port parsing error when importing openvas

### LINKED ISSUE #14174: db_import not able to import openvas xml data
## Steps to reproduce

1. Create scan report with OpenVas Version 9 (now called gvm) in XML
2. Open msfconsole
3. Import XML with `db_import ~/xml_name.xml`

## Expected behavior
`msf5 > db_import rr.xml`
`[*] Importing 'Openvas XML' data`
`[*] Importing host 10.0.2.15`
`[*] Importing host 10.0.2.15`
`[*] Importing host 10.0.2.15`
`[*] Importing host 10.0.2.15`
`[*] Importing host 10.0.2.15`
`[*] Importing host 10.0.2.15`
`[*] Successfully imported path/to/test.xm`

## Current behavior
`msf5 > db_import rr.xml`
`[*] Importing 'OpenVAS XML' data`
`[*] Import: Parsing with 'Nokogiri v1.10.10'`
`[-] **Error while running command db_import: Validation failed: Port must be an integer**`

Call stack:
```
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/validations.rb:79:in raise_record_invalid'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/validations.rb:43:in `save!'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:291:in `block in save!'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:220:in `transaction'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:291:in `save!'
`/usr/share/metasploit-framework/lib/msf/core/db_manager/service.rb:132:in `block in report_service'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord`-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in with_connection'
`/usr/share/metasploit-framework/lib/msf/core/db_manager/service.rb:61:in `report_service'
`/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:38:in `block in report_service'
`/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
`/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:36:in `report_service'
`/usr/share/metasploit-framework/lib/rex/parser/nokogiri_doc_mixin.rb:152:in `db_report'
`/usr/share/metasploit-framework/lib/rex/parser/openvas_nokogiri.rb:179:in `record_service'
`/usr/share/metasploit-framework/lib/rex/parser/openvas_nokogiri.rb:117:in `end_element'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/document.rb:127:in end_element_namespace'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:110:in parse_with'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:110:in parse_memory'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:83:in parse'
`/usr/share/metasploit-framework/lib/msf/core/db_manager/import/open_vas.rb:11:in `import_openvas_noko_stream'
`/usr/share/metasploit-framework/lib/msf/core/db_manager/import/open_vas.rb:22:in `import_openvas_new_xml'
`/usr/share/metasploit-framework/lib/msf/core/db_manager/import.rb:100:in `import'
`/usr/share/metasploit-framework/lib/msf/core/db_manager/import.rb:219:in `import_file'
`/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb:17:in `block in import_file'
`/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
`/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb:15:in `import_file'
`/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1464:in `block (3 levels) in cmd_db_import'
`/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1457:in `each'
`/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1457:in `block (2 levels) in cmd_db_import'
`/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1451:in `each'
`/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1451:in `block in cmd_db_import'
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
`/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1446:in `cmd_db_import'
`/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
`/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
`/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
`/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
`/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
`/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
`/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
`/usr/bin/msfconsole:23:in `<main>'
```

### Metasploit version

`Framework: 5.0.101-dev`
`Console  : 5.0.101-dev`

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/core]
LogLevel=3

[framework/ui/console]
ActiveWorkspace=open
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
351    workspace -a open
352    hosts
353    set LogLevel 3
354    db_import rr.xml
355    debug
```

</details>

##  Errors

The following errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[09/22/2020 16:09:18] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[09/22/2020 16:09:18] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[09/22/2020 16:09:18] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[09/22/2020 16:09:18] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[09/22/2020 16:09:42] [e(0)] core: Problem reporting service - ActiveRecord::RecordInvalid Validation failed: Port must be an integer
[09/22/2020 16:09:42] [e(0)] core: Problem generating DB Import - ActiveRecord::RecordInvalid Validation failed: Port must be an integer
[09/22/2020 21:39:33] [e(0)] core: Problem reporting service - ActiveRecord::RecordInvalid Validation failed: Port must be an integer
[09/22/2020 21:39:33] [e(0)] core: Problem generating DB Import - ActiveRecord::RecordInvalid Validation failed: Port must be an integer
[09/22/2020 21:42:21] [e(0)] core: Problem reporting service - ActiveRecord::RecordInvalid Validation failed: Port must be an integer
Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/validations.rb:79:in `raise_record_invalid'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/validations.rb:43:in `save!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:291:in `block in save!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:220:in `transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:291:in `save!'
/usr/share/metasploit-framework/lib/msf/core/db_manager/service.rb:132:in `block in report_service'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/core/db_manager/service.rb:61:in `report_service'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:38:in `block in report_service'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:36:in `report_service'
/usr/share/metasploit-framework/lib/rex/parser/nokogiri_doc_mixin.rb:152:in `db_report'
/usr/share/metasploit-framework/lib/rex/parser/openvas_nokogiri.rb:179:in `record_service'
/usr/share/metasploit-framework/lib/rex/parser/openvas_nokogiri.rb:117:in `end_element'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/document.rb:127:in `end_element_namespace'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:110:in `parse_with'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:110:in `parse_memory'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:83:in `parse'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import/open_vas.rb:11:in `import_openvas_noko_stream'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import/open_vas.rb:22:in `import_openvas_new_xml'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import.rb:100:in `import'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import.rb:219:in `import_file'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb:17:in `block in import_file'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb:15:in `import_file'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1464:in `block (3 levels) in cmd_db_import'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1457:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1457:in `block (2 levels) in cmd_db_import'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1451:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1451:in `block in cmd_db_import'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1446:in `cmd_db_import'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[09/22/2020 21:42:21] [e(0)] core: Problem generating DB Import - ActiveRecord::RecordInvalid Validation failed: Port must be an integer
Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/validations.rb:79:in `raise_record_invalid'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/validations.rb:43:in `save!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:291:in `block in save!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:220:in `transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:291:in `save!'
/usr/share/metasploit-framework/lib/msf/core/db_manager/service.rb:132:in `block in report_service'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/core/db_manager/service.rb:61:in `report_service'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:38:in `block in report_service'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:36:in `report_service'
/usr/share/metasploit-framework/lib/rex/parser/nokogiri_doc_mixin.rb:152:in `db_report'
/usr/share/metasploit-framework/lib/rex/parser/openvas_nokogiri.rb:179:in `record_service'
/usr/share/metasploit-framework/lib/rex/parser/openvas_nokogiri.rb:117:in `end_element'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/document.rb:127:in `end_element_namespace'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:110:in `parse_with'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:110:in `parse_memory'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:83:in `parse'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import/open_vas.rb:11:in `import_openvas_noko_stream'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import/open_vas.rb:22:in `import_openvas_new_xml'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import.rb:100:in `import'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import.rb:219:in `import_file'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb:17:in `block in import_file'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb:15:in `import_file'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1464:in `block (3 levels) in cmd_db_import'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1457:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1457:in `block (2 levels) in cmd_db_import'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1451:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1451:in `block in cmd_db_import'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1446:in `cmd_db_import'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
```

</details>

##  Logs

The following logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
[09/22/2020 21:42:21] [e(0)] core: Problem generating DB Import - ActiveRecord::RecordInvalid Validation failed: Port must be an integer
Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/validations.rb:79:in `raise_record_invalid'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/validations.rb:43:in `save!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:291:in `block in save!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:220:in `transaction'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:291:in `save!'
/usr/share/metasploit-framework/lib/msf/core/db_manager/service.rb:132:in `block in report_service'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/core/db_manager/service.rb:61:in `report_service'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:38:in `block in report_service'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:36:in `report_service'
/usr/share/metasploit-framework/lib/rex/parser/nokogiri_doc_mixin.rb:152:in `db_report'
/usr/share/metasploit-framework/lib/rex/parser/openvas_nokogiri.rb:179:in `record_service'
/usr/share/metasploit-framework/lib/rex/parser/openvas_nokogiri.rb:117:in `end_element'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/document.rb:127:in `end_element_namespace'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:110:in `parse_with'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:110:in `parse_memory'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:83:in `parse'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import/open_vas.rb:11:in `import_openvas_noko_stream'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import/open_vas.rb:22:in `import_openvas_new_xml'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import.rb:100:in `import'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import.rb:219:in `import_file'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb:17:in `block in import_file'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb:15:in `import_file'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1464:in `block (3 levels) in cmd_db_import'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1457:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1457:in `block (2 levels) in cmd_db_import'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1451:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1451:in `block in cmd_db_import'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1446:in `cmd_db_import'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 5.0.101-dev
Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]
Install Root: /usr/share/metasploit-framework
Session Type: Connected to msf. Connection type: postgresql. Connection name: #<Msf::DBManager:0x0000557c1eeef530>.
Install Method: Other - Please specify
```

</details>

### PR DESCRIPTION
**Pull request by adfoster-r7**
Fix port parsing error when importing to import a openvas file.

closes https://github.com/rapid7/metasploit-framework/issues/14174

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] Ensure you are connected to a local database:
```
msf6 exploit(multi/handler) > db_status
[*] Connected to msf. Connection type: postgresql.
```
- [x] Ensure that the example import is extracted [import.xml.zip](https://github.com/rapid7/metasploit-framework/files/5304200/import.xml.zip)
- [x] `db_import import.xml`
- [x] **Verify** that services and hosts are correctly imported:
```
msf6 > hosts

Hosts
=====

address   mac  name  os_name  os_flavor  os_sp  purpose  info  comments
-------   ---  ----  -------  ---------  -----  -------  ----  --------
10.0.2.4             Unknown                    device

msf6 > services
Services
========

host      port  proto  name  state  info
----      ----  -----  ----  -----  ----
10.0.2.4  8787  tcp          open
10.0.2.4  22    tcp          open
10.0.2.4  80    tcp          open
10.0.2.4  445   tcp          open
10.0.2.4  1524  tcp          open
10.0.2.4  3632  tcp          open
10.0.2.4  5432  tcp          open
10.0.2.4  5900  tcp          open
10.0.2.4  6200  tcp          open
10.0.2.4  6667  tcp          open
10.0.2.4  8009  tcp          open
10.0.2.4  21    tcp          open
```

There should be import messages too, but they're not appearing.

### CODE REVIEW

File: lib/rex/parser/openvas_nokogiri.rb [hunk 1]
```diff
@@ -112,8 +112,8 @@ def end_element(name=nil)
             @state[:proto] = @text.split('(')[1].split('/')[1].split(')')[0]
             record_service unless @state[:name].nil?
           elsif @text.index('/')
-            @state[:port] = @text.split('/')[0]
-            @state[:proto] = @text.split('/')[1]
+            @state[:port] = @text.split('/')[0].strip
```
Comment (adfoster-r7) [inline lib/rex/parser/openvas_nokogiri.rb:115]: Happy path is meant to have no whitespace:
image

This import has whitespace:
image

Which later caused an import error:
```
[-] **Error while running command db_import: Validation failed: Port must be an integer**
```

**Comment by gwillcox-r7** [comment]
Changes look good to me, here is what I see when testing this:

```
msf6 > db_status
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: local-https-data-service.
msf6 > db_disconnect 
Successfully disconnected from the data service: remote_data_service: (https://localhost:5443).
msf6 > db_status
[*] Connected to msf. Connection type: postgresql.
msf6 > db_import import.xml
[*] Importing 'OpenVAS XML' data
[*] Import: Parsing with 'Nokogiri v1.10.10'
[*] Successfully imported /home/gwillcox/git/metasploit-framework/import.xml
msf6 > hosts

Hosts
=====

address   mac  name  os_name  os_flavor  os_sp  purpose  info  comments
-------   ---  ----  -------  ---------  -----  -------  ----  --------
10.0.2.4             Unknown                    device         

msf6 > services
Services
========

host      port  proto  name  state  info
----      ----  -----  ----  -----  ----
10.0.2.4  21    tcp          open   
10.0.2.4  22    tcp          open   
10.0.2.4  80    tcp          open   
10.0.2.4  445   tcp          open   
10.0.2.4  1524  tcp          open   
10.0.2.4  3632  tcp          open   
10.0.2.4  5432  tcp          open   
10.0.2.4  5900  tcp          open   
10.0.2.4  6200  tcp          open   
10.0.2.4  6667  tcp          open   
10.0.2.4  8009  tcp          open   
10.0.2.4  8787  tcp          open   

msf6 > 
```

Here are my results before applying this patch:

```
msf6 > db_status
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: local-https-data-service.
msf6 > db_disconnect
Successfully disconnected from the data service: remote_data_service: (https://localhost:5443).
msf6 > db_import import.xml
[*] Importing 'OpenVAS XML' data
[*] Import: Parsing with 'Nokogiri v1.10.10'
[-] Error while running command db_import: Validation failed: Port must be an integer

Call stack:
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:80:in `raise_validation_error'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:52:in `save!'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `block in save!'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/share/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:315:in `save!'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/suppressor.rb:48:in `save!'
/home/gwillcox/git/metasploit-framework/lib/msf/core/db_manager/service.rb:124:in `block in report_service'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/gwillcox/git/metasploit-framework/lib/msf/core/db_manager/service.rb:53:in `report_service'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:38:in `block in report_service'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:36:in `report_service'
/home/gwillcox/git/metasploit-framework/lib/rex/parser/nokogiri_doc_mixin.rb:152:in `db_report'
/home/gwillcox/git/metasploit-framework/lib/rex/parser/openvas_nokogiri.rb:172:in `record_service'
/home/gwillcox/git/metasploit-framework/lib/rex/parser/openvas_nokogiri.rb:117:in `end_element'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/document.rb:127:in `end_element_namespace'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:110:in `parse_with'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:110:in `parse_memory'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:83:in `parse'
/home/gwillcox/git/metasploit-framework/lib/msf/core/db_manager/import/open_vas.rb:11:in `import_openvas_noko_stream'
/home/gwillcox/git/metasploit-framework/lib/msf/core/db_manager/import/open_vas.rb:22:in `import_openvas_new_xml'
/home/gwillcox/git/metasploit-framework/lib/msf/core/db_manager/import.rb:100:in `import'
/home/gwillcox/git/metasploit-framework/lib/msf/core/db_manager/import.rb:219:in `import_file'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb:17:in `block in import_file'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb:15:in `import_file'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1464:in `block (3 levels) in cmd_db_import'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1457:in `each'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1457:in `block (2 levels) in cmd_db_import'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1451:in `each'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1451:in `block in cmd_db_import'
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1446:in `cmd_db_import'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
msf6 > 
```

**Comment by gwillcox-r7** [comment]
Okay everything looks good, landing now

**Comment by gwillcox-r7** [comment]
# Release Notes
A fix has been applied to the OpenVAS importer to fix an error whereby certain lines related to the port and protocol were not being imported or were causing stack traces when they contained leading or trailing whitespace. The OpenVAS importer will now ensure that port and protocol entries are correctly stripped of whitespace prior to saving these entries into the database.

**Comment by pbarry-r7** [comment]
# Release Notes

Fixed a bug with the <code>db_import</code> command where some OpenVAS XML files would trigger a stack trace and fail to import properly.  Those OpenVAS files should now properly import.
