### PR TITLE
Fix issue with info command and IP address check

### LINKED ISSUE #18048: Running info on fetch payloads fails with "You must set FETCH_SRVHOST to a routable IP"
Run `info payload/cmd/windows/tftp/x64/vncinject/reverse_winhttp` and you'll see the error. I'm pretty sure this affects all the fetch payloads because of how they all share the `FETCH_SRVHOST` datastore option. We'll likely need to move the validation of that option so that the information can be displayed to the user.

```
msf6 > info payload/cmd/windows/tftp/x64/vncinject/reverse_winhttp
[-] Error while running command info: You must set FETCH_SRVHOST to a routable IP

Call stack:
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/payload/adapter/fetch.rb:35:in `check_srvhost'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/payload/adapter/fetch.rb:97:in `generate'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/payload.rb:195:in `size'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/base/serializer/readable_text.rb:500:in `dump_payload_module'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/base/serializer/readable_text.rb:26:in `dump_module'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/ui/console/command_dispatcher/modules.rb:135:in `print_module_info'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/ui/console/command_dispatcher/modules.rb:190:in `block in cmd_info'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/ui/console/command_dispatcher/modules.rb:170:in `each'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/ui/console/command_dispatcher/modules.rb:170:in `cmd_info'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/rex/ui/text/shell.rb:168:in `run'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/command/console.rb:48:in `start'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
msf6 > 
```

### PR DESCRIPTION
**Pull request by bwatters-r7**
Fixes https://github.com/rapid7/metasploit-framework/issues/18048

Before:
```
msf6 payload(cmd/linux/http/x64/meterpreter/reverse_tcp) > info
[-] Error while running command info: You must set FETCH_SRVHOST to a routable IP

Call stack:
/home/tmoose/rapid7/metasploit-framework/lib/msf/core/payload/adapter/fetch.rb:35:in `check_srvhost'
/home/tmoose/rapid7/metasploit-framework/lib/msf/core/payload/adapter/fetch.rb:97:in `generate'
/home/tmoose/rapid7/metasploit-framework/lib/msf/core/payload.rb:195:in `size'
/home/tmoose/rapid7/metasploit-framework/lib/msf/base/serializer/readable_text.rb:500:in `dump_payload_module'
/home/tmoose/rapid7/metasploit-framework/lib/msf/base/serializer/readable_text.rb:26:in `dump_module'
/home/tmoose/rapid7/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:135:in `print_module_info'
/home/tmoose/rapid7/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:159:in `cmd_info'
/home/tmoose/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/home/tmoose/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/home/tmoose/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/home/tmoose/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/home/tmoose/rapid7/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
/home/tmoose/rapid7/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/tmoose/rapid7/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'

```

After
```
msf6 > use payload/cmd/linux/http/x64/meterpreter/reverse_tcp
msf6 payload(cmd/linux/http/x64/meterpreter/reverse_tcp) > info

       Name: HTTP Fetch, Reverse TCP Stager
     Module: payload/cmd/linux/http/x64/meterpreter/reverse_tcp
   Platform: Linux, Linux
       Arch: cmd
Needs Admin: No
 Total size: 106
       Rank: Normal

Provided by:
  Brendan Watters
  Brent Cook <bcook@rapid7.com>
  ricky
  tkmru

Basic options:
Name                Current Setting  Required  Description
----                ---------------  --------  -----------
FETCH_COMMAND       CURL             yes       Command to fetch payload (Accepted: CURL, FTP, TFTP, TNFTP, WGET)
FETCH_DELETE        false            yes       Attempt to delete the binary after execution
FETCH_FILENAME      RFJEBKsJ         no        Name to use on remote system when storing payload; cannot contain spaces.
FETCH_SRVHOST       0.0.0.0          yes       Local IP to use for serving payload
FETCH_SRVPORT       8080             yes       Local port to use for serving payload
FETCH_URIPATH                        no        Local URI to use for serving payload
FETCH_WRITABLE_DIR  /tmp             yes       Remote writable dir to store payload; cannot contain spaces.
LHOST                                yes       The listen address (an interface may be specified)
LPORT               4444             yes       The listen port

Description:
  Fetch and Execute an x64 payload from an http server.

  Connect back to the attacker



View the full module info with the info -d command.

```

### CODE REVIEW

**Review by smcintyre-r7 — COMMENTED** [review]
Would you mind looking into adding a new keyword argument to `OptAddress` to provide this validation?

Something like this (untested hax):

```ruby
class OptAddress < OptBase
  def initialize(in_name, attrs = [], **kwargs)
    @routable = kwargs.fetch(:routable, false)
    super
  end

  def valid?(value, check_empty: true)
    if @routable
      # do the existing check using that logic.
    end

   ...
  end
end
```

cc @jmartin-r7

File: lib/msf/core/payload/adapter/fetch.rb [hunk 1]
```diff
@@ -7,7 +7,7 @@ def initialize(*args)
         Msf::OptBool.new('FETCH_DELETE', [true, 'Attempt to delete the binary after execution', false]),
         Msf::OptString.new('FETCH_FILENAME', [ false, 'Name to use on remote system when storing payload; cannot contain spaces.', Rex::Text.rand_text_alpha(rand(8..12))], regex:/^[\S]*$/),
         Msf::OptPort.new('FETCH_SRVPORT', [true, 'Local port to use for serving payload', 8080]),
-        Msf::OptAddressLocal.new('FETCH_SRVHOST', [ true, 'Local IP to use for serving payload', "0.0.0.0"]),
+        Msf::OptAddressRoutable.new('FETCH_SRVHOST', [ true, 'Local IP to use for serving payload', "0.0.0.0"]),
```
Comment (dwelch-r7) [inline lib/msf/core/payload/adapter/fetch.rb:10]:
```suggestion
        Msf::OptAddressRoutable.new('FETCH_SRVHOST', [ true, 'Local IP to use for serving payload']),
```
I don't think it's valid to default this to 0.0.0.0 any more right?

Comment (jmartin-r7) [reply lib/msf/core/payload/adapter/fetch.rb:10]: Agree, no default is likely a good change, it would be nice to default to the last used routable address but that likely a significant add.

**Comment by jheysel-r7** [comment]
Before:
```
msf6 > use cmd/linux/http/x64/meterpreter/reverse_tcp
msf6 payload(cmd/linux/http/x64/meterpreter/reverse_tcp) > info
[-] Error while running command info: You must set FETCH_SRVHOST to a routable IP

Call stack:
/Users/jheysel/rapid7/metasploit-framework/lib/msf/core/payload/adapter/fetch.rb:35:in `check_srvhost'
/Users/jheysel/rapid7/metasploit-framework/lib/msf/core/payload/adapter/fetch.rb:89:in `generate'
/Users/jheysel/rapid7/metasploit-framework/lib/msf/core/payload.rb:195:in `size'
/Users/jheysel/rapid7/metasploit-framework/lib/msf/base/serializer/readable_text.rb:500:in `dump_payload_module'
/Users/jheysel/rapid7/metasploit-framework/lib/msf/base/serializer/readable_text.rb:26:in `dump_module'
/Users/jheysel/rapid7/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:135:in `print_module_info'
/Users/jheysel/rapid7/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:159:in `cmd_info'
/Users/jheysel/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/Users/jheysel/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/Users/jheysel/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/Users/jheysel/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/Users/jheysel/rapid7/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
/Users/jheysel/rapid7/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/jheysel/rapid7/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
msf6 payload(cmd/linux/http/x64/meterpreter/reverse_tcp) >
```

After:
```
msf6 > use cmd/linux/http/x64/meterpreter/reverse_tcp
msf6 payload(cmd/linux/http/x64/meterpreter/reverse_tcp) > info

       Name: HTTP Fetch, Reverse TCP Stager
     Module: payload/cmd/linux/http/x64/meterpreter/reverse_tcp
   Platform: Linux, Linux
       Arch: cmd
Needs Admin: No
 Total size: 108
       Rank: Normal

Provided by:
  Brendan Watters
  Brent Cook <bcook@rapid7.com>
  ricky
  tkmru

Basic options:
Name                Current Setting  Required  Description
----                ---------------  --------  -----------
FETCH_COMMAND       CURL             yes       Command to fetch payload (Accepted: CURL, FTP, TFTP, TNFTP, WGET)
FETCH_DELETE        false            yes       Attempt to delete the binary after execution
FETCH_FILENAME      FtHPjcNJTDm      no        Name to use on remote system when storing payload; cannot contain spaces.
FETCH_SRVHOST                        yes       Local IP to use for serving payload
FETCH_SRVPORT       8080             yes       Local port to use for serving payload
FETCH_URIPATH                        no        Local URI to use for serving payload
FETCH_WRITABLE_DIR  /tmp             yes       Remote writable dir to store payload; cannot contain spaces.
LHOST                                yes       The listen address (an interface may be specified)
LPORT               4444             yes       The listen port

Description:
  Fetch and execute an x64 payload from an HTTP server.
  Connect back to the attacker



View the full module info with the info -d command.
```
Looks good 🚀
