### PR TITLE
Ensure msfdb reinit can be used for starting the database

### LINKED ISSUE #15317: Database not connected
## Steps to reproduce

How'd you do it?

1. I rant he command `msfconsole`
2. I got the error `No local database connected, meaning some Metasploit features will not be available. A full list of the affected features & database setup instructions can be found here: https://github.com/rapid7/metasploit-framework/wiki/msfdb:-Database-Features-&-How-to-Set-up-a-Database-for-Metasploit`
3. I ran `db_status` and received `db_status [*] postgresql selected, no connection`
4. I then ran 1msfdb init` and received the below output
```
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/static.rb:111: warning: The called method `initialize' is defined here
====================================================================
Running the 'init' command for the database:
Found a database at /Users/MyUserName/.msf4/db, checking to see if it is started
Database already started at /Users/MyUserName/.msf4/db
Creating initial database schema
====================================================================

====================================================================
Running the 'init' command for the webservice:
MSF web service is already running as PID 16013
====================================================================
```
5. I tried reinstalling MSF and that didn't fix it either
6. I ran msfupdate as well and that did not fix it either
7. I tried running ` db_connect -y ~/.msf4/database.yml` and that didnt work either

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.
`Darwin HQSML-1689616 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`

## Were you following a specific guide/tutorial or reading documentation?
i followed 

If yes link the guide/tutorial or documentation you were following here, otherwise you may omit this section.
* https://www.offensive-security.com/metasploit-unleashed/using-databases/
* https://docs.rapid7.com/metasploit/managing-the-database/
* https://www.offensive-security.com/metasploit-unleashed/database-introduction/
* https://github.com/rapid7/metasploit-framework/issues/11139
* https://sourabhbajaj.com/mac-setup/PostgreSQL/

## Expected behavior

What should happen?
i should be able to run the hosts, services, and whatever else uses the db
## Current behavior

What happens instead?
I get the no connection error (reported above)
### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).
I am running this version 
```
245baf20389c898088e1845851f47030cf2b001a automatic module_metadata_base.json update
Framework: 6.0.48-dev-4bf4b5a2fcd4f9cbcc57bf62b8624f190fb802f4
Console  : 6.0.48-dev-4bf4b5a2fcd4f9cbcc57bf62b8624f190fb802f4
```

## Additional Information
If your version is less than `5.0.96`, please update to the latest version and ensure your issue is still present.

If the issue is encountered within `msfconsole`, please run the `debug` command using the instructions below. If the issue is encountered outisde `msfconsole`, or the issue causes `msfconsole` to crash on startup, please delete this section.

1. Start `msfconsole`
2. Run the command `set loglevel 3`
3. Take the steps necessary recreate your issue
4. Run the `debug` command
5. Copy all the output below the `===8<=== CUT AND PASTE EVERYTHING BELOW THIS LINE ===8<===` line and make sure to **REMOVE ANY SENSITIVE INFORMATION.**
===8<=== CUT AND PASTE EVERYTHING BELOW THIS LINE ===8<===

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/database]
default_db=local-https-data-service

[framework/database/local-https-data-service]
url=[Filtered]
cert=[Filtered]
skip_verify=[Filtered]
api_token=[Filtered]

[framework/features]

[framework/ui/console]
ActiveModule=auxiliary/scanner/ssh/ssh_login_pubkey

[scanner/ssh/ssh_login_pubkey]
WORKSPACE=
VERBOSE=true
USERNAME=REDACTED
USER_FILE=REDACTED
BRUTEFORCE_SPEED=5
DB_ALL_CREDS=false
DB_ALL_USERS=false
DB_ALL_PASS=false
STOP_ON_SUCCESS=false
REMOVE_USER_FILE=false
REMOVE_PASS_FILE=false
REMOVE_USERPASS_FILE=false
TRANSITION_DELAY=0
MaxGuessesPerService=0
MaxMinutesPerService=0
MaxGuessesPerUser=0
CreateSession=true
InitialAutoRunScript=
AutoRunScript=
CommandShellCleanupCommand=
AutoVerifySession=true
RHOSTS=REDACTED
THREADS=10
ShowProgress=true
ShowProgressPercent=10
RPORT=22
SSH_IDENT=SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
SSH_TIMEOUT=30
SSH_DEBUG=false
KEY_PATH=./
KEY_PASS=REDACTED
PRIVATE_KEY=
Proxies=
SSH_KEYFILE_B64=
GatherProof=true
password=REDACTED
loglevel=3
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
1085   db_status
1086   db_status | pbcopy
1087   msfdb init
1088   db_rebuild_cache
1089   msfdb reinit
1090   db_status
1091   host -l
1092   services -l
1093   git log -1 --pretty=oneline
1094   git log -1 --pretty=oneline | pbcopy
1095   version
1096   set loglevel 3
1097   debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[06/08/2021 17:56:49] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[06/08/2021 17:56:49] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:04:46] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[06/08/2021 18:04:46] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:16:10] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[06/08/2021 18:16:10] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:24:07] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[06/08/2021 18:24:07] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:54:19] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[06/08/2021 18:54:19] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
No matching patterns were found in msf-ws.log.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
from /opt/metasploit-framework/embedded/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'

[06/08/2021 14:26:19] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/dos/smb/smb_loris.rb failed to load - LoadError  Try running file manually to check for errors or dependency issues.
[06/08/2021 16:01:40] [i(0)] core: Default data service found. Attempting to connect...
[06/08/2021 16:01:41] [d(0)] core: Updated user based module store
[06/08/2021 16:01:46] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/08/2021 17:56:49] [i(0)] core: Default data service found. Attempting to connect...
[06/08/2021 17:56:49] [i(0)] core: Trying to continue despite failed database creation: FATAL:  password authentication failed for user "msf"

[06/08/2021 17:56:49] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[06/08/2021 17:56:49] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[06/08/2021 17:56:56] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/08/2021 17:59:17] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[06/08/2021 18:04:45] [i(0)] core: Default data service found. Attempting to connect...
[06/08/2021 18:04:46] [i(0)] core: Trying to continue despite failed database creation: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:04:46] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[06/08/2021 18:04:46] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:04:50] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/08/2021 18:09:32] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[06/08/2021 18:16:10] [i(0)] core: Default data service found. Attempting to connect...
[06/08/2021 18:16:10] [i(0)] core: Trying to continue despite failed database creation: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:16:10] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[06/08/2021 18:16:10] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:16:13] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/08/2021 18:18:14] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[06/08/2021 18:24:06] [i(0)] core: Default data service found. Attempting to connect...
[06/08/2021 18:24:07] [i(0)] core: Trying to continue despite failed database creation: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:24:07] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[06/08/2021 18:24:07] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:24:11] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/08/2021 18:54:11] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[06/08/2021 18:54:19] [i(0)] core: Default data service found. Attempting to connect...
[06/08/2021 18:54:19] [i(0)] core: Trying to continue despite failed database creation: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:54:19] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[06/08/2021 18:54:19] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[06/08/2021 18:54:23] [d(0)] core: HistoryManager.push_context name: :msfconsole
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `new'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:413:in `with_connection'
	/opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/user.rb:10:in `users'
	/opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/metasploit_api_app.rb:44:in `block in <class:MetasploitApiApp>'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1000:in `block in filter!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:999:in `each'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:999:in `filter!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1126:in `block in dispatch!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:53:in `process'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:87:in `start'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
	/opt/metasploit-framework/embedded/bin/thin:23:in `load'
	/opt/metasploit-framework/embedded/bin/thin:23:in `<main>'
2021-06-08 19:05:53 -0400 Exiting!
2021-06-08 19:06:04 -0400 Writing PID to /Users/MyUserName/.msf4/msf-ws.pid
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/static.rb:111: warning: The called method `initialize' is defined here
2021-06-08 19:06:07 -0400 Thin web server (v1.8.1 codename Infinite Smoothie)
2021-06-08 19:06:07 -0400 Maximum connections set to 1024
2021-06-08 19:06:07 -0400 Listening on localhost:5443, CTRL+C to stop
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
2021-06-08 19:06:10 - PG::ConnectionBad - FATAL:  password authentication failed for user "msf"
:
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `new'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:413:in `with_connection'
	/opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/user.rb:10:in `users'
	/opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/metasploit_api_app.rb:44:in `block in <class:MetasploitApiApp>'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1000:in `block in filter!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:999:in `each'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:999:in `filter!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1126:in `block in dispatch!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:53:in `process'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:87:in `start'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
	/opt/metasploit-framework/embedded/bin/thin:23:in `load'
	/opt/metasploit-framework/embedded/bin/thin:23:in `<main>'
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.0.48-dev-4bf4b5a2fcd4f9cbcc57bf62b8624f190fb802f4
Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin15]
Install Root: /opt/metasploit-framework/embedded/framework
Session Type: postgresql selected, no connection
Install Method: Omnibus Installer
```

</details>

### PR DESCRIPTION
**Pull request by adfoster-r7**
closes https://github.com/rapid7/metasploit-framework/issues/15317

## Verification

Ensure that on master the following commands change the password:
```
bundle exec ruby ./msfdb reinit
# Verify the password and database works:
cat ~/.msf4/config; bundle exec msfconsole -qx ‘db_status’

bundle exec ruby ./msfdb stop
bundle exec ruby ./msfdb init # This should only _start_ the database, currently it generates new password

# Now verify the password is the same and database access works:
    cat ~/.msf4/config; bundle exec msfconsole -qx ‘db_status’
```

Test the following commands on mac + linux:
```
bundle exec ruby ./msfdb reinit 
bundle exec ruby ./msfdb start
bundle exec ruby ./msfdb stop
bundle exec ruby ./msfdb delete
bundle exec ruby ./msfdb init
```

Testing docker

Run docker
> docker run --rm -p 6000:5432 -e POSTGRES_PASSWORD=mysecretpassword postgres:13.1

Testing:
```
bundle exec ruby ./msfdb reinit --connection-string=postgresql://postgres:mysecretpassword@localhost:6000/postgres
bundle exec ruby ./msfdb start --connection-string=postgresql://postgres:mysecretpassword@localhost:6000/postgres
bundle exec ruby ./msfdb stop --connection-string=postgresql://postgres:mysecretpassword@localhost:6000/postgres
bundle exec ruby ./msfdb delete --connection-string=postgresql://postgres:mysecretpassword@localhost:6000/postgres
bundle exec ruby ./msfdb init --connection-string=postgresql://postgres:mysecretpassword@localhost:6000/postgres
```

### CODE REVIEW

**Comment by dwelch-r7** [comment]
This looks good to me, the only thing I thought I'd mention is that when you run `init` as a way just to start the db (or if the db is already started) it prompts you to ask 
`[?] Would you like to delete your existing data and configurations? []:`
but it won't actually delete anything, which is the correct functionality it's just a little odd that it would ask
image
You can seein the screenshot how it prompted, I said yes and then the config remained the same

File: lib/msfdb_helpers/db_interface.rb [hunk 1]
```diff
@@ -13,10 +13,6 @@ def delete
       raise NotImplementedError
     end
 
-    def reinit
-      raise NotImplementedError
-    end
-
```
Comment (adfoster-r7) [inline lib/msfdb_helpers/db_interface.rb:19]: Removed `reinit` as it seemed like logic that needed to exist in msfdb, rather than in these helpers

File: lib/msfdb_helpers/pg_ctl.rb [hunk 2]
```diff
@@ -12,21 +12,6 @@ def initialize(db_path:, options:, localconf:, db_conf:)
...
-
-      if File.exist?(@db_conf) && !@options[:delete_existing_data]
-        if !load_db_config
-          puts 'Failed to load existing database config. Please reinit and overwrite the file.'
-          return
-        end
-      else
-        write_db_config
-      end
-
```
Comment (adfoster-r7) [inline lib/msfdb_helpers/pg_ctl.rb:29]: This preamble now exists in the msfdb orchestration

**Comment by dwelch-r7** [comment]
# Release Notes

Fixes an issue where running `msfdb init` on an already initialised database would generate a new password instead of just starting the database
