### PR TITLE
fix nil check in atutor module

### LINKED ISSUE #12357: Exploit failed: NoMethodError undefined method `body' for nil:NilClass
## Steps to reproduce

How'd you do it?

1. use exploit/multi/http/atutor_sqli
2. set targeturi /Atutor/
3. set rhost insert_remote_ip_address_here
4. set rport 80
5. exploit

Tested against a remote Ubuntu machine.
Verbose option was on.

## Expected behavior

The exploit should run and show me the hashes.

## Current behavior

What happens instead?

[*] insert_remote_ip_address_here:80 - Dumping the username and password hash...
[+] insert_remote_ip_address_here:80 - Got the 's hash:  !
[-] insert_remote_ip_address_here:80 - Exploit failed: NoMethodError undefined method `body' for nil:NilClass
[*] Exploit completed, but no session was created.

### Metasploit version

Framework: 4.17.80-dev
Console  : 4.17.80-dev
Pro      : 4.16.0-2019091001

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [X] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Windows x64, but I also have it on Ubuntu Windows Subsystem.

### PR DESCRIPTION
**Pull request by h00die**
Fixes #12357 

This fixes the `nil` to return a string.  However, there are unknown consequences later on in the code for doing such.  @SelfLeaker can you please verify that this fixes the issue and doesn't make the module do something crazy?  May need to just bail out of the module instead of passing back an empty string (which is my hunch).

## Verification

- [ ] Start `msfconsole`
- [ ] use exploit/multi/http/atutor_sqli
- [ ] set targeturi /Atutor/
- [ ] set rhost insert_remote_ip_address_here
- [ ] set rport 80
- [ ] exploit
- [ ] you don't see `Exploit failed: NoMethodError undefined method 'body' for nil:NilClass`

### CODE REVIEW

File: modules/exploits/multi/http/atutor_sqli.rb [hunk 1]
```diff
@@ -157,7 +157,10 @@ def perform_request(sqli)
         'search' => 'Search'
       },
     })
-    return res.body
+    if res.nil?
```
Comment (wvu-r7) [inline modules/exploits/multi/http/atutor_sqli.rb]: I think a guard clause would be better here. Alternatively, you could use `res ? res.body : ''`.

**Review by ThiagoAlexsander — COMMENTED** [review]
The response code is always 404 for the target i was testing and the "check" command returns "this target is not exploitable.", so ... i guess it doesn't work? I just got curious with this exploit because it showed a yellow message saying "Got the hash" when i was testing the exploits so I thought it worked and the exploit was broken.

**Comment by h00die** [comment]
There is a 2nd issue here that is causing the nil string issue:
```
msf5 exploit(multi/http/atutor_sqli) > rexploit
[*] Reloading module...

[*] Started reverse TCP handler on 1.1.1.1:4444
[*] 2.2.2.2:80 - Dumping the username and password hash...
[-] 2.2.2.2:80 - The host (2.2.2.2:80) was unreachable.
[-] 2.2.2.2:80 - The host (2.2.2.2:80) was unreachable.
[-] 2.2.2.2:80 - The host (2.2.2.2:80) was unreachable.
[-] 2.2.2.2:80 - The host (2.2.2.2:80) was unreachable.
[-] 2.2.2.2:80 - The host (2.2.2.2:80) was unreachable.
[-] 2.2.2.2:80 - The host (2.2.2.2:80) was unreachable.
[-] 2.2.2.2:80 - The host (2.2.2.2:80) was unreachable.
[-] 2.2.2.2:80 - The host (2.2.2.2:80) was unreachable.
[+] 2.2.2.2:80 - Got the 's hash:  !
[-] 2.2.2.2:80 - Exploit failed: TypeError no implicit conversion of nil into String
[*] Exploit completed, but no session was created.
```

The code isn't bailing properly on a non-vuln case.  This will be handled in the next commit.

File: modules/exploits/multi/http/atutor_sqli.rb (hunk 1 above)
Comment (h00die) [reply modules/exploits/multi/http/atutor_sqli.rb]: Originally I wrote it as a ternary, but in python syntax.  Then I had a @bcoles conversation with myself and said 'exit early and often' and re-wrote it.  Prior to reading this, I decided ternary would be better since its one line instead of 4, thus most likely a better choice.  Glad my thinking was on the right path!

Comment (wvu-r7) [reply modules/exploits/multi/http/atutor_sqli.rb]:
```ruby
return unless res

res.body
```

This would be the Ruby approach. Really, it's two/three lines. I'm fine with either.

File: modules/exploits/multi/http/atutor_sqli.rb [hunk 2]
```diff
@@ -234,7 +234,7 @@ def service_details
   def exploit
     print_status("Dumping the username and password hash...")
     credz = dump_the_hash
-    if credz
+    if credz && credz != []
```
Comment (bcoles) [inline modules/exploits/multi/http/atutor_sqli.rb]:
```suggestion
    if credz && !credz.empty?
```

Also, given that there's no point continuing if this conditional fails, the module could `return` here.

```ruby
return unless credz
return if credz.empty?
```

However, the module does not `print_` anywhere else, and it only uses `fail_with` in the methods used later (`login` and `upload_shell`)... so, in the event that dumping the hash fails, the module will effectively just die with no feedback after `Dumping the username and password hash...`

A more user friendly approach would be:

```ruby
if credz.nil? || credz.empty?
  fail_with(NotVulnerable, 'Failed to retrieve username and password hash')
end
```

Comment (h00die) [reply modules/exploits/multi/http/atutor_sqli.rb]: I like these suggestions, thanks for the input.  I'll implement in a few days

**Review by bcoles — APPROVED** [review]
Untested, but LGTM

**Comment by space-r7** [comment]
Changes look good to me.

Tested with nil values:

```
msf5 exploit(multi/http/atutor_sqli) > run

[*] Started reverse TCP handler on 192.168.37.1:4444 
[*] 192.168.37.231:80 - Dumping the username and password hash...
[-] 192.168.37.231:80 - Exploit aborted due to failure: not-vulnerable: Failed to retrieve username and password hash
[*] Exploit completed, but no session was created.
```

**Comment by space-r7** [comment]
## Release Notes

This fixes a `nil` error in the Atutor SQLi exploit module.
