### PR TITLE
Fix uri escape in rex request for reverse http/https meterpreter shells

### LINKED ISSUE #13294: bombardment of warning: URI.unescape is obsolete on terminal
## Steps to reproduce

How'd you do it?

1. Created new session using "exploit"
2. Session is created
  

This section should also tell us any relevant information about the
environment; for example, if an exploit that used to work is failing,
tell us the victim operating system and service versions.

## Expected behavior
 Session should be created without lot of warnings 

## Current behavior
Terminal output is filled with 
"/opt/metasploit/lib/rex/proto/http/request.rb:79: warning: URI.unescape is obsolete"
warrings 

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

## System stuff

blackarch installation
Ruby version : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

### Metasploit version
Framework: 5.0.83-dev
Console  : 5.0.83-dev

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
black arch installation
Ruby version : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

### OS

What OS are you running Metasploit on?
Blackarch

Screenshot_20200420_143524

### LINKED ISSUE #13356: URI.unescape is obsolete warning while using exploit
## Steps to reproduce

While connecting to the victim machine in a **client-side attack** after ensuring that the victim runs the payload:

1. Used the multi-handler exploit module
2. set PAYLOAD to windows reverse_https 
3. set the appropriate LHOST and LPORT.
4. launched the exploit

LHOST:
OS : Kali Linux 2020.2

VICTIM:
OS : Windows 10 Home

## Expected behavior

Expected to be logged into the Victim's machine via the meterpreter.

## Current behavior

MSF bombards the terminal with a warning

_warning :_ _URI.unescape is obsolete_
Screenshot_2020-04-28_15-17-57

### Metasploit version

metasploit v5.0.86-dev

### I installed Metasploit with:
Kali package via apt

### OS

Kali Linux 2020.2

### PR DESCRIPTION
**Pull request by adfoster-r7**
Fixes deprecation warnings on Ruby 2.7 when using a a reverse http/https meterpreter shell:

image

There are more deprecations in the codebase to fix, but I'll review them individually in a future pull request. For now the main reported problem is reverse http/https meterpreter shells.

## Verification

Test with both Ruby 2.7 and Ruby 2.6

- [x] Start `msfconsole`
- [x] Set up a reverse http meterpereter session, for example on mac:
```
use payload/osx/x64/meterpreter_reverse_https
set LHOST 127.0.0.1
set LPORT 4445
set SessionCommunicationTimeout 0
set ExitOnSession false

generate -o reverse_shell -f macho

to_handler
```
- [x] Open a new tab, run the `reverse_shell`
- [x] **Verify** that there is no longer any warning messages
- [ ] **Verify** that other calls to the rex requests do not break

### CODE REVIEW

File: lib/rex/proto/http/request.rb [hunk 1]
```diff
@@ -76,7 +76,7 @@ def initialize(method = 'GET', uri = '/', proto = DefaultProtocol)
   def update_cmd_parts(str)
     if (md = str.match(/^(.+?)\s+(.+?)\s+HTTP\/(.+?)\r?\n?$/i))
       self.method  = md[1]
-      self.raw_uri = URI.decode(md[2])
+      self.raw_uri = CGI.unescape(md[2])
```
Comment (adfoster-r7) [inline lib/rex/proto/http/request.rb:79]: For the meterpreter session, the value of `str` was:

```
GET /lDpvTKraKaE8XjVcYvfzTASDnGgNNa1FGjqDq25ruwMs7EKq9n8wxPt-va5Izarzo1Y42Xrw2h1ObE_suZuQHC78OSC5/ HTTP/1.1'
```

**Comment by gwillcox-r7** [comment]
Ruby 2.6 seems to be working fine:

```
$ git checkout land-pr13363 
Switched to branch 'land-pr13363'
Your branch is up to date with 'upstream/pr/13363'.
$ cat .ruby-version 
2.6.6
$ ruby --version
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
$ ./msfconsole
                                                  
               .;lxO0KXXXK0Oxl:.
           ,o0WMMMMMMMMMMMMMMMMMMKd,
        'xNMMMMMMMMMMMMMMMMMMMMMMMMMWx,
      :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:
    .KMMMMMMMMMMMMMMMWNNNWMMMMMMMMMMMMMMMX,
   lWMMMMMMMMMMMXd:..     ..;dKMMMMMMMMMMMMo
  xMMMMMMMMMMWd.               .oNMMMMMMMMMMk
 oMMMMMMMMMMx.                    dMMMMMMMMMMx
.WMMMMMMMMM:                       :MMMMMMMMMM,
xMMMMMMMMMo                         lMMMMMMMMMO
NMMMMMMMMW                    ,cccccoMMMMMMMMMWlccccc;
MMMMMMMMMX                     ;KMMMMMMMMMMMMMMMMMMX:
NMMMMMMMMW.                      ;KMMMMMMMMMMMMMMX:
xMMMMMMMMMd                        ,0MMMMMMMMMMK;
.WMMMMMMMMMc                         'OMMMMMM0,
 lMMMMMMMMMMk.                         .kMMO'
  dMMMMMMMMMMWd'                         ..
   cWMMMMMMMMMMMNxc'.                ##########
    .0MMMMMMMMMMMMMMMMWc            #+#    #+#
      ;0MMMMMMMMMMMMMMMo.          +:+
        .dNMMMMMMMMMMMMo          +#++:++#+
           'oOWMMMMMMMMo                +:+
               .,cdkO0K;        :+:    :+:                                
                                :::::::+:
                      Metasploit

       =[ metasploit v5.0.87-dev-fb3c953ff7               ]
+ -- --=[ 2006 exploits - 1095 auxiliary - 343 post       ]
+ -- --=[ 562 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 7 evasion                                       ]

Metasploit tip: You can upgrade a shell to a Meterpreter session on many platforms using sessions -u <session_id>

msf5 > use payload/osx/x64/meterpreter_reverse_https
msf5 payload(osx/x64/meterpreter_reverse_https) > set LHOST 127.0.0.1
LHOST => 127.0.0.1
msf5 payload(osx/x64/meterpreter_reverse_https) > set LPORT 4445
LPORT => 4445
msf5 payload(osx/x64/meterpreter_reverse_https) > set SessionCommunicationTimeout 0
SessionCommunicationTimeout => 0
msf5 payload(osx/x64/meterpreter_reverse_https) > set ExitOnSession false
ExitOnSession => false
msf5 payload(osx/x64/meterpreter_reverse_https) > generate -o reverse_shell -f macho
[*] Writing 804084 bytes to reverse_shell...
msf5 payload(osx/x64/meterpreter_reverse_https) > to_handler
[*] Payload Handler Started as Job 0

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
msf5 payload(osx/x64/meterpreter_reverse_https) > [*] Started HTTPS reverse handler on https://127.0.0.1:4445
msf5 payload(osx/x64/meterpreter_reverse_https) > [*] https://127.0.0.1:4445 handling request from 127.0.0.1; (UUID: uesmysa2) Redirecting stageless connection from /qX8vJPGTEPWVTpxMy-dxQQ0v2ixiDMOi16vwTIACJI8Y1m9uieas2cD3OZUirsPbyMnI6LA1Z with UA 'Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko'
[*] https://127.0.0.1:4445 handling request from 127.0.0.1; (UUID: uesmysa2) Redirecting stageless connection from /qX8vJPGTEPWVTpxMy-dxQQ_fT5cm2KhcCaiLYDHGNn3n9kAWcR-mBN-zZwc4KLRl with UA 'Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko'
[*] https://127.0.0.1:4445 handling request from 127.0.0.1; (UUID: uesmysa2) Attaching orphaned/stageless session...
[*] Meterpreter session 1 opened (127.0.0.1:4445 -> 127.0.0.1:54999) at 2020-04-29 15:31:12 -0500

msf5 payload(osx/x64/meterpreter_reverse_https) > exit
[*] You have active sessions open, to exit anyway type "exit -y"
msf5 payload(osx/x64/meterpreter_reverse_https) > sessions -K
[*] Killing all sessions...

[*] 127.0.0.1 - Meterpreter session 1 closed.
msf5 payload(osx/x64/meterpreter_reverse_https) > 
msf5 payload(osx/x64/meterpreter_reverse_https) > exit
$
```

**Comment by gwillcox-r7** [comment]
Ruby 2.7.1 seems to be working. Does appear to be slower than Ruby 2.6.6 during my tests though? Otherwise tests working fine:

```
$ cat .ruby-version 
2.7.1
$ ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
$ ./msfconsole
                                                  
                                   ___          ____
                               ,-""   `.      < HONK >
                             ,'  _   e )`-._ /  ----
                            /  ,' `-._<.===-'
                           /  /
                          /  ;
              _          /   ;
 (`._    _.-"" ""--..__,'    |
 <_  `-""                     \
  <`-                          :
   (__   <__.                  ;
     `-.   '-.__.      _.'    /
        \      `-.__,-'    _,'
         `._    ,    /__,-'
            ""._\__,'< <____
                 | |  `----.`.
                 | |        \ `.
                 ; |___      \-``
                 \   --<
                  `.`.<
                    `-'



       =[ metasploit v5.0.87-dev-fb3c953ff7               ]
+ -- --=[ 2006 exploits - 1095 auxiliary - 343 post       ]
+ -- --=[ 562 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 7 evasion                                       ]

Metasploit tip: Enable verbose logging with set VERBOSE true

msf5 > use payload/osx/x64/meterpreter_reverse_https
msf5 payload(osx/x64/meterpreter_reverse_https) > set LHOST 127.0.0.1
LHOST => 127.0.0.1
msf5 payload(osx/x64/meterpreter_reverse_https) > set LPORT 4445
LPORT => 4445
msf5 payload(osx/x64/meterpreter_reverse_https) > set SessionCommunicationTimeout 0
SessionCommunicationTimeout => 0
msf5 payload(osx/x64/meterpreter_reverse_https) > set ExitOnSession false
ExitOnSession => false
msf5 payload(osx/x64/meterpreter_reverse_https) > generate -o reverse_shell2 -f macho
[*] Writing 804084 bytes to reverse_shell2...
msf5 payload(osx/x64/meterpreter_reverse_https) > to_handler
[*] Payload Handler Started as Job 0

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
msf5 payload(osx/x64/meterpreter_reverse_https) > [*] Started HTTPS reverse handler on https://127.0.0.1:4445
[*] https://127.0.0.1:4445 handling request from 127.0.0.1; (UUID: gs8hpuq9) Redirecting stageless connection from /AW4v7Yxf0t4cwhXAQmv04wm1-5l_d4o3SqG0vOAQY with UA 'Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko'
[*] https://127.0.0.1:4445 handling request from 127.0.0.1; (UUID: gs8hpuq9) Attaching orphaned/stageless session...
[*] Meterpreter session 1 opened (127.0.0.1:4445 -> 127.0.0.1:55599) at 2020-04-29 15:48:33 -0500

msf5 payload(osx/x64/meterpreter_reverse_https) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > shell
Process 67573 created.
Channel 1 created.

pwd
/opt/rapid7/metasploit-framework
exit
meterpreter > exit
[*] Shutting down Meterpreter...


[*] 127.0.0.1 - Meterpreter session 1 closed.  Reason: User exit
msf5 payload(osx/x64/meterpreter_reverse_https) > 
msf5 payload(osx/x64/meterpreter_reverse_https) > exit
$ 
```

**Comment by gwillcox-r7** [comment]
Finished review on this @adfoster-r7 but still a bit confused on how `Verify that other calls to the rex requests do not break` was meant to be verified. Got any steps for testing this out?

File: lib/rex/proto/http/request.rb (hunk 1 above)
Comment (adfoster-r7) [reply lib/rex/proto/http/request.rb:79]: From the Ruby docs:

> **URI.unescape**
> This method is obsolete and should not be used. Instead, use CGI.unescape, URI.decode_www_form or URI.decode_www_form_component depending on your specific use case.

CGI and URI decode are not semantically equivalent, but in the above scenario that's not an issue. I don't have full context on all the scenarios this `cmd_parts` functionality would be used, before I go code diving it would be worth a second set of eyes here :eyes:

Comment (gwillcox-r7) [reply lib/rex/proto/http/request.rb:79]: After further discussion with the team this morning, we have confirmed that this should work fine, with a potential low to medium risk of breaking things. We will merge this in with the idea to monitor this to see if anything does indeed break.

**Comment by gwillcox-r7** [comment]
As per last comments, we are clear to merge this in after approval from discussions this morning. Will need to keep an eye out just in case this breaks anything but if it does break it should only be on edge cases. Going to merge this in now.

**Comment by gwillcox-r7** [comment]
# Release Notes
This PR fixes up a depreciation error that was occurring when generating the HTTP and HTTPS Meterpreter shells using Ruby 2.7.x by replacing a <code>URI.decode</code> call with a <code>CGI.unescape</code> call.

**Comment by etcpwd13** [comment]
Had the same issue with running "auxiliary/scanner/http/crawler" 
Linux kali 5.9.0-kali5-amd64 #1 SMP Debian 5.9.15-1kali1 (2020-12-18) x86_64 GNU/Linux
Metasploit 6.0.25-dev
ruby 2.7.2
The error for "URI.unescape is obsolete" was thrown by this file - "/usr/share/metasploit-framework/lib/anemone/page.rb" on line 178 of the file. 

The manual fix was to edit the file and replace URI.encode with CGI.unescape
