### PR TITLE
resolved #7645 where dolibarr_login module crashed

### LINKED ISSUE #7645: module scanner/http/dolibarr_login causes a stack trace
## Steps to reproduce

How'd you do it?

1. `run auxiliary/scanner/http/dolibarr_login`
2. `set RHOSTS 127.0.0.1`
3.  `run`
```
msf auxiliary(dolibarr_login) > run

[*] Trying "connect:connect"
[-] Auxiliary failed: NameError undefined local variable or method `get_cookies' for #<Msf::Modules::Mod617578696c696172792f7363616e6e65722f687474702f646f6c69626172725f6c6f67696e::MetasploitModule:0x00000009798cc8>
Did you mean?  get_client
[-] Call stack:
[-]   /home/jqian/rapid7/metasploit-framework/modules/auxiliary/scanner/http/dolibarr_login.rb:49:in `get_sid_token'
[-]   /home/jqian/rapid7/metasploit-framework/modules/auxiliary/scanner/http/dolibarr_login.rb:91:in `do_login'
[-]   /home/jqian/rapid7/metasploit-framework/modules/auxiliary/scanner/http/dolibarr_login.rb:147:in `block in run_host'
[-]   /home/jqian/rapid7/metasploit-framework/lib/msf/core/auxiliary/auth_brute.rb:197:in `block in each_user_pass'
[-]   /home/jqian/rapid7/metasploit-framework/lib/msf/core/auxiliary/auth_brute.rb:178:in `each'
[-]   /home/jqian/rapid7/metasploit-framework/lib/msf/core/auxiliary/auth_brute.rb:178:in `each_user_pass'
[-]   /home/jqian/rapid7/metasploit-framework/modules/auxiliary/scanner/http/dolibarr_login.rb:145:in `run_host'
[-]   /home/jqian/rapid7/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /home/jqian/rapid7/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

### Metasploit version
```
msf auxiliary(dolibarr_login) > version
Framework: 4.13.3-dev-b6bb199
Console  : 4.13.3-dev-b6bb199
```

### OS

ubuntu 14.04

### PR DESCRIPTION
**Pull request by jinq102030**
Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/http/dolibarr_login`
- [x] `set RHOSTS 127.0.0.1`
- [x] `run`
lots of output like:
```
[-] Bad login: "xampp-dav-unsecure:wampp"
[*] Trying "xampp-dav-unsecure:turnkey"
[*] Using sessiond ID: DOLSESSID_G=1234
[*] Using token: 567789
[-] Bad login: "xampp-dav-unsecure:turnkey"
[*] Trying "xampp-dav-unsecure:vagrant"
[*] Using sessiond ID: DOLSESSID_G=1234
[*] Using token: 567789
[-] Bad login: "xampp-dav-unsecure:vagrant"
[*] Trying "vagrant:admin"
[*] Using sessiond ID: DOLSESSID_G=1234
[*] Using token: 567789
[-] Bad login: "vagrant:admin"
[*] Trying "vagrant:password"
[*] Using sessiond ID: DOLSESSID_G=1234
[*] Using token: 567789
[-] Bad login: "vagrant:password"
[*] Trying "vagrant:manager"

```

closed #7645
Add "res" (http response) when trying to retrieve the cookie

### CODE REVIEW

**Comment by wvu-r7** [comment]
# Release Notes

This fixes ```auxiliary/scanner/http/dolibarr_login``` to properly use ```get_cookies```, allowing the module to fetch the session ID from the cookie. Previously, the module was calling the method without ```res```.

File: modules/auxiliary/scanner/http/dolibarr_login.rb [hunk 1]
```diff
@@ -46,7 +46,7 @@ def get_sid_token
     return [nil, nil] if res.nil? || res.get_cookies.empty?
 
     # Get the session ID from the cookie
-    m = get_cookies.match(/(DOLSESSID_.+);/)
+    m = res.get_cookies.match(/(DOLSESSID_.+);/)
```
Comment (jinq102030) [inline modules/auxiliary/scanner/http/dolibarr_login.rb]: Thanks @wvu-r7 for adding the release note and close the issue.
