### PR TITLE
fix #11158, fix multi line text in android send_sms

### LINKED ISSUE #11158: android/meterpreter/reverse_* send_sms need multi line
cannot send newline
fix plz

### PR DESCRIPTION
**Pull request by timwr**
Quick fix for https://github.com/rapid7/metasploit-framework/issues/11158

## Verification

- [x] Get an android meterpreter session
- [x] `meterpreter > send_sms -t "New\nLine" -d +5555`
- [x] **Verify** you receive a text with a new line in it

(Note: if you have a session on an Android emulator, you can send a text to yourself using the destination number +5555).

### CODE REVIEW

File: lib/rex/post/meterpreter/ui/console/command_dispatcher/android.rb [hunk 1]
```diff
@@ -527,6 +527,7 @@ def cmd_send_sms(*args)
         dest = val
       when '-t'
         body = val
+        body.gsub!('\n',"\n")
```
Comment (acammack-r7) [inline lib/rex/post/meterpreter/ui/console/command_dispatcher/android.rb]: This might need a comment explaining Ruby's quoting and escaping rules.

Comment (timwr) [reply lib/rex/post/meterpreter/ui/console/command_dispatcher/android.rb]: Good point, thanks!

**Comment by wchen-r7** [comment]
# Release Notes

This allows multi-line messages in Android SMS.
