### PR TITLE
Fixes validation for `to_handler` command for Evasion and Payload modules

### LINKED ISSUE #17935: Payload and Evasion modules don't validate the datastore with to_handler
The `to_handler` command available in payload modules does not validate the datastore options prior to starting the handler. This means if an option is missing, the user will still see a message indicating that the handler started successfully.

In the following scenario, the `LHOST` option is required. The `generate` command fails because `LHOST` failed to validate, but `to_hander` does not indicate any error.

```
msf6 payload(linux/x64/meterpreter/reverse_tcp) > show options 

Module options (payload/linux/x64/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


View the full module info with the info, or info -d command.

msf6 payload(linux/x64/meterpreter/reverse_tcp) > to_handler 
[*] Payload Handler Started as Job 
msf6 payload(linux/x64/meterpreter/reverse_tcp) > generate -f raw
[-] Payload generation failed: One or more options failed to validate: LHOST.
msf6 payload(linux/x64/meterpreter/reverse_tcp) > 
```

Evasion modules seem to suffer from the same issue. In this case, I'd again expect a failure because the required `LHOST` option is blank.

```
use evasion/windows/syscall_inject 
[*] Using configured payload windows/x64/meterpreter/reverse_tcp
msf6 evasion(windows/syscall_inject) > show options 

Module options (evasion/windows/syscall_inject):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   CIPHER    chacha           yes       Shellcode encryption type (Accepted: chacha, rc4)
   FILENAME  Xtr.exe          yes       Filename for the evasive file (default: random)
   SLEEP     20000            no        Sleep time in milliseconds before executing shellcode


Payload options (windows/x64/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST                      yes       The listen address (an interface may be specified)
   LPORT     4444             yes       The listen port


Evasion target:

   Id  Name
   --  ----
   0   Microsoft Windows (x64)



View the full module info with the info, or info -d command.

msf6 evasion(windows/syscall_inject) > to_handler 
[*] Payload Handler Started as Job 
msf6 evasion(windows/syscall_inject) > 
```

### PR DESCRIPTION
**Pull request by cgranleese-r7**
Fixes #17935

This PR fixes a validation issue that was present in the `to_handler` methods for both Payload and Evasion modules. More information can be found in the linked issue.

## Before
image

## After
image

## Verification
- [ ] Start `msfconsole`
- [ ] Use any payload e.g. `use linux/x64/meterpreter/reverse_tcp`
- [ ] Run `to_handler` while having no value set for `LHOST`
- [ ] **Verify** a suitable error is now returned
- [ ] Repeat the steps above for an Evasion module.

### CODE REVIEW

File: lib/msf/ui/console/command_dispatcher/evasion.rb [hunk 1]
```diff
@@ -91,10 +91,22 @@ def cmd_to_handler(*_args)
     }
 
     handler.share_datastore(mod.datastore)
-    handler.exploit_simple(handler_opts)
-    job_id = handler.job_id
 
-    print_status "Payload Handler Started as Job #{job_id}"
+    replicate_handler = nil
+    handler.exploit_simple(handler_opts) do |yielded_replicate_handler|
+      replicate_handler = yielded_replicate_handler
```
Comment (adfoster-r7) [inline lib/msf/ui/console/command_dispatcher/evasion.rb:97]:
```suggestion
    handler.exploit_simple(handler_opts) do |yielded_replicant_handler|
      replicant_handler = yielded_replicant_handler
```

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes validation for the `to_handler` command when running Evasion and Payload modules
