### PR TITLE
Fix broken ntlm message constants

### LINKED ISSUE #14611: Uninitialized constant error in scanner/rdp/cve_2019_0708_bluekeep
While running the cve_2019_0708_bluekeep scanner on a list of hosts with the following options:
```
set ShowProgressPercent 1; set threads 5; set verbose true;
```
I am presented with the following error for seemingly random hosts:

```
[-] <IP>:3389     - Unexpected error: uninitialized constant Msf::Exploit::Remote::RDP::NTLM_MESSAGE
/usr/share/metasploit-framework/lib/msf/core/exploit/remote/rdp.rb:205:in `rdp_fingerprint'
/usr/share/metasploit-framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:206:in `check_rdp_vuln'
/usr/share/metasploit-framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:98:in `check_host'
/usr/share/metasploit-framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:65:in `run_host'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:120:in `block (2 levels) in run'
/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'
```

I am running on kali and have just done an `apt full-upgrade`.

```
$ uname -a
Linux host 5.9.0-kali5-amd64 #1 SMP Debian 5.9.15-1kali1 (2020-12-18) x86_64 GNU/Linux
```

Any suggestions as to what I can try to troubleshoot?
Thanks!

### PR DESCRIPTION
**Pull request by adfoster-r7**
Fix broken ntlm message constants

Closes https://github.com/rapid7/metasploit-framework/issues/14611

### Before

An error is shown to the user:

```
[-] <IP>:3389     - Unexpected error: uninitialized constant Msf::Exploit::Remote::RDP::NTLM_MESSAGE
/usr/share/metasploit-framework/lib/msf/core/exploit/remote/rdp.rb:205:in `rdp_fingerprint'
/usr/share/metasploit-framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:206:in `check_rdp_vuln'
/usr/share/metasploit-framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:98:in `check_host'
/usr/share/metasploit-framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:65:in `run_host'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:120:in `block (2 levels) in run'
/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'
```

### After

The module works as expected:

```
msf6 auxiliary(scanner/rdp/cve_2019_0708_bluekeep) > run

[+] 10.10.39.203:3389     - The target is vulnerable. The target attempted cleanup of the incorrectly-bound MS_T120 channel.
[*] 10.10.39.203:3389     - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

## Verification

Target a windows machine which is vulnerable to bluekeep

```
use scanner/rdp/cve_2019_0708_bluekeep
set rhost 10.10.39.203
run
```

### CODE REVIEW

File: lib/msf/core.rb [hunk 1]
```diff
@@ -14,8 +14,15 @@
...
 require 'rex/ui'
 require 'rex/arch'
+
 include Rex::Arch
 
+NTLM_CONST   ||= ::Rex::Proto::NTLM::Constants
+NTLM_CRYPT   ||= ::Rex::Proto::NTLM::Crypt
+NTLM_UTILS   ||= ::Rex::Proto::NTLM::Utils
+NTLM_BASE    ||= ::Rex::Proto::NTLM::Base
+NTLM_MESSAGE ||= ::Rex::Proto::NTLM::Message
```
Comment (adfoster-r7) [inline lib/msf/core.rb:24]: In a future PR we'll nuke these aliases, as well as the `include Rex::Arch` approach too

**Comment by adfoster-r7** [comment]
## Release Notes

Fixes regression error with modules depending on NTLM such as cve_2019_0708_bluekeep

File: lib/msf/core.rb (hunk 1 above)
Comment (adfoster-r7) [reply lib/msf/core.rb:24]: This approach is an alternative, defining the aliases within a base class:

https://github.com/rapid7/metasploit-framework/blob/710ed31b75618af8ce0bdb19480a0a88871b0e69/lib/rex/proto/smb/client.rb#L21-L29
