### PR TITLE
apport_abrt_chroot_priv_esc: check if apport-cli is in $PATH

### LINKED ISSUE #15370: local_exploit_suggester: Post failed: ArgumentError Malformed version number string /bin/sh: apport
meterpreter > run post/multi/recon/local_exploit_suggester

[*] X - Collecting local exploits for x64/linux...
[*] X - 40 exploit checks are being tried...
[-] X - Post failed: ArgumentError Malformed version number string /bin/sh: apport
[-] X - Call stack:
[-] X -   /opt/metasploit-framework/embedded/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:215:in `initialize'
[-] X -   /opt/metasploit-framework/embedded/framework/lib/rex/version.rb:10:in `initialize'
[-] X -   /opt/metasploit-framework/embedded/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:204:in `new'
[-] X -   /opt/metasploit-framework/embedded/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:204:in `new'
[-] X -   /opt/metasploit-framework/embedded/framework/modules/exploits/linux/local/apport_abrt_chroot_priv_esc.rb:118:in `check'
[-] X -   /opt/metasploit-framework/embedded/framework/modules/post/multi/recon/local_exploit_suggester.rb:121:in `block in run'
[-] X -   /opt/metasploit-framework/embedded/framework/modules/post/multi/recon/local_exploit_suggester.rb:119:in `each'
[-] X -   /opt/metasploit-framework/embedded/framework/modules/post/multi/recon/local_exploit_suggester.rb:119:in `run'

_Originally posted by @sssseossss in https://github.com/rapid7/metasploit-framework/issues/12729#issuecomment-868410985_

### PR DESCRIPTION
**Pull request by bcoles**
Fixes #15370

### CODE REVIEW

File: modules/exploits/linux/local/apport_abrt_chroot_priv_esc.rb [hunk 1]
```diff
@@ -142,7 +145,7 @@ def upload_and_chmodx(path, data)
   end
 
   def exploit
-    if check != CheckCode::Appears
+    unless [ CheckCode::Detected, CheckCode::Appears ].include?(check)
```
Comment (smcintyre-r7) [inline modules/exploits/linux/local/apport_abrt_chroot_priv_esc.rb:148]: Instead of maintaining this list, this seems like a good opportunity to switch to using `prepend Msf::Exploit::Remote::AutoCheck`.

**Review by smcintyre-r7 — CHANGES_REQUESTED** [review]
I was able to reproduce the original issue on Ubuntu 20.10 workstation by moving the `apport-cli` binary outside of the PATH. I was also able to confirm the proposed changes fix the issue.

I just left one change request to use the new-ish `AutoCheck` mixin.

File: modules/exploits/linux/local/apport_abrt_chroot_priv_esc.rb (hunk 1 above)
Comment (bcoles) [reply modules/exploits/linux/local/apport_abrt_chroot_priv_esc.rb:148]: It would be, but that would involve ninja editing in changes. As too would changing all check codes to use the optional description instead of separate vprint methods. As too would be updating the style to use parenthesis as is now the fashion. The purpose of the commit is then unclear.

Comment (smcintyre-r7) [reply modules/exploits/linux/local/apport_abrt_chroot_priv_esc.rb:148]: Well you can add an additional commit and comment it as you see fit. Sure you could change everything to use the optional description from the vprint methods so it'd be consistent with the change you made for updating `CheckCode::Safe` to `CheckCode::Detected` and you could also update the style to use parenthesis. While those would be great changes neither are actually required to use the `AutoCheck` mixin. The concern I have is primarily the maintenance of the list of check codes that correspond to the exploit/don't exploit outcome being duplicated both in the mixin and here. The messaging and ability for the user to bypass it using a consistent datastore option would also be improvements towards keeping our UX consistent.

**Comment by smcintyre-r7** [comment]
Tested successfully to ensure that it fixes the issue:
```
msf6 post(multi/recon/local_exploit_suggester) > run

[*] 192.168.159.35 - Collecting local exploits for x64/linux...
[*] 192.168.159.35 - 40 exploit checks are being tried...
[+] 192.168.159.35 - exploit/linux/local/apport_abrt_chroot_priv_esc: The service is running, but could not be validated. Could not determine Apport version. apport-cli is not installed or not in $PATH.
[+] 192.168.159.35 - exploit/linux/local/network_manager_vpnc_username_priv_esc: The service is running, but could not be validated.
[+] 192.168.159.35 - exploit/linux/local/sudo_baron_samedit: The target appears to be vulnerable. sudo 1.9.1 is a vulnerable build.
[*] Post module execution completed
msf6 post(multi/recon/local_exploit_suggester) >
```

Minor changes added in 636b790 as discussed.

**Comment by smcintyre-r7** [comment]
# Release Notes
This fixes an issue in the `apport_abrt_chroot_priv_esc` module where if the `apport-cli` binary was not in the PATH the check method would fail.
