### PR TITLE
Fixes deprecation message logic when no `data` object present

### LINKED ISSUE #20558: [DEPRECATION] Using report_note with a non-hash data value is deprecated, please raise a Github issue with this output.
## Steps to reproduce

How'd you do it?

1. msfconsole

```
msf > use auxiliary/scanner/http/wordpress_scanner
msf auxiliary(scanner/http/wordpress_scanner) > set RHOST 94.237.57.211
RHOST => 94.237.57.211
msf auxiliary(scanner/http/wordpress_scanner) > set RPORT 51008
RPORT => 51008
msf auxiliary(scanner/http/wordpress_scanner) > set TARGETURI /
TARGETURI => /
msf auxiliary(scanner/http/wordpress_scanner) > exploit
[*] Trying 94.237.57.211
[+] 94.237.57.211 - Detected Wordpress 5.6.1
[*] 94.237.57.211 - Enumerating Themes
[*] 94.237.57.211 - Progress  0/3 (0.0%)
[*] 94.237.57.211 - Finished scanning themes
[*] 94.237.57.211 - Enumerating plugins
[*] 94.237.57.211 - Progress   0/73 (0.0%)
[+] 94.237.57.211 - Detected plugin: simple-backup version 2.7.10

[-] [DEPRECATION] Using report_note with a non-hash data value is deprecated, please raise a Github issue with this output.
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:415:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/note.rb:81:in 'Msf::DBManager::Note#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:40:in 'block in NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in 'Metasploit::Framework::DataService::DataProxy#data_service_operation'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:38:in 'NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/report.rb:185:in 'Msf::Auxiliary::Report#report_note'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:117:in 'block in Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Array#each'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Enumerable#each_with_index'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:116:in 'block (2 levels) in Msf::Auxiliary::Scanner#run'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:105:in 'block in Msf::ThreadManager#spawn'
[*] 94.237.57.211 - Finished scanning plugins
[*] 94.237.57.211 - Searching Users
[*] 94.237.57.211 - Was not able to identify users on site using /wp-json/wp/v2/users
[*] 94.237.57.211 - Finished all scans
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

## Were you following a specific guide/tutorial or reading documentation?

No

## Expected behavior

What should happen?

I shouldn't get any warning.

## Current behavior

What happens instead?

I get the warning

### Metasploit version

Framework: 6.4.90-dev-  
Console  : 6.4.90-dev-

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/core]
loglevel=3

[framework/ui/console]
ActiveModule=auxiliary/scanner/http/wordpress_scanner

[scanner/http/wordpress_scanner]
RHOSTS=94.237.57.211
RPORT=51008
TARGETURI=/
WORKSPACE=
VERBOSE=false
VHOST=
SSL=false
Proxies=
KrbCacheMode=read-write
HTTP::Auth=auto
HTTP::Rhostname=
DomainControllerRhost=
HTTP::Krb5Ccname=
HTTP::KrbOfferedEncryptionTypes=AES256,AES128,RC4-HMAC,DES-CBC-MD5,DES3-CBC-SHA1
UserAgent=Mozilla/5.0 (iPad; CPU OS 17_7_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Mobile/15E148 Safari/604.1
HttpUsername=
HttpPassword=
HttpRawHeaders=
DigestAuthIIS=true
SSLVersion=Auto
FingerprintCheck=true
DOMAIN=WORKSTATION
HttpClientTimeout=
HttpTrace=false
HttpTraceHeadersOnly=false
HttpTraceColors=red/blu
SSLServerNameIndication=
SSLKeyLogFile=
HTTP::uri_encode_mode=hex-normal
HTTP::uri_full_url=false
HTTP::pad_method_uri_count=1
HTTP::pad_uri_version_count=1
HTTP::pad_method_uri_type=space
HTTP::pad_uri_version_type=space
HTTP::method_random_valid=false
HTTP::method_random_invalid=false
HTTP::method_random_case=false
HTTP::version_random_valid=false
HTTP::version_random_invalid=false
HTTP::uri_dir_self_reference=false
HTTP::uri_dir_fake_relative=false
HTTP::uri_use_backslashes=false
HTTP::pad_fake_headers=false
HTTP::pad_fake_headers_count=0
HTTP::pad_get_params=false
HTTP::pad_get_params_count=16
HTTP::pad_post_params=false
HTTP::pad_post_params_count=16
HTTP::shuffle_get_params=false
HTTP::shuffle_post_params=false
HTTP::uri_fake_end=false
HTTP::uri_fake_params_start=false
HTTP::header_folding=false
WPCONTENTDIR=wp-content
WPCHECK=true
THREADS=1
ShowProgress=true
ShowProgressPercent=10
EXPLOITABLE=true
EXPLOITABLE_THEMES=/opt/metasploit-framework/embedded/framework/data/wordlists/wp-exploitable-themes.txt
EXPLOITABLE_PLUGINS=/opt/metasploit-framework/embedded/framework/data/wordlists/wp-exploitable-plugins.txt
THEMES=true
PLUGINS=true
THEMES_FILE=/opt/metasploit-framework/embedded/framework/data/wordlists/wp-themes.txt
PLUGINS_FILE=/opt/metasploit-framework/embedded/framework/data/wordlists/wp-plugins.txt
PROGRESS=1000
USERS=true
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: Connected to msf. Connection type: postgresql.
```

| ID | Hosts | Vulnerabilities | Notes | Services |
|-:|-:|-:|-:|-:|
| 1 **(Current)** | 1 | 0 | 2 | 1 |
| **Total (1)** | **1** | **0** | **2** | **1** |

</details>

##  Framework Configuration

The features are configured as follows:
<details>
<summary>Collapse</summary>

| name | enabled |
|-:|-:|
| wrapped_tables | true |
| fully_interactive_shells | false |
| manager_commands | false |
| metasploit_payload_warnings | true |
| defer_module_loads | true |
| smb_session_type | true |
| postgresql_session_type | true |
| mysql_session_type | true |
| mssql_session_type | true |
| ldap_session_type | true |
| show_successful_logins | false |
| dns | true |
| hierarchical_search_table | true |
| display_module_action | true |

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
36     set loglevel 3
37     use auxiliary/scanner/http/wordpress_scanner
38     set RHOST 94.237.57.211
39     set RPORT 51008
40     set TARGETURI /
41     exploit
42     debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[09/21/2025 16:48:05] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[09/21/2025 16:48:05] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[09/21/2025 16:48:11] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[09/21/2025 16:48:11] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[09/21/2025 16:48:12] [e(0)] core: Failed to open history file: /home/fra/.msf4/history with error: No such file or directory @ rb_sysopen - /home/fra/.msf4/history
[09/21/2025 17:36:20] [e(0)] core: 
[-] [DEPRECATION] Using report_note with a non-hash data value is deprecated, please raise a Github issue with this output.
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:415:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/note.rb:81:in 'Msf::DBManager::Note#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:40:in 'block in NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in 'Metasploit::Framework::DataService::DataProxy#data_service_operation'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:38:in 'NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/report.rb:185:in 'Msf::Auxiliary::Report#report_note'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:117:in 'block in Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Array#each'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Enumerable#each_with_index'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:116:in 'block (2 levels) in Msf::Auxiliary::Scanner#run'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:105:in 'block in Msf::ThreadManager#spawn'
[09/21/2025 17:44:22] [e(0)] core: 
[-] [DEPRECATION] Using report_note with a non-hash data value is deprecated, please raise a Github issue with this output.
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:415:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/note.rb:81:in 'Msf::DBManager::Note#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:40:in 'block in NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in 'Metasploit::Framework::DataService::DataProxy#data_service_operation'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:38:in 'NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/report.rb:185:in 'Msf::Auxiliary::Report#report_note'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:117:in 'block in Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Array#each'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Enumerable#each_with_index'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:116:in 'block (2 levels) in Msf::Auxiliary::Scanner#run'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:105:in 'block in Msf::ThreadManager#spawn'
[09/21/2025 17:58:21] [e(0)] core: 
[-] [DEPRECATION] Using report_note with a non-hash data value is deprecated, please raise a Github issue with this output.
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:415:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/note.rb:81:in 'Msf::DBManager::Note#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:40:in 'block in NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in 'Metasploit::Framework::DataService::DataProxy#data_service_operation'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:38:in 'NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/report.rb:185:in 'Msf::Auxiliary::Report#report_note'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:117:in 'block in Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Array#each'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Enumerable#each_with_index'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:116:in 'block (2 levels) in Msf::Auxiliary::Scanner#run'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:105:in 'block in Msf::ThreadManager#spawn'
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[09/21/2025 16:48:05] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[09/21/2025 16:48:11] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[09/21/2025 16:48:11] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[09/21/2025 16:48:12] [e(0)] core: Failed to open history file: /home/fra/.msf4/history with error: No such file or directory @ rb_sysopen - /home/fra/.msf4/history
[09/21/2025 17:36:20] [e(0)] core: 
[-] [DEPRECATION] Using report_note with a non-hash data value is deprecated, please raise a Github issue with this output.
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:415:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/note.rb:81:in 'Msf::DBManager::Note#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:40:in 'block in NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in 'Metasploit::Framework::DataService::DataProxy#data_service_operation'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:38:in 'NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/report.rb:185:in 'Msf::Auxiliary::Report#report_note'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:117:in 'block in Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Array#each'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Enumerable#each_with_index'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:116:in 'block (2 levels) in Msf::Auxiliary::Scanner#run'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:105:in 'block in Msf::ThreadManager#spawn'
[09/21/2025 17:44:22] [e(0)] core: 
[-] [DEPRECATION] Using report_note with a non-hash data value is deprecated, please raise a Github issue with this output.
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:415:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/note.rb:81:in 'Msf::DBManager::Note#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:40:in 'block in NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in 'Metasploit::Framework::DataService::DataProxy#data_service_operation'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:38:in 'NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/report.rb:185:in 'Msf::Auxiliary::Report#report_note'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:117:in 'block in Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Array#each'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Enumerable#each_with_index'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:116:in 'block (2 levels) in Msf::Auxiliary::Scanner#run'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:105:in 'block in Msf::ThreadManager#spawn'
[09/21/2025 17:57:28] [i(2)] core: Reloading auxiliary module scanner/http/wordpress_scanner. Ambiguous module warnings are safe to ignore
[09/21/2025 17:58:21] [e(0)] core: 
[-] [DEPRECATION] Using report_note with a non-hash data value is deprecated, please raise a Github issue with this output.
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:415:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/note.rb:81:in 'Msf::DBManager::Note#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:40:in 'block in NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in 'Metasploit::Framework::DataService::DataProxy#data_service_operation'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:38:in 'NoteDataProxy#report_note'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/report.rb:185:in 'Msf::Auxiliary::Report#report_note'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:117:in 'block in Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Array#each'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Enumerable#each_with_index'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/wordpress_scanner.rb:109:in 'Msf::Modules::Auxiliary__Scanner__Http__Wordpress_scanner::MetasploitModule#run_host'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:116:in 'block (2 levels) in Msf::Auxiliary::Scanner#run'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:105:in 'block in Msf::ThreadManager#spawn'
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.4.90-dev-
Ruby: ruby 3.4.4 (2025-05-14 revision a38531fd3f) +PRISM [x86_64-linux]
OpenSSL: OpenSSL 1.1.1t  7 Feb 2023
Install Root: /opt/metasploit-framework/embedded/framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Omnibus Installer
```

</details>

### PR DESCRIPTION
**Pull request by cgranleese-r7**
Fixes https://github.com/rapid7/metasploit-framework/issues/20558.

With the previous implementation I added https://github.com/rapid7/metasploit-framework/pull/19939 if no `data` object was present in the `report_note` method it would incorrectly return the deprecation message. Now a `nil` check has been added, so if `data` is not present it will not return the depreciation message.

## Testing
Can be any target or module that make use of `report_note`. Below I will add what I used:

### Target
```
❯ docker run --platform linux/amd64 \
… ❯   -e "ACCEPT_EULA=Y" \
… ❯   -e "MSSQL_SA_PASSWORD=MyMSSQLServerPassword__<>" \
… ❯   -p 1433:1433 \
… ❯   mcr.microsoft.com/mssql/server:2022-latest
```

## Module 
```
admin/mssql/mssql_enum
```

Within the chosen module, comment out the `data` object from the `report_note` call:
```ruby
    report_note(
      host: mssql_client.peerhost,
      proto: 'TCP',
      port: mssql_client.peerport,
      type: 'MSSQL_ENUM',
      # data: { version: sqlversion }
    )
```

## Before
```
msf auxiliary(admin/mssql/mssql_enum) > run session=-1
[*] Running MS SQL Server Enumeration...
[*] Using existing session 1
[*] Version:
[*]	Microsoft SQL Server 2022 (RTM-CU18) (KB5050771) - 16.0.4185.3 (X64)
[*]		Feb 28 2025 18:24:49
[*]		Copyright (C) 2022 Microsoft Corporation
[*]		Developer Edition (64-bit) on Linux (Ubuntu 22.04.5 LTS) <X64>
[-] [DEPRECATION] Using report_note with a non-hash data value is deprecated, please raise a Github issue with this output.
[-] Call stack:
[-]   /Users/cgranleese/.rvm/gems/ruby-3.3.8@metasploit-framework/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:415:in `with_connection'
[-]   /Users/cgranleese/code/metasploit-framework/lib/msf/core/db_manager/note.rb:81:in `report_note'
[-]   /Users/cgranleese/code/metasploit-framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:40:in `block in report_note'
[-]   /Users/cgranleese/code/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in `data_service_operation'
[-]   /Users/cgranleese/code/metasploit-framework/lib/metasploit/framework/data_service/proxy/note_data_proxy.rb:38:in `report_note'
[-]   /Users/cgranleese/code/metasploit-framework/lib/msf/core/auxiliary/report.rb:185:in `report_note'
[-]   /Users/cgranleese/code/metasploit-framework/modules/auxiliary/admin/mssql/mssql_enum.rb:54:in `run'
[-]   /Users/cgranleese/code/metasploit-framework/lib/msf/base/simple/auxiliary.rb:180:in `job_run_proc'
[-]   /Users/cgranleese/code/metasploit-framework/lib/msf/base/simple/auxiliary.rb:87:in `run_simple'
[-]   /Users/cgranleese/code/metasploit-framework/lib/msf/base/simple/auxiliary.rb:98:in `run_simple'
[-]   /Users/cgranleese/code/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:66:in `cmd_run'
[-]   /Users/cgranleese/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:582:in `run_command'
[-]   /Users/cgranleese/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:531:in `block in run_single'
[-]   /Users/cgranleese/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `each'
[-]   /Users/cgranleese/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:525:in `run_single'
[-]   /Users/cgranleese/code/metasploit-framework/lib/rex/ui/text/shell.rb:165:in `block in run'
[-]   /Users/cgranleese/code/metasploit-framework/lib/rex/ui/text/shell.rb:309:in `block in with_history_manager_context'
[-]   /Users/cgranleese/code/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'
[-]   /Users/cgranleese/code/metasploit-framework/lib/rex/ui/text/shell.rb:306:in `with_history_manager_context'
[-]   /Users/cgranleese/code/metasploit-framework/lib/rex/ui/text/shell.rb:133:in `run'
[-]   /Users/cgranleese/code/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
[-]   /Users/cgranleese/code/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
[-]   ./msfconsole:23:in `<main>'
[*] Configuration Parameters:
[*] 	C2 Audit Mode is Not Enabled
...
[*] Default Server Instance SQL Server Service is running under the privilege of:
[*] 	xp_regread might be disabled in this system
[*] Auxiliary module execution completed
```

## After
```
msf auxiliary(admin/mssql/mssql_enum) > run session=-1
[*] Running MS SQL Server Enumeration...
[*] Using existing session 1
[*] Version:
[*]	Microsoft SQL Server 2022 (RTM-CU18) (KB5050771) - 16.0.4185.3 (X64)
[*]		Feb 28 2025 18:24:49
[*]		Copyright (C) 2022 Microsoft Corporation
[*]		Developer Edition (64-bit) on Linux (Ubuntu 22.04.5 LTS) <X64>[*] Configuration Parameters:
[*] 	C2 Audit Mode is Not Enabled
...
[*] Default Server Instance SQL Server Service is running under the privilege of:
[*] 	xp_regread might be disabled in this system
[*] Auxiliary module execution completed
```

## Verification

- [ ] Follow testing steps again and confirm before and after
- [ ] Code change is sane
- [ ] CI goes green

### CODE REVIEW

File: lib/msf/core/db_manager/note.rb [hunk 1]
```diff
@@ -144,7 +144,7 @@ def report_note(opts)
 
     ntype  = opts.delete(:type) || opts.delete(:ntype) || (raise RuntimeError, "A note :type or :ntype is required")
 
-    unless opts[:data].is_a?(Hash)
+    unless opts[:data].is_a?(Hash) || opts[:data].nil?
```
Comment (adfoster-r7) [inline lib/msf/core/db_manager/note.rb]: Maybe:

```suggestion
    unless opts[:data]&.is_a?(Hash)
```

Comment (cgranleese-r7) [reply lib/msf/core/db_manager/note.rb]: Will add a comment to improve parse `# We expect data to be a Hash, but we also need to allow for no data value being passed`.

Could maybe add a test potentially as well.

Comment (cgranleese-r7) [reply lib/msf/core/db_manager/note.rb]: Potential fix.
```suggestion
    has_valid_note_datatype = opts[:data].is_a?(Hash) || opts[:data].nil?
    unless has_valid_note_datatype
```

**Review by adfoster-r7 — APPROVED** [review]

**Comment by cgranleese-r7** [comment]
## Release Notes
Fixes a crash when running modules that reported notes with no data present, such as the `admin/mssql/mssql_enum` and `scanner/http/wordpress_scanner` modules
