### PR TITLE
guard Rex::Version.new against crashes on local modules

### LINKED ISSUE #19812: Rex::Version crashes in some local modules with Amazon Linux 2 kernel versions
Placeholder to link fixing several modules.

Several modules (a bunch written by me) use the following logic:

```
release = kernel_release
Rex::Version.new(release)
```

This works great on most Ubuntu systems, Fedora, etc. However, Amazon Linux 2 has kernel versions like `5.4.129-72.229.amzn2int.x86_64` ([ref](https://docs.aws.amazon.com/incident-manager/latest/APIReference/API_SSMContacts_ListContactChannels.html))

```
>> Rex::Version.new('5.4.129-72.229.amzn2int.x86_64')
/usr/lib/ruby/vendor_ruby/rubygems/version.rb:223:in `initialize': Malformed version number string 5.4.129-72.229.amzn2int.x86_64 (ArgumentError)
```

So we'll need to do better about guarding like so:

```
require 'rex/version'

begin
  Rex::Version.new('5.4.129-72.229.amzn2int.x86_64')
rescue ArgumentError => e
  puts "Error reading invalid version: #{e}"
end
```

### PR DESCRIPTION
**Pull request by h00die**
fixes #19812

Fixes some bugs and potential bugs where `Rex::Version.new` is fed data which may cause a crash. Guard these to prevent crashes on Amazon 2 Linux, and other systems (tomcat one should break on non dpkg based systems like fedora)

### CODE REVIEW

**Comment by bcoles** [comment]
All of the existing `kernel_release` code looks fine to me for the example "funky" version string `5.4.129-72.229.amzn2int.x86_64`. Was there another version string causing issues?

This code splits at the first `-`. `Rex::Version` receives `5.4.129` which is valid and will not `raise`.

The package parsing code does no prior parsing of the version before passing to `Rex::Version` and will likely `raise`.

**Comment by h00die** [comment]
The `kernel_release` code is good, it returns as expected. That test string won't load well into `Rex::Version`, so we either need to guard on getting something from `kernel_release` that won't cleanly load into a `Rex::Version`, or do some post filtering (typically done with software package versions, less so kernel releases) to make it load correctly.

This is just want I was seeing in an engagement and wanted to fix some crashes that `exploit_suggester` was seeing

**Comment by h00die** [comment]
I'll be testing these changes on target to make sure its handling better, and get some more test data.

File: modules/exploits/linux/local/docker_cgroup_escape.rb [hunk 1]
```diff
@@ -83,13 +83,17 @@ def check
...
-    release_short = Rex::Version.new(release.split('-').first)
-    release_long = Rex::Version.new(release.split('-')[0..1].join('-'))
-    if release_short >= Rex::Version.new('5.13.0') && release_long < Rex::Version.new('5.13.0-37.42') || # Ubuntu 21.10
-       release_short >= Rex::Version.new('5.4.0') && release_long < Rex::Version.new('5.4.0-105.119') || # Ubuntu 20.04 LTS
-       release_short >= Rex::Version.new('4.15.0') && release_long < Rex::Version.new('4.15.0-173.182') || # Ubuntu 18.04 LTS
-       release_short >= Rex::Version.new('4.4.0') && release_long < Rex::Version.new('4.4.0-222.255') # Ubuntu 16.04 ESM
-      return CheckCode::Vulnerable("IF host OS is Ubuntu, kernel version #{release} is vulnerable")
+    begin
+      release_short = Rex::Version.new(release.split('-').first)
+      release_long = Rex::Version.new(release.split('-')[0..1].join('-'))
```
Comment (h00die) [inline modules/exploits/linux/local/docker_cgroup_escape.rb:88]: since we re-join with '-' (which works on ubuntu where I tested it), this will fail on amazon linux.

**Comment by h00die** [comment]
@bcoles 

Fedora 31 target (vm) I'm getting the following:

```
[msf](Jobs:2 Agents:1) exploit(linux/local/netfilter_xtables_heap_oob_write_priv_esc) > check
[-] Exploit failed: RuntimeError Could not determine grsecurity status
[-] Check failed: The state could not be determined.
```

This is caused by https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/linux/kernel.rb#L262 . Which looks like its checking on the LOCAL (metasploit) system, not the remote (exploited) system. Just wanted to confirm if that was right and if that was the expected behavior.

**Comment by bcoles** [comment]
> @bcoles
> 
> Fedora 31 target (vm) I'm getting the following:
> 
> ```
> [msf](Jobs:2 Agents:1) exploit(linux/local/netfilter_xtables_heap_oob_write_priv_esc) > check
> [-] Exploit failed: RuntimeError Could not determine grsecurity status
> [-] Check failed: The state could not be determined.
> ```
> 
> This is caused by https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/linux/kernel.rb#L262 . Which looks like its checking on the LOCAL (metasploit) system, not the remote (exploited) system. Just wanted to confirm if that was right and if that was the expected behavior.

That is definitely checking the *local* file which is definitely *wrong*.

The `grsec_installed?` method was added in https://github.com/rapid7/metasploit-framework/commit/d87fef5ee318b6ded84b315e01320c5a555b45bd and checks the remote file.

The breaking change was introduced in https://github.com/rapid7/metasploit-framework/commit/f5145dee351dd12212d318227f49acc36ea97831 (#19405).

**Comment by h00die** [comment]
@jvoisin any background on that change?

**Review by smcintyre-r7 — COMMENTED** [review]
This seems like something that would be good functionality to move into `post/linux/kernel` as a function. I see we already have `kernel_version` but something with an intuitive name that would return an instance of `Rex::Version` so this kind of normalization is centralized would be beneficial in the future. It would be a good idea to do the exception handling within the method as well and just return `nil` to the caller so they can do what they want in the event that they can't get a `Rex::Version` instance.

Maybe something like `kernel_rex_version`?

I'm particularly concerned about this because of the one case where the string is rejoined in the case of Ubuntu.

**Comment by jvoisin** [comment]
Dang, I thought that `File.exists?('/dev/grsec') && File.chardev?('/dev/grsec')` would check the remote system :/

**Comment by h00die** [comment]
> This seems like something that would be good functionality to move into `post/linux/kernel` as a function. I see we already have `kernel_version` but something with an intuitive name that would return an instance of `Rex::Version` so this kind of normalization is centralized would be beneficial in the future. It would be a good idea to do the exception handling within the method as well and just return `nil` to the caller so they can do what they want in the event that they can't get a `Rex::Version` instance.
> 
> Maybe something like `kernel_rex_version`?
> 
> I'm particularly concerned about this because of the one case where the string is rejoined in the case of Ubuntu.

I like the idea, but I think that needs to be handled outside of this PR. I think a bunch of different kernel releases from different flavors will be required in a pretty big spec to make sure we handle all the cases. For instance, Ubuntu has kernels like `5.13.0-37.42` from the docker cgroup exploit, and `5.4.129-72.229.amzn2int.x86_64`. Seems like an easy split/regex, `\d{1}\.\d{1-3}\.\d{1-4}\-\d{1-3}\.\d{1-4}`. But gathering that data will take some time.

File: lib/msf/core/post/linux/kernel.rb [hunk 2]
```diff
@@ -1,331 +1,338 @@
...
+          directory?('/proc/sys/lkrg')
+        rescue StandardError
+          raise 'Could not determine LKRG status'
+        end
+
+        #
+        # Returns true if grsecurity is installed
+        #
+        def grsec_installed?
+          cmd_exec('test -c /dev/grsec && echo true').to_s.strip.include? 'true'
```
Comment (jheysel-r7) [inline lib/msf/core/post/linux/kernel.rb:266]: Would it be worth adding a function like `character_file?` in `file.rb` similar to: https://github.com/rapid7/metasploit-framework/blob/0cf227ff00e655fbe12a100959272b1e7490f362/lib/msf/core/post/file.rb#L186
for handling this scenario?

**Review by jheysel-r7 — COMMENTED** [review]
# Testing
### Before
```
msf6 exploit(linux/local/tomcat_ubuntu_log_init_priv_esc) > check
[-] Exploit failed: ArgumentError Malformed version number string command
[-] Check failed: The state could not be determined.
```

```
msf6 exploit(linux/local/docker_cgroup_escape) > check
[*] Unable to determine host OS, this check method is unlikely to be accurate if the host isn't Ubuntu
[-] Exploit failed: ArgumentError Malformed version number string 4.14.355-275.572.amzn2.x86_64
[-] Check failed: The state could not be determined.
```

```
msf6 exploit(linux/local/vmwgfx_fd_priv_esc) > check
[-] Exploit failed: ArgumentError Malformed version number string 4.14.355-275.572.amzn2.x86_64
[-] MANUAL replacement of trojaned  is required.
[-] Check failed: The state could not be determined.
```
### After
```
msf6 exploit(linux/local/tomcat_ubuntu_log_init_priv_esc) > check
[*] The target is not exploitable. Unable to execute command to determine installed pacakges
```

```
msf6 exploit(linux/local/docker_cgroup_escape) > check
[*] Unable to determine host OS, this check method is unlikely to be accurate if the host isn't Ubuntu
[*] The target is not exploitable. Kernel version 6.8.0-51-generic may not be vulnerable depending on the host OS
```

```
msf6 exploit(linux/local/vmwgfx_fd_priv_esc) > check
[-] MANUAL replacement of trojaned  is required.
[*] The target is not exploitable. Error determining or processing kernel release (4.14.355-275.572.amzn2.x86_64) into known format: Malformed version number string 4.14.355-275.572.amzn2.x86_64
```

File: lib/msf/core/post/linux/kernel.rb (hunk 2 above)
Comment (h00die) [reply lib/msf/core/post/linux/kernel.rb:266]: @bcoles wrote that, I simply reverted a bad change to it so it works again

Comment (jheysel-r7) [reply lib/msf/core/post/linux/kernel.rb:266]: @h00die sounds good. It doesn't seem like this method of checking for a character file is used anywhere else in the framework. We can refactor later if need be.

**Review by jheysel-r7 — APPROVED** [review]
Thanks for the fix @h00die, much appreciated. This PR looks good to go as is. I've opened an issue to track the improvements suggested by @smcintyre-r7.

**Comment by jheysel-r7** [comment]
# Release Notes 
Fixes an issue were Rex::Version.new was causing modules to crash when run against instances of Amazon Linux and other distributions which have a different format for displaying the kernel version.
