### PR TITLE
Fix windows DNS crash on bootup

### LINKED ISSUE #19516: `searchlist=': Wrong argument format, neither String nor Array (ResolverArgumentError)
Windows11 Pro 64-bit system installation after the following error, how to solve it?
image

### PR DESCRIPTION
**Pull request by adfoster-r7**
Closes https://github.com/rapid7/metasploit-framework/issues/19516

Best reviewed with whitespace ignored

## Verification

I manually set `arr` to match the user's [resolv info](https://github.com/rapid7/metasploit-framework/issues/19516#issuecomment-2382911844) of a `nil` searchlist.

### Before

Crash

```
c:/a/metasploit-framework/lib/net/dns/resolver.rb:282:in `searchlist=': Wrong argument format, neither String nor Array (ResolverArgumentError)
        from c:/a/metasploit-framework/lib/net/dns/resolver.rb:1086:in `parse_config_file'
        from c:/a/metasploit-framework/lib/rex/proto/dns/resolver.rb:66:in `initialize'
        from c:/a/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:25:in `initialize'
        from c:/a/metasploit-framework/lib/msf/ui/console/driver.rb:86:in `new'
        from c:/a/metasploit-framework/lib/msf/ui/console/driver.rb:86:in `initialize'
        from c:/a/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
        from c:/a/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
        from c:/a/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
        from c:/a/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from msfconsole:23:in `<main>'
```

### After

verified there was no longer a crash:

```
msf6 >
```

### CODE REVIEW

File: lib/net/dns/resolver.rb [hunk 1]
```diff
@@ -1081,36 +1081,34 @@ def parse_config_file
...
-                  # per https://man7.org/linux/man-pages/man5/resolv.conf.5.html nameserver values must be IP addresses
-                  begin
-                    ip_addr = IPAddr.new(nameserver)
-                  rescue IPAddr::InvalidAddressError
-                    @logger.warn "Ignoring invalid name server '#{nameserver}' from configuration file"
-                    next
-                  else
-                    self.nameservers += [ip_addr]
-                  end
+          IO.foreach(@config[:config_file]) do |line|
```
Comment (adfoster-r7) [inline lib/net/dns/resolver.rb:1087]: There's an existing edge-case here, where we might be have partially parsed this file before encountering an error - and we don't revert state back, or continue parsing the rest of the file

**Review by smcintyre-r7 — APPROVED** [review]
