### PR TITLE
Fix references to LDAP Datastore Options

### LINKED ISSUE #20259: Fix auxiliary/gather/vmware_vcenter_vmdir_ldap
Make sure the datastore options match the new datastore module options in both the module and docs.

### PR DESCRIPTION
**Pull request by bwatters-r7**
Fixes https://github.com/rapid7/metasploit-framework/issues/20259
Replaces old datastore options with new datastore options.

### CODE REVIEW

File: modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@ def initialize(info = {})
           the vmdir service in VMware vCenter Server version 6.7 prior to the
           6.7U3f update, only if upgraded from a previous release line, such as
           6.0 or 6.5.
-          If the bind username and password are provided (BIND_DN and BIND_PW
+          If the bind username and password are provided (BIND_DN and BLDAPPassword
```
Comment (bwatters-r7) [inline modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb:22]:
```suggestion
          If the bind username and password are provided (BIND_DN and LDAPPassword
```

**Comment by smcintyre-r7** [comment]
This is crashing with network errors but they're unrelated to the changes in this PR. If you apply this patch however I can test these changes by showing that it's successfully binding to the target LDAP server.

```diff
diff --git modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb
index ac48322022..3fa1f789db 100644
--- modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb
+++ modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb
@@ -102,9 +102,16 @@ class MetasploitModule < Msf::Auxiliary
       # HACK: Stash discovered base DN in CheckCode reason
       Exploit::CheckCode::Vulnerable(base_dn)
     end
+  rescue Errno::ECONNRESET
+    fail_with(Failure::Disconnected, 'The connection was reset.')
+  rescue Rex::ConnectionError => e
+    fail_with(Failure::Unreachable, e.message)
+  rescue Rex::Proto::Kerberos::Model::Error::KerberosError => e
+    fail_with(Failure::NoAccess, e.message)
+  rescue Rex::Proto::LDAP::LdapException => e
+    fail_with(Failure::NoAccess, e.message)
   rescue Net::LDAP::Error => e
-    print_error("#{e.class}: #{e.message}")
-    Exploit::CheckCode::Unknown
+    fail_with(Failure::Unknown, "#{e.class}: #{e.message}")
   end
 
   def pillage(entries)
```

**Review by smcintyre-r7 — APPROVED** [review]

**Comment by smcintyre-r7** [comment]
# Release Notes
This fixes an issue with the `auxiliary/gather/vmware_vcenter_vmdir_ldap` module caused by some options that had been changed.
