### PR TITLE
Preference target values when registering options

### LINKED ISSUE #12963: Target DefaultOptions not imported into the datastore when module is initialized
Target DefaultOptions are not imported into the datastore when module is initialized, but only if you explicitly set the target. Apparently, this only works if `import_target_defaults` is added at the end of the `initialize` method.

Related PR: https://github.com/rapid7/metasploit-framework/pull/10471

## Steps to reproduce

1. Create this module `modules/exploits/windows/import_target_defaults_test.rb`
```ruby
##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##

class MetasploitModule < Msf::Exploit::Remote
  Rank = NormalRanking

  include Exploit::Remote::Tcp

  def initialize(info = {})
    super(
      update_info(
        info,
        'Name'           => 'Sample Exploit',
        'Description'    => %q(
          foo
        ),
        'License'        => MSF_LICENSE,
        'Author'         => ['skape'],
        'Targets'        =>
          [
            # Target 0: Windows All
            [
              'Windows XP/Vista/7/8',
              {
                'Platform' => 'win',
                'Ret'      => 0x41424344,
                'DefaultOptions' => { 'DisablePayloadHandler' => true, 'WfsDelay' => 0 }
              }
            ],
            [
              'Windows 10',
              {
                'Platform' => 'win',
                'Ret'      => 0x45454545,
                'DefaultOptions' => { 'DisablePayloadHandler' => false, 'WfsDelay' => 90 }
              }
            ]
          ],
        'DefaultTarget'  => 0
      )
    )
    #import_target_defaults
  end

  def exploit
    return
  end
end
```
2. `./msfconsole`
3. `msf5 > use exploits/windows/import_target_defaults_test`
4. Target 0 is the default target:
```ruby
msf5 exploit(windows/import_target_defaults_test) > show options

Module options (exploit/windows/import_target_defaults_test):

   Name    Current Setting  Required  Description
   ----    ---------------  --------  -----------
   RHOSTS                   yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT                    yes       The target port (TCP)


Exploit target:

   Id  Name
   --  ----
   0   Windows XP/Vista/7/8
```
5. The advanced options `DisablePayloadHandler` and `WfsDelay` are not set as expected
```ruby
msf5 exploit(windows/import_target_defaults_test) > show advanced

Module advanced options (exploit/windows/import_target_defaults_test):

   Name                    Current Setting  Required  Description
   ----                    ---------------  --------  -----------
   CHOST                                    no        The local client address
   CPORT                                    no        The local client port
   ConnectTimeout          10               yes       Maximum number of seconds to establish a TCP connection
   ContextInformationFile                   no        The information file that contains context information
   DisablePayloadHandler   false            no        Disable the handler code for the selected payload
   EnableContextEncoding   false            no        Use transient context when encoding payloads
   Proxies                                  no        A proxy chain of format type:host:port[,type:host:port][...]
   SSL                     false            no        Negotiate SSL/TLS for outgoing connections
   SSLCipher                                no        String for SSL cipher - "DHE-RSA-AES256-SHA" or "ADH"
   SSLVerifyMode           PEER             no        SSL verification method (Accepted: CLIENT_ONCE, FAIL_IF_NO_PEER_CERT, NONE, PEER)
   SSLVersion              Auto             yes       Specify the version of SSL/TLS to be used (Auto, TLS and SSL23 are auto-negotiate) (Accepted: Auto, TLS, SSL23, SSL3, TLS1, TLS1.1, TLS1.2)
   VERBOSE                 false            no        Enable detailed status messages
   WORKSPACE                                no        Specify the workspace for this module
   WfsDelay                0                no        Additional delay when waiting for a session
```
6. even after executing the exploit, these options are still not set correctly:
```ruby
msf5 exploit(windows/import_target_defaults_test) > set rhosts 172.16.60.173
rhosts => 172.16.60.173
msf5 exploit(windows/import_target_defaults_test) > set rport 25
rport => 25
msf5 exploit(windows/import_target_defaults_test) > run

[*] Started reverse TCP handler on 172.16.60.1:4444
[*] Exploit completed, but no session was created.
msf5 exploit(windows/import_target_defaults_test) > show advanced

Module advanced options (exploit/windows/import_target_defaults_test):

   Name                    Current Setting  Required  Description
   ----                    ---------------  --------  -----------
   CHOST                                    no        The local client address
   CPORT                                    no        The local client port
   ConnectTimeout          10               yes       Maximum number of seconds to establish a TCP connection
   ContextInformationFile                   no        The information file that contains context information
   DisablePayloadHandler   false            no        Disable the handler code for the selected payload
   EnableContextEncoding   false            no        Use transient context when encoding payloads
   Proxies                                  no        A proxy chain of format type:host:port[,type:host:port][...]
   SSL                     false            no        Negotiate SSL/TLS for outgoing connections
   SSLCipher                                no        String for SSL cipher - "DHE-RSA-AES256-SHA" or "ADH"
   SSLVerifyMode           PEER             no        SSL verification method (Accepted: CLIENT_ONCE, FAIL_IF_NO_PEER_CERT, NONE, PEER)
   SSLVersion              Auto             yes       Specify the version of SSL/TLS to be used (Auto, TLS and SSL23 are auto-negotiate) (Accepted: Auto, TLS, SSL23, SSL3, TLS1, TLS1.1, TLS1.2)
   VERBOSE                 false            no        Enable detailed status messages
   WORKSPACE                                no        Specify the workspace for this module
   WfsDelay                0                no        Additional delay when waiting for a session
```
7. The `DefaultOptions` are correctly imported if you explicitly set the target:
```ruby
msf5 exploit(windows/import_target_defaults_test) > set target 1
target => 1
msf5 exploit(windows/import_target_defaults_test) > show advanced

Module advanced options (exploit/windows/import_target_defaults_test):

   Name                    Current Setting  Required  Description
   ----                    ---------------  --------  -----------
   CHOST                                    no        The local client address
   CPORT                                    no        The local client port
   ConnectTimeout          10               yes       Maximum number of seconds to establish a TCP connection
   ContextInformationFile                   no        The information file that contains context information
   DisablePayloadHandler   false            no        Disable the handler code for the selected payload
   EnableContextEncoding   false            no        Use transient context when encoding payloads
   Proxies                                  no        A proxy chain of format type:host:port[,type:host:port][...]
   SSL                     false            no        Negotiate SSL/TLS for outgoing connections
   SSLCipher                                no        String for SSL cipher - "DHE-RSA-AES256-SHA" or "ADH"
   SSLVerifyMode           PEER             no        SSL verification method (Accepted: CLIENT_ONCE, FAIL_IF_NO_PEER_CERT, NONE, PEER)
   SSLVersion              Auto             yes       Specify the version of SSL/TLS to be used (Auto, TLS and SSL23 are auto-negotiate) (Accepted: Auto, TLS, SSL23, SSL3, TLS1, TLS1.1, TLS1.2)
   VERBOSE                 false            no        Enable detailed status messages
   WORKSPACE                                no        Specify the workspace for this module
   WfsDelay                90               no        Additional delay when waiting for a session
``` 

## Expected behavior
Target DefaultOptions should be imported into the datastore when the module is initialized.

### PR DESCRIPTION
**Pull request by adfoster-r7**
Fixes https://github.com/rapid7/metasploit-framework/issues/12963

## Verification

List the steps needed to make sure this thing works

- [x] Run through the original issue's steps and ensure that `DisablePayloadHandler` is now set to true
- [x] Verify some the other modules have the same options / advanced options
- [x] Verify that there's no other impacted code paths, I'm thinking that `share_datastore` _could_ be impacted - but will need to confirm.

### CODE REVIEW

File: lib/msf/core/module/options.rb [hunk 1]
```diff
@@ -63,7 +61,6 @@ def register_evasion_options(options, owner = self.class)
   #
   def register_options(options, owner = self.class)
     self.options.add_options(options, owner)
-    self.datastore.import_options(self.options, 'self', true)
```
Comment (adfoster-r7) [inline lib/msf/core/module/options.rb:66]: I statically verified this, it seemed like `import_defaults(false)` already calls this line under the hood and it seemed good to remove

File: lib/msf/core/module/options.rb [hunk 2]
```diff
@@ -63,7 +61,6 @@ def register_evasion_options(options, owner = self.class)
...
     import_defaults(false)
```
Comment (adfoster-r7) [inline lib/msf/core/module/options.rb:64]: I statically verified this line deletion, it seemed like `import_defaults(false)` already calls this line under the hood and it seemed good to remove

https://github.com/rapid7/metasploit-framework/blob/d88d4d93296c34f3f336f4d4a7f29a963de225e9/lib/msf/core/module/data_store.rb#L16-L20

File: lib/msf/core/exploit.rb [hunk 3]
```diff
@@ -377,9 +377,6 @@ def initialize(info = {})
       self.active_timeout = info['Payload']['ActiveTimeout'].to_i
     end
 
-    # Initialize exploit datastore with target information
-    import_target_defaults
```
Comment (adfoster-r7) [inline lib/msf/core/exploit.rb:381]: Registering new options will now take into consideration the target defaults

File: modules/exploits/linux/http/apache_ofbiz_deserialiation.rb [hunk 4]
```diff
@@ -77,9 +77,6 @@ def initialize(info = {})
       Opt::RPORT(8443),
       OptString.new('TARGETURI', [true, 'Base path', '/'])
     ])
-
-    # XXX: https://github.com/rapid7/metasploit-framework/issues/12963
```
Comment (wvu-r7) [inline modules/exploits/linux/http/apache_ofbiz_deserialiation.rb:81]: Hey, I'm glad for `XXX` for once!

**Review by dwelch-r7 — APPROVED** [review]

**Comment by agalway-r7** [comment]
## Release Notes
The `DefaultOptions` of an exploit modules' targets are now automatically set when a target is chosen.

**Comment by pbarry-r7** [comment]
## Release Notes

Fixed a bug where the default options of a target were not being correctly set on initial module load/use.
